### ISSUE TITLE
Fix stack cleaning

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1003]
On Node.js 6 we're not cleaning all the unnecessary stack lines. Needs to be fixed in an external module: https://github.com/tapjs/stack-utils/issues/14#issuecomment-238026000

**Comment by sotojuan** [comment]
Does your recent `clean-stack` module not help with this?

**Comment by sindresorhus** [comment]
@sotojuan No, we're using another more advanced module in AVA. Should be very easy to fix in `stack-utils` though. Just need to support `/` in the stack path.

**Comment by LasaleFamine** [comment]
This is solved with 1.0.0 of `stack-utils`: [tapjs/stack-utils#14 (comment)](https://github.com/tapjs/stack-utils/issues/14#issuecomment-276881190).

**Comment by novemberborn** [comment]
@LasaleFamine thanks for noticing this!
