### ISSUE TITLE
TypeScript: Can't compile code accessing `context` in `beforeEach`

### ISSUE THREAD

**Issue by rhysd** [avajs/ava#1004]
## Description

I tried ava v0.16.0 in my project and it causes some compilation error with tsc v2.0.0.  When accessing to `context` in `beforeEach` or `afterEach` hook, 'context is not a property of `t`' error occurred.  I found below code in `types/make.js` so this may be intentional.

```js
if (!has('beforeEach') && !has('afterEach')) {
	type = 'Contextual' + type;
}
```

But I also found some test codes actually access to `context` in `beforeEach` hook.  [Sample code in README](https://github.com/avajs/ava/blob/adc823ecc9747b43d96da70d39cb7040997f8e85/readme.md#before--after-hooks) also does.  I couldn't find why above `!has('beforeEach') && !has('afterEach')` guard was added from any issues or commit histories.

### Test Source

Please save below code as `foo.ts`.

```typescript
import test from 'ava';

test.beforeEach(t => {
    t.context.foo = 42;
});
```

### Error Message & Stack Trace

Compilation error by `tsc` command.

```
foo.ts(4, 7): error TS2339: Property 'context' does not exist on type 'TestContext'.
```

### Config

Copy the relevant section from `package.json`: N/A

### Command-Line Arguments

```
tsc --target es6 --module commonjs foo.ts
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly: https://github.com/rhysd/YourFukurou

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

- OS X 10.11.5
- Node.js v6.2.1
- npm v3.10.4
- ava v0.16.0
- tsc v2.0.0

**Comment by sindresorhus** [comment]
// @ivogabe

**Comment by ivogabe** [comment]
@SamVerschueren I thought that `.context` shouldn't/couldn't be used with `beforeEach` and `afterEach`. Was I mistaken with `before` and `after`?

**Comment by SamVerschueren** [comment]
It should work in `beforeEach` and `afterEach`, not in `before` and `after`.

**Comment by ivogabe** [comment]
Then `if (!has('beforeEach') && !has('afterEach')) {` should be `if (!has('before') && !has('after')) {`

**Comment by rhysd** [comment]
`context` is a property to share some data between some test cases and hooks.  So I think it should be accessed in all hooks (`before`, `beforeEack`, ...).  At least until v0.15, I could access to `context` from all hooks.

**Comment by SamVerschueren** [comment]
From the docs

> Context sharing is not available to before and after hooks.

It was asked for multiple times. There is no valid use case why you want the context in before or after. Those functions apply to all the tests only once. If you want to setup some stuff in there, you should do it globally.

**Comment by rhysd** [comment]
@SamVerschueren 

Thank you for explanation.  I checked my code and I actually used `beforeEach` and `afterEach` hooks only. Regarding `before` and `after` hooks it was my misunderstanding.

So, as @ivogabe said, `(!has('before') && !has('after')` guard is proper.

**Comment by rhysd** [comment]
@SamVerschueren @sindresorhus Thank you :smile:
