### ISSUE TITLE
Ava output has missing peices

### ISSUE THREAD

**Issue by kennetpostigo** [avajs/ava#1006]
Hey,

I followed the instructions in the README.md and also ran the example tests and they run and work. I'm running Ava version `0.16.0`. However the output from Ava has like blank spots:

Output from passed test:
<img width="126" alt="screen shot 2016-08-16 at 2 18 13 pm" src="https://cloud.githubusercontent.com/assets/8888991/17710722/85b56d36-63bc-11e6-9c7d-aac9aad8644e.png">

Output from failed test:
<img width="1210" alt="screen shot 2016-08-16 at 2 18 29 pm" src="https://cloud.githubusercontent.com/assets/8888991/17710721/85b3a1cc-63bc-11e6-8e54-374875d8df93.png">

These tests are the same example tests from the README.md

They are missing the checkmarks and test names from what I notice. Any idea why this may be happening?

**Comment by sindresorhus** [comment]
By default, AVA shows a minimal output on success, but verbose failures. We feel there's no point in showing a lot of verbose info when everything worked. If you really want verbose output, run AVA with the verbose flag: `$ ava --verbose`.

**Comment by kennetpostigo** [comment]
@sindresorhus I'm not looking for the verbose output at all 😅
I'm wondering why this doesn't appear:
![screen shot 2016-08-16 at 3 44 13 pm](https://cloud.githubusercontent.com/assets/8888991/17713332/526214dc-63c8-11e6-9b37-092aa2dba2c5.png)

**Comment by sindresorhus** [comment]
@kennetpostigo That's the verbose output. Try `$ ava --verbose` and you'll see.

**Comment by kennetpostigo** [comment]
@sindresorhus hadn't realized that. Looking at the Readme I thought that was default ouput.

**Comment by sindresorhus** [comment]
Ah ok. Yes, that screenshot is misleading. I've removed it.
