### ISSUE TITLE
Disable power assert

### ISSUE THREAD

**Issue by kentcdodds** [avajs/ava#1017]
## Description

As amazing as [`power-assert`](https://npmjs.com/package/power-assert) is, it's constantly causing my team problems. Often it results in reeeeally weird behavior (for example, sometimes suddenly AVA thinks we have infinite tests and runs them like it's got a mind of its own until we kill the process). Often the issues involve JSX, enzyme wrappers, objects with circular references, and upcoming JS features.

Many of the problems that have come up with power-assert in the past have been fixed which is awesome, but it's still just too much magic for my team to stay productive and still causes us a great deal of grief. I love it when it works, but I just don't think that we can keep using it. We're seriously considering changing frameworks because of this (and some perf issues which I know are being worked on).

### Proposal

Expose a config to disable power-assert:

```json
{
  "ava": {
    "powerAssert": false
  }
}
```

Then [this](https://github.com/avajs/ava/blob/81ffd8db1fd68c24f4d54ceeef4397a56539002d/lib/babel-config.js#L78-L85):

```javascript
var defaultPlugins = lazy(function () {
	return [
		espowerPlugin(),
		require('babel-plugin-ava-throws-helper'),
		rewritePlugin(),
		require('babel-plugin-transform-runtime')
	];
});

function build(babelConfig, filePath, code) {
	// ...
	objectAssign(options, {
		inputSourceMap: sourceMap,
		filename: filePath,
		sourceMaps: true,
		ast: false
	});
	// ...
	options.plugins = (options.plugins || []).concat(defaultPlugins());
	// ...
}
```

Could be changed to this:

```javascript
var defaultPlugins = lazy(function (options) {
	return [
		options.powerAssert ? espowerPlugin() : null,
		require('babel-plugin-ava-throws-helper'),
		rewritePlugin(),
		require('babel-plugin-transform-runtime')
	].filter(plugin => !!plugin); // filter out null plugins
});

function build(babelConfig, filePath, code) {
	// ...
	objectAssign(options, {
		inputSourceMap: sourceMap,
		filename: filePath,
		sourceMaps: true,
		ast: false,
		powerAssert: true
	});
	// ...
	options.plugins = (options.plugins || []).concat(defaultPlugins(options));
	// ...
}
```

Here's a `diff`:

```diff
- var defaultPlugins = lazy(function () {
+ var defaultPlugins = lazy(function (options) {
	return [
- 		espowerPlugin()
+ 		options.powerAssert ? espowerPlugin() : null,
		require('babel-plugin-ava-throws-helper'),
		rewritePlugin(),
		require('babel-plugin-transform-runtime')
-   	]
+   	].filter(plugin => !!plugin); // filter out null plugins
});

function build(babelConfig, filePath, code) {
	// ...
	objectAssign(options, {
		inputSourceMap: sourceMap,
		filename: filePath,
		sourceMaps: true,
- 		ast: false
+ 		ast: false,
+ 		powerAssert: true
	});
	// ...
- 	options.plugins = (options.plugins || []).concat(defaultPlugins());
+ 	options.plugins = (options.plugins || []).concat(defaultPlugins(options));
	// ...
}
```

Without actually testing this, it seems to me like it would work. Thoughts? 💭

**Comment by xjamundx** [comment]
My personal favorite power-assert issue from last week was failing the same test over and over again <img width="1021" alt="screen shot 2016-08-17 at 2 44 19 pm" src="https://cloud.githubusercontent.com/assets/246143/17901336/cdc1bc46-6917-11e6-9d9e-8c210d9eba9f.png">

**Comment by jcama** [comment]
Hi! @kentcdodds @xjamundx  I'm working on a similiar test framework project. Wont to help me out? If so drop an email at jonnycasamillo@gmail.com. For others as well. Feel free to send an email!

**Comment by sindresorhus** [comment]
Makes sense to me. I've run into some problems with power-assert in the past too.

That doesn't mean you shouldn't report issues regarding power-assert, though. @xjamundx Can you open a separate issue about that?

**Comment by jfmengels** [comment]
I'd like to work on this. I want to get more accustomed to the AVA codebase.

**Comment by jfmengels** [comment]
Should this only be a setting available in the config, or also using the CLI?
If also in the CLI, what should the flag be named? `--no-power-assert`?

**Comment by kentcdodds** [comment]
Sounds good to me

**Comment by sindresorhus** [comment]
> If also in the CLI, what should the flag be named? --no-power-assert?

👍

**Comment by vikfroberg** [comment]
I'm not sure why, but I can't seem to turn of powerAssert. My assertions works just fine if I change the argument to anything but `t`.

`ava -s dist/test/lib/postgres.js --no-power-assert`

ava version: 0.17.0
node version: 4.4.0
