### ISSUE TITLE
Expose verboseness flag to tests/fixtures/helpers

### ISSUE THREAD

**Issue by eloquence** [avajs/ava#1018]
For reporting purposes, I would find it useful to be able to tell within my tests whether the test runner was invoked with --verbose. This would let me use a single flag to control verbosity of fixtures and helpers (such as progress reports). I can achieve this with a wrapper script or a separate variable, of course, but direct access from within tests would be more convenient and less error-prone.

Would you give consideration to a pull request to this effect, which would expose this variable through process.env or by other means? My apologies if there's already a way to do this; I looked at the CLI code and it looks like the flags aren't passed along for the ride.

**Comment by jfmengels** [comment]
Sounds to me like what [debug](https://www.npmjs.com/package/debug) offers you. Not behind a --verbose flag, but a process.env variable. Would that do the trick for you?

**Comment by eloquence** [comment]
Thanks for the response, @jfmengels! I do currently use the debug module for this. There's two (admittedly small) issues with this:

- It's behind a separate flag
- I consider these more progress updates than debug messages, and they're styled to be consistent with the default verbose test output.

It's not a big deal and if you see it as crufty or if there are other reasons not to let the tests see the status of this flag, feel free to close this. But if you think it could be helpful for some scenarios, I can prepare a small patch for it.

**Comment by jfmengels** [comment]
I'm not against this, but I think that using a process.env variable would simply do the trick in your case. 

```js
test('foo', t => {
  if (process.env.VERBOSE) {
    console.log('...');
  }
});
```

and run AVA using `VERBOSE=1 ava --versbose`
It does not come automatically with `--verbose`, but it should be fine unless you are developing an external library. You could do this if this gets rejected or while waiting for it to be implemented if approved.

**Comment by vdemedes** [comment]
I think we should proxy CLI flags to the `node` child processes, so that users could easily access them.

Tip: https://github.com/sindresorhus/has-flag.

**Comment by novemberborn** [comment]
This should be solved using environment variables. Especially once we support a programatic API (#1043) it's hard to reason about whether `--verbose` was passed or the calling code set the option. Environment variables mean that AVA does not have to be involved.
