### ISSUE TITLE
Feature: get names of all ava tests to be run

### ISSUE THREAD

**Issue by btford** [avajs/ava#1020]
## Description

I'm looking for some way to run ava (programmatically or via CLI) to just get a list of spec names, but without running them.

Some background: I'm working on adding tests to a legacy codebase, and I want to cover a combination of behaviors. It's very difficult to manually keep track of which behaviors I already have tests for, so I'm trying to automate it.

To do this, I might create an array with all the test names I ultimately want to have specs for:

```
const tests = [];
['Person', 'Unicorn', 'Dinosaur'].forEach(entity =>
  ['create', 'retrieve', 'update', 'delete'].forEach(action => 
    specs.push(\`A user can ${action} an ${entity}\`)
  )
);
```

Then, I want some way to compare the list of tests that I should have against the list of tests actually implemented.

It'd be great if I could get this metadata directly from ava like this:

```
$ ava --list-test-names --dry-run
A user can update a Unicorn
A user can retrieve a Person
...
```

Then in addition to code coverage, I can calculate a sort of "behavioral coverage" that shows that I have "2 out of 12 tests implemented."
## Relevant Links
- initial conversation on [twitter dot com](https://mobile.twitter.com/briantford/status/769324452672786432)

**Comment by novemberborn** [comment]
You could get this via `--verbose` or `--tap`. It does mean you have to run the tests, but it sounds like you're planning to give this result after a test run anyway.

Also there's `test.todo` which you could you use as a placeholder. The number of such tests is reported after a test run.
