### ISSUE TITLE
Directories named fixtures, helpers and node_modules are NOT always ignored.

### ISSUE THREAD

**Issue by gravitypersists** [avajs/ava#1026]
The main Readme states:

> Directories named fixtures, helpers and node_modules are *always* ignored.

however in package.json if you do:

```
"ava": {
    "files": "./assets/tests/**/*.js",
}
``` 

this is not true at all, ava will complain that these files have no tests. Ava does not complain when you use `"./assets/tests"`, though. Unsure if this is a clarification issue with the readme or if this is actually unintended.

version 0.16.0

**Comment by sotojuan** [comment]
Might just be an issue with the glob. `**/*` means everything as you know—AVA's file resolver might be getting overwritten by the results of that glob and not "re-ignoring" stuff. IMO this is something we should fix.

**Comment by sotojuan** [comment]
@gravitypersists, it turns out it's a glob issue and not an AVA one.

Try: `assets/tests/**/*.js` Should work.

See:

https://github.com/isaacs/minimatch/blob/master/test/patterns.js#L130-L131

**Comment by kevva** [comment]
Maybe we should take this into account in `ava-files` though?

**Comment by sotojuan** [comment]
Ha, right sorry. I mean, we need to do something about this. Maybe if we see `./` at the beginning of a blog we take it off? Might as well not have users worry.

**Comment by sotojuan** [comment]
Doing that ^ fixes this example.

**Comment by kevva** [comment]
I think we should add it to the globs instead. It's probably less prone to fail.
