### ISSUE TITLE
Fix tests on Node.js 6.5.0

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1027]
From https://github.com/avajs/ava/pull/1024#issuecomment-243609090. They passed on 6.4.0, but something changed.

**Comment by sotojuan** [comment]
So in the runner tests there's the "test types and titles" test, and for some reason the `beforeEach` and `after` are being set as `fn` Only happens with those two. Investigating!

**Comment by sotojuan** [comment]
Problem seems to be with the `fn-name` module.

**Comment by sotojuan** [comment]
This code:

```js
var fnName = require('fn-name')

var fn = function (a) {
  a.pass()
}

console.log(fnName(fn))
```

running in 6.4.0 logs out `null`.

In 6.5.0, it logs out `fn`.

**Comment by sotojuan** [comment]
...And further down...

6.5.0:

```js
var fn = function (a) {
  a.pass()
}

console.log(fn.name) // 'fn'
```

6.4.0:

```js
var fn = function (a) {
  a.pass()
}

console.log(fn.name) // ''
```

@sindresorhus So what should be done in `fn-name` to handle this? Unless the result is to just change the AVA tests to expect `fn for test` instead of `beforeEach for tests` 😅

**Comment by sindresorhus** [comment]
I wouldn't consider it a bug in `fn-name`. It's just reading the `.name` property off the function. It seems the V8 version in Node.js 6.5.0 got better at inferring the function name.

**Comment by sotojuan** [comment]
Ah, I meant the search led to there—`fn-name` seems to work as intended.

**Comment by sotojuan** [comment]
A quick way to fix this is to add a rule to the part of AVA's code that sets titles when they're `null` to also handle them the same way when they're `fn`. Just tested it and it works.
