### ISSUE TITLE
Watching doesn't work properly on Linux

### ISSUE THREAD

**Issue by dchambers** [avajs/ava#1030]
On my Linux laptop, `--watch` only re-runs your tests when you edit code that happens to be in the same directory as one of your tests. Is this maybe because [Inotify](https://en.wikipedia.org/wiki/Inotify) doesn't support recursive watch handles?

**Comment by dchambers** [comment]
On the flip-side, AVA tests are an order of magnitude faster (~2s instead of ~20s) on my Linux laptop (i5 x 4 @ 2.2Ghz \w 8GB RAM & SSD) than they are on my Mac laptop (i7 x 2 @ 2.2Ghz \w 8GB RAM & SSD) :smile:. I'm guessing this is either as result of me using Babel or because [Node’s `require` is dog slow](https://kev.inburke.com/kevin/node-require-is-dog-slow/), but this dramatic speed difference between platforms came as a surprise to me, so I thought I'd mention this too.

**Comment by novemberborn** [comment]
We're using [chokidar](https://github.com/paulmillr/chokidar), whose README does imply watching should work recursively. Does anybody else have experience with this?

**Comment by dchambers** [comment]
So I just now debugged this, and I noticed that chokidar was being asked to observe changes on these paths:

~~~
['package.json', '**/*.js', 'src/**/*.test.js']
~~~

So I tried changing the middle one to limit it to only watch my `src` directory like so:

~~~
['package.json', 'src/**/*.js', 'src/**/*.test.js']
~~~

and it started working! I was able to permanently effect this change by adding this to my `ava` config:

~~~
"source": [
  "src/**/*.js"
],
~~~

I've had experience with watching very large directories on Linux before, and depending on how the distro is configured you can easily run out of watch handles if you watch too many directories, so I'm guessing chokidar is swallowing errors about running out of handles so it just silently fails to report on some directories instead.

You need one watch handle per directory, and you can see how many handles you have available on your distro like this (for me it was set to `65536`):

~~~
cat /proc/sys/fs/inotify/max_user_watches
~~~ 

Hopefully that helps the next guy!

**Comment by novemberborn** [comment]
@dchambers interesting! We can definitely do better in reporting these issues, I've just opened #1071 for that.
