### ISSUE TITLE
Fixtures and helpers are not compiled via Babel

### ISSUE THREAD

**Issue by vdemedes** [avajs/ava#1037]
I've used default function parameters while testing code on Node.js v4 (which does not support them) and discovered that AVA does not compile helpers, fixtures and underscore-prefixed files (e.g. `_setup.js`).

I compile the library source via Babel and AVA takes care of test files, but using "next-gen" code in test helpers breaks the compatibility.

The solution to this would be to include `tests`, `fixtures` and `_*.js` files into precompilation, but still ignore those files (not treat them as tests).

**Comment by novemberborn** [comment]
See #720.
