### ISSUE TITLE
Reporter should support all Unicode strings

### ISSUE THREAD

**Issue by revelt** [avajs/ava#1039]
## Description

Let's make AVA emoji-friendly. Currently it's difficult to use AVA for testing libraries that perform string operations. Here, errors regarding strings containing emoji appear chopped off and often contain broken characters. Consider the most basic example:

### Test Source

```js
test.only('foo', t => {
  t.fail('🦄🐴🦄')
})
```

### Error Message & Stack Trace

Notice the broken symbol:

```
   1 failed


   1. foo
   🦄�
      Test.fn (test.js:508:5)
npm ERR! Test failed.  See above for more details
```

Since one emoji `.length` equals to two, second half of second emoji is cut off. That broken symbol is high-surrogate of second emoji.

### Config

```json
{
  "ava": {
    "tap": false
  }
}
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v5.11.1
darwin 15.6.0
ava 0.16.0
npm 3.10.7
```

**Comment by sotojuan** [comment]
Sounds great! Is there any library or resource I can look up to help with this?

**Comment by revelt** [comment]
I tend to solve string `.length` problem like [Sindre](https://github.com/sindresorhus/splice-string/blob/master/index.js) — convert the string to an array using `lodash.toarray`, then measure it using `Array.length` (or perform operations on that array, later `.join('')`-ing back 😊).

**Comment by sotojuan** [comment]
Cool, I'll give it a shot tonight : )

**Comment by sotojuan** [comment]
@revelt Can you check if this isn't an issue with your system? I'm on OS X El Capitan and have tested with Node 4, 5, and 6, iTerm 2 and Terminal and I get the following: 

<img width="660" alt="screen shot 2016-09-19 at 8 27 46 am" src="https://cloud.githubusercontent.com/assets/8217766/18633711/42d4a4a4-7e43-11e6-9811-702fe280fa03.png">

Seems right?

**Comment by revelt** [comment]
Good spot, it's HyperTerm, I can't recreate the issue on iTerm2 too... Let's close this issue, thanks for clearing this.
