### ISSUE TITLE
Fail to load .babelrc with babel-preset-latest

### ISSUE THREAD

**Issue by pastak** [avajs/ava#1042]
## Description

Fail to load `.babelrc` when it uses `babel-preset-latest` and sets `es2015` options.

### Test Source

```js
{ "presets": [
  ["latest", {
    "es2015": {
      "modules": false 
    }
  }]
] }
```

via https://babeljs.io/docs/plugins/preset-latest/

### Error Message & Stack Trace

```
TypeError: [BABEL] <JSFilePath> Invalid options type for foreign
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "babel": "inherit" 
  }
}
```

**Comment by novemberborn** [comment]
@pastak that error seems to come from Babel, not AVA.

**Comment by sindresorhus** [comment]
Closing for lack of response from OP.
