### ISSUE TITLE
Revisit programmatic API

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1043]
AVA exposes an API through `require('ava/api')`. It's what other Node.js programs should use (e.g. Gulp & Grunt, #345). Currently it's undocumented (#284).

Let's provide a reliable, documented, SemVer-compliant & public API.

Feature wise it should be possible to run individual tests, test files, and start watch mode, as well as interrupt test runs (#710). Integrations should be able to collect test results, both as they happen and as individual tests finish (see also #141).

Integrations should be able to use AVA configuration in `package.json` files without duplicating code from the CLI (#700).

This is blocked until AVA's internals settle further, so let's start by figuring out what we want out of this API. This won't be there for a 1.0 release.

**Comment by novemberborn** [comment]
While yes, we do want to support this, I don't think we need to keep this issue open. We'll get back to this eventually.

**Comment by novemberborn** [comment]
@MKRhere no. I think it's more likely we'll require AVA to be run in a child process, but allow you to load your own extensions into that process.

**Comment by MKRhere** [comment]
Thanks a lot for responding. I understand the reasons behind the decision, I think. I strongly needed an API-first framework, so I've built one in the meanwhile. It doesn't do parallelisation yet, of course :)

Thanks a lot! Overall a great job.
