### ISSUE TITLE
Thoughts on CLI flags

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1048]
Came across [this comment](https://github.com/avajs/ava/issues/782#issuecomment-217615776) from @jamestalmage:

> My feeling on options via `cli.js`: We should only add those where users would conceivably want to temporarily override the contents of their `package.json` config. Allowing different reporters on CI servers, running in `--serial` mode occasionally to debug, these are good examples.

I quite like this! Maybe it should be our "official" stance.

I think that'd mean `--require` has to go. On the other hand the `--source` flag may have to stay (as opposed to #937). We shouldn't have `--extension` either (#631).

Thoughts?

**Comment by sindresorhus** [comment]
@novemberborn I agree, but what other flags would we remove?

> On the other hand the --source flag may have to stay

Why?

**Comment by novemberborn** [comment]
> other flags would we remove?

Just `require` I think. Ideas for more?

>> On the other hand the --source flag may have to stay

> Why?

To restrict watch mode on the fly to a more specific pattern.

**Comment by jamestalmage** [comment]
> To restrict watch mode on the fly to a more specific pattern.

That seems unlikely to be truly useful. Why would you want to avoid rerunning when certain sources change, but not others?

**Comment by vdemedes** [comment]
I think `--require` and `--source` are the only ones that can safely go away. All the other ones are quite useful, don't think there's more room for removal.

**Comment by novemberborn** [comment]
Great! I've updated the relevant issues and opened #1069 to remove the `--require` flag.
