### ISSUE TITLE
Alternative approach to Babel transpilation

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1052]
I've been experimenting with creating a binary cache (#594) of the `babel-core` dependency: https://github.com/novemberborn/cached-module-loader. On my machine this leads to a 3x improvement in loading `babel-core`.

I think this would allow us to do Babel transpilation in the test workers themselves, including transpiling helpers (#720) and creating a faster `babel-register` without precompilation (#945).

I suspect it'll be easier to swap out the Babel transpiler for a TypeScript one, or make other customizations, if we can load it in the test workers rather than the main process. Performance on older Node.js versions (including v4) may not be as good as it is currently, however (#1051).

Curious to hear people's thought on this approach. Happy to provide more detail.

**Comment by vdemedes** [comment]
> I think this would allow us to do Babel transpilation in the test workers themselves

This would be just awesome!
