### ISSUE TITLE
Missing signature declaration for test with macro

### ISSUE THREAD

**Issue by Conaclos** [avajs/ava#1053]
## Description

The signature of test for macro is missing in the generated type declaration file.

For testers seeking for a workaround, see at the end of this issue

### Test Source

```js
import test from 'ava'
import {AssertContext} from 'ava'

function macro (t: AssertContext, input: any, expected: any) {
    t.is(input, expected)
}

test("macro", macro, 1, 1)

```

### Error Message & Stack Trace

```
8 test("macro", macro, 1, 1)

test/macro.test.ts(8,1): error TS2346: Supplied parameters do not match any signature of call target.
```

### Environment

I'm using Ava 0.16.0 with Typescript 2.1.x

## Temporary fix

As a workaround add this in your test file:
```
const testM = test as (l: string, m: (t: AssertContext, ...a: any[]) => void, ...a: any[]) => void
```
And use ```testM``` instead of ```test``` when you wish to use a macro.

**Comment by sindresorhus** [comment]
This is fixed in master and will be part of the next release. https://github.com/avajs/ava/commit/8816faf6bee675213c5bfe32f628a0a683708484
