### ISSUE TITLE
Consider switching deep equal module

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1055]
We currently use: https://github.com/sotojuan/not-so-shallow

I know this is something like the third time, but someone pointed out our current module [has a lot of issues](https://github.com/sotojuan/not-so-shallow/issues), and I'm personally not interested or have time to fix those, nor maintain a deep equal module.

I'd like to look into whether we could use [`lodash.isEqual`](https://lodash.com/docs/4.16.2#isEqual).

// @jdalton

**Comment by sotojuan** [comment]
Going to run some benchmarks just in case.

**Comment by jdalton** [comment]
Hiya!

Ok so `lodash.isEqual` supports comparing:
> arrays, array buffers, booleans, date objects, error objects, maps, numbers, Object objects, regexes, sets, strings, symbols, and typed arrays. Object objects are compared by their own, not inherited, enumerable properties. Functions and DOM nodes are not supported.

It is an equivalence method so somethings may be seen as equiv that aren't like `1` and `Object(1)`. The behavior can be customized with `lodash.isEqualWith`.
```js
function deepEqual(a, b) {
  return isEqualWith(a, b, function(a, b) {
    if (typeof a !== typeof b) {
      return false;
    }
  });
}
```

**Comment by sindresorhus** [comment]
I assume it does strict value equality checks?

Does it handle circular references?

I noticed it doesn't handle Node.js buffers? Would you able to add that?
See https://nodejs.org/api/buffer.html#buffer_buf_equals_otherbuffer

Would you be willing to ensure `lodash.isEqual` handles these issues: https://github.com/sotojuan/not-so-shallow/issues ?

-

> It is an equivalence method so somethings may be seen as equiv that aren't like 1 and Object(1) (legacy rules).

That's fine. They're not equal.

> The behavior can be customized with lodash.isEqualWith.

My goal is not having to do that. Would be better if we all agreed what deep equality entails.

**Comment by jdalton** [comment]
> I assume it does strict value equality checks?

For primitives yep. For objects it recursively crawls.

> Does it handle circular references?

Yes.

> I noticed it doesn't handle Node.js buffers? Would you able to add that?

Node buffers fall under the typed array support.

> Would you be willing to ensure `lodash.isEqual` handles these issues:
> https://github.com/sotojuan/not-so-shallow/issues ?

I believe it already handles those issues.

> My goal is not having to do that. Would be better if we all agreed what deep equality entails.

The method allows customization for the things you'd like to change and handles the rest. It's a pretty good mix.

**Comment by sindresorhus** [comment]
> Node buffers fall under the typed array support.

I would be explicit about that in the docs. While Node.js buffers inherit from TypedArray, they're not entirely the same thing and not everyone knows buffers inherit from TypedArray.

**Comment by jdalton** [comment]
> I would be explicit about that in the docs. While Node.js buffers inherit from TypedArray, they're not entirely the same thing and not everyone knows buffers inherit from TypedArray.

Cool. Explicit support is probably better anyways. I'll patch it up.

**Comment by vdemedes** [comment]
@sindresorhus  So I assume, until then we could use `lodash.isEqualWith` with an additional equality check just for buffers? It's pretty solid. Or do you want to keep searching for the module with the satisfying defaults?

**Comment by sindresorhus** [comment]
@vdemedes It's already part of a Lodash release, so we can just use `isEqual`. We should bring in the tests from https://github.com/sotojuan/not-so-shallow/tree/master/test just to make sure we didn't break anything. Wanna do a PR?

**Comment by vdemedes** [comment]
@sindresorhus Yes, definitely!
