### ISSUE TITLE
Expose options object to tests

### ISSUE THREAD

**Issue by mmkal** [avajs/ava#1057]
There may be a way of doing this that I haven't been able to find in the documentation or dicussions of other issues, but I think it'd be nice to be able to access the options object that's used by `Api`.

Specifically, I'd like to get at the `resolveTestsFrom` property. 
Here's an example of why. NB, this is TypeScript, and I'm using `"outDir": "js"` in tsconfig.json.

```TypeScript
import test from "ava";
import Thing from "../thing";
import fs = require("fs");
import glob = require("glob");

glob.sync("../../**/interesting*.txt").forEach(filename => {
    test(filename + " file should contain hello", t => {
        t.is(fs.readFileSync(filename, "utf8"), "hello");
    });
});
```

The problem is that ugly `../../` at the beginning of my glob. The number of `../`s I have there is coupled to what I set my output directory to in tsconfig.json. In the case of my real project, I end up having to use `../../../` to find what I'm looking for because of my directory structure.

My current workaround is to do this:
in `_ava-meta.ts`:
```TypeScript
const options: { resolveTestsFrom: string } = JSON.parse(process.argv[2]);
export const packageDir = options.resolveTestsFrom;
```
int `thingTest.ts`:
```TypeScript
import {packageDir} from "../_ava-meta";
...
glob.sync(packageDir + "/**/interesting*.txt");
```
But it's brittle and a bit of a hack.

My suggestion would be to just expose the options object so I can do:
```TypeScript
import test from "ava";
console.log(test.options.resolveTestsFrom); // c:\users\me\myproject
```

Or is there an already-existing nicer way I can get this value?

**Comment by vdemedes** [comment]
Perhaps you could pass this path as an environment variable to your tests:

```
$ TESTS_BASE='....' ava
```

and in your tests:

```js
const base = process.env.TESTS_BASE;
```

**Comment by mmkal** [comment]
I could - but that still feels like an unpleasant workaround, but it's probably even more obscure than the one I suggested, because it's not immediately obvious where that value actually comes from. Is there any reason the options object shouldn't be exposed?

**Comment by vdemedes** [comment]
Actually, this solution is straightforward and clear. `process.env` is a "standard" way to access environment variables in Node.js apps. AVA proxies all the environment variables you pass to its test processes, so it's totally fine to use that.

> Is there any reason the options object shouldn't be exposed?

We try not to add alternatives/aliases or functionality, that already exists in some other form. If we would, AVA could quickly become hard to maintain. That's why we are so picky what goes in the core and what does not. Each change has to be supported in future versions, so we try to avoid mistakes. Hope you understand ;)

Let me know if the `process.env` solution works for you.

**Comment by sindresorhus** [comment]
@mmkal It's seems like what you need is the path of the project root directory (where package.json resides)? If so, in https://github.com/avajs/ava/issues/32 we plan on changing `process.cwd()` to always be the project root path (where the tests are run from - package.json). When that's changed, you could simply use `process.cwd()`.

**Comment by mmkal** [comment]
@sindresorhus - great, using process.cwd() would be ideal. I'll close this one since #32 is covering my use case.
