### ISSUE TITLE
Asynchronous tests when stubbing with sinon

### ISSUE THREAD

**Issue by yamsellem** [avajs/ava#1066]
This is a copy of [this stackoverflow question](http://stackoverflow.com/questions/37900687/problems-with-ava-asynchronous-tests-when-stubbing-with-sinon) — I'm encountering the same issue, and don't know how to process.

``` javascript
import test from 'ava';
import sinon from 'sinon';

// Fake dependency code - this would be imported
const myDependency = {
    someMethod: () => {}
};

// Fake production code - this would be imported
function someCode() {
    return myDependency.someMethod()
        .then((response) => { return response; })
        .catch((error) => { throw error; });
}

// Test code

let sandbox;

test.beforeEach(() => {
    sandbox = sinon.sandbox.create();
});

test.afterEach.always(() => {
    sandbox.restore();
});

test('First async test', async (t) => {
    const fakeResponse = {};

    sandbox
    .stub(myDependency, 'someMethod')
    .returns(Promise.resolve(fakeResponse));

    const response = await someCode();

    t.is(response, fakeResponse);
});

test('Second async test', async (t) => {
    const fakeError = 'my fake error';

    sandbox
    .stub(myDependency, 'someMethod')
    .returns(Promise.reject(fakeError));

    const returnedError = await t.throws(someCode());

    t.is(returnedError, fakeError);
});
```

If you run either test alone, the test passes. But if you run these together, the setup for the test A runs, and then before it completes, the setup for test B runs and you get this error:

```
Second async test
   failed with "Attempted to wrap someMethod which is already wrapped"
```

The stackoverflow answer suggest to `test.serial`on every test — which works. But I'm wondering if there ain't no better way.

This may be totally on Sinon, but because I'm switching from Mocha to Ava, I start by asking it here.

Thanks a million for this :rocket: library.

**Comment by novemberborn** [comment]
@yamsellem I've expanded on the answer here: http://stackoverflow.com/questions/37900687/problems-with-ava-asynchronous-tests-when-stubbing-with-sinon#comment67089250_37900956

**Comment by vdemedes** [comment]
If the thing that's worrying you is writing `.serial` for each test, you could use `--serial` flag, which makes all your tests run serially. As people on SO said, it complicates things that you stub the same dependency in multiple tests, so I guess `--serial` is the only workaround.

**Comment by alathon** [comment]
The tests need to be serial because sinon is imported once for the process running the test file, and thus can't stub/mock/whichever the same method twice. This has little to do with AVA, and lots to do with the fact that the imports are global state within the process. 

If it were possible to run each *test* in its own process, instead of each file, then this would be possible as each process would have access to its own copy of sinon. Incidentally not a bad idea, as an option - but I'm not sure its possible without additional syntactic sugar for that specific case, which may be unwanted.

**Comment by sindresorhus** [comment]
> any interest in such a feature, if it should come up as a PR? (and is even feasible, haven't dug too deep into the worker/process stuff)

No, it's not something we want to explore right now.
Relevant issue where we should have this discussion: https://github.com/avajs/ava/issues/421
