### ISSUE TITLE
Inheritance of required file

### ISSUE THREAD

**Issue by yamsellem** [avajs/ava#1067]
Their is something weird / broker about external module inheritance.

In the following code, declare `TeaPot` class in the test and everything just works.
But uncomment the `const TeaPot` that required it from a path (after removing the TeaPot class definition) and it won't work anymore.

```javascript
const test = require('ava');

// replacing this
class TeaPot {
    get value() { return 12; }
}
// by that, broke the test
// const TeaPot = require('./teapot');

class Pot extends TeaPot {}

test('hot tea', t => {
    const pot = new Pot();
    t.is(pot.value, 12);
});
```

The error is `failed with "Class constructor TeaPot cannot be invoked without 'new'"`.
Ava 0.16.0.

**Comment by sindresorhus** [comment]
What exactly does `./teapot` contain?

**Comment by yamsellem** [comment]
Sorry about not been cristal clear. 
It's just the same class. 

```javascript
module.exports = 
class TeaPot {
    get value() { return 12; }
}
```

**Comment by sindresorhus** [comment]
I looked into this. Turns out you can't extend a native ES6 class with a ES5 type "class". Since your test is transpiled while `./teaport` is not, the test has a transpiled ES5 type class while `./teapot` has a real ES6 class.

See:

- http://stackoverflow.com/questions/32981988/class-constructors-cannot-be-invoked-without-new/32982156
- https://github.com/babel/babel/pull/3582 (fix)

**Comment by sindresorhus** [comment]
Yes, AVA transpiles with Babel by default. See: https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md

What Node.js versions do you run your test with?

**Comment by yamsellem** [comment]
@sindresorhus 6.3

**Comment by sindresorhus** [comment]
You could use this config then in your package.json:

```json
{
  "ava": {
    "babel": {
      "presets": ["es2015-node6"],
      "plugins": ["transform-async-to-generator"]
    }
  }
}
```

```
$ npm install --save-dev babel-preset-es2015-node6
```

**Comment by yamsellem** [comment]
@sindresorhus you're my hero :champagne: take care (_ps. ava is a wonder_)
