### ISSUE TITLE
Report Chokidar errors

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1071]
Watch mode uses [`chokidar`](https://github.com/paulmillr/chokidar) to detect changes. Chokidar can emit `error` events. Currently these are ignored. We should report them to the user instead as they may include clues as to why the watcher isn't detecting changes.

For example #1030 was due to Chokidar watching more files than the system allowed.

I'm thinking this should be part of the watcher's [debug output](https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#debugging), but that still takes some effort to find. Should it go in the verbose output instead?

We'll have to reproduce #1030 with this reporting enabled to see if Chokidar actually reports the errors and if it's informative enough.

**Comment by fabiospampinato** [comment]
Kind of tangential and I'm biased on this, but it might be worth exploring replacing chokidar with [watcher](https://github.com/fabiospampinato/watcher), which could be more refined for what this library needs (native watching under windows, much better handling of EMFILE errors, rename detection...).

**Comment by novemberborn** [comment]
This would be irrelevant if https://github.com/avajs/ava/pull/3123 is completed.
