### ISSUE TITLE
Simplify failure output

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1072]
With:

``` js
import test from 'ava';

test('returns true when happy', t => {
    throw new Error('unicorn');
});
```

It currently outputs:

```
❯ ava

  1 failed

  returns true when happy
  Error: unicorn
    Test.fn (test.js:5:8)
```

I think we should simplify it to:

```
❯ ava

  1 failed

  returns true when happy
  Error: unicorn
    test.js:5:8
```

So users can quickly see where the error came from. `Test.fn` doesn't have any value to the user.

This also applies to the verbose reporter (`$ ava --verbose`).
## 

We could also use https://github.com/sindresorhus/ansi-escapes#itermsetcwdpath to make the path clickable on iTerm.

**Comment by sotojuan** [comment]
I can take care of this as I've worked with the reporters before.

**Comment by ntwcklng** [comment]
Hi, would you mind if i tackle this issue? However, when i run this test i get the following outout:
```bash
❯ ./cli.js ava.test.js          

  1 failed

  returns true when happy
  Error: unicorn
    Test.t [as fn] (ava.test.js:4:11)
```
My output`Test.t [as fn] (ava.test.js:4:11)` vs. sindresorhus output: `Test.fn (test.js:5:8)`


I'm using
```
❯ node -v
v7.1.0
````
Maybe the output from the errorstack has changed in node v7?

Responsible for the output:
- https://github.com/avajs/ava/blob/master/lib/reporters/verbose.js#L112
- https://github.com/avajs/ava/blob/master/lib/reporters/mini.js#L184

**Comment by sotojuan** [comment]
Sure, no problem! Give it a try :D There must've been some changes in 7, I haven't looked yet.

[Here's](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md) the Node 7 changelog.

**Comment by sindresorhus** [comment]
@ntwcklng We always appreciate help, but @vdemedes is currently doing a big rewrite of the output, so this would conflict. I would ask you to wait until that work is done or try another issue :)

**Comment by ntwcklng** [comment]
Okay thanks, i will have a look.

**Comment by LasaleFamine** [comment]
Hi there, is this still valid?

**Comment by sindresorhus** [comment]
Only partly. The current output looks like:

```
❯ ava

  1 failed

  foo
  test.js:24

   23:
   24:   throw new Error('unicorn');
   25: });

  Error: unicorn

  Test.fn (test.js:24:8)
```

As you can see, the test file and line are shown twice. I think we could simplify it to not show the stack trace if it's only the test function. @avajs/core Thoughts?

**Comment by novemberborn** [comment]
> I think we could simplify it to not show the stack trace if it's only the test function. @avajs/core Thoughts?

👍

**Comment by LasaleFamine** [comment]
> Simplify it to not show the stack trace if it's only the test function.

Can I take this as the issue?

**Comment by sindresorhus** [comment]
@LasaleFamine Yes :)

**Comment by LasaleFamine** [comment]
I have a question. Is this related to `reporters`? The check should be made inside every `reporters`?

**Comment by sindresorhus** [comment]
@LasaleFamine Yes, the `mini` and `verbose` reporter, but not `tap`.

**Comment by LasaleFamine** [comment]
Well, I need some ideas to a good and "self-explained" check. I will make a PR soon though I'm still in WIP.
