### ISSUE TITLE
Typescript support in vs code

### ISSUE THREAD

**Issue by tonyeung** [avajs/ava#1079]
Docs say: 

> When you set module to commonjs in your tsconfig.json file, TypeScript will automatically find the type definitions for AVA. You should set target to es2015 to use promises and async functions.

I believe the docs can be a bit more explicit about what it takes to get things going.
Below is what I had to do in order to get a smoke test running with my preferred compiler options:

my original tsconfig.json

```
    "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        ...
    }
```

package.json

```
  "ava": {
    "files": [
      "app/**/*-test.js"
    ],
    "source": [
      "!app/**/*-test.js",
      "app/**/*.js"
    ],
    "match": [],
    "concurrency": 5,
    "failFast": true,
    "tap": true,
    "powerAssert": false
  },
  "devDependencies": {
    "ava": "^0.16.0",
    "babel-preset-es2015": "^6.16.0",
    "babel-register": "^6.16.3",
    ...
  }
```

bootstrap-test.ts

```
import test from 'ava';
import 'babel-register';
import { bootstrap } from './bootstrap';
test('bootstrap function should insert "hello world!" into container', (t) => {
    const result = bootstrap(null);
    t.false(result);
});
```

bootstrap.ts

```
export function bootstrap(container: HTMLElement) {
    if (container) { 
        container.innerText = "hello world!"; 
        return true;
    } 

    return false;
}
```

**Comment by sindresorhus** [comment]
@tonyeung Using AVA with TypeScript and using our type definition are different things. The former we have a [recipe](https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md) for. The latter should just work. I'm not really sure what you're asking for here?

**Comment by tonyeung** [comment]
@sindresorhus  right, I followed the recipe but it had different settings then I wanted. I'm just listing what I had to do in order to get it working for me. The impression I got from the recipe was that you had to have certain things in order for everything to work, like having the commonjs module format.

**Comment by sindresorhus** [comment]
I don't use TypeScript, so no idea, but maybe @SamVerschueren that wrote the recipe could chime in.

**Comment by tonyeung** [comment]
@sindresorhus just to be clear, i'm not saying the documentation is wrong. I'm just providing what I needed to do, in order to make it work for me.

**Comment by SamVerschueren** [comment]
@tonyeung Feel free to improve the recipe though. PR's are more then welcome on things like that :).
