### ISSUE TITLE
Test.todo typings may be wrong: error TS2345: Argument of type 'string' is not assignable to parameter of type 'ContextualTest'.

### ISSUE THREAD

**Issue by JustinDFuller** [avajs/ava#1081]
## Description

When using test.todo with Typescript, I pass in one string, like:

``` javascript
test.todo('Model should require attributes');
```

But I receive the error 

```
 error TS2345: Argument of type 'string' is not assignable to parameter of type 'ContextualTest'.
```

When I try to compile before I run.
### Test Source

``` js
import test from 'ava';

test.todo('Model should require attributes');
```
### Error Message & Stack Trace

```
λ npm run build

> nodemodulesystem@0.0.0 build C:\Users\Justin\nodemodulesystem
> tsc

src/module/controller/controller.spec.ts(3,11): error TS2345: Argument of type 'string' is not assignable to parameter of type 'ContextualTest'.
```
### Command-Line Arguments

I am not getting the error from this but I'll include it anyways..

```
nyc ava **/*.spec.js
```
## Relevant Links

https://github.com/JustinDFuller/NodeModuleSystem
## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v6.5.0
win32 10.0.14393
0.16.0
3.10.7
```

**Comment by unional** [comment]
Encounter the same issue. ava@0.17.0

**Comment by gajus** [comment]
The same issue is present with Flow type.

```
call of method `todo`: /dev/test/Plugin/#constructor.js:26
Function cannot be called on any member of intersection type
intersection: /dev/node_modules/ava/index.js.flow:159
Member 1:
function type: /dev/node_modules/ava/index.js.flow:160
Error:
string: /dev/test/Plugin/#constructor.js:26
This type is incompatible with the expected param type of
function type: /dev/node_modules/ava/index.js.flow:160
Member 2:
function type: /dev/node_modules/ava/index.js.flow:161
Error:
undefined (too few arguments, expected default/rest parameters): /dev/test/Plugin/#constructor.js:26
This type is incompatible with
function type: /dev/node_modules/ava/index.js.flow:161
Member 3:
function type: /dev/node_modules/ava/index.js.flow:162
Error:
string: /dev/test/Plugin/#constructor.js:26
This type is incompatible with
union: type application of polymorphic type: type `Macro` | array type: /dev/node_modules/ava/index.js.flow:162
Member 4:
function type: /dev/node_modules/ava/index.js.flow:163
Error:
undefined (too few arguments, expected default/rest parameters): /dev/test/Plugin/#constructor.js:26
This type is incompatible with
union: type application of polymorphic type: type `Macro` | array type: /dev/node_modules/ava/index.js.flow:163
```

**Comment by tugend** [comment]
I get the following behavior in typescript. I'd say this is clearly an error.

test.todo('my todo'); // compile error
Argument of type  'my todo' is not assignable to parameter of type 'Macros<ContextualTestContext>'.

test.todo('my todo', () => {}); // runtime error
​​TypeError: `todo` tests are not allowed to have an implementation. Use `test.skip()` for tests with an implementation.​​

**Comment by mightyiam** [comment]
@tugend the second, runtime, error seems correct. It is telling you that a test that has the `.todo` modifier must not have an implementation. An implementation is a function. In your case an empty arrow function.

**Comment by novemberborn** [comment]
@mightyiam their second example is go get around the bad typing, but that just causes a runtime error.

@tugend yes the typing is wrong. Perhaps you'd be interested in fixing it? The type definition is generated here: https://github.com/avajs/ava/blob/master/types/make.js

**Comment by novemberborn** [comment]
I had to make some changes to the generator script and I think I found the issue. See https://github.com/avajs/ava/pull/1197.

**Comment by tugend** [comment]
*happy face*, ^_^

**Comment by novemberborn** [comment]
Please try installing from `master`.
