### ISSUE TITLE
Got error when res.status test in API end point test

### ISSUE THREAD

**Issue by SuThaw** [avajs/ava#1086]
I used superagent as promised for api testing. I write as recommended. But when i compared statusCode, I got error.
```javascript
test.only('no email - should respond with errors', async t => {
    t.plan(1);    
    const res = await request(app)
        .post('/users')
        .send({email: 'ava@rocks.com', password: '123123'});
    
    t.is(res.status,200);

});
```
i got the following error

  users-create › no email - should respond with errors

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)
npm ERR! Test failed.  See above for more details.

**Comment by alathon** [comment]
I use superagent for testing with AVA, works fine for me. F.ex:

```javascript
test.beforeEach(async(t) => {
  t.context.agent = request.agent(app.listen())
})

test.serial('client signup: without companyId', async t => {
  const data = t.context.user
  let res

  res = await t.context.agent
    .post('/api/v2/auth/signup/client')
    .send(data)
  t.falsy(res.error)
  t.is(res.status, 200, 'Signup ok')

  res = await t.context.agent
    .post('/api/v2/auth/login')
    .send({email: data.email, password: data.password})
  t.truthy(res.error)
  t.is(res.status, 400)
  t.is(res.error.text, 'user not activated')
})
```

Where `request` is just an `import supertest` and `app` is a koa v2 application.

**Comment by SuThaw** [comment]
@alathon when i change the code as the following. It works. It doesn't work, when i directly use res.status  in the test. I don't know why.
```javascript
test.only('no email - should respond with errors', async t => {
    t.plan(1);    
    const res = await request(app)
        .post('/users')
        .send({email: 'ava@rocks.com', password: '123123'});
 
   const status = res.status;
    t.is(status,200);

});
```

**Comment by alathon** [comment]
@SuThaw Can you please provide a small example repository that shows this? i.e. a `package.json` file with the required dependencies, and a single test file to run.

**Comment by SuThaw** [comment]
@alathon  I finally know the source of error.  It is because of tap-reporter.
```javascript
{
  "name": "ava_tst",
  "version": "1.0.0",
  "description": "sample test with ava",
  "main": "index.js",
  "scripts": {
    "test": "node_modules/.bin/ava test/*.js  --tap | tap-spec"
  },
  "author": "SuThaw",
  "license": "ISC",
  "dependencies": {
    "express": "^4.14.0"
  },
  "devDependencies": {
    "ava": "^0.16.0",
    "tap-diff": "^0.1.1",
    "tap-nyan": "0.0.2",
    "tap-spec": "^4.1.1",
    "supertest": "^2.0.1"
  }
}
```
I cannot use the tap-spec as report. If I use tap-nyan or other, it is ok. But when i use tap-spec, i got error.   If you want to test it, here is the repo.Thanks for your time.

[](https://github.com/SuThaw/ava-test)
