### ISSUE TITLE
warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by guillaumevincent** [avajs/ava#1087]
## Description

My test print a warning, same as https://github.com/avajs/ava/issues/745

`(node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.`

### Test Source
tests are here : https://github.com/lesspass/cli/blob/master/test.js

I try to test my command line interface with 16 tests like this one : 

```
test('test space in password', async t => {
    const {stdout} = await execa('./cli.js', ['lesspass.com', 'contact@lesspass.com', 'my Master Password']);
    t.is(stdout, 'onAV7&uvEC2=');
});
```
Here the output for my tests : https://travis-ci.org/lesspass/cli/jobs/169243714

## Github

Here the github repository to reproduce the bug : https://github.com/lesspass/cli

## Environment

```
Node.js v4.6.0
linux 4.4.0-45-generic
ava version 0.16.0
npm version 3.10.8
```

I suppose this is because I exec 16 times in 16 processes. 
How can I avoid to raise this warning ?

**Comment by novemberborn** [comment]
Hi @guillaumevincent. This is a problem in [`execa`](https://github.com/sindresorhus/execa/), not AVA. Could you raise it there instead?

**Comment by guillaumevincent** [comment]
@novemberborn sure, thanks
