### ISSUE TITLE
Power-assert graph incomplete

### ISSUE THREAD

**Issue by jyboudreau** [avajs/ava#1090]
## Description

Power assertions with Ava outputs incomplete graphs.
### Test Source

``` js
test('A test', t =>{
    const arr = ['foo', 'bar'];
    t.true(arr.indexOf('moo') !== -1);
});
```
#### Expected assertion output

```
t.true(arr.indexOf('moo') !== -1)
         |   |              |   |
         |   |              |   -1
         |   -1             false
         ["foo","bar"]
```

> Note: This is the output you get from using power-assert directly in something like mocha.
#### Actual assertion output

```
t.true(arr.indexOf('moo') !== -1)
             |
             -1
```
### Config

Copy the relevant section from `package.json`:

``` json
{
  "ava": {
    "files": [
      "test.js"
    ]
  }
}
```
### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava
```
## Environment

Node.js: `v6.9.1`
OS: `darwin 15.6.0`
ava: `0.16.0`
yarn: `0.15.1` - Used for installing packages in my project
npm: `3.10.8`

**Comment by sindresorhus** [comment]
// @twada

**Comment by twada** [comment]
@jyboudreau @sindresorhus This is expected since AVA uses [succinct renderer](https://github.com/twada/power-assert-runtime/tree/master/packages/power-assert-renderer-succinct), not [the verbose one](https://github.com/twada/power-assert-runtime/tree/master/packages/power-assert-renderer-diagram) used by power-assert by default .

**Comment by jyboudreau** [comment]
The documentation of Ava definitively alludes that the output of assertions will be like what the verbose renderer outputs.

I would vote for switching the renderer to the verbose one.

**Comment by sindresorhus** [comment]
@twada I would definitely want to see the array value with the SuccinctRenderer. Just seeing `-1` isn't very useful.

@jyboudreau The verbose one is too verbose. We try to strike a balance. In this case, ours was too minimal.

**Comment by twada** [comment]
@sindresorhus Agreed. Let's getting SuccinctRenderer better.
@jyboudreau Thank you for reporting!

**Comment by novemberborn** [comment]
We now print all values through our formatter, so this issue is no longer applicable.
