### ISSUE TITLE
docs / feature request

### ISSUE THREAD

**Issue by ORESoftware** [avajs/ava#1097]
Mocha is far and away the most popular test runner in the Node.js ecosystem. And I think we all agree that is has some major problems. Unless I am missing something, is there a place that AVA formally discusses its advantages over Mocha (in the docs or elsewhere)? 

Perhaps it would be a good idea to do a full-fledged side-by-side comparison of the advantages that AVA has over Mocha.

I am going to start a shared list, but first let me know if some AVA maintainer is interested in formally criticizing Mocha.

**Comment by vdemedes** [comment]
I'm not a fan of these kinds of comparisons. I think AVA users should be attracted to it by its features, not by mentioning how bad alternatives are. No product is perfect, that is a fact. AVA has its pros & cons as well and it's perfectly normal. Every testing tool loses to each other in some way.

**Comment by ORESoftware** [comment]
well I am trying to convince my workplace to avoid mocha but having a hard
time finding verified info that shows the benefits even if I can spout them
off verbally

**Comment by sotojuan** [comment]
We're more than happy to tell you reasons to use AVA but it's not our place to tell you why Mocha is a bad choice—that's on you.

I have no experience with Mocha as I've always used tap, tape, or AVA and if I'm not the only one then we can't give you unbiased, informed opinions. [This](https://github.com/avajs/ava#why-not-mocha-tape-tap) is probably as much as you can get from us and the fact that Sindre cut his Pageres test duration by almost a third with AVA.

**Comment by vdemedes** [comment]
I think we sorted this out, closing.
