### ISSUE TITLE
Feature request: coverage reporting in watch mode

### ISSUE THREAD

**Issue by tuhoojabotti** [avajs/ava#1100]
## Description

While running ava in the watch mode (`--watch`) I would like to see an overview of the test coverage. If I'm writing tests I would like to see the coverage summary.

Maybe a way to invoke a command after successful test run? For example:

```
"ava": {
  "afterSuccess": "nyc report -r text"
}
```

### Command-Line Arguments

```
ava --watch
```

## Relevant Links

- https://github.com/istanbuljs/nyc
- https://github.com/avajs/ava/blob/master/docs/recipes/code-coverage.md

**Comment by novemberborn** [comment]
This would be interesting, yes. I think we'd need to integrate more closely with Istanbul though. That's still a ways off so I'm going to close this for now.

For now you could use [`nodemon`](http://nodemon.io/) to rerun your coverage tasks when code changes. Not ideal but better than manually rerunning it.

**Comment by tuhoojabotti** [comment]
@novemberborn Do you have a public road map somewhere? Would you be interested in a PR if we can work out the integration?

**Comment by novemberborn** [comment]
> Would you be interested in a PR if we can work out the integration?

Of course, but I don't think we can deal with integrating Istanbul for the foreseeable future.
