### ISSUE TITLE
Suggestion: Support t.throws(..., ..., message?: string | RegExp | undefined)

### ISSUE THREAD

**Issue by unional** [avajs/ava#1102]
ava version: 0.16.0

So that we can validate both the Error type and use RegExp to check for the message.

Currently, error type checking with RegExp is not possible: `t.throws(..., /filter err messge/)`

🌷

**Comment by sindresorhus** [comment]
`t.throws` is already too overloaded. We're not gonna make it even harder to use.

We're planning to simplify it over in https://github.com/avajs/ava/issues/1047. Could use your thoughts there ;)
