### ISSUE TITLE
Please release new version to make debugging possible

### ISSUE THREAD

**Issue by develar** [avajs/ava#1110]
#874 is not included into latest release. Could you please release new AVA version?

**Comment by sotojuan** [comment]
IIRC we're releasing one very soon. @novemberborn I think Sindre said he was going to be busy, do you think we can do a release soon?

**Comment by sindresorhus** [comment]
I was planning to do it today actually, but didn't have much computer time. I've been a bit strapped for time lately. Will do a new release tomorrow.

**Comment by sindresorhus** [comment]
Done: https://github.com/avajs/ava/releases/tag/v0.17.0

**Comment by mightyiam** [comment]
Thank you!

**Comment by masaeedu** [comment]
@sindresorhus Might it be a good idea to publish a continuous release on npm? I'm in the same boat, been waiting for a committed feature since August.

**Comment by sindresorhus** [comment]
@masaeedu Nothing is stopping you from using the master branch if you need to: `$ npm i avajs/ava`. We do releases when it makes sense.
