### ISSUE TITLE
Document how to debug with Node.js debugger/Chrome DevTools/etc.

### ISSUE THREAD

**Issue by mightyiam** [avajs/ava#1112]
Until we have a seamless debugging experience (perhaps see #929), it would be great to have instructions on how to use current debuggers like Chrome DevTools and the Node.js debugger with Ava.

The only place I've seen such instructions is where they were given to me [in an issue comment](https://github.com/avajs/ava/pull/874#issuecomment-261063096).

Would a pull-request for this be welcomed?

**Comment by sindresorhus** [comment]
Yes, a pull request would be lovely 😁

Title suggestion: `Debugging tests in Chrome DevTools` (filename: `debugging-tests.md`)

Could be a recipe: https://github.com/avajs/ava/tree/master/docs/recipes

(Make sure to also add it to https://github.com/avajs/ava#recipes)
