### ISSUE TITLE
ava 0.17.0 with FlowType 0.35.0 results in type-ambiguity errors

### ISSUE THREAD

**Issue by jokeyrhyme** [avajs/ava#1114]
## Description

Trying to update a project to use ava 0.17.0

For what seem like pretty standard-looking ava tests to me (as far as I know), FlowType is getting all up in my face about some ambiguity relating to the new types that ava declares. I am obviously quite scandalised by all this. Oh my!

### Test Source

This is the test code in question:

```js
test('A, A->B, B->C, BC->end', (t) => {
  const tasks = [
    { fn: noop, id: 'a', label: 'a', requires: [ 'B', 'C' ] },
    { fn: noop, id: 'b', label: 'b', provides: [ 'C' ], requires: [ 'B' ] },
    { fn: noop, id: 'c', label: 'c', provides: [ 'B' ], requires: [ 'A' ] },
    { fn: noop, id: 'd', label: 'd', provides: [ 'A' ] }
  ]
  t.notThrows(() => tasks.sort(compareByMetadata))
  const ids = tasks.map((task) => task.id)
  t.deepEqual(ids, [ 'd', 'c', 'b', 'a' ])
})
```

### Error Message & Stack Trace

When I run `flow_check`, I get 23 errors that are all very similar, like this:

```
test/sort-tasks.js:63
 63: test('A, A->B, B->C, BC->end', (t) => {
     ^ function call. Could not decide which case to select
201: declare module.exports: {
                             ^ callable object type. See: node_modules/ava/index.js.flow:201
  Case 2 may work:
  203: 	(name: string, run: ContextualTest): void;
       	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See: node_modules/ava/index.js.flow:203
  But if it doesn't, case 4 looks promising too:
  205: 	(name: string, run: Macros<ContextualTestContext>, ...args: Array<any>): void;
       	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See: node_modules/ava/index.js.flow:205
  Please provide additional annotation(s) to determine whether case 2 works (or consider merging it with case 4):
   63: test('A, A->B, B->C, BC->end', (t) => {
                                            ^ return
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {}
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
nyc ava
```

## Relevant Links

- https://github.com/jokeyrhyme/node-init.js

## Environment

```
Node.js v7.1.0
darwin 16.3.0
ava 0.17.0
npm 4.0.2
```

**Comment by sindresorhus** [comment]
@thejameskyle halp

**Comment by jokeyrhyme** [comment]
@sindresorhus that kitten slays me every time. So cute! Your participation in any GitHub conversation is a welcome presence. :D

**Comment by jfmengels** [comment]
I am getting the same error and can't seem to find a solution to it (except removing the macro possibility...) :thinking:

**Comment by jokeyrhyme** [comment]
I did get this working by explicitly annotating the types, something like this:

```js
/* :: import type { ContextualTest } from 'ava' */
test('my test', (t) => { t.pass('yay') } /* : ContextualTest */)
```

But I don't want to have to do this for every single test.

Another interim solution would be to tell FlowType to ignore ava. /shrug

**Comment by jokeyrhyme** [comment]
Just FYI: I'm having this issue with FlowType 0.36.0, too.

**Comment by mymattcarroll** [comment]
Another FYI: Having the same issue with `flow-bin@0.37.0`

**Comment by jokeyrhyme** [comment]
Oooo, nice work! Yay! <3

**Comment by btipling** [comment]
Is this released yet? I still get this problem.

**Comment by jokeyrhyme** [comment]
@btipling most recent release looks like [0.17.0](https://github.com/avajs/ava/releases/tag/v0.17.0) 2016-11-17, whilst this was only merged 2016-12-25
