### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by seacloud9** [avajs/ava#1118]
node:v6.6.0 

`.babelrc` configuration:

```json
{
 "presets": [  "es2015", "stage-3", "react-native"],
  "ignore": false,
  "env": {
    "development": {
      "sourceMaps": "inline"
    }
  }
}
```

`package.json`

```json
"devDependencies": {
    "ava": "^0.17.0",
    "babel-cli": "^6.18.0",
    "babel-eslint": "^7.1.1",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-3": "^6.17.0",
    "babel-register": "^6.18.0",
    "enzyme": "^2.6.0",
    "flow-bin": "^0.33.0",
    "ghooks": "^1.3.2",
    "mockery": "^1.7.0",
    "nyc": "^8.1.0",
    "react-addons-test-utils": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-native-mock": "^0.2.7",
    "reactotron-apisauce": "^1.3.0",
    "reactotron-react-native": "^1.3.0",
    "reactotron-redux": "^1.3.1",
    "snazzy": "^5.0.0",
    "standard-flow": "^1.0.0"
  },
"ava": {
    "files": [
      "Tests/**/*.js",
      "!Tests/Setup.js"
    ],
    "require": [
      "babel-register",
      "babel-polyfill",
      "react-native-mock/mock",
      "./Tests/Setup"
    ],
    "babel": "inherit"
  }
```

All tests pass when this https://github.com/xotahal/react-native-material-ui  I have read the numerous issues about this type of issue on your github repo.  Is there something you can see that I am missing?  I have also attempted to clear the cache as well. I do not know why adding the above repo would break my tests.  Any assistance on this issue would be greatly appreciated thanks.

**Comment by novemberborn** [comment]
@seacloud9 how are you adding that repository? I suspect it only distributes code using ES2015 module syntax, but if you install it into `node_modules` then `babel-register` won't transpile it. You'll need to configure Babel so it transpiles that particular dependency as well as your code, I suppose by tweaking the [`only` option](https://babeljs.io/docs/usage/options/).

**Comment by yuriy-yarosh** [comment]
Nah, `once` will not work properly, `ignore: false` is not a good choice because transpiling any `node_modules` non ES6 stuff will cause an error.

I'm initializing my `babel-register` like so nowadays.
```
const packageJson = require('../package.json');

require('babel-register')({
  // eslint-disable-next-line
  ignore: `/node_modules/!(${Object.keys(packageJson.dependencies).join('|')})/**/*`
});
```

Please keep in mind that `babel-register` will go for .babelrc config, or embedded `package.json` babel config, but will completely ignore ava's babel config. So, `ava: { "babel": "inherit" }` is a way to go 99% of the time.
