### ISSUE TITLE
t.throws() ignores error parameter for rejected promise

### ISSUE THREAD

**Issue by dchowitz** [avajs/ava#1119]
## Description

According to the documentation for [`.throws(function|promise, [error, [message]])`](https://github.com/avajs/ava#throwsfunctionpromise-error-message) the error parameter should be taken into account and compared or matched with the rejection reason (error message) of a promise. Unless I got the API totally wrong, this is not the case.

### Test Source

```js
// this should fail, but doesn't
test('error message of rejected promise doesn''t match expected message)', t => {
  t.throws(Promise.reject(new Error('foo'), 'bar'));
});

// this should fail, but doesn't
test('error message of rejected promise doesn''t match expected regex)', t => {
  t.throws(Promise.reject(new Error('foo'), /bar/));
});
```

## Environment

Node.js v7.1.0
darwin 16.1.0
npm 3.10.9
ava 0.17.0

**Comment by sindresorhus** [comment]
You have your parens wrong:

```diff
-t.throws(Promise.reject(new Error('foo'), 'bar'));
+t.throws(Promise.reject(new Error('foo')), 'bar');
```

**Comment by dchowitz** [comment]
Ups, sorry. Stupid me ;-)
