### ISSUE TITLE
t.throws() returns promise instead of promise's rejection reason

### ISSUE THREAD

**Issue by dchowitz** [avajs/ava#1120]
## Description

According to the documentation for [`.throws(function|promise, [error, [message]])`](https://github.com/avajs/ava#throwsfunctionpromise-error-message) the method should return the rejection reason of promise, instead the promise itself is returned.

### Test Source

```js
test('throws(promise) returns promise', t => {
  var result = t.throws(Promise.reject(new Error('foo')));
  t.is(typeof result.then, 'function');
});

// I've expected this should work, but it fails, since message is undefined
test('rejection reason is foo', t => {
  const error = t.throws(Promise.reject(new Error('foo')));
  t.is(error.message, 'foo');
});
```

## Environment

Node.js v7.1.0
darwin 16.1.0
npm 3.10.9
ava 0.17.0

**Comment by sindresorhus** [comment]
Thanks for reporting. It's a documentation bug. It should say that it returns a promise for the rejection reason. I'll fix that up shortly.

You need to await it:

```js
test('rejection reason is foo', async t => {
	const error = await t.throws(Promise.reject(new Error('foo')));
	t.is(error.message, 'foo');
});
```

That being said. We're planning a better interface for the `throws` assertion: https://github.com/avajs/ava/issues/1047 (feedback welcome)

**Comment by dchowitz** [comment]
Understood. Thanks for the quick reply and clarification!
