### ISSUE TITLE
`t.deepEqual` seems to ignore symbol key properties

### ISSUE THREAD

**Issue by mightyiam** [avajs/ava#1121]
## Description

`t.deepEqual` is affected by [upstream lodash issue](https://github.com/lodash/lodash/issues/2840). It means that

```js
t.deepEqual({[Symbol()]: undefined}, {})
// true
```

## Relevant Links

- [upstream lodash issue](https://github.com/lodash/lodash/issues/2840)
- https://bugzilla.mozilla.org/show_bug.cgi?id=1318933
- [`Object.getOwnPropertySymbols`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols)

**Comment by mightyiam** [comment]
Upstream [was fixed in less than two hours](https://github.com/lodash/lodash/commit/fd4808147d762ba40299bc67b5ae3807f20d6145) after reported :tada:
I wonder whether I should even ask for a release.

**Comment by vdemedes** [comment]
Since the `lodash.isEqual` is fixed now, we just need to update the dependency. Thanks for reporting!

**Comment by jdalton** [comment]
I haven't cut a release yet.

**Comment by vdemedes** [comment]
@jdalton Thanks for the note! We'll keep watching and update when it's ready.

**Comment by mightyiam** [comment]
@jdalton please :smile_cat:

**Comment by jdalton** [comment]
Ah yep, will do. Look for it some time on the 7th.
