### ISSUE TITLE
A way to disable progress indicator and colors on Docker Machine SSH 

### ISSUE THREAD

**Issue by pocesar** [avajs/ava#1127]
## Description

I'm using Docker Machine in Windows, and it uses a dumb terminal, with no colors and no progress capabilities. the reports are really hard to read. FWIW, I'm running tests using docker-compose for microservices using the real microservice architecture emulated using Docker

It seems that the `--no-color`  isn't doing anything

![ava](https://cloud.githubusercontent.com/assets/461084/20553371/4c2a378c-b13b-11e6-98ea-1ca7426085fc.png)

although I found that https://gist.github.com/ikasty/ae76beb34be3d12b66947ebf0872602b works pretty well (if you have `cat` for windows)

### Command-Line Arguments

```
ava --no-color
```

## Environment

```
Node.js v6.9.1
win32 10.0.14393
ava 0.17
npm 4.0.2
```

**Comment by sindresorhus** [comment]
See: https://github.com/avajs/ava/pull/1104

**Comment by pocesar** [comment]
oh I assumed it was already implemented, most colorized-by-default libraries comes with `--no-color`

**Comment by novemberborn** [comment]
@pocesar going to close this, looks like you have a workaround, and #1104 should fix any remaining issues.
