### ISSUE TITLE
Recommend Yarn for installation

### ISSUE THREAD

**Issue by vdemedes** [avajs/ava#1129]
In discussion regarding how to decrease installation time, @sindresorhus suggested recommending Yarn as a temporary solution for this problem. Installing AVA with Yarn is a great experience, so we might as well recommend it officially.

This involves putting a simple note in readme under [installation](https://github.com/avajs/ava#add-ava-to-your-project) section. Don't forget to link to Yarn too ;)

**Comment by fankee** [comment]
I looked into it, and installed ava using yarn. Can I take up this issue?

**Comment by sindresorhus** [comment]
@fankee There's already an open pull request for this unfortunately: https://github.com/avajs/ava/issues/1130
