### ISSUE TITLE
Request: ordered results option

### ISSUE THREAD

**Issue by mightyiam** [avajs/ava#1131]
I often like to see the test results in serial order, when I'm developing. So I run with `--serial`.
Yet, I don't care that they *run* serially—only that they show up in the serial order.

Perhaps an option for running normally and displaying serially? `--ordered-results` or so?

**Comment by sindresorhus** [comment]
But then you wouldn't see the results until after they're all done. I don't think that's a very good UX.

**Comment by mightyiam** [comment]
Yes, I realize that. Well, at least I'd have this choice. And it will be better than `--serial` because the run will finish x times faster.

**Comment by mightyiam** [comment]
Another reason for this is that in CI I use `--verbose` so that I could review the test output (computed test names and such), and I almost always prefer to see the results ordered, because it obviously easier to read that way.

**Comment by novemberborn** [comment]
> I often like to see the test results in serial order, when I'm developing.

Could you elaborate on why?

**Comment by mightyiam** [comment]
Seeing an ordered set of test names gives me a familiar feeling. I see the names of my tests and I see that they're passing. I can recognize my tests much better when they are in order. Really, not a big thing. I've also found myself not using `--verbose` lately, in development. The number of tests was enough.
