### ISSUE TITLE
Show clear indicator in the output when `.only()` is used

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1135]
It's easy to forget and end up not running the rest of the tests before pushing changes.

---

Similar to https://github.com/avajs/ava/issues/1134.

**Comment by tjbenton** [comment]
This happened to me yesterday

**Comment by sindresorhus** [comment]
@tjbenton I would recommend using our [ESLint plugin](https://github.com/avajs/eslint-plugin-ava), which would have caught that and many other things.

**Comment by ThomasBem** [comment]
I have made a PR that fixes #1134 in -> #1160 and since this is kind of similar I would like to take a stab at this too.

**Comment by sindresorhus** [comment]
@ThomasBem Go for it! 😄

**Comment by ThomasBem** [comment]
After looking at the code its really easy to get this to print out a warning similar to what was done for  the #1134 issue in the #1160 PR. 

I was thinking about changing the logic around counting tests when in .only / exclusive mode. I did some quick testing and I could make it at least count all the tests in files that does **NOT** contain any .only tests.

This would look something like this:

If all test files have at least one .only test in them, it logs this:
''There are tests with the .only() modifier in use. All other tests have been skipped''

If there are additional test files that do not contain any .only tests, it logs this:
"There are tests with the .only() modifier in use. At least', _remainingTests_, 'tests were not run."

remainingTests would then be the number of tests in the files without exclusive tests in them.

Any thoughts around this?

**Comment by mightyiam** [comment]
Perhaps instead of
"There are tests with the .only() modifier in use"
be it
"The .only() modifier is used in some tests"

**Comment by ThomasBem** [comment]
I agree, that wording is much better. 

Any thoughts regarding if there is any point to adding additional details around a number of tests skipped?
