### ISSUE TITLE
Feature request: add 'silent' option

### ISSUE THREAD

**Issue by Hurtak** [avajs/ava#1144]
## Description

Feature request to add new option flag to produce more silent output.
When silent flag would be turned on, it would not print anything to `stdout` in case of tests passing.

Use case:
- people are usually only interested when tests fail
- when using with gulp, output is unnecessarily verbose (takes 5 lines instead of gulps regular 2)

**Comment by sotojuan** [comment]
@avajs/core What do we think of this? It sounds interesting.

**Comment by vadimdemedes** [comment]
I don't think this is going to be helpful, since it's basically what mini reporter does. The default output is as minimal as it could get, I think.

> people are usually only interested when tests fail

Mini reporter only shows failed tests and exceptions too.

> when using with gulp, output is unnecessarily verbose (takes 5 lines instead of gulps regular 2)

I don't use gulp anymore, so I don't know what you mean here. Could you paste a screenshot?

**Comment by Hurtak** [comment]
It looks like this

```
[20:10:39] Starting 'test'...
[20:10:42] gulp-ava:

  8 passed


[20:10:42] Finished 'test' after 2.67 s
```

What I would prefer in case of no errors
```
[20:10:39] Starting 'test'...
[20:10:42] Finished 'test' after 2.67 s
```

**Comment by vadimdemedes** [comment]
I think this change would better belong to gulp-ava or maybe even a layer on top of it. The idea is to hide all output if exit code is zero (all tests are passing). What do you think?
