### ISSUE TITLE
t.throw flow type check is giving a false-positive (Callable signature not found in)

### ISSUE THREAD

**Issue by gajus** [avajs/ava#1148]
## Description

I am getting an "Callable signature not found in" when using `t.throws`.

The type error originates in the `node_modules/ava/index.js.flow` definition.

This could be simply me misunderstanding what the error is saying.

I'd expect Flow to pickup:

```js
throws(value: Promise<mixed>, error?: ErrorValidator, message?: string): Promise<mixed>;
```

annotation and ignore:

```js
throws(value: () => void, error?: ErrorValidator, message?: string): mixed;
```

I even explicitly cast the result to `Promise<void>`.

If I remove the `Promise<void>` cast, I am getting a different error, https://gist.github.com/gajus/5c42f0262874a2bae7842691eea28a60#file-ava-flow-sh-L2.

### Test Source

```js
test('timesout after 60 seconds', async (t): Promise<void> => {
  const {
    document
  } = createDocument();

  global.document = document;

  const result: Promise<void> = loadScript('http://dailymail.co.uk/');

  clock.tick(6e4 + 1);

  t.throws(result, 'Script loading time has exceeded the maximum configured time limit.');
});
```

### Error Message & Stack Trace

```js
$ flow
node_modules/ava/index.js.flow:71
 71: 	throws(value: () => void, error?: ErrorValidator, message?: string): mixed;
     	              ^^^^^^^^^^ function type. Callable signature not found in
 94:   t.throws(result, 'Script loading time has exceeded the maximum configured time limit.');
                ^^^^^^ Promise. See: test/utilities/loadScript.js:94


Found 1 error
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "babel": {
      "plugins": [
        "transform-flow-strip-types",
        "transform-async-to-generator",
        "transform-es2015-modules-commonjs"
      ]
    },
    "require": [
      "babel-register"
    ]
  }
}
```

### Command-Line Arguments

```
ava
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v7.2.1
darwin 16.1.0
0.17.0
3.10.10
```

**Comment by jamestalmage** [comment]
pinging @thejameskyle

**Comment by gajus** [comment]
Can this be marked as a bug?

I am not sure how to fix it... I would raise a PR otherwise.

It is breaking our integration tests. Annoyingly, I cannot even use `FlowFixMe` comment because it then throws error in ava definition. Therefore, we had to comment out async tests just to make Flow stop complaining about these assertions.

**Comment by gajus** [comment]
@leebyron Could you have a look at this issue please?

(Since you have tackled a similar issue here https://github.com/avajs/ava/pull/1164.)

**Comment by leebyron** [comment]
A simpler repro case is simply:

```
t.throws(Promise.reject(new Error()))
```

Which yields:

```
index.js.flow:61
 61: 	throws(value: () => void, error?: ErrorValidator, message?: string): mixed;
     	              ^^^^^^^^^^ function type. Callable signature not found in
 13:   t.throws(Promise.reject(new Error()))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Promise. See: test.js.flow:13
```
