### ISSUE TITLE
t.notThrows() gives no info on thrown error in case an error is thrown

### ISSUE THREAD

**Issue by justin-calleja** [avajs/ava#1150]
## Description

I have yet to make a test which uses `t.notThrows()` pass. Is it by design to not get any info on the thrown error when `t.notThrows()` actually errors out? All I get is:

`Got unwanted exception..`

I would like to see the stack trace.

Currently, I'm expecting the code to fail with a ` SequelizeUniqueConstraintError: Validation error` error. But since I'm not seeing anything other than `Got unwanted exception..`, I cannot verify this. Later on, after fixing this, if the test fails again, I would like to see the stack trace to see if it's still because of the constraint violation.

### Test Source

```js
  let [transaction, onSuccess] = await adapter.setupTransaction();
  // fails with "Got unwanted exception..". 
  await t.notThrows(Promise.all(G.deltas.map(delta => {
    return adapter.addContentObjectDelta(G.co1.getContentObjectId(), delta, {}, { transaction });
  })));
  await onSuccess();
```

### Error Message & Stack Trace

```
AssertionError: Got unwanted exception..
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "require": [
      "babel-register",
      "babel-polyfill"
    ],
    "babel": "inherit",
    "files": [
      "test/**/*.test.js"
    ],
    "failFast": true
  },
}
```

### Command-Line Arguments

```
ava --serial
```

`--verbose` does not help.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v6.3.1
darwin 15.4.0
ava: 0.17.0
npm: 3.10.3
```

**Comment by sindresorhus** [comment]
Yes, that's pretty bad UX. For this assertion we're using the built-in `assert` module, which obviously isn't very good. We plan on rewriting the throws/notThrows assertions: https://github.com/avajs/ava/issues/1047

**Comment by justin-calleja** [comment]
Ok thanks @sindresorhus
