### ISSUE TITLE
import relative path issue

### ISSUE THREAD

**Issue by alivedise** [avajs/ava#1153]
Not sure if this is asked because I can't find out the key of this problem accurately.
Here is a repo to reproduce the issue, https://github.com/alivedise/react-todo

## Problem description ##
* Tests are living in test/*.js
* a.test.js is importing Module 'App' from 'src'
* 'App' is importing 'MyModule' which is living in the same directory of App.

## Error output ###
After running <code>npm test</code>
```shell
> todo@0.1.0 test /Users/alive/Projects/todo
> cross-env NODE_ENV=test ava

module.js:327
    throw err;
    ^

Error: Cannot find module 'MyComponent'
```

I think the problem is coming from the path, and here is my currently workaround:

```js
// test/test-setup.js
var path = require('path');
var localModulesDir = path.resolve(__dirname, '..');
var anotherDirToCheck = path.resolve(__dirname, '../src');

var a = require("babel-core/register")({
       	resolveModuleSource: require('babel-resolver')(localModulesDir, anotherDirToCheck)
});
```

## My question ##
Is there a more clever way to do this? It seems stupid because the path works just well while not running the test, but while importing it in test, need to add this kind of hack...
If not, do we need to add this in the documentation?

**Comment by mightyiam** [comment]
[This line](https://github.com/alivedise/react-todo/blob/30b985fe6dad12232de35394768a21a01955dab2/src/App.js#L4) should be:
```js
import MyComponent from './MyComponent';
```
I would try that.
