### ISSUE TITLE
Unexpected token function, when use async in Node 7.2

### ISSUE THREAD

**Issue by eric7578** [avajs/ava#1161]
In my case, I try to run without babel, so I use node **v7.2.0**
in my source code:

```
exports.create = async function (mail, password) {
...
}
```

But I got the following error

```
/Volumes/HD/projects/stores/mailIdentity.js:3
exports.create = async function (mail, password) {
                       ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
```

**Comment by sindresorhus** [comment]
The common mistake is not including the correct Babel plugin if you don't use the AVA defaults.

**Comment by eric7578** [comment]
Thanks for the reply! But, with Node 7, I can run async/await without any babel plygin. I do run the code with Node(without plugin), and it works. The problem is that I can run with the same code with Node 7, but I cannot run it with avajs.

**Comment by novemberborn** [comment]
> with Node 7, I can run async/await without any babel plygin. I do run the code with Node(without plugin), and it works.

As far as I can tell Node.js 7 currently ships with V8 5.4, and async / await is only in 5.5: <http://v8project.blogspot.co.za/2016/10/v8-release-55.html>. How are you managing this?

**Comment by cliguo** [comment]
I encountered similar problems，with Node 7, I can run async/await，but ava：
async findById(table, id, columns) {
              ^^^^^^^^
SyntaxError: Unexpected identifier

**Comment by mightyiam** [comment]
@cliguo `async function findById(table, id, columns) {` perhaps
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by EduardoRFS** [comment]
v8 5.4 have async functions when use --harmony-async-await

**Comment by novemberborn** [comment]
> v8 5.4 have async functions when use --harmony-async-await

@eric7578 @cliguo are you using this flag?

**Comment by EduardoRFS** [comment]
Ava `shebang` dont pass flags to node, you need to run using a command `node --harmony-async-await ./node_modules/.bin/ava`

**Comment by novemberborn** [comment]
> Ava shebang dont pass flags to node

You mean the `ava` invocation in the `npm test` script?

**Comment by EduardoRFS** [comment]
@novemberborn yep

**Comment by novemberborn** [comment]
Ah cool. Then yea, that makes sense. Your workaround is good, though honestly I think folks should stick to Babel until `async` / `await` is available without a flag.

**Comment by eric7578** [comment]
Thanks for the reply @EduardoRFS , I will try it later ;)

**Comment by eric7578** [comment]
Finally back to work :D, I tried @EduardoRFS and it works!
Thanks for every one who provide opinions!
As a record for those who has the same problem, here is my final script:

`node --harmony-async-await ./node_modules/.bin/ava NODE_ENV=test ./**/*_test.js`

**Comment by cdyfng** [comment]
check this link :
https://github.com/trufflesuite/truffle/pull/146
