### ISSUE TITLE
No `t.snapshot`

### ISSUE THREAD

**Issue by machineghost** [avajs/ava#1162]
I'm using version 0.17 of Ava, and trying to use the snapshot feature.  However, when I run my (very simple) test file ...

    import test from 'ava';

    test('HelloWorld component', t => {
      console.log(t.snapshot, t.ifError)
    });

It logs the following:

    undefined [Function: decoratedAssert]

If I actually try to use `t.snapshot` I get an error (as one would expect).  However, logging `t.anythingElseYouWouldExpectTToHave` does log the expected function.

I am using Babel with Ava, but otherwise my environment is pretty simple.  Is there anything I could be doing wrong to prevent my `t` argument from having a `snapshot` method?

**Comment by sindresorhus** [comment]
It's not released yet. Like most repos on GitHub, the readme reflect latest master. If you want a specific release, see the correct git tag or [npm page](https://www.npmjs.com/package/ava).
