### ISSUE TITLE
How can I know the time spent on test?

### ISSUE THREAD

**Issue by xiaomaisu** [avajs/ava#1166]
How can I know the time spent on test?

**Comment by mightyiam** [comment]
Good question. I would try the [official support channels](https://github.com/avajs/ava#support).

**Comment by xiaomaisu** [comment]
I'm sorry that I have another expanded question,I  tried to compare the spent time on mocha and ava, but I can't find a live example.
    So I  checked the history version of postcss,however,it always made a mistake.
    Can official support channels provide a live example?

**Comment by sindresorhus** [comment]
If you just want to know the time of a test, put `console.time()` in the beginning and `console.timeEnd()` at the end. If you want to compare test run time between Mocha and AVA, only the total test run time is useful as AVA runs tests concurrently.
