### ISSUE TITLE
ava incorrectly ignores test files when the project itself is contained in node_modules directory

### ISSUE THREAD

**Issue by gajus** [avajs/ava#1173]
## Description

I have two projects:

* https://github.com/gajus/isomorphic-webpack
* https://github.com/gajus/isomorphic-webpack-demo

Due to the nature of the projects (`process.pwd()` aware dependency resolution), it is not possible to link `isomorphic-webpack-demo` inside `isomorphic-webpack`. Therefore, I need to do:

```bash
git clone https://github.com/gajus/isomorphic-webpack
git clone https://github.com/gajus/isomorphic-webpack-demo
(cd ./isomorphic-webpack && npm install)
(cd ./isomorphic-webpack-demo && npm install)
rm -fr ./isomorphic-webpack-demo/node_modules/isomorphic-webpack
cp ./isomorphic-webpack ./isomorphic-webpack-demo/node_modules
```

The problem happens when I try to run `ava` inside of `isomorphic-webpack`, i.e.

```bash
cd ./isomorphic-webpack-demo/node_modules/isomorphic-webpack
npm run test
```

I am getting error:

```
  1 exception

  ✖ Couldn't find any files to test
```

My guess (without looking at the source code), is that `ava` detects that `./isomorphic-webpack-demo/node_modules/isomorphic-webpack/test` path includes `node_modules` and therefore ignores this path.

Expected behaviour: ava should detect the immediate `./test` directory and run the tests.

## Environment

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
ava --version
npm --version
Node.js v7.3.0
darwin 16.3.0
0.17.0
3.10.10
```

**Comment by oskarmurand** [comment]
At least in 0.15.2 it works if you cd into the module that contains the tests and then do ../.bin/ava with all of the flas and path that you need.

**Comment by gajus** [comment]
> In 0.15.2 it works if you cd into the module that contains the tests and then do ../.bin/ava with all of the flas and path that you need.

Assuming you mean something like `ava ./test/**/*`, yes that works. However, behaviour of ava should not change depend on the current directory of the project, i.e. `ava` should work just as well.

**Comment by novemberborn** [comment]
I think this is related to https://github.com/isaacs/node-glob/pull/301.

When searching for test files, if we match a directory we [search for nested `*.js` files](https://github.com/avajs/ava-files/blob/3f2a63acae61fd7c86677a298618e3222650557e/index.js#L272:L279). This ends up passing an absolute pattern to `glob` (via `globby`), but with relative ignore patterns.

Instead we should make the pattern relative to `this.cwd`.

**Comment by yatharthk** [comment]
@novemberborn Do we need to work upon this bug?

**Comment by novemberborn** [comment]
@yatharthk you can take this if you want, yes 😄

**Comment by Jolo510** [comment]
Hey @novemberborn, I new to open source and Ava. Would this be a good first bug to tackle?

**Comment by novemberborn** [comment]
@Jolo510 actually I need to review the various globbing issues. I suggest you hold off until then. I think we may need a more comprehensive approach.
