### ISSUE TITLE
Bundle react-test-renderer with AVA

### ISSUE THREAD

**Issue by vadimdemedes** [avajs/ava#1175]
Is there any reason why user has to manually import `react-test-renderer` and render their React tree "by hand"?

```jsx
import test from 'ava';
import React from 'react';
import renderer from 'react-test-renderer';

test('snapshots', t => {
  const tree = renderer.create(<h1>Test</h1>).toJSON();
  t.snapshot(tree);
});
```

We could bundle `react-test-renderer` and that test would become:

```jsx
import test from 'ava';
import React from 'react';

test('snapshots', t => {
  const tree = <h1>Test</h1>;
  t.snapshot(tree);
});
```

...which is cleaner and nicer, imo.

Main reason for it is to also allow magic assert to do diffing on snapshots. Because trees in snapshots are not shallowly rendered (full trees are saved instead), we can't use `react-element-to-jsx-string` module, so we need `react-test-renderer` inside AVA either way.

What do you think?

**Comment by sindresorhus** [comment]
Sounds like an easy win. I don't like how big its dependency tree is though. It brings with it 2.5MB of mostly unused dependencies...

**Comment by jfmengels** [comment]
What about projects that use JSX with another tool than React?

**Comment by vadimdemedes** [comment]
Hmm, good point. Would be great if we had a universal `render-to-string` package, that would detect React/Preact/Inferno/etc vnodes and render them to string.

**Comment by vadimdemedes** [comment]
Then `t.jsxEqual()` would be universal as well.

**Comment by vadimdemedes** [comment]
On the other hand though, `t.jsxEqual()`, diffs and syntax highlighting in magic assert are tied to React. Unfortunately we can't be "easily" universal at the moment. 

Here are the possible routes we can go:

1. Create packages to serialize library-dependent JSX trees into JSON, bundle them and support most popular frameworks out of the box

This way would be the most comfortable from the user's perspective, but the most time consuming and expensive in terms of maintenance for us.

2. Remove React support and let the user handle JSX assertions

Least preferable way for both users and AVA, despite being the easiest solution. For diffs users would use libraries like [chai-jsx](https://www.npmjs.com/package/chai-jsx).

3. Leave `t.jsxEquals()` and make it accept JSON tree, like in `t.snapshot()`

This would make `t.jsxEquals()` compatible with every possible JSX-based library. I think this is best way to go. Developers could contribute similar libraries to `react-test-renderer` (converts JSX to JSON), which would allow AVA users to write tests with these libraries.

**Comment by novemberborn** [comment]
Can we use a Babel plugin to solve this?

**Comment by vadimdemedes** [comment]
I don't think it can be reliably implemented, because we'd have to detect which library is imported (react/preact/inferno/etc) and import according `react-test-renderer` alternative.

In my opinion, we could do just fine with the third option for a while. Minimal maintenance, universal compatibility.

**Comment by novemberborn** [comment]
Rephrasing yesterday's comment, now that I actually know what I meant to say…:

Could we support Babel plugins that rewrite `t.jsxEqual()` to automatically apply the JSON conversion? That way (assuming you don't mix JSX dialects within the same project) you don't need to do it manually. So option three, on steroids.

**Comment by vadimdemedes** [comment]
So steroids (babel plugins to transform JSX into JSON) are basically left for community to implement? Sure, why not? They can freely use any babel plugins in configuration.

**Comment by vadimdemedes** [comment]
Closing this, since the issue is now resolved.
