### ISSUE TITLE
Run 2 configurations

### ISSUE THREAD

**Issue by unional** [avajs/ava#1180]
ava: 0.17

I want to run two passes of ava, each with different configuration. Currently I can't find a way to do it.

I want to run `ava` once with `browser-env` and once without.
Since the configuration is done in `package.json` (the `require: []` is not supported in cli), I couldn't find a way to do it.

Maybe extending `ava: {} | []`?

```js
// package.json
{
  "ava": [{ /* first pass */}, { /* second pass */}]
}
```

**Comment by mightyiam** [comment]
This kind of thing is sometimes done using environment variables. Granted, you'll have to (conditionally) `require` inside the test files, perhaps.

**Comment by unional** [comment]
I tried using `shelljs` and use environment variables. But couldn't get it to work.

The issue seems like when ava runs, since it runs on a separate process, the environment variable is not picked up.

**Comment by mightyiam** [comment]
I don't see the need for `shelljs`. If you run `export FOO="foo" ava` won't the child processes have `FOO` set as well?

**Comment by unional** [comment]
Thanks, it works wonder!

For the record, this work for me:

```js
// package.json
{
  "scripts": {
    "coverage": "nyc --check-coverage --branches 85 --functions 85 --lines 85 npm test",
    "test": "ava && export BROWSER_TEST=true; ava"
  },
  "ava": {
    ...
    "require": [
      "./scripts/setup-browser-env.js"
    ]
  }
}

// scripts/setup-browser-env.js
if (process.env.BROWSER_TEST) {
  require('browser-env')()
}
```
