### ISSUE TITLE
Default parameters alter function arity

### ISSUE THREAD

**Issue by mightyiam** [avajs/ava#1185]
## Description

Default parameters alter function arity.

### Test Source

`index.js`
```js
module.exports = (foo = 'foo', bar = 'bar') => null
```
`index.test.js`
```js
const { test } = require('ava')
const subject = require('.')
test('exports function of arity 2', (t) => {
  t.is(typeof subject, 'function')
  t.is(subject.length, 2) // nope. it will be 1.
})
```

Note: I didn't try this exact reproduction code.

### Error Message & Stack Trace

Meh.

### Config

No config.

### Command-Line Arguments

No args.

## Relevant Links

Perhaps there's a babel issue...

## Environment

Doesn't seem to matter.

**Comment by sindresorhus** [comment]
Most likely Babel, yeah.

**Comment by novemberborn** [comment]
It's `0` in Node.js 7.4:

```console
$ node
> fn=(foo = 'foo', bar = 'bar') => null
[Function: fn]
> fn.length
0
```

This is a Babel issue. There'll always be a risk of subtle differences when using language features that require transpilation. The only solution is to carefully control what features you're relying on being available natively, and which you are compiling.

This is a nice edge-case though!
