### ISSUE TITLE
no tests found if using deasync

### ISSUE THREAD

**Issue by gurpreetatwal** [avajs/ava#1190]
I am converting some older projects that are currently using `mocha` to `ava` and ran into an issue with one of the projects that makes use of [`deasync`](https://github.com/abbr/deasync). 

Whichever test file requires a file which has a usage of `deasync` anywhere in its dependency tree, `ava` reports that no tests are found in that test file.

However, I was able to get everything working by changing [`L56 of lib/main.js`](https://github.com/avajs/ava/blob/22a60818afe6f5f7ae09979e148a9ce7ea37a90c/lib/main.js#L56) 

```diff
- globals.setImmediate(() => {
+ require('process').nextTick(() => {
```
To my understanding this works because the `setImmediate` gets executed at the end of this 'tick' and the `process.nextTick` gets executed at the beginning of the next tick. However, my understanding of the node event loop isn't the greatest so I don't know if that technically correct. 

### File Under Test

```js
'use strict';

const deasync = require('deasync');
const cp = require('child_process');

const exec = deasync(cp.exec);

let out = '';
try {
  out = exec('echo "hello"');
} catch(err){
  console.error(err);
}

if (!module.parent) {
  console.log(out);
}

module.exports = out;
```
### Test Source

```js
'use strict';

const test = require('ava');
const index = require('.');

test('output', t => {

  t.is(index.out, 'hello');

});
```

### Error Message & Stack Trace

```
$ npm test

> ava-deasync@1.0.0 test /home/gurpreet/temp/ava-deasync
> ava


  1 exception

  ✖ No tests found in test.js

npm ERR! Test failed.  See above for more details.

```

## Relevant Links
- [gist](https://gist.github.com/gurpreetatwal/aea507d17aca42b9c2bc490259355e0e) with minimal reproduction
- [deasync](https://github.com/abbr/deasync)
## Environment

Windows Subsytem for Linux, Build 14393
```
Node.js v6.9.4
linux 3.4.0+
ava 0.17.0
npm 4.1.2
```

**Comment by novemberborn** [comment]
> To my understanding this works because the setImmediate gets executed at the end of this 'tick' and the process.nextTick gets executed at the beginning of the next tick. However, my understanding of the node event loop isn't the greatest so I don't know if that technically correct.

It's the other way around, actually. `process.nextTick` schedules callbacks when the current turn of the event loop runs to completion. `setImmediate` is scheduled for the start of the next turn of the event loop.

Given that `deasync` hacks the event loop it's likely it's breaking the expected Node.js behavior. That's not something AVA will guard against. Perhaps try using [`execa`](https://www.npmjs.com/package/execa) to run your deasync'ed code in another child process from within your test.
