### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by zbraniecki** [avajs/ava#1199]
Just switched from mocha/chai to ava for a small project with 12 tests - https://github.com/zbraniecki/L10nRegistry

running `ava` takes 10 seconds on my machine. Seems like a bug.

setup: Ubuntu 16.10, node 7.4.0, yarn 0.18.1, ava 0.17

**Comment by novemberborn** [comment]
I see you're loading `babel-register`. Per https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#transpiling-sources:

> Note that loading babel-register in every forked process has a non-trivial performance cost. If you have lots of test files, you may want to consider using a build step to transpile your sources before running your tests. This isn't ideal, since it complicates using AVA's watch mode, so we recommend using babel-register until the performance penalty becomes too great

[RFC 001](https://github.com/avajs/ava/blob/master/docs/specs/001%20-%20Improving%20language%20support.md) is the plan for improving this. See also https://github.com/avajs/ava/projects/1 where I'm starting to list the tasks.
