### ISSUE TITLE
Can't import 'babel-core' in test file

### ISSUE THREAD

**Issue by billyjanitsch** [avajs/ava#1202]
## Description

I'm interested in using ava to test a Babel preset. The natural thing to do is import `babel-core` in my test file (and run `babel.transform(code, {presets: [require('.')]})` on some code to see if I get the expected output).

However, importing `babel-core` in a test file doesn't work -- the result is `undefined`. This might be a bug caused by ava's own use of babel to transpile the test file?

### Test Source

```js
// test.js
import test from 'ava'
import babel from 'babel-core'

console.log(babel)
```

### Error Message & Stack Trace

```
undefined
```

### Config

No custom config.

### Command-Line Arguments

```
ava
```

## Environment

Node 7.4.0, npm 4.1.1, ava 0.17.0, darwin 16.3.0.

**Comment by billyjanitsch** [comment]
Here's a repo: kensho/babel-preset-kensho@f7bbbf4064a0d0c623fc6b9e226d17623363081d

**Comment by novemberborn** [comment]
`babel-core` doesn't have a default export. This isn't an issue for most Node.js modules but since `babel-core` was created using Babel it does trip you up when using Babel's module syntax transform.

Use `import * as babel from 'babel-core` instead.

**Comment by billyjanitsch** [comment]
My mistake -- thanks for clarifying 🤤
