### ISSUE TITLE
Promises instantiated in test files do not pass `... instanceof Promise` in my code

### ISSUE THREAD

**Issue by aularon** [avajs/ava#1209]
## Description
I am working on a [mini library](https://github.com/etabits/node-line) that allows _"mixing Async/Sync code with Promises and Streams in a reusable unified line"_. I sat up many tests, and they are passing with no problem on my Node.js v6 environment. I switched to v5 to check how does the library do there and some of the tests failed... No problem: I thought it had to do with my code and Node.js at first, something that I will resolve later.

Later, I started digging for the problem, and it turned out that **invoking ava is changing the way code is behaving**: In my code there is an `if (var instanceof Promise)` switch, **the check is evaluating to false for promises created in test blocks**, and execution is taking different code paths!

The problem does not happen with Node.js version v7 or v6, only with v5 or v4.

### Test Source
https://github.com/aularon/ava-bugreport-promises

## Environment
Failing:
```
Node.js v5.12.0
linux 4.4.0-59-generic
AVA 0.17.0
npm 3.8.6

```
Succeeding:
```
Node.js v6.9.4
linux 4.4.0-59-generic
AVA 0.17.0
npm 3.10.10
```
## P.S.
I wanted to submit a pull request with a failing test, as suggested by your contribution guide, but you are [using bluebird as Promise in your promise.js test file](https://github.com/avajs/ava/blob/master/test/promise.js#L2), which will make it fail every time regardless of environment or the issue itself. So I put the test code in its own repo.

## P.P.S
Thank you for this awesome library!

**Comment by sindresorhus** [comment]
This is because we use Babel, and it replaces globals with polyfills. I'm pretty sure this is fixed in master. Can you try it? → `$ npm i avajs/ava`.

I would also strongly recommend against doing instance checking for `Promise`. Most promise libraries do not inherit from `Promise` (even Bluebird). The correct way of checking if something is a promise is: https://github.com/sindresorhus/p-is-promise/blob/4333abad2f82fb0b33fbdd962ec25d7e3f0e0672/index.js#L5-L8

**Comment by aularon** [comment]
Hello!

I updated to latest master as advised, and now tests are consistent across all nodejs versions (4, 5, 6 and 7!): All tests pass except for [these two](https://github.com/aularon/ava-bugreport-promises/blob/5d88077f15a75c88fa13556a65368095de9f4368/test/ava.js#L23-L24) (Both of which are irrelevant).

Before, test results were inconsistent between node versions, and these two failing tests were succeeding across all versions!

I am going with your approach to support any promise.

Thank you for your time and efforts!

**Comment by sindresorhus** [comment]
That's good to know. I'll keep this issue open until we've done a new release (Hopefully soon).

**Comment by sindresorhus** [comment]
New release is out: https://github.com/avajs/ava/releases/tag/v0.18.0 :)
