### ISSUE TITLE
Caching issue inside throwing test.

### ISSUE THREAD

**Issue by hzlmn** [avajs/ava#1211]
## Description

Hi and thanks for good tool!

I have a little problem with caching inside throwing test.

As you can see from test source i have `tokenizer` object loaded from `lib/tokenize`. On previous run it had `tokenizer.tokenize` method, but then it was moved and `tokenize` was placed in test file. 

When i run test it throws exception, where message tells that in transpiled code it expect availability of `tokenize` method on `tokenizer` object, while it was moved away from it.

Also tried with `no-cache` opt - same thing.

Could you help with it, please.

### Test Source

```js
import test from 'ava';
import tokenizer from '../lib/tokenize';
import Input    from '../lib/input';

function tokenize(source, options) {
    let tokens = [];
    const tk = tokenizer(source, options);
    while (!tk.endOfFile()) tokens.push(tk.readNextToken());
    return tokens;
}

test('throws error on unclosed comment', t => {
    t.throws(() => {
        tokenize(new Input(' /*'));
    }, /:1:2: Unclosed comment/);
});
```

### Error Message & Stack Trace

```
throws error on unclosed comment
  (0 , _tokenize2.default)(...).tokenize is not a function
    Test.t [as fn] (test/tokenize.js:236:7)
```

### Command-Line Arguments

```
ava ./test/tokenize.js [--no-cache]
```
## Environment

```
Node.js v6.9.1
linux 4.4.0-45-generic
ava  0.17.0
npm  3.10.8
```

**Comment by sindresorhus** [comment]
Do you have any `ava` config in package.json, like `babel-register`?

**Comment by hzlmn** [comment]
No I don't have any `ava` configuration in`package.json`

**Comment by hzlmn** [comment]
@sindresorhus Hi, did you have a chance to look on it?

**Comment by novemberborn** [comment]
@hzlmn there isn't really anything to look at I'm afraid. Perhaps you could share a repository with a branch in which tests are working, and another in which they're failing?
