### ISSUE TITLE
Render JSX in t.snapshot arguments

### ISSUE THREAD

**Issue by vadimdemedes** [avajs/ava#1214]
See https://github.com/avajs/ava/pull/1154#discussion_r97379225. During the development of magic-assert PR, we decided to extract `t.jsxEqual` from it and land it bit later with a more clear purpose.

> I do have one idea for these, but not sure if that can be implemented to be stable enough. We (or community) could write a babel plugin for react/preact/inferno, which detects `t.jsxEqual` and convert:
>
> ```jsx
> t.jsxEqual(<This/>, <That/>);
> ```
>
> into:
>
> ```jsx
> t.jsxEqual(renderer.create(<This/>).toJSON(), renderer.create(<That/>).toJSON());
> ```
>
> to save the user from typing that manually or creating shortcuts (as mentioned in #1175).

---

Also related https://github.com/avajs/ava/issues/1175

**Comment by novemberborn** [comment]
I wonder if we could advocate JSX transforms that just do this for `deepEqual`. Was there any specific behavior in `jsxEqual`?

**Comment by vadimdemedes** [comment]
Nope, there wasn't any specific behavior inside `t.jsxEqual`. I just thought it may be easier for 3rd-party transforms to detect what needs to be transformed, if we had `t.jsxEqual`.

**Comment by jfmengels** [comment]
Jut so I'm sure I understand: Why do we wish to have a new `jsxEqual` assertion method? Is it because doing 
```js
t.deepEqual(<This/>, <That/>);
```
creates an unreadable object that does not look like what you expect to see in the DOM?

**Comment by novemberborn** [comment]
I think this comes down to #1175. We can't do a generic `jsxEqual` because we need to render the JSX somehow, which means choosing a particular implementation (e.g. React). The solution for that was to encourage Babel plugins that would translate the JSX for use with the assertion. But I'm not convinced those plugins need to latch onto `t.jsqEqual` calls. They can just detect the JSX AST nodes.

**Comment by vadimdemedes** [comment]
@jfmengels I thought to add it, just to clearly indicate for 3rd-party babel plugins what JSX needs to be transformed.

@novemberborn Actually, this issue can be closed, since goal is to not have restrictive preferences and be open & universal to all JSX-based libraries. I should create a new issue describing my thoughts and a possible route we can take.

> But I'm not convinced those plugins need to latch onto t.jsqEqual calls. They can just detect the JSX AST nodes.

I don't have experience in that area, so I can't argue with this. If it's just easy as detecting `t.jsxEqual`, I'm fine with having just `t.deepEqual`.

One thought: would this confuse users who'd use `t.is` with JSX too?

**Comment by novemberborn** [comment]
Detecting JSX nodes is pretty easy, yeah.

> One thought: would this confuse users who'd use t.is with JSX too?

You can't use that to compare objects though, can you?

**Comment by vadimdemedes** [comment]
Nope, but I'm wondering if users will assume `t.is` is for shallow compare (JSX) and `t.deepEqual` for deep JSX.

**Comment by novemberborn** [comment]
That confusion doesn't seem exclusive to JSX object comparisons.

**Comment by vadimdemedes** [comment]
Yes, also true.

**Comment by vadimdemedes** [comment]
New developments on this issue. The idea is to have separate and optional babel plugins, which would transform `t.snapshot(<Hello/>)` into `t.snapshot(reactTestRenderer.create(<Hello/>).toJSON())`. Those plugins would only be responsible for injecting the renderer and placing JSX into `reactTestRender.create(JSX).toJSON()` code and putting it inside `t.snapshot()` args.

Renderers:

- [react-test-renderer](https://www.npmjs.com/package/react-test-renderer) for React
- [preact-render-to-json](https://github.com/nathancahill/preact-render-to-json) for Preact

User should be free to choose any test renderer he desires, but in case we already have a babel plugin for it, they can just go with that.

**Comment by novemberborn** [comment]
We'd be happy to promote plugins written for this purpose, but this isn't something that AVA needs to support by itself.
