### ISSUE TITLE
How can we set the pollInterval for watching files with the --watch flag

### ISSUE THREAD

**Issue by qaiser110** [avajs/ava#1216]

**Comment by sindresorhus** [comment]
Can you elaborate on why you need that? What OS are you using?

**Comment by qaiser110** [comment]
I'd like to set pollInterval to 1000ms. I'm using Mac, but I don't see how that's related to pollInterval.

**Comment by sindresorhus** [comment]
> I'd like to set pollInterval to 1000ms.

I'm looking for the reason for why you need this?

**Comment by qaiser110** [comment]
There is no major reason. On some occasions, i'd like to have a bit higher pollInterval, but it's not that a big deal if it isn't configurable in AVA. I just thought since AVA uses chokidar, and chokidar has pollInterval setting, it might be possible to set this option in AVA. 

BTW, AVA is awesome, and I'm loving it.
