### ISSUE TITLE
Error stack points to compiled source when using babel-register

### ISSUE THREAD

**Issue by vadimdemedes** [avajs/ava#1217]
While developing #1154, I faced an issue in a project, that uses `babel-register`. Error source pointed to a location in the compiled file, rather than original. As @novemberborn mentioned, it might get auto-fixed after [RFC 001](https://github.com/avajs/ava/blob/master/docs/specs/001%20-%20Improving%20language%20support.md). Let's keep this issue to remember and verify later.

**Comment by novemberborn** [comment]
I believe this is my comment: https://github.com/avajs/ava/pull/1154#issuecomment-276665936

Our code assumes stack locations are accurate. We do this through `source-map-support`. Locations may of course still be wrong but there's little we can do about that, safe for taking ownership of the location mapping. Which we won't do for now.
