### ISSUE TITLE
Snapshot feature shows empty diff when changing order of keys on object

### ISSUE THREAD

**Issue by raymond-h** [avajs/ava#1220]
## Description

When using the snapshot feature, if the new value is an object that is identical to the snapshot **but with a different key order**, the diff shown is **empty**.

### Test Source

Before:

```js
	...
	t.snapshot({
		coolNumber: 5 + 8,
		otherNumber: 9 + 8,
	});
	...
```

After altering the test so that the keys are in reversed order:
```js
	...
	t.snapshot({
		otherNumber: 9 + 8,
		coolNumber: 5 + 8,
	});
	...
```

### Error Message & Stack Trace

```
  1 failed

  banana
  test/test.js:6

   5: test('banana', async t => {
   6:   t.snapshot({             
   7:     otherNumber: 9 + 8,    

  Difference:

 
  Please check your code or --update-snapshots

  Test.<anonymous> (test/test.js:6:4)
  Test.fn (test/test.js:5:1)
```

### Config

package.json:
```json
{
  "ava": {
    "require": [
      "babel-register"
    ],
    "babel": "inherit"
  }
}
```

.babelrc:
```json
{
    "plugins": [
        "transform-runtime"
    ],
    "presets": [
        "stage-0",
        "es2015-node4"
    ]
}
```

### Command-Line Arguments

```
ava
```

## Environment

```
Node.js v4.6.2
linux 4.8.0-34-generic

AVA 0.18.0

npm 3.10.9
```

**Comment by novemberborn** [comment]
@vadimdemedes I assume magic assert doesn't care about key order? I suppose the snapshot comparison does, which seems fair.

**Comment by novemberborn** [comment]
Please see https://github.com/avajs/ava/issues/1275 for context.

**Comment by vadimdemedes** [comment]
> @vadimdemedes I assume magic assert doesn't care about key order? I suppose the snapshot comparison does, which seems fair.

Nope, it doesn't. `t.deepEqual()` doesn't care about key order, so you won't simply get an error, so it won't even "get to" magic-assert.

**Comment by novemberborn** [comment]
The issue is that we're actually comparing JSON strings inside `jest-snapshot`, so key order suddenly matters. That's not how `jest-snapshot` behaves otherwise (I think because `pretty-format` sorts the keys).
