### ISSUE TITLE
t.is not working, however is more strict cousin t.deepEqual is working

### ISSUE THREAD

**Issue by 6ewis** [avajs/ava#1222]
## Description
Goal: Playing with ava for the first time, hoping to get it to work somehow :)
Problem: Test run into a wall when I use the assertion method 't.is', 't.deepEqual' works for some reasons

### Failing Test

```js
test('renders zero items', t => {
  const wrapper = mount(
    <InventoryCategoryRow columns={['test']}/>
  );
  t.is(wrapper.find('tr').length, 3); //fail here
});

```
### Test Source

```js
const renderTableHeader = (category, index) => {return <th key={index}>{ category }</th>};

export default ({columns}) => {
  return (
    <thead>
      <tr>
        { columns.map((column, index) => renderTableHeader(column, index)) } 
      </tr>
    </thead>
  );
};
```

### Error Message & Stack Trace

```
TypeError: Cannot read property 'open' of undefined
    printBasicValue (node_modules/@ava/pretty-format/index.js:68:48)
    print (node_modules/@ava/pretty-format/index.js:276:17)
    printObject (node_modules/@ava/pretty-format/index.js:171:21)
    printComplexValue (node_modules/@ava/pretty-format/index.js:238:39)
    print (node_modules/@ava/pretty-format/index.js:282:10)
    printObject (node_modules/@ava/pretty-format/index.js:171:21)
    printComplexValue (node_modules/@ava/pretty-format/index.js:238:39)
    print (node_modules/@ava/pretty-format/index.js:282:10)
    printObject (node_modules/@ava/pretty-format/index.js:171:21)
    printComplexValue (node_modules/@ava/pretty-format/index.js:238:39)
    print (node_modules/@ava/pretty-format/index.js:282:10)
    printObject (node_modules/@ava/pretty-format/index.js:171:21)
    printComplexValue (node_modules/@ava/pretty-format/index.js:238:39)
    prettyFormat (node_modules/@ava/pretty-format/index.js:377:10)
    node_modules/clean-yaml-object/index.js:69:9
    cleanYamlObj (node_modules/clean-yaml-object/index.js:57:15)
    module.exports (node_modules/clean-yaml-object/index.js:3:9
Raw

```

### Config

`package.json`:

```json
"ava": {
    "babel": "inherit",
    "require": [
      "babel-register",
      "ignore-styles",
      "./src/test-setup"
    ]
  }

```

### Command-Line Arguments

npm test or more precisely:

```
cross-env NODE_ENV=test ava
```

## Environment

Node.js, npm, and AVA

```
Node.js v7.2.0
darwin 16.1.0
0.18.0
3.10.9
```

**Comment by vadimdemedes** [comment]
Could you post your failing test?

**Comment by vadimdemedes** [comment]
I released a few minor fixes to the underlying dependency (`@ava/pretty-format`), so make sure to run `npm update` before rerunning your tests.

**Comment by 6ewis** [comment]
@vadimdemedes I have just updated the description. Most importantly I ran npm update and it seems to work now

**Comment by vadimdemedes** [comment]
Great, thanks for reporting, it got resolved thanks to you!

**Comment by bjentsch** [comment]
I seem to be suffering the same issue. Force-upgrading to `@ava/pretty-format@1.1.0` seems to solve the initial problem, but it generates hundreds of log lines on the console now for my failing test. I tracked it down to this: 

- When using `t.true` or `t.false` as an assertion, ava tries to show me useful output by showing me all objects involved. In my case, I was doing a `[somedomelement].classlist.contains(...)` assertion, which resulted in having the console full of the jsonified DOM element and its (prototype) properties.

- When rewriting the test to use `t.is`, everything works as expected again.

**Comment by novemberborn** [comment]
@bjentsch yea, I can reproduce that problem. I think you're running into this issue: https://github.com/avajs/ava/issues/1204.

**Comment by bjentsch** [comment]
Oh. Well. Yes. Sorry for the noise.
