### ISSUE TITLE
Add `ava/babel` as a shortcut for including AVA's Babel presets

### ISSUE THREAD

**Issue by vadimdemedes** [avajs/ava#1225]
It seems to be a good convention across the community (glamor, next.js, more) to provide a shortcut for auto-including Babel settings. If user wants to customize presets, right now he has to include these presets manually. What I'm proposing:

```js
{
  "presets": [
    "ava/babel",
    "custom-preset"
  ]
}
```

It would also significantly simplify the creation of tools like [ava-preact-init](https://github.com/avajs/ava-preact-init), ava-react-init, ava-inferno-init, etc. If we provide a simple entrypoint for these presets, we won't need to update each of these modules when we change something in our presets.

**Comment by novemberborn** [comment]
We have `@ava/stage-4` and `@ava/transform-test-files` now. What are you proposing `@ava/babel` does?

**Comment by vadimdemedes** [comment]
No, not `@ava/babel` package, but `ava/babel.js` file. This file would simply serve as a preset, which would include `@ava/stage-4` and `@ava/transform-test-files`. Think of it as a handy shortcut, nothing more.

**Comment by novemberborn** [comment]
Ah. I think we should wait and see how the new presets get used, especially as we improve our Babel support.

**Comment by vadimdemedes** [comment]
> I think we should wait and see how the new presets get usedI think we should wait and see how the new presets get used

Could you explain that more? I didn't get the point.

**Comment by novemberborn** [comment]
See if and how people use `@ava/stage-4` / `@ava/transform-test-files`, without adding a wrapper preset to AVA itself.

**Comment by novemberborn** [comment]
Turns out a preset like this [is suggested in RFC 001](https://github.com/avajs/ava/blob/master/docs/specs/001%20-%20Improving%20language%20support.md#babel-projects):

> `testOptions`: `{}`: specify the Babel options used to compile test and helper files. If provided this completely disables the default Babel configuration AVA uses to compile test and helper files. Like with `sourceOptions`, `babelrc` defaults to `true`. Set `presets: ["ava"]` to apply AVA's transforms.

Though I suspect we may have to parse the options looking for that preset, and then replacing it with `@ava/stage-4` and `@ava/transform-test-files`. The latter taking the power-assert option into account.

**Comment by novemberborn** [comment]
#1608 implements `ava/stage-4` as an alias for our `@ava/stage-4` preset. I've decided not to expose `@ava/transform-test-files` as I want to (conceptually at least) separate the enhancements it contains from AVA's Babel usage.
