### ISSUE TITLE
Include only plain objects/arrays in t.true/t.false output of statements

### ISSUE THREAD

**Issue by vadimdemedes** [avajs/ava#1226]
AVA's magic-assert output causes a crash when this kind of assertion fails:

```js
t.true(some.spy.calledOnce);
```

or similar, when functions/instances are involved. This is happening, because `@ava/pretty-print` tries to print `some.spy` and `some` nicely. When parsing statements in `lib/enhance-assert`, we should ignore anything but plain objects and arrays.

**Comment by novemberborn** [comment]
Could you elaborate on what specifically causes the crash? 

> When parsing statements in lib/enhance-assert, we should ignore anything but plain objects and arrays.

How does this affect the output for `t.true(some.spy.calledOnce)`?

**Comment by vadimdemedes** [comment]
Sure. You can easily cause a crash if one of the statements contain (or is) a reference to a global scope (`global`). There's a ton of stuff in there and it doesn't make sense to print that.

Same goes with all the libraries. Unless it's a plain object or array, we can't pretty print it. Even if we could, why would we? The output needs to be meaningful and compact. So in the above example, `t.true(some.spy.calledOnce)` it's enough to print that `some.spy.calledOnce` is `false`.

**Comment by novemberborn** [comment]
> Same goes with all the libraries. Unless it's a plain object or array, we can't pretty print it. Even if we could, why would we? The output needs to be meaningful and compact. So in the above example, t.true(some.spy.calledOnce) it's enough to print that some.spy.calledOnce is false.

Fair enough.

I'd love to be able to print `Map` and `Set` though. And for those values we can't print, indicate their type.

**Comment by vadimdemedes** [comment]
Sure, `Map` and `Set` are ok. Talking about instances of classes/libraries. For example, you wouldn't want to pretty print an instance of Mongoose model, right?

**Comment by novemberborn** [comment]
> For example, you wouldn't want to pretty print an instance of Mongoose model, right?

It can be useful sometimes, but probably no 😄  Perhaps those kinds of instances could be restricted to showing the first three properties, with a little note saying "59 more properties not shown".

**Comment by vadimdemedes** [comment]
I think implementing this might be overly complicated and could take a while. This bug is quite annoying actually, I've seen it at least 6 times during last 2 days (yes, I've set up a counter 😄). I'd just go for a set of accepted types to be pretty-formatted in the "statements" output and push a fix. We can always make it more complex later ;)

**Comment by novemberborn** [comment]
> I'd just go for a set of accepted types to be pretty-formatted in the "statements" output and push a fix. We can always make it more complex later ;)

👍

**Comment by sindresorhus** [comment]
> > I'd just go for a set of accepted types to be pretty-formatted in the "statements" output and push a fix. We can always make it more complex later ;)
> 👍

👍

**Comment by novemberborn** [comment]
@vadimdemedes do you recall the actual error? I assume you're using Sinon, but with `sinon@1.17.7` I just get `[Function proxy]` for `@ava/pretty-format` output of the `sinon.spy()` result.

**Comment by pho3nixf1re** [comment]
This same behavior happens when using `enzyme` wrappers. The output is so large it makes the test output useless. I've gotten into the habit of putting the exact test value into a variable before passing it to the ava assertion.

**Comment by novemberborn** [comment]
As of #1341 we now limit how deeply we format values. There's loads of other suggestions in this thread we could still take on though.

**Comment by novemberborn** [comment]
The immediate problems are covered by #1204 and #1205. Beyond that we need to (eventually) support custom formatters for libraries like Sinon and Enzyme, but there's no point keeping this issue open for that.
