### ISSUE TITLE
Ignore node_modules and .gitignore when reading code excerpts

### ISSUE THREAD

**Issue by unional** [avajs/ava#1231]
ava: 0.18.1

In 0.17, I can still type "r" to rerun all tests in watch mode.

In 0.18.1 (and 0.18.0) this feature seems to be not working.

**Comment by unional** [comment]
When I Ctrl-C, it reports error like:
```sh
Error: ENOENT: no such file or directory, open 'E:\hwong\panda\module-loader\node_modules\systemjs\src\instantiate.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at module.exports (E:\hwong\panda\module-loader\node_modules\ava\lib\code-excerpt.js:15:20)
    at runStatus.errors.forEach (E:\hwong\panda\module-loader\node_modules\ava\lib\reporters\mini.js:191:22)
    at Array.forEach (native)
    at MiniReporter.finish (E:\hwong\panda\module-loader\node_modules\ava\lib\reporters\mini.js:178:21)
    at Logger.finish (E:\hwong\panda\module-loader\node_modules\ava\lib\logger.js:38:28)
    at busy.api.run.then.runStatus (E:\hwong\panda\module-loader\node_modules\ava\lib\watcher.js:112:12)
From previous event:
    at Watcher.run.specificFiles [as run] (E:\hwong\panda\module-loader\node_modules\ava\lib\watcher.js:110:68)
    at Watcher.rerunAll (E:\hwong\panda\module-loader\node_modules\ava\lib\watcher.js:270:8)
    at new Watcher (E:\hwong\panda\module-loader\node_modules\ava\lib\watcher.js:130:8)
    at Object.exports.run (E:\hwong\panda\module-loader\node_modules\ava\lib\cli.js:152:20)
    at Object.<anonymous> (E:\hwong\panda\module-loader\node_modules\ava\cli.js:22:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Seems like `ava` tries to load file using the sourcemap path?
`systemjs/src/instantiate.js` does not exist. It only has `systemjs/dist/...` with sourcemap.

**Comment by unional** [comment]
Correction: the above case is an issue on the test code. Once the test code is fixed, "r" started working.

However, the problem is still valid, and it seems like "magic-assert" tries to do something but couldn't, thus crash/block `ava` from continue to function in watch mode.

**Comment by novemberborn** [comment]
> the above case is an issue on the test code.

Could you elaborate on the kind of issue? I'm assuming an error was thrown in `systemjs`?

The error must have had its stack trace corrected using source maps, but the original source is not in the `systemjs` package. I think `code-excerpt` should return `null` in that case.

It'd be helpful to know where the error came from and what the test looks like that triggered it. Why are we trying to generate a code excerpt for it in the first place?

**Comment by unional** [comment]
Yes, it was an error thrown from `systemjs`. I have also encountered other cases that when an error is thrown, `ava` 0.18 just print out "1 failed" but didn't print out the thrown error (and "r" is not working in some cases), while in 0.17 the error message is printed.

**Comment by novemberborn** [comment]
@unional could you share the test that caused `systemjs` to throw?

**Comment by unional** [comment]
That one I can't. It's company code. I'll see if I can get the same behavior on one of my open source project and create a branch for this.

**Comment by novemberborn** [comment]
I'm thinking we shouldn't show code excerpts for errors that don't come from the test or helper files.

E.g. in this expression:

```js
const cacheKeys = (await result.getVerifier()).getCacheKeys()
```

Seeing this isn't particularly helpful:

```
  main › fromVirtual()
  node_modules/md5-hex/index.js:9

   8:     const inputEncoding = typeof buf === 'string' ? 'utf8' : undefined;
   9:     hash.update(buf, inputEncoding);
   10:   };

  Error: Data must be a string or a buffer

  update (node_modules/md5-hex/index.js:9:8)
  module.exports (node_modules/md5-hex/index.js:17:9)
  computeHashes (lib/Verifier.js:17:14)
  Verifier.getCacheKeys (lib/Verifier.js:22:23)
  Test.<anonymous> (test/main.js:329:50)
  step (test/main.js:38:191)
```

Given that the problem is somewhere in:

```js
      const hashes = from
        .filter(item => envName ? item.envs.indexOf(envName) > -1 : !item.default)
        .map(item => item.hash)

      return md5Hex(hashes)
```

@vadimdemedes?

**Comment by vadimdemedes** [comment]
Totally makes sense! We should avoid extracting everything from `node_modules` and `.gitignore`. `.gitignore` requires slightly more work, but ignoring `node_modules` should be pretty easy.

**Comment by unional** [comment]
Adding some info:
It seems to break the watch mode when an error is thrown during an async test.

**Comment by novemberborn** [comment]
> It seems to break the watch mode when an error is thrown during an async test.

@unional could you try https://github.com/avajs/ava/pull/1242? It should crash the watcher when this error occurs. That doesn't actually fix the magic-assert problem of course but at least in the future you won't be left hanging until you interrupt the watcher.

**Comment by novemberborn** [comment]
@vadimdemedes this part of the code also trips up when the error comes from an iterator:

```js
Array.from({
  *[Symbol.iterator] () {
    throw new Error('Boom')
  }
})
```

**Comment by unional** [comment]
You can test this from here: https://github.com/unional/some-issues/tree/systemjs-jsdomify
To run it:
```sh
git clone https://github.com/unional/some-issues.git
cd some-issues
git checkout systemjs-jsdomify
npm install
npm test
```

**Comment by unional** [comment]
> @unional could you try #1242? It should crash the watcher when this error occurs.

Forgot to reply on this. Yes I tried it, but it still "crash" the watch mode.

**Comment by novemberborn** [comment]
I've opened https://github.com/avajs/ava/issues/1268 and https://github.com/avajs/ava/issues/1269 as follow-ups.

I think for now we should show code excerpts when the error comes from a test, helper or source file, but not from dependencies. Let's leave `.gitignore` out of this. We can refine later based on user feedback.
