### ISSUE TITLE
Empty diff because of .toJSON

### ISSUE THREAD

**Issue by fleg** [avajs/ava#1233]
Using `deepEqual` with object with `.toJSON` method produce empty diff

### Test Source
Example with underscore chain object
```js
var test = require('ava'),
    _ = require('underscore');

test(function(t) {
    t.deepEqual(_([1, 2]).chain(), [1, 2]);
});
```

### Error Message & Stack Trace

```
$ ava test.js 

  1 failed

  [anonymous]
  test.js:5

   4: test(function(t) {                       
   5:   t.deepEqual(_([1, 2]).chain(), [1, 2]);
   6: });                                      

  Difference:

 
  Test.fn (test.js:5:4)

```

```
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v4.4.7
linux 4.4.0-59-generic
$ ava --version
0.18.1
$ npm --version
2.15.8

```

**Comment by fleg** [comment]
pretty-format has an option [callToJSON](https://github.com/avajs/pretty-format/blob/732c2c291c37694018d7077d952b06afbbb622d4/index.js#L286) that `true` by default, maybe this is a reason?

**Comment by vadimdemedes** [comment]
Hmm, I will look into this, thanks for reporting!

**Comment by novemberborn** [comment]
Perhaps if we can't compute a diff then we should not display the "Difference" section at all.
