### ISSUE TITLE
Support subtests like tape

### ISSUE THREAD

**Issue by secobarbital** [avajs/ava#1237]
## Description

I am trying to switch from tape to Ava to run tests in parallel but I did not find a way to write subtests, which I use extensively to group tests by function under test. For example:

```js
test('addOne', (st) => {
  st.test('- should add one to input', (t) => {
    t.equal(addOne(1), 2)
    t.end()
  })
  st.test('- should handle null', (t) => {
    t.equal(addOne(null), null)
    t.end()
  })
})
```

## Relevant Links

- [t.test in tape](https://github.com/substack/tape#ttestname-opts-cb)

**Comment by sindresorhus** [comment]
See: https://github.com/avajs/ava/issues/222
