### ISSUE TITLE
Improve diff symbols

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1238]
I think the symbols used to display diffs with the new magic assert could be improved.

Here's an example of a fairly complex diff output:

```
main › fromVirtual()
test/main.js:363

 362:
 363:   t.deepEqual(configModule.getOptions(), {
 364:     plugins: [

Difference:

    env: Object {
      development: Object {
        env: Object {
          development: Object {
-           env: Object {
-             development: Object {
-               plugins: Array [
-                 Array [
-                   "/pkg/test/fixtures/compare/node_modules/plugin/index.js",
-                   Object {
-                     label: "plugin@virtual",
-                   },
-                 ],
-               ],
-               presets: Array [
-                 Array [
-                   "/pkg/test/fixtures/compare/node_modules/preset/index.js",
-                   Object {
-                     label: "preset@virtual",
-                   },
-                 ],
-               ],
-             },
-           },
            plugins: Array [
              Array [
                "/pkg/test/fixtures/compare/node_modules/plugin/index.js",
                Object {
-                 label: "plugin@extended-by-virtual",
+                 label: "plugin@virtual",
                },
              ],
            ],
            presets: Array [
              Array [
                "/pkg/test/fixtures/compare/node_modules/preset/index.js",
                Object {
-                 label: "preset@extended-by-virtual",
+                 label: "preset@virtual",
                },
              ],
            ],
          },
```

The first section (the 20 lines of `-`) is an object that is *extraneous* in the actual value used in the `t.deepEqual()` expression. Similarly the other two sections attempt to show how the wrong value is present:

* `+                 label: "plugin@virtual",` is the *expected* value
* `-                 label: "plugin@extended-by-virtual",` is the *actual* value.

Using `-` and `+` put me in a `git diff` mindset. This makes it hard to know whether the values shown are *expected* or *actual*. To make matters worse in this case the *actual* output is correct, I need to update the *expected* result.

Perhaps we could do something more along these lines?

```
main › fromVirtual()
test/main.js:363

 362:
 363:   t.deepEqual(configModule.getOptions(), {
 364:     plugins: [

Difference:

    env: Object {
      development: Object {
        env: Object {
          development: Object {
⚠           env: Object {
⚠             development: Object {
⚠               plugins: Array [
⚠                 Array [
⚠                   "/pkg/test/fixtures/compare/node_modules/plugin/index.js",
⚠                   Object {
⚠                     label: "plugin@virtual",
⚠                   },
⚠                 ],
⚠               ],
⚠               presets: Array [
⚠                 Array [
⚠                   "/pkg/test/fixtures/compare/node_modules/preset/index.js",
⚠                   Object {
⚠                     label: "preset@virtual",
⚠                   },
⚠                 ],
⚠               ],
⚠             },
⚠           },
            plugins: Array [
              Array [
                "/pkg/test/fixtures/compare/node_modules/plugin/index.js",
                Object {
✖                 label: "plugin@extended-by-virtual",
❯                 label: "plugin@virtual",
                },
              ],
            ],
            presets: Array [
              Array [
                "/pkg/test/fixtures/compare/node_modules/preset/index.js",
                Object {
✖                 label: "preset@extended-by-virtual",
❯                 label: "preset@virtual",
                },
              ],
            ],
          },
```

That's a warning sign for extraneous values, a cross for wrong values, with a pointer for the expected value. See [`figures`](https://www.npmjs.com/package/figures).

**Comment by vadimdemedes** [comment]
Not sure I'd want such "rich" output. I think "-" and "+" would be enough, we just need to display removed/added values after all.

I'm a big fan of the proposal by @jfmengels. Jeroen suggested we treat a diff like a set of guidelines to fix the error. So "+" would mean "add this" and "-" - remove this. So instead of "actual"/"expected" we tell how to fix this problem. I don't think I've seen this before, it feels like an interesting approach to take.

**Comment by novemberborn** [comment]
I find it difficult to know *where* I need to fix the problem. Is the *actual* value wrong, or the *expected* value?

My example above refers to the code [here](https://github.com/novemberborn/hullabaloo-config-manager/blob/9ebc0caf33d5453b74c2ce25adde3be93122cbab/test/main.js#L210:L471). I'm inclined to take the `-` as "remove this from the *expected* value", but I need to do the opposite and *add* it instead.

But that's just in case the expected value is lagging behind, because I made the test more complicated. Just as easily there could be a bug, meaning there are missing values. Now if `+` means "add this", then should I add it to the *actual* or *expected* value? It's just as confusing.

**Comment by novemberborn** [comment]
@sindresorhus thoughts?

**Comment by unional** [comment]
Seems like an interesting way. But IMO is confusing and a step too far. 

It is an assertion that compares two objects. So I think it should just show what's the difference, I.e like git diff, rather then suggesting how to fix the assertion. 

This is not consistent to `t.is()` which just throw and say they don't match, instead of saying "you should change `actual` to `expected`.

**Comment by sindresorhus** [comment]
I think we should just show the difference and not try to invent a new meaning like "how to fix the problem". To make it clearer, we could do what Mocha does and clearly label what the symbols mean:

<img width="231" alt="screen shot 2017-04-17 at 15 51 43" src="https://cloud.githubusercontent.com/assets/170270/25471901/4abd5db0-2b53-11e7-9e41-a360e9d428ed.png">

**Comment by novemberborn** [comment]
Yes. And we should improve the diff output, which #1341 achieves.
