### ISSUE TITLE
Incorrect type definition for test.todo

### ISSUE THREAD

**Issue by davewasmer** [avajs/ava#1239]
## Description

The typescript type definition for `test.todo` seems to be incorrect:

```ts
export function todo(name: string, implementation: ContextualTest): void;
export function todo(implementation: ContextualTest): void;
export function todo(name: string, implementation: Macros<ContextualTestContext>, ...args: any[]): void;
export function todo(implementation: Macros<ContextualTestContext>, ...args: any[]): void;
```

It requires an implementation argument. The docs seem to indicate otherwise:

> They only require a title; you cannot specify the implementation function

It looks like the definitions are generated programmatically, and `test.todo` is the only one that does not follow the `test([name,] implementation)` pattern, so I'm guessing it just got swept into that category and a special case needs to be added.

### Test Source

![image](https://cloud.githubusercontent.com/assets/707213/22724235/4b25df20-ed82-11e6-9c62-b01f923fc91d.png)

**Comment by sindresorhus** [comment]
Are you using latest AVA? I thought this was fixed in https://github.com/avajs/ava/commit/0603edcbfbcee4cca7cf3a150d8899ef80b66840.

**Comment by davewasmer** [comment]
Apologies, my mistake, turns out I was on the prior version, thought I was on latest.
