### ISSUE TITLE
[Request] Introduce shorthand for t.context

### ISSUE THREAD

**Issue by GregOnNet** [avajs/ava#1249]
## Description

It would be nice to have a shorthand to get access to the data inside of `t.context`.
You could pass `context` as second optional parameter to each test.

### Benefit

- In my opinion this would make tests more readable.
- Naming of variables becomes more flexible.

### Test Source

```js
import test from 'ava';

// Before
test('my passing test', t => {
    const data = t.context.desiredData;
});

// After
test('my passing test', (t, ctx) => { // context == ctx, sut would also be a convenient parameter name.
    const data = ctx.desiredData;
});
```

## Environment

```
Node.js v7.5.0
win32 6.1.7601
ava 0.18.1
npm 4.1.2
```

**Comment by sindresorhus** [comment]
> ```js
>// After
>test('my passing test', (t, ctx) => { // context == ctx, sut would also be a convenient parameter >name.
>    const data = ctx.desiredData;
>});
> ```

This is not possible as it would conflict with [test macros](https://github.com/avajs/ava#test-macros).

**Comment by GregOnNet** [comment]
Yes, totally agreed.
Thanks for your quick response and for providing ava.
I've been working with it for two weeks now and I love it.

Kinds
Greg

**Comment by sindresorhus** [comment]
I you only need one thing in the context, you can assign it directly to `t.context`:

```js
test.beforeEach(t => {
    t.context = () => {
        // do something
    };
});

test('my passing test', t => {
    t.context();
});
```

If you need multiple things, you can take advantage of destructuring:

```js
test('my passing test', t => {
    const {data1, data2, data3} = t.context;
});
```

**Comment by GregOnNet** [comment]
Thanks for documenting this.
This is my current way to extract test data from the `t.context`. :+1:
