### ISSUE TITLE
Snapshot is doubly-escaped / hard to see diffs

### ISSUE THREAD

**Issue by ochafik** [avajs/ava#1254]
The example from the readme gives:

```js
exports[`HelloWorld component 1`] = `"\"\\n<h1>\\n    Hello World...!\\n</h1>\\n\""`;
```

(looks like it's json-stringified, with extra `"` quotes)

I'd love to use the snapshot feature, but non-diffable snapshots are a no-go. Could the exported value not just be a json object instead of a stringified json object?

**Comment by novemberborn** [comment]
> Could the exported value not just be a json object instead of a stringified json object?

Yes, that's what https://github.com/avajs/ava/pull/1223 is aiming to do.

**Comment by ochafik** [comment]
Awesome, thanks!

**Comment by novemberborn** [comment]
Please see https://github.com/avajs/ava/issues/1275 for context.
