### ISSUE TITLE
mini reporter fails on files with a sourcemap source URLs

### ISSUE THREAD

**Issue by davewasmer** [avajs/ava#1266]
## Description

For files that are transpiled before they reach ava, if the sourcemap includes a source URL, the mini reporter attempts to load the source code (via [code-excerpt.js](https://github.com/avajs/ava/blob/master/lib/code-excerpt.js#L15)), but it attempts to load it from the source URL specified in the source map. Since the code went through a build step prior to reaching ava, there's no guarantee that a relative source URL is still valid and exists. If the file does not exist, ava will error out.

### Error Message & Stack Trace

In the stack trace below, the `command-acceptance.ts` file does not exist, but `command-acceptance.js` does.

```
/Users/daw/projects/oss/denali/denali/node_modules/ava/lib/cli.js:174
                                        throw err;
                                        ^

Error: ENOENT: no such file or directory, open '/Users/daw/projects/oss/denali/denali/tmp/test/lib/test/command-acceptance.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at module.exports (/Users/daw/projects/oss/denali/denali/node_modules/ava/lib/code-excerpt.js:15:20)
    at runStatus.errors.forEach (/Users/daw/projects/oss/denali/denali/node_modules/ava/lib/reporters/mini.js:191:22)
    at Array.forEach (native)
    at MiniReporter.finish (/Users/daw/projects/oss/denali/denali/node_modules/ava/lib/reporters/mini.js:178:21)
    at Logger.finish (/Users/daw/projects/oss/denali/denali/node_modules/ava/lib/logger.js:38:28)
    at api.run.then.runStatus (/Users/daw/projects/oss/denali/denali/node_modules/ava/lib/cli.js:167:12)
From previous event:
    at Object.exports.run.err [as run] (/Users/daw/projects/oss/denali/denali/node_modules/ava/lib/cli.js:166:5)
    at Object.<anonymous> (/Users/daw/projects/oss/denali/denali/node_modules/ava/cli.js:22:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "plugins": [],
    "presets": []
  }
}
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v6.9.5
darwin 15.6.0
ava: 0.18.1
npm: 3.10.10
```

**Comment by davewasmer** [comment]
Seems like there's a few issues at play here, stemming from these lines in the mini and verbose reporters:

* If the source map's urls are relative, then as mentioned originally, an intermediate build step that moves the compiled files relative to their source before running ava will result in incorrect urls. 
* If the source map's urls are absolute, the reporters will still try to prefix the project's basePath (typically `process.cwd()`), resulting in two absolute URLs joined together. 

Both cases result in incorrect stacktrace URLs. For the verbose reporter, that seems to be a purely cosmetic problem - the user sees the wrong URLs, but that's all. For the mini reporter, it tries to build a code excerpt from that source URL, so the wrong URL actually crashes ava itself.

For absolute URLs, I filed #1267 to try to address this, which should resolve the issue.

For relative URLs, this gets trickier. Since ava can't know the what the original paths are relative to for sure, I'd suggest just aiming for better error reporting. At the very least, we could add some guards around the `codeExcerpt` method so that the mini reporter doesn't throw for non-existent source files, and could return a warning message instead of the code excerpt that could suggest using absolute sourcemap urls. We could go further, and do the same for the verbose reporter (i.e. print a warning that URLs will be incorrect).

Happy to PR either of those approaches.

**Comment by novemberborn** [comment]
Thanks for raising this @davewasmer. Some of your points have been discussed elsewhere, I've opened https://github.com/avajs/ava/issues/1268 and https://github.com/avajs/ava/issues/1270 to track their progress.

> [We] could return a warning message instead of the code excerpt that could suggest using absolute sourcemap urls. We could go further, and do the same for the verbose reporter (i.e. print a warning that URLs will be incorrect).

I think it's fine not to show a code excerpt. If we see many support requests asking why code excerpts are missing maybe we could output debug information, but let's see what actually happens first.
