### ISSUE TITLE
Upstream `pretty-format` changes

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1272]
I don't want us to maintain a fork. We have more than enough code to maintain of our own.

These changes: https://github.com/avajs/pretty-format/compare/33d06d06ec02d6162743be2bffdc34b8ef521209...master

**Comment by caesarsol** [comment]
To be verbose, you want to place a PR containing @vadimdemedes commits in Jest upstream repo (without changing their color defaults), then use their version.
Right?

**Comment by sindresorhus** [comment]
@caesarsol Not necessarily the commits directly, but a way to achieve the same results in a way that the maintainers of `pretty-format` accepts. Probably an option, but I haven't really looked into what will be needed.

**Comment by caesarsol** [comment]
I think it's just adding possibility of new colors for types, easy to keep the default to a neutral color theme Jest could accept, then switch it to unicorn-colorful in AVA 😉

I'll see if I find the time!

**Comment by sindresorhus** [comment]
👍

**Comment by novemberborn** [comment]
https://github.com/avajs/pretty-format/commit/5b3cd6e7898e6951312eab4aad4a1ee73c2e98bd might be contentious. I suspect we may want to diverge in other ways too, and the upstream being in a monorepo doesn't make things any easier.

**Comment by sindresorhus** [comment]
@novemberborn Even if that turns out to be the case, we should at least try to upstream as much as possible so it's easier to keep the fork current.

**Comment by cpojer** [comment]
Happy to help! Please send PRs our way and we'll make sure to address them.

@novemberborn which aspect of the monorepo is giving you trouble?

**Comment by novemberborn** [comment]
> which aspect of the monorepo is giving you trouble?

@cpojer it makes it harder to maintain a fork of a project inside the repo 😉

**Comment by SimenB** [comment]
Any news here? I'm guessing upstreaming would mean pulling down changes from upstream as well. Would love to have the latest HtmlElement plugin working inside ava! Or just a clean way of adding extra serialisers.

I'd be happy to help upstream changes if necessary 😄

**Comment by novemberborn** [comment]
> Seems like a small case of NIH hit and you're replacing jest-snapshot/pretty-format entirely: #1341. It'll be interesting to see what comes out of it. Looks cool! 😄

@SimenB yea if I get that over the finish line then we'll drop our dependency on `pretty-format`, forked or not. It's a rethinking of how `deepEqual` relates to `snapshot`, ensuring we can diff any value (and that the diff contains whatever it was that made the comparison logic think values were unequal), and bringing AVA's snapshot experience more in line with the other assertions. Including diff colors in snapshots ✨

**Comment by novemberborn** [comment]
With `0.20` we're no longer using `pretty-format`. The repository is still available if anybody wants to upstream our changes.
