### ISSUE TITLE
Magic assert output is very noisy

### ISSUE THREAD

**Issue by davewasmer** [avajs/ava#1278]
First off, I just wanted to say the new magic-assert functionality is pretty awesome. It's great to get some additional context from a test failure, and frequently saves me multiple rounds of "well, let's try logging out this value". And the designer in me appreciates the output formatting - very readable, scannable, and well structured.

That said, in many cases, the output can be very noisy in an unhelpful way. For example, I have several tests that assert that a file exists:

```js
t.true(fs.existsSync(someFilePath), 'file exists');
```

In this case, magic-assert ends up printing the entirety of the `fs` object, which is ~170 lines long, and not super helpful here. In another case, I assert a value on t.context:

```js
t.true(fs.existsSync(t.context.someFilePath), 'file exists');
```

magic-assert dumps `t` here, which ends up being nearly 800 lines long. This means lots of scrolling to find the info I actually care about (the value of `t.context.someFilePath`).

Now, I realize the inherent difficulty (impossibility?) of determining what is "useful" to print out and what isn't. One option that came to mind would be to have a browser based reporter, i.e. running ava would launch a browser tab that displayed the test results, which would allow for a richer UI for interacting with test results than is possible in the terminal. But based on other issue and PR comments, it seems like the ava team isn't interested in supporting custom reporters other than via TAP, which loses the magic-assert info.

I don't have any solid solutions to offer, and I normally refrain from posting issues like this when I can't be constructive, but I figured I'd toss this out there in case someone smarter than I came along and had an idea. Feel free to close if this is just one of those inherently unsolvable issues.

**Comment by novemberborn** [comment]
Yea, I hear ya. #1204 and #1205 cover this. I've added your examples to the thread in #1204.

> One option that came to mind would be to have a browser based reporter, i.e. running ava would launch a browser tab that displayed the test results, which would allow for a richer UI for interacting with test results than is possible in the terminal.

That's quite interesting! And difficult, I think. Instead we could better integrate with Node's debugging tools and trigger a breakpoint when an assertion fails, but that too sounds rather difficult.

> I don't have any solid solutions to offer, and I normally refrain from posting issues like this when I can't be constructive, but I figured I'd toss this out there in case someone smarter than I came along and had an idea. Feel free to close if this is just one of those inherently unsolvable issues.

No worries! I'm playing with a project that gives us more control over the diff output, hopefully we can use that to come up with good solutions for these problems.

**Comment by qaiser110** [comment]
Magic assert is awesome indeed, and very helpful indeed. But yes, it is quite noisy at times.

One option could be to have a flag to disable Magic assert, keeping power-assert enabled, resulting in the default power-assert style assertion messages that existed before Magic assert was added.

**Comment by davewasmer** [comment]
> That's quite interesting! And difficult, I think. Instead we could better integrate with Node's debugging tools and trigger a breakpoint when an assertion fails, but that too sounds rather difficult.

Yea, a little "pie-in-the-sky" to be sure. But personally, I wouldn't find the debugger integration that much more helpful. That's a much heavier process (i.e. you have to start ava, then copy the devtools URL, open that in the browser, then hit "play" since you need to pass in `--debug-brk`, then wait for it to hit the assertion, then look through the Scope panel, ...). The problem here isn't that I need more information - in my examples, the magic-assert had the right info, but it had too much excess info as well.

If there was a way to expose magic-assert's info to TAP consumers, or some other kind of reporter that fed the magic-assert info out in a machine readable format, then this kind of thing could be explored in userland.

**Comment by novemberborn** [comment]
> One option could be to have a flag to disable Magic assert, keeping power-assert enabled, resulting in the default power-assert style assertion messages that existed before Magic assert was added.

@qaiser110, for one, how we should the `power-assert` messages has also changed. We're wanting to improve magic assert first, before adding an option to disable it.

> If there was a way to expose magic-assert's info to TAP consumers, or some other kind of reporter that fed the magic-assert info out in a machine readable format, then this kind of thing could be explored in userland.

@davewasmer this might be possible if my experiments pan out, but hopefully if they do we can just improve the default output 😄

**Comment by qaiser110** [comment]
@novemberborn, thank you for the reply, and all the good work with ava. In some cases, I'm testing the REST endpoint, the response body is very big, so the terminal output gets exhausted, and I cannot even reach up to the start of the test output.

Also, I think giving both power-assert's graphical output and magic-assert's awesome :) output, and the options to disable one or the other would be very beneficial.

I know you're working on improving magic assert, and I'm sure you have something better planned. Just thought I should mention my concerns & thought. Thanks again for job well done.

**Comment by brokenseal** [comment]
This is a fairly old thread and the other mentioned issues are inactive as well.

I am thinking of dumping ava in favor of some other tools because of this...

**Comment by novemberborn** [comment]
@brokenseal could you give some examples of how this is making you regret using AVA?

**Comment by brokenseal** [comment]
Of course, I am using a couple of `test.ok(objA.name === objB.name)`, of course it fails but I will never know what `objA.name` and `objB.name` values are because the representation, in the terminal, of those two objects is so humongous that it even exhausts the maximum lines terminal capacity, there I can't even scroll up enough.

For privacy reasons, I can't share a screenshot at the moment.

**Comment by brokenseal** [comment]
I understand, I'll see if I can try your advice out then.
