### ISSUE TITLE
deepEqual() magic assert is reversed

### ISSUE THREAD

**Issue by unional** [avajs/ava#1279]
ava: 0.18.2

```js
test.only(t => {
  const actual = { a: 1 }
  const expected = { b: 2 }
  t.deepEqual(actual, expected)
});
```

![image](https://cloud.githubusercontent.com/assets/3254987/23193584/91accf08-f85e-11e6-9fa4-3d847bb35a64.png)

Should be the other way around. `+a: 1, -b: 2`

**Comment by novemberborn** [comment]
It's attempting to show you how to fix the test, but I agree it's confusing. See #1238.
