### ISSUE TITLE
Should before and after run with skip?

### ISSUE THREAD

**Issue by unional** [avajs/ava#1283]
ava: 0.18.2

```js
import test from 'ava'

test.before(() => {
  throw new Error('should not run?')
})
test.after(() => {
  throw new Error('should not run?')
})

test.skip('some skipped test', t => { })
```

Currently the `before()` and `after()` is run even if the file contain only skipped tests.
Is that the expected behavior?

**Comment by novemberborn** [comment]
Interesting. I don't particularly mind to be honest, it's a bit of an edge case. What do you think?

**Comment by sindresorhus** [comment]
As a user, I would expect them to not run. Same with `beforeEach` and `afterEach`.
