### ISSUE TITLE
Request: inverted match (--exclude?) and --file-match

### ISSUE THREAD

**Issue by machineghost** [avajs/ava#1292]
## Description

**--exclude use case:** when you are working with a subset of tests (eg. `--match="*something*"`) and you make a change that might affect other tests, so you want to check "did I break anything unrelated to my tests on accident?" (without seeing the output from or taking the time to run your current subset).  It would be convenient if you could simply do `--exclude="*something*"` in this case.

**--file-match use case:** let's say I have `fooTests.js`, `bar/fooTests.js`, and `baz/fooTests.js` files.  I'd like to run just my "foo tests", but since the tests in those files don't have "foo" in their name (why would they, it's in the file name?) there's currently no way to do so.  However if there was a `file-match` argument I could (similar to `match`) do `file-match="*foo*"`.

**Comment by sindresorhus** [comment]
1. You can already do this with: `--match="!*something*"`
2. You can do this with globbing: `ava **/*foo*.js`

**Comment by machineghost** [comment]
Sorry for not responding sooner. `--match="!*something*"` was in the docs, so I apologize for not finding that on my own.

The globbing solution is great too, although it's not a perfect solution for me personally.  When I run Ava I do it through an NPM script.  We have both front- and back-end tests, in different folders, with frontend/backend test paths hard-coded.  This is great for easily running front/back-end tests only, but it makes it impossible to change the path.

Of course I can always run ava directly from the command line and glob anything I want.  It just would be nice for me personally if there was a way to "filter" within whatever glob/path I've already specified.

**Comment by machineghost** [comment]
P.S. For anyone happening on this thread afterwards I should mention that you want to use `--match='!*something*'` (note the single quotes).  If you use double quotes your command line may very well interpret `"!` as something entirely different from what you want.

The documentation does have the correct (single) quotes though, so I'm not just mentioning it for this thread.

**Comment by novemberborn** [comment]
> We have both front- and back-end tests, in different folders, with frontend/backend test paths hard-coded. This is great for easily running front/back-end tests only, but it makes it impossible to change the path to target a subset of tests.

@machineghost, to clarify, something like `ava frontend/*foo*.js` would override the configured `"files"` patterns.

(Closing since this issue has been inactive for a while.)
