### ISSUE TITLE
React snapshot saves JSON object instead of HTML output

### ISSUE THREAD

**Issue by avaly** [avajs/ava#1294]
## Description

Minimal React snapshot test saves a JSON object in the snapshot file, instead of the pretty printed HTML format.

### Test Source

```js
test('React', t => {
    const tree = render.create(<Component />).toJSON();
    t.snapshot(tree);
});
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "babel": {
    "presets": [
      "react"
    ]
  },
  "ava": {
    "babel": "inherit",
    "require": [
      "babel-register"
    ]
  }
}
```

### Command-Line Arguments

```
ava -u
```

### Snapshot file

```
exports[`React 1`] = `"{\"__ava_react_jsx\":{\"type\":\"div\",\"props\":{},\"children\":[{\"type\":\"h1\",\"props\":{\"className\":\"foo\"},\"children\":[\"Hello World...!\"]},{\"type\":\"p\",\"props\":{},\"children\":[\"Lorem ipsum\"]}]}}"`;
```

## Relevant Links

Gist: https://gist.github.com/avaly/11bd5ce8210938abc36092ef00a8fb45

## Environment

Node.js v6.9.4
linux 4.4.0-64-generic
ava 0.18.2
yarn 0.20.3

**Comment by novemberborn** [comment]
Yea we're aware. Please see #1275.
