### ISSUE TITLE
Default to using babel if babel-core is detected

### ISSUE THREAD

**Issue by sheerun** [avajs/ava#1300]
Currently in all of my projects I put following configuration in package.json

```
  "devDependencies": {
    "babel-core": "^x.x.x",
    "babel-preset-env": "^y.y.y",
  },
  "ava": {
    "babel": "inherit",
    "require": [
      "babel-core/register"
    ]
  }
```

Ideally AVA would just know I use `babel-core` as development dependency and default to the configuration above, i.e. it would be nice if AVA followed convention over configuration.

Could you detect if babel-core is listed in devDependencies and if so, default configuration to { "babel": "inherit", "require": [ "babel-core/register" ] } ?

Two more notes:

- defaulting to babel: "inherit" if babel-core is detected doesn't make tests much slower if one uses `"node": "current"` flag for babel-preset-env
- one can always opt-out by setting "babel" and "require" configuraton options to something else

**Comment by novemberborn** [comment]
Our plan for improving Babel support is here: https://github.com/avajs/ava/blob/master/docs/specs/001%20-%20Improving%20language%20support.md#specific-proposal

Once that's fully implemented you can do `"ava": { "babel": true }` to achieve the same.

It's an interesting idea, but I think triggering Babel mode based on a dependency is too hard to explain to users, especially if they weren't expecting AVA to transpile source files. Thanks for suggesting it though!
