### ISSUE TITLE
Infinite loop with mock-fs

### ISSUE THREAD

**Issue by wmnnd** [avajs/ava#1307]
## Description

When using mock-fs in `beforeEach`/`afterEach` hooks, ava will go into an infinite loop, repeating all tests over and over again, if one test fails.
Using `afterEach.always` instead of just `afterEach` makes no difference.

If all tests pass, this problem does not occur.

### Test Source

```js
const {test} = require("ava")
const mock = require("mock-fs")

test.beforeEach("mocking fs", t => mock({}))
test.afterEach.always("unmocking fs", t => mock.restore())

test("this will work", t => t.is(true, true))
test("this will fail", t => t.is(true, false))
```

### Error Message & Stack Trace
This is the output I got. I interrupted it after a while with Ctrl+C.
```
(node) warning: possible EventEmitter memory leak detected. 11 test listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TestCollection.addListener (events.js:252:17)
    at Runner.run (~/ava-mock-fs/node_modules/ava/lib/runner.js:149:14)
    at process.<anonymous> (~/ava-mock-fs/node_modules/ava/lib/main.js:73:10)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process.<anonymous> (~/ava-mock-fs/node_modules/ava/lib/test-worker.js:66:10)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
 
 ⠋ this will work

  18521 passed
```

### Command-Line Arguments

ava was called without any special configuration or parameters

```
ava mock-fs-test.js
```
## Environment
I tried this with Node.js v5.11.1 on Ubuntu 16.10, with ava 0.18.2, mock-fs 4.2.0 and npm 3.8.6.

**Comment by novemberborn** [comment]
With Node.js 7.7.1, I installed `ava` and `mock-fs` and copied your test source. I get a different error:

```
  Error: ENOENT, no such file or directory '/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.GMA5DKe8sX/node_modules/.cache/ava/33bf9bc21e0daef2216476b2877cac1e.js.map'

  Binding.<anonymous> (node_modules/mock-fs/lib/binding.js:397:15)
  maybeCallback (node_modules/mock-fs/lib/binding.js:43:17)
  Binding.open (node_modules/mock-fs/lib/binding.js:371:10)
  mapSourcePosition (node_modules/source-map-support/source-map-support.js:168:21)
  wrapCallSite (node_modules/source-map-support/source-map-support.js:339:20)
  Function.prepareStackTrace (node_modules/source-map-support/source-map-support.js:373:24)
  new AssertionError (node_modules/core-assert/index.js:77:9)
  Test.t [as fn] (test.js:10:31)
```

It might be related, of course.

It won't come as a surprise to you that AVA reads files from disk, even after your test has been loaded. `mock-fs` gets in the way of that. With the error I'm seeing, it's `mock-fs` that breaks AVA.  It doesn't look like `mock-fs` can be constrained to specific directories though, which is a pity.

**Comment by wmnnd** [comment]
I tried the same with [fake-fs](https://github.com/eldargab/node-fake-fs) and unfortunately it also results in the looping error for me.
There seems to be no way to test modules that do disk i/o with ava, or did I overlook something?

**Comment by novemberborn** [comment]
Patching `fs` is risky. I'm not familiar with the various mocking libraries out there, so if they all interfere with other programs then that is unfortunate. I'm not particularly interested in writing code that can defend against such interference.

IMHO it should be possible to write a file system mocking library that only mocks very specific file paths, but I don't know if they exist.

I'm curious though what error you might get on Node.js 7. You mentioned you're using 5.11.1 but Node.js 5 is no longer maintained.
