### ISSUE TITLE
Probably not compiling with babel: `Unexpected import token`

### ISSUE THREAD

**Issue by renatorib** [avajs/ava#1309]
## Description

Testings are failing in `Unexpected import token` (probably due to non babel compiling issue)

### Test Source

initials.js
```js
const initials = (string: string) =>
  string.split(' ').map(word => word[0]).join('').slice(0, 2);

export default initials;
```

initials.test.js 
```js
import test from 'ava';
import initials from './initials';

test(t => t.expect(initials('Renato Ribeiro')).toBe('RR'));
```

### Error Message & Stack Trace

Here's a print (Sorry, I have a problem with my term that I can't copy text :cry:)

![image](https://cloud.githubusercontent.com/assets/3277185/23932815/f85670e0-0918-11e7-8f19-27ef8ba966e1.png)

### Config

package.json
```json
{
  "...": "...",
  "ava": {
    "babel": "inherit"
  }
}
```

.babelrc
```json
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    "transform-export-extensions"
  ]
}
``` 

Note: also tested with `"require": ["babel-register"]` in ava configuration

### Command-Line Arguments

```
ava
```

## Relevant Links

Repo: https://github.com/renatorib/next-jsonplaceholder
Initials test commit: https://github.com/renatorib/next-jsonplaceholder/commit/f5602a1f77163ca9a0fdac4f9bd76ccf10955fcd

## Environment

```
$ ava --version
0.18.2

$ node --version
v7.5.0 
```

**Comment by novemberborn** [comment]
> (probably due to non babel compiling issue)

Yes.

You've disabled AVA's default transpilation of test files. It's now up to you to make sure your code runs in Node.js. You'll have to make sure to transpile the module syntax in your own Babel config.

**Comment by renatorib** [comment]
> You've disabled AVA's default transpilation of test files.
Where?

My custom babel config support `import/export` and latest es versions.

---

When I remove this config:

``` 
"ava": {
  "babel": "inherit"
}
```

This error persists.

**Comment by novemberborn** [comment]
> And when I remove this config:
> 
> "ava": {
>   "babel": "inherit"
> }
> This error persists.

I actually get this error, which seems to be some Flow syntax that isn't removed:

```
❯ npm t

> Placeholder@ test /private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.zWXKadVBb1/next-jsonplaceholder
> ava

/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.zWXKadVBb1/next-jsonplaceholder/utils/initials.js:3
const initials = (string: string) =>
                        ^
SyntaxError: Unexpected token :
```

In any case, it means AVA transpiled the ESM syntax correctly.

> My custom babel config (next/babel) support import/export and latest es versions.

But does it transpile to CJS?

> Why closed issue, since this not resolved?

This issue tracker is for AVA itself. Happy to do the occasional support here, and happy to keep discussing, but this is a problem with your Babel setup, not AVA.

**Comment by penge** [comment]
Put those to **package.json:**
```
{
  "ava":  {
    "require": ["babel-register"]
  },

  "babel": {
    "presets": ["@ava/stage-4"]
  }
}
```
[source]: https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#transpiling-sources

*Source: [transpiling-sources@AVA][source]*

@avajs, I would suggest making init more clever so those issues are gone.
To be "No extra setup needed." :)

**Comment by mdvorscak** [comment]
I would like to add that it is very un-intuitive that you must add 
```
"ava":  {
    "require": ["babel-register"]
  }
```
In order to get ava working with ESNext source files and the documentation [here](https://github.com/avajs/ava/blob/master/docs/recipes/babel.md) is very misleading:

> By default our Babel pipeline is applied to test and helper files ending in .js. If your project uses Babel then we'll automatically compile files using your project's Babel configuration.

Since you must add the snippet from above, which is given at the bottom of the doc.

**Comment by novemberborn** [comment]
@mdvorscak that paragraph does attempt to specify "test and helper files", but I agree it's not entirely clear. Perhaps "files" in the second sentence should be "these files", and we should add a paragraph linking to source compilation section?

**Comment by mdvorscak** [comment]
I agree, I created a PR to attempt to clarify this behavior.
