### ISSUE TITLE
RxJs error when returning Observable.catch() in test

### ISSUE THREAD

**Issue by sanderploegsma** [avajs/ava#1311]
## Description
The documentation states that it is possible to return an Observable from your test to have it automatically handled by the framework. However, I would like to test that a certain function throws an error in certain cases. Doing so, I got an error from the RxJs library (version 5.2.0), leaving me with the impression that this is a bug in Ava. See details below.

### Test Source
Not the actual source, but this MVP shows the exact same behaviour
```js
test('Observable throws an error', t => {
  t.plan(1);
  const error = new Error('Failed');
  return Observable.throw(error).catch(err => t.is(error, err));
});
```

### Error Message & Stack Trace

```
token › Observable throws an error
  /Users/sander/test/node_modules/rxjs/src/util/subscribeToResult.ts:81

  Error: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

  Object.subscribeToResult (node_modules/rxjs/src/util/subscribeToResult.ts:81:23)
  CatchSubscriber.error (node_modules/rxjs/src/operator/catch.ts:111:16)
  ErrorObservable._subscribe (node_modules/rxjs/src/observable/ErrorObservable.ts:79:18)
  ErrorObservable.Observable._trySubscribe (node_modules/rxjs/src/Observable.ts:113:19)
  ErrorObservable.Observable.subscribe (node_modules/rxjs/src/Observable.ts:98:21)
  CatchOperator.call (node_modules/rxjs/src/operator/catch.ts:80:19)
  Observable.subscribe (node_modules/rxjs/src/Observable.ts:96:16)
  Observable.forEach (node_modules/rxjs/src/Observable.ts:141:12)
  module.exports (node_modules/observable-to-promise/index.js:13:4)
```

### Config

```json
{
  "ava": {
    "files": [
      "test/**/*.test.js"
    ]
  }
}
```

### Command-Line Arguments
None

## Environment
- Ava version 0.18.2
- Node version 6.10.0
- darwin 16.4.0

**Comment by BarryThePenguin** [comment]
To allow the Observable sequence to continue after you've caught it, you'll need to return an Observable sequence to continue with.

From the documentation for [`Observable.prototype.catch`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-catch):
> Return: An observable that originates from either the source or the observable returned by the catch selector function.

A couple of options are, return an empty Observable after you've run your assertions

```js
test('Observable throws an error', t => {
  t.plan(1);
  const error = new Error('Failed');
  return Observable.throw(error).catch(err => {
    t.is(error, err);
    return Observable.empty();
  });
});
```

or, catch and then assert your errors by mapping over them

```js
test('Observable throws an error', t => {
  t.plan(1);
  const error = new Error('Failed');
  return Observable.throw(error).catch(err => Observable.of(err))
    .map(err => t.is(error, err));
});
```

**Comment by sanderploegsma** [comment]
Right, that makes sense, can't see how I missed that. Thanks!
