### ISSUE TITLE
Verbose (v) in watch mode

### ISSUE THREAD

**Issue by unional** [avajs/ava#1328]
ava: 0.17

Currently, I use `r` to rerun test in watch mode a lot.
However, there are times when the error message is not clear enough (e.g. uncaught exception).
It would be great to use `v` to rerun the test with verbose temporary turned on.

**Comment by sindresorhus** [comment]
Why do you have to press `r` a lot? That sounds like a bug is misconfiguration.

What kind of verbose information are you missing? As far as I know we show all the information we have.

**Comment by unional** [comment]
Closing for now as we are in 0.19
