### ISSUE TITLE
Allow config options on a per test basis

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#1333]
See https://github.com/avajs/ava/issues/1322#issuecomment-290935841

There are a few options that we apply globally, where it's conceivable you may want to tune them per test.  Since we are already doing an AST pass with Babel, we could allow users to declare overrides in an export declaration:

```js
export const avaConfig = {
  serial: true,
  failFast: true,
  require: ['babel-register'],
  runTopLevel: true
};
```

Another possibility would be something like [config overrides in xo](https://github.com/sindresorhus/xo#config-overrides). Where you declare overrides in `package.json`, and supply glob patterns.

The main advantage of the second option is that it allows you to apply overrides to multiple files without putting a declaration at the top of each one.

The advantage of the first option is that it's probably easier to understand (people don't grok globs, and it's confusing), and you are able to make changes to the behavior of the current test file without switching to a different file in your editor.

We could of course combine both strategies, or follow some other clever idea.

**Comment by Magellol** [comment]
I'm actually in the need of having different set of configurations.
I'm using `ava` to test react components but also code living in the server (proxying requests and handling server side rendering for instance). Although, some parts of my server don't need to be transpiled by babel (node js compliant code) but I couldn't find a way to specify a per directory config set, so ava runs all tests under the same conditions.

```json
  "ava": {
    "babel": "inherit",
    "require": [
      "babel-register",
      "./test/_init.js"
    ]
  },
```

So I believe this idea would solve these kind of problems.

**Comment by novemberborn** [comment]
> Although, some parts of my server don't need to be transpiled by babel (node js compliant code) but I couldn't find a way to specify a per directory config set,

@Magellol you should be able to specify an `ignore` pattern in your [Babel options](https://babeljs.io/docs/core-packages/#options) which causes it to ignore those files.

**Comment by Magellol** [comment]
@novemberborn Oh interesting. Will check it out, thanks!
