### ISSUE TITLE
How to use Ava with Node v7.7+ native async..await

### ISSUE THREAD

**Issue by dj-hedgehog** [avajs/ava#1338]
I already transitioned my web application to use Node 7.8 (V8 5.5) and therefore have native async..await available. How do I make Ava use it too instead of `transform-regenerator`

**Comment by jamestalmage** [comment]
See the [ES2017 Support](https://github.com/avajs/ava#es2017-support) section of the documentation. If you already have a babel config you want applied to your test, use the `babel: "inherit"` option. If you want to disable babel, you could do:

```js
"ava": {
  "babel": {
    "presets": [] 
  }
}
```

That supplies an empty config, which essentially tells babel to "do nothing". AVA will still add a few transforms, but nothing related to `async` / `await`.

**Comment by novemberborn** [comment]
I don't think we use `transform-regenerator` anymore, since we're now only targeting Node.js versions with generator support.

When Node.js 8 comes out we'll update our transforms and we'll no longer transpile `async/await` for those Node.js versions.

**Comment by sindresorhus** [comment]
This was fixed by https://github.com/avajs/ava/commit/e45695197c8ba5d0ec7df7a7fe38f00f9a5f5fb0.

**Comment by medikoo** [comment]
@novemberborn so which features still need to be transpiled when relying on Node 8 ? I thought moving to Node 8 removes the need for babel completely :)

**Comment by sindresorhus** [comment]
@medikoo The `import`/`export` syntax: https://github.com/avajs/babel-preset-stage-4/blob/master/plugins/8.json We also use Babel in AVA itself to detect incorrect usage of `t.throws()`. And there will soon be more: https://github.com/avajs/babel-preset-stage-4/issues/7 JS is constantly evolving and there will always be features not even available in the latest engines.

**Comment by cdaringe** [comment]
hi all.  love the project--you're doing great work.

i'd really love to dodge the transpile step _for at least my source_ s.t. debugging is less roundabout:

- i can edit my files in the same window during the test (vs closing the transpiled src and nav'ing to my old file)
- ...and i can use built in break points!

i _think_ this could be as simple as getting some config to babel to _ignore my stuff_.  wow-wee that'd be incredible!  is that something you're open to?

**Comment by cdaringe** [comment]
good news! its seem as though the system _doenst_ transpile stuff if you use pure runtime stuff! woo hoo!

![screen shot 2017-08-11 at 4 56 44 pm](https://user-images.githubusercontent.com/1003261/29235700-135d7dc6-7eb6-11e7-96b3-a07ce0f164f5.png)

**Comment by medikoo** [comment]
> JS is constantly evolving and there will always be features not even available in the latest engines.

@sindresorhus wouldn't it be better to just use what's available natively, without compilation overhead (?) There's actually quite big cost behind that. Is it worth it?  Isn't what's natively available good enough?

**Comment by novemberborn** [comment]
@medikoo tests should work across Node.js versions. We want you to be able to use the latest syntax in your tests, even if you're developing for Node.js 6 or 4.
