### ISSUE TITLE
Test context type missing `end` (at least in callback test)

### ISSUE THREAD

**Issue by mightyiam** [avajs/ava#1347]
## Description

Default `t` type for at least callback tests is missing `t.end`.

![screenshot_2017-04-06_13-09-30](https://cloud.githubusercontent.com/assets/635591/24749223/ebea5d12-1aca-11e7-871b-b501ed4aa88b.png)

## Relevant Links

https://github.com/mightyiam/cyclejs-components/pull/122

## Environment

Node.js v7.8.0
linux 4.10.0-15-generic
npm 4.2.0
ava 0.19.0

**Comment by mightyiam** [comment]
Thanks, @novemberborn !

Hey, but, for the record, the `context` is `t.context`, and not `t`, as suggested above, right?

**Comment by novemberborn** [comment]
`t` is the "execution context" 😉
