### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by rhysburnie** [avajs/ava#1349]
Hi,

I've been writing tests - new to AVA and have 27 done all passing.
However after the 27th the following started appearing:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 beforeExit listeners added. Use emitter.setMaxListeners() to increase limit
```

Is there some gotcha as far as setup goes that I should be aware of?
The tests themselves are passing.

**Comment by novemberborn** [comment]
Yes, see https://github.com/avajs/ava/pull/1346. I'll probably get that out as a `0.19.1` patch release tomorrow.
