### ISSUE TITLE
Out of memory if compare huge objects

### ISSUE THREAD

**Issue by cevek** [avajs/ava#1350]
### Test Source

```js
var document = jsdom('', {});
test.only(t => {
     node = document.createElement('div');
    var obj = {node: node, a: 1}
    t.is(obj, {a: 1});
});
```

```
Security context: 0x4c9cc7c0d39 <JS Object>
    2: printFunction(aka printFunction) [...node_modules/@ava/pretty-format/index.js:~41] [pc=0x21ada69f3380](this=0x4c9cc704311 <undefined>,val=0x1576e457fc21 <JS Function HTMLSpanElement (SharedFunctionInfo 0x386a10cbf289)>,printFunctionName=0x4c9cc7043b1 <true>)
    3: printBasicValue(aka printBasicValue) [.../node_modules/@ava/pret...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by novemberborn** [comment]
What version of AVA, `jsdom` and Node.js are you using?

I've tried to reproduce this with `0.19.0`, `9.12.0` and `7.8.0` respectively, but though the output is massive, it doesn't crash:

```js
import test from 'ava'

test(t => {
  const document = require('jsdom').jsdom('', {});
  const node = document.createElement('div');
  t.is({node, a:1},{a: 1})
})
```

(We're aware of the output size issues.)

**Comment by cevek** [comment]
ava version: 0.18.2
node: 7.4.0
So, yeah, that's example doesn't crash, cause output it is not very much :)
```
test(t => {
  const document = require('jsdom').jsdom('', {});
  const node = document.createElement('div');
  // because every dom linked with each other
  for (var i = 0; i<1000; i++) node.appendChild(document.createElement('div'));
  t.is({node, a:1},{a: 1})
})
```

**Comment by novemberborn** [comment]
Ha, nice! With https://github.com/avajs/ava/pull/1341 we're hoping to control how many properties are output for `power-assert` assertions (`t.is()` is one of those). That will help with this scenario. Eventually it should also be possible to register helpers for say `jsdom` objects which can then print a more useful representation.

**Comment by novemberborn** [comment]
#1341 has landed. A new release will be out soon. While I haven't checked your example I'm hopeful it won't crash :)
