### ISSUE TITLE
Optional format for string diff error messages 

### ISSUE THREAD

**Issue by pomber** [avajs/ava#1351]
Feature request:

When comparing two string with `t.is(actual, expected)` sometimes, when the test fails, is better to have the two strings side by side instead of showing the diff. It would be nice if this can be configured in some way.

For example:
`t.is("<undefined></undefined>", "<div></div>");`

Current output :
```
  Difference:
    "<undefinedv></undefinedv>"
```

Suggested output (using same output as other types use):
```
  Actual:

    "<undefined></undefined>"

  Must be strictly equal to:

     "<div></div>"

```
Or even better:
```
    Actual: "<undefined></undefined>"
  Expected: "<div></div>"
```

**Comment by novemberborn** [comment]
I agree. With https://github.com/avajs/ava/pull/1341 (pending input from others) the output would be:

```
Difference

- <undefined></undefined>
+ <div></div>
```

**Comment by dudu84** [comment]
Hi! Can I take this?

**Comment by novemberborn** [comment]
@dudu84 we'll be solving this with #1341.

**Comment by novemberborn** [comment]
#1341 has landed. A new release will be out soon.
