### ISSUE TITLE
ava --init should respect package.json indentation

### ISSUE THREAD

**Issue by OmgImAlexis** [avajs/ava#1358]
## Description
Running `ava --init` adds ava to my `package.json` but also reformats the whole file to 2 spaces instead of the 4 I have listed in my `.editorconfig`.

```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
# and trailing whitespace removed
[*]
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.{js,css,json}]
charset = utf-8
indent_style = space
indent_size = 4

# Matches the exact files either package.json or .travis.yml
[{.travis.yml}]
indent_style = space
indent_size = 2
```

**Comment by sindresorhus** [comment]
npm doesn't preserve indentation, so wouldn't help much. Most people use `npm install --save` which makes npm modify the package.json. I would be willing to add this if npm added supported for preserving the existing indentation, but not worth the overhead when it doesn't.

**Comment by OmgImAlexis** [comment]
Yarn does preserve indentation so that'd be why I never noticed it. Since this and most of your other repos suggest using yarn over npm would you be willing to add it based on that?

**Comment by sindresorhus** [comment]
Ah, I didn't know that. I think it makes more sense to just preserve the existing indentation though, than specifically read `.editorconfig`. Could just get the indentation with [`detect-indent`](https://github.com/sindresorhus/detect-indent). Pull request welcome.

**Comment by yatharthk** [comment]
@sindresorhus I am picking this up. But not really sure if we need to make this improvement in `ava-init` package or should we do it to `write-pkg` itself? 😄

**Comment by sindresorhus** [comment]
@yatharthk Good idea, let's add it to `write-pkg`.

**Comment by sindresorhus** [comment]
For reference, npm@5 will also preserve the indentation, so this will be much needed soon :)

**Comment by OmgImAlexis** [comment]
Would it not be better to add an auto option to `write-json-file`?

**Comment by yatharthk** [comment]
@sindresorhus Cool, then I'll should open an issue and work for indent-preservation on `write-pkg`.

**Comment by sindresorhus** [comment]
> Would it not be better to add an auto option to write-json-file?

👍
