### ISSUE TITLE
Tests consume too much memory

### ISSUE THREAD

**Issue by Brzda** [avajs/ava#1365]
We have cca 180 tests and they consume cca 3GB memory. I tried run ava with `--serial` option, nothing change. I tried remove node_modules, clean cache and install packages again, nothing change. It happens on linux and windows all the time.

Versions:
```
node: 6.10.1
ava: 0.19.1
babel-register: 6.24.1
```

Ava configuration:
```
"ava": {
    "files": [
      "tests/**/*.test.js"
    ],
    "require": [
      "babel-register"
    ],
    "babel": "inherit"
  }
```

Are we doing something wrong?

Example test:
```
test('loading categories success', t => {
  const oldState = { fetching: true, error: null, categories: [] }
  const categories = ['Category 1', 'Category 2']
  const action = { type: Types.LOADING_CATEGORIES_SUCCESS, categories }
  const newState = { fetching: false, error: null, categories }
  t.deepEqual(reducer(Immutable(oldState), action), newState)
})
```

**Comment by novemberborn** [comment]
Across how many files are those tests distributed? `--serial` runs one test at a time, but still launches processes for each test file, all at once. Try `--concurrency` to reduce the number of concurrent processes, which should help with the memory consumption (assuming you have loads of test files).

**Comment by Brzda** [comment]
We have cca 30 files with tests. I tried run ava with `--serial` and `--concurrency` option, but nothing change.

**Comment by novemberborn** [comment]
> I tried run ava with --serial and --concurrency option, but nothing change.

Did you specify a concurrency value? Try `--concurrency=3`.

**Comment by Brzda** [comment]
Oh, very thanks. It helped.

**Comment by novemberborn** [comment]
Great! I've opened https://github.com/avajs/ava/issues/1367, it would have been useful if AVA had warned you that you didn't specify a concurrency value.
