### ISSUE TITLE
Change snaphots directory name

### ISSUE THREAD

**Issue by ngryman** [avajs/ava#1368]
Hi,

This is a small thing, but it would be nice to be able to choose a different snapshots directory name. `__snapshots__` feels like `jest` convention, not `ava` convention if I may say so.

Thanks!

**Comment by sindresorhus** [comment]
Yes, with https://github.com/avajs/ava/pull/1341, we'll use `__snapshots__` only if you use `__tests__`, otherwise `snapshots`.

**Comment by ngryman** [comment]
@sindresorhus Awesome. Thanks!.
