### ISSUE TITLE
Interrupt test workers caught in an infinite loop

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1378]
As suggested by @molsson in https://github.com/avajs/ava/issues/1377#issuecomment-299709992, AVA should "detect bugs where a synchronous function accidentally ends up in an infinite loop."

Users might expect `--timeout` covers this, but it merely calls `fork.exit()`, which only [sends an `init-exit` message to the worker](https://github.com/avajs/ava/blob/a1e08ab8fea773daab3489f05ad47fdd7f202644/lib/fork.js#L152:L153). If the worker is blocked then it'll never process that message, and it won't exit.

We need to decide whether to detect this case purely with `--timeout`, in which case we can kill the worker process if it doesn't exit within a few seconds (perhaps the `--timeout` period?).

Alternatively we could always detect this, by sending occasional pings to the worker.

**Comment by ORESoftware** [comment]
upont --timeout, send a SIGINT, followed by SIGKILL after a grace period

**Comment by novemberborn** [comment]
> Users might expect --timeout covers this, but it merely calls fork.exit(), which only sends an init-exit message to the worker. If the worker is blocked then it'll never process that message, and it won't exit.

With #1722 we'll force the worker to exit without relying on IPC. If we fix #583 then we can clearly communicate which tests were active and thus may have caused the infinite loop.

#1718 proposes we don't automatically exit the process once the last hook has completed. This makes processes that never drain their event loop indistinguishable from those that have an infinite loop, as far as the main process is concerned.

I suggest we set a default timeout to say 60 seconds, and then force any active worker processes to exit.

**Comment by sindresorhus** [comment]
> Alternatively we could always detect this, by sending occasional pings to the worker.

👍

**Comment by novemberborn** [comment]
I believe our current timeout logic is sufficient.
