### ISSUE TITLE
snapshot tests failing with `Cannot read property 'split' of null`

### ISSUE THREAD

**Issue by pho3nixf1re** [avajs/ava#1381]
## Description

When snapshots do not match a type error is thrown instead of the diff. `TypeError: Cannot read property 'split' of null`.

### Test Source

```jsx
import React from 'react';
import test from 'ava';
import { render } from 'enzyme';

const TestMe = ({ me }) => (
  <div>
    <p>{me}</p>
  </div>
);

test('renders the component', t => {
  const wrapper = render(<TestMe me='change me' />);
  t.snapshot(wrapper.html());
});
```

### Error Message & Stack Trace

```
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
  ✖ renders the component Error thrown in test

  1 test failed [11:04:02]

  renders the component
  /path/to/example.test.js:13

   12:   const wrapper = render(<TestMe me='change us' />);
   13:   t.snapshot(wrapper.html());
   14: });

  Error thrown in test

  Error:

    [TypeError: Cannot read property 'split' of null]
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "require": [
      "babel-register",
      "./test-environment.js"
    ],
    "babel": "inherit",
    "files": [
      "**/*.test.js",
      "!node_modules"
    ]
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava --verbose path/to/example.test.js
```

## Relevant Links

https://gist.github.com/pho3nixf1re/4c23d77709ce4ef044ebae7c937940ec

## Environment

```
Node.js v7.10.0
darwin 16.5.0
AVA 0.19.1
npm 4.2.0
yarn v0.23.4
```

**Comment by pho3nixf1re** [comment]
This even fails with a more trivial example...

```js
import test from 'ava';

test('renders the component', t => {
  t.snapshot('change me');
});
```

**Comment by novemberborn** [comment]
I suspect this comes from https://github.com/avajs/ava/blob/2ed94853ddd2ca4614a82b2a79cc251c09212331/lib/assert.js#L256, but since that's internal to AVA it's not in the stack trace that's shown.

This implies that `jest-diff` somehow doesn't provide us with a diff, which is annoying. Open to a bugfix, otherwise this will get superseded by #1341.

**Comment by pho3nixf1re** [comment]
I'll verify and get a quick fix up if it's simple.

**Comment by mmmveggies** [comment]
For those who end up here looking for a fix, you can delete the corresponding entry in the `__snapshots__/` folder. You lose your snapshot history but it will fix the bug

**Comment by novemberborn** [comment]
#1341 has landed. A new release will be out soon.
