### ISSUE TITLE
How can I test cluster related modules?

### ISSUE THREAD

**Issue by zhengqingxin** [avajs/ava#1386]
## Description
I want to test a cluster related module, I found the test case execute once, and `cluster.isMaster` is always true, is there any way to resolve this except mock cluster?

### Test Source

```js
test('test case', async t => {
  let options = {
    workers: 1,
  };
  let ClusterMaster = getClusterMaster();
  if(cluster.isMaster){
    // always master
    let instance = new ClusterMaster(options);
    instance.forkWorkers().then(()=>{console.log(1)});
  }else{
    // cannot entry this block
    console.log('worker running');
    try {
      http.Server((req, res) => {
        res.writeHead(200);
        res.end('hello world\n');
        process.send({cmd: 'notifyRequest'});
      }).listen(8000);
    } catch (e) {
      console.log(e);
    }
  }
});
```

**Comment by novemberborn** [comment]
You can't use `cluster` inside AVA's test workers. Best bet would be to launch a child process from your test, which can act as the master, and then have that process launch the workers. You'd have to communicate with your test through stdout. Have a look at [`execa`](https://github.com/sindresorhus/execa).

**Comment by zhengqingxin** [comment]
@novemberborn Got it.Thanks for your guide.
