### ISSUE TITLE
Press 'u' in watch mode to update snapshots

### ISSUE THREAD

**Issue by lukescott** [avajs/ava#1387]
Ava borrows Jest's snapshot feature, and from #1275 and other issues, this feature is evolving in Ava. That's really awesome.

Jest, in addition, has an interactive watcher that:

- Runs only tests related to files that have changed
- Replaces previous console output of passing tests
- Provides commands to interact with the running watcher

One of the commands is `u`, which updates snapshots of tests that just ran.

I became familiar with Ava thru @novemberborn when working on `babel-plugin-import-glob`. I really like Ava, especially with the TAP-like syntax.

Ava just needs an interactive watcher to compliment the snapshot feature.

**Comment by sindresorhus** [comment]
We already do the first thing, but I agree, the rest would be very useful too.

**Comment by novemberborn** [comment]
Let's focus this issue on the `u` command:

> One of the commands is u, which updates snapshots of tests that just ran.

**Comment by masaeedu** [comment]
@novemberborn Is there already an issue for a proper interactive UI? I had no idea there was a `u` option since it didn't seem to be documented, and the console UI provides no indication that this shortcut is available.

**Comment by novemberborn** [comment]
@masaeedu yes, see #1525.
