### ISSUE TITLE
ava transformer cache and babel-plugin-import-glob

### ISSUE THREAD

**Issue by lukescott** [avajs/ava#1388]
I use @novemberborn's `babel-plugin-import-glob` and ran into an issue where files containing wildcard glob imports would not get updated due to transformer cache. This would cause tests to fail/pass when files were removed/added.

Is there a way to exclude specific files from the cache? All I could find were `--no-cache`. Or perhaps a better solution?

I originally found this issue with Jest. I opened an issue with them, but they told me to keep my files idempotent and closed the issue. With Jest I came up with [babel-jest-import-glob](https://github.com/lukescott/babel-jest-import-glob) as a solution. It wraps the `babel-jest` transformer and adds the glob result to the cache key for those files.

Looking to do something similar in AVA, but it doesn't look like AVA has an option to replace the transformer.

**Comment by novemberborn** [comment]
Interesting. I don't think we'd take our Babel support in the direction that Jest has, which makes your `babel-jest-import-glob` workaround a non-starter for AVA. There's a lot of trade-offs that need to be made to ensure the test file compilation is performant. Non-idempotent transforms make that really difficult. I don't see a good way out of that. Probably the same limitations apply to Jest.

I suppose you could run AVA multiple times, where `--no-cache` is only used for those files that can't be cached, but that's not ideal.

Or you could precompile test files, or place `import-glob` in a source file that is precompiled? 

The best approach may be to write a `importGlob()` method that works like the proposed `import()`. That way you could get the same behavior as `import-glob` but at runtime.

**Comment by lukescott** [comment]
I think an option to exclude specific file(s) from the cache would be a good start. That's what I originally asked for from Jest, but they declined. That's why I came up with the babel-jest wrapper, which ended up working better (it only does the transform if a file is added/removed).

So in AVA you could have something like `--cache-exclude=path/to/wild.js,...`, which would have a similar option to add in a config file / package.json.

I do encourage custom transforms though. I've currently using TypeScript at work, and it would be awesome to use that for the transformer. Or both. I know there is a workaround that involves `tsc && ava`, but that involves writing extra files to the filesystem. The beauty behind the custom transform is you can do it all in memory in a single pipeline.

I would take a different approach from Jest though. If I want to combine Babel and TypeScript, for example, I have to do a third custom transform. I would do something more like webpack's loaders. In fact it would be amazing if AVA was compatible with webpack's loaders (not sure if that's technically possible).

**Comment by novemberborn** [comment]
We have an [RFC for improving language support](https://github.com/avajs/ava/blob/master/docs/specs/001%20-%20Improving%20language%20support.md), including better TypeScript handling. If we establish a common interface we could open that up to any kind of language.

I'm not sure about letting users exclude certain files from the caching. It seems very niche, and I haven't yet seen use cases where there isn't an alternative approach that is almost as good as what the user was trying to achieve initially.

**Comment by lukescott** [comment]
If there is another solution, other than doing `--no-cache`, I'm all for it. My concern with `--no-cache` is it excludes every file, which for wildcard glob imports is really only needed for one or two files in the project.

**Comment by novemberborn** [comment]
You could do `"test": "ava --no-cache test/globbing-test.js && ava 'test/*.js,!test/globbing-test.js'"` or something along those lines.

**Comment by novemberborn** [comment]
We won't implement specific cache exclusions any time soon. Closing this for now.
