### ISSUE TITLE
Allow `ava.config.json` instead of package.json or CLI

### ISSUE THREAD

**Issue by nowy** [avajs/ava#1394]
## Description

This is a feature request.

There are currently two ways of setting up ava config (prioritised):
1. CLI arguments
2. Package.json

Proposal: **Add a third way, through ava.config.json**

Advantages:
- Slimmer package.json file
- Easier to handle environment-specific config
- More flexibility on project configuration

Ie. This code in `package.json`, could be defined in `ava.config.json`

```json
{
  "ava": {
  ...
  }
}
```

Also adding a flag to specify the config file (falling back to `ava.config.json`) if need be:
```
ava --config-file my.ava.config.json
```

## Other technologies that handle this:

- TypeScript: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
- Webpack: https://webpack.js.org/configuration/configuration-types/

I would be willing to submit a PR if approved.
Thanks

**Comment by kevva** [comment]
This has been discussed in length in multiple issues already, e.g, https://github.com/avajs/ava/issues/520.
