### ISSUE TITLE
Using without babel

### ISSUE THREAD

**Issue by rightaway** [avajs/ava#1404]
I'm using node 7.10 without babel since the ES6 features I want are included in this node version. I'm using the latest version of ava and am getting a syntax error `SyntaxError: Unexpected token ...` when using ES6 functionality: `super({ ...object, prop: value })`. If I understand it right this is a bug, since my code in node works fine in my application but fails just when this code runs under ava.

**Comment by sindresorhus** [comment]
Object spread is still just a proposal: https://github.com/tc39/proposal-object-rest-spread

**Comment by niftylettuce** [comment]
@sindresorhus do you think the node env in particular should have this as a default as an ava babel plugin since it's supported since node v8.3+ though?  it's weird to not be able to write tests out of the box with ava that use object rest spread.

**Comment by sindresorhus** [comment]
@niftylettuce Yes, see: https://github.com/avajs/babel-preset-stage-4/issues/7 Help welcome.
