### ISSUE TITLE
Feature request to make it possible to inspect an error

### ISSUE THREAD

**Issue by rightaway** [avajs/ava#1405]
Right now if a test unexpectedly throws an error, the only output given for that error in the console is something like `[MyError: my error message]`, which is the error's `name` and `message` properties. But often I'd like to inspect the error in more detail and print its other (custom) properties to the console, to make it easy to see where things failed.

I'd like to request a feature where when an error is thrown, it gets passed to a callback where for example you can inspect it further.

**Comment by novemberborn** [comment]
With #1341 we'll print all enumerable properties on the error object. I've just started a contract so I'm a bit pressed for time with regards to finishing that PR.

Would this solve your problem? I'm not sure the callback would do anything more than you couldn't do with a `try/catch` in your test.

**Comment by novemberborn** [comment]
#1341 has landed. A new release will be out soon.
