### ISSUE TITLE
Raise events to allow better external integration

### ISSUE THREAD

**Issue by ArtemGovorov** [avajs/ava#141]
Hey guys, AVA looks promising!

I have started adding AVA support to wallaby.js and so far it looks awesome:

![n](https://cloud.githubusercontent.com/assets/979966/10989814/c57074ca-8497-11e5-89cd-73bd78c6d371.gif)

I did however have to monkey-patch a couple of functions to get the data I need for the integration. Other testing frameworks, such as Mocha and Jasmine, expose some APIs (in one form or another) to allow external integrations. For example via their reporters one may get an event when a test/hook is about to start and when the test is finished, etc.

While I understand that AVA's idea is to stay simple, I don't think raising a few events would hurt the simplicity much. Would you be ok to raise more events from `Runner`? Happy to send a PR if you are not opposed to the idea.

**Comment by vdemedes** [comment]
Glad you like AVA!

Could you please provide some examples, what kind of events are you interested in?

**Comment by ArtemGovorov** [comment]
Here are a couple events from `Runner` I'm interested in:
- an event before a test starts, passing the `Test` instance.
- an event when a test completes, passing the `Test` instance.

I know there's the `test` event raised from `Runner`, it somewhat addresses the second even request, but it would also be great to have a `hook` property on the `Test` instance to be able to distinguish between tests and hooks in those events.

**Comment by vdemedes** [comment]
Sounds reasonable to me, I think it'd be great to have this anyway.

@sindresorhus @kevva what do you think?

**Comment by sindresorhus** [comment]
Cool! Makes sense. PR welcome.

**Comment by novemberborn** [comment]
Let's move the discussion to #1043.
