### ISSUE TITLE
From v0.18 onwards, cannot disable default globs

### ISSUE THREAD

**Issue by wmertens** [avajs/ava#1412]
## Description

I have a project where I have subdirectories with test files that AVA should not be running. When I provide a glob to AVA in v0.17, this is not a problem. From 0.18 onward, it seems that AvaFiles is instantiated twice, once with the given glob and once with the defaults.

### Test Source

to test, put a `foo.test.js` in some subdirectory and put a `throw` in there. Then run AVA with a glob that does not match `foo.test.js`.

### Config

This fails with and without any config.

### Command-Line Arguments

```
ava build/**/*.js
```

## Environment

darwin 16.5.0

11458 $ ava --version
0.19.1

11459 $ npm --version
4.2.0

**Comment by wmertens** [comment]
Turns out the second run is for the helpers, and AVA is trying to precompile a failing helper that is not being used at all.

Maybe this could be solved by #1292, having excludes also apply to helpers? Or allowing specifying the helpers glob?

**Comment by novemberborn** [comment]
Yea this isn't ideal. I think the best thread is #736. There are ideas floating around on how to improve all this.

I suppose you could remove the helper file that isn't being used?
