### ISSUE TITLE
Side question - TS -> JS

### ISSUE THREAD

**Issue by ORESoftware** [avajs/ava#1415]
Just an aside question! :) So the master branch is all JS, but it appears much of your true source code is TypeScript. Are contributors supposed to create PRs against a branch other than master?

I read contributing.md, and looked at this too:
https://github.com/dchelimsky/rspec/wiki/Topic-Branches

I guess my main question is - if we want to contribute to the TypeScript code, how do we do that? Because it seems clear that the TS source is not in the master branch. Or maybe the source doesn't have any TS and you just export TS types?

**Comment by novemberborn** [comment]
Which branch are you referring to?

We do generate a TypeScript definition, but that's about it. See https://github.com/avajs/ava/tree/master/types.

**Comment by ORESoftware** [comment]
ok nevermind, lol
