### ISSUE TITLE
Endpoint testing with Mongomem and supertest?

### ISSUE THREAD

**Issue by zellwk** [avajs/ava#1417]
## Description

Hey all, I'm trying to combine AVA with Mongomem and Supertest as mentioned in `docs/recipes`, but the test just hangs when I tried calling a mongoose model method like`User.findOne({})` in any of my tests. 

How can I reference the correct mongoose instance within my endpoint tests? 

I tried checking for `mongoose.connection.readyState` in both my test and server files. `test.js` shows readyState 1. `server.js` shows readyState 0. 

### Test Source

Here's my spec file: 

```js
import test from 'ava'
import mongoose from 'mongoose'
import request from 'supertest'
import { MongoDBServer } from 'mongomem'
import { createFixtures, dropFixtures } from '../../fixtures/'

const setupMongoose = async _ => {
  const db = new mongoose.Mongoose()
  db.Promise = global.Promise
  await db.connect(await MongoDBServer.getConnectionString())

  require('../../models/Course')
  require('../../models/User')

  for (const name of mongoose.modelNames()) {
    db.model(name, mongoose.model(name).schema)
  }

  return db
}

test.before('start server', async t => await MongoDBServer.start())

test.beforeEach(async t => {
  const db = await setupMongoose()
  const User = db.model('User')
  const Course = db.model('Course')
  await createFixtures(Course, User)

  const app = require('../../server')
  t.context.db = db
  t.context.app = app
})

test('Pass POST v1/users/testing', async t => {
  const { app } = t.context
  const res = await request(app)
    .post('/test')
    .send({
      email: 'testing@email.com'
    })
  t.is(res.status, 200)
})
```

Here's `server.js`
```js
const express = require('express')
const routes = require('./routes')
const isProduction = process.env.NODE_ENV === 'production'
const app = express()
const User = require('./models/User')

app.use('/test', async (req, res) => {
  const { email } = req.body
  console.log(mongoose.connection.readyState);
  const r = await User.findOne({email})
  res.json(r)
})

module.exports = app
```

### Error Message & Stack Trace

```
> course-server@1.0.0 watch /Users/zellwk/Projects/private-repos/course-server
> NODE_ENV=test ava test/**/* --watch

  1 passed [22:31:20]
  1 failed

  routes › register › Pass POST v1/users/testing

  Rejected promise returned by test

  Rejection reason:

    [Error: socket hang up]
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "test": "NODE_ENV=test ava test/**/*",
}
```

## Relevant Links

(Working on a repo for a reduced test case) 

## Environment

Node - v7.1 
npm - 4.2.0
ava - 0.19.1 (installed locally with npm install)

**Comment by zellwk** [comment]
Managed to find a way. Awaiting the mods to see if they'll like me to write docs for it. Hence, closing.

**Comment by snarfed** [comment]
hey @zellwk what was your solution to this? i have the same problem with ava + express + supertest, or at least similar. it's fine when tests pass, but when there's an uncaught exception in async code, it hangs forever.

**Comment by zellwk** [comment]
@snarfed My process is written in the docs now: https://github.com/avajs/ava/blob/master/docs/recipes/endpoint-testing-with-mongoose.md
