### ISSUE TITLE
How to specify an alternative location for the babelrc

### ISSUE THREAD

**Issue by CMCDragonkai** [avajs/ava#1419]
The documentation (https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#extend-an-alternate-config-file) states that you can extend with an alternative location. I tried to do this in the package.json:

```
  "ava": {
    "require": [
      "babel-register"
    ],
    "babel": {
      "extends": "test/.babelrc"
    }
  }
```

It doesn't work when my `test/.babelrc` is:

```
{
  "presets": ["env"]
}
```

The error is just: 

```
/home/cmcdragonkai/Projects/js-resource-counter/node_modules/ava/lib/cli.js:196
                                        throw err;
                                        ^
ParseError: /home/cmcdragonkai/Projects/js-resource-counter/.babelrc: Error while parsing — Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""
    at parseFile (/home/cmcdragonkai/Projects/js-resource-counter/node_modules/hullabaloo-config-manager/lib/collector.js:27:11)
    at Object.parse (/home/cmcdragonkai/Projects/js-resource-counter/node_modules/hullabaloo-config-manager/lib/collector.js:103:25)
    at fromFile.then.then.result (/home/cmcdragonkai/Projects/js-resource-counter/node_modules/hullabaloo-config-manager/lib/collector.js:120:63)
From previous event:
    at Api.run (/home/cmcdragonkai/Projects/js-resource-counter/node_modules/ava/api.js:71:5)
    at Object.exports.run.err [as run] (/home/cmcdragonkai/Projects/js-resource-counter/node_modules/ava/lib/cli.js:187:7)
    at Object.<anonymous> (/home/cmcdragonkai/Projects/js-resource-counter/node_modules/ava/cli.js:22:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! Test failed.  See above for more details.
```

**Comment by novemberborn** [comment]
The error says it tried to parse `js-resource-counter/.babelrc` though:

```
ParseError: /home/cmcdragonkai/Projects/js-resource-counter/.babelrc: Error while parsing — Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""
```

Could you try `"extends": "./test/.babelrc"`?

**Comment by CMCDragonkai** [comment]
Still doesn't work.

It also doesn't work, if I just specify babel settings inside package.json like:

```
  "ava": {
    "require": [
      "babel-register",
      "babel-polyfill"
    ],
    "babel": {
      "presets": ["env"]
    }
  },
```

No matter what, it only works when I have `/.babelrc` at project root.

**Comment by novemberborn** [comment]
There's two separate issues at play here. AVA needs to compile the tests. Since you're requiring `babel-register` that will be used to compile any sources you may require.

AVA resolves its Babel config starting at `package.json#ava.babel`. Separately, `babel-register` resolves it from `.babelrc` (or `package.json#babel` if the `.babelrc` file is missing).

The error in your original post came from AVA not being able to resolve its Babel config. Your current problem is probably `babel-register` not doing any compilation since it doesn't have any config.

---

This is pretty hard to resolve without seeing your actual project though.

**Comment by CMCDragonkai** [comment]
Main issue is that I want to isolate the babel configuration for tests
different from my build and dev. For building, I use rollup and it allows
me to specify babel config in rollup.config.js. I can bring in babel
plugins for resolving and compiling and finally bundling the output. So
what's the best way to have an ava specific babel config that also brings
in babel register and babel polyfill?

**Comment by novemberborn** [comment]
> So
> what's the best way to have an ava specific babel config that also brings
> in babel register and babel polyfill?

Put the Babel options for your source code in a `.babelrc`. `babel-register` will pick that up, and if necessary you should configure `rollup` to do the same.

It's not clear to me if you even need to customize AVA's Babel config (which is only applied to test files). If you do, specify it it `package.json#ava.babel` and extend `.babelrc`.

**Comment by CMCDragonkai** [comment]
Ok, what about the extends property, it's still not finding the alternative location? Or is it because babel-register doesn't use the extends property and still looks for a `.babelrc` at project root?

**Comment by novemberborn** [comment]
`babel-register` doesn't look at `package.json#ava.babel`.
