### ISSUE TITLE
Flaky AppVeyor test for watcher not rerunning tests when they write snapshot files

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1427]
The `watcher does not rerun test files when they write snapshot files` [test](https://github.com/avajs/ava/blob/0e82f8f/test/cli.js#L310:L334) is flaky on AppVeyor. It relies on the watcher picking up the file system events. Presumably the [event debouncer](https://github.com/avajs/ava/blob/652705b735b818c9a206b35cc06f3760e6dcea13/lib/watcher.js#L28) is too fast for AppVeyor. This may also be a problem for users in general.

Perhaps we need to slow the debounce internal on AppVeyor, or even make it configurable? @avajs/core?

**Comment by sindresorhus** [comment]
Just make it slower for AppVeyor. AppVeyor is notoriously slow.

**Comment by sindresorhus** [comment]
@novemberborn Can we close this as we're not using AppVeyor anymore?
