### ISSUE TITLE
Configurable cache directory

### ISSUE THREAD

**Issue by langri-sha** [avajs/ava#1436]
## Description

Currently we can only use `cacheEnabled` to control caching, with the cache directory ultimately resolved by `find-cache-dir` (or, in case a path isn't found, a temporary directory).

While it is definitely convenient that a cache directory is picked for us, it would still be nice to have control over the final cache destination. For instance those of us using Yarn get their `node_modules/` directory wiped clean on every lock file change.

**Comment by sindresorhus** [comment]
> it would still be nice to have control over the final cache destination.

That is most likely not going to happen. We prefer for things to *just work*. We would be happy to work with you to improve the Yarn experience though.

> For instance those of us using Yarn get their `node_modules/` directory wiped clean on every lock file change.

Are you sure? How do I reproduce that?

**Comment by langri-sha** [comment]
Here's the quickest way to reproduce:

```
# Change into package directory
cd ~package/
# Use Yarn, get lock file generated
yarn install

# Great! Let's add something
touch node_modules/princess.js
# Force lock file change
yarn install --force
# The princess has left the castle :|
```

**Comment by novemberborn** [comment]
npm doesn't remove `node_modules/.cache` even as it cleans up redundant packages. If this is still an issue then I'd suggest you raise an issue with Yarn to adopt this behavior. (I've tried searching for an existing issue but it's hard to search for ".cache" 😉 )

**Comment by langri-sha** [comment]
@novemberborn I don't think you'll have much luck searching their issues, because this with storing something that's not a package alongside other packages has been invented here and I'm not certain why they should be the ones adding support for quirks. 

I'll try my luck at `find-cache-dir`.
