### ISSUE TITLE
Question: How can I get ava to run babel to transpile my source files every time the watch is triggered?

### ISSUE THREAD

**Issue by davidnagli** [avajs/ava#1437]
I use Ava with the —watch flag, however my source files require transpilation (since they use ES6 export which isn’t supported by Node). How can I get Ava to trigger babel transforms before running, or vice versa (babel watches files and triggers Ava after transpiling).

**Comment by StoneCypher** [comment]
[like this](https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md)

**Comment by davidnagli** [comment]
It didn't work with watch mode.

**Comment by wmertens** [comment]
@davidnagli are you sure? It works fine for me - I use https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#transpiling-tests-and-sources-the-same-way
