### ISSUE TITLE
Unexpected throw in `.throws()`

### ISSUE THREAD

**Issue by StoneCypher** [avajs/ava#1439]
You can replicate by pulling [my repo](https://github.com/StoneCypher/jssm) and uncommenting the [commented-out test](https://github.com/StoneCypher/jssm/blob/master/src/js/tests/general.js#L779).

### Test Source

```js
  it('probable exits for throws on non-state', t => t.throws(() => {
    const machine = new jssm.machine({
      initial_state: '1',
      transitions:[
        { name:'id1', from:'1', to:'2', action:'identical' }
      ]
    });
    // why does this test fail Threw unexpected exception: 'No such state "3" in probable_exits_for' >:(
    machine.probable_exits_for('3');
  }, Error));
```

### Error Message & Stack Trace

```
  general › Illegal machines probable exits for throws on non-state
  /Users/johnhaugeland/projects/jssm/src/js/tests/general.js:780

   779:                                                                     
   780:   it('probable exits for throws on non-state', t => t.throws(() => {
   781:                                                                     

  Threw unexpected exception:

  'No such state "3" in probable_exits_for'
```

The exception is expected, and that is the correct exception message.

This test is a `.throws()`.  I don't understand why this is treated as a failure.  Near-verbatim identical tests cover my other `throw`s and work as expected.

### Config

I do not configure Ava.  No such block or .rc exists in my project.

### Command-Line Arguments

[My build is trivial](https://github.com/StoneCypher/jssm/blob/master/package.json#L11).

```
    "test": "ava src/js/tests/*.js",
```

## Relevant Links

[This is the repo](https://github.com/StoneCypher/jssm).

## Environment

Replicates under MacOS current and Windows 10 Pro current.  Both tested under node 8 current.

Replicates on travis-ci under node-6, node-7, and node-8, all current, all under whatever linux they use.

All are using ava 0.20.0, installed as local node modules.

**Comment by sindresorhus** [comment]
You're throwing a string and not an Error object: https://github.com/StoneCypher/jssm/blob/6f22cc476a2a24476a10f6d5c8f75bead619f48e/src/js/jssm.js#L265

**Comment by StoneCypher** [comment]
Oh.

May I please recommend that the error message here point that out as a possibility?  It would not have occurred to me that throwing a string wouldn't be caught by `.throws` .

**Comment by StoneCypher** [comment]
And/or should strings thrown be caught by `.throws` ?

**Comment by kevva** [comment]
You should use `throw new Error(string)` in your code. Read more about the `Error` object here https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Error#Throwing_a_generic_error.

**Comment by StoneCypher** [comment]
@kevva - sorry, no, `throw` can and always has legally accepted strings, as [the first example on your source shows](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw).

**Comment by kevva** [comment]
I'm aware of that, but it's a bad practice.

**Comment by StoneCypher** [comment]
this is not a duplicate of 661; the behavior is entirely different, and does not appear to be defective in presentation

this is not a duplicate of 1047, which is about simplifying `throws`, and barely touches on this in passing

i wish this had not been closed, and generally it's polite to ask the person opening the ticket before closing

i retain the belief that `throws` should accept all valid `throw`s, which it currently does not, without mentioning that in the documentation

**Comment by sindresorhus** [comment]
@StoneCypher It's because you specified it to expect an `Error` object in the assertion, but you threw a string. I've opened https://github.com/avajs/ava/issues/1440 instead to improve the experience.

**Comment by StoneCypher** [comment]
Thank you.
