### ISSUE TITLE
`Buffer.alloc` is not a function

### ISSUE THREAD

**Issue by jagged3dge** [avajs/ava#1446]
## Description
Seems like the `Buffer.alloc` api was introduced in node v5.10+. Since I'm using node v5.9.1, and ava's `package.json` specifies valid engines as `">=4"`, I'll have to upgrade my node install to play with ava. Running a silly test throws a NAF error as shown below.

I know I can upgrade my node to 5.10.0 and keep going. Just reporting this in case there are others facing this problem.

Moving forward, should the `package.json`'s `engines` key to at least `5.10.0` of node?
Or keep the `engines` as it is, and change the `Buffer.alloc` call to something suitable for older node versions?

### Test code
```
const test = require('ava')
const users = require('../resources/users.methods')

test('should return all users in db', async function (t) {
  const fetchedUsers = await users.getAll()
  t.truthy(fetchedUsers.length)
})
```

### Error Message & Stack Trace

```
$ ava
D:\Work\server-express\node_modules\ava\lib\snapshot-manager.js:21
const VERSION_HEADER = Buffer.alloc(2);
                              ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (D:\Work\server-express\node_modules\ava\lib\snapshot-manager.js:21:31)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\Work\server-express\node_modules\ava\lib\assert.js:10:25)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\Work\server-express\node_modules\ava\lib\serialize-error.js:5:16)
    at Module._compile (module.js:413:34)

  1 exception

  × routes\users\users.methods.test.js exited with a non-zero exit code: 1
```

### Config

Copy the relevant section from `package.json`:

Defaults. No custom config in `package.json`

### Command-Line Arguments

```
ava
```

## Environment

```
Node.js v5.9.1
win32 6.1.7601
ava 0.20.0
```

**Comment by novemberborn** [comment]
Node.js 5 has been unsupported for a year, and with [yesterday's security release](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/) has definite vulnerabilities that will never be patched. You need to move up to Node.js 6.

---

This code works with Node.js 4.5, though not earlier versions. Which is unfortunate since AWS Lambda runs 4.3 (and also 6.10). We do want to solve this.

This code should use [`safe-buffer`](https://www.npmjs.com/package/safe-buffer) instead of accessing `Buffer` directly. We should also run tests on 4.3 so we'll be aware of breakage like this.

If anybody wants to help out with this please feel free!

**Comment by ajtorres9** [comment]
Hey @novemberborn when you say we should run test on 4.3, should that be in addition to running tests on the latest 4.x release (which is what Travis CI currently does) or should the `.travis.yml` file be modified to specify 4.3 as opposed to 4?

**Comment by novemberborn** [comment]
In addition. We still want to test the latest of 4.
