### ISSUE TITLE
Convert documentation to a more accessible format

### ISSUE THREAD

**Issue by jottr** [avajs/ava#1454]
Currently the documentation is available in a single README.  
I would like to suggest to convert the documentation to a format which can be consumed by other tools, e.g. [Dash](https://kapeli.com/dash) or [devdocs.io](http://devdocs.io). 
I found that publishing documentation via [readthedocs.io](https://readthedocs.io), which uses sphinx to convert markdown files to the final documentation ([tutorial](https://docs.readthedocs.io/en/latest/getting_started.html)), yields great results. 
Sphinx-generated documentation can be consumed by Dash, and should be easily scrapable for devdocs. 

On a side note, I found the [API documentation](https://github.com/avajs/ava#api) too sparse, some methods are not explained in that section, but must be searched for in other sections (e.g. `test.serial`, `test.cb`, and so on).  

I found it rather difficult, at times even confusing, when trying to look up a certain method.

**Comment by novemberborn** [comment]
I'm definitely in favor of moving the API documentation out of the README, into something that's better organized and more complete.

I'm not sure how great a fit these documentation websites are. We'd have to see if hosting Markdown files on GitHub is sufficient, or whether we should use `devdocs` / `readthedocs` / etc, in lieu of building an AVA website.

@avajs/core?

**Comment by sindresorhus** [comment]
I'm totally 👍 for this, just needs to be a solution with little overhead. I don't want a big build step.

**Comment by jottr** [comment]
There's a bunch of tools specific to API documentation, e.g. [swagger](https://swagger.io/) and [the likes](http://nordicapis.com/ultimate-guide-to-30-api-documentation-solutions/). 
I'd love to help improve the documentation. 
@sindresorhus do you have any preference?

**Comment by sindresorhus** [comment]
>  e.g. swagger and the likes.

Seems like these are for web APIs, not libraries.

**Comment by sindresorhus** [comment]
I'm not really up to date on what people use for API docs these days, but I would prefer something where we could write it manually instead of it parsing JSDoc comments. I like the freedom of hand-crafting docs, as generated ones are always bad. Happy to hear suggestion on what we should use.

**Comment by jamiebuilds** [comment]
Maybe all the documentation could be pulled into the `docs` directory in separate files and published to a very simple markdown-to-html website using GitHub Pages (with Jekyll) or [Netlify](https://www.netlify.com) (with anything).

Netlify is cool cause it will automatically run on PRs and give you a unique URL to preview the website on every change

**Comment by sindresorhus** [comment]
@jamiebuilds The docs site should show the latest version, not master, so I don't think we can use the `docs` directory approach.

**Comment by sindresorhus** [comment]
https://docusaurus.io/ could be an option too, it's not simple though.

**Comment by jamiebuilds** [comment]
You can make it so that you manually select which version of the site to deploy with Netlify.

- Deploy with Netlify on every master build
- Turn off auto-publishing
- When releasing, publish the latest deployed version

**Comment by jamiebuilds** [comment]
Docusaurus is also really nice for allowing docs to be translated and versioned. Maybe worth the complexity

**Comment by nklayman** [comment]
What about [vuepress](https://vuepress.vuejs.org)? It supports markdown -> HTML, is open source, has a zero-config build step, and can be deployed anywhere.

**Comment by nklayman** [comment]
If you want, I'd be happy to convert the docs into separate pages for each h2 using vuepress and submit a PR.

**Comment by novemberborn** [comment]
I think as a start I'd like to split the docs across multiple Markdown files in this repository. I'd prefer to do that myself though, I can be a little particular when it comes to this kind of work 😄

**Comment by novemberborn** [comment]
We've now split the docs into multiple files: https://github.com/avajs/ava/tree/master/docs

I'd like to keep the documentation in this repository, but then publish when `master` is built. Then we should also have a way to browse docs for multiple versions. Also, preferably, a free or low-cost option.

**Comment by novemberborn** [comment]
Hey @nklayman, that looks nice! Apologies for waiting this long to get back to you, been a bit busy moving to another country 😄 

I'm concerned about the lack of versioning support (https://github.com/vuejs/vuepress/issues/1018). I've seen a lot of confusion when it's unclear what version of the documentation you're reading, and ideally we can display documentation for previous versions. What do you reckon?

We could host this on GitHub Pages, sure. I ported my site to https://zeit.co/now the other day and that may also work quite nicely.

**Comment by nklayman** [comment]
What about publishing under a different url every time, ie docs.ava.io/v1/, docs.ava.io/v2? You could then create a custom drop-down that would redirect to the correct page. Each url would be its own vuepress app, so search would work fine. There would need to be a way to retrieve new versions from an old page, however.

**Comment by nklayman** [comment]
Does anyone know how to get just the release tag? `https://api.github.com/repos/avajs/ava/releases` gives you a lot of unnecessary info.

**Comment by nklayman** [comment]
How should I authenticate with the API?

**Comment by nklayman** [comment]
Since the graphql api forces use of an authentication token, maybe we should just host a json file with the release data ourselves, as part of the docs site.

**Comment by nklayman** [comment]
Then your access key would be publicly available on the site. I can use a [postversion](https://docs.npmjs.com/misc/scripts) script to automate updating the json file, so it won't be an issue.

**Comment by nklayman** [comment]
Updated my fork to support versioning. It requests the `releases.json`, located in the public folder. It creates a dropdown called "versions" and links each version. The link redirects to `/${version}`. I also added a "version" script which adds the latest release to the `releases.json`. All that's left is to publish each version of the docs to `/${version}`.

**Comment by novemberborn** [comment]
> Updated my fork to support versioning.

Would you mind opening a PR?

**Comment by nklayman** [comment]
https://github.com/avajs/ava/pull/2051

**Comment by novemberborn** [comment]
I'd still like to see this. A lesson learned from @nklayman's attempt is that the solution shouldn't take me more than a couple of hours to evaluate & integrate, anything that requires more time than that is very likely to languish.

This is best achieved if the website code can live in a separate repository.

Furthermore:

* We want to write Markdown files
* We want to have the documentation browsable by release
* We want to include `eslist-plugin-ava`, `@ava/babel` and `@ava/typescript` in the website
* We want to use GitHub Actions to build the documentation
* We want the documentation to be available via https://avajs.dev
* The English-language Markdown files should stay in the relevant repositories, and require little changes
* Ideally, we can pull in translations from `ava-docs`
