### ISSUE TITLE
Snapshot fixture location with transpiled tests

### ISSUE THREAD

**Issue by impaler** [avajs/ava#1459]
When writing tests with something like the Typescript, tests can be transpiled to an output folder and run there. This is problematic when you need to keep the generated snapshots  `*.snap` and `*.md` fixtures in version control and not the build folder.

A lot of build processes will clean the build directory all together with a `rmraf` or similar along with the fixtures. Currently there does not seem to be an api to have a custom location for the [generated snapshot fixtures](https://github.com/avajs/ava/commit/ebd572a02debe8e17802f795e6cd618073c8d787). 

Got any suggestions would anyone consider a user defined location for the snapshot fixtures? @novemberborn

Cheers, ava is great :+1:

**Comment by novemberborn** [comment]
Oh that's an interesting problem to have!

One option may be to resolve the original file location through source maps. That should probably deal with your use case?

Of course source maps aren't always reliable, so I do see the need for a configured location. But then it should be one directory that is used for all test files. There is a risk of multiple test files having the same filename, but existing in different directories. I'm not sure how to handle that problem. We could reproduce the directory structure (relative to the `package.json`), or concatenate the relative file path (but I'm wary of running into file name length restrictions). What do you think @impaler?

**Comment by impaler** [comment]
@novemberborn yes and this feature is the only issue I have when using Ava and Typescript. Ideally using sourcemaps to have the snapshot fixtures next to the source *.ts files would be the best solution, developer experience wise.

I can't speak to the reliability issue with source maps you mention. Currently I am using the a basic tsc command to compile all *.ts files in my project along with the ava tests in ts, to one build folder. I can then the node debugger in Intellij Idea to configured to the ava "profile.js" to successfully use breakpoints etc on the original typescript source without issue, its fantastic. Its working with the sourcemaps generated from the typescript compiler just fine.

On the custom location, I agree one snapshot base directory would make sense for keeping things manageable. Regarding name collisions, maybe a subdirectory of this base path could be derived from the transpiled javascript test __filepath itself?

**Comment by novemberborn** [comment]
I think we should:

* Check if the test file has a source map associated with it, and attempt to resolve the source file path
* Have that source file path take precedence over the test file path when it comes to loading and saving the snapshot
* Add a setting in `package.json#ava` to force snapshots to be stored in the specified global directory. This takes precedence over the source file detection
* When snapshots are stored in a global directory, mirror the file hierarchy of the test file (with the source file path still taking precedence) inside the global directory
* We should also add an integration test where the test file comes from a TypeScript compiler

If anybody wants to pick this up that'd be great.

**Comment by impaler** [comment]
Ok thanks @novemberborn I'll have a try at implementing this.

**Comment by impaler** [comment]
@novemberborn in the commit above it made sense to me to add another cli option `--snapshot-location` think its worth it?

No tests yet, looks like I can add another test block to `ava/test/assert.js` and verify a few of the contexts and add a test sourcemap as you suggest. So far its working with a small test project :)

I saw the project has some interesting typescript support upcoming, I guess that this feature is worthwhile not just for typescript though. Any "compile to js" language would need this.

**Comment by novemberborn** [comment]
> it made sense to me to add another cli option --snapshot-location think its worth it?

That flag would have to be provided on every test run. We've been trying to move such flags into the `package.json` and not have them on the CLI at all.

> I guess that this feature is worthwhile not just for typescript though. Any "compile to js" language would need this.

Yup. Figuring out the actual test file source location seems like a good idea regardless.

**Comment by mariusGundersen** [comment]
I just ran into this same issue, and want to +1 either option (having it find the original .ts file, or having a snapshot-location configuration option).

**Comment by impaler** [comment]
@novemberborn no problem having no `--snapshot-location` cli arg, it was just useful while testing, I doubt there is a more general use case.

Do you think we should add a `package.json#ava` config to enable sourcemap detection? This feature will enforce a `fs.readFileSync` [on every test](https://github.com/impaler/ava/blob/snapshot-location/lib/snapshot-manager.js#L391) where before there was none. Maybe this is not worth worrying about performance?

This is nearly there, when I get some free time next I'll wrap this up in a pull request. Happy if anyone can help test, there maybe some hidden contexts.

**Comment by mariusGundersen** [comment]
Does its need to read the sourcemap file on every test? Isn't it using the same sourcemap that the transpiled test is using? 

I'm OK with a cli arg (as long as it's also a package.json config)

**Comment by impaler** [comment]
@mariusGundersen yes in the scenario for testing javascript that is not transpiled with ava. Ava is then running against a transpiled build folder that includes the sourcemaps. Eg I added this as a test fixture https://github.com/impaler/ava/tree/snapshot-location/test/fixture/snapshots/test-sourcemaps.

So afaik right now ava has no reason to check and store any existing sourcemaps. In this branch it just manually fs checks if a *.map to know where to put the snapshot. Maybe this would impact thousands of tests? I was thinking it would be fair to instead enable this feature through some config flag in `package.json#ava#sourcemaps` or similar.

**Comment by novemberborn** [comment]
> Do you think we should add a package.json#ava config to enable sourcemap detection? This feature will enforce a fs.readFileSync on every test where before there was none. Maybe this is not worth worrying about performance?

The snapshot manager is cached once it's loaded, so it's only loaded once for each test file that uses snapshots. It'll be OK.

> In this branch it just manually fs checks if a *.map to know where to put the snapshot.

I have some feedback on this, though at this point it's better if you could open a PR. It's fine if it's not yet complete.

As to not keep you in suspense, we'd need to find a way to pass the current test file path to the `load()` function, and use a source map library to parse the file for source map annotations, from which the source can be extracted. Anyway, let's collaborate on that in a PR.

**Comment by impaler** [comment]
@novemberborn sounds good, its up I linked to an example project I was using to test eveything. I haven't looked into what you mean by `load()` specifically yet. As it is now I think its meeting all the feature criteria without a sourcemap library. Lets continue in the pull request.

**Comment by masaeedu** [comment]
Is this resolved now that #1489 is merged?
