### ISSUE TITLE
Timeout error thrown when running without concurrency

### ISSUE THREAD

**Issue by avaly** [avajs/ava#1463]
## Description

Running `ava` with any concurrency value >1 passes all tests.

Running `ava` with concurrency value `0` or with `serial` flag enabled, a timeout error is thrown and not all tests are being run.

Increasing the timeout value in the config to 30 seconds, does not have any effect on the outcome.

### Error Message & Stack Trace

```
$ ava --concurrency=2 

  136 passed

$ ava --concurrency=0 

  112 passed
  1 exception

  ✖ Exited because no new tests completed within the last 10000ms of inactivity

```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "babel": "inherit",
    "failFast": true,
    "files": [
      "api/**/*-test.js",
      "client/**/*-test.js",
      "shared/**/*-test.js",
      "tasks/**/*-test.js"
    ],
    "require": [
      "babel-register",
      "./tests/ava-setup.js"
    ],
    "timeout": "10s",
    "verbose": false
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
$ ava --concurrency=2
$ ava --concurrency=0
```

## Environment

```
Node.js v8.1.2
linux 4.4.0-83-generic (Ubuntu 16.04)
ava 0.21.0
npm 5.0.3
```

**Comment by novemberborn** [comment]
`--concurrency=0` seems like it should result in an error. I reckon it currently works without any concurrency limitation, and the timeout may just be because of your system slowing down. Which is why we have the option to begin with.

In other words, I'm not sure there's an issue here?

**Comment by avaly** [comment]
Maybe I misunderstood the meaning of `--concurrency=0`. I had assumed it was doing the same as `--serial`. Using `--concurrency=1` works for me. Feel free to close if you believe it's not a bug @novemberborn .

**Comment by novemberborn** [comment]
@avaly no worries. I've opened #1476 so AVA can give a helpful message earlier.
