### ISSUE TITLE
Save ava test case and results to a file 

### ISSUE THREAD

**Issue by tsghosh** [avajs/ava#1465]
Hi is there a way to save test cases along with results in a file , i am trying to locate a coverage tool for test cases that can be viewed in browser .

any ideas?
thanks

**Comment by novemberborn** [comment]
You could use our TAP reporter and parse the output, and then try and correlate it with the test case… and depending on how you collect coverage, combine it all… somehow?

To be honest this sounds rather difficult! It could be interesting but it's beyond AVA's purview at this point.

I'm closing this issue but please feel free to respond to it, or drop a line in our Gitter chat: https://gitter.im/avajs/ava
