### ISSUE TITLE
Incorrect assertion for -0 === 0

### ISSUE THREAD

**Issue by ivikash** [avajs/ava#1466]
## Description
I am using ava to do some computation and for `-0 === 0` is returning negative.

### Test Source
```javascript
test(t => {
	t.deepEqual(-0, 0);
});
```

### Error Message
```javascript
Difference:
  - -0
  + 0
```

### Config
ava --version --> `0.21.0`

## Environment
Node.js v8.1.0
darwin 16.5.0
npm 5.0.3

### Actual
<img width="577" alt="screen shot 2017-07-24 at 12 49 10 pm" src="https://user-images.githubusercontent.com/371007/28512209-89b8f94c-706e-11e7-9fa0-64ff84cbadfb.png">

### Expected
<img width="110" alt="screen shot 2017-07-24 at 12 46 45 pm" src="https://user-images.githubusercontent.com/371007/28512213-8fd57012-706e-11e7-95b7-0b35169f9c43.png">

**Comment by novemberborn** [comment]
AVA considers those values to be different, both with `t.deepEqual()` and `t.is()`. You'll have to use `t.true(-0 === 0)`.

**Comment by ivikash** [comment]
Thanks for your response, in my case I have a carousel and within the carousel, this is happening for a certain property. 

###Usage
```javascript
t.deepEqual(results, [
    {
      ...state,
      start: {clientX: 10, clientY: 15},
      move: {clientX: 15, clientY: 15},
      carouselX: 0,
      selected: 0,
      direction: Direction.NONE
    }
  ])
```

And depending upon the direction we have to do certain computations. In such a scenario carouselX gets computed to -0. So using `t.true(-0 === 0)` is not possible

**Comment by novemberborn** [comment]
> depending upon the direction we have to do certain computations. In such a scenario carouselX gets computed to -0

That sounds like the polarity of `0` is meaningful, so you should be testing it. If it's not meaningful then it's better if the code ensures it's always `0`.

**Comment by ivikash** [comment]
@novemberborn  Its completely meaningful because that's used to decide the direction for carousel and screen and also the animation. Also this was working in the previous version

**Comment by novemberborn** [comment]
The previous version considered `0` to equal `-0`. As you say, the difference is meaningful, which is why we now consider those values to be unequal. You'll have to adjust your test so it expects the right value.
