### ISSUE TITLE
Improve t.throws output for mismatched constructor

### ISSUE THREAD

**Issue by sholladay** [avajs/ava#1471]
## Description

The output for a failed `t.throws()` assertion should be clearer when the actual and expected constructors do not match.

Currently, it simply says that there was an unexpected exception and shows the error object. It is not immediately clear at first glance that the constructor is what caused the assertion to fail.

### Test Source

```js
const foo = async () => {
    throw new TypeError('Uh oh');
};

test('foo() does stuff', async (t) => {
    await t.throws(foo(), RangeError);
});
```

### Output

```js
  Threw unexpected exception:

  TypeError {
    message: 'Uh oh',
  }
```

## Environment

Node 8.1.4
npm 5.3.0
ava 0.21.0
darwin 16.6.0

**Comment by sholladay** [comment]
A simple solution would be to replace this:

```
Threw unexpected exception:
```

... with something like:

```
Threw `TypeError` but expected `RangeError`:
```

**Comment by sindresorhus** [comment]
I was first thinking a diff:

```
  Threw unexpected exception:

- RangeError {
+ TypeError {
    message: 'Uh oh',
  }
```

But I think your suggestion would be better.

**Comment by novemberborn** [comment]
👍  on @sholladay's suggestion.

I suspect we still need to tackle https://github.com/avajs/ava/issues/1047#issuecomment-288031293 first though.
