### ISSUE TITLE
Question: How can I get AVA to run ESLint on my project?

### ISSUE THREAD

**Issue by joeyespo** [avajs/ava#1474]
New to AVA. So far it's awesome 😃 I probably overlooked this, but after searching the README, issues, and Googling for plugins, I still couldn't find it.

Is there a way to get AVA to lint your project and have a test failure if there's a lint error?

Note that [Ember CLI has an addon](https://github.com/ember-cli/ember-cli-eslint) to do this. And I found a guide for [doing the same with Mocha](https://robots.thoughtbot.com/testing-your-style-with-eslint-and-mocha).

I use ESLint in Sublime, but a test like this will guarantee I won't push any overlooked linting errors.

Thanks!

**Comment by sindresorhus** [comment]
You need to put ESLint in your test script. In package.json:

```json
"scripts": {
	"test": "eslint . && ava"
},
```

Now it will lint when you run `npm test` and in your CI.

If you need to run it on `git push`, see https://github.com/typicode/husky
