### ISSUE TITLE
Fail when `--concurrency` is set to `0`

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1476]
Inspired by #1463. `--concurrency=0` currently means AVA spins up as many workers as there are test files, and when #1467 lands it means AVA spins up as many workers as there are CPU cores. In either case, we should refuse to run tests when the value is set to `0` since AVA's behavior won't match user expectations.

See a similar test in `lib/cli.js`: https://github.com/avajs/ava/blob/a0d5b373a19e9eb0022ad2936b46a1608f11b53f/lib/cli.js#L121

**Comment by mliou8** [comment]
hey @novemberborn . I read through the ticket and I'd like to try and make an attempt at it if that's all right.

**Comment by novemberborn** [comment]
Hey @mliou8, thank you for your interest. As it turns out @tdeschryver already took this on in #1478. I hope you find one of the other open issues interesting to work on though!

---

In the end we figured to allow the `0` value. We now default to `--concurrency` mode, and the `0` value lets AVA pick a machine-appropriate number of worker processes. The flag should be able to override any `package.json#ava` value.
