### ISSUE TITLE
Cannot install with npm on Debian Sid

### ISSUE THREAD

**Issue by russel** [avajs/ava#1480]
```
|> npm install -g ava
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'concordance/react' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'ava'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.11.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ava"
npm ERR! cwd /home/users/russel
npm ERR! node -v v6.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E404
```

**Comment by sindresorhus** [comment]
You need to upgrade npm. Your npm version is ancient.

**Comment by ORESoftware** [comment]
`npm install -g npm@4`

**Comment by russel** [comment]
It's the npm that comes as standard with Debian Sid.

**Comment by russel** [comment]
@sindresorhus @ORESoftware OK, I believe I have a reasonable version of Node (the Debian nodejs package is 6.11, but nodejs reports itself as version 7.10.0) and a reasonable npm using the bootstrap from the ancient Debian version, as indicated earluer. I installed Ava globally, i.e.

    npm install -g ava

and that seems to have worked. However the test test:

```
import test from 'ava';

test('something', t => {
    t.true(true);
});
```

leads to:

    Error: Cannot find module 'ava'

so I am guessing that globally installed modules are not on the default search path.

(Yes, as you can tell I am a total beginner at JavaScript, ES6, Node, etc. Sorry.)

**Comment by novemberborn** [comment]
@russel how are you running that test? By invoking `ava test.js`, or `node test.js`? (I'm assuming your test file is `test.js`.)

**Comment by russel** [comment]
I had the file something.js in the directory test

**Comment by novemberborn** [comment]
@russel despite the global install, you also need to install AVA within your project. Either with `ava --init` or `npm install --save-dev ava`. See https://github.com/avajs/ava/#add-ava-to-your-project.

**Comment by novemberborn** [comment]
> so I am guessing that globally installed modules are not on the default search path.

And yes that does seem to be the problem for you. Still, it's good practice to install your dependencies inside your project too.

**Comment by russel** [comment]
@novemberborn This would seem to imply that global installs are actually useless: if the global location is not on the package search path, only the per project location is, what is the point of the global location.

(You'll have to excuse what is clearly a "newbie" Node/JavaScript/NPM question – it's because I am a "newbie" at this coming from years with Python, D, C++, Java, Kotlin, etc.)

**Comment by novemberborn** [comment]
> This would seem to imply that global installs are actually useless: if the global location is not on the package search path, only the per project location is, what is the point of the global location.

I suspect this is due to how Debian manages Node.js and npm though.
