### ISSUE TITLE
Proposal, support for t.all()

### ISSUE THREAD

**Issue by bhurlow** [avajs/ava#1482]
when testing with ava, I find myself commonly testing if a given set of returned values "all" match a certain predicate or type, e.g:

```js
const R = require('ramda')
let results = [1, 2, 3]
t.true(R.all(R.is(Number), results))
``` 

However if there's a bad apple: 

```js
const R = require('ramda')
let results = [1, '2', 3]
t.true(R.all(R.is(Number), results))
```

Ava prints *all the methods on the ramda object* making it pretty hard to tell what's failing where. It would be nice if ava supported an `.all(predicate, collection)` method which could pretty print value(s) that doesn't match `predicate`.  Or perhaps there's a better solution or work around I'm not seeing

**Comment by novemberborn** [comment]
> Ava prints all the methods on the ramda object making it pretty hard to tell what's failing where.

This should be alleviated by #1204.

> Or perhaps there's a better solution or work around I'm not seeing

Least ideal is to do:

```js
let results = [1, '2', 3]
const outcome = R.all(R.is(Number), results)
t.true(outcome)
```

But now it won't print `results` at all. This may also work:

```js
let results = [1, '2', 3]
const {all, is} = R
t.true(all(is(Number), results))
```

Or:

```js
const predicate = R.is(number)
for (const r of results) {
  t.true(predicate(r))
}
```

> It would be nice if ava supported an .all(predicate, collection) method which could pretty print value(s) that doesn't match predicate.

How would you use this? `t.all(R.is(Number), results)`? We try to advocate using plain JavaScript in favor of additional assertions. I think the `for-of` example above covers this sufficiently.

---

I'm closing this for house keeping purposes. Please feel free to keep the discussion going 😄
