### ISSUE TITLE
Using `unref` on a node timer gives weird error

### ISSUE THREAD

**Issue by SimenB** [avajs/ava#1484]
## Description

If we add a `unref` to a timeout, ava tells us that the promise never resolves. Removing the unref gives the expected result.

### Test Source

```js
'use strict';

const test = require('ava');

test('should succeed', async () => {
    await new Promise((_, reject) => {
        setTimeout(reject, 100).unref();
    });
});

```

### Error Message & Stack Trace

```
  Promise returned by test never resolved
```

### Config

Copy the relevant section from `package.json`:

N/A

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava
```

## Relevant Links

https://gist.github.com/SimenB/b179f81961e34676ac0d3fc881494b12
https://nodejs.org/api/timers.html#timers_timeout_unref

## Environment

MacOS Sierra and Ubuntu 16.04, node 7 and 8, using yarn@0.27.5 and ava@0.21.0

**Comment by forresst** [comment]
I do not have the solution, but maybe I have an idea of the problem.

The error message is normally created at [this location](https://github.com/avajs/ava/blob/master/lib/test.js#L377).

[This line](
https://github.com/avajs/ava/blob/master/lib/test.js#L288) must be I think what is problematic.

To confirm my idea, can you change 100 by 2000 in your test source and give me the result:

```js
'use strict';

const test = require('ava');

test('should succeed', async () => {
    await new Promise((_, reject) => {
        setTimeout(reject, 2000).unref();
    });
});
```

**Comment by SimenB** [comment]
Setting it to 2000 makes no difference

**Comment by forresst** [comment]
Thank you for your answer. Unfortunately, I thought it would have the same as "Removing the unref". So my idea is not the right one. 

If anyone has another idea? Sorry.

**Comment by SimenB** [comment]
The weird thing is that having `unref` also makes ava completetly ignore the `--timeout` option. Seems like doing an `unref` on a timer messes up some global internal state in ava

**Comment by novemberborn** [comment]
AVA detects when the test worker exits, which happens once the Node.js process has no more work to do. Calling `unref()` means the timer won't stop Node.js from exiting. Upon exit, AVA determines your test never finished.

I suspect you're not directly calling `unref()`, so you'd need something else to keep the test alive. Perhaps you could set up a long timeout using `before` or `beforeEach` and clear it in an `after` or `afterEach`?

**Comment by SimenB** [comment]
We discovered this bug when writing a test that didn't really need the `unref`, so we just removed it.

I still find it odd that ava doesn't wait for the returned promise regardless. And that adding a `unref`-ed timer changes the semantics of the test that much. Is that a quirk (or even a bug) in node itself? A still pending promise is discarded

**Comment by novemberborn** [comment]
> Is that a quirk (or even a bug) in node itself? A still pending promise is discarded

A quirk, I'd say.

Node.js exits when the event loop is empty and there is no more work scheduled. Unreferenced timers do not count towards work being scheduled.

It'd be odd if `global.foo = new Promise(resolve => global.resolveFoo = resolve)` kept the process alive indefinitely.

AVA used to have an infinite timer which kept the process alive until all tests completed. That meant that if a test never finished, AVA would never exit either. We've changed it so that AVA fails tests that are still pending when the process exits. On the whole I think that works out better for most use cases.

(Closing, but please feel free to continue the conversation.)
