### ISSUE TITLE
support question - automated front-end testing without Karma?

### ISSUE THREAD

**Issue by ORESoftware** [avajs/ava#1490]
If there is a Slack/Gitter channel I can ask this on, I will copy it over.

Right now we are using Karma and Jasmine for front-end testing, and TBH I am not really digging it at all.

The problem with Karma is that it forces you to use mocks to do your testing. We can't use our actual API data - we have to create mock data which I feel is mostly a waste of time and inaccurate. I'd like to write some front-end tests without using mock API data, for example.

Does AVA allow you to do front-end "unit" testing with real API data? I assume this would be not with Karma but some other runner?

Obviously, we can use Selenium for E2E, but I am looking to write tests that run directly in the browser, but don't force you to write mock API data.

Any advice helpful, thanks, hopefully my question is clear.

**Comment by sindresorhus** [comment]
https://stackoverflow.com/questions/tagged/ava or https://gitter.im/avajs/ava
