### ISSUE TITLE
Remove Bluebird.longStackTraces()

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1492]
We enable long stack traces: http://bluebirdjs.com/docs/api/promise.longstacktraces.html

However these don't matter for users. By default tests will run with the native `Promise` implementation, even with async-await on Node.js 4 and 6. AVA's code, which at times does use Bluebird, is always removed from the stack traces, so it doesn't matter what Bluebird captures.

As long as we process the `require` modules early enough, users can still enable long stack traces if they use Bluebird in their own code. It would be good to have an integration test for this though.

See https://github.com/avajs/ava/blob/dd9e8b2effe541f9f232ee622452343dac5895dd/lib/test-worker.js#L33

**Comment by thakkardharmik** [comment]
I would like to take this up. @novemberborn Can you help me with getting started?

**Comment by novemberborn** [comment]
@thakkardharmik there's already a PR: https://github.com/avajs/ava/pull/1496. We'd still need an integration test though. It should be an AVA test file which enables long stack traces, and then verifies that they were indeed enabled.

**Comment by thakkardharmik** [comment]
@novemberborn can you point me to some reference for writing a test?

**Comment by novemberborn** [comment]
@thakkardharmik Bluebird's documentation has an example: http://bluebirdjs.com/docs/api/promise.longstacktraces.html

I'd make a new directory under `test/fixture`, with a `package.json` that configures AVA. Write a module that configures `longStackTraces` and use AVA's `require` option to load it. Then add a `test.js` which gets an error stack as is shown in Bluebird's example. Don't log it to the console though. This `test.js` should contain an AVA test which checks if the stack contains `From previous event`. You can run it from `test/cli.js`. There's a fair amount of similar tests in that file.

**Comment by novemberborn** [comment]
Reopening since we still need a test.

**Comment by mliou8** [comment]
@novemberborn I'd like to take a try at this if that's all right.

**Comment by novemberborn** [comment]
@mliou8 all yours!

**Comment by mliou8** [comment]
hi @novemberborn ! I think i'm pretty close, but I'm having trouble getting the assertion to pass correctly. Part of the problem is I'm unsure of how to actually test what the error I'm throwing is. 

Console.log and process write seem to be disabled, is there another way to find out what I'm throwing as an error?

**Comment by novemberborn** [comment]
@mliou8 I usually run the test directly, e.g. `cd test/fixture/path/to/ && node ../../../../cli.js test.js`. Then when that's behaving correctly you can hook it up with the CLI tests.

**Comment by mliou8** [comment]
@novemberborn thanks, that was helpful. I opened a PR here: https://github.com/avajs/ava/pull/1514
