### ISSUE TITLE
Ava should not error/process.exit() when loaded outside its CLI

### ISSUE THREAD

**Issue by davewasmer** [avajs/ava#1495]
## Description

Right now, merely requiring/importing ava outside of the ava CLI causes an immediate hard exit. This makes it difficult for frameworks and libraries to build on top of ava.

For example, Denali (a Node.js server framework) ships with ava as the test runner. We also ship some helpers that wrap ava with some Denali-specific setup and teardown. We export these helpers as part of the main package, i.e. `export { default as AvaTestHelper } from './test/helpers'`

Currently, we are forced to load ava via `require()` in a code path that is guaranteed to only fire in test mode. If we use a normal `import` statement (which, being statically evaluated, would run in every context, including outside of test mode), ava will forcibly take down the entire process with it's `process.exit` call:

https://github.com/avajs/ava/blob/dbc78dc19cb759b6b72946bc1b833abc284cfab2/lib/test-worker.js#L16

### Test Source

```js
require('ava');
```

### Error Message & Stack Trace

```
Test files must be run with the AVA CLI:

    $ ava dist/app/index.js```

**Comment by novemberborn** [comment]
We do this because the worker code modifies the process in order to run the tests. This is a side effect that I can't imagine you want even in your test mode. Is there a way to run your meta-tests without actually requiring `ava`? Perhaps by stubbing the require cache?

**Comment by davewasmer** [comment]
We can isolate the require statement to a test-only code path (our current workaround), so its not a showstopper for us. But it is surprising that requiring Ava at all results in a hard exit. Is there _any_ supported way to ship test helpers like our use case that doesn't involve conditionally loading Ava?

**Comment by novemberborn** [comment]
> We do this because the worker code modifies the process in order to run the tests.

To follow-up on this, we could make it so the worker knows it's in a child process (e.g. through an environment variable) and bail out quietly if it isn't. However there is a second reason we force the process to exit. Libraries like [node-tap](http://www.node-tap.org/) let you do `node test.js` and they run the tests. AVA doesn't do that. We print a warning and exit to guide users in the right direction.

> Is there any supported way to ship test helpers like our use case that doesn't involve conditionally loading Ava?

Not at the moment, but I'd be happy to find a way. We'd need to meet the following requirements:

* `require('ava')` must not modify the process unless ran inside an AVA worker
* `node test-file.js` must print the warning and exit

Perhaps in `'ava'` we could detect if `module.parent === require.main`. That should only be `true` if it's required from a file that is run directly. We could make it so it only prints the warning if that's the case. As mentioned earlier we could find another way of making sure the process isn't modified.

I'm not sure what the module should export though. A stubbed `test` which throws when it's used? Would wrapper libraries like [ava-describe](https://www.npmjs.com/package/ava-describe) have to replicate this behavior so they behave correctly when the main module requires `ava-describe` and not `ava`?

I'm not sure this is worth it. An alternative approach might be to support an environment variable which disables the warning, but to be honest at that point I'd prefer if these wrapper libraries worked around AVA's behavior in their tests.
