### ISSUE TITLE
Read snapshot content

### ISSUE THREAD

**Issue by philippotto** [avajs/ava#1497]
## Description

It would be cool if the snapshot content corresponding to a snapshot-id could be retrieved via the API. Snapshots in one context could be mocks in another context. Then the following would be possible:

- test the backend api via snapshot testing
- test the front-end by using the snapshots of the API tests as mocks

The api could be something like `t.getSnapshot(snapshotId)` and would retrieve the object which is usually compared to when using `t.snapshot`.

**Comment by novemberborn** [comment]
> Snapshots in one context could be mocks in another context.

Unfortunately the snapshots are *descriptions* of the original values. They're stored with enough fidelity to be compared against current values, but restoring them would only work for built-in object types (e.g. no custom classes), and wouldn't really work for functions, symbols, and some other value types. See https://github.com/concordancejs/concordance for the library we use.

> Then the following would be possible:
> 
> * test the backend api via snapshot testing
> * test the front-end by using the snapshots of the API tests as mocks

This is probably best done through a dedicated library. [Nock](https://github.com/node-nock/nock) does this for HTTP requests in Node.js itself.
