### ISSUE TITLE
Function `t.log()` is not defined in TypeScript and Flow type definitions

### ISSUE THREAD

**Issue by jmquigley** [avajs/ava#1498]
## Description

I'm getting the following typescript compilation error when using latest version 0.22.0 and the new `t.log()`.

`error TS2339: Property 'log' does not exist on type 'GenericTestContext<Context<any>>'`

I think this new function is missing from your typings generation.  I didn't see it in `./types/generated.d.ts`.  I did add it to my local copy to get around the build errors (by adding it to interface TestContext)

## Environment
node v7.8.0
ava 0.22.0
yarn 0.28.4
typescript 2.4.1

**Comment by sindresorhus** [comment]
Yes, you're right. We need to get it added to both the TypeScript and Flow bindings.
