### ISSUE TITLE
Writing polymorphic tests

### ISSUE THREAD

**Issue by edenworky** [avajs/ava#1503]
Is there a way to test polymorphically?

My use case is testing a derived class. I want to run the superclass's tests polymorphically for all the classes that extend it. For example:

```js
class Foo {
  constructor() {
    this.shouldThrow = true
  }

  doThing() {
    if (this.shouldThrow)
      throw new Error
  }
}

class Bar extends Foo {
  doThing() {
    super.doThing()
    return 'success'
  }
}

let bar = new Bar
bar.doThing() // throws
bar.shouldThrow = false
bar.doThing() // 'success'
```

So I would write a test for `Foo`, asserting that it throws when `doThing` is called and `shouldThrow` is `true`. Naturally, `Bar` inherits this functionality.

There are two approaches to take for testing `Bar`. The first is asserting that `Bar` extends `Foo`, but this couples the test to `Bar`'s implementation. The second is to write a polymorphic test class `TestFoo` and having a `TestBar` class inherit for it.

I imagine the second can be achieved by something like this:

```js
class TestFoo {
  constructor(ClassUnderTest) {
    this.ClassUnderTest = ClassUnderTest
  }

  registerTests(test) {
    test('throws when should throw', t => {
      let foo = new this.ClassUnderTest
      t.throws(() => foo.doThing(), 'should throw')
    })

    test("doesn't throw when shouldn't", t => {
      let foo = new this.ClassUnderTest
      foo.shouldThrow = false
      t.notThrows(() => foo.doThing())
    })
  }
}

class TestBar extends TestFoo {
  registerTests(test) {
    super.registerTests(test)
    test("return success when shouldn't throw", t => {
      let bar = new this.ClassUnderTest
      bar.shouldThrow = false
      t.is(bar.doThing(), 'success')
    })
  }
}

new TestBar(Bar).registerTests(test /* AVA's instance */)
```

This works, but it's somewhat inelegant and feels like a workaround. Is this a supported use case? Do you see a simpler solution for this problem?

**Comment by novemberborn** [comment]
AVA takes a low-key -`test()`-functions-inside-a-file approach. We do support macros which let you reuse a test implementation:

```js
const likeFoo = (t, Klass) => {
  const instance = new Klass()
  t.throws(() => instance.doThing())
  instance.shouldThrow = false
  t.notThrows(() => instance.doThing())
}

likeFoo.title = (prefix, Klass) => `${prefix} ${Klass.name} behaves like Foo`

test(likeFoo, Foo)
test(likeFoo, Bar)
```

**Comment by edenworky** [comment]
I didn't know about macros! That's cool.

However, it doesn't solve my issue. I want to inherit tests. A macro allows a shorter way to define a test. I'm looking for polymorphism, not simply reuse. This would require me to register every superclass test for every derivative.

**Comment by novemberborn** [comment]
> I want to inherit tests.

That's not the testing approach taken by AVA. You have to built something on top of it, like you're already doing.
