### ISSUE TITLE
"require" option doesn't load precompiled helpers

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1506]
From https://github.com/avajs/ava/issues/1187#issuecomment-315526027, when test helpers are specified in the `"require"` option, AVA does not load the precompiled file.

The problem seems to be that we install our loader too late: https://github.com/avajs/ava/blob/9c9dfefb548dc5b18b4d72b15ed18ef1e8084e9f/lib/test-worker.js#L33

I suspect that it might be OK if we move that line up before:
https://github.com/avajs/ava/blob/9c9dfefb548dc5b18b4d72b15ed18ef1e8084e9f/lib/test-worker.js#L30

We need to test how this interacts with `babel-register`, and add an integration test to verify we require the precompiled helpers.

**Comment by darthgera123** [comment]
is this issue still open or is it closed?

**Comment by novemberborn** [comment]
@darthgera123 it's still open.

**Comment by JavierPons** [comment]
Hi there,

I'm interesting in help in this issue. It will be my first intervention. (Im a beginner). 
What concretely do you need? Where I can help in this? Or if you need help in an other issue as well Im ready to participate.

**Comment by novemberborn** [comment]
@JavierPons that's great! Beyond what's in the issue description at the top, what information are you looking for?

**Comment by JavierPons** [comment]
@novemberborn Im looking for some issue with code that I can make better for example or if it is a bug that I can resolve. (Maybe its very high level for me :p ) But I would like to try.

**Comment by novemberborn** [comment]
@JavierPons by all means, go ahead.

As the issue describes, you probably need to move up the `adapter.installPrecompilerHook();` line. Test it on a local installation first (use `npm link` so you can test against your local AVA checkout). Helper files are files inside a `test` folder that start with an underscore. If you use `import` to require a dependency in that helper file it'll be a good way of checking whether the precompiled version was loaded.

If that's all looking good you'll have to make an integration test. There should be bunch of examples in `test/cli.js`.

Please open a PR with your initial changes so we can iterate on them more effectively. Thanks!

**Comment by SunflowerPKU** [comment]
> Hi there,
> 
> I'm interesting in help in this issue. It will be my first intervention. (Im a beginner).
> What concretely do you need? Where I can help in this? Or if you need help in an other issue as well Im ready to participate.

Hi @JavierPons ,

I am a Ph.D. student. I am doing research about **helping newcomers participate in OSS projects**. I noticed that many projects are using labels such as 'good first issue/bug, difficulty/newcomer' for issues to recommend that newcomers start from these tasks. 

I noticed that you tried to solve this issue, but unfortunately, you had not contributed successfully. I also found there are many newcomers feel difficult when submitting their first pr. Therefore, I want to optimize this mechanism, which needs your help. I have some questions and wish your valuable feedback.

**1. What problems did you meet when solving this issue? 
2. Do you think it is appropriate to recommend newcomers to solve this issue?  and why?
3. How do you think of the existing mechanism that adding certain labels to issues for helping newcomers participate in open source projects?**

I am looking forward to hearing from you soon. Thank you very much!
