### ISSUE TITLE
Watch mode: show the first few non-rerun test files

### ISSUE THREAD

**Issue by wmertens** [avajs/ava#1509]
## Description

Feature request: Instead of just showing the number of failed test files that were skipped in this run, also show the paths of at least the first few.

This allows one to fix tests in watch mode from bottom to top, and then moving to the next test file by opening it and saving it, causing a re-run.

The only alternative is to restart AVA, which can take a very long time.

## Environment

```
Node.js v8.2.1
darwin 16.5.0
 $ npx ava --version
0.22.0
 $ npm --version
5.3.0
```

**Comment by novemberborn** [comment]
Makes sense.



> The only alternative is to restart AVA, which can take a very long time.

You can type `r` followed by the return key, and that'll rerun all tests without having to restart the watch process.

**Comment by wmertens** [comment]
Oh wow! That's handy! I think it would be good to print that on a line
after the tests when in watch mode :)
