### ISSUE TITLE
Inline `require` opts to process.argv

### ISSUE THREAD

**Issue by mAAdhaTTah** [avajs/ava#1512]
## Description

From @jdalton:

> Mocha does a nifty trick where it takes its mocha.opts file and inlines them into the process.argv arguments so @std/esm can detect itself. There's a bug open on nyc to add similar functionality. Ava should do this too 😋!

Source: https://github.com/standard-things/esm/issues/89#issuecomment-327910381

The reason this would be needed/helpful is so that std/esm parses the command line arguments to tell whether it should augment the module require to compile ESM.

May be related to #1393.

### Config

If I have this:

```json
{
  "ava": {
      "require": [
        "@std/esm"
      ]
  }
}
```

std/esm will be able to compile my app code's ESM in the tests without requiring babel.

## Relevant Links

- Source issue: https://github.com/standard-things/esm/issues/89
- Related issue in nyc: https://github.com/istanbuljs/nyc/issues/660

**Comment by jdalton** [comment]
The relevant bit in Mocha's implementation is [here](https://github.com/mochajs/mocha/blob/74fa66f52e797b4f9bdbd1fe3cb096c6693fccea/bin/options.js#L25-L35).

**Comment by novemberborn** [comment]
We won't support `-r` in AVA's CLI flags, nor add additional flags to the workers.

You should be able to use `node -r "@std/esm" ./node_modules/.bin/ava`, or alternatively write a file that creates the loader and require that through AVA's `package.json` configuration. Though I can't figure out from the [documentation](https://github.com/standard-things/esm) whether that loader is then used for all modules.

**Comment by mAAdhaTTah** [comment]
Tried this: `node -r "@std/esm" ./node_modules/.bin/ava`; no dice w/ v0.8.3 of esm.

> write a file that creates the loader and require that through AVA's package.json configuration

This sounds _possible_, but (I think) we would have to overwrite the global `require` function. I attempted (ava-esm.js):

```javascript
// Nope
require('module').prototype.require = require('@std/esm')(module, { cjs: true, esm: 'js' });
// Nah
require('module').prototype.require = require('@std/esm')(module, true);
// Still no
require('module').prototype.require = require('@std/esm')(module);
```

Different errors with each one, but none of them work. Is this the right approach to take? Any other ideas?

**Comment by jdalton** [comment]
@novemberborn 

> You should be able to use node -r "@std/esm" ./node_modules/.bin/ava

AVA seems to be using it's own loader `require-precompiled`
```
export var value = reset()
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Module._extensions..js (module.js:584:10)
    at extensions.(anonymous function) (/projects/esm/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/projects/esm/node_modules/ava/lib/process-adapter.js:100:4)
```

@mAAdhaTTah
```js
// Nope
// Nah
// Still no
```
That's not the right approach. If the esm loader can be the entry point for all tests then you can do:
```js
require("@std/esm")(module)("./testForAll.js")
```
But there is no way to enable global require overwriting with it's API *(that's a feature)*.

**Comment by jdalton** [comment]
It looks like AVA sends commands as JSON string arguments to its forked processes. I should be able to sniff them. Is this a standard thing or something AVA cooked up?

**Comment by jdalton** [comment]
It looks like sniffing the stringified param will enable `@std/esm` to hook in but then it's running into AVA's built-in Babel use (AVA is transpiling the `import`/`export`). I tried to disable it with some babel configs but not having any luck. Any guidance @novemberborn?

**Comment by mAAdhaTTah** [comment]
@jdalton Ava transpiles its test files by default, but not external files. I'm trying to use `@std/esm` for those so I don't need babel at all.

**Comment by jdalton** [comment]
@mAAdhaTTah I'm saying once `@std/esm` is patched to hook in with `"require": "@std/esm"` it still won't work because the test files are being handled by Babel. If there was a way to disable the `"module":false` transform for AVA then it might work. Which is why I'm asking @novemberborn if it's possible.

**Comment by mAAdhaTTah** [comment]
If AVA is handling transforming the test files via babel, shouldn't `@std/esm` just treat them like cjs files?

**Comment by jdalton** [comment]
The problem is that when AVA transpiles the test file
```
import envDelta from '../envDelta';
```
will transpile it to:
```
var _envDelta = require('../envDelta');
var _envDelta2 = _interopRequireDefault(_envDelta);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
So because `brookjs-cli/src/deltas/envDelta.js` is handled by `@std/esm` it's export is as a regular cjs file without a `__esModule` property so Babel will treat it as `{ default: obj }` which breaks the tests since `envDelta` is supposed to be a function not an object as `{ default: func }`.

**Comment by jdalton** [comment]
I made the `cjs` option of `@std/esm` add the `_esModule` property to its export and that fixed it with Babel unit tests.

**Comment by mAAdhaTTah** [comment]
> I made the cjs option of @std/esm add the _esModule property to its export and that fixed it with Babel unit tests.

Awesome. We can close this out then, yeah?

**Comment by novemberborn** [comment]
> Tried this: node -r "@std/esm" ./node_modules/.bin/ava; no dice w/ v0.8.3 of esm.

@mAAdhaTTah , I had assumed that would be propagated to the workers, but maybe not.

> It looks like AVA sends commands as JSON string arguments to its forked processes. I should be able to sniff them. Is this a standard thing or something AVA cooked up?

@jdalton it's our own thing. Note that we do have a stalled PR that aims to forward remaining arguments to the workers, but they'd come after the filename argument so that wouldn't quite help with `-r`.

> it's running into AVA's built-in Babel use (AVA is transpiling the import/export). I tried to disable it with some Babel configs but not having any luck. Any guidance @novemberborn?

It is possible to disable this, yes. You'd lose all other transforms though (currently not a problem with Node.js 8, but it'll hurt the compatibility of your tests with earlier versions). But we can find a way of running https://github.com/avajs/babel-preset-stage-4 without the module transform.

**Comment by jdalton** [comment]
> It is possible to disable this, yes. You'd lose all other transforms though (currently not a problem with Node.js 8, but it'll hurt the compatibility of your tests with earlier versions). 

Can you go into detail. I know some Babel presets like babel-env allow you to disable module transpilation with `"module": false` option.

**Comment by dinoboff** [comment]
@jdalton to disable module transform you can try with @dinoboff/babel-preset-stage-4 (scoped package for this avajs/babel-preset-stage-4#8):
```
npm i @dinoboff/babel-preset-stage-4
```

And in `package.json`:
```
{
  "ava": {
    "babel": {
      "presets": [
        [
          "@dinoboff/stage-4",
          {
            "modules": false
          }
        ]
      ]
    }
  }
```

**Comment by novemberborn** [comment]
> Can you go into detail. I know some Babel presets like babel-env allow you to disable module transpilation with "module": false option. How does that map to AVA?

@jdalton we currently do not have that option, but we should. @dinoboff helpfully opened https://github.com/avajs/babel-preset-stage-4/pull/8.

Besides this detail, is there anything that prevents `@std/esm` from working with AVA? And has there been consideration for enabling the processing of all files via an environment variable?

**Comment by jdalton** [comment]
> Besides this detail, is there anything that prevents @std/esm from working with AVA?

I patched `@std/esm` so it works with Babel transforms using the `"cjs":true` option and the AVA `require` option. All good!

> And has there been consideration for enabling the processing of all files via an environment variable?

That hasn't been brought up. I'd be concerned that deps of deps of deps using `@std/esm` would also trigger since they'd notice the environment variable too.
