### ISSUE TITLE
Missing space between var1 instanceof var2 in output

### ISSUE THREAD

**Issue by OmgImAlexis** [avajs/ava#1513]
## Description

When a test fails while using `test.true(var1 instanceof var2)` the output removes the spaces.

### Test Source

```js
test('returns itself', t => {                
    t.true(t.context.script instanceof Script);
});
```

### Error Message & Stack Trace

```
  1 failed
  1 rejection

  returns itself

  /Users/xo/code/@lad/mongoose/test/test.js:10

    9: test('returns itself', t => {                
   10:   t.true(t.context.script instanceof Script);
   11: });                                          

  Value is not `true`:

  false

  t.context.scriptinstanceofScript
  => false
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
  ...
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v8.4.0
darwin 16.7.0
ava 0.22.0
npm 5.3.0
```

**Comment by novemberborn** [comment]
Yea that's not great. Thanks for reporting it.

**Comment by codeslikejaggars** [comment]
The same behavior affects any infix operator. Empty strings are also rendered invisible:

```javascript
const val = 'some value';
test('fails with multiple === expressions', t => {
	t.false(val === '' && '' === val);
});
```

```
  1 failed

  fails with multiple === expressions

  /Users/path/ava/test/fixture/enhanced-assertion-spaces.js:5

   4: test('fails with multiple === expressions', t => {
   5:   t.true(val === '' && '' === val);
   6: });

  Value is not `true`:

  false

  val===&&===val
  => false

  val===
  => false

  val
  => 'some value'
```

One way to resolve this would be to use [babel-generator](https://github.com/babel/babel/tree/master/packages/babel-generator) in [enhance-assert.js](https://github.com/avajs/ava/blob/master/lib/enhance-assert.js) to regenerate the code from the AST, instead of concatenating the token values.

**Comment by OmgImAlexis** [comment]
@codeslikejaggars @novemberborn thank you!
