### ISSUE TITLE
Execution sequence of multiple test files with `--serial` flag.

### ISSUE THREAD

**Issue by huanxir** [avajs/ava#1517]
## Description

The CLI flag `--serial` controls to execute multiple test files serially. But how does `ava` determine the file sequence? 

My test suite needs run couples of files in a particular sequence, say, test-file-1.js, test-file-2.js, test-file-3.js, etc.  How can I specify the execution sequence with `ava`? I have tried to specify the filenames in `package.json` explicitly, but it doesn't work. They are always running in test-file-1.js, test-file-3.js, test-file2.js sequence.

### Config

Copied the relevant section from `package.json`:

```json
{
 "scripts": {
    "test": "ava"
  },
  "ava": {
    "files": [
      "test/test-file-1.js",
      "test/test-file-2.js",
      "test/test-file-3.js"
    ],
    "serial": true,
    "verbose": true
  }
...
}
```

## Environment

```
Node.js v6.10.3
darwin 16.7.0
ava 0.22.0
npm 5.3.0
```

**Comment by novemberborn** [comment]
> But how does ava determine the file sequence?

We use third-party modules to find the test files. There is no guaranteed order.

> My test suite needs run couples of files in a particular sequence, say, test-file-1.js, test-file-2.js, test-file-3.js, etc. How can I specify the execution sequence with ava?

This… doesn't sound great. You should revisit your test setup so you do not have this dependency. The `--serial` option exists for debugging purposes. AVA assumes test files can be executed independently from each other.
