### ISSUE TITLE
Remove React from Browser Testing Recipe

### ISSUE THREAD

**Issue by lukechilds** [avajs/ava#1522]
Can we remove the React example from the browser testing recipe?

https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md

We now have a dedicated recipe for React. I didn't write the React section of that recipe, it was left in from the previous revision before I added `browser-env`/`window`. I always thought it seemed a bit convoluted and it appears it's actually invalid (references an undefined `div` variable).

Can this be removed in favour of the React recipe?

Also, if you wanna keep the React version in the browser recipe, I have since written [ReactJSDOM](https://github.com/lukechilds/react-jsdom) which may be a neater solution.

**Comment by novemberborn** [comment]
Yea sounds good. Help wanted! 😄

**Comment by lukechilds** [comment]
Just checking, you're saying you want the React section removed, not updated to use ReactJSDOM, right

**Comment by novemberborn** [comment]
Remove the React section, yes.

**Comment by novemberborn** [comment]
Remove the React section, yes.
