### ISSUE TITLE
async keyword causes test to be seen as single promise => timeout too short

### ISSUE THREAD

**Issue by wmertens** [avajs/ava#1526]
## Description

When using Node 8, transpiling all, and babel-preset-env with `node:true` as target, some of my longer tests time out via `finishDueToInactivity`. This doesn't happen when the async is transpiled by babel. I assume that the async creates a single promise where the transpiled version splits in many?

If so, I propose that the timeout gets reset every time one of the test functions gets called?

### Test Source

```js
test('long test with many steps', async t => {
    t.snapshot(await slowThing1(), 'after 1')
    t.snapshot(await slowThing2(), 'after 2')
// ... Sometime here it will say "Promise returned by test never resolved"
    t.snapshot(await slowThing8(), 'after 8')
})
```

### Error Message & Stack Trace

```
 Promise returned by test never resolved

  Test.finishDueToInactivity (node_modules/ava/lib/test.js:377:7)
  onBeforeExit (node_modules/ava/lib/sequence.js:43:20)
  process.beforeExitHandler (node_modules/ava/lib/sequence.js:6:3)
  processEmit [as emit] (node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:146:32)
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "files": [
      "{src,lib}/**/{__tests__/*,*.test}.js{,x}"
    ],
    "babel": "inherit",
    "concurrency": 5,
    "require": [
      "babel-register",
      "babel-polyfill"
    ]
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava --watch
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v8.4.0
darwin 16.5.0
0.22.0
5.3.0
```

**Comment by novemberborn** [comment]
This is odd. The inactivity implementation doesn't use timeouts though. It registers a hook for when the process exits, which will happen when the event loop is empty.

It seems as if you're running into a Node.js or even V8 error?

I'm closing this since I don't think it's an AVA issue, but I'm happy to help debug this further. Though I suspect you can't share your code.

**Comment by pigcan** [comment]
got this issue too

**Comment by novemberborn** [comment]
@pigcan could you provide details on your Node.js version, and if possible even your test suite?

**Comment by pigcan** [comment]
@novemberborn ok , later I will share my example code.

**Comment by Smilebags** [comment]
I am also experiencing this issue with a rather simple example

**Comment by novemberborn** [comment]
@Smilebags could you share your example?
