### ISSUE TITLE
Add flag for transpiling all

### ISSUE THREAD

**Issue by wmertens** [avajs/ava#1527]
## Description

I know that the configuration at https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#transpiling-tests-and-sources-the-same-way can transpile all source files, but I believe AVA should have a flag that does this.

The reason is that in big projects, globbing the helper files takes a very long time (e.g. #1228), and when transpiling everything, there is no point in globbing. Since it's hard to look at the require config and determine if we're transpiling everything, it would be better to have a flag.

So the request is: add a `transpileAll: true` flag that has the same effect as the config linked above, but also disables the helper globs.

**Comment by novemberborn** [comment]
There is a longer term goal to enable AVA to transpile source files. Nearer term though I'm planning on fixing the helper globbing.
