### ISSUE TITLE
Change watch listening mode to raw

### ISSUE THREAD

**Issue by unional** [avajs/ava#1531]
ava@0.22

It would be nice to change watch listening mode to raw so that users don't have to type `r + ENTER` or `u + ENTER`. Just `r` or `u` is sufficient.

I can work on a PR for that.

However, I notice the code also check for `rs`: https://github.com/avajs/ava/blob/master/lib/watcher.js#L278
which does the same thing as `r`

Any reason for that? if not, I can remove it (which simplifies the code).

**Comment by novemberborn** [comment]
> However, I notice the code also check for rs: /lib/watcher.js@master#L278
> which does the same thing as r
> 
> Any reason for that? if not, I can remove it (which simplifies the code).

It's what `nodemon` uses. But we can remove that.

**Comment by sindresorhus** [comment]
I initially wanted just `u`, but I no longer remember why we went with `u` + `Enter`.

**Comment by novemberborn** [comment]
> I initially wanted just u, but I no longer remember why we went with u + Enter.

See https://github.com/avajs/ava/pull/1533, raw mode breaks interrupts.
