### ISSUE TITLE
Expose files dirs seperately

### ISSUE THREAD

**Issue by OmgImAlexis** [avajs/ava#1540]
Currently apart from passing in my own files list there doesn't seem to be any way to set the helper's directory apart from overriding the whole `files` array. I'd like to suggest adding a way to change each of the arrays that makes up the`files` option.

This would include `defaultExcludePatterns`, `defaultIncludePatterns ` and `defaultHelperPatterns `. My idea would be to use an object for files which has the fields`excludes`, `includes` and `helpers`.  
https://github.com/avajs/ava/blob/87eef846392d04b727b57981a16f7e8429a04195/lib/ava-files.js#L76-L95

The reason I'm suggesting this is I want to use `__helpers__` for my helper directory as I currently have a `helpers` directory for a test with my helpers. To add that I'd need to replace the whole files array instead of just doing something like `{ files: { helpers: ['**/__helpers'] } }`.

**Comment by sindresorhus** [comment]
Adding more options is rarely a good solution. Maybe we should just use `__helpers__` for helpers if you use the naming convention `__tests__` for tests, like we do with snapshots.

**Comment by novemberborn** [comment]
I've been collecting these issues under the [`globbing` label](https://github.com/avajs/ava/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+globbing%22). I haven't quite summarized the solution, but I actually do think we should support separate helper patterns.

I also like the idea of supporting `__helpers__`.

I should have more time to work on AVA soon, and this is one of the areas I'd like to tackle. So stay tuned (but not too tuned, can't make any promises 😉 ).
