### ISSUE TITLE
afterEach.fail hook would be nice

### ISSUE THREAD

**Issue by Martin-Kuca** [avajs/ava#1544]
Hi, I'm using ava for tests running on CI and I was wondering if there is a way for me to perform an action (e.g. take a screenshot) whenever a test fails.

something along the lines of a .afterEach.fail hook:
test.afterEach.fail(() => {
await browser.screenshot()
})

I know there is a simple .afterEach hook but that would create way too many unnecessary screenshots

**Comment by ORESoftware** [comment]
I think there was talk of passing the test result to every afterEach hook, something like this:

```js
test.afterEach(t => {
   if(t.failed) { /* do your thing here */}
});
```

but hopefully someone will explain further

**Comment by Martin-Kuca** [comment]
@ORESoftware Thank you. I've looked the issue up and found a solution for my problem

```
test.afterEach('this only runs when test succeeds', async t => {
  // this is here since my eslint does not allow object mutation
  // eslint-disable-next-line mutation/no-mutation
  t.context = 'success'
})

test.afterEach.always('clean up', async t => {
  if (t.context !== 'success') {
    await browser.saveScreenshot(`./screenshot-${Date.now()}`)
  }
// the rest of the code runs regardless of the test succeeding
// more of my clean up code
})
```
for anyone wondering the issue, this is discussed in, is #840
