### ISSUE TITLE
Companies Using AVA

### ISSUE THREAD

**Issue by clemtrek** [avajs/ava#1545]
I just wanted to know who all use this beautiful unit testing franework

**Comment by clemtrek** [comment]
unit testing **framework**

**Comment by novemberborn** [comment]
Hey @clemtrek thanks for your interest. We don't have a list of companies. Perhaps browsing https://www.npmjs.com/browse/depended/ava could yield some insights.

**Comment by clemtrek** [comment]
Thanks
