### ISSUE TITLE
Image snapshots w/visual comparison

### ISSUE THREAD

**Issue by niftylettuce** [avajs/ava#1548]
It'd be nice if the snapshots stored images as actual images instead of inline binary data.

Not sure if this is possible, I didn't see it documented anywhere.

It'd also be nice to add https://github.com/Huddle/Resemble.js built-in to do visual diffing with a threshold (which could be configured by ava config or test-specific).

**Comment by niftylettuce** [comment]
Rather we might want to use <https://github.com/gemini-testing/looks-same> instead

**Comment by bokuweb** [comment]
@niftylettuce  I have created ava + electron + visual regression test example.

- https://github.com/bokuweb/react-avaron-reg-sample
- https://github.com/bokuweb/react-avaron-reg-sample/pull/7

I hope it will be helpful to you :)

**Comment by niftylettuce** [comment]
@bokuweb cool!  hmm yours checks for an exact match, I think I'm going to use @limonte approach at <https://github.com/limonte/sweetalert2/blob/3c5b196fbf9bf3780c091a6e22a860228c9486ae/test/puppeteer/visual-tests.js#L167> probably, thank you.  Currently using https://github.com/Huddle/Resemble.js and dislike that it requires canvas etc.

**Comment by sindresorhus** [comment]
Would be cool if someone could submit a recipe for this: https://github.com/avajs/ava/tree/master/docs/recipes
