### ISSUE TITLE
No transpile option

### ISSUE THREAD

**Issue by cdaringe** [avajs/ava#1556]
## Description

- add support for a flag/mode that skips transpilation of all files.

ava doesn't support a "no transpilation" option.  a no transpile option would improve performance and, more importantly, yield a stable, easy debugging experience for those of us who don't need/want transpilation.  i use ava for many of it's great features, transpilation not being one of them.  transpilation+source_maps+editors frequently don't play nicely.

observe:

![vscode-ava](https://user-images.githubusercontent.com/1003261/31685899-79fb7a6c-b339-11e7-8012-b6d62919ead9.gif)
^^ _shows setting breakpoints, running ava, transpiliation happens behind the scenes, and my editor losing it's cool as it lost refs to the actual lines breakpoints were originally on, pretest_

this is already a known issue without a solution--[it even says so in the docs](https://github.com/avajs/ava/blob/master/docs/recipes/debugging-with-vscode.md#debug).  these issues "just go away" when i can use raw node, and the runtime runs just my code, untouched!

thanks for the consideration!  great work.

**Comment by sindresorhus** [comment]
Yeah, I'd like to see that too. Now that Node.js 8 has native async/await, there's no longer a need for me personally to transpile. The main reason we chose to do transpilation by default initially was to get async/await.

**Comment by sindresorhus** [comment]
@avajs/core Thoughts?

**Comment by novemberborn** [comment]
Yes. See also https://github.com/avajs/ava/issues/709 (don't worry I'll clean up the issues).

Say we have a `"babel': false` option. Should that also imply `"powerAssert": false`? I'm leaning towards yes, since `power-assert` requires transpilation, whether via Babel or https://github.com/power-assert-js/espower-loader. But it might be an unexpected way to lose that feature. Same goes for our [throws helper](https://github.com/avajs/babel-plugin-throws-helper). Should there be an easy way to opt back in to it?

**Comment by sindresorhus** [comment]
> Say we have a "babel': false option. Should that also imply "powerAssert": false?

Yes, unless we can figure out a way to run it efficiently at [runtime](https://github.com/power-assert-js/espower-loader) on a failure.

> Should there be an easy way to opt back in to it?

I don't see how you could opt into the throws helper again without having Babel, and then using `babel: false` is moot.

**Comment by novemberborn** [comment]
There's something to be said for separating AVA's file manipulations from syntax transforms. The `babel` option could refer to syntax transforms only, while we have a separate `transpileEnhancements` option. This would supersede the current `powerAssert` option.

Since we're still looking to integrate source transpilation and also support TypeScript, it makes sense (at least to me) that the enhancements are controlled separately.

**Comment by sholladay** [comment]
I would use this a lot and it would have helped me today. 😃 

See: https://github.com/avajs/ava/commit/37c9122c50722b06039f1cc2306a7c176fd3c786#commitcomment-25662855

**Comment by alpfactory-alex** [comment]
Will this be merged? We'd need that too using Node 8.7

**Comment by cdaringe** [comment]
@novemberborn, you're an 👼 . can't wait to test this out!

**Comment by cdaringe** [comment]
Hmm...

- i installed the latest commit directly from github,
- ran `yarn` (observed the request hit GH, though the gif below is too fast moving :))
- configured ava
- and ran the test

```json5
// package.json
  "ava": {
    "options": {
      "compileEnhancements": false
    }
  }
``` 

sure enough, breakpoints still jump around, leading me to think something is still being transpiled (or built, run, and sourcemapped at least)

![still-transpiling mov](https://user-images.githubusercontent.com/1003261/35494728-75e9b61c-0471-11e8-88d7-dd054e54388c.gif)

**Comment by novemberborn** [comment]
@cdaringe that's not how AVA's options are set. You'll *also* still need to disable the regular Babel compilation that AVA applies:

```json
"ava": {
  "babel": false,
  "compileEnhancements": false
}
```

**Comment by sholladay** [comment]
What would this do?

```json
"ava": {
  "babel": false,
  "compileEnhancements": true
}
```

Would the `false` be ignored? I'm wondering if it should imply `"compileEnhancements" : false`.

**Comment by novemberborn** [comment]
@sholladay AVA won't apply the `stage-4` preset, but power-assert will keep working, and we'd detect `t.throws(throw new Error())`.

Whilst those last two features are currently provided through a Babel preset I think that's an implementation detail. We could change the compiler we use, and when we add native support for TypeScript we may still want to add those features to test files written in TypeScript.

**Comment by cdaringe** [comment]
hey @novemberborn, whoops, sorry for that!

even with

```js
"ava": {
  "babel": false,
  "compileEnhancements": false
}
```

i'm still seeing the jumpiness.  is the file still being meddled with or source mapped somehow?

**Comment by novemberborn** [comment]
@cdaringe are you per chance applying `nyc` in your test run? Feel free to pop in on https://gitter.im/avajs/ava so we can hash this out more directly (assuming our time zones have some overlap).

**Comment by cdaringe** [comment]
hi @novemberborn, thx for the continued support.  indeed, i was using nyc.  after removing nyc, however, the issue persists.  sorry i was late to see this message.  im out for a few days for surgery but will be back soon.  i'll try and reach out to you on gitter then.

**Comment by cdaringe** [comment]
OR, here's a teeny tiny reproduction: https://github.com/cdaringe/vscode-ava-no-transpile-party-time

it's [wired up](https://github.com/cdaringe/vscode-ava-no-transpile-party-time/blob/master/package.json#L23-L26) per instruction.  clone, `npm i/yarn`, then readme steps!

**Comment by novemberborn** [comment]
@cdaringe aha! `profile.js` doesn't skip compilation. It's a bit of an odd duck. Nice catch!

**Comment by StarpTech** [comment]
Is this issue with vscode really a vscode issue? When I add a breakpoint in a jest file with es modules and inside an async function it works fine!
