### ISSUE TITLE
Global .afterEach and .afterEach.always hooks

### ISSUE THREAD

**Issue by Martin-Kuca** [avajs/ava#1559]
Hi, I am wondering if there is a way to globally set up my .afterEach and .afterEach.always hooks so that I don't have to define them in every single test file.

Currently I have about 20 test files and each of them has the following:

.afterEach hook

```
test.afterEach('this only runs when test succeeds', async t => {
  // eslint-disable-next-line mutation/no-mutation
  t.context = 'success'
})
```

and .afterEach.always hook

```
test.afterEach.always('clean up', async t => {
  if (t.context !== 'success') {
    const screenshotBuffer = await browser.saveScreenshot()
    const screenshotKey = `failed-test-screenshot-from--${testfilename}--${Date.now()}`
    uploadFileToServer(screenshotBuffer, screenshotKey)
  }
  // .... more code specific to each test file
})
```

Whenever I change a bit of this logic I have to go to every one of those 20 test files and change them accordingly.

Is there a way to set up a global ava .afterEach and .afterEach.always hook or would you be willing to implement it?
I'm thinking that the main problem of the global hooks would be the fact that each test file might share a lot of code but differ either in the start of the hook or in the end of the hook (as in my .afterEach.always hook). It could therefore take an optional two arguments that would define whether there should be some code inputted at the start or the end of the test.

For example:
```
test.afterEach.global('this is a global afterEach hook', async (t, optionalStartCode, optionalEndCode) => {
  optionalStartCode
  console.log('this is the global part of the global test hook')
  optionalEndCode
})
```
Sorry for the post to be this long, it's just an idea that would benefit me greatly and probably would benefit more people also.

Thank you for reading

**Comment by sindresorhus** [comment]
You could place your hooks in a separate file that has a function that accepts the `test` instance and creates the hooks and import and initiate that in each file.

**Comment by Martin-Kuca** [comment]
@sindresorhus Yeah, I just realized this while making coffee right after posting this. I am sorry for a probably completely unnecessary suggestion and a very long issue. 

Thank you for an extremely quick response! :-)
