### ISSUE TITLE
Make test-worker process independent

### ISSUE THREAD

**Issue by unional** [avajs/ava#1576]
ava@0.23

I am trying to work on a vscode extension to support debugging with AVA+TypeScript.

I looked at `profile.js` and IMO it hacks around to fool `test-worker` that it is working on a child process.

Would you take a PR to make `test-worker` communicates using events and the current consuming code have an adapter between the event emitter and the process?

**Comment by novemberborn** [comment]
I don't think we're ready to settle on any kind of stable interface to the workers, or indeed making these low-level parts extensible, sorry. The best bet at this stage is to use the CLI. The `profile.js` stuff is quite the hack in itself and not fully baked IMHO.

(Closing now to keep the issue count down, but please feel free to continue the discussion.)

**Comment by sindresorhus** [comment]
@unional Would https://github.com/avajs/ava/issues/1332 help you? If so, that one is "PR welcome". If not, can you elaborate on what you need instead of how? Maybe we can figure out a better way to achieve it together :)

**Comment by unional** [comment]
I think it might. My idea is to make the `test-worker` independent from the context thou. i.e. it should contain logic to run test, without knowing it is running in `process` or `vm`.
Then, you can consume it in `process` or `vm` by just using an adapter to hook up the events from an event emitter to the `process` or `vm`

**Comment by sindresorhus** [comment]
@unional Agreed. That's how it should work.
