### ISSUE TITLE
Can I define the number of the parallel test?

### ISSUE THREAD

**Issue by rossoneri520** [avajs/ava#1577]
## Description
I got this warning when I run test in 10 parallel

(node:14004) MaxListenersExceededWarning: Possible EventEmitter memory leak dete
cted. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:14004) MaxListenersExceededWarning: Possible EventEmitter memory leak dete
cted. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit

then some test fail with "Rejected promise returned by test", I guess memory leak take chrome launch timeout, so can I only reduce the parallel unmber?

BTW, Can I define the number of the parallel test in one JS file?

**Comment by novemberborn** [comment]
@rossoneri520 I assume you have more than ten asynchronous tests in one test file? What AVA version is this with?

> then some test fail with "Rejected promise returned by test", I guess memory leak take chrome launch timeout, so can I only reduce the parallel unmber?

I'm not sure what you mean here with memory leaks and chrome launch timeout.

> BTW, Can I define the number of the parallel test in one JS file?

No, but you can use `test.serial` to run one test at a time (within that test file).
