### ISSUE TITLE
`t.deepEqual` doesn't work with Proxy objects

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1578]
## Description

AVA can't handle `t.deepEqual` on Proxy objects. It eventually crashes the Node.js process. Seems to be an issue with Concordance.

### Test Source

Uncomment the code in https://github.com/sindresorhus/negative-array/blob/9a13a27cc9bd18101998e924d5afc4eeee0ab7c2/test.js#L36-L46 and run AVA.

### Error Message & Stack Trace

```
<--- Last few GCs --->

   14971 ms: Mark-sweep 1240.2 (1437.0) -> 1239.6 (1437.0) MB, 1614.0 / 0.0 ms [allocation failure] [GC in old space requested].
   16362 ms: Mark-sweep 1239.6 (1437.0) -> 1239.6 (1437.0) MB, 1390.3 / 0.0 ms [allocation failure] [GC in old space requested].
   17762 ms: Mark-sweep 1239.6 (1437.0) -> 1244.4 (1417.0) MB, 1399.8 / 0.0 ms [last resort gc].
   19141 ms: Mark-sweep 1244.4 (1417.0) -> 1249.0 (1417.0) MB, 1379.1 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x35b5456cfb39 <JS Object>
    2: formatDeep [/Users/sindresorhus/dev/oss/negative-array/node_modules/concordance/lib/primitiveValues/undefined.js:~27] [pc=0x36297783c88] (this=0x42727fed8d1 <an UndefinedValue with map 0x2d3829bdc371>,theme=0xbf8a79b4e19 <an Object with map 0x2d3829bdb4a9>)
    3: arguments adaptor frame: 2->1
    4: format(aka format) [/Users/sindresorhus/dev/oss/negative-array/node_modules/concordance/...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/sindresorhus/n/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/sindresorhus/n/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/sindresorhus/n/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/sindresorhus/n/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/sindresorhus/n/bin/node]
 6: 0x362973079a7
```

## Environment

```
Node.js v6.11.0
darwin 17.2.0
AVA 0.23.0
npm 4.6.1
```

**Comment by novemberborn** [comment]
@sindresorhus interesting:

```js
const arr = require('negative-array')([1, 2, 3)
Array.isArray(arr) // true
Object.prototype.toString.call(arr) // '[object Array]'
arr.length // undefined
```

So `arr` walks like a duck, but it doesn't talk like a duck. I think this causes Concordance to walk through the list items until the process runs out of memory, given https://github.com/concordancejs/concordance/blob/262782ac7f9de37d05c0f5460884ddc4b92e0c85/lib/complexValues/object.js#L116-L124.

I'm inclined to say the real bug is with `negative-array`, and all Concordance can do is to throw an error when it thinks it's dealing with a list but `length` is not a number.

**Comment by sindresorhus** [comment]
Ah, you're right... I didn't realize Proxy would proxy *all* properties of an array. I was just thinking the elements. Should be fixed now: https://github.com/sindresorhus/negative-array/commit/7263ff43c93a0cc817410bb84ad37b312a777cbe

> and all Concordance can do is to throw an error when it thinks it's dealing with a list but length is not a number.

That would have been helpful.

**Comment by sindresorhus** [comment]
Closing as this is my mistake.
