### ISSUE TITLE
Can't import TypeScript module

### ISSUE THREAD

**Issue by HamedFathi** [avajs/ava#1588]
We want to use avajs in our project but seems it can not import some pathes correctly

I imported a class with correct path. you can see the below picture.
VS Code recognize it correctly.

![err](https://user-images.githubusercontent.com/8418700/32793357-f6c100e2-c97a-11e7-800d-03a324536e00.png)

but avajs can not

![err1](https://user-images.githubusercontent.com/8418700/32793474-3ed7163c-c97b-11e7-9327-edfe3c74b5ae.png)

Can anyone guide me why ?

**Comment by HamedFathi** [comment]
@novemberborn 

I am not so familiar with `ts-node/register` Do you have a sample for this problem?

**Comment by novemberborn** [comment]
See https://www.npmjs.com/package/ts-node.

Configure the `require` option as shown in https://github.com/avajs/ava#configuration — but use `ts-node/register` instead of `babel-register`.

**Comment by MarekLani** [comment]
Hello, I am facing same issue. I configured ts-node/register in package.json file: 

`"ava": {
    "compileEnhancements": false,
    "extensions": [
      "ts"
    ],
    "require": [
      "ts-node/register"
    ]
  },`

But I am still seeing Cannot find module 'ava' error. Any idea what else might be wrong?
