### ISSUE TITLE
Want to configure file lookup rules from node_modules

### ISSUE THREAD

**Issue by yangbin1994** [avajs/ava#1589]
Now find the package.json from the test code directory.Want to look up from the directory of bin files like Babel.Or provide a `-- config`

**Comment by sindresorhus** [comment]
Can you please elaborate? I don’t fully understand what you’re requesting. Also explain why you need it.

**Comment by yangbin1994** [comment]
So, in my multiple package project, each subpackage depend on the project under the root directory of `ava`, subpackage often appear this script: ` "test": "../../node_modules/.bin/nyc ../../node_modules/.bin/ava --verbose --tap test/**/*.test.js"`, but gives me a headache, can't seem to like `babel-cli` as long as in the root directory to create a new `.babelrc` can be applied to all child package, to make the configuration of the `ava`, I seem to be in all the subpackage write clear configuration of content.

**Comment by novemberborn** [comment]
AVA will find and use the closest `package.json` from the current working directory. What I've done previously in a monorepo project is to run all tests from the top-level directory, and using globbing patterns to run tests from a specific package.

Alternatively you could use the `extends` option in the Babel configuration to point at a `.babelrc` file in a higher directory. That way you don't have to duplicate the file.

I'd like AVA to work well with monorepos but I'm not convinced yet we'd need to change how we load the configuration.
