### ISSUE TITLE
HOW-TO: ES Modules with @std/esm

### ISSUE THREAD

**Issue by motss** [avajs/ava#1590]
If you're using [@std/esm](https://github.com/standard-things/esm) for your projects, `ava` will not be able to read your `import test from 'ava';` if you're not transpiling ES modules.

The following configuration in `package.json` will help you out:

```json
{
...
"@std/esm": {
  "esm": "all",
  "cjs": true,
  "gz": true,
  "await" true
},
"ava": {
  "require": [
    "@std/esm"
  ]
}
...
}
```

Hope this helps! 🎉

**Comment by sindresorhus** [comment]
@motss Would you be able to submit a recipe?

See: https://github.com/avajs/ava/tree/master/docs/recipes

**Comment by motss** [comment]
@sindresorhus PTAL at the PR #1593

**Comment by dacz** [comment]
It doesn't work for me. I use flow so my `.babelrc`:

```
{
  "presets": ["@babel/preset-flow"]
}
```
and `package.json`

```
...
"@std/esm": { "esm": "all", "cjs": true },
  "ava": {
    "files": ["**/**/*.test.js"],
    "require": ["@std/esm", "@babel/register"],
    "babel": {
      "babelrc": true
    }
  },
...
```
I tried all possible combinations in require section of ava and in `@std/esm` settings.

Outside ava `@std/esm works like a charm. And w/o @std/esm ava works (with some limitations based on babel7).

**Comment by jdalton** [comment]
@dacz head over to the std/esm repo and file the issue there with a simple repro repo and I'll investigate.

**Comment by motss** [comment]
@dacz Thanks for reporting the issue. Are you using Babel 6 or 7? Mind filing an issue at @std/esm as @jdalton suggested with your Babel config to assist in the investigation?

**Comment by jdalton** [comment]
It looks like there was complications with ava support (see https://github.com/standard-things/esm/issues/197#issuecomment-353494337)
