### ISSUE TITLE
load files in browser environment

### ISSUE THREAD

**Issue by telekosmos** [avajs/ava#1591]
Hi there
We have a pretty legacy web application to test. That means, functions in the global scope, files set in the html page inside script tags... In addition to a custom loader, but that is just another function.

I created a very simple test just like:
```javascript
// caller.js
console.log('[caller.js] '+message('it was ok :)'));
```

```javascript
// function.js
function message(msg) {
    console.log('[function.js] this is a... : '+msg);
    return 'this is another -> '+msg;
}
```

```html
<html>
    <script src="lib/alu/test/function.js"></script>
    <script src="lib/alu/test/caller.js"></script>
    <body>
        jeje
    </body>
</html>
```
Obviously, everything works ok in browser. But when I try to test with ava just like:
```javascript
// caller.spec.js
const test = require('ava').test;
let msg;

test.beforeEach(t => {
    msg = message('jojo');
});

test('jojo', t => {
    t.regex('msg', /.*jojo.*/g);
});
```
what we get is the following error:
```sh
> ava --verbose


  ✔ modules › mvtvstandby › utilDate pass
  ✖ caller › beforeEach for jojo Error thrown in test

  1 test failed

  caller › beforeEach for jojo

  /home/nacho/iptv/180001/TEST/spec/caller.spec.js:6

   5: test.beforeEach(t => { 
   6:     msg = message('jojo');
   7: });                    

  Error thrown in test:

  ReferenceError {
    message: 'message is not defined',
  }


npm ERR! Linux 4.4.0-98-generic
npm ERR! argv "/home/nacho/.nvm/versions/node/v6.9.4/bin/node" "/home/nacho/.nvm/versions/node/v6.9.4/bin/npm" "run" "test-ava"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! appweb-unit-test@0.0.1 test-ava: `ava --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appweb-unit-test@0.0.1 test-ava script 'ava --verbose'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appweb-unit-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ava --verbose
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appweb-unit-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appweb-unit-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nacho/iptv/180001/TEST/npm-debug.log
```

Obviously, the problem is we don't know how files are loaded and even if they are loaded given the following `package.json` configuration:

```js

### Config

Copy the relevant section from `package.json`:

```json
{
"scripts": {
    "test-ava": "ava --verbose"
  },
  "ava": {
    "files": [
      "./spec/**/*.spec.js"
    ],
    "require": [
      "./spec/helpers/setup-browser-env.js"
    ],
    "source": [
      "../SOURCE/lib/test/*.js"
    ],
    "tap": false
  },
}
```

The environment:
- Node.js v6.9.4
- linux 4.4.0-98-generic
- npm: 3.10.10
- ./node_modules/ava/cli.js --version: 0.23.0

No ava installed globally.

So, what is the problem here and/or the way to load the files. Is it possible to load the files in order? I mean, here `function.js` has to be loaded before `caller.js`.

Thanks!!

**Comment by telekosmos** [comment]
Forgot to say I'm obviously using `browser-env` in order to mock the browser environment just as described in https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md.

**Comment by novemberborn** [comment]
Node.js loads files differently from the `<script>` tag. Each module has its own scope, so your `message` function is not actually a global. You'll want to use a module loader and a build tool like webpack, so you can author and test your modules and then separate make a bundle that can be used in the browser.

**Comment by telekosmos** [comment]
Sorry for the late view and thanks for the reply. What you tell will be subject of further discussions in our department ;-)
