### ISSUE TITLE
Pre-bind assertion methods

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1592]
Or simply all methods on the test context `t`.

I didn't really buy the use-case in https://github.com/avajs/ava/issues/1255, but after that I've encountered some situations where it could have been useful.

Sometimes I need to skip an assert based on some condition:

```js
test(t => {
	const isTrue = condition ? t.true : t.skip.true;
	isTrue('a', 'b');
});
```

The above results in an error:

```
TypeError {
    message: 'Cannot read property \'_test\' of undefined',
  }
```

Or use a different assertion. I realize it's not a very good practice, but sometimes it's just the best way to do it.

Right now I have to do:

```js
test(t => {
	const isTrue = (condition ? t.true : t.skip.true).bind(t);
	isTrue('a', 'b');
});
```

Which is not very nice.

**Comment by novemberborn** [comment]
Yea we can give it a shot. It's a bunch more function allocations so it'd be interesting to see what happens when there's loads of tests in a single file, but on the other hand I doubt it'll really have an impact, especially in the most recent Node.js.

**Comment by reddysridhar53** [comment]
Can I pick this up?

**Comment by novemberborn** [comment]
@reddysridhar53 it's all yours!

**Comment by irahulcse** [comment]
How to do the work on this project?

**Comment by sindresorhus** [comment]
@irahulcse You mean how to contribute? See our comprehensive contribution guide: https://github.com/avajs/ava/blob/master/contributing.md
