### ISSUE TITLE
fix: string `//# sourceMappingURL=` breaking tests

### ISSUE THREAD

**Issue by zanona** [avajs/ava#1595]
## Description
Apparently, there's a bug on AVA when used with `nyc` for testing where files containing a string with the initial part of a sourcemap instruction, i.e:` //# sourceMappingURL=`, will fail to generate code coverage as well as being tested.

For bug reports, please provide as much *relevant* info as possible.

### Test Source

__index.js__
```js
function someFn(src) {
  const ref = `//# sourceMappingURL=${src}`;
  console.log(ref);
}
module.exports = someFn;
```

__test/index.js__
```js
const {test} = require('ava'),
      someFn = require('../');

test.todo('some fn with hardcoded the sourcemap string');
```

### Error Message & Stack Trace

```
$ nyc ava -v

Transformation error for /Users/zanona/Desktop/ava-sourcemaps-fail/index.js ; return original code
An error occurred while trying to read the map file at /Users/zanona/Desktop/ava-sourcemaps-fail/${src}\n`;
Error: ENOENT: no such file or directory, open '/Users/zanona/Desktop/ava-sourcemaps-fail/${src}\n`;'
  - some fn with hardcoded the sourcemap string

  0 tests passed
  1 test todo

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
✨  Done in 1.56s.
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
nyc ava
```

## Relevant Links

- Repro: https://github.com/zanona/ava-sourcemap-fail

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v8.7.0
darwin 16.7.0
ava --version > 0.23.0
npm --version > 5.5.1
```

**Comment by sindresorhus** [comment]
I can reproduce this with Mocha too, so this would be better posted on the `nyc` issue tracker.
