### ISSUE TITLE
Getting ready for Babel 7

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1598]
Babel 7 will be released soon (#1575). Here's what we're going to do:

* AVA will ship with Babel 7, since its test file transforms should work out of the box
* We'll update https://github.com/avajs/babel-preset-stage-4, https://github.com/avajs/babel-plugin-throws-helper and https://github.com/avajs/babel-preset-transform-test-files to ensure they work with Babel 7, update their CI configuration and release new major versions to prevent any accidental (future) breakage with older AVA releases
* I'll update https://github.com/novemberborn/hullabaloo-config-manager so it can resolve [Babel 7 configurations](https://github.com/novemberborn/hullabaloo-config-manager/issues?q=is%3Aissue+is%3Aopen+label%3Ababel7)

Any changes that are required in the dependencies will be released to npm when they're ready. The remaining changes in AVA itself will be held back until Babel 7 is officially released. We'll do a new AVA release once the dust settles. Those of you working with Babel's beta versions will be able to install from GitHub.

It's possible that AVA won't fully support all the new configuration options, but that won't stop us from releasing Babel 7 support. We'll just have to document what's still missing.

There's a lot of pieces to coordinate here, so for now I've assigned myself to this effort. If you've got some time in the next few weeks and are looking to help out, please chime in here and I'll see where we are. There's lots of [other issues labeled "help wanted"](https://github.com/avajs/ava/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) too 😉 

Thanks!

**Comment by novemberborn** [comment]
> Any changes that are required in the dependencies will be released to npm when they're ready.

Looking at https://github.com/avajs/babel-preset-stage-4/pull/11 this is tricky though, since all the v7 plugins are still released as betas. We'll probably have to install our dependencies from GitHub until Babel 7 is released officially.

**Comment by razor-x** [comment]
With the tight babel integration and no support for using a peer version of Babel, is Ava concerned about users who cannot upgrade yet to Babel 6 becoming locked out of support for the next version of Ava? This issue is exacerbated by not using semver as this change would normally force a major version bump leaving the previous version open for PRs to backport security fixes and bug fixes.

**Comment by novemberborn** [comment]
@razor-x bug fixes could still be backported (they count as patch releases anyhow), but as a general rule the AVA team does not have the resources to maintain earlier versions.

I think this would impact users who customize the Babel configuration that AVA applies to their test files. As far as the official Babel plugins are concerned the Babel 7 versions will be published under new package names, so the test configuration could use new versions whereas sources can still be compiled using Babel 6. Another workaround would be to precompile test files using Babel 6.

I did consider supporting both versions, but as I'm doing the work on the dependencies that seems increasingly complicated.

**Comment by razor-x** [comment]
That's all reasonable. Mostly want to bring up this issue for an official response so affected users understand what Ava development will support and can plan accordingly.

I'd say it's dangerous to assume code that passes tests run through Babel 7 but compiled with Babel 6 will run identically in production. Ideally that's not the case, but one cannot guarantee perfect parity between two major versions.

**Comment by novemberborn** [comment]
> I'd say it's dangerous to assume code that passes tests run through Babel 7 but compiled with Babel 6 will run identically in production.

AVA doesn't compile source code though, it only compiles test files, and by default only to deliver stage-4 syntax to older Node.js versions (plus some other enhancements under our control). I don't expect any breakage there once we finish the upgrade.

**Comment by razor-x** [comment]
Are you saying Ava does not run relative `import`in spec files though the bundled Babel version but through the one specified by your package.json?

**Comment by novemberborn** [comment]
Other than helper files, AVA does not compile source files (the stuff you're testing). You have to use `babel-register` for that (or precompile), so this change will not affect source files.

**Comment by novemberborn** [comment]
@vjpr, @citycide, @cwonrails Please give https://github.com/avajs/ava/pull/1608 a whirl if you have a moment. Note that `.babelrc.js` files are not yet supported.

**Comment by citycide** [comment]
@novemberborn was about to try it out but it looks like `babel-preset-transform-test-files#babel7`  needs its deps updated because `babel-plugin-espower#babel7` was merged to master and removed (https://github.com/power-assert-js/babel-plugin-espower/commit/71e1a50fb44d8308e9c4abc04b6d286a2ea3e4e3)

Until then npm will fail with a _very_ unhelpful message:

```shell
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout babel7
npm ERR! error: pathspec 'babel7' did not match any file(s) known to git.
```

while yarn is a bit more useful since it actually gave me some kind of idea where the problem was:

```shell
yarn install v1.3.2
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find match for "babel7" in "_c" for "https://github.com/power-assert-js/babel-plugin-espower.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by novemberborn** [comment]
@citycide thanks for the heads up. I've updated the dependencies, please give it another go!
