### ISSUE TITLE
Revisiting supported Node.js versions

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1599]
Inspired by [npm's support statement](http://blog.npmjs.org/post/165273023140/supported-nodejs-versions-in-the-npm-cli) I'd like to revisit which Node.js versions we support:

* We'll support any major version that is supported by Node.js itself, see https://github.com/nodejs/Release#release-schedule1
* Removing support for a Node.js version will be a breaking change

The non-LTS releases (7, 9, etc) are odd ducks. We'll support them during their limited lifetime, but support will be unceremoniously dropped (**without a breaking change**) once their lifetime ends.

*Support* here, by the way, means that we run our test suite under the given Node.js versions and will accept pull requests to fix any bugs (provided they're not known bugs in Node.js itself that will be fixed imminently). Consequently, *dropping support* means we'll remove those Node.js versions from our test matrix and will no longer accept specific pull requests to fix bugs under those versions.

For each major version we'll support the latest release. Currently this means we'll support 4.8.6, 6.12.0, 8.9.1 and 9.2.0. Notably this means we'll drop support for 4.3, which is used by AWS Lamda. This has been an issue in the past. (Technically we'll drop official support for 6.10 as well, which is also used by AWS Lambda, but I'm not expecting this to actually break anything.)

I'd like to say that we won't accidentally drop support for minor releases, e.g. by adopting new backported APIs. I'm not sure whether we should enforce this through CI, as that would increase the test duration. I suppose this won't be an issue until we're out of the `0.x` releases, since any feature release can be considered "breaking" anyhow.

@avajs/core and others, what are your thoughts on this?

**Comment by sindresorhus** [comment]
👍 Makes sense.

**Comment by sindresorhus** [comment]
> We'll support any major version that is supported by Node.js itself, see nodejs/Release#release-schedule1

We need to specify whether this means supporting the oldest Node.js maintenance LTS release or active LTS release.

**Comment by novemberborn** [comment]
I did mean maintenance, yes.

I'll see if I can add this to the README and other docs where appropriate.
