### ISSUE TITLE
Customizing the Test Report

### ISSUE THREAD

**Issue by dlumma** [avajs/ava#1607]
Hi All,

I have a general question for you: I am interested in adding additional metadata to each of the tests that I am running through ava, and be able to set and report on these attributes through a tap reporter. 

Is there a way to do this which is already defined in ava?  Or should I try to add support for this?  If so, where might be a good place to look?  Perhaps the snapshot logic?

Thank you,
-Denali

**Comment by novemberborn** [comment]
That sounds interesting. Could you give an example of what kind of metadata you'd like to report, and how you'd like to declare this in AVA?

Is there a standard way of including this information in the TAP output? I'm not sure what we're doing now even lines up to any standard usage.

**Comment by vadimdemedes** [comment]
I don't think there's a standard way for it. Perhaps @dlumma could use TAP comments for it. See https://github.com/avajs/ava#tlogmessage.

**Comment by dlumma** [comment]
Yes, thanks for the comments. In the end, I satisfied my use case my leveraging the TAP comments.  This was difficult for me because of problems related to when t.log can be called, described in detail here: https://github.com/avajs/ava/issues/1536

But I managed to get it working for the time being...
