### ISSUE TITLE
Doc Issue// precompiling-with-webpack // Test against precompiled sources

### ISSUE THREAD

**Issue by EEtancelin** [avajs/ava#1614]
Doc Issue
In Precompiling-with-webpack // Test against precompiled sources,  the last webpack configuration file is presented as being webpack.config.js, but it's seem it's fact it's the webpack.config.test.js.
Or does i misunderstood something ? 

https://github.com/avajs/ava/blob/master/docs/recipes/precompiling-with-webpack.md#webpackconfigjs-3

**Comment by novemberborn** [comment]
@EEtancelin I think you're right, the `precompile-tests` line should be updated to load `webpack.config.js`. Would you like to do a PR to make that change?

**Comment by ppatel221** [comment]
Hello, Im a student in an Open-Source development class and looking to contribute. Can i take care of this?

**Comment by ppatel221** [comment]
Ive requested a PR https://github.com/avajs/ava/pull/1625
