### ISSUE TITLE
Possible to execute a single test function from within a test file containing several?

### ISSUE THREAD

**Issue by dlumma** [avajs/ava#1616]
Hi There,

I am wondering if I can instruct ava to execute a single test function defined in a file which contains several test functions.  Is this possible and if so, how would I do this?

Thanks,
-Denali

**Comment by dlumma** [comment]
The only way around this I can find is to use Visual Studio Code "Toggle Line Comment" after selecting all of the tests I don't currently want to run.  This seems sub-optimal.  

Other advances test frameworks like nose for python have support for single test execution by specifying: module name.class name:function name

Might be worth considering as a new feature.

**Comment by jamestalmage** [comment]
You can use the `--match` flag.

https://github.com/avajs/ava#running-tests-with-matching-titles

**Comment by dlumma** [comment]
Yes, just discovered this.  Thanks! (Apologies for the obvious question.)

**Comment by jgravois** [comment]
new link for 2019 - https://github.com/avajs/ava/blob/master/docs/05-command-line.md#running-tests-with-matching-titles

**Comment by SephReed** [comment]
I can not for the life of me get this to work on files hidden in subfolders.

```
Sephs-MBP:helium-source-repo seph-play$ ava --match='*Controller.test*'

  ✖ Couldn’t find any matching tests

Sephs-MBP:helium-source-repo seph-play$ ava --match='**/*Controller.test*'

  ✖ Couldn’t find any matching tests
```
