### ISSUE TITLE
Find a reference to the name property from within the test function

### ISSUE THREAD

**Issue by dlumma** [avajs/ava#1617]
## Description

I am hoping to simplify my test code as it relates to the test name itself.  Here is an example of one of my tests:

### Test Source

```js
const external_landing = "external_landing";
/**
 * Test the external landing page.
 */
test(external_landing, async t => {

    t.context.test_name = external_landing;
    await t.context.chromeless.goto(pages.external_landing_page.href);
    (await checkpoint(t)).forEach(function(element){t.log(element);})

    t.pass();

});
```

As you can see, the const "external_landing" is defined, then it is passed in as the first argument to the test function, then I set the t.contest.test_name value again.  This is three points of reference that seems like a poor design. Much better would be to simply set the test name to a plain string in the test function argument, and then be able to reference it again later by pointing to whatever internal structure ava uses to store this value.

Any way I can reference this value from within the t => function definition or the t.context object?

Thanks for any pointers!
-Denali

**Comment by sindresorhus** [comment]
You can get the test title from `t.title`, per docs: https://github.com/avajs/ava#t

**Comment by jamestalmage** [comment]
> You can get the test title from t.title, per docs: avajs/ava#t

`t.name` is not documented

**Comment by novemberborn** [comment]
> t.name is not documented

@jamestalmage that's because it doesn't exist, but `t.title` does, and is supported.

@dlumma I'm going to go ahead and close this, but please let us know if `t.title` doesn't solve your issue.

**Comment by dlumma** [comment]
Thanks all!
