### ISSUE TITLE
Stack traces of async (Puppeteer) exceptions only show the last line

### ISSUE THREAD

**Issue by aknuds1** [avajs/ava#1619]
I am having the problem that Ava (v0.24.0 and Node v9.3.0) only shows the last line of the stack for asynchronous exceptions thrown by the [Puppeteer](https://github.com/GoogleChrome/puppeteer/) library in tests. This means I can't tell which line in the test failed, only where in Puppeteer itself the error happened.

I made [a Gist](https://gist.github.com/aknuds1/bc2f21662821c5cc423e2383dd9b63b6) for easy reproduction. It produces the following output:

```
➜  ava-stacktrace npm test

> ava-stacktrace@0.1.0 test /Users/arve/ava-stacktrace
> ava


  1 failed

  A Puppeteer timeout gives a short stacktrace

  /Users/arve/ava-stacktrace/node_modules/puppeteer/lib/FrameManager.js:593

  Rejected promise returned by test. Reason:

  Error {
    message: 'waiting failed: timeout 1000ms exceeded',
  }
```

I can't point out exactly what's going wrong, but I guess Ava should print more of the stack trace, especially the original call site (from within the test)?

**Comment by sindresorhus** [comment]
AVA removes internal stack frames coming from Node.js, but it shouldn't remove any user frames. Can you try replacing [this chunk](https://github.com/avajs/ava/blob/965cbc65d82b12019cdf6a3257b3198dd4181b79/lib/beautify-stack.js#L59-L72) in AVA with `module.exports = stack => stack;` and share what you get?

**Comment by aknuds1** [comment]
@sindresorhus Thanks for the quick reply! The unadulterated stack trace looks like this after your suggested change:

```
Error: waiting failed: timeout 1000ms exceeded
      at Timeout.WaitTask._timeoutTimer.setTimeout (/Users/arve/ava-stacktrace/bc2f21662821c5cc423e2383dd9b63b6-95c510e2794b843c50e0ec5f488559090844da3d/node_modules/puppeteer/lib/FrameManager.js:593:58)
      at ontimeout (timers.js:466:11)
      at tryOnTimeout (timers.js:304:5)
      at Timer.listOnTimeout (timers.js:264:5)
```

God jul! ;)

**Comment by sindresorhus** [comment]
So that means that there are really no more stack frames captured.

**Comment by sindresorhus** [comment]
Closing as I can reproduce this without AVA:

```js
const puppeteer = require('puppeteer');

(async t => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	await page.goto(`https://github.com/avajs/ava`);
	await page.waitForSelector(`#this-doesnt-exist`, {timeout: 1000});
})().catch(console.error);
```

```
❯ node index.js
Error: waiting failed: timeout 1000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/Users/sindresorhus/Downloads/t1/node_modules/puppeteer/lib/FrameManager.js:593:58)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
```

Open an issue on Puppeteer about this instead. God jul :)

**Comment by aknuds1** [comment]
Alright, thanks Sindre, I will try to figure out why no other context is captured in the stack trace. I guess it has to do with intricacies of async JS.

**Comment by aknuds1** [comment]
Also thanks for enlightening me as to the logic of Ava's stack cleaning, it's helpful to know!

**Comment by backspaces** [comment]
So how _do_ you use ava with puppeteer?

I would be OK creating a web page for each test file but don't know how to import ava into the browser. Maybe a browser based assertion library?
