### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#162]
This is just to gather ideas. Not going to do a website until after AVA 1.0.0, as we want to focus on AVA itself, not marketing.

**Comment by sindresorhus** [comment]
Would be nice to embed the Gitter chat on the website: https://sidecar.gitter.im

**Comment by vdemedes** [comment]
How about a live code playground?

**Comment by sindresorhus** [comment]
@vdemedes How would it work exactly? Not sure I understand the purpose.

**Comment by vdemedes** [comment]
@sindresorhus We'd have a text editor on the left side and live output (result of running ava) on the right side. That way we could demonstrate our nice stuff, like super dope assertions.

**Comment by vdemedes** [comment]
Although we'd need AVA to have support for browsers.

**Comment by sindresorhus** [comment]
Oh yeah, that would be cool. We'll have browser support by the time we do a website anyways.

**Comment by Qix-** [comment]
I don't think a live editor will help since this is a test framework. What would you have to test? Make sure to attach everything to analytics to see what's actually being used. :+1:

**Comment by sindresorhus** [comment]
@Qix- Just to give the user a feel of how nice and simple the test syntax is and what the output will look like.

**Comment by sotojuan** [comment]
The main thing I can think of is lots of examples for different kinds of tests. Simple assertions, testing promises/async, testing APIs, etc. Not too many (overwhelming users is bad), but examples help newbies a lot. They don't have to be interactive, just the code and what the output would be.

**Comment by kentcdodds** [comment]
When you've got the website up, if you wanna have a listing for users, you can add PayPal to that list. We're happily using it as of today :-) [PayPal.svg](https://drive.google.com/open?id=0BxZDtibcRzVWUDBHTTZhZVpDQjQ)

**Comment by jamestalmage** [comment]
@kentcdodds - That's awesome news!

**Comment by denar90** [comment]
Hi guys. Talking about site. It can have pages generated form docs and pages with some content, like authors, links to some resources, compare stuff etc. So I propose to build all stuff using grunt/gulp etc. Build tool will grab all content and make html from it, would it be doc file or jade or whatever. 
So site can consist of pages like
 - main page (why AVA, AVA vs other, contributors)
 - sources/plugins
 - docs
 - examples
 - changelog
What do you think guys?
Also what do you think about creating repo in AVA org where issues can be created? Eg. I can prepare some PR's and issues while core team is busy with v1. Someone from core team can from time to time look at it.

**Comment by yowainwright** [comment]
@novemberborn could I get insight into the website priority from the Ava team? 

I'm finding the readme/docs folder to be difficult to navigate for myself—although the documentation is clear. 

Is there a way I that I don't know where I can better navigate the readme and docs folder that I'm not aware of?

**Comment by novemberborn** [comment]
@yowainwright still not a priority until we ship a `1.0` release. We do need to reorganize the documentation though, I think mostly by splitting it out from the main README. You might be interested in the discussion in #1454.

**Comment by novemberborn** [comment]
Closing this until we're in a place where we'd want a website.
