### ISSUE TITLE
can one AVA global variable be used in multiple test files?

### ISSUE THREAD

**Issue by rossoneri520** [avajs/ava#1620]
I want to define a global variable in AVA, it can be set and get when multiple test files is run.  Dose AVA have this api?

**Comment by novemberborn** [comment]
Not directly. Each test file runs in its own process. You could write a helper file and add it to AVA's `"require"` options in `package.json` so it's loaded in each process.

(I'm closing this issue for house keeping purposes, but please comment if this doesn't answer your question.)
