### ISSUE TITLE
Test Runner API

### ISSUE THREAD

**Issue by clemtrek** [avajs/ava#1628]
Any way to run ava tests programatically i.e. From javascript file ?

**Comment by sindresorhus** [comment]
There's is an API, but it's not officially supported and might break at any time. `require('ava/api')`. Example: https://github.com/avajs/ava/blob/c1faf95b9bbaa1981013e98576fc58a4d6217020/test/api.js#L34-L40

**Comment by novemberborn** [comment]
See https://github.com/avajs/ava/issues/1043#issuecomment-339370294.

**Comment by novemberborn** [comment]
@davewasmer It's more that there are other parts of AVA's implementation that should be improved, and I personally don't want to *also* have to worry about how those changes impact a programmatic API. Lots of those issues are covered by the [`scope:scheduling`](https://github.com/avajs/ava/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Ascope%3Ascheduling) label if you're interested.

**Comment by alshdavid** [comment]
I'd prefer to use ava from a programmatic entry point. Would love to see this made available 👍
