### ISSUE TITLE
Global hook to handle failed tests

### ISSUE THREAD

**Issue by indexmotion** [avajs/ava#1630]
I use ava in my project as testing framework, needs to scaffold the processing of errors.

Can ava add an error handler globally (across all test files), triggered if each test fails?

**Comment by novemberborn** [comment]
Any hooks need to be registered in each test file, but you could do that in a helper script and include it via the `require` option in the AVA's `package.json` configuration.

However you can't currently access the test status from such hooks. We're open to that feature though, see #840.
