### ISSUE TITLE
Performance with many test files is showstopper

### ISSUE THREAD

**Issue by james-s-turner** [avajs/ava#1631]
In my projects I have individual test files per component, resulting in hundreds of small test files. The performance  in this scenario is a showstopper for using AVA. The issue is the cost of forking  node processes as recognised in https://github.com/avajs/ava/issues/789. I hoped it might be useful to gather some stats to show the scale of the issue. I created a little script to auto-generate test files and ran them against AVA, Mocha and Jest

| Files  * Tests per file | AVA | Mocha | Jest|
| ------------- | ------------- |  ------------- |  ------------- |
| 7  * 1428  |  2.8 (10.2)|  4.2 (72) | 4.0 (26.0) |
| 8 * 1250  | 2.9 (10.1)  | 4.1 (53) | 4.1 (24) |
| 10 * 1000 | 3.5 (10.6) | 4.2(37) | 4.2 (15.6) |
|100 * 100 | 17.2 (25.3) | 5.5 (12.7) | 5.4 (8.3) |
| 500 * 20 | 73 (78) | 4.8(10.3) | 7.5 (10.3)|

In each case total number of tests executed is 10K - split across different number of files
All times are in seconds
Time in brackets is first run. Presumably higher because of Babel transpilation.
Test is 
```
import test from 'ava';
const double = (x) => x * 2;

test('test double 1', t => {
    t.is(double(1), 2);
});
...
```
As you can see AVA goes from being significantly faster  :-) than the others to an order of magnitude slower dependent on the number of files :-(

I was testing on 8 core MacBook Pro running OS X 10.10.5. 
NodeJs: 8.6.0
AVA: 0.24

Any chance of upping the priority of https://github.com/avajs/ava/issues/789 ?

**Comment by novemberborn** [comment]
Thanks for the research @james-s-turner! Is it in a repo somewhere we could use as a future benchmark?

I think the relevant starting point is now #1332, though it's a little different from #789 as stated. Nothing to stop anybody from implementing #1332 in workers though.

> Any chance of upping the priority of #789 ?

Somebody would have to pick it up 😉

**Comment by james-s-turner** [comment]
OK - I can take a hint ;-) I've already had a brief squirrel around the code.
The auto-generation code is on my laptop at the moment. It takes manual intervention to generate benchmarks. I'll get it working automatically as part of the PR.

**Comment by novemberborn** [comment]
Thanks @james-s-turner. I'm closing this issue for now, let's continue discussing in #1332.
