### ISSUE TITLE
Run AVA as a REPL

### ISSUE THREAD

**Issue by backspaces** [avajs/ava#1632]
## Description

I believe this is a feature request (or documentation)

I need to run node with the same environment as ava has for simple debugging of my test files. 

Currently I believe I have to simply `ava test/FooTests`. But these sometimes fail and I need to know why by actually being in the node repl with the ava environment.

### Test Source

None

### Error Message & Stack Trace

None

### Config

Copy the relevant section from `package.json`:

None

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
    "test": "ava"
```

## Relevant Links

https://github.com/backspaces/as-core

## Environment

 git 2.15.0
 node v8.9.3
 npm 5.5.1
 yarn 1.3.2
 eslint v4.14.0
 ava 0.24.0

**Comment by novemberborn** [comment]
There is a section on Debugging in the README: https://github.com/avajs/ava#debugging

To be honest I've never actually used that myself, but it should work. See also https://github.com/avajs/ava/blob/master/docs/recipes/debugging-with-chrome-devtools.md.

(I'm closing this issue, but please let me know if this helps you, or if I've misunderstood your problem.)

**Comment by backspaces** [comment]
Here's my goal: to somehow start an ava/node repl, in interactive mode. In other words somehow start node/ava, and be left in node so that I can try things within the ava-created environment.

What I mean by that is that I start node, then require('ava.js') and be left in interactive mode to try things just like when using node in interactive mode.

If I try: `node --interactive --inspect node_modules/ava/profile.js` I get `Error('Specify a test file')`.

Or this `node --interactive --inspect node_modules/ava/profile.js test/test.js` it runs the tests, printing out
```
Debugger listening on ws://127.0.0.1:9229/005415cf-dc16-455b-bcc6-dc76cb96948f
For help see https://nodejs.org/en/docs/inspector
TEST: foo null
TEST: AS null
RESULTS: { failCount: 0,
  knownFailureCount: 0,
  passCount: 2,
  skipCount: 0,
  testCount: 2,
  todoCount: 0 }
```
but exits, not remaining in the repl.

How do I simply start ava/node in such a way it remains in the repl, in interactive mode?

**Comment by novemberborn** [comment]
Yea this isn't as easy at it should be. We do have #1505 open, but it looks like we should improve the documentation too.

This works for me:

```js
// test/test.js
import test from 'ava'
debugger
```

```console
$ node --interactive --inspect-brk node_modules/ava/profile.js test/test.js
```

Then if I open `chrome://inspect` I can target the `profile.js` process, press `Continue` and it'll break at `debugger`.

**Comment by backspaces** [comment]
OK we're getting there.  I inserted `debugger` exactly as above. Then ran the node command:
```
node --interactive --inspect-brk node_modules/ava/profile.js test/test.js
Debugger listening on ws://127.0.0.1:9229/0a853d55-8246-46ce-b7c8-1d8d9001e3d3
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
```
I then opened `chrome://inspect` which looked like this:
![snap 01 10 18-16 47 08](https://user-images.githubusercontent.com/124366/34801664-18dca086-f627-11e7-8b01-62c919f51bab.jpg)

I clicked on the `inspect` link and this appeared:
![snap 01 10 18-16 53 12](https://user-images.githubusercontent.com/124366/34801688-3acfd082-f627-11e7-9617-4c2a1bd38176.jpg)

By press continue, do you mean click on the blue debugger continue button?
![snap 01 10 18-16 57 54](https://user-images.githubusercontent.com/124366/34801740-7e98c99a-f627-11e7-9ccc-3934957fb822.jpg)

When I do that I get:
![snap 01 10 18-17 04 17](https://user-images.githubusercontent.com/124366/34801947-662fdf00-f628-11e7-8510-e9f79ea65881.jpg)

That looks pretty hopeful! When I click on `console` I get:
![snap 01 10 18-17 07 19](https://user-images.githubusercontent.com/124366/34802060-d393749e-f628-11e7-942d-5dfb8175363c.jpg)

But when I try to require my cjs rollup I get:
![snap 01 10 18-17 11 10](https://user-images.githubusercontent.com/124366/34802200-8899a958-f629-11e7-8703-c3f8c0553851.jpg)

It does appear to be the right path, using others gives errors. And lots of node works, like using the process.cwd() & __dirname give the right values, and fs=require('fs') works fine.

So it seems like I'm in the wrong scope or something similar??

Thanks a LOT for your patience, a lot of this is new to me so I'm likely doing something silly.

**Comment by novemberborn** [comment]
I'd put the `debugger` in the test or source code that you actually want to debug. That way you can be sure everything is set up exactly as you need it to.
