### ISSUE TITLE
Windows Line Feed Code Excerpt Display Bug

### ISSUE THREAD

**Issue by Adam-Paterson1** [avajs/ava#1636]
## Description

There seems to be a small display bug when printing the code-excerpt for an assertion failure into the console for CRLF encoded files due to windows **\r\n** line feed.
The code-excerpt node module returns lines with **\r** at the end for CRLF encoded files.
ava/lib/code-excerpt.js line 29: 
```js
const excerpt = codeExcerpt(contents, line, {around: 1});
//[ { line: 14, value: '  1 + 1 + 1 + 1;\r' },
//  { line: 15, value: '  t.is(1,2)\r' },
//  { line: 16, value: '  1;\r' } ]
```
These are then joined with **\n** and sent to the equal-length module which re-splits the lines on **\n** and adds trailing spaces to equalize the length of each line:
```js
[ '  1 + 1 + 1 + 1;\r',
  '  t.is(1,2)\r     ',
  '  1;\r            ' ]
```
Due to the **\r**, the trailing spaces override the preceding string, resulting in blanked out characters:
![image](https://user-images.githubusercontent.com/17567279/34902627-5befd07c-f817-11e7-8b2c-32bd8731af79.png)
When it should show:
![image](https://user-images.githubusercontent.com/17567279/34902637-7986a0c0-f817-11e7-8f19-7128e7d4415b.png)

### Ava Source
ava/lib/code-excerpt.js lines 29 to 56:
```js
const excerpt = codeExcerpt(contents, line, {around: 1});
if (!excerpt) {
	return null;
}

const lines = excerpt.map(item => ({
	line: item.line,
	value: truncate(item.value, maxWidth - String(line).length - 5)
}));

const joinedLines = lines.map(line => line.value).join('\n');
const extendedLines = equalLength(joinedLines).split('\n');

return lines
	.map((item, index) => ({
		line: item.line,
		value: extendedLines[index]
	}))
	.map(item => {
		const isErrorSource = item.line === line;

		const lineNumber = formatLineNumber(item.line, line) + ':';
		const coloredLineNumber = isErrorSource ? lineNumber : chalk.grey(lineNumber);
		const result = ` ${coloredLineNumber} ${item.value}`;

		return isErrorSource ? chalk.bgRed(result) : result;
	})
	.join('\n');
```

### Equal Length Source
equal-length/index.js line 8:
```js
const lines = input.split('\n');
```

### Code Excerpt Source
code-excerpt/index.js line 27:
```js
source = tabsToSpaces(source).split('\n');
```
### 1 Avoid Equalizing Length
Remove lines 43 to 46 of ava/lib/code-excerpt.js and remove call to equal-length library:

```js
const excerpt = codeExcerpt(contents, line, {around: 1});
if (!excerpt) {
	return null;
}

const lines = excerpt.map(item => ({
	line: item.line,
	value: truncate(item.value, maxWidth - String(line).length - 5)
}));

return lines
	.map(item => {
		const isErrorSource = item.line === line;

		const lineNumber = formatLineNumber(item.line, line) + ':';
		const coloredLineNumber = isErrorSource ? lineNumber : chalk.grey(lineNumber);
		const result = ` ${coloredLineNumber} ${item.value}`;

		return isErrorSource ? chalk.bgRed(result) : result;
	})
	.join('\n');
```

This fixes the display bug, as after the final join each **\r** is properly matched with a **\n** to create a valid newline. I'm not too sure why the lines need to be equalized personally, so I think this makes things a little simpler.

### 2 Tweak Code-Excerpt Library - (my preference if both can't be implemented)
Replacing code-excerpt/index.js line 27:
```js
source = tabsToSpaces(source).split(/\r?\n/);
```
fixes the problem as the data being passed into the line equalizer is free of any **\r**.
https://stackoverflow.com/questions/21895233/how-in-node-to-split-string-by-newline-n

## Finally
Thank you in advance for any work you do on this as it took me ages to puzzle it out, hope it is helpful :).

**Comment by novemberborn** [comment]
Good find @Adam-Paterson1, thank you for your detailed report.

Ideally we'd fix this upstream: https://github.com/vadimdemedes/code-excerpt/issues/1

If necessary we could normalize the linebreaks before feeding the source to that library.

**Comment by kugtong33** [comment]
lol, another good for beginner issue, can I get this @novemberborn ?

**Comment by novemberborn** [comment]
Go for it @kugtong33! It'd be best to do a PR against the `code-excerpt` library. Mention me in the PR and I'll make sure Vadim sees it.

**Comment by kugtong33** [comment]
@novemberborn , code-excerpt dependency updated to version `2.1.1`
