### ISSUE TITLE
Can't make custom Babel configuration specific for ava

### ISSUE THREAD

**Issue by willnode** [avajs/ava#1640]
## Description

In `package.json` I have this configuration (minimum config to make ava able to transpile my sources):

```js
{
	"ava": {
		"require": "babel-register",
		"babel": "inherit"
	},
	"babel": {
		"presets": [
			"@ava/stage-4"
		]
	},
}
```

Works very good. But according to example from this [documentation](https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#customizing-how-ava-transpiles-your-tests), I can move the babel configuration to be specifiv for ava:

```js
  "ava": {
    "require": "babel-register",
    "babel": {
      "presets": [
        "@ava/stage-4"
      ]
    }
  }
```

But then it does not work.

### Test Source

Modified for demonstration.

test.js:
```js
import test from 'ava';
import {default as foo} from './foo';
test(t => { t.true(foo.bar === "bar") });
```

foo.js:
```js
export default { bar: "bar" }
```

### Error Message & Stack Trace

The following is unmodified stack trace from my project:
```
import test from 'ava';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at extensions.(anonymous function) (X:\@Web\webpack-explorer\node_modules\require-precompiled\index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (X:\@Web\webpack-explorer\node_modules\ava\lib\process-adapter.js:100:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)

  1 exception

  × test.js exited with a non-zero exit code: 1

```

### Config

Copy the relevant section from `package.json`:

```json
  "ava": {
    "require": "babel-register",
    "babel": {
      "presets": [
        "@ava/stage-4"
      ]
    }
  }
```

No other babel config in `babel.rc` or in `package.json` (outside ava). 

**EXTRA:** If I define babel config both inside and outside ava package.json, test will run OK. (is babel config inside ava config is ignored?)

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava
```

## Relevant Links

My project is somewhat huge in depedencies, but [here just in case](https://github.com/willnode/webpack-explorer). modify `package.json` to above before running. 

## Environment

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"

ava --version
npm --version
```
```
Node.js v9.4.0
win32 10.0.16299

0.24.0
5.6.0
```

**Comment by novemberborn** [comment]
When I modify the config I get the following error:

```
/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.Zn9QS0NO2v/webpack-explorer/js/registry.js:9
export default {
^^^^^^

SyntaxError: Unexpected token export
```

Note that this is not in the `import test from 'ava'` line. This makes sense because the `ava.babel` configuration is *only* applied to the test files. `babel-register` now no longer has any configuration to transpile the sources with.

I would use this configuration instead:

```json
  "ava": {
    "require": "babel-register"
  },
  "babel": {
    "presets": [
      "@ava/stage-4"
    ]
  },
```

This way, test files are compiled using the default configuration, and `babel-register` takes care of transpiling sources such that they'll run in Node.js.

I don't know why you got the error on the `import test from 'ava'` line. This crops up every once in a while but I've never been able to reproduce it.

**Comment by willnode** [comment]
Oh wait, sorry I put the wrong stacktrace. That's was my experiment when leaving babel presets empty `"presets": []`. The correct stacktrace points to `export default` like what you get.

My main problem here is that I thought I can put babel config inside ava:

```
"ava": {
    "require": "babel-register",
    "babel": {
      "presets": [
        "@ava/stage-4"
      ]
    }
  }
```

I believe that because I saw the [example for this documentation](https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#customizing-how-ava-transpiles-your-tests). (below is what I assumed to work so far)

```
"ava": {
    "babel": {
      "presets": [
        "@ava/stage-4"
      ]
    }
  }
```

But it still does not work, then I scroll until I found that I miss `"require": "babel-register"`.

To my surprise, it still does not work. Frankly I've spend hours figuring why until I found that I just put my babel settings in the wrong place.

---

Anyway I new here so I really sorry if my story feels weird for you. I'm here to suggest whether it's possible to put a specific babel configuration for ava (using scenario above).

**Comment by novemberborn** [comment]
Hey @willnode, I'm sorry you got stuck here.

> I believe that because I saw the example from this documentation.

That section only applies to AVA's compilation of test files. Indeed it starts with the words *You can override the default Babel configuration AVA uses for test transpilation in `package.json`.*

The section on [transpiling sources](https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#transpiling-sources) introduces `babel-register`. Then there is another section which [combines](https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#transpiling-tests-and-sources-the-same-way) both approaches.

Do you have suggestions on how to improve this recipe?

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by willnode** [comment]
> That section only applies to AVA's compilation of test files. Indeed it starts with the words You can override the default Babel configuration AVA uses for test transpilation in package.json.

Whoa, really? Thanks for that. It makes sense now.

I think we can prevent futher confusion by mentioning that in the documentation.
