### ISSUE TITLE
Use node experimental-modules?

### ISSUE THREAD

**Issue by andyperisho** [avajs/ava#1641]
One way to avoid having to use babel, is to enable the `--experimental-modules` node feature.
So, for example, I'd run: `node --experimental-modules  main.mjs` (mode [here](https://nodejs.org/api/esm.html))

But, i can't seem to figure out how to make ava use experimental modules instead of relying on babel-register. Any clue?

**Comment by novemberborn** [comment]
AVA does not recognize test files with `.mjs` extensions. See https://github.com/avajs/ava/issues/631#issuecomment-357733734. That comment still assumes use of a transpiler or `@std/esm`. I'm not sure how much we should change AVA to work with experimental Node.js features, though I'm open to this as long as the changes are not too intrusive.

I imagine you *can* forward the `--experimental-modules` flag to the worker processes by running `node --experimental-modules ./node_modules/.bin/ava`. Perhaps you can then import `.mjs` *source* files from your tests.

**Comment by jrgleason** [comment]
@novemberborn Nope...

```
node --experimental-modules ./node_modules/.bin/ava ./src/test/js/webdriver/tests/sampleTest.mjs 
(node:1742) ExperimentalWarning: The ESM module loader is experimental.

  ✖ Couldn't find any files to test

node --experimental-modules ./node_modules/.bin/ava ./src/test/js/webdriver/tests/sampleTest.js 
(node:1744) ExperimentalWarning: The ESM module loader is experimental.

⠹ (node:1745) ExperimentalWarning: The ESM module loader is experimental.

  1 test passed
```

**Comment by novemberborn** [comment]
@jrgleason you need to be using the latest AVA release (`ava@next` on npm), and configure it to recognize the `mjs` extension. But even then it may not work. https://github.com/avajs/ava/issues/1810 has more discussion.

**Comment by dandv** [comment]
Indeed, it didn't work. I tried `node --experimental-modules node_modules/.bin/ava ava-test.mjs` and got

> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:
