### ISSUE TITLE
Incorrect stack traces with MongoDBMemoryServer / babel-register

### ISSUE THREAD

**Issue by gisderdube** [avajs/ava#1646]
## Description
We use [MongoDBMemoryServer](https://github.com/nodkz/mongodb-memory-server) in our tests to enable DB mocks. This alone is not really a problem. However, the package uses ES6 `import` /  `export` syntax, which is not supported in node / ava. To enable it, you seem to have to use `babel-register`. With the usage of this package, the tests work fine, __except__ for the error stacks. Those seem to be off, because of the transpiling (?!), please see the sample error stack below. The validator.js file is in fact only 342 lines long, but the stack trace shows me an error in line 378. I set up the memory server and the configuration similar as in the [guide](https://github.com/avajs/ava/blob/master/docs/recipes/endpoint-testing-with-mongoose.md). If desired, I can provide the setup, but I think the problem lies within the babel-register configuration. I would also be happy with just not using the `import` / `export`syntax, but I don't see a way to not use it with the MongoDBMemory server.

Any help would be greatly appreciated.

### Error Message & Stack Trace

```
  _callee5$ (backend/services/service/validator.js:378:31)
  tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
  Generator.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
  Generator.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)

```

### Config
```json
{
  "ava": {
        "files": ["backend/**/*.test.js"],
        "source": ["backend/**/*"],
        "failFast": true,
        "require": ["babel-register", "babel-polyfill"],
        "babel": {
            "presets": ["es2015", "stage-0"],
            "plugins": ["espower", "transform-runtime"],
            "sourceMaps": "both",
            "babelrc": false
        }
  }
}
```

### Command-Line Arguments
```
ava --watch --verbose
```

## Environment
```
Node.js v8.9.4
darwin 17.3.0
ava 0.24.0
npm 5.6.0
```

**Comment by novemberborn** [comment]
> However, the package uses ES6 import / export syntax

I imagine you can use it with `require()`, despite their documentation.

> With the usage of this package, the tests work fine, except for the error stacks. Those seem to be off, because of the transpiling (?!)

Probably. There isn't anything we can do about that though.

**Comment by gisderdube** [comment]
Unfortunately, to `require` a module, the given module has to be a commonJS module (`module.exports`), since commonJS modules are loaded synchronously, whereas ES6 modules are loaded asynchronously. Since the MongoDBMemoryServer is declared as a ES6 module, it is not possible to just `require()` it.

The reason why I'm writing that here is that the [guide in this repo](https://github.com/avajs/ava/blob/master/docs/recipes/endpoint-testing-with-mongoose.md) explicitly recommends using the MongoDBMemory Server. I am just wondering how the people wh o wrote that guide handled the situation.

A more general thing: When transpiling scripts with babel, the stack traces are correct (when configured correctly /w sourcemaps). Here I don't know why the stack trace is off.

**Comment by novemberborn** [comment]
`mongodb-memory-server` is distributed as CJS:

```console
$ npm i mongodb-memory-server
$ node -pe "require('mongodb-memory-server')"
{ MongoMemoryServer: [Function: MongoMemoryServer],
  MongoInstance: { [Function: MongodbInstance] childProcessList: [] },
  MongoBinary: { [Function: MongoBinary] cache: {} },
  default: [Function: MongoMemoryServer] }
```

**Comment by gisderdube** [comment]
Thanks a lot. Having this insight solved my issue. For anyone having this issue:
```
const MemoryServer = require('mongodb-memory-server').MongoMemoryServer

const mongod = new MemoryServer()
```

solved it. Just doing 
```
const MemoryServer = require('mongodb-memory-server')

const mongod = new MemoryServer()
```

threw an error. Thanks a lot for you help @novemberborn

**Comment by novemberborn** [comment]
@gisderdube you're welcome! The example relies on AVA transpiling the `import` syntax to CJS, the result of which does work with `mongodb-memory-server`. But you're right that if you use `require()` directly you need to make further adjustments.
