### ISSUE TITLE
Error running ava in wallaby with esm

### ISSUE THREAD

**Issue by Lichtjaeger** [avajs/ava#1649]
### Description

I run into an error if I try to run my tests with "@std/esm" support in wallaby.
Running the test via `ava` command does work.

### Test Source

[See my repo.](https://github.com/Lichtjaeger/test-wallaby-esm-ava)

### Error Message & Stack Trace

```
d:\pscheler\Documents\Projekte\Tests\esm\node_modules\ava\lib\process-adapter.js:1​​
​​SyntaxError: Unexpected token r in JSON at position 0​​
​​    at JSON.parse (<anonymous>)​​
​​    at Object.<anonymous> (d:\pscheler\Documents\Projekte\Tests\esm\node_modules\ava\lib\process-adapter.js:29:19)​​
​​    at Object.Module._extensions..js (module.js:671:10)​​
​​    at Object.Module._extensions..js (module.js:671:10)​​
​​    at Object.<anonymous> (d:\pscheler\Documents\Projekte\Tests\esm\node_modules\ava\lib\test-worker.js:22:17)​​
​​    at Object.Module._extensions..js (module.js:671:10)​​
​​    at Object.Module._extensions..js (module.js:671:10)​​
​​    at Object.<anonymous> (d:\pscheler\Documents\Projekte\Tests\esm\node_modules\ava\lib\main.js:2:16)​​
​​    at Object.Module._extensions..js (module.js:671:10)​​
​​    at Object.Module._extensions..js (module.js:671:10)​​
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "@std/esm": "cjs",
  "ava": {
    "require": [
      "@std/esm"
    ]
  }
}
```

But this works. There is only a problem with the execution in wallaby.

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

I don't know. They are passed by wallaby.

## Relevant Links

wallabyjs/public#1474
[Example Repo](https://github.com/Lichtjaeger/test-wallaby-esm-ava)

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v9.3.0
win32 10.0.16299
ava --version --> 0.24.0
npm --version --> 5.5.1
```

**Comment by novemberborn** [comment]
Going by https://github.com/wallabyjs/public/issues/1474#issuecomment-359390677 this is an issue with Wallaby. Please let me know if this is something on AVA's end after all 😄
