### ISSUE TITLE
node_modules shouldn't ALWAYS be excluded; is there an override?

### ISSUE THREAD

**Issue by majgis** [avajs/ava#1651]
In my project, I have the node_modules folder at the root of the project that we all know in love, but I also include node_modules folders in my source.  This pattern eliminates the need for relative imports, and the scope of "internal", ie. application specific and unpublished, packages can be promoted as need.

For the life of me, I can't get tests in these sub-node_modules folders to run.  Is there a way to override the default behaviour of excluding all node_modules folders?  I only want to exclude the node_modules folder at the root of the project.

**Comment by sindresorhus** [comment]
I don't know if it currently works or not, but we should support negating the ignore pattern to unignore default ignore patterns: `"files": ["!foo/node_modules/**"]`

**Comment by majgis** [comment]
I will give it a try, thank you for the suggestion.

**Comment by majgis** [comment]
I added the following to the package.json
```js
  "ava": {
    "files": [
      "runtimes/node_modules/*.test.js"
    ],
    "tap": true
  }
```
Which gives this output
```
$ ava
TAP version 13
# Couldn't find any files to test
not ok 1 - Couldn't find any files to test

1..0
# tests 0
# pass 0
# fail 1
```
Despite the fact that there is one test file present:
```
$ ls runtimes/node_modules/*.test.js
runtimes/node_modules/getCachePath.test.js

```

I'm expecting that by being explicit, I'd override the default ignores, but it doesn't seem to be the case.  Let me know if I got the syntax wrong.

**Comment by novemberborn** [comment]
I'm afraid this is a known issue: #1173. There's currently no solution. As you can see in the [`scope:globbing` issue list](https://github.com/avajs/ava/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Ascope%3Aglobbing) we have a bunch of problems in this area, it's my next priority to figure this stuff out.
