### ISSUE TITLE
Handle compilation of files ignored by Babel

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1667]
Babel can be configured to ignore test and helper files. When AVA compiles those files it'll [receive `null` instead of the expected result object](https://github.com/avajs/ava/blob/7be7fe80234af9008700502f84e7b7439c3ed82c/lib/caching-precompiler.js#L57).

We need to bail out if this is the case, by [returning `null` before attempting to use the result object](https://github.com/avajs/ava/blob/7be7fe80234af9008700502f84e7b7439c3ed82c/lib/caching-precompiler.js#L69).

This needs to be handled upstream, to [avoid writing `null` to disk](https://github.com/avajs/caching-transform/blob/50cc9935bad0465bc1da6505e25576b59477a14e/index.js#L83).

Additionally we [must not return a file hash](https://github.com/avajs/ava/blob/7be7fe80234af9008700502f84e7b7439c3ed82c/lib/caching-precompiler.js#L39) to the API, and the API must check for the lack of the file hash when compiling [tests](https://github.com/avajs/ava/blob/7be7fe80234af9008700502f84e7b7439c3ed82c/api.js#L65) and [helpers](https://github.com/avajs/ava/blob/7be7fe80234af9008700502f84e7b7439c3ed82c/api.js#L150).

**Comment by kelvinman** [comment]
I'm interested to work on this

**Comment by liewrichmond** [comment]
Hey just checking in on this issue. Is there any way I could help on this?

**Comment by novemberborn** [comment]
@liewrichmond yea, that'd be great! The issue contains links to the various files and one dependency that needs fixing. Code may have changed a little bit since then. Let me know if you've got any questions.

**Comment by liewrichmond** [comment]
@novemberborn ok thanks! I'm really excited to work on this. It's my first real open source contribution I'm still trying to get my bearings with ava and the issue itself but I'll start on this as soon as I can

**Comment by liewrichmond** [comment]
@novemberborn Do you have any suggestions on testing the potential bug fix/ steps to reproduce the bug?

**Comment by novemberborn** [comment]
@liewrichmond top of my head, in the `.babelrc`:

```
{
  ignore: ['test.js']
}
```

And then `npx ava test.js` should trigger this. You may need to delete `node_modules/.cache` if you were trying to reproduce this previously.
