### ISSUE TITLE
Inconsistent behavior defining tests dynamically inside (nested and top level) async functions

### ISSUE THREAD

**Issue by JayAndCatchFire** [avajs/ava#1672]
## Description
I'm not sure if what I'm describing is a bug or just a request for support.  I'm experiencing unexpected behavior when trying to create test cases dynamically inside of an async function (or sometimes nested async functions).  In most cases, no tests are detected by AVA at runtime.  In some cases, test cases are inconsistently detected, making me think it might be a race condition problem.  In some cases, test cases are consistently detected when using the `ava` executable, but not when using the debugging procedure explained in your README.

## Relevant Links
I've made a reasonably comprehensive repository to minimally recreate what I'm experiencing.  There are more details in my README file.

https://github.com/JayAndCatchFire/ava-async-issue-example

## Environment
linux 4.13.0-32-generic (Ubuntu 16.04 AMD64)
Node.js v8.9.4
AVA 0.25.0
yarn version v1.3.2
npm 5.6.0

That's the environment in which I set up my example repository.  I'm also able to reproduce the results on macOS 10.13.3 with the rest of the versions being the same.

**Comment by novemberborn** [comment]
Thanks for the detailed report @JayAndCatchFire! The bad news is that AVA isn't meant to run those tests. It should have told you though! The good news, as it were, is that you found a bug so now we can improve things. To that end, please see #1674.
