### ISSUE TITLE
Feature request: t.warn

### ISSUE THREAD

**Issue by JayAndCatchFire** [avajs/ava#1673]
## Description
It would be nice if there was a `t.warn` function to complement `t.log`.

I'm doing differential testing.  If the original version of a function and a refactored version of that function return the same results, that test should pass, end of story.  However, if the refactored version should take longer to execute than the original, I'd like to throw a warning messing in the output.

There's currently the `t.log` function, which is great.  But it only prints a message when AVA is in verbose mode and it formats that message with an informational, purple, lowercase "i" in front of it.  (Perhaps `t.info` would be a more accurate description?)

Perhaps a `t.warn` function would print the message with a yellow "!" in front of it?  This also introduces the possibility of logging levels beyond simply verbose and quiet.  Maybe I want to always see warnings, but never log/info messages.

Just some ideas to toss around.

**Comment by novemberborn** [comment]
I think `t.log()` is best suited for debugging test failures. You could manually prefix the log messages if you want to use it as a communication channel. I don't think AVA needs to implement full-fledged logging.

The logs should also be available in the TAP output if that makes it easier to process.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by jamiebuilds** [comment]
I'd actually like to see a `t.warn()` along with a whole warning system. It'd be nice to see them collected in the final output:

```js
$ ava

  ✔ foo
    ⚠︎ blah() is deprecated, use blerg()
  ✔ bar
  ✔ baz
    ⚠︎ blah() is deprecated, use blerg()

3 passed
2 warnings
```

**Comment by novemberborn** [comment]
@jamiebuilds could you elaborate on the use cases for `t.warn()`? Are you thinking about libraries that perform assertions for you? I don't see why you'd use this in your own test files.

Would https://nodejs.org/api/util.html#util_util_deprecate_fn_msg_code be sufficient for a deprecation scenario?

**Comment by JayAndCatchFire** [comment]
I was actually thinking in terms of tests that aren't pure equality.  For example, a function that should return a value within a certain range of known good values.  But if the return value starts to slip too close to the edges of what's acceptable, throw a warning.  Of course, I realize that my example is stretching the definition of unit testing.
