### ISSUE TITLE
Collecting and running tests needs some cleanup

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1674]
As raised in #1672 our requirement that tests must be declared synchronously is no longer properly enforced. I think this broke when we switched to limited concurrency (#1467).

Originally all workers sent their tests to the main process, and once all workers were ready did we start running the tests. Any test declared after this point would [throw an error at the point of declaration](https://github.com/avajs/ava/blob/d42865be9f9484a6a3ab7e90a91283ec50c0d405/lib/runner.js#L71:L730). We still have the code logic for this, and a unit test, but the unit test is at the `runner` level rather than an integration test. It doesn't seem to have an effect in #1672.

Further, despite us saying that tests should be declared synchronously, the ["start running your tests" instruction](https://github.com/avajs/ava/blob/d42865be9f9484a6a3ab7e90a91283ec50c0d405/api.js#L274) is sent over IPC which is inherently asynchronous.

We also don't detect later `test()` calls [when we're looking to only run exclusive tests](https://github.com/avajs/ava/blob/d42865be9f9484a6a3ab7e90a91283ec50c0d405/lib/runner.js#L216).

We need to update our test running logic:

* When `test()` is first called, schedule running them using `process.nextTick()`. This should happen in `lib/runner.js` itself to avoid any other asynchronicity from being introduced.
* Any `test()` call in a subsequent tick should cause that test to be marked as failing with an appropriate reason. The test should never run.
* Workers should run tests in the tick after the first one has been registered. There should be no need to wait for IPC with the main process.
* There is no requirement that `test()` is called immediately. This allows for asynchronous module loading and top-level `await`.

It's important that no new tests are registered once tests start running. Allowing it makes it hard to know when all tests are finished, or to tell when a test might be stuck. I think the above approach should work since presumably the worker process doesn't exit whilst there is something going on that will end up registering a new test, and once that completes we'll immediately fail that test without ever running it.

**Comment by okyantoro** [comment]
Whoa, it is an interesting issue. I would like to follow the discussion since I want to understand the high level overview of how ava work.
