### ISSUE TITLE
profile.js script does not compile helpers

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1677]
Unlike AVA itself, the `profile.js` script, which can be used for debugging, does not compile helpers.

I'm not sure whether we ought to make `profile.js` behave more like regular AVA, or whether we should focus on a built-in debug mode: #1505. Probably the latter.

**Comment by sindresorhus** [comment]
`profile.js` was only meant as a stop-gap solution before we could introduce a better permanent solution, so I would go with the latter.
