### ISSUE TITLE
async/await causes beforeEach of another test to invoke.

### ISSUE THREAD

**Issue by unional** [avajs/ava#1681]
ava@0.24 and 0.25 both have this problem.
```ts
test.beforeEach(() => {
  console.log('before')
})
test.afterEach(() => {
  console.log('after')
})

test('a', async () => {
  console.log(1)
  await foo(1)
  console.log(2)
  await foo(2)
  console.log(3)
})
test('b', async () => {
  console.log(4)
  await boo(1)
  console.log(5)
  await boo(2)
  console.log(6)
})
```

prints out:
```sh
before
before
before
before
before
1
before
4
2
5
6
after
after
after
after
after
```

Here is the source: https://github.com/unional/komondor/blob/ava-async/src/config.spec.ts#L109-L137

**Comment by novemberborn** [comment]
This is by design. Tests run concurrently. `b` is started regardless of whether `a` finishes. Starting `b` means its `beforeEach` hook is also run.

Use `test.serial()` to ensure tests run serially.
