### ISSUE TITLE
Improve `Observable` typing in TS and Flow definitions

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1685]
We currently type `Observable` like so:

```ts
export interface ObservableLike {
	subscribe(observer: (value: any) => void): void;
}
```

I think we should include a more complete type definition. See the `index.d.ts` and `index.js.flow` files.

**Comment by novemberborn** [comment]
This has caused an issue in the past: #1236.

**Comment by sindresorhus** [comment]
@novemberborn How about [this one](https://github.com/sindresorhus/type-fest/blob/c6a3d8c2603e9d6b8f20edb0157faae15548cd5b/source/basic.d.ts#L56)?

**Comment by novemberborn** [comment]
@sindresorhus I don't use observables much, so sure 😄

**Comment by novemberborn** [comment]
@sindresorhus I'm not sure we fully understood this change. #1236 referred to a Flowtype issue. For TypeScript, before this change, anything with a `subscribe()` would've been a valid test implementation return value, but now it *also* needs the `[Symbol.observable]()` function. Do we want to require that second property? Should we support *either* property instead?

**Comment by sindresorhus** [comment]
I feel that "just a `subscribe` function" is too loose. It could accidentally match just a normal object too. The TS type now ensures it's an actual Observable. All the Observable libraries I know of uses `Symbol.observable`. We can reconsider if it causes any problems.

**Comment by micaelmbagira** [comment]
@sindresorhus @novemberborn I believe this fix broke something else. The following test in TypeScript:

```ts
test('foo', t => {
  return of(3).pipe(tap(() => t.pass()));
});
```

does not compile because of the following error

> 
>  error TS2345: Argument of type '"foo"' is not assignable to parameter of type 'OneOrMoreMacros<[(t: ExecutionContext<{}>) => Observable<number>], {}>'.
>
>  test('foo', t => {
>         ~~~~~
