### ISSUE TITLE
Restore embedded documentation in TS and Flow definitions

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1686]
I completely refactored the type definitions in #1670 without retaining the embedded documentation. Sorry about that 😞 

It'd be great to restore and even improve the embedded documentation. The `index.d.ts` and `index.js.flow` files are quite similar to each other, so work should start on one and then by copied to the other. Screen grabs of how the documentation is displayed in code editors would be useful so we can review how much documentation should be included.

**Comment by kugtong33** [comment]
@novemberborn , a lot has happened in the past days when I was gone, I think its my time to dive into documentation, do you need help with this one?

**Comment by novemberborn** [comment]
@kugtong33 that'd be great, thanks!

**Comment by kugtong33** [comment]
@novemberborn 

How does `ifError` differs from `falsy` if both checks the value then fails when it is truthy?

**Comment by kugtong33** [comment]
![ava assertions](https://user-images.githubusercontent.com/3274087/36349640-06af54d6-14c6-11e8-8cd9-0d9aaa3b77c3.gif)

I hope this gif is helpful, I find it fast myself, lol

**Comment by novemberborn** [comment]
> How does ifError differs from falsy if both checks the value then fails it when value is truthy?

I know… I've just opened #1720.
