### ISSUE TITLE
ava/test-ended error on function defined outside

### ISSUE THREAD

**Issue by niftylettuce** [avajs/ava#1687]
I receive the following lint error if I define a function `someFunction(t) { ... }` that calls `t.end` inside of it and use `test.cb.beforeEach(someFunction)` or `test.cb.afterEach(someFunction)` such as:

```
const someFunction = t => {
  t.end();
};

test.cb.beforeEach(someFunction); // <--- lint error here
```

```log
Callback test was not ended. Make sure to explicitly end the test with `t.end()`. (ava/test-ended)
```

**Comment by novemberborn** [comment]
This is better discussed in `eslint-plugin-ava`. Looks like you ran into this before @niftylettuce 😉 https://github.com/avajs/eslint-plugin-ava/issues/180#issuecomment-363087470
