### ISSUE TITLE
Add `beforeAndAfter` test method with cb variants

### ISSUE THREAD

**Issue by niftylettuce** [avajs/ava#1688]
It'd be great to have a beforeAndAfter fn available that also has a cb variant.

It'd run the same code/function before and after.

**Comment by novemberborn** [comment]
@niftylettuce could you expand on the use case? What kind of code would you run before and after a test suite?

**Comment by sindresorhus** [comment]
```js
const beforeAfter = () => { … };
test.before(beforeAfter);
test.after(beforeAfter);
```

**Comment by niftylettuce** [comment]
closing as we don't need this
