### ISSUE TITLE
match params question

### ISSUE THREAD

**Issue by MrZhouChiBang** [avajs/ava#1691]
when I test doc demo
```
test('foo', t => {
	t.pass();
});

test('moo will also run', t => {
	t.pass();
});

test.only('boo will run but not exclusively', t => {
	t.pass();
});

test.only('sadfsdf', t => {
	t.pass();
});

test(function (t) {
	t.fail();
});

test(function foo(t) {
	t.fail();
});
```

and run `ava --match='*oo*' -v`,but it doesn't work (with win10)

![qq 20180206143817](https://user-images.githubusercontent.com/17632172/35845031-73f347fc-0b4b-11e8-8e4d-fa26889c6de4.png)

But it can be work in MAC.

And I find the difference between windows and mac

![qq 20180206144554](https://user-images.githubusercontent.com/17632172/35845234-773ec5c0-0b4c-11e8-97cb-d0c6bb7e8c97.png)

get `[ '\'*oo*\'' ]` in windows
get `[ "*oo*" ]` in mac

why not remove single quotes, so it can be work both of windows and mac
`ava --match=*oo* -v`

**Comment by sindresorhus** [comment]
You have to use double-quotes on Windows. That's not really something to do with AVA, but rather how the command-line works on Windows.

**Comment by MrZhouChiBang** [comment]
thx
Could you modify the document to avoid the mistake?
