### ISSUE TITLE
Merge two or more tests ?

### ISSUE THREAD

**Issue by MagixInTheAir** [avajs/ava#1695]
I have a test-suite based on a single macro, like follows : 

```
let iterations = 30;
for(let i = 0; i < iterations; i++) {
    test('Test ('+(i+1)+'/'+iterations+')', testMacro, {
        param1: chance.bool(),
        param2: chance.bool(),
        param3: chance.bool(),
        param4: chance.bool(),
        param5: chance.bool(),
        param6: chance.bool()
    }); 
}
```

Can I merge those tests into a single test entry ? I need a clean context for each one of them and couldn't find a way to refactor them in a single test() call. Is there a trick ?

**Comment by novemberborn** [comment]
Rather than using `beforeEach` hooks to set up your context, call a function. Then you could move the loop inside your test implementation and create a clean context for each iteration.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by MagixInTheAir** [comment]
I would have to skip the `beforeEach` call only in this single test then ? Is there a way to do this ?
This looks like a sensible work-around, but maybe a better solution will be found :)

**Comment by novemberborn** [comment]
You could assign the `beforeEach` implementation to a variable. Use it with `test.beforeEach` and then repeatedly call it inside your test.
