### ISSUE TITLE
Ensure workers inherit color level from main process

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1701]
Workers don't inherit the correct color level from the main process. @nowells raised this in #1455. This got entangled with a solution for #1393, by @kevva in #1401. I'm now fixing that with #1700.

As of #1700 workers remove AVA's internal flags from `process.argv`. We could apply the solution from #1455 so workers correctly inherit the color level.

I'm concerned that `chalk` / `supports-color` will behave inconsistently in the test processes. If the user code shares its `chalk` / `supports-color` dependencies with AVA, they'll inherit the color level from the main process. Otherwise the color level is detected afresh. I don't think AVA should foist the `--color` / `--no-color` flags onto the worker process. We could solve this inconsistency by bundling `chalk`. That way we can be sure to only configure *our* copy and leave user code unaffected. Users can still manipulate color levels in their test processes through environment variables or additional command line arguments.

@nowells, @kevva, @sindresorhus, what do you think?

**Comment by jamiebuilds** [comment]
Cherry picked changes from #1455 into #1713 on latest master

**Comment by novemberborn** [comment]
> I'm concerned that chalk / supports-color will behave inconsistently in the test processes.

I got thrown off by `chalk`'s odd constructor access pattern. The trick is for AVA to use its own `chalk` instance and to configure it in the main process based on the `package.json` options and CLI flags, and in the worker processes based on what it was told by the main process.

I'm refactoring a lot of code at the moment and Chalk's instantiation came up, so I'm tackling *that* part now.

Once that lands we should support the color level option in the `package.json` *and* forward it to the worker processes.

**Comment by novemberborn** [comment]
See #1722.

**Comment by novemberborn** [comment]
With #1722, AVA now uses its own `chalk` instance. It's loaded quite early on [in `lib/worker/subprocess.js`](https://github.com/avajs/ava/blob/refactor-status-and-reporters/lib/worker/subprocess.js#L7). Right now it [processes the `--color` / `--no-color` argument](https://github.com/avajs/ava/blob/refactor-status-and-reporters/lib/worker/load-chalk.js) passed [by `lib/fork.js`](https://github.com/avajs/ava/blob/refactor-status-and-reporters/lib/fork.js#L47).

* Instead, `lib/fork.js` should stop passing those arguments. We [remove them anyway](https://github.com/avajs/ava/blob/refactor-status-and-reporters/lib/worker/consume-argv.js#L5).
* `lib/worker/subprocess.js` should require `lib/worker/consume-argv` *before* `lib/worker/load-chalk`.
* `load-chalk.js` should access the `color` option through requiring `lib/worker/options` and use it to [instantiate `chalk`](https://github.com/avajs/ava/blob/refactor-status-and-reporters/lib/chalk.js#L15).
* `consume-argv.js` should only remove `process.argv[2]`, not also `process.argv[3]`.

Additionally (though this could be done as a follow-up), we should expand the `--color` CLI flag and `package.json#ava.color` to support the `256` and `16m` string values from [`support-color`](https://www.npmjs.com/package/supports-color).

(I still can't get CI to pass for #1722 so the links above are for the branch. Will update once the PR lands.)

**Comment by novemberborn** [comment]
This is ready to be worked on again, if anybody wants to pick it up 😀

**Comment by novemberborn** [comment]
This has been addressed.



> Additionally (though this could be done as a follow-up), we should expand the `--color` CLI flag and `package.json#ava.color` to support the `256` and `16m` string values from [`support-color`](https://www.npmjs.com/package/supports-color).

I'm not sure if this is important, so I'm not going to open this issue.
