### ISSUE TITLE
Requiring @std/esm unexpectedly disables Babel pipeline

### ISSUE THREAD

**Issue by billyjanitsch** [avajs/ava#1705]
## Description

Adding `"require": "@std/esm"` to an AVA config causes AVA to disable its Babel pipeline. 

This is a pretty limiting restriction because aside from the fact that it can be used to transpile ESM imports/exports, Babel is orthogonal to std/esm. For example, if using std/esm, one can't use JSX in test files.

It's also quite surprising, since std/esm is the _only_ thing you can add to `require` that will cause this behavior. e.g. imagine running node 6 and adding `"require": "@std/esm"` to find that it breaks async functions in your test files (???)

How difficult do you think this would be to fix? If it's not likely to be addressed for awhile, I am happy to PR a caveat in the docs.

cc @jdalton

## Relevant Links

[Here's](https://github.com/billyjanitsch/ava-esm) a small repo -- run `npm it` to reproduce.

**Comment by jdalton** [comment]
Related to https://github.com/standard-things/esm/issues/277.

**Comment by novemberborn** [comment]
It seems to be working with `ava@next` and Babel 7: https://github.com/billyjanitsch/ava-esm/pull/1.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by jdalton** [comment]
Oh neat!

**Comment by jdalton** [comment]
@novemberborn Can this be added to the `@std/esm` cookbook example. I can see folks reaching for something like this again.

**Comment by billyjanitsch** [comment]
Very cool @novemberborn, I didn't think to try the beta release. I haven't been following its development too closely, but if I understand your PR correctly, `{"babel": "inherit"}` is becoming the default behavior?

**Comment by novemberborn** [comment]
> if I understand your PR correctly, {"babel": "inherit"} is becoming the default behavior?

@billyjanitsch yep.

> Can this be added to the @std/esm cookbook example. I can see folks reaching for something like this again.

@jdalton good idea, will do.

**Comment by novemberborn** [comment]
> Can this be added to the @std/esm cookbook example. I can see folks reaching for something like this again.

@jdalton where is this cookbook?

**Comment by jdalton** [comment]
See https://github.com/avajs/ava/blob/master/docs/recipes/es-modules.md.

**Comment by novemberborn** [comment]
@jdalton I think that's up to date? It links to the Babel recipe for disabling AVA's default ESM compilation too. Let me know if you think it needs more changes.

**Comment by jdalton** [comment]
Maybe the change should be on the disable babel bit. Your way of doing it looks simpler than what is currently documented. Though maybe theirs is more correct in some way?

**Comment by novemberborn** [comment]
@jdalton are you referring to https://github.com/billyjanitsch/ava-esm/pull/1? That just fixes the Babel setup for Babel 7. With that setup AVA is still compiling ESM to CJS, though that doesn't impact `@std/esm`.

**Comment by billyjanitsch** [comment]
@novemberborn why does AVA still transpile ESM to CJS in that PR? The Babel config has the env preset configured with `{"modules": false}`.

Or does the new AVA version merge its Babel config with mine, rather than delegating entirely to mine?

**Comment by novemberborn** [comment]
@billyjanitsch it merges, yes.

**Comment by billyjanitsch** [comment]
@novemberborn Hmm. That makes sense, but it's surprising to me that an ESM->CJS transform is among the transforms automatically applied by AVA if the user has _explicitly_ set something like `["@babel/preset-env", {"modules": false}]` in their config (as in the case in your PR to my repo).

Also, isn't the point of adding `{"require": "@std/esm"}` to an AVA config to use std/esm for _test_ files? To use std/esm for the pkg itself, I would have an `index.js` like the following (which my test files would presumably import from):

```js
module.exports = require("@std/esm")(module)('./lib')
```

**Comment by novemberborn** [comment]
> it's surprising to me that an ESM->CJS transform is among the transforms automatically applied by AVA if the user has explicitly set something like ["@babel/preset-env", {"modules": false}] in their config

That sounds nice, but I really wouldn't know how to do that reliably. I think it's better to communicate what AVA does and how to disable certain things if necessary. Let me know if you have suggestions for our Babel recipe in that regard.

> Also, isn't the point of adding {"require": "@std/esm"} to an AVA config to use std/esm for test files?

I've assumed it's so you can use ESM in your source files and require them directly from your tests, without having to precompile them. I'm not sure about the difference in semantics between AVA's ESM->CJS transform and `@std/esm`, but nuances aside you shoudn't need `@std/esm` to load your test files.
