### ISSUE TITLE
Support `code` expectation in t.throws()

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1708]
#1704 introduces an expectation object for `t.throws()`. It'd be neat if we could add an expectation for the [`code` property in Node.js](https://nodejs.org/api/errors.html#errors_error_code_1).

~~We could consider supporting [`errno`](https://nodejs.org/api/errors.html#errors_error_errno) as well. I suspect `code` may be the more future proof property though, in which case I wonder if `errno` support is really needed.~~

**Comment by sindresorhus** [comment]
👍 to `code`, 👎to `errno`.
