### ISSUE TITLE
Snapshots Can Have Weird Characters In Them

### ISSUE THREAD

**Issue by rzec-r7** [avajs/ava#1715]
## Description

Snapshot seems to sometimes have weird characters at the end of lines in the generated `.md` file. There have been some cases where with a component, it would render a unicode star.

The one use-case the is simple to reproduce and always happens is using a snap show to compare a simple sting. I want to use a snapshot because the string is dynamically generated and can be quite large and write those test is any other way would just take too much time and would be very brittle. The issue with snapshotting string if that the line return character are being literally printed out:

```
## test

> Snapshot 1

    `just want␊
    to test␍␊
    something`
```

### Test Source

```jsx
test('test, (t) => {
  t.snapshot('just want\nto test\r\nsomething');
});
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
OS: Mac OS X 10.13.3
node: 8.9.4
ava: 0.25.0
npm: 5.6.0
```

**Comment by novemberborn** [comment]
This is intentional. We want to show these otherwise invisible characters. In fact we'd like to [show more](https://github.com/concordancejs/concordance/issues/4).

Do you find this behavior surprising? Did you think it impacts the test outcome?

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by rzec-r7** [comment]
I found it a bit surprising (at least for the weird star that I have no idea why it is there, the line feed one at least makes sense on why it would be there).

As for effecting the test, no, it does not really impact it all that much (it is seems weird as I usually don't see those characters), just wanted to point this out as I was not sure if it was expected or not. Since it is intentional, I am good with it.

**Comment by novemberborn** [comment]
By "weird star" do you mean `⍟`? I agree it's a bit obscure — I think it's only used with React elements. The intent is to show the difference between built-in types (they end up being strings) and function types that could have the same name.
