### ISSUE TITLE
Can't resolve promise when loading an image using browser-env

### ISSUE THREAD

**Issue by TotomInc** [avajs/ava#1717]
## Description

I'm trying to test a promise function which load an image. Image is resolved or rejected when `addEventListener` `load` or `error` is fullfilled. It's using `browser-env` to simulate a browser environment, and configured as it is recommended by ava in [the browser testing section](https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md).

### Test Source

```js
// test/test.js
import test from 'ava';

function imagePromise() {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.addEventListener('load', () => resolve(true));
    img.addEventListener('error', () => reject(false));
    img.src = 'http://78.media.tumblr.com/tumblr_lr9mx5Axur1qlyuwso1_1280.jpg';
  });
}

test('load image with promise', (t) => {
  return imagePromise().then((result) => {
    t.is(result, true);
  });
});
```

```js
// test/helpers/setup-browser-env.js
const browserEnv = require('browser-env');
browserEnv();
```
### Error Message & Stack Trace

There are no stack trace, only an error message at the end of the tests:

```
Promise returned by test never resolved
```

### Config

```json
  "ava": {
    "require": [
      "./test/helpers/setup-browser-env.js"
    ]
  }
```

### Command-Line Arguments

`ava` or `ava --watch`.

## Relevant Links

- I have created a small repo containing a basic test of what I want to do, [it's here](https://github.com/TotomInc/ava-test-image-promise). Just clone, `yarn` or `npm i` then `ava`.

## Environment

- Node.js v8.9.4
- darwin 17.4.0
- ava 0.25.0
- npm 5.6.0

**Comment by sindresorhus** [comment]
Most likely related to `jsdom` (used by `browser-env`). See: https://github.com/jsdom/jsdom/blob/master/lib/old-api.md#external-resources You might have to allow remote image explicitly.

Also, next time please include links to any other places you have asked the question, or preferably only ask it in one place. https://stackoverflow.com/questions/48840541/ava-testing-image-loading-with-promise-promise-returned-by-test-never-resolved

**Comment by TotomInc** [comment]
Thanks @sindresorhus, I finally fixed my tests, if someone is seeing this, [here a repo where I fixed it](https://github.com/TotomInc/ava-test-image-promise):

```
// install browser-env and canvas-prebuilt
// (https://github.com/jsdom/jsdom#loading-subresources)
yarn add browser-env canvas-prebuilt -D
```

```js
/**
 * test/helpers/setup-browser-env.js
 *
 * using the new API of browser-env, you need to specify the `resources: 'usable'`
 * config to allow browser-env + jsdom to load subresources like images, scripts,
 * stylesheets, ... (https://github.com/jsdom/jsdom#loading-subresources)
 * the 3-lines below make the `window`, `document` and `Image` objects global
 */
require('browser-env')(['window', 'document', 'Image'], {
  resources: 'usable',
});
```

```js
/**
 * test/test.js
 *
 * load an image and return a resolved or rejected promise.
 */
import test from 'ava';

function imagePromise() {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.addEventListener('load', () => resolve(true));
    img.addEventListener('error', () => reject(false));
    // an heavy 4k wallpaper to check if promise is resolved after a long time
    img.src = 'https://www.wallpaperup.com/wallpaper/download/991808/8000/5224';
  });
}

test('load image with promise', (t) => {
  return imagePromise().then((result) => {
    t.is(result, true);
  });
});
```
