### ISSUE TITLE
is there a way to combine ava tap streams and show errors with stacktraces?

### ISSUE THREAD

**Issue by stringbeans** [avajs/ava#1725]
what i want to do is run two tests one after another and then have report of both tests at the end of the run WITH stacktraces.

what i'm doing is:

`ava --concurrency=4 dist/**/*.unit.js && ava --serial dist/**/*.integration.js`
(our integration tests need to be run serially because they involve the database)

but unfortunately it wont concatenate and report the failing tests at the end of the screen.

i could use a tap reporter but tap reporters dont seem to ever display stack traces :(

is there any way in ava to do this?

**Comment by novemberborn** [comment]
I don't think we'll support a way to run test files concurrently and *then* serially, within a single `ava` invocation, which would be one way of solving this problem.

So really this is a question for the TAP tools out there. I'm sure our TAP output could be improved and we'll accept PRs as necessary.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by stringbeans** [comment]
@novemberborn thanks for your response! im a little new to how tap outputs and tap reporting works, but i'll keep digging. i took a peek at how tap is handled by ava and from what i can guess at, it looks like ava DOES at least include the strack trace...
