### ISSUE TITLE
Recipe detailing context in per-file and per-test hooks

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1730]
Via https://github.com/avajs/ava/pull/1711#issuecomment-365646530 — it'd be great to document how `t.context` works in `.before()` / `.after()` and `.beforeEach()` / `.afterEach()` hooks. Examples should illustrate when context is copied and how to share references and values.

**Comment by Seiyial** [comment]
Hi, I've recently used `.before()` / `.after()` and `.beforeEach()` / `.afterEach()` hooks in my project and would love to help with this. I'm rather new to open source contributing so any feedback/advice would be appreciated. Thanks!

**Comment by novemberborn** [comment]
@Seiyial that's great! Have a look at some of [our other recipes](https://github.com/avajs/ava/tree/master/docs/recipes) to see what we're looking for. Some of the more recently updates ones are:

* https://github.com/avajs/ava/blob/master/docs/recipes/babel.md
* https://github.com/avajs/ava/blob/master/docs/recipes/flow.md
* https://github.com/avajs/ava/blob/master/docs/recipes/test-setup.md
* https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md

Fork the repository, create a new Markdown file in the `docs/recipes` and go from your experiences. Then do a PR and we can help with any improvements.

**Comment by Seiyial** [comment]
@novemberborn Sorry for the delay. Please let me know how you think about it, thanks!

**Comment by mh81** [comment]
I have some free time this weekend, I'd be happy to build on @Seiyial's work in his PR and update it with @novemberborn's PR feedback.  Any objection?

**Comment by novemberborn** [comment]
Go for it @mh81. If you could retain @Seiyial's commits that'd be great.
