### ISSUE TITLE
AVA should apply its Babel presets/plugins after user presets/plugins

### ISSUE THREAD

**Issue by billyjanitsch** [avajs/ava#1732]
## Description

When AVA@next (by default) merges its own Babel config with that of the user's, it seems to put its own config in front of the user's.

This is problematic in the context of ESM/CJS. AVA automatically injects a ESM->CJS transform plugin, seemingly in front of any user plugins. If the user includes a plugin which, for example, _adds_ an ESM import to a file, that import won't be transpiled to CJS.

It's especially odd if the user's config _already_ includes the ESM->CJS transform (in the correct order wrt other plugins). AVA seems to still reorder that transform, so a build that works when run through Babel will break when run through AVA.

### Test Source

[Here](https://github.com/billyjanitsch/ava-plugin-order)'s a repo demonstrating the latter case. After an `npm install`:
- `npm run build` will correctly transpile `test.js`, outputting `lib/test.js` for inspection
- `npm test` will incorrectly transpile `test.js` and output a syntax error:

```
  import React from "react";
  ^^^^^^
  
  SyntaxError: Unexpected token import
```

## Environment

macOS 10.13.3
node 8.9.4
npm 5.7.1

**Comment by novemberborn** [comment]
> When AVA@next (by default) merges its own Babel config with that of the user's, it seems to put its own config in front of the user's.

Interesting. We could apply our `stage-4` preset *last*.

> It's especially odd if the user's config already includes the ESM->CJS transform (in the correct order wrt other plugins). AVA seems to still reorder that transform, so a build that works when run through Babel will break when run through AVA.

I think Babel might be choosing not to run the transform twice, so AVA's ends up running too early. This might be where "pass per preset" comes in but I've never quite understood that. Perhaps the [new documentation](https://new.babeljs.io/docs/en/next/index.html) is clearer on that front.

We construct our Babel config [starting here](https://github.com/avajs/ava/blob/d3bade8cd7fac004c1c6d2eff9b3f498257baa60/lib/babel-config.js#L110). Between `createConfig` and `extend` calls hopefully it's easy enough to follow. I'd appreciate somebody trying either "pass per preset" or reordering when we apply our `stage-4` preset.

**Comment by ivan-kleshnin** [comment]
Maybe relevant. I'm getting this error:

```
Plugin or preset file '/Users/username/Sandboxes/projectname/node_modules/babel-preset-es2015/lib/index.js' 
did not export a function
```

at `$ ava tests` with `ava@1.0` while the same environment works just fine with `ava@0.25`.

#### package.json

```
"ava": {
    "require": [
      "@std/esm"
    ]
  },
```

```
  "@std/esm": "^0.16.0",
  "babel-core": "^6.26.0",
  "babel-preset-es2015": "^6.24.1",
```

**Comment by novemberborn** [comment]
@ivan-kleshnin you're using a Babel 6 preset. AVA 1.0 uses Babel 7. You should either stop AVA from extending your project's Babel options, upgrade your project to Babel 7, or stick to AVA 0.25 for now.

**Comment by novemberborn** [comment]
Hopefully https://github.com/avajs/ava/pull/1798 covers this.
