### ISSUE TITLE
`t.context` is not available in before tests

### ISSUE THREAD

**Issue by bennyn** [avajs/ava#1736]
## Environment

```
Node.js v8.9.4
win32 10.0.16299
ava 0.22.0
npm 5.6.0
```

I tried the [Text context](https://github.com/avajs/ava#test-context) sample from the README but it does not seem to work. I get the following error: 

> `t.context` is not available in before tests

Here is my failing code:

```js
import test from 'ava'

test.before(t => {
  t.context = 'unicorn';
});

test('context is unicorn', t => {
  t.is(t.context, 'unicorn');
});
```

**Comment by novemberborn** [comment]
This is available since `1.0.0-beta.2`. You're using `0.22`. You can install the latest 1.0 beta using `npm i -D ava@next`.

**Comment by sshetty** [comment]
I get "t.context is not available in before tests" even after updating AVA. I tried versions 1.0.0-beta.2 and 1.0.0-beta.3

**Comment by novemberborn** [comment]
@sshetty if you could share your code or reproduce this that'd be great. Perhaps make a post in our [Spectrum community](https://spectrum.chat/ava)?

**Comment by reymalahay** [comment]
if anyone still has problems with this, i solved the issue using `require` as opposed to `import`.

i.e. this works:
```
const test = require('ava');
```

this gives problems:
```
import test from 'test';
```

hth.
