### ISSUE TITLE
Remove ava-init and recommend use of npx

### ISSUE THREAD

**Issue by billyjanitsch** [avajs/ava#1737]
## Description

Now that `npx` presents a great solution for running one-off chore commands, I want to propose going a step farther from d3bade8cd7fac004c1c6d2eff9b3f498257baa60 and removing the `--init` command (& associated dependency) entirely, and recommend running `npx ava-init` for new projects.

This will make AVA installs a little smaller, and I think it's a better separation of concerns, because `--init` isn't useful past the initial setup. For bonus points, the command is two characters shorter than `npx ava --init` :)

You could even have `ava-init` install `ava` if it isn't already present.

Happy to PR this if you like the idea.

**Comment by novemberborn** [comment]
Great idea! Ergonomically, how would you feel about using `@ava/init`? We're trying to scope our supporting packages.

@sindresorhus thoughts?

**Comment by billyjanitsch** [comment]
Glad you like it, and `npx @ava/init` sounds great to me.

**Comment by sholladay** [comment]
I like that `npx @ava/init` is clearly its own thing, whereas `npx ava-init` could be confused for `npx ava init` or `npx ava --init` if you read it quickly, as people often do with the install instructions.
