### ISSUE TITLE
t.thows with rejected promise intermittently fails

### ISSUE THREAD

**Issue by jaydenseric** [avajs/ava#1739]
## Description

Using `t.throws` for a promise that rejects intermittently fails with the message `Rejected promise returned by test`.

It is very mysterious behavior: Sometimes it works, sometimes not. In Travis CI the tests always seem to fail, but locally the tests pass most of the time. They seem to pass more often when tests are run in `--serial` mode.

These tests only started failing this week, so I'm not sure if it is due to a recent alpha v1 version?

### Test Source

https://github.com/jaydenseric/apollo-upload-server/blob/76f60c7544e447f35122b4f58c305f7994069f53/test.js#L104

### Error Message & Stack Trace

https://travis-ci.org/jaydenseric/apollo-upload-server/jobs/350670499

```
> ava
  - Exceed max file size.
  ✔ Single file.
  ✔ Deduped files.
  ✔ Missing file.
  ✖ Extraneous file. Rejected promise returned by test
  ✖ Exceed max files. Rejected promise returned by test
  ✔ Exceed max files with extraneous files intersperced.
  ✔ Misorder “map” before “operations”.
  ✔ Misorder files before “map”.
  2 tests failed
  1 test skipped
  Extraneous file.
  /home/travis/build/jaydenseric/apollo-upload-server/node_modules/node-fetch/lib/index.js:1369
  Rejected promise returned by test. Reason:
  FetchError {
    code: 'EPIPE',
    errno: 'EPIPE',
    message: 'request to http://localhost:44731/ failed, reason: write EPIPE',
    type: 'system',
  }
  Exceed max files.
  /home/travis/build/jaydenseric/apollo-upload-server/node_modules/node-fetch/lib/index.js:1369
  Rejected promise returned by test. Reason:
  FetchError {
    code: 'EPIPE',
    errno: 'EPIPE',
    message: 'request to http://localhost:37227/ failed, reason: write EPIPE',
    type: 'system',
  }
npm ERR! Test failed.  See above for more details.
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "cache": false,
    "serial": true,
    "verbose": true
  }
}
```

### Command-Line Arguments

```
ava
```

## Relevant Links

- https://github.com/jaydenseric/apollo-upload-server/blob/76f60c7544e447f35122b4f58c305f7994069f53/test.js#L104
- https://travis-ci.org/jaydenseric/apollo-upload-server/jobs/350670499

## Environment

- AVA v1.0.0-beta.3
- Node.js v9.7.1
- NPM v5.7.1
- macOS v10.13.3

**Comment by novemberborn** [comment]
> ✖ Extraneous file. Rejected promise returned by test
>   ✖ Exceed max files. Rejected promise returned by test

These test themselves are returning a rejected promise. Neither of them seem to be using a `t.throws()` assertion.

Going by the printed error I think the error [originates from the `fetch()` call](https://github.com/jaydenseric/apollo-upload-server/blob/76f60c7544e447f35122b4f58c305f7994069f53/test.js#L158).

```
  Extraneous file.
  /home/travis/build/jaydenseric/apollo-upload-server/node_modules/node-fetch/lib/index.js:1369
  Rejected promise returned by test. Reason:
  FetchError {
    code: 'EPIPE',
    errno: 'EPIPE',
    message: 'request to http://localhost:44731/ failed, reason: write EPIPE',
    type: 'system',
  }
```

The `EPIPE` error might mean it can't connect to your server, but I'm not familiar enough with the libraries you're using to help there.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
