### ISSUE TITLE
Document how to exclude a directory of tests

### ISSUE THREAD

**Issue by vjpr** [avajs/ava#1750]
I searched everywhere, issues and docs for "exclude" or "ignore" and I could not find it.

I have a bunch of tests I want to exclude, how is it possible?

**Comment by sindresorhus** [comment]
Patterns prefixed with `!` are ignore patterns in the `files` config. We should better document this though.

https://github.com/avajs/ava#configuration

**Comment by Briantmorr** [comment]
I'm just getting into the open source community, and I'd love to work on this!

**Comment by novemberborn** [comment]
Go for it @Briantmorr. Let me know if you have any questions!

**Comment by Briantmorr** [comment]
Thanks @novemberborn ! I submitted the pull request late Tuesday Night, but I just realized I should also post here for visibility. Please let me know if my changes were what you had in mind!

**Comment by clemtrek** [comment]
@vjpr, you can exclude certain tests in a file by adding .skip to the test. For example,

```js
test.skip('I will not run', t => {
  t.fail()
})
```
