### ISSUE TITLE
open source projects

### ISSUE THREAD

**Issue by Wylie-S** [avajs/ava#1753]
I'm just getting into the open source community, and I'd love to work on this!

**Comment by novemberborn** [comment]
Welcome @Wylie-S! Have a look at our [Medium article](https://medium.com/@vadimdemedes/making-your-first-contribution-de6576ddb190#.umxr7id07) and ["good for beginner"](https://github.com/avajs/ava/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+for+beginner%22) issues. Some of us are in our [Spectrum community](https://spectrum.chat/ava) as well.
