### ISSUE TITLE
When linking to documentation, link to specific Git tag

### ISSUE THREAD

**Issue by revelt** [avajs/ava#1757]
hi all,

One of error messages is saying:

> Unexpected Babel configuration for AVA. See https://github.com/avajs/ava#es2017-support for allowed values.

<img width="950" alt="screen shot 2018-03-31 at 12 20 03" src="https://user-images.githubusercontent.com/8344688/38162697-fcec4dcc-34dd-11e8-8d03-686e18d0842f.png">

However, the link is not valid any more. Let's fix it!

**Comment by novemberborn** [comment]
I suspect you're using AVA 0.25 or older? The documentation has changed, and yea that's not great in this circumstance. With the `1.0` releases we [link to the Babel recipe instead](https://github.com/avajs/ava/blob/977cf4f4a6e11c44d8f9e472c4626a20cf39e050/lib/babel-config.js#L26).

What if we build these links based on the `package.json#version` value? That should correspond to the Git tags (once prefixed with `v`) so at least the links won't go out of date.

**Comment by revelt** [comment]
Yeah, I'm on `0.25`

**Comment by okmanl** [comment]
Hello, I'm new to open source contribution. Would it be possible for me to work on this issue? Thank you.

**Comment by novemberborn** [comment]
Yea that'd be great, @okmanl!

**Comment by TheDancingCode** [comment]
@okmanl 
Just checking in: are you still working on this? Otherwise I'd like to have a go.

**Comment by novemberborn** [comment]
Go for it @TheDancingCode.
