### ISSUE TITLE
@babel/register is the wrong module when loading sources compiled with Babel 6

### ISSUE THREAD

**Issue by lili21** [avajs/ava#1767]
## Description

**babel options** under **ava congifure** isn't working.

### Test Source

```js
import test from 'ava';

import { add } from './index'

test('add', t => {
  t.is(add(1, 2), 3)
})

```

### Error Message & Stack Trace

![image](https://user-images.githubusercontent.com/4456380/38669109-1bfa9f5e-3e78-11e8-8274-e9f181686fe3.png)

### Config

```json
{
  "ava": {
    "require": [
      "@babel/register"
    ],
    "babel": {
      "testOptions": {
        "babelrc": false,
        "presets": [
          "@babel/env"
        ]
      }
    }
  }
}
```

### Command-Line Arguments

```
ava
```

## Relevant Links

[ava-demo](https://github.com/lili21/ava-demo)

## Environment

Node.js v9.8.0
darwin 17.2.0
ava 1.0.0-beta.3
npm 5.6.0

**Comment by lili21** [comment]
I guess the problem is `@babel/register`.   `@babel/register` will read the config from `.babelrc` unless You specify options like below

```js
require('@babel/register')({
// your options
})
```

**Comment by lili21** [comment]
confirmed.

update **ava** config

```json
"ava": {
    "require": [
      "./setup.js"
    ],
    "babel": {
      "testOptions": {
        "babelrc": false,
        "presets": [
          "@babel/env"
        ]
      }
    }
  }
```

**setup.js**

```js
require('@babel/register')({
  babelrc: false,
  presets: ['@babel/env']
})
```

it works.

**Comment by lili21** [comment]
just read the `docs` again. looks like this is the expected behavior? .

**Comment by novemberborn** [comment]
> I guess the problem is @babel/register. @babel/register will read the config from .babelrc unless You specify option

Oh that makes sense!

> kind of weird to me, that test file and source file using different way to handle babel config.

I think in your case you should require `babel-register`. You shouldn't need that or `@babel/register` to run your tests, unless you want to use it to compile sources on-the-fly. And then you need to use the `register` that is compatible with how you compile your source files.

We should update https://github.com/avajs/ava/blob/master/docs/recipes/babel.md#compile-sources so it recommends the correct `register` module based on how source files are compiled.

**Comment by nothingismagick** [comment]
Have you tried to use the babel bridge repo?
https://github.com/babel/babel-bridge
`yarn add babel-core@^7.0.0-0`

**Comment by xxxxxMiss** [comment]
I also experienced it. I try many times but it don't working. So i can confirm the config of 
```
```
  don't working.

**Comment by xxxxxMiss** [comment]
I also experienced it. I tried many times and i can confirm the config
```
"babel": {
      "testOptions": {
        "babelrc": false
      }
    }
``` don't  working.

Than i use .babelrc and installed `babel-core@^7.0.0-0` and run test, it throws an error:
```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

**Comment by novemberborn** [comment]
@xxxxxMiss given that you're commenting here, are you using `babel-register`? That's Babel 6, so it won't work with Babel 7 configs or plugins. You need to either use `@babel/register` and Babel 7 configs, or `babel-register` with Babel 6 configs.

**Comment by xxxxxMiss** [comment]
@novemberborn Sorry that i view issues to it and commented BTW. About my [that issue](https://github.com/avajs/ava/issues/1813), i give a [demo link here](https://github.com/xxxxxMiss/ava-test)

**Comment by novemberborn** [comment]
@xxxxxMiss I get the following:

```console
❯ npm t

> ava-test@1.0.0 test /private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.ki5NUCbmLQ/ava-test
> ava


  1 failed

  test dynamic import

  /private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.ki5NUCbmLQ/ava-test/test/test.js:11

   10: test('test dynamic import', t => {
   11:   return import('lodash').then(m => {
   12:     const _ = m.default || m

  Rejected promise returned by test. Reason:

  Error {
    message: 'Not supported',
  }
```

I think the problem you're seeing now is that `import()` is not supported by `@babel/preset-env`.

Could you post any follow-up to this on Spectrum instead? https://spectrum.chat/ava

**Comment by xxxxxMiss** [comment]
@novemberborn OK, no problem.

**Comment by ashimagarwal** [comment]
Hi Ava Team,

I would love to update the correct register module based on how source files are compiled.
Can you please guide me on the process. (New to the OSS community).

**Comment by novemberborn** [comment]
@ashimagarwal that sounds great! Perhaps this article will be useful: https://medium.com/@vadimdemedes/making-your-first-contribution-de6576ddb190

**Comment by novemberborn** [comment]
Now that Babel 7 is out, I think we can assume people are upgrading. We probably shouldn't be making our documentation more complicated by covering Babel 6.
