### ISSUE TITLE
ava ignore tests in nested folders

### ISSUE THREAD

**Issue by guillaumevincent** [avajs/ava#1772]
## Description

Hello ava, maybe I'm not using ava correctly.
I want to run all my tests in src directory.
So I configured in my package.json with blob pattern  `"test": "ava src/**/*.test.js"`

I expected ava to run all tests even in sub directories. Look's like ava ignore some tests.

### Test Source

I created a repo to reproduce the bug: https://github.com/guillaumevincent/ava-kua

### Command-Line Arguments

```
ava src/**/*.test.js
```

`npm test` return `1 passed`. I expected `3 passed`

## Environment
```
Node.js v8.11.1
linux 4.15.15-300.fc27.x86_64
$ ava --version
0.25.0
$ npm --version
5.6.0
```

Any idea, it's me? or a real issue?
Thank you

**Comment by novemberborn** [comment]
How odd! Thanks for your repo, I can reproduce this on my end. Doing `require('glob').sync('src/**/*.test.js')` works so I wonder if the other files are somehow filtered out.

It'll be a few days before I can dig deeper though.

**Comment by guillaumevincent** [comment]
@F1LT3R is right
`ava 'src/**/*.test.js'` or `"ava \"src/**/*.test.js\""` works

It's a shell extension transforming the command

`test.js`

```
#!/usr/bin/env node
var args = process.argv

console.log(args)
```


```
$ node ./test.js src/**/*.test.js
[ '/usr/bin/node',
  '.../test.js',
  'src/1/1.test.js' ]

```

not an ava issue, closing

Thanks @F1LT3R and @novemberborn
