### ISSUE TITLE
drop Node.js v4 support

### ISSUE THREAD

**Issue by boneskull** [avajs/ava#1773]
Per #1599 this looks like something you want to be doing.

In a little under two weeks (April 30, 2018), Node.js v4 will be [End-of-Life'd](https://github.com/nodejs/Release).  

I wanted to encourage the Ava team to drop support for this version as soon as is feasible.  Mocha will also be dropping support ASAP.

Thanks!

**Comment by harrysarson** [comment]
@boneskull they are one step ahead of you it seems: #1760

**Comment by boneskull** [comment]
great—was just going off of latest published version.

**Comment by novemberborn** [comment]
Hey @boneskull, thanks for dropping by!

We're currently shipping beta releases that use Babel 7, which is itself in beta. So unfortunately the `latest` package on npm is looking a little outdated. But yea, farewell Node.js 4 🎈
