### ISSUE TITLE
integration tests are slow due to initializing of sequelize per process

### ISSUE THREAD

**Issue by stringbeans** [avajs/ava#1775]
## Description

Our integration tests initialize and seed a database at the beginning of the test. We are currently using Sequelize as our ORM. Because of the nature of AVA, each test is in a separate process and thus, sequelize must be initialized each time. The initialization of sequelize is essentially what is slowing down our integration test suite because it takes roughly 5 seconds (im assuming this is to create the connection to the database, init a connection pool, etc etc).

Is there a way to share a single instance of sequelize across all of our tests? My gut tells me no, but perhaps someone else has run into this in their situation? Would love any input :)

**Comment by jamestalmage** [comment]
I would start by using an in-memory SQLite instance as your backing database, or using something like [sequelize-mock](https://sequelize-mock.readthedocs.io).

Sharing a single instance of Sequelize across tests, by definition, will create global state that is shared across tests. This is a an anti-pattern that AVA purposely discourages.

**Comment by stringbeans** [comment]
@jamestalmage thanks for the tips. using a SQLite instance wont work for us as there are some slight differences in syntax and behaviour between mariadb/mysql (our db) and sqllite. 

because of including the db in our integration tests we actually make sure we only run our integration tests serially to avoid the shared global state

**Comment by novemberborn** [comment]
Yea there's no way around this. You could perhaps reduce the connection pool size so that's a little quicker?

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
