### ISSUE TITLE
MaxListenersExceededWarning with beforeEach and afterAeach

### ISSUE THREAD

**Issue by cortopy** [avajs/ava#1779]
## Description

I have a file with 8 tests and two hooks for each (`beforeEach` and `afterEach`). I'm running into MaxListenersExceededWarning and I'm unable to change setMaxListeners.

I'm only able to run 3 tests, before I get MaxListenersExceededWarning.

Reading https://github.com/avajs/ava/issues/1577 I understand that the node.js default max of  10 is followed by ava. However, in my case it seems that the two hooks count for 1 listener each. As soon as I add a fourth test, I get MaxListenersExceededWarning.

Is there a way to access the EventEmitter of ava in order to set `setMaxListeners`?

### Test Source
All tests are very similar to this
```typescript
test("should do something", async t => {
  const context = t.context as InstanceContext;
  const res = await supertest(context.server)
    .post("/endpoint")
    .send({})
    .expect(400);
  const body = res.body;
  t.is(body.error, "INVALID_PAYLOAD");
});
```

### Error Message & Stack Trace

```
(node:6374) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
```

### Config

none used

### Command-Line Arguments
In terminal:
```
NODE_PATH=build/src NODE_ENV=test node_modules/.bin/ava file.spec.js
```
And with gulp (setting setMaxListeners on `ava` doesn't make a difference:

```js
  const options = [SPEC_FILES.main, "--watch"];
  const ava = spawn("node_modules/.bin/ava", options, { stdio: [0, 1, 2] });
  ava.on("exit", function(code) {
    console.log(code);
  });
```

## Environment

Ava 1.0.0-beta.4 (same behaviour with 0.x branch)
Node.js v8.11.1
linux 4.14.34-1-MANJARO

**Comment by novemberborn** [comment]
I reckon your `beforeEach` is setting up these listeners? It's run for each test, so with four tests it's run 4 times.

I don't think this error is coming from AVA itself but I can't tell without a longer stack trace.

**Comment by cortopy** [comment]
Makes sense. I've changed to serial, and that did the trick for now at least. Thanks!
