### ISSUE TITLE
Running snapshot tests with -u on different platforms modifies paths

### ISSUE THREAD

**Issue by masaeedu** [avajs/ava#1786]
## Description
When a project has snapshots created on Linux, all the paths in the markdown files (and presumably somewhere in the `.snap` file) contain forward slashes. When you rerun the exact same tests on Windows with `-u`, e.g. to update a single changed snapshot, every `.md` and `.snap` file in the project gets modified so the paths contain backslashes instead. This makes it difficult to review commit diffs, because it looks at first glance like every snapshot file in the entire project has somehow been affected by the change.

Running tests with `-u` shouldn't touch the separators in the file paths at all, and in fact ideally the paths should be normalized (e.g. to always use forward slashes regardless of platform).

### Test Source
N/A. You can run the following on Windows to reproduce the issue:

```
git clone https://github.com/masaeedu/fp
cd fp
git checkout 33ef555
yarn
yarn test -u
git status
```

Every markdown and snap file is modified, whereas nothing should be modified.

### Error Message & Stack Trace
N/A

### Config
Not relevant to the issue, although you can take a look at the config in the repo linked above.

### Command-Line Arguments

```
ava -u
```

## Relevant Links

- https://github.com/masaeedu/fp

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v10.0.0
win32 10.0.15063

ava --version
0.25.0

npm --version
1.6.0
```

**Comment by novemberborn** [comment]
Yikes that's not right! IIRC the snapshot code assumes paths have been normalized, but perhaps that's not the case after all, or maybe something changed.

To be sure, could you try with [`ava@next`](https://github.com/avajs/ava/releases/tag/v1.0.0-beta.4)?

**Comment by masaeedu** [comment]
Yes, it happens with `ava@next` as well. See the repro snippet I linked above; tweaking the version to `"ava": "next"`, rerunning `yarn` and `yarn test -u` still results in all the files getting modified.

**Comment by novemberborn** [comment]
We definitely need to normalize slashes in this line: https://github.com/avajs/ava/blob/434cb7424db72c8475311184cf07a82bcb754343/lib/snapshot-manager.js#L132

Preferably to POSIX.

Looking at the code I don't know why `.snap` files would change. They contain hashes of the test titles, and value serializations. The titles don't include any path components. It may be that the values are file system sensitive but that'd be a problem with the tests. @masaeedu could you point me at a commit where the `.snap` file changes?

**Comment by masaeedu** [comment]
@novemberborn I'm not sure I understand the question, sorry. Are you looking for the first commit in the ava codebase that introduces the problem?

If you're looking for a commit in `masaeedu/fp` that reproduces the problem, just copy pasting the snippet I have in the issue should work. All `.md` and `.snap` files are modified, even though none should be.

**Comment by masaeedu** [comment]
If you think this is a problem with the tests themselves producing nondeterministic output, just run the same snippet on Linux. Neither the `.md` nor the `.snap` files will change.

**Comment by novemberborn** [comment]
I'm on macOS. I see changes to the `.snap` files but not the Markdown ones. Depending on how the snapshots evolved they may see some churn when updating.

If you could update snapshots on Linux, commit that, and then do the same on Windows, that should give us a good sample of the changes within the snapshot files. Right now I can't figure out why they would be affected.

To be clear, there's definitely a bug with the Markdown reports. I'm just not sure about the `.snap` files.

**Comment by masaeedu** [comment]
> If you could update snapshots on Linux, commit that

Nothing changes on Linux, so there's nothing to commit. I don't have access to a Windows system at the moment but I'll see if I can do that on a branch tomorrow.

**Comment by masaeedu** [comment]
@novemberborn I've added a branch winbug that shows the modifications I get to all the snapshot files if I run the tests with `-u`. See https://github.com/masaeedu/fp/commit/9ef08bd447ff342422454f7091e6a7e1ee4a84f7

**Comment by novemberborn** [comment]
Thanks @masaeedu. The issue apparent when you `hexdump` the snapshot files and get their diff:

```diff
  0000000 41 56 41 20 53 6e 61 70 73 68 6f 74 20 76 31 0a
< 0000010 01 00 10 39 72 6e 44 3c 60 7f f6 2d f5 4c 87 d9
< 0000020 14 ca 1f 8b 08 00 00 00 00 00 00 03 9b c6 c0 c0
---
  0000000 41 56 41 20 53 6e 61 70 73 68 6f 74 20 76 31 0a
> 0000010 01 00 7b ed eb 99 70 b6 66 ab ef 1c 21 e8 d3 cb
> 0000020 41 a8 1f 8b 08 00 00 00 00 00 00 0a 9b c6 c0 c0
```

Open <https://github.com/avajs/ava/blob/master/lib/snapshot-manager.js#L215:L220> for reference.

The first 16 bytes is the readable header, followed by two bytes indicating the snapshot version, and then a 16 byte checksum. The compressed output starts at byte 34 (the `1f 8b 08 00 00 00 00 00 00` part). Byte 43 is `03` on Linux but `0a` on Windows.

We should solve this by rewriting byte 43 to always be `03`. It's the 10th byte in the `compressed` array.

---

Together with https://github.com/avajs/ava/issues/1786#issuecomment-387119194 we should be able to get rid of these cross-platform inconsistencies. Thanks for sharing the reproduction!

Would you be keen on making these changes?

**Comment by masaeedu** [comment]
> The first 16 bytes is the readable header, followed by two bytes indicating the snapshot version, and then a 16 byte checksum

I'm guessing you mean 16 bit, two bytes, 16 bit. For some reason i was mentally correcting that to "two bits" and it wasn't making any sense.

**Comment by masaeedu** [comment]
@novemberborn Regarding https://github.com/avajs/ava/issues/1786#issuecomment-387119194, do you just want to do a string substitution of `\` to `/`? The character `\` is itself a valid character of a POSIX filename, so just replacing `\` -> `/` might break people who have such files (although it seems very unlikely anyone has such filenames). There may be more path edge cases I'm not thinking of.

**Comment by novemberborn** [comment]
Where-ever we build up the path, we should use `path.posix.join()`. That ensures the proper separators are used regardless of underlying platform.
