### ISSUE TITLE
Low vulnerability in dependencies

### ISSUE THREAD

**Issue by israeleriston** [avajs/ava#1792]
When installing java using npm 6.0.1, it displays dependency vulnerability, I'm not sure if the ava team has knowledge, but I'll still be alerting

npm version 6.0.1
node v9.0.0
OS: MacOs Sierra
![captura de tela 2018-05-10 as 22 11 56](https://user-images.githubusercontent.com/10285100/39904865-e7b110a0-549f-11e8-88b6-6dd062b3364f.png)

**Comment by sindresorhus** [comment]
As you can see, it's deep down in the dependency-tree and not something we control. I would recommend trying to handle this further down in the dependency-tree.

**Comment by israeleriston** [comment]
@sindresorhus I saw, I just opened the issue for everyone's

**Comment by novemberborn** [comment]
@israeleriston this is a new npm feature and as such I don't think they have fully worked out their communication strategy, and as a community we haven't yet considered how to engage on these issues.

AVA being a development dependency it's quite unlikely anything dependency vulnerability can actually lead to a compromise (except for code that is so nefarious that npm will just remove it from the registry).

Opening issues on all projects that have a transitive dependency on a vulnerable dependency version won't be very productive for anybody involved.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
