### ISSUE TITLE
Request for Documentation: AVA & Puppeteer

### ISSUE THREAD

**Issue by backspaces** [avajs/ava#1799]
This is not a bug but a request for documentation.

I'd like a reasonably detailed document discussing use of AVA and Puppeteer where the tests are snippets sant to and run in the browser with ava in node testing that the results are correct.

My example: I have an agent based model that I want to run for 500 steps in the browser.  I then want to write ava tests against the state of the simulation. I'd like to be able to write snippets that are sent to the browser, and the result values sent back to ava for testing.

So there is no need to execute ava in the browser, but only the ability to message back/forth between it and puppeteer, using ava's sane assertions.

**Comment by novemberborn** [comment]
Yes would be great to have a recipe for this! 👍
