### ISSUE TITLE
Check whether Babel returned a source map

### ISSUE THREAD

**Issue by isnifer** [avajs/ava#1804]
## Prerequisites

installed Source Map Support

## Description
With installed Source Map Support tests in async function won't show errors correctly
[Screenshot WITH installed source maps support](https://user-images.githubusercontent.com/1788245/40121313-f112e7a2-5929-11e8-9880-6fdcc8ac2efb.png)
[Screenshot WITHOUT installed source maps support](https://user-images.githubusercontent.com/1788245/40121371-16e5b022-592a-11e8-81dd-499ffd7836ef.png)

### Test Source

```js
t.falsy(1, 'List of nearby stores should not be empty')
```

### Error Message & Stack Trace

```
  ✔ 02_NearbyStoreList › Nearby Store List (1.5s)
Uncaught Exception: __tests__/scenarios/07_StoreTabView.test.js
  TypeError: Cannot read property 'sections' of null
  new SourceMapConsumer (node_modules/ava/node_modules/source-map/lib/source-map-consumer.js:20:20)
mapSourcePosition (node_modules/ava/node_modules/source-map-support/source-map-support.js:191:14)
wrapCallSite (node_modules/ava/node_modules/source-map-support/source-map-support.js:359:20)
node_modules/ava/node_modules/source-map-support/source-map-support.js:394:26
Function.prepareStackTrace (node_modules/ava/node_modules/source-map-support/source-map-support.js:393:24)


  ✖ Test results were not received from __tests__/scenarios/07_StoreTabView.test.js

  1 test passed [16:49:31]
  2 uncaught exceptions
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "files": [
    "__tests__/scenarios/*.test.js"
  ],
  "sources": [
    "web/index.js"
  ],
  "require": [
    "./__tests__/setup/tape.js"
  ],
  "failFast": true,
  "failWithoutAssertions": true,
  "compileEnhancements": false,
  "babel": "inherit"
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava --vebose --watch
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:
```
Node.js v9.4.0
darwin 17.5.0
ava --version 0.25.0
npm --version 6.0.1
```

**Comment by isnifer** [comment]
I will try to create reproducible demo

**Comment by isnifer** [comment]
Did some debug and found — this line https://github.com/avajs/ava/blob/1e0e8e84dbc8ed70286d01dd9c8d290f30533aad/lib/worker/precompiler-hook.js#L19 returns `null` as a `string`.
It brokes log.

If I change locally to:
```js
if (sourceMapCache.has(source)) {
  const map = fs.readFileSync(sourceMapCache.get(source), 'utf8')

  if (map !== 'null') {
    return {
      url: source,
      map: map
    };
  }
}
```
Then there is no problem

**Comment by novemberborn** [comment]
Wow that's surprising, nice find @isnifer!

Can you share this reproduction? And does it occur when you install `ava@next`?

**Comment by isnifer** [comment]
@novemberborn yes, I will. Just need some free time. 
Also, I will check it with `ava@next`. Thank you for your response.

**Comment by novemberborn** [comment]
Looking through the source code we're assuming that Babel returns us a source map, and that's probably a wrong assumption. See https://github.com/avajs/ava/blob/2167c575c925d104dc5ecab3d45143a328e9f33a/lib/caching-precompiler.js#L71. This leads to the `'null'` string.

We'll have to update the `worker/precompiler-hook` module accordingly. We don't need the `sourceMapCache` value at all, we can compute the source map location from the `options`. We just need to catch any errors if the file does not exist.

Do you happen to have source maps disabled in your Babel options?

**Comment by novemberborn** [comment]
Note that we may remove our `source-map-support` integration entirely: https://github.com/avajs/ava/issues/974#issuecomment-390478448

We should still fix this bug while #974 is pending.

**Comment by novemberborn** [comment]
Fixing this should wait until https://github.com/avajs/ava/pull/1798 lands.

**Comment by isnifer** [comment]
@novemberborn 
> Do you happen to have source maps disabled in your Babel options?
No
