### ISSUE TITLE
Source map issue

### ISSUE THREAD

**Issue by niftylettuce** [avajs/ava#1805]
I use babel to compile a file - and then in my tests I require it.

e.g. `const myLibrary = require('../lib');` and `lib/index.js` is compiled from `src/index.js`

my babel config:

```
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": "6.4.0"
      }
    }]
  ],
  "plugins": [ "@babel/transform-runtime", "@babel/plugin-proposal-object-rest-spread" ],
  "sourceMaps": "inline"
}
```

curious why the stack traces from ava are showing from `lib/index.js` versus `src/index.js`?

I looked at bottom of `lib/index.js` and I see the inline source map comments

**Comment by niftylettuce** [comment]
For example, I get this error:

```sh
TypeError: undefined is not a function
    at promise.then.args (/Users/test/Projects/test/frisbee/src/interceptor.js:4:81)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at runMain (/Users/test/.node-spawn-wrap-32523-715159df5212/node:68:10)
    at Function.<anonymous> (/Users/test/.node-spawn-wrap-32523-715159df5212/node:171:5)
    at Object.<anonymous> (/Users/test/Projects/test/frisbee/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
```

and on line 4 of interceptor.js it is a blank line..

```js
module.exports = class Interceptor {
  constructor(API, interceptableMethods = []) {
    this.interceptors = [];

    if (!API) {
      throw new Error('API should be passed to the Interceptor');
    }

    if (interceptableMethods.length === 0) {
      throw new Error('no methods were added to interceptableMethods');
    }

    // ...
```

**Comment by niftylettuce** [comment]
I've already tried this as well in my ava config:

```
  "ava": {
    "failFast": true,
    "verbose": true,
    "files": [
      "test/**/*.test.js"
    ],
    "babel": {
      "testOptions": {
        "babelrc": false // <---- attempted to use this 
      }
    }
  },
```

**Comment by xtx1130** [comment]
The same issue

**Comment by sindresorhus** [comment]
@niftylettuce What AVA version and Node.js version? Can you try the [latest AVA beta](https://github.com/avajs/ava/releases/tag/v1.0.0-beta.4)?

**Comment by niftylettuce** [comment]
Sorry this is 100% due to nyc.  I'm on latest ava and nyc beta.  It's just source mapping in the console output is not correct when using nyc with ava.

**Comment by sindresorhus** [comment]
@xtx1130 "me too" comments are not useful unless you provide additional information ;)

**Comment by sindresorhus** [comment]
Sounds similar to https://github.com/istanbuljs/nyc/issues/619

**Comment by niftylettuce** [comment]
this is a duplicate of #974 - the issue has existed for quite some time (but most likely because of istanbul/nyc source mapping)

**Comment by xtx1130** [comment]
@sindresorhus https://github.com/avajs/ava/issues/1800
