### ISSUE TITLE
How to use a custom `@babel/core` version

### ISSUE THREAD

**Issue by vjpr** [avajs/ava#1818]
Ava depends on `7.0.0-beta.44`, but my app is using the latest `7.0.0-beta.49`.

I get an error like the following which sometimes means that there is a conflict between two `@babel/core` versions.

```
You gave us a visitor for the node type PrivateName but it's not a valid type
```

Ava has a line in the `caching-precompiler.js` like so:

```
this.babel = require('@babel/core');
```

Is it possible to use my own `@babel/core` version?

---

Using `pnpmfile.js` with pnpm I can simply override the version to use the latest and everything works.

So ava should probably allow passing in your own core.

**Comment by novemberborn** [comment]
I'm hoping to have a release out this week that should get us to beta 48. Maybe a newer one if I have time to update our dependencies.

Once Babel 7 is out of beta we'll stop pinning an exact release and then deduping in the installation process should take care of this.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by dlebedynskyi** [comment]
Run into same issue. this is blocking ( not critical) us from updating to babel.49. Would appreciate the fix 🙏
