### ISSUE TITLE
Error: Cannot find module 'del'

### ISSUE THREAD

**Issue by 0xF6** [avajs/ava#1824]
## Description
 

Remove module `del` from devDependencies
and add `del` to dependencies

### Error Message & Stack Trace

![image](https://user-images.githubusercontent.com/13326808/40809795-5d8c89d6-6534-11e8-9e31-19c6c269c145.png)

## Environment

![image](https://user-images.githubusercontent.com/13326808/40810035-3b7a099e-6535-11e8-8c34-052ac3ff79cf.png)
![image](https://user-images.githubusercontent.com/13326808/40809881-a786ddb6-6534-11e8-9648-1b906353d952.png)

**Comment by novemberborn** [comment]
Fixed in [`1.0.0-beta.5.1`](https://github.com/avajs/ava/releases/tag/v1.0.0-beta.5.1). Thanks @tobli for the quick PR!
