### ISSUE TITLE
Ava runs twice when using with Parcel

### ISSUE THREAD

**Issue by minhchu** [avajs/ava#1832]
## Description

When I'm using Ava in `watch mode` with Parcel, it runs twice

### Test Source

https://github.com/minhchu/ava-parcel-bug

## Environment

Node.js v6.14.2
linux 4.13.0-43-generic
ava 0.25.0
npm 3.10.10

**Comment by novemberborn** [comment]
@minhchu is Parcel run with its own watch mode? If so, then I reckon AVA detects the file change, and then once Parcel has updated the bundle, AVA detects a change to *that* file too, causing it to rerun tests.

You can confirm this by running AVA's watch mode with the `DEBUG` environment variable set: https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#debugging

Then change `sources` to only target the `src/` directory: https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#source-files-and-test-files

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by minhchu** [comment]
@novemberborn thanks for your answer
After adding `sources` to `ava` config it now works as expected
