### ISSUE TITLE
Run a single test from specify folder directory

### ISSUE THREAD

**Issue by Adriang71** [avajs/ava#1842]
## Description

Hello, I want to have a possibility to run a single test from specify folder directory. I have set up to watch all source file in a config, and from CLI I add specify root to test folder. After this in watch mode when I make some change in folder passed thru CLI, a test doesn't run when. This is strange situation because when I make a change in other folders then passed thru cli, test start.

### Test Source
This is my config:
```js
export default {
  "files": [
    "../app/src/modules/auth/*.test.js"
  ],
  "sources": [
    "../app/src/**/*.js"
  ],
  "require": [
    "../test/src/ava.transform"
  ],
  "babel": {
    "testOptions": {
      "presets": [
        "@ava/stage-4",
        "@babel/preset-react",
        [
          "@babel/env",
          {
            "targets": {
              "node": "current"
            }
          }
        ]
      ],
      "retainLines": true
    }
  },
  "timeout": "20s",
  "failFast": true,
  "failWithoutAssertions": false
};

```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava --verbose --watch  ../app/src/modules/auth/*.test.js
```

**Comment by novemberborn** [comment]
I'm a little surprised by the `../` paths. AVA starts in the directory that has your `package.json` file. Paths are relative to this directory. `ava.config.js` is only used if it's in the same directory as the `package.json` file.

I'm pretty sure you can't run tests from directories *above* that one, or even if it seems to work it's not supported. Which is what may be going on here. Why do you have the `../` paths?

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by Adriang71** [comment]
Thank for your replay, it is configured ava this way because I have application and test setup in two different repositories.
