### ISSUE TITLE
Use Node.js worker threads

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1846]
Opening this so we don't forget. It's still in the early days and experimental: https://twitter.com/JavaScriptDaily/status/1009531401216122880

Also see: https://github.com/watson/worker-threads-pool

**Comment by JenyMzo** [comment]
As worker threads are stable already, would it make sense to start working on this now?

**Comment by novemberborn** [comment]
@JenyMzo 👋thanks for your interest!

@abrenneke is working on this already, actually. Have a look at https://github.com/avajs/ava/pull/2333.

**Comment by novemberborn** [comment]
Closing in favor of https://github.com/avajs/ava/issues/1428.
