### ISSUE TITLE
Is it possible to run multiple directories with tests in parallel, but the tests inside to run serially?

### ISSUE THREAD

**Issue by Sosomqk** [avajs/ava#1847]
Hello, 

Due to the software under test's business crtitical feature, my automation tests must be run serially with ava. But they are separated in sub-directories by logic and currently all of them run one by one. I couldn't find info on my problem - is it possible to launch all folders in parallel but the tests scripts inside to be serial?

**Comment by novemberborn** [comment]
You can use `test.serial()` in your test files. AVA will still run files concurrently.

I wonder if you're asking whether you can run tests in each directory serially, but then run multiple directories concurrently. That's not possible.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by Sosomqk** [comment]
Ok, thank you. 

This is what i asked. I achueved this by simply running all folders in parallel with bash script, but I wanted to know if this can be handled by AVA.

Cheers!
