### ISSUE TITLE
Snapshot md files become malformed when new tests with t.snapshot are added.

### ISSUE THREAD

**Issue by coreyfarrell** [avajs/ava#1848]
## Description

When test.js.md is updated by addition of t.snapshot in a new test the md output has missing characters.

### Test Source

See https://github.com/coreyfarrell/ava-snapshot-md-error for smallest possible demo.  First commit shows test.js.md after running only one test, second commit shows the updated result from running both tests.  In the second commit you can see test.js.md was generated without the last character of the first test, plus the file does not end with a line-feed.

### Config

None

### Command-Line Arguments

None

## Environment

```
Node.js v10.4.1
linux 4.16.14-300.fc28.x86_64
ava 1.0.0-beta.6
npm 6.1.0
```

**Comment by novemberborn** [comment]
Nice find!

The appending of the additional snapshot should happen at this line: https://github.com/avajs/ava/blob/fd73358d9ee85c3623a10acfebb5af88c51d628b/lib/snapshot-manager.js#L149

I reckon the line-ending removal code is overly eager:

https://github.com/avajs/ava/blob/fd73358d9ee85c3623a10acfebb5af88c51d628b/lib/snapshot-manager.js#L84

**Comment by coreyfarrell** [comment]
@novemberborn Thanks for pointing me to the right place, was a pretty easy fix.  I'm not sure how/if this could be tested?

**Comment by novemberborn** [comment]
Thanks for the PR!

To be honest I'm not sure if this is worth an integration test. Will have a play next week when I'm back from holiday.

**Comment by novemberborn** [comment]
Works great, thanks @coreyfarrell!
