### ISSUE TITLE
Why is console.log/info forwarded to stderr? Producing confusing logs.

### ISSUE THREAD

**Issue by dewdad** [avajs/ava#1849]
I'm using [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) to run JS tests for our project and I have the following output which is very confusing.

![image 002](https://user-images.githubusercontent.com/6195827/41844594-29462454-7860-11e8-9143-cbc8751ed470.png)

The logging we produce in order to trace our tests' execution is all logged as [ERROR]

ava 1.0.0-beta.6
node 10.5.0
npm 6.1.0

**Comment by novemberborn** [comment]
It's to separate AVA's output from your program's output. For example with the TAP reporter we can't mix them up.

The answer might be to configure your logger to not output anything when tests are running, or to discard `stderr` in CI.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by dewdad** [comment]
Can't this be managed with streams? Use one stream specifically for AVAs output and pipe it at the end to stdout or a file.

**Comment by novemberborn** [comment]
That's pretty much what we do, except that all non-AVA output is written to `stderr`.

I wonder if, unless `--verbose` is set, AVA should not print any non-AVA output. Perhaps with a message at the end that output was silenced.
