### ISSUE TITLE
Logs from min reporter "stick" in terminal

### ISSUE THREAD

**Issue by SidneyNemzer** [avajs/ava#1864]
## Description

Logs from ava's minimal reporter output "stick" in the terminal (see pictures below). In other words, the output is not cleared, even though the min reporter is supposed to clear most of its output (I believe). Occurs in both PowerShell and [Hyper](https://hyper.is) terminal. (I use Hyper from day-to-day, just tested in PowerShell to make sure it wasn't Hyper).

I couldn't find anyone reporting this, although I think clearly something is wrong. Maybe I couldn't find the issue? Otherwise something really strange is happening on my computer.

### Test Source

It doesn't seem that any particular test causes this. Tests are part of proprietary code. I might be able to make an MCVE if that would be helpful.

### Error Message & Stack Trace

No errors -- ava runs tests correctly, the output is rather difficult to read though

### Command-Line Arguments

Reproduces with both:

```
./node_modules/.bin/ava -w
npx ava -w
```

## Relevant Links

Example from Hyper terminal (running Git Bash shell):

![image](https://user-images.githubusercontent.com/21203108/42718967-d029a2b6-86c3-11e8-9b94-ea82260be328.png)

Example from PowerShell:

![image](https://user-images.githubusercontent.com/21203108/42718986-06d5e93c-86c4-11e8-8eeb-fd59974cbcd8.png)

## Environment

```
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v8.9.4
win32 10.0.17134
$ ava --version
1.0.0-beta.6
$ npm --version
6.1.0
```

**Comment by SidneyNemzer** [comment]
Unfortunately same behavior with Node 10

**Comment by SidneyNemzer** [comment]
Might be worth noting that the output was correctly cleared when I first started this project about two weeks ago. As I added more tests it eventually stopped clearing the output, and it got worse as I added more tests.

**Comment by novemberborn** [comment]
Did you also add more test files? I wonder if this is triggered by something in the newer test files, or newer tests. Perhaps you could try and whittle it down to a single test file?

**Comment by SidneyNemzer** [comment]
Correct, I also added more test files too, I've got about 33 test files now. I'll try to narrow it down to one file (although I may not have time to do so until this weekend).

I'm a bit surprised I'm the only one experiencing this, but I suppose in that case it's a not a super high priority.

**Comment by novemberborn** [comment]
> I'm a bit surprised I'm the only one experiencing this, but I suppose in that case it's a not a super high priority.

Yea me too. Which leads me to think it's something in your test output that prevents the line erasure from working, but honestly that's just a wild guess.

**Comment by SidneyNemzer** [comment]
Progress: Commenting out a `console.warn` in firebase-functions greatly reduces the number of stuck lines. I suspect there's another console call *somewhere*, the problem is that it's probably in a library and I don't see it in the terminal. Sometimes, the `console.warn` from firebase-functions would show up, sometimes multiple times, which is what motivated me to comment it out.

And yes, I commented that line out inside of the package in node_modules.

Thoughts?
