### ISSUE TITLE
DeprecationWarning in Node 10

### ISSUE THREAD

**Issue by MarkTiedemann** [avajs/ava#1877]
```
(node:14136) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:159:11)
    at new Buffer (buffer.js:174:3)
    at zalgo.run.then.hash (C:\<redacted>\node_modules\package-hash\index.js:148:19)
```

See [novemberborn/package-hash#34](https://github.com/novemberborn/package-hash/issues/34).

The code has already been updated, but no new version has been released yet.

**Comment by novemberborn** [comment]
Which AVA version are you using?

**Comment by MarkTiedemann** [comment]
@novemberborn Sorry I forgot to include that. I'm using `v0.25.0`. But I guess it's true for any version of `ava` running Node 10 since `package-hash` hasn't be released again yet.

**Comment by novemberborn** [comment]
I'm not sure, I haven't encountered this myself in Node.js 10. Are you perchance using an early release? IIRC something changed and they're only reporting this warning for first-party code.

Will leave this open for now, in case others have run into the same.

Note that v0.25 won't receive any updates and predates Node.js 10.

**Comment by MarkTiedemann** [comment]
Early release and `NODE_PENDING_DEPRECATION=1` was set. Upgrading to latest Node and unsetting the env var fixed it.

Thank you very much for helping me!
