### ISSUE TITLE
--watch not working with typescript recipe 

### ISSUE THREAD

**Issue by midgethoen** [avajs/ava#1881]
Im new to ava so I followed the generic setup and then the typescript recipe.

running `ava` finds the `test.ts`  file nicely. but `--watch` doesn't work then.. whut?!

when renaming `test.ts` to `test.js` it does work;
when running `ava --watch test.ts`  it also does work.

**Comment by novemberborn** [comment]
Oh nice find! I don't think the watcher provides the extensions to the file globber: https://github.com/avajs/ava/blob/3ac2a8f813947588832fccd065d160fc533cd75c/lib/watcher.js#L83

We also need to provide them to the watcher itself: https://github.com/avajs/ava/blob/3ac2a8f813947588832fccd065d160fc533cd75c/lib/cli.js#L237

@midgethoen would you be interested in working on this?

**Comment by midgethoen** [comment]
To be honest I was trying out several testing frameworks to see which appeals most to me. So I’m not even sure jet if this will be ava. However I have been wanting to contribute to open source for some time and the issue seems pretty straight forward. 

I’ll give it a go. Although I’m a bit occupied atm. So it might be in a litte while.

**Comment by novemberborn** [comment]
@midgethoen oh no, I stepped on your toes!

I got as far as https://github.com/avajs/ava/tree/watcher-custom-extensions. Perhaps you could test that with your setup if you still have it lying around? `npm install avajs/ava#watcher-custom-extensions` should do the trick.

If that works we just need some tests in `test/integration/watcher`. That's not particularly glamorous work though, so feel free to punt that back to me 😉

**Comment by midgethoen** [comment]
> @midgethoen oh no, I stepped on your toes!

Ah, That's ok 😁 

The fix works like a charm for me!

**Comment by novemberborn** [comment]
Glad to hear, thanks @midgethoen.

**Comment by denis-sokolov** [comment]
For future readers, my watcher initially only watched for changes in test files, but not in imported source files. I had to manually configure the `sources` key in my [configuration](https://github.com/avajs/ava/blob/f4b2d196e813cf3549e19703e5a79ebc988fb8ca/docs/06-configuration.md#options):

```json
"files": [
  "src/**/*.test.ts"
],
"sources": [
  "src/**/*.ts"
],
```

**Comment by nadilas** [comment]
Hi @novemberborn, I can't get it to work. Using 4.0.1 the sources config is deprecated and changes in my source files seem to be ignored. What's the proper way to use watch with typescript?

Here's my current config:
```
  "ava": {
    "timeout": "60s",
    "concurrency": 1,
    "files": [
      "./src/**/*.test.ts"
    ],
    "typescript": {
      "rewritePaths": {
        "src/": "lib/"
      },
      "compile": "tsc"
    }
  },
```

**Comment by novemberborn** [comment]
@nadilas could you please start a discussion for this? This issue is three years old.
