### ISSUE TITLE
t.throwsAsync is not a function

### ISSUE THREAD

**Issue by papb** [avajs/ava#1883]
## Description

I run a version of Node which does not support async/await. But AVA claims that I can use them and it will automagically work. Unfortunately, I found out that the assertions `t.throwsAsync()` and `t.notThrowsAsync()` are not available.

Note: I am assuming that this issue has something to do with the automagic async/await support simply because I have no other idea of what could be wrong. I just copy-pasted the docs example, so it should work... Am I missing something?

### Test Source

```js
import test from 'ava';
test('throws', async t => {
    await t.throwsAsync(async () => {
        throw new TypeError('foo');
    });
});
```

### Error Message & Stack Trace

```
  Rejected promise returned by test. Reason:

  TypeError {
    message: 't.throwsAsync is not a function',
  }
```

### Command-Line Arguments

```
ava
```

### package.json

It's very likely this is not relevant, but still:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "ava"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "ava": "^0.25.0"
  }
}
```

## Environment

```
Node.js v6.11.1
win32 6.1.7601
npm 3.10.10
ava 0.25.0
```

**Comment by sindresorhus** [comment]
`t.throwsAsync` is not yet released.

You should read the readme from the latest version: https://github.com/avajs/ava/tree/v1.0.0-beta.6#readme
