### ISSUE TITLE
Why does `code` need to be a string in the `expected` parm of `t.throws`?

### ISSUE THREAD

**Issue by ronen** [avajs/ava#1901]
## Description

`t.throws()` and `t.throwsAsync()` take an optional `expected` argument, which is [documented as](https://github.com/avajs/ava#throwsfn-expected-message)

> ... a matcher object with one or more of the following properties:
>
> * [...]
> * `code`: the expected `.code` value of the thrown error

But the documentation doesn't mention that it requires expected `.code` value to be a string (https://github.com/avajs/ava/blob/master/lib/assert.js#L109).

In my app, `.code` is an integer.   Is there a reason not to allow a matcher for integers?    If so it'd be nice to mention that requirement in the doc.  If not, it'd be nice to change it :)

(I tried passing the code as a string, in case it'd test with `==` but no luck :)

Of course simple workaround is to use `err = async t.throwsAsync(...); t.is(err.code, 12345)`

Thanks

## Environment

```
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v10.8.0
darwin 17.7.0
$ npx ava --version
1.0.0-beta.7
$ npm --version
6.3.0
```

**Comment by novemberborn** [comment]
This was modeled after the `.code` property in Node.js, which is a string: https://github.com/avajs/ava/issues/1708

But happy to support numbers as well.

**Comment by okyantoro** [comment]
Hello @novemberborn 

Can I work on this?

**Comment by novemberborn** [comment]
@okyantoro let's see if @ronen was keen on tackling this soon, given that he raised the issue. Appreciate the enthusiasm though 👍

**Comment by okyantoro** [comment]
Sure @novemberborn :)

**Comment by ronen** [comment]
@okyantoro go for it!

(I'm happy to complain but not actually fix anything myself :)

**Comment by novemberborn** [comment]
All yours @okyantoro!

**Comment by okyantoro** [comment]
Thank you @novemberborn @ronen 

I created a pull request in https://github.com/avajs/ava/pull/1902. Let me know if I do something wrong with the unit test.

Thank you
