### ISSUE TITLE
nyc + ava 1.0.0 beta = ReferenceError: require is not defined 

### ISSUE THREAD

**Issue by bcomnes** [avajs/ava#1904]
## Description

Recently, ava 1.0.0 stopped working with nyc.  This is what I'm seeing:

This is with nyc v12 and v13, and all of the ava 1.0.0-beta family.  Tested on node 10 and 8.

The pre-1.0.0 nyc + ava still work together fine, but I really need some of the newer features in 1.0.0 so it would be great to get this fixed.  Rolling recent ava and nyc versions around didn't fix the issue, so this could be a transient dep issue.  Let me know if you have any ideas and I can dig deeper.

### Test Source

NA, throws before loading tests.

### Error Message & Stack Trace

```console
$ npm test

> netlify-cli@0.0.0 test /Users/bret/netlify/cli
> run-s test:*


> netlify-cli@0.0.0 test:ava /Users/bret/netlify/cli
> nyc --reporter=lcov ava --verbose && nyc report

file:///Users/bret/netlify/cli/node_modules/chalk/index.js:2
const escapeStringRegexp = require('escape-string-regexp');

ReferenceError: require is not defined
    at file:///Users/bret/netlify/cli/node_modules/chalk/index.js:2:34
    at Generator.next (<anonymous>)
    at Module._extensions..js (module.js:663:10)
    at file:///Users/bret/netlify/cli/node_modules/nyc/node_modules/append-transform/index.js:62:4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netlify-cli@0.0.0 test:ava: `nyc --reporter=lcov ava --verbose && nyc report`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the netlify-cli@0.0.0 test:ava script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bret/.npm/_logs/2018-08-13T23_29_41_455Z-debug.log
ERROR: "test:ava" exited with 1.
npm ERR! Test failed.  See above for more details.
```

### Config

Copy the relevant section from `package.json`:

```json
"ava": {
    "files": [
      "src/**/*.test.js"
    ]
  },
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
$ nyc --reporter=lcov ava --verbose && nyc report
```

## Relevant Links

Example
https://gist.github.com/bcomnes/82bbd4d6c686c7ca8dcee7f4e333c722

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

Mac os 10.13.6
Node v8.11.3 & 10.8.0
Ava 1.0.0-beta.7
"nyc": "^12.0.2" and 13 beta

**Comment by kaelzhang** [comment]
The same issue 😢

**Comment by SHITianhao** [comment]
same here

**Comment by novemberborn** [comment]
Do you have any Babel configuration in your project?

**Comment by kaelzhang** [comment]
```json
"babel": false
```

**Comment by bcomnes** [comment]
I do not, this is an Uncompiled node app.

**Comment by bcomnes** [comment]
See the runnable gist for a repeatable example.

**Comment by novemberborn** [comment]
@bcomnes unfortunately I can't reproduce this with a plain test file. If you could share more from your project code that may help.

I imagine you may have a local branch from https://github.com/netlify/netlify-cli that perhaps you could push up?

**Comment by bcomnes** [comment]
Currently rewriting on a private repo unfortunately.  I can next week.

...Just retesting my example again:

hah, what was not working yesterday, is working again today.  Smells a lot like a broken transient dep.  Let me run some sanity checks and decide what to do with this issue.

**Comment by bcomnes** [comment]
Seem to be working now.  Closing.  Feel free to re-open if you can reproduce again.
