### ISSUE TITLE
Wait for plan execution

### ISSUE THREAD

**Issue by afoninsky** [avajs/ava#1918]
I want to create helper, which will wait for execution plan or throw an error on timeout. This will reduce boilerplate required for clean test functions.

Example:
```
test('some test', async t => {
  t.plan(3)
  ...
  // lots of async stuff
  ...
  await myHelper(t, 3000) // will wait 3 seconds and throw `Planned for 3 assertions, but got 2`
})
```

1) Is there any workaround to get current execution plan in test? I couldn't find it :(
2) What about proposal `t.planWait(3000)`

**Comment by novemberborn** [comment]
Could you elaborate on what you're looking for beyond what AVA already supports? E.g. there is a timeout feature, but it's to help find inactivity in your test suite as a whole, not a particular test.

Are you looking for the timeout error to have feedback on how far pending tests managed to progress towards their execution plan? Or are you hoping to limit how long a particular tests is allowed to run for?

**Comment by afoninsky** [comment]
No, I'm looking for a way how can I ensure if plan executed OR timeout achieved _in particular test_. Sometimes (often, actually :) I have to test async code without clean interceptors or mocks. So I want to have something like:
```
// just an example
test('some test', async t => {
  t.plan(1) <- set test spaln
  somethingAsync.on('event', () => {
  	t.pass()
  })
  somethingAsync.start()

  await resolveWhenTestPlanAchievedOrRejectAfterTimeout() <- this
})
```
Sure it is a dummy example, but I hope I was able to convey the idea.

**Comment by novemberborn** [comment]
Right, gotcha. AVA's timeout option isn't quite suitable for this.

You could partially get there by calling `t.fail()` after a timeout, but you'll have to detect whether you've reached the plan count yourself.

I think ideally we'd support this through https://github.com/avajs/ava/issues/1692, where you can use `Promise.race()` with a timeout promise, and fail the test if the assertions didn't complete on time.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
