### ISSUE TITLE
How to "prefix" tests?

### ISSUE THREAD

**Issue by ericmorand** [avajs/ava#1919]
I'm aware that sub-tests don't exist in AVA but the documentation hints that it's possible to prefix tests like in the following gif:

![documentation gif](https://github.com/avajs/ava/raw/master/media/mini-reporter.gif)

Test named "accept header with JSON option" is prefixed with "headers" for example.

I'm used to prefix my tests this way to make them much clearer to read:

Foo class
> constructor
>> Accepts 2 parameter
>> Accepts 3 parameters
>
> getBar
>> Returns expected value
>> Throws an exception

With tape it's just a matter of creating sub-tests. But sub-tests are not a thing with AVA so how was the Gif posted above possible?

**Comment by novemberborn** [comment]
When you run more than one test file, AVA prefixes with the file path. Albeit with prettier separator characters.

In my tests I tend to either use separate files, or prefix in the test title itself.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
