### ISSUE TITLE
Is there an access for the "# tests passed" or "# tests failed" output on CLI?

### ISSUE THREAD

**Issue by Isikiyski** [avajs/ava#1922]
Hello,

A bit of context - I run several folders of AVA's tests in unix parallel processes.
So when a directory is successfull it will say for example 72 tests passed.
Right bellow it another test directory is also successful and it will say - 36 tests passed.

Question - how can I access this stdout msg # tests passed/failed.
I want it because I will make a simplle assertion which will take all passed tests combined, and if there is a single failure - fail the whole build run.

Cheers!

**Comment by sindresorhus** [comment]
The default AVA output is not guaranteed to be stable. It's meant for humans. Check out the [`--tap` flag](https://github.com/avajs/ava#tap-reporter) instead, which generates machine-readable output.

**Comment by Sosomqk** [comment]
Ok, thank you!
