### ISSUE TITLE
deepEqual consider the order of `Map`s and `Set`s

### ISSUE THREAD

**Issue by run27017** [avajs/ava#1926]
## Description

Though ava consider maps and sets with different order keys are not the same thing, I think it is not  reasonable. Isn't `new Set([1, 2, 3])` and `new Set([3, 2, 1]` the same thing?

### Test Source

```javascript
test('JS map structures are equal even if order is not the same', (t) => {
  const mapA = new Map([['a', 1], ['b', 2]]);
  const mapB = new Map([['a', 1], ['b', 2]]);

  t.deepEqual(mapA, mapB, 'ava: Maps with equal content in same insertion order compare as equal');

  // same map content, different order
  const mapC = new Map([['b', 2], ['a', 1]]);

  t.deepEqual(mapA, mapC, 'ava: Maps with equal content but different insertion order compare as equal');
});
```

### Error Message & Stack Trace

```

  1 failed

  JS map structures are equal even if order is not the same

  /home/hello/workspace/run27017/json-to-table/test/countMetaMatrixSize.test.js:23

   22:
   23:   t.deepEqual(mapA, mapC, 'ava: Maps with equal content but different insertion order compare as equal');
   24: });

  ava: Maps with equal content but different insertion order compare as equal

  Difference:

    Map {
  -   'a' => 1,
  +   'b' => 2,
  -   'b' => 2,
  +   'a' => 1,
    }
```

**Comment by novemberborn** [comment]
We're erring on the side of caution here. Sets do have an order. I don't want users to write an assertion which they think tests an expected order, and passes, even though the actual order did not match their expectations. If the order is truly insignificant there are still other ways to set up your assertions.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
