### ISSUE TITLE
Throw an error on `t.plan(1)`

### ISSUE THREAD

**Issue by szmarczak** [avajs/ava#1928]
The required amount of tests is `1`. 
`t.plan(n)` changes that. But `t.plan(1)` changes `1` to `1`, so it's useless.
AVA should throw on `t.plan(1)`, because it always throws when no assertion is done.

**Comment by novemberborn** [comment]
Plan also sets a maximum number of assertions. If the test ends and you've exceeded that maximum, the test will fail.

AVA can be configured not to throw, for users who don't use the built-in assertions (see the `failWithoutAssertions` option).

In conclusion `t.plan(1)` does have additional value over AVA's default behavior.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
