### ISSUE TITLE
docs: document the --reset-cache flag

### ISSUE THREAD

**Issue by revelt** [avajs/ava#1929]
## Description

PR https://github.com/avajs/ava/pull/1796 added the `--reset-cache` flag, so let's document it in readme!

**Comment by novemberborn** [comment]
Yea that's an oversight. It's documented in the [Babel recipe](https://github.com/avajs/ava/blob/master/docs/recipes/babel.md#reset-avas-cache) but we should document it in the main README as well.

**Comment by robertbernardbrown** [comment]
I can pick this up. Correct me if I'm wrong, but from reading the Babel Recipe and the mentioned PR it looks like `--reset-flag` should only be used when Babel config files are changed. Otherwise, AVA automatically detects changes to test files and recaches them. Is this more or less correct?

**Comment by revelt** [comment]
@robertbernardbrown Robert, feel free to pick it up, I'm too busy atm

**Comment by robertbernardbrown** [comment]
Cool - just submitted a PR (#1937 ).

Let me know if you see anything that needs changing. Hope it's alright I re-used a little of the explanations offered in the #1796 and the referenced Babel Recipe.
