### ISSUE TITLE
Cannot disable AVAs babel pipeline

### ISSUE THREAD

**Issue by alanshaw** [avajs/ava#1930]
https://github.com/avajs/ava/blob/master/docs/recipes/babel.md#disable-avas-babel-pipeline

I get:

  ✖ Unexpected Babel configuration for AVA. See https://github.com/avajs/ava#es2017-support for allowed values.

**Comment by alanshaw** [comment]
Apologies - this works in 1.0 beta

**Comment by Akiyamka** [comment]
Still not work for me.

node -v 
```10.6.0```

**ava.config.js**
```js
export default {
  "ava": {
    "babel": false,
    "compileEnhancements": false
  }
}
```
npx ava --reset-cache
```
✔ Removed AVA cache files in .../node_modules/.cache/ava
```
test.js
```
import test from 'ava';

test('bar', async t => {
	const bar = Promise.resolve('bar');
	t.is(await bar, 'bar');
});
```
Crush with error
```
   6:                                      
   7: test('bar', async t => {             
   8:   const bar = Promise.resolve('bar');

  ReferenceError: regeneratorRuntime is not defined
```

**Comment by Akiyamka** [comment]
```
import "@babel/polyfill";
```
In every test file help temporary fix this error, bot not fix problem. I still want to turn off the babel, since async/await works great in node 10 without babel

**Comment by Akiyamka** [comment]
@nonnontrivial you right, this really solved the problem. I was confused by the examples in the documentation, and ava did not report an error (usually trow error about invalid options in config)

**Comment by JerryC8080** [comment]
@Akiyamka  

I came across the same problem in ava-1.2.1，and below is how i slove the problem:

in package.json
```json
 "ava": {
    "require": [
      "@babel/register",
      "@babel/polyfill"
    ]
 },
```
