### ISSUE TITLE
When using an async function in `t.throws()`, receive errors: "Function returned: Promise {}" and "Unhandled rejection"

### ISSUE THREAD

**Issue by Lukenickerson** [avajs/ava#1931]
## Description

In `1.0.0-beta.8` (with no special configuration or command line arguments) I'm seeing an error with essentially the same function that was posted in #1371.

### Test Source

```javascript
import test from 'ava';

test('test', async (t) => {
  await t.throws(async () => {
    throw new Error();
  });
});
```

### Error Message & Stack Trace

Message returned from running the test says something like:

> 1 test failed
> 1 unhandled rejection

> Line: await t.throws(async () => {
> Function returned: Promise {}

> Line: throw new Error();
> Unhandled rejection in _[test filename]_

## Environment

Node.js v10.9.0
darwin 17.6.0
AVA 1.0.0-beta.8
npm 6.2.0

**Comment by novemberborn** [comment]
Ah sorry about that. As of [Beta 7](https://github.com/avajs/ava/releases/tag/v1.0.0-beta.7), `t.throws()` only works for synchronous errors. You'll need to change your test to use `t.throwsAsync()`.

However we should provide better feedback in the test output. I've opened #1932 with some pointers.
