### ISSUE TITLE
'Cannot read property \'substring\' of undefined'

### ISSUE THREAD

**Issue by run27017** [avajs/ava#1935]
## Description

Just a simple test, compare two strings.

### Test Source

```js
const test = require('ava')

test.only('222', t => {
  const html = `<table>
    <tr>
      <td>undefined</td>
      <td>3</td>
    </tr>
</table>
`
  const expected = `<table>
    <tr>
      <td>3</td>
      <td>4</td>
    </tr>
</table>`
  t.is(html, expected)
})
```

### Error Message & Stack Trace

```
  1 failed

  222

  .../node_modules/fast-diff/diff.js:63

  Error thrown in test:

  TypeError {
    message: 'Cannot read property \'substring\' of undefined',
  }

  diff_main (node_modules/fast-diff/diff.js:63:17)
  diffLine (node_modules/concordance/lib/primitiveValues/string.js:65:19)
  StringValue.diffDeep (node_modules/concordance/lib/primitiveValues/string.js:271:24)
  Object.diffDescriptors (node_modules/concordance/lib/diff.js:307:17)
  Test.is (test/222.test.js:17:5)
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

- node: `Node.js v8.11.1, linux 4.4.138-59-default`
- npm: 6.4.0
- ava: 0.25.0

**Comment by novemberborn** [comment]
Wow that's unexpected! I've opened an issue in the underlying library: https://github.com/concordancejs/concordance/issues/44.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
