### ISSUE TITLE
Beta 8: Importing Typescript files gives: default is not a function

### ISSUE THREAD

**Issue by mesqueeb** [avajs/ava#1952]
## Description

- Ava can handle most of my TS files imported into the AVA test files.
- Ava cannot handle when an imported TS file imports another module. I get the error that `~~.default is not a function`.

### My Ava test file
```js
import setDefaultValues from '../src/utils/setDefaultValues.ts'
```
And that TS file has this line:
```js
import merge from 'merge-anything'
```
Merge anything is a public repo [available here](https://github.com/mesqueeb/merge-anything).

### Error Message & Stack Trace
I get this error originating from the imported file
```
TypeError {
    message: 'merge_anything_1.default is not a function',
  }
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "devDependencies": {
    "ava": "^1.0.0-beta.8",
    ...
  }
}
```
My AVA config is in `ava.config.js`
```
export default {
  'compileEnhancements': false,
  'extensions': [
    'ts'
  ],
  'require': [
    'ts-node/register'
  ]
}
```
### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava
```

## Relevant Links

- [Public repo](https://github.com/mesqueeb/vuex-easy-firestore/tree/rewrite-tests)
- `rewrite-tests` branch.
To reproduce:
```
yarn
yarn test ./test/utils
```

**Comment by novemberborn** [comment]
> 'merge_anything_1.default is not a function'

This looks like a runtime error coming from your compiled TypeScript. That's not something AVA is responsible for.

Looking at `merge-anything`, the "main" points at a CJS file, not an ESM file. I think you might have to use `import merge = require('merge-anything')` instead.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by mesqueeb** [comment]
@novemberborn however the weird thing is that other commonjs files are properly imported even with `import` in ava, just this one cjs file that gives me problems. : S

About your workaround: use `require` instead. 
This is not possible because `import merge from 'merge-anything'` is happening in one of my source files. Not in the ava test file. In the source file it works perfectly like so, but importing that source file gives me the bug. 

I know it’s confusing sorry for the bad explanation.

- Ava test: import a.ts
- A.ts: import merge

**Comment by novemberborn** [comment]
Babel isn't touching your test files though. Presumably they're being loaded by `ts-node/register`. You should be able to reproduce this outside of AVA.

**Comment by mesqueeb** [comment]
I don’t use babel yes. Only TypeScript.

**Comment by mesqueeb** [comment]
@novemberborn 
It's reproducable if you clone this:
https://github.com/mesqueeb/vuex-easy-firestore/tree/rewrite-tests
notice `tree/rewrite-tests`
Then just `yarn` and `yarn test ./test/utils/setDefaultvalues.js`

As you can see in the top two lines:
```js
// import setDefaultValues from '../../src/utils/setDefaultValues'
import setDefaultValues from '../helpers/utils/setDefaultValues'
```
The first one is the TS file from src, the second one is the CJS file compiled by rollup which uses a typescript compiler plugin. No babel is used for this compilation and I have a TS config file set up.

When using the top line from the TS file it will give me the error
`'merge_anything_1.default is not a function'`
When using the second line with the CJS file it works

Any ideas for me?
Thakns a lot!
