### ISSUE TITLE
Advice regarding indeterminate callbacks

### ISSUE THREAD

**Issue by natzcam** [avajs/ava#1964]
How best to approach this?

```
test.cb('2 callbacks', t => {
    t.plan(2);

    const alice = new Alice();
    alice.on('connect', () => {
        t.pass();
        t.end(); //?
    });

    const bob = new Bob();
    bob.on('connect', () => {
        t.pass();
        t.end(); //?
    });
});
```

There is no guarantee which connect callback will be called first, but I need to assert that both got called. Promise.all could solve this but are there any alternatives?

**Comment by havenchyk** [comment]
@natzcam I don't know the answer except using `Promise.all`, but the best place for asking such questions is https://spectrum.chat/ava or stackoverflow.

Btw, if you could split this logic into 2 tests it would be easier to track/manipulate from the first sight.

**Comment by novemberborn** [comment]
You could also count how many `connect`s are still pending, decrement on each `connect` and within that callback if you hit zero, call `t.end()`.

None of this helps if a callback is invoked twice though.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by novemberborn** [comment]
You could also count how many `connect`s are still pending, decrement on each `connect` and within that callback if you hit zero, call `t.end()`.

None of this helps if a callback is invoked twice though.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by sindresorhus** [comment]
You could also use [`p-event`](https://github.com/sindresorhus/p-event) for this:

```js
import test from 'ava';
import pEvent from 'p-event';

test('2 callbacks', async t => {
	const alice = new Alice();
	await pEvent(alice, 'connect');

	const bob = new Bob();
	await pEvent(bob, 'connect');

	t.pass();
});
```

**Comment by natzcam** [comment]
Tried above, but the test would not complete because connection is initiated on the constructor and `await pEvent(alice, 'connect');` would block new Bob(). Changing the order did not help either, because 'connect' might have been fired already.
```
  const alice = new Alice();
  const bob = new Bob();
  await pEvent(alice, 'connect');
  await pEvent(bob, 'connect');
  t.pass();
```
Using Promise.all would solve it though, but it would circle back to my original question. :)
```
  await Promise.all([pEvent(alice, 'connect'), pEvent(bob, 'connect')]);
  t.pass();
```
It would be nice, for callbacks, there is a 'countdown' functionality. Wherein, the test would end when the countdown = 0
```
test.cb('2 callbacks', t => {
    t.plan(2);
    t.countdown(2);

    const alice = new Alice();
    alice.on('connect', () => {
        t.pass();
        t.end(1); //decrement 1
    });

    const bob = new Bob();
    bob.on('connect', () => {
        t.pass();
        t.end(1); //decrement 1
    });
});
```

**Comment by novemberborn** [comment]
I think that's functionality one could add atop of AVA once #1692 lands.
