### ISSUE TITLE
Can AVA be integrated with Codeceptjs, Cypressjs or other similar frameworks?

### ISSUE THREAD

**Issue by Isikiyski** [avajs/ava#1965]
Hello,

I could not find this particular info on the web, but in a nutshell:

Can AVA be used with Cypressjs (https://www.cypress.io/) or  Codeceptjs(https://codecept.io/)
 
Thanks in advance!

**Comment by havenchyk** [comment]
Hey, @Isikiyski, the best place to ask such questions is https://spectrum.chat/ava or stackoverflow.

**Comment by novemberborn** [comment]
As long as you can import an npm library and drive your tests from a Node.js process, you can probably use AVA.
