### ISSUE TITLE
Ava is not using babel presets from ava config

### ISSUE THREAD

**Issue by sarneeh** [avajs/ava#1968]
## Description
I've followed the latest [babel recipe](https://github.com/avajs/ava/blob/master/docs/recipes/babel.md) to configure `ava` in my project to use it with `React`. Unfortunately, specifying `babel` configuration via the `ava` property in `package.json` doesn't work. What's interesting is that using the same `babel` presets in `.babelrc` make `ava` work properly.

### Test Source

Subject:
```js
import React from "react";

class Component extends React.Component {
    render() {
        return <h1>Hello World</h1>;
    }
}

export default Component;
```

Test:
```js
import test from "ava";

import Component from "./index";

test("something", t => {
    t.pass();
});
```

### Error Message & Stack Trace

```
$ ava

  ✖ No tests found in index.test.js

  1 uncaught exception

  Uncaught exception in index.test.js

  /Users/sarneeh/Workshop/Development/Software/ava-test/node_modules/@babel/parse
r/lib/index.js:3939

  SyntaxError: /Users/sarneeh/Workshop/Development/Software/ava-test/index.js: Un
expected token (5:15)

  Parser.raise (node_modules/@babel/parser/lib/index.js:3939:15)
  Parser.unexpected (node_modules/@babel/parser/lib/index.js:5248:16)
  Parser.parseExprAtom (node_modules/@babel/parser/lib/index.js:6328:20)
  Parser.parseExprSubscripts (node_modules/@babel/parser/lib/index.js:5924:21)
  Parser.parseMaybeUnary (node_modules/@babel/parser/lib/index.js:5903:21)
  Parser.parseExprOps (node_modules/@babel/parser/lib/index.js:5812:21)
  Parser.parseMaybeConditional (node_modules/@babel/parser/lib/index.js:5784:21)  Parser.parseMaybeAssign (node_modules/@babel/parser/lib/index.js:5731:21)
  Parser.parseExpression (node_modules/@babel/parser/lib/index.js:5684:21)
  Parser.parseReturnStatement (node_modules/@babel/parser/lib/index.js:7508:28)
```

### Config

Non-working:

package.json
```json
{
    "ava": {
        "require": [
            "@babel/register"
        ],
        "babel": {
            "testOptions": {
                "presets": [
                    "@babel/preset-react"
                ]
            }
        }
    }
}
```

Working:

package.json
```json
{
    "ava": {
        "require": [
            "@babel/register"
        ]
    }
}
```

.babelrc
```json
{
    "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```

### Command-Line Arguments

Just `ava`.

## Relevant Links

I've created a reproduction repository with a non-working and working example.

Using `ava` property in `package.json`: https://github.com/sarneeh/ava-babel-issue/tree/master
Using `.babelrc`: https://github.com/sarneeh/ava-babel-issue/tree/working-example

## Environment

Node: `10.9.0`
Ava: `1.0.0-rc.1`

**Comment by novemberborn** [comment]
`@babel/register` doesn't consult AVA's configuration. You haven't configured how it should compile the source files. Thus you get a syntax error when you try to load a source file (through `@babel/register`). It doesn't get compiled so the JSX syntax ends up breaking it.

Using `.babelrc` or `babel.config.js` is the correct approach.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
