### ISSUE TITLE
Inlining tests into the project

### ISSUE THREAD

**Issue by gajus** [avajs/ava#1972]
Is there a downside to inlining tests into the project?

Suppose I have a `/src/utilities.js` project file, what would be a reason not to inline the tests?

```js
import test from 'ava';

const roundTo = (subject, multiple) => {
  return Math.ceil((subject + 1) / multiple) * multiple;
};

test('roundTo: rounds input to the closest multiple', (t) => {
  t.true(roundTo(87, 10) === 90);
});

// ... other utilities and tests

```

Production build would not be affected (it is simple to strip all ava specific function calls and therefore tests).

I have a project with thousands of API integrations. Each integration has its own ad-hoc utilities. Creating a dedicated test file for every scraper would just create clutter in the codebase (e.g. it would require to export all utilities from the file).

Fishing for feedback: What would be the downsides of my approach?

**Comment by makepost** [comment]
Please do export utilities. What's worth testing is probably a functional unit others would like to reuse. Modules and IIFEs with inaccessible stuff inside are often a pain, when I need just some of their behavior but have to launch something with dependencies the size of my app simply to get a way to execute it.

Tests serve great as up-to-date usage examples, so it's convenient for a library end user to focus on a separate file without getting distracted by implementation details. Contrarily, library authors, who are looking for what usage of a specific method their changes can affect, benefit from having the tests by hand. Sort of a compromise is placing `Unit.js` and `Unit.test.js` in the same dir.

Other point is about tests that are roughly the size of what they check, or bigger, and have their own additional dependencies. They get in the way when you're navigating inside the file, and search of unused imports which might have side effects is probably more resource-intensive that stripping test calls.

When these are not a problem, it's alright I think. Interested in seeing code bases with inline Ava tests, checking out how efficiently minification and hot module replacement escape these, and whether it reminds of [CommonJS tests](http://wiki.commonjs.org/wiki/Unit_Testing/1.0#Test).

**Comment by novemberborn** [comment]
@gajus that's an interesting approach for sure. I'd be careful to disable AVA's Babel transforms since they'll suddenly also impact your source code. 

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
