### ISSUE TITLE
sources ignored in ava.config.js

### ISSUE THREAD

**Issue by Christilut** [avajs/ava#1982]
## Description

I have added the `sources` section to `ava.config.js` as below but when I run this command:
```bash
npm run test:watch -- --verbose --match="foo"
```
The tests are not re-run when saving a file under the `server/` path.

However, when I add the `sources` parameter as CLI argument then it does work as expect:
```bash
npm run test:watch -- --verbose --match="foo" --sources="server/**/*.ts"
```

And when I run without any argument then it the `sources` from `ava.config.js` does work:
```bash
npm run test:watch
```

So I guess when adding CLI arguments, the ava.config.js `sources` arguments is lost even when it is not added as a CLI argument. Is this expected behavior?

### Config

```json
export default {
  "compileEnhancements": false,
  "extensions": [
    "ts"
  ],
  "require": [
    "ts-node/register"
  ],
  "sources": [
    "server/**/*.ts"
  ],
  "files": [
    "tests/*.test.ts"
  ]
}
```

### Command-Line Arguments
test script:
```json
"test:watch": "ava --watch",
```
npm run test:watch -- --verbose --match="foo"

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v8.12.0
ava 1.0.0-beta.8
npm 6.4.1
```

**Comment by novemberborn** [comment]
The `--sources` flag doesn't exist… Try setting the `DEBUG` environment variable so it logs the file changes: https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#debugging

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by Christilut** [comment]
Ah okay. I thought that all the options [here](https://github.com/avajs/ava/blob/master/docs/06-configuration.md) were both ava.config.js options and CLI options.

I think I was confused by this line: `Arguments passed to the CLI will always take precedence over the configuration in package.json.` which is followed by the ava.config.js options.

I'll use the debug flag and see why sources is ignored when adding match.
