### ISSUE TITLE
How to really failFast?

### ISSUE THREAD

**Issue by Druotic** [avajs/ava#1987]
Is there a way to ensure exactly one test case runs at a time (globally) _and_ when a test fails, do not run any more tests? If not, is that something that would be viewed favorably if I were to open a PR? Thanks!

Context: v0.25.0 Recently, I noticed that `failFast` doesn't seem to behave quite like I expected. For some of our projects, we run the integration tests with `concurrency=1` and all tests use `.serial` to ensure that exactly one integration test is running at a time. In this scenario, I thought `failFast=true` would mean that if the current test fails, no others would run. However, that's not quite true. In reality, only the other tests in the same file (process) after the failing test are skipped. All other files will continue to be executed despite the failure.

I'm happy to include a snippet to reproduce if necessary, but the scenario seemed simple enough. Let me know if you'd like to see a snippet for reproduction and I'd be happy to add one!

**Comment by havenchyk** [comment]
@Druotic could you please try `ava@next`? I have the same case (integration tests with `serial: true`) and if one test fails, ava stops executing.

**Comment by Druotic** [comment]
@havenchyk Nice! `ava@next` worked like a charm, thanks! Looking forward to the next release 👍
