### ISSUE TITLE
Feature Request:  store human-readable snapshot files as .yaml/.json vs .md

### ISSUE THREAD

**Issue by sramam** [avajs/ava#1988]
## Description
Using ava's snapshot capability, I have increasingly gravitated towards writing data-driven test cases.
The general pattern is:

```
test(`my test`, (t) => {
  const { all, data, generated} = fnUnderTest(); 
  t.snapshot({all, data, generated});
});
```
This has been greatly simplifying to writing tests.

One nagging inconvenience, is the snapshot.md files. 
Which by their nature have to store the "snapshot" as a string, irrespective of it's actual format. 
In my case, the data can be voluminous, making navigating the data when errors happen rather
inconvenient. In my case, the snapshot data per test can sometimes exceed 100's of LOC.

Since the snapshot is really a great big JS object, I was wondering if there is any appetite to store it as YAML or JSON. That'll allow leveraging an IDE's structured navigation capabilities to make this task easier.

**Comment by novemberborn** [comment]
This is too much of an edge-case for how we see snapshots being used, sorry.

It sounds like you may not need the readable files at all, given that the data is perhaps generated elsewhere. You could ignore those files from source control, you only need the `.snap` files committed for use in CI.
