### ISSUE TITLE
Dynamic import not supported

### ISSUE THREAD

**Issue by RedHatter** [avajs/ava#1990]
When I try and use dynamic import in my source files ava throws `Error: Not supported`. I have `@babel/plugin-syntax-dynamic-import` enabled in my babelrc.

See minimal repo [here](https://github.com/RedHatter/ava-import).

**Comment by FreddyFY** [comment]
I don't know if it'll help you but I had a similar problem.
Changing`@babel/plugin-syntax-dynamic-import` to `dynamic-import-node` worked for me.
