### ISSUE TITLE
Searching documentation 

### ISSUE THREAD

**Issue by Christilut** [avajs/ava#1994]
I kinda miss the old documentation style because I could search in everything very quickly. Now I can't do that anymore.

Maybe we can also have 1 file that merges all documentation for people who like to have one giant readme? Should make everyone happy!

**Comment by Christilut** [comment]
Thanks, but it's not quite the same

**Comment by foxbunny** [comment]
I agree it's not the same. 

If the ava devs are fine with introducing some Python dependencies just for documentation, I could look into preparing a MR that ports the existing docs to [MkDocs](https://mkdocs.readthedocs.io/en/859/). It has the ability to create search indices that are strictly client-side, and a single command to publish on GH pages.

Themes can be customized to taste, although I normally don't bother and just go with the ReadTheDocs theme you see on the link I've provided.

**Comment by Christilut** [comment]
That site looks nice but I don't feel that it works that well. Search is slow and doesn't work intuitively.

Personally I'd go either 1 giant markdown file or if you want something more fancy maybe Gitbook, which is free for open source anyway.

**Comment by foxbunny** [comment]
> Search is slow and doesn't work intuitively.

I've just checked the MkDocs site, the search doesn't work _at all_ for me. Though, I've set it up [for Imba](https://imba.github.io/imba-guide/search.html?q=variable) earlier, and the search is both quick and finds what you need.

**Comment by novemberborn** [comment]
@Christilut agreed. We had to split the documentation since it was too hard to manage. I think we're ready for a site, though. Let's take the conversation to https://github.com/avajs/ava/issues/1454#issuecomment-445475088.
