### ISSUE TITLE
Errors thrown outside of tests have truncated message

### ISSUE THREAD

**Issue by sholladay** [avajs/ava#1995]
## Description

AVA is truncating multline error messages before displaying the error in the console when that error is thrown outside of a test (e.g. inside of a helper that is being imported). This doesn't seem to happen if the error is thrown in the test itself.

In the minimal example below, where AVA shows the source code lines with a hardcoded message, this may not seem like a big deal. But in practice, I stumbled upon this with some argument validation logic in a helper. The output in the terminal was super confusing and vague because the actual and exepected values were not on the first line (it was a [joi](https://github.com/hapijs/joi) error) and basically all it said was `ValidationError: {`.

### Test Source

```js
// test/hello-world.js
import test from 'ava';

throw new Error('I will be seen\nBut I will not be seen');

test('hello', () => {
    t.true(true);
});
```

### Error Message & Stack Trace

```
❯ npx ava test/hello-world.js


  ✖ No tests found in test/hello-world.js

  1 uncaught exception

  Uncaught exception in test/hello-world.js

  /Users/sholladay/Code/noirdoor/chords/test/hello-world.js:3

   2:
   3: throw new Error('I will be seen\nBut I will not be seen');
   4:

  Error: I will be seen
```

### Config

N/A

### Command-Line Arguments

```
npx ava
```

## Environment

```
Node.js v8.14.0
darwin 17.7.0
ava 1.0.0-rc.2
npm 6.4.1
```

**Comment by novemberborn** [comment]
I think that's due to this line:

https://github.com/avajs/ava/blob/eed2e7a9bc7a8bcdd6917206e6685feeda325e14/lib/serialize-error.js#L106

Errors that occur inside tests are probably treated as assertion errors, so they end up being serialized differently.
