### ISSUE TITLE
Incompatibility between 1.0.0 and import-fresh

### ISSUE THREAD

**Issue by pvdlg** [avajs/ava#1999]
I'm testing a module that keeps a state, so I need to import it fresh (bypassing `require` cache) for each test.
In `ava@0.25` I was doing the following:
```js
test.beforeEach(t => {
  clearModule('..');
  t.context.m = require('..');
});

test('Test 1', async t => {
  t.is(await t.context.m.something(), expectation);
});

test('Test 2', async t => {
  t.is(await t.context.m.something(), expectation);
});
```

However with `ava@1.0.1` the module in `t.context.m` is not imported fresh and contains the state set by other tests.

I tried different approaches to solve this issue, but unsuccessfully so far:

**Call `clear-module` in each test**

```js
test('Test 1', async t => {
  clearModule('..');
  t.is(await require('..').something(), expectation);
});

test('Test 2', async t => {
  clearModule('..');
  t.is(await require('..').something(), expectation);
});
```
The result is the same, the module is not imported fresh and has the state set by other test.

**Use `import-fresh` in `beforeEach`**

```js
test.beforeEach(t => {
  t.context.m = importFresh('..')();
});

test('Test 1', async t => {
  t.is(await t.context.m.something(), expectation);
});

test('Test 2', async t => {
  t.is(await t.context.m.something(), expectation);
});
```

With this config the `beforeEach` of each test throws the error `All tests and hooks must be declared synchronously in your test file, and cannot be nested within other tests or hooks.`

**Use `import-fresh` in each test**

```js
test('Test 1', async t => {
  t.is(await importFresh('..')().something(), expectation);
});

test('Test 2', async t => {
  t.is(awaitimportFresh('..')().something(), expectation);
});
```
With this config each test throw the error `Cannot read property \'getFileName\' of undefined` with the stack trace:
```
<redacted>/node_modules/caller-path/index.js:4
module.exports (node_modules/caller-path/index.js:4:40)
module.exports.moduleId (node_modules/import-fresh/index.js:11:44)
```

**Question / bug report**

Is it something intentional/expected in `ava@1.0.1`? Or is it a bug?
If it's intentional or expected what is the proper way to to have each test provided with freshly imported module instance?

**Comment by novemberborn** [comment]
Based on the syntax you posted, I don't know why your tests would stop working. 

> With this config the `beforeEach` of each test throws the error `All tests and hooks must be declared synchronously in your test file, and cannot be nested within other tests or hooks.`

Is the module you're importing declaring tests? Cause it sure looks like you're declaring everything synchronously.

Could you point me to the relevant code in, I presume, https://github.com/semantic-release/github/pull/143?

**Comment by pvdlg** [comment]
I encountered the problem with https://github.com/semantic-release/npm/blob/master/test/integration.test.js

Here is a reduced test case: https://gist.github.com/pvdlg/171b84eecd08b22da547c15c55a6163b

**Comment by pvdlg** [comment]
Analyzing a bit further I think it's related to the `cwd` set by AVA when calling `clearModule`.

See this other reduced case: https://gist.github.com/pvdlg/6bd01c2d66350e8bb2f25aba64ad8859

It's similar to the previous, but instead of having the `test.js` file in the `test` directory it's at the root of the project, so `clear-module` is called with `clearModule('.')`. In that scenario `clear-module` throw the error `Cannot find module \'.\'`.

For some reasons in the first scenario `clearModule('..')` doesn't throw but I'm guessing it doesn't clear the cache the module I'm testing.

**Comment by pvdlg** [comment]
With the second example, in the `clear-module` package, on [this line](https://github.com/sindresorhus/clear-module/blob/fe68245dd2f9accf5ab757c7649b3e41bdb38fe1/index.js#L11), callerPath():
- returns `<project_root>/test.js` in `ava@0.25.0`
- returns `<project_root>/node_modules/ava/lib/test.js` in `ava@1.0.1`

I can't figure out why though....

**Comment by sindresorhus** [comment]
Turns out the logic in `caller-callsite` is pretty buggy in recent Node.js versions, although it used to work perfectly. That's what happens when you accidentally rely on implementation details...

I have done a new version of `clear-module` and `import-fresh` which both now works with your [test case](https://gist.github.com/pvdlg/6bd01c2d66350e8bb2f25aba64ad8859).

**Comment by pvdlg** [comment]
Thanks, that works!
I think we can close this issue then, unless you see a reason to keep it opened?
