### ISSUE TITLE
Calling t.true or t.false with spread operator causes "Unexpected token" error

### ISSUE THREAD

**Issue by GregRos** [avajs/ava#2004]
## Description

If you call `t.true` or `t.false` with a spread operator instead of specifying the arguments manually, and the assertion fails, you get the following error instead of the failure that should occur:

```
  SyntaxError {
    message: 'Unexpected token u in JSON at position 0',
  }
```

I assume this is because the magic assert gets confused when it sees the way in which `t.true` is called.

Other assertions don't have this problem.

### Test Source

```js
const test = require("ava").default;

test("example1", t => {
  t.true(...[false, "bad!"]);
}); // the assertion throws an unexpected error

test("example2", t => {
  t.false(...[true, "bad!"]);
}) // the assertion throws an unexpected error

test("example3", t => {
  t.is(...[1, 0, "bad!"]);
}) // this doesn't
```

### Use-case
I was using this to get around the fact ava doesn't support custom assertions. Basically a had a function like this:

```
function checkSomething(x) {
    return [PASS, "reason for the failure];
}

test("test", t => {
    t.true(...checkSomething(1));
});
```

So I would get a human-readable reason for the failure together with `t.true`'s regular printout. 

### System, config, etc
It always happens.

**Comment by novemberborn** [comment]
Oh that's an interesting use case!

I think this is an issue with the Babel plugin that we use, I've filed an upstream issue at https://github.com/power-assert-js/babel-plugin-espower/issues/28.

**Comment by twada** [comment]
Thank you for reporting 😃
I've cut a patch release [3.0.1](https://github.com/power-assert-js/babel-plugin-espower/blob/master/CHANGELOG.md#301-2019-01-08). So would you try it again?

**Comment by novemberborn** [comment]
Thanks @twada, that works great for me.

I've published a patch release of https://www.npmjs.com/package/@ava/babel-preset-transform-test-files to ensure users get the latest `babel-plugin-espower` when they next upgrade AVA. (Will bump AVA's dependency on that preset as part of the release process.)
