### ISSUE TITLE
Expose current test instance to `test.meta`

### ISSUE THREAD

**Issue by szmarczak** [avajs/ava#2017]
In last release (1.1.0) there was added [`test.meta` feature](https://github.com/avajs/ava/commit/bccd297f38c9f4cf6dbb16dffa7ee8753dbbd12f).

I'd like to propose `test.meta.currentTest` which points to the current test instance. Use case:

```diff
-const compare = (t, entries, goal) => {
+const compare = (entries, goal) => {
+   const t = test.meta.currentTest;
	if (Array.isArray(entries)) {
		entries = entries.map(entry => {
			t.true(typeof entry.expires === 'number');
			return {
				address: entry.address,
				family: entry.family
			};
		});
	} else {
		delete entries.expires;
	}

	t.deepEqual(entries, goal);
};

test('demo', t => {
	const entries = getEntries();
-	compare(t, entries, [
+   compare(entries, [
		{address: '1.2.3.4', family: 4},
		{address: }
	]);
});
```

**Comment by szmarczak** [comment]
> I don't think that would work for asynchronous tests: multiple tests would be running concurrently so there wouldn't be any one currentTest.

Hmm, that's true, unfortunately.

> Besides the code sample, could you elaborate on your use case?

You just need to pass the test instance every time, which is quite irritating. I often did `compare(entries, ...)` instead `compare(t, entries)`.

**Comment by novemberborn** [comment]
We are open to being able to install additional assertions on `t`: https://github.com/avajs/ava/issues/1094

**Comment by szmarczak** [comment]
@novemberborn That whould be the right thing :)
