### ISSUE TITLE
Allow excludePatterns to be overwritten

### ISSUE THREAD

**Issue by RedKenrok** [avajs/ava#2020]
Ava is a great library and enjoy using it. I would love to be able to overwrite the `excludePatterns` property of the `lib/ava-files.js` script as it currently always set to the default of `[ '!**/node_modules/**', '!**/fixtures/**', '!**/helpers/**' ]` at line 118. Because I use the helpers directory name in my library and would like my test directory to follow a similar structure. As a result the directories becomes easier to navigate and allowing me to prepend an underscore to the actual test helpers would help it stand out and pin it to the top of the test directory.

Currently what my project directory looks like:

```
...
├── examples/
├── library/
│   ├── helpers/
│   └── index.js
└── test/
     ├── examples/
     ├── helpers/
     └── library/
         ├── _helpers/
         └── index.js
```

What I would to be able to make my project directory look like:

```
...
├── examples/
├── library/
│   ├── helpers/
│   └── index.js
└── test/
     ├── _helpers/
     ├── examples/
     └── library/
         ├── helpers/
         └── index.js
```

**Comment by novemberborn** [comment]
Agreed, see #909. I've been meaning to summarize my thoughts on our various [globbing issues](https://github.com/avajs/ava/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Ascope%3Aglobbing) into a concrete proposal but haven't gotten round to it yet.
