### ISSUE TITLE
Deprecated workspaceRoot in VS Code debug recipe

### ISSUE THREAD

**Issue by niktekusho** [avajs/ava#2023]
## Description

In the [Debugging tests with Visual Studio Code](https://github.com/avajs/ava/blob/ed7807e372f7f50d43597d966a2314bdd7a7d6ff/docs/recipes/debugging-with-vscode.md) the `{workspaceRoot}` variable has been deprecated since version 1.17 in favor of `{workspaceFolder}`. Relevant links below.

I'm opening this issue just in case anyone has something against changing that variable (in my local tests `{workspaceFolder}` is fine).

If it is fine to change it, I'll open a PR about it.

## Relevant Links

- https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented
- https://code.visualstudio.com/updates/v1_17#_workspacefolder-in-launchjson-and-tasksjson

**Comment by novemberborn** [comment]
A PR would be great!

**Comment by novemberborn** [comment]
Ah I thought I saw the PR, but then it didn't show up in the links here. Turns out the reference to this issue was incorrect (I've since fixed that). Thanks @niktekusho!

**Comment by niktekusho** [comment]
> Ah I thought I saw the PR, but then it didn't show up in the links here. Turns out the reference to this issue was incorrect (I've since fixed that). Thanks @niktekusho!

Yeah, sorry about that! Glad this was merged quickly! 🎉
