### ISSUE TITLE
`timeout` option is missing in Configuration documentation

### ISSUE THREAD

**Issue by niftylettuce** [avajs/ava#2025]
Docs suggest otherwise at <https://github.com/avajs/ava/blob/master/docs/07-test-timeouts.md>

**Comment by niftylettuce** [comment]
Ah, I see that they accept human-friendly Strings.  Perhaps we should document this!

<https://github.com/avajs/ava/blob/bccd297f38c9f4cf6dbb16dffa7ee8753dbbd12f/test/api.js#L269>

**Comment by novemberborn** [comment]
Ah yes it should be added to https://github.com/avajs/ava/blob/master/docs/06-configuration.md. Thanks for noticing, @niftylettuce.

**Comment by Chrisyee22** [comment]
Hi. If this issue is still open I would be happy to work on it.

**Comment by novemberborn** [comment]
That'd be great @Chrisyee22!

**Comment by MackenzieBerliner-Glasser** [comment]
@Chrisyee22 hey are you still working on this issue? If not I would be happy to work on it :).

**Comment by Chrisyee22** [comment]
@MackenzieBerliner-Glasser I am still working on this issue. Got delayed by a flu. ☹️

**Comment by MackenzieBerliner-Glasser** [comment]
@Chrisyee22 oh no :/. I hope you are feeling better!
