### ISSUE TITLE
Suggestion for tagline

### ISSUE THREAD

**Issue by incompl** [avajs/ava#2026]
I apologize if this seems frivolous, but I really enjoy unit testing and I think the tagline for this project "Testing can be a drag. AVA helps you get it done."  perpetuates a misconception that testing is inherently unpleasant. In my experience when testing is unpleasant it is usually as a result of unpleasant tools. This misconception can contribute to testing-avoidant behavior and results in lower quality software across the community. AVA is absolutely a fun tool that helps me focus on what I love about testing. I believe only a minor change in the tagline would make it more accurate and more virtuous. For example: "Testing can be fun. AVA helps you get it done." Furthermore, though it was not my intention, this suggestion _rhymes_, which is amazing. Thank you for your consideration!

**Comment by bthompson90** [comment]
I think we'll find that every developer has their own opinion on testing.  I like the suggestion by @incompl though.  Perhaps we could have a survey?

**Comment by sindresorhus** [comment]
I agree the tagline be a bit more positive.

**Comment by novemberborn** [comment]
We could leave it up to your own interpretation:

> Testing. AVA helps you get it done.

@incompl may read this as "Testing! Yay, AVA helps me get it done" and I can read it as "Testing… AVA helps me get it done."

**Comment by novemberborn** [comment]
FYI we've recently changed this to "Node.js test runner that lets you develop with confidence 🚀".
