### ISSUE TITLE
Use `unknown` in the TS types instead of `any`

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#2030]
Pretty much anywhere `any` is used. It's stricter, which is good.

https://stackoverflow.com/questions/51439843/typescript-3-0-unknown-vs-any

It's breaking change, so it will have to wait for AVA v2.

---

The Flow definitions too. `mixed` instead of `any`: https://stackoverflow.com/questions/30004233/what-is-the-difference-between-mixed-and-any

**Comment by novemberborn** [comment]
Could you be more specific which `any`'s you'd like to replace? For our assertions, `any` seems more appropriate since we're typing what kinds of values you can provide. `unknown` is useful as a way to force yourself to refine the type of value you received.

**Comment by sindresorhus** [comment]
> TypeScript 3.0 introduces a new type called unknown that does exactly that. **Much like `any`, any value is assignable to `unknown`**; however, unlike any, you cannot access any properties on values with the type unknown, nor can you call/construct them. Furthermore, values of type unknown can only be assigned to unknown or any.

So for the assertion parameters, it will work the same as `any`. It's mostly just for consistency, however, had AVA been written in TS, we could have benefitted from the strictness when handling the assertion parameters internally.

For return values, it forces the user to cast it to a proper value, which is good.

**Comment by sindresorhus** [comment]
Actually, looking at the type definition in more detail now, I see that there are no `any` being returned. I was sure there was. Maybe there was before 1.0.

**Comment by sindresorhus** [comment]
> I still think `any` is more self-documenting for those calling our assertions than `unknown` would be.

How so?

**Comment by sindresorhus** [comment]
And `unknown` means that too. But doesn't matter.

**Comment by novemberborn** [comment]
@sindresorhus I still don't agree this change is necessary, but now would be the time.

**Comment by sindresorhus** [comment]
Closing. It's not important. Just would be nice with consistency. It wouldn't change the behavior at all anyway.
