### ISSUE TITLE
Tests consuming really large memory

### ISSUE THREAD

**Issue by be5invis** [avajs/ava#2033]
Hi all. In one of my internal projects I have stress test cases that takes around 3GB each. Therefore what is the best practice to arrange them? Other cases are small so I want the others to be parallel, but the large tests should run in serial or use some sort of locks to limit their parallelism.

**Comment by novemberborn** [comment]
You're probably best off running AVA twice, e.g. in the npm scripts:

```json
{
  "test:parallel": "ava test/parallel/**/*.js",
  "test:stress": "ava test/stress/**/*.js",
  "test": "npm run -s test:parallel && npm run -s test:stress"
}
```

It's not great because you get two sets of results, but it'll work in CI where you just want all tests to pass anyway.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
