### ISSUE TITLE
Support for mocking / ignoring non-js modules

### ISSUE THREAD

**Issue by fotonmoton** [avajs/ava#2038]
## Description

I try to test React component with Enzyme and have some issues. 
To bundle my project  I use Webpack and css and file loaders to handle non-js modules.
In test environment css and file modules can be ignored, but I don't find any examples in docs how to mock or ignore specific types of modules.

### Source

```js
import React from 'react';
import { hot } from 'react-hot-loader/root';

// uncomment this modules to get error
// import './App.css';
// import kitten from './kitten.jpg';

const App = () => (
  <div className="App">
    <p>Hello from React!</p>
    {/* <img src={kitten} alt="" /> */}
  </div>
);

export default hot(App);
```

### Test Source

```js
test('App should render text', (t) => {
  const wrapper = mount(<App />);
  t.is(wrapper.find('p').text(), 'Hello from React!');
});
```

### Error Message & Stack Trace

```
  /tmp/react_webpack_template/src/components/App.css:3
  #root
  ^

  SyntaxError: Invalid or unexpected token

```

```
  /tmp/react_webpack_template/src/components/kitten.jpg:1
  (function (exports, require, module, __filename, __dirname) { ����
                                                                ^

  SyntaxError: Invalid or unexpected token

```

### Config

```js
export default {
  files: [
    'src/**/*spec.{js,jsx}',
  ],
  sources: [
    'src/**/*.{js,jsx}',
  ],
  cache: true,
  concurrency: 5,
  failFast: true,
  failWithoutAssertions: true,
  verbose: false,
  compileEnhancements: false,
  require: [
    './config/jsdom.setup.js',
    '@babel/register',
  ],
  babel: {
    extensions: ['jsx'],
  },
};
```

### Command-Line Arguments

```
ava
```

## Relevant Links

https://github.com/fotonmoton/ava_ignore_modules
uncomment modules imports in App.jsx to fail test.

## Environment

```
Node.js v10.15.0
linux 4.15.0-45-generic
ava 1.2.1
npm 6.4.1
yarn 1.12.3
```

**Comment by novemberborn** [comment]
You should use a Babel plugin to rewrite those imports, so that Node.js doesn't try to import them as if they were JavaScript. I don't have the right plugin handy for you though.

Alternatively you could try and run your Webpack bundle within AVA but I'm not quite sure how to go about that either.

If anybody has tackled this before, it'd be great to update the documentation to solve this problem.

**Comment by fotonmoton** [comment]
@novemberborn I found workaround. After requiring `@babel/register` you can set 
```
require.extensions['css'] = () => {}
require.extensions['jpg'] = () => {}
```
and this imports will return nothing.
ava.config.js:
```js
export default {
  files: [
    'src/**/*spec.{js,jsx}',
  ],
  sources: [
    'src/**/*.{js,jsx}',
  ],
  cache: true,
  concurrency: 5,
  failFast: true,
  failWithoutAssertions: true,
  verbose: false,
  compileEnhancements: false,
  require: [
    './config/jsdom.setup.js',
    './config/babel.register.js',
  ],
  babel: {
    extensions: ['jsx'],
  },
};
```
./config/babel.register.js:
```
require('@babel/register');

require.extensions['.css'] = () => {};
require.extensions['.jpg'] = () => {};
```
Full code on branch `solution` in this [repo](https://github.com/fotonmoton/ava_ignore_modules).

I think this should be somewhere in docs, or better add support for something like `ignoreExtensions` to configuration so that AVAs internal babel pipeline can ignore some modules (because this solution works only with `@babel/register`).

**Comment by novemberborn** [comment]
> I think this should be somewhere in docs, or better add support for something like `ignoreExtensions` to configuration so that AVAs internal babel pipeline can ignore some modules (because this solution works only with `@babel/register`).

AVA doesn't follow your imports, it just rewrites them to `require()` calls. Node.js then loads the files and assumes they're JavaScript.

**Comment by fotonmoton** [comment]
So if I don't use `@babel/register` I can't rewrite `require()` calls for specific modules? How I can solve this problem without compiling sources on the fly then? Solution above works for me well but, I think, there should be less "hacky" way. Or maybe importing non-js modules is not a good way to compose React components and this problem can be solved outside AVAs context?

**Comment by novemberborn** [comment]
Your code, as written, assumes a Webpack build step. If you want it to work in Node.js you'll need to adjust your approach. Pre-compiling using Babel, or `@babel/register`, or perhaps you can test your Webpack bundle itself.

**Comment by fotonmoton** [comment]
Yeah, I see argument behind testing final bundle itself - it will contain "final" version of sources and tests for compiled modules will be less "flaky" in some edge cases. I will try to setup Webpack to produce compiled componets and test them instead of compiling on the fly.

**Comment by fotonmoton** [comment]
I think title is misleading, I wrote about module imports inside sources not tests, but I don't know how describe problem more precisely.

**Comment by novemberborn** [comment]
I think the title is fine 😄

**Comment by tsaitsau** [comment]
Oh thx

Mark Wubben <notifications@github.com>於 2019年2月14日 週四，下午4:13寫道：

**Comment by 3cp** [comment]
> `require.extensions['css'] = () => {}`

> `require.extensions['.css'] = () => {};`

Pls fix a small typo. Your first sample code is incorrect, while the other sample code is correct. This workaround should be a good addition to the doc.

**Comment by novemberborn** [comment]
@3cp I don't think we've properly documented this at all. Would you be interested in converting this approach to a recipe?

**Comment by richardeschloss** [comment]
FWIW, if anyone is coming to this issue in 2021 and looking for a full ESM / babel-less solution (i.e., with `require.extensions` deprecated), here's an alternative solution that works for me: 

1. Define a node-based css loader: 
`./cssLoader.js`
```js
import { URL, pathToFileURL } from 'url';

const baseURL = pathToFileURL(`${process.cwd()}/`).href;

export function resolve(specifier, context, defaultResolve) {
  const { parentURL = baseURL } = context;
  if (specifier.endsWith('.css')) {
    return {
      url:  new URL(specifier, parentURL).href
    };
  }

  // Let Node.js handle all other specifiers.
  return defaultResolve(specifier, context, defaultResolve);
}

export function getFormat(url, context, defaultGetFormat) {
  // This loader assumes all network-provided JavaScript is ES module code.
  if (url.endsWith('.css')) {
    return {
      format: 'module'
    };
  }

  // Let Node.js handle all other URLs.
  return defaultGetFormat(url, context, defaultGetFormat);
}

export function transformSource(source, context, defaultGetSource) {
  const { url } = context;
  if (url.endsWith('.css')) { // for files that import css... (i.e., import 'someFile.css'), just empty it out for testing...
    return {
      source: '' // empty source... 
    }
  }
  
  // Let Node.js handle all other URLs.
  return defaultGetSource(source, context, defaultGetSource);
}
```

2. Specify the loader in the ava config, supplying it as one of the `nodeArguments`:
`./ava.config.js`
```js
export default {
  nodeArguments: [
    '--experimental-loader=./cssLoader.js',
    '--no-warnings', // supplied to suppress Node's warning about using experimental loaders...
  ],
  // ...
}
```
