### ISSUE TITLE
The `fake-tty.js` implementation should shim all the methods

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#2041]
AVA [fakes TTY](https://github.com/avajs/ava/blob/7b6e578dce32a6561e61ed6e2be6de8237b37800/lib/worker/fake-tty.js), but it doesn't implement all the methods. This can cause packages to crash because when `.isTTY === true`, they expect to be able to use certain methods.

Related issue: https://github.com/avajs/ava/pull/1885

Missing methods:

- `.clearLine(dir)`
- `.clearScreenDown()`
- `.cursorTo(x, y)`
- `.getWindowSize()`
- `.moveCursor(dx, dy)`

More info: https://nodejs.org/api/tty.html#tty_writestream_clearline_dir

---

I got the following crash with AVA 1.2.1:

```
  Uncaught exception in test/api.js

  /Users/sindresorhus/dev/oss/awesome-lint/node_modules/ora/index.js:116

  TypeError: this.stream.clearLine is not a function

  Ora.clear (node_modules/ora/index.js:116:16)
  Ora.render (node_modules/ora/index.js:126:8)
```

**Comment by tsaitsau** [comment]
Bug

**Comment by novemberborn** [comment]
Would we shim these as no-ops?

**Comment by sindresorhus** [comment]
Well, would be nice if they actually did what they should. It's not hard to shim them. Can use https://github.com/sindresorhus/ansi-escapes for everything except for `.getWindowSize()`, which can just return `[80, 24]`.

**Comment by okyantoro** [comment]
Hello @novemberborn 

Can I work on this?

**Comment by novemberborn** [comment]
Yes please, @okyantoro!
