### ISSUE TITLE
[FEATURE REQUEST] simplification for file extension configuring

### ISSUE THREAD

**Issue by fotonmoton** [avajs/ava#2043]
## Description
Feature request: Simplify file extensions configuration.
Configuration must be changed in three places if you want to test files and sources with different extensions:

in `files` array:
```js
  files: [
    'src/**/*spec.{js,jsx,ts,tsx}',
  ],
```

in `babel.extensions`:
```js
babel: {
    extensions: [
      'js',
      'jsx',
      'ts',
      'tsx',
    ],
  },
```

and if you use `@babel/register` for compiling on the fly you should add configurations for it as well:
```js
require('@babel/register')({
  extensions: [
    '.js',
    '.jsx',
    '.ts',
    '.tsx',
  ],
});
```
Change in `@babel/register` configuration must be done in any way because it outside of the AVAs scope. But I don't understand why I should specify extensions in two places in same config? Moreover, in some places extension must be with dot in some doesn't. 

### Error Message & Stack Trace

if I remove extension from `files` array or from `babel.extensions` I've got:
```
$ yarn test
yarn run v1.13.0
$ ava

  ✖ Couldn't find any files to test

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Config

ava.config.js
```js
export default {
  files: [
    'src/**/*spec.{js,jsx,ts,tsx}',
  ],
  sources: [
    'src/**/*.{js,jsx,ts,tsx}',
  ],
  cache: true,
  concurrency: 5,
  failFast: true,
  failWithoutAssertions: true,
  verbose: false,
  compileEnhancements: false,
  require: [
    './config/jsdom.setup.js',
    './config/babel.register.js',
  ],
  babel: {
    extensions: [
      'js',
      'jsx',
      'ts',
      'tsx',
    ],
  },
};
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava
```

## Relevant Links

[Repo](https://github.com/fotonmoton/ava_file_extension_configuration) with example config.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v10.15.1
linux 4.15.0-45-generic
ava: 1.2.1
npm: 6.4.1
yarn: 1.13.0
```

**Comment by novemberborn** [comment]
Yea that does look cumbersome.

I'm pretty sure we do take `babel.extensions` into account when looking for files, however you have custom patterns for the test files. I can't really think of a reason we shouldn't also look for `.spec.js` files. @sindresorhus?

I think you should also be able to specify `src/` as the source pattern and AVA should select all files with the right extensions within. Or if it doesn't work that way then it should.

I hadn't realized `@babel/register` required the dots. I wonder if in hindsight that would have been a better choice. I'm reluctant to support both but we can change over in the next major version. @sindresorhus?

**Comment by sindresorhus** [comment]
> I can't really think of a reason we shouldn't also look for .spec.js files. @sindresorhus?

I guess.

> I think you should also be able to specify src/ as the source pattern and AVA should select all files with the right extensions within. Or if it doesn't work that way then it should.

Note that the latest AVA beta release moves to not to support a directory input for test files: https://github.com/avajs/ava/releases/tag/v2.0.0-beta.1

> I wonder if in hindsight that would have been a better choice. I'm reluctant to support both but we can change over in the next major version. 

I don't see the point in requiring the dot. Why would it have been a better choice?

**Comment by sindresorhus** [comment]
To address the actual issue, this would IMHO be better solved by moving to transpile everything and add first-class TypeScript support. Then none of this config would be needed in the first place.

**Comment by novemberborn** [comment]
With 2.0 you can select all files, and AVA will filter down to the ones for which an extension is configured.

> > I wonder if in hindsight that would have been a better choice. I'm reluctant to support both but we can change over in the next major version.
> 
> I don't see the point in requiring the dot. Why would it have been a better choice?

Yea I don't know. Compatibility, I guess.

@sindresorhus are we agreed to add `.spec.js` to the patterns? It could be considered a breaking change so now's the right time to do it.

**Comment by sindresorhus** [comment]
> @sindresorhus are we agreed to add .spec.js to the patterns? It could be considered a breaking change so now's the right time to do it.

👍 Yes, it's a common pattern.

**Comment by novemberborn** [comment]
OK I've opened a PR for selecting `spec.js` files. I think that addresses everything raised in this issue so far.

I'm closing this issue for housekeeping purposes, but let's keep the conversation going.
