### ISSUE TITLE
redirect unit tests

### ISSUE THREAD

**Issue by scheung38** [avajs/ava#2044]
How to test in a scenario where there is redirect, i.e the first statusCode being a 302, and then followed by 200? 

```
  t.is(res.statusCode, 200) // or 302?
  t.deepEqual(res.result, expectedResponse)
```
am I looking for response before or after the redirect happens? 
 
## Environment
 
```
Mac OSX - 10.14.2
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
node --version - v11.6.0
ava --version - 1.0.1
npm --version - 6.5.0-next.0

```

**Comment by novemberborn** [comment]
It seems odd to test for either result. Ideally you have one test for a 200 response, and another for a 302 response.

If you do have such variability in your test, I would use `t.true(res.statusCode === 200 || res.statusCode === 302)`. And perhaps an `if () {}` condition before comparing the result.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by MrXploder** [comment]
@novemberborn can you give me some advices. I'm using Avajs in my Nuxtjs application and I need to run some test on my "pages components" but my application uses passportjs (for authenication purposes) so, when I try to render index, or any other "page component" route I get redirected to my OIDC provider for authentication.

There is a way to "surpass" or even manually enter user/password for that external service and then procceede to the page I want to test (?)

**Comment by novemberborn** [comment]
@MrXploder sorry, that's rather specific to your use case and not AVA itself. This is probably better asked on https://spectrum.chat/ava?tab=posts or https://stackoverflow.com/questions/tagged/ava.
