### ISSUE TITLE
Update dependency tracking after modules are loaded from AVA's "require" configuration

### ISSUE THREAD

**Issue by lo1tuma** [avajs/ava#2049]
See next steps at https://github.com/avajs/ava/issues/2049#issuecomment-469029767.

Original issue description follows.

---

According to the [watch-mode documentation](https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#dependency-tracking) dependency tracking should work when custom extensions/transpilers are configured directly in `ava.config.js` or in the package.json. The linked documentation (06-configuration.md) doesn’t really explain how this should be done. In the [babel recipe](https://github.com/avajs/ava/blob/master/docs/recipes/babel.md) however it is explained how to utilize babel transpiling for source files, the recommendation is to use the `require` option to load e.g. `@babel/register`. The problem with that is, that dependency tracking is [installed **before**](https://github.com/avajs/ava/blob/7d10446e91706e65e5fc6b6286b2279c29ef9615/lib/worker/subprocess.js#L104-L106) the `require` option is executed.

I followed the instructions in the babel recipe to transpile typescript source files with `@babel/register` and `@babel/preset-typescript` via the ava `require` option. Since the dependency tracking is installed before this step, it is unaware of the additional file extensions like `ts` and `tsx` that `@babel/register` adds.

I’m a little bit confused right now, because the documentation says it should work somehow, but it doesn’t explain how.

**Comment by fotonmoton** [comment]
You can check out [this](https://github.com/avajs/ava/issues/2043) issue, I have same frustration. Here working [repo](https://github.com/fotonmoton/ava_file_extension_configuration) with TypeScript support for AVA.

**Comment by novemberborn** [comment]
Nice find @lo1tuma!

You're right, the dependency tracker works by decorating the functions in `require.extensions`. Thus, it misses any additional functions added when AVA loads the modules from its `require` configuration.

What we should do is after each module is loaded, go through `require.extensions` again to decorate any now undecorated functions. That way we can track most of the dependencies.

**Comment by novemberborn** [comment]
See these lines which installs the tracker for the first time:

https://github.com/avajs/ava/blob/334e15b4af06492c9aed2800a0764f245d6a908b/lib/worker/subprocess.js#L104:L107

Note that the comment applies to `precompilerHook.install()`.

Then, the module is loaded here:

https://github.com/avajs/ava/blob/334e15b4af06492c9aed2800a0764f245d6a908b/lib/worker/subprocess.js#L111
