### ISSUE TITLE
Don't report filtered tests as pending

### ISSUE THREAD

**Issue by acchou** [avajs/ava#2055]
## Description

When tests fail when using a `-m` title matching filter, Ava says that some tests are pending, even if they are not matched. For example:

```
$ ava --concurrency=8 --timeout=2m -m='!remote*' -m='*aws*'
...
✖ Timed out while running tests
 5 tests were pending in [...]build/test/basic.test.js
 ◌ basic › remote aws basic calls { mode: 'queue', childProcess: true }
 ◌ basic › remote google basic calls { mode: 'https', childProcess: false }
 ◌ basic › remote google basic calls { mode: 'https', childProcess: true }
 ◌ basic › remote google basic calls { mode: 'queue', childProcess: false }
 ◌ basic › remote google basic calls { mode: 'queue', childProcess: true }

```

The match criteria is the union of all non-remote tests with all tests matching `*aws*`. The tests matching `remote google` should be filtered out (and indeed are not executed), however they are reported as pending. This is confusing because:

(1) It's hard to tell which test timed out, especially if there are many tests being filtered out.
(2) It makes it seem that the matching filter isn't working even though it is.

Proposed behavior: filter the pending test report before printing, so the output above would be:

```
✖ Timed out while running tests
 1 tests were pending in [...]build/test/basic.test.js
 ◌ basic › remote aws basic calls { mode: 'queue', childProcess: true }
```

This would pinpoint the test that is actually timing out.

### Config

Copy the relevant section from `package.json`:

```json
{
 "ava": {
        "files": [
            "build/test/*.test.js"
        ]
    }
}
```

### Command-Line Arguments

```
$ ava --concurrency=8 --timeout=2m -m='!remote*' -m='*aws*'
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v8.14.0
darwin 18.2.0
$ ava --version
1.2.1
$ npm --version
6.4.1
```

**Comment by novemberborn** [comment]
This looks like a bug to me.

I think this line: https://github.com/avajs/ava/blame/d97f11ddbbf824fd72165266770b9ae046e62324/lib/run-status.js#L62

Should be moved to this `else` branch:

https://github.com/avajs/ava/blame/d97f11ddbbf824fd72165266770b9ae046e62324/lib/run-status.js#L86

**Comment by vancouverwill** [comment]
I can take a look, why I'll I'm at it I wouldn't mind adding the pending tests line `writePendingTests()` to tap as it is pretty major feature not to show as the main goal of a test suite is to show the tests which have not passed.

What do you think @novemberborn ?

**Comment by novemberborn** [comment]
> I can take a look

@vancouverwill great!



> I wouldn't mind adding the pending tests line `writePendingTests()` to tap as it is pretty major feature not to show as the main goal of a test suite is to show the tests which have not passed.

Sure, if you think that's useful. Note that this is only used when a timeout occurs or if you interrupt the test run. You may have to update the reporter code as well. Is there a good way of expressing that in TAP? (This is probably best as a separate PR.)

**Comment by vancouverwill** [comment]
yeah good call about separate pr 👍
