### ISSUE TITLE
[Feature request] Custom ava.config.js location

### ISSUE THREAD

**Issue by ehmicky** [avajs/ava#2058]
## Description (in short)

A `--config` CLI flag to specify a custom location for `ava.config.js` would be useful.

## Description (in more details)

My goal is to share my Ava setup across many repositories, both the invocation and the configuration.

My current setup is the following:
  - one shared repository called `gulp-shared-tasks`:
     - at its root is the shared `ava.config.js`
     - at its root is also a shared `gulpfile.js` that defines a Gulp task that just calls `ava`
  - each repository then:
     - defines an `ava.config.js` which simply re-use the shared config:

```js
import config from 'gulp-shared-tasks/ava.config.js'
export default config
``` 

and defines a `gulpfile.js` which simply re-uses the shared Gulp tasks:

```js
module.exports = require('gulp-shared-tasks/gulpfile.js')
```

Like this I can change my Gulp or ava setup in a single repository.

This works. However if I could do `ava --config path/to/shared/ava.config.js` inside my `gulp-shared-tasks` repository, I would not have to define any `ava.config.js` in any other repository, which would be even simpler.

At the moment Ava looks up `ava.config.js` based on the current directory, which won't work for my specific setup. Changing the current directory is not an option either as it impacts other tools, e.g. when running `nyc ava`, since `nyc` relies on the current directory for several things. 

## Environment

```
Node.js v11.10.1
linux 4.18.0-15-generic
1.2.1 (ava)
6.8.0 (npm)
```

**Comment by novemberborn** [comment]
Yup, see https://github.com/avajs/ava/issues/1857.

Re-reading that issue I see that my questions in https://github.com/avajs/ava/issues/1857#issuecomment-402513251 have been resolved (https://github.com/avajs/ava/issues/1857#issuecomment-405091537), so it's ready to be worked on.

**Comment by ehmicky** [comment]
Sorry! I did search the issues twice but I must have used the wrong keywords. Thanks for the quick reply.

**Comment by ehmicky** [comment]
Actually the solution outlined in #1857 might not work for my use case because the `package.json` is looked up based on the current directory :/

**Comment by novemberborn** [comment]
No it still allows `--config`, it's just that it *also* allows `package.json#ava.config`. (Happy to accept a PR just for the CLI flag, by the way.)

**Comment by ehmicky** [comment]
Oh great then! From [this comment](https://github.com/avajs/ava/issues/1857#issuecomment-405091537):

> Having to specify the --config argument would be bothersome. So I'm 👍 on a package.json#ava.config option

I thought the `--config` CLI option was not part of the solution, but if it is then this completely solves this issue.
