### ISSUE TITLE
docs: requesting thorough helper documentation

### ISSUE THREAD

**Issue by shellscape** [avajs/ava#2066]
## Description

I'd like to request some more thorough documentation around helpers. Helpers can be extremely powerful, yet they have received very little attention in the documentation. For example, see: https://github.com/avajs/ava/blob/master/docs/recipes/puppeteer.md. This document mentions using a helper to wrap and return a function to the test which has an additional parameter, but the doc (nor any other docs) go into detail about what magic this is, nor how it works. Unfortunately the code is a bit cryptic from `index.js` to where this functionality is actually defined, and I failed to find it on my first attempt. Additionally, this doc requires that a user extrapolate what the `withPage` function exports, and how we get from that helper to the `(t, page) =>` function. Certainly not a stretch for a lightly seasoned developer, but not exactly new-user friendly either.

The [browser testing](https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md) recipe (as well as the Vue and React recipes) have a completely different flavor of "helper," one that is loaded by configuration. The differences between the two uses of "helper," or the distinction between the functionality in the two, is never laid out in the docs for users.

In the [writing tests](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md) file, helpers are only mentioned in the context of accessing metadata about the current test.

All in all, I believe that helper documentation is a glaring hole in the documentation for Ava. For what it's worth, I opened this after a potential contributor (who is a fairly solid dev) to one of my projects attempted to make sense of the puppeteer setup in our tests, and was absolutely baffled as to "what magic" was going on. 

### Test Source

n/a

### Error Message & Stack Trace

n/a

### Config

n/a

### Command-Line Arguments

n/a

## Relevant Links

- https://github.com/avajs/ava/blob/master/docs/recipes/puppeteer.md
- https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md
- https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md

## Environment

n/a

**Comment by novemberborn** [comment]
Yes this is most definitely welcome!
