### ISSUE TITLE
Debug AVA with VS Code into a Lerna project

### ISSUE THREAD

**Issue by skycult** [avajs/ava#2072]
Thank you for your awesome test runner! I've only a problem using a Lerna monorepo. I use `lerna bootstrap --hoist` to avoid a lot of duplicated modules into every single project inside the monorepo. If I try to debug a test using VSCode configured following your [guide](https://github.com/avajs/ava/blob/master/docs/recipes/debugging-with-vscode.md), I'm not able to debug because the program `${workspaceFolder}/node_modules/ava/profile.js` is outside the workspace.
There is some workaround or another VSCode config to do this?
Thank you!

**Comment by novemberborn** [comment]
I think it should work if you change that value so that it points at your actual AVA installation.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by skycult** [comment]
Yes I solved putting the AVA absolute path.
Thank you
