### ISSUE TITLE
Bind JSON built-ins to allow stubbing

### ISSUE THREAD

**Issue by mihai-dinu** [avajs/ava#2081]
**See conclusion here: https://github.com/avajs/ava/issues/2081#issuecomment-489430603**

---

## Description

Running a simple test where I'm stubbing the `JSON.parse()` function to return a specific output. In case a failure occurs, ava outputs a "Test failure: Could not serialize error" and then hangs. Same hang appears even if a test passes, but I don't call `sinon.restore()`.

### Test Source

```js
import test from 'ava'
import * as sinon from 'sinon'

let sandbox: sinon.SinonSandbox

test.beforeEach(() => {
    sandbox = sinon.createSandbox()
})

test.afterEach(() => {
    sandbox.restore()
})

test('getServerPort', (t) => {
    let parse = sandbox.stub(JSON, 'parse')
    parse.returns({})
    t.is(3,4)
})
```

### Error Message & Stack Trace

```
▶ npm run test
> ava build/tests/lib/*.js --verbose

  ✖ getServerPort Test failure: Could not serialize error
^C
  ✖ Exiting due to SIGINT

  1 test failed

  getServerPort


  Test failure: Could not serialize error

  Error: Test failure: Could not serialize error
      at serializeError (/home/mihai/workspace/github/sherry/node_modules/ava/lib/serialize-error.js:143:23)
      at runSingle.then.result (/home/mihai/workspace/github/sherry/node_modules/ava/lib/runner.js:337:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Config
Nothing configured for ava. Just transpiling some TS files and then running ava for the js files

### Command-Line Arguments
```
  "scripts": {
    "test": "ava build/tests/lib/*.js --verbose",
    "prepare": "tsc"
  }
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v10.15.1
Ubuntu 18.04
Kernel: linux 4.18.0-16-generic
ava v1.4.0
npm v6.4.1
```

**Comment by sindresorhus** [comment]
We should probably do the same as we do with timers and save a reference to the JSON.parse/stringify functions.

https://github.com/avajs/ava/blob/master/lib/now-and-timers.js

**Comment by novemberborn** [comment]
> We should probably do the same as we do with timers and save a reference to the JSON.parse/stringify functions.

I'm not so sure. Faking timers isn't great but sometimes unavoidable. Stubbing `JSON.parse()` feels like it's going too far.

**Comment by sindresorhus** [comment]
> Stubbing JSON.parse() feels like it's going too far.

AVA is for testing stuff though. Sometimes stubbing is the only way to test something. Preferably, AVA should gracefully handle any global property being stubbed.

**Comment by mihai-dinu** [comment]
I was able to stub JSON.parse() using `jest`, so this problem arose when I was trying to move to `ava`. 

The more concrete scenario that I have is that I am reading a config file from disk that is stored in json format. So I have a something like this:


```javascript
// moduleA.js

function readConfigFile(filePath) {
    const fileContent = fs.readFileSync(filePath)
    const json = JSON.parse(fileContent)
    return json
}

export function getPropFromConfigFile(prop) {
    // init prop with default value
    // call my readConfigFile function
    // return the default if prop not in json
}
```

Now, I want to test `getPropFromConfigFile` without having to export `readConfigFile` since that's only used in the above exported function. That's why I wanted to stub `JSON.parse()`.

**Comment by novemberborn** [comment]
> AVA is for testing stuff though. Sometimes stubbing is the only way to test something. Preferably, AVA should gracefully handle any global property being stubbed.

OK. Let's change `now-and-timers` to `bound-builtins`:

* Re-export `timers`
* Export `now` from `Date.now`
* Export a `JSON` object with bound `parse` and `stringify` methods

**Comment by mihai-dinu** [comment]
I can take a swing at making the changes you've mentioned - doesn't seem to be too difficult.

**Comment by novemberborn** [comment]
As discussed in https://github.com/avajs/ava/pull/2117#issuecomment-491607970 we're not sure how to deal with this. Closing, but please comment if you have a solution.
