### ISSUE TITLE
TypeScript defintions are missing the .assert() assertion

### ISSUE THREAD

**Issue by vogre** [avajs/ava#2082]
## Description

The TypeScript definitions file is missing the 1.4.0 (power-assert) `assert` assertion:

### Test Source

```typescript
test('hello', async t => {
  t.assert(true);
});
```

### Error Message

```
typescript:Error:2339:Property 'assert' does not exist on type 'ExecutionContext<{}>'.
```

## Environment

ava version 1.4.0

**Comment by novemberborn** [comment]
Oops, here I was feeling happy about remembering to update our ESLint rules! 😊

**Comment by novemberborn** [comment]
Out as 1.4.1.
