### ISSUE TITLE
Replacement for toHaveBeenCalledWith

### ISSUE THREAD

**Issue by mesqueeb** [avajs/ava#2087]
I need to check if some mocked functions have been called with certain params.
In Jest I could use [toHaveBeenCalledWith](https://jestjs.io/docs/en/expect#tohavebeencalledwitharg1-arg2-). Is there anything close to this in AVA?

**Comment by novemberborn** [comment]
Hi @mesqueeb. AVA doesn't come with any mocking utilities. I'm partial to https://github.com/testdouble/testdouble.js/. https://sinonjs.org is nice too.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
