### ISSUE TITLE
Internal error after git submodule add babel repository

### ISSUE THREAD

**Issue by teramotodaiki** [avajs/ava#2091]
## Description

After added babel as a submodule into my project, AVA throws an Internal error.

- git init
- npm init
- npm i -D ava
- git submodule add https://github.com/babel/babel.git
- npx ava →Internal error

### Test Source

Here is a tiny repository to reproduce above error.
https://github.com/teramotodaiki/ava-git-submodule-error

### Error Message & Stack Trace

```
  ✖ Internal error
  SyntaxError: /home/travis/build/teramotodaiki/ava-git-submodule-error/babel/packages/babel-helpers/test/helpers/define-helper.js: Unexpected token, expected "," (11:5)
  
     9 | 
    10 | export default function defineHelper(
  > 11 |   dir: string,
       |      ^
    12 |   name: string,
    13 |   code: string,
    14 | ): string {
```

More detail is here: https://travis-ci.org/teramotodaiki/ava-git-submodule-error/builds/520791119 

### Config

No configuration.

### Command-Line Arguments

No arguments.

## Relevant Links

- Please see above GitHub and Travis CI link.

## Environment

My local PC is:
```
Node.js v11.13.0
darwin 18.5.0
ava 1.4.1
npm 6.9.0
```

**Comment by novemberborn** [comment]
AVA is trying to execute the test files inside the Babel submodule. That doesn't work because they're written with Flow, and not meant for AVA anyhow. Update the `files` option to only select tests inside the `test` directory, e.g. `test/**/*.js`.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by teramotodaiki** [comment]
Thank you for answering. I have change configuration into some patterns, but same error was thrown. :(

1. Write only `test` directory
```
"ava": {
    "files": [
      "test/**/*"
    ]
  }
```

Actual commit: https://github.com/teramotodaiki/ava-git-submodule-error/commit/07dbe64d575c602ab1bff449a66109251b42a785

But same error was thrown.
https://travis-ci.org/teramotodaiki/ava-git-submodule-error/builds/522160851

2. Disable `babel` directory
```
"ava": {
    "files": [
      "test/**/*",
      "!babel/**/*"
    ]
  }
```

Actual commit: https://github.com/teramotodaiki/ava-git-submodule-error/commit/bd01e90e8dc24f2d920de42a281a5e4be6a9eddc

Also same error was thrown.
https://travis-ci.org/teramotodaiki/ava-git-submodule-error/builds/522162788

If it ends with extension `.js`, it throws same error. https://travis-ci.org/teramotodaiki/ava-git-submodule-error

I'm going to use ava locally to test them when I have time. I know that this issue is very specific case... 😅
