### ISSUE TITLE
Support `helpers` globs

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2105]
#2103 removes AVA's support for finding helper files inside `helpers` directories. Instead we'll support this by letting users specify glob patterns to find helpers:

* Implement `helpers` configuration. If specified, it must be an array containing at least one pattern
* Any test files matched by `helpers` patterns must be treated as helpers
* Watch mode must ensure that helpers are treated as sources, not tests
* If the Babel pipeline is disabled (`babel: false` and `compileEnhancements: false`), optimize by not finding helpers: just make sure test files that match the helper patterns are not treated as tests
* The documentation needs updating

**Comment by coreyfarrell** [comment]
Do you plan to make the default helpers pattern be `['**/_*', '**/helpers/**']`?

Also is this a good place to query about the plans for `**/fixtures/**`?  The ability to put fixtures in `test/fixtures/` is useful because nyc already ignores `test/**`.

**Comment by novemberborn** [comment]
> Do you plan to make the default helpers pattern be `['**/_*', '**/helpers/**']`?

No. By default, the only helper files are those matched by the test file patterns that start with an underscore. Given how test file extensions can be configured, it's too confusing to have default `helpers` patterns. And it's been causing performance issues for users who don't use helpers but have large repositories.



> Also is this a good place to query about the plans for `**/fixtures/**`? The ability to put fixtures in `test/fixtures/` is useful because nyc already ignores `test/**`.

Ah I forgot to note that in the release. These files are no longer ignored, and will now be treated as test files. You'll have to exclude them in `files`.
