### ISSUE TITLE
Display internal Node.js stacktrace if no user stacktrace is present

### ISSUE THREAD

**Issue by szmarczak** [avajs/ava#2110]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/avajs/ava/issues/2110)

### Current behavior

![image](https://user-images.githubusercontent.com/36894700/56914132-a0bde300-6ab3-11e9-8260-7c3530dc407f.png)

## Expected behavior

```js
{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1177:34)
    at TLSSocket.emit (events.js:193:13)
    at TLSSocket._finishInit (_tls_wrap.js:668:8) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Submitted pull Requests
- [#2420 Show node internal stack trace](https://issuehunt.io/r/avajs/ava/pull/2420)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/ava/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
Makes sense to me.

I also notice we don't show the `.code` property. We should show that if it's not empty, no matter what.

**Comment by szmarczak** [comment]
It should also display `No user stacktrace present.` IMHO

**Comment by novemberborn** [comment]
It's a little jarring when there is no stack trace. But, if the Node.js trace lines are useful here, why wouldn't they be useful in other situations?

Should we perhaps color code the trace lines but not filter any?

Agreed we should show all properties of the error.

**Comment by sindresorhus** [comment]
It's the difference between the error originating from your own code or from Node.js itself. If it originates from your own code, you don't really care or want the Node.js code frames, but if the error originates from Node.js, you definitely want them for context or being able to report it to the Node.js team.
