### ISSUE TITLE
Cannot find module xxx/*.png

### ISSUE THREAD

**Issue by Gaetan-dc** [avajs/ava#2122]
## Description

Hello,

I have a solution which uses Parcel and runs correctly. I want to implement Ava for testing, however I run into this error : Error: Cannot find module '../../images/modules/*.png'
I have tried a lot of tricks about esm/babel from the documentation but I just can't get it to work. I know my way around javascript but I'm pretty new to the whole npm pipeline.

### Test Source
In my real code I import one of my own modules, which has the import line "import Images from "../../images/*.png";". However you can very simply reproduce the issue by putting the import directly in the test file (and yes, the relative paths are correct, and my module runs fine with Parcel).

```js
import test from 'ava';
import Images from "../images/*.png";

test('my passing test', t => {
    t.pass();
});
```

### Error Message & Stack Trace

```
 Uncaught exception in tests\test.js

  Error: Cannot find module '../images/modules/*.png'
  Require stack:
  - C:\Private\GitHub\Tangible-Grid\tests\test.js
  - C:\Private\GitHub\Tangible-Grid\node_modules\ava\lib\worker\subprocess.js

  × tests\test.js exited with a non-zero exit code: 1

  1 uncaught exception
```

### Config
```json
{
  "ava": {
    "require": "esm",
    "babel": false,
    "compileEnhancements": false,
    "files": "tests/**",
    "sources": [
      "javascript"
    ],
    "verbose": true
  },
  "scripts": {
    "test": "ava",
    "dev": "parcel index.html",
    "build": "parcel build index.html"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/register": "^7.4.4",
    "ava": "^1.4.1",
    "cssnano": "^4.1.10",
    "esm": "^3.2.22"
  }
}

```

### Command-Line Arguments
```
npm test
```

## Environment
```
Node.js v12.2.0
win32 10.0.17134
ava 6.9.0
```

**Comment by sindresorhus** [comment]
This is a non-standard import specifier `../images/modules/*.png`. You need to specify the appropriate Babel plugins in the AVA config that can handle importing  images and using globs.

**Comment by Gaetan-dc** [comment]
Thanks, I tried installing babel-plugin-transform-assets-import-to-string and babel-plugin-import-glob (and adding them to the config), but couldn't get it to work either.

I was also wondering why it works with Parcel, so I read their docs a bit more and it turns out they use Babel with the @babel\preset-env to transpile : https://parceljs.org/javascript.html#default-babel-transforms
I tried using that preset in the ava babel config, but no luck : 
```
"ava": {
    "require": [
      "esm"
    ],
    "babel": {
      "testOptions": {
        "presets": [
          "@babel/preset-env"
        ]
      },
      "extensions": [
        "js",
        "mjs"
      ]
    },
    "files": "tests/**",
    "sources": [
      "javascript"
    ]
  }
```

**Comment by novemberborn** [comment]
`@babel/preset-env` won't make this work.

> I tried installing babel-plugin-transform-assets-import-to-string

Going by the name of that plugin, it sounds like you're on the right track.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by Gaetan-dc** [comment]
Still can't make it work. I have tried to reference [the Babel plugins that Parcel uses](https://www.npmjs.com/package/parcel-bundler?activeTab=dependencies), as well as some things from the ava documentation (register, polyfill), but no luck : 

```{
  "ava": {
    "require": [
      "@babel/register",
      "@babel/polyfill",
      "esm"
    ],
    "babel": {
      "testOptions": {
        "plugins": [
          [
            "babel-plugin-transform-assets-import-to-string",
            {
              "baseDir": "/images"
            }
          ],
          "@babel/plugin-transform-modules-commonjs",
          "@babel/plugin-transform-flow-strip-types",
          "@babel/plugin-transform-runtime",
          "@babel/plugin-syntax-export-namespace-from",
          "@babel/plugin-syntax-export-default-from"
        ],
        "presets": [
          "@babel/preset-env"
        ]
      },
      "extensions": [
        "js",
        "mjs"
      ]
    },
    "files": "tests/**",
    "sources": [
      "javascript",
      "images"
    ]
  },
  "scripts": {
    "test": "ava",
    "dev": "parcel index.html",
    "build": "parcel build index.html"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/plugin-syntax-export-default-from": "^7.2.0",
    "@babel/plugin-syntax-export-namespace-from": "^7.2.0",
    "@babel/plugin-transform-flow-strip-types": "^7.4.4",
    "@babel/plugin-transform-modules-commonjs": "^7.4.4",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@babel/register": "^7.4.4",
    "ava": "^1.4.1",
    "babel-plugin-transform-assets-import-to-string": "^1.2.0",
    "cssnano": "^4.1.10",
    "esm": "^3.2.22"
  },
  "dependencies": {
    "@babel/polyfill": "^7.4.4"
  }
}
```

**Comment by Gaetan-dc** [comment]
I even tried importing a single png file like this (in my test file) :
`import image from "../images/modules/2attcv.png";`

But then I get this error : 
`Error [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension: C:\Private\GitHub\MyProject\images\test.png`

I tried babel plugins such as "import-static-files" but nothing solves my issue.

**Comment by novemberborn** [comment]
Remember that `babel.testOptions` is only applied, by AVA, to your test files. `@babel/register` won't use that config. You may want to configure Babel itself using a `babel.config.js` file.

**Comment by Gaetan-dc** [comment]
I see. However the problematic line is actually inside my test file here. 
I'll try to see if I can configure Babel with babel.config.js, thanks.

**Comment by Gaetan-dc** [comment]
I have worked around the issue by accessing my images in another way : I have a static folder containing them, that is transported by the parcel plugin `parcel-plugin-static-files-copy` all the way to the destination folder. So now I can simply use a path to the images instead.
