### ISSUE TITLE
SyntaxError: Invalid or unexpected token: Symbol.iterator

### ISSUE THREAD

**Issue by industral** [avajs/ava#2127]
**package.json**

```json
{
  "type": "module",
  "devDependencies": {
     "esm": "^3.2.23"
  },
  "ava": {
    "require": [
      "esm"
    ]
  }
}
```

**index.spec.js**

```javascript
import test from 'ava';
import fetch from 'node-fetch';

console.log(fetch);

test('foo', t => {
  t.pass();
});

test('bar', async t => {
  const bar = Promise.resolve('bar');
  t.is(await bar, 'bar');
});
```

Running it, got an error:

```bash
$ npx ava tests/index.spec.js



  ✖ No tests found in tests/index.spec.js

  1 uncaught exception

  Uncaught exception in tests/index.spec.js


  <PATH_HERE>/node_modules/node-fetch/lib/index.js:899
  	[Symbol.iterator]() {
                    ^

  SyntaxError: Invalid or unexpected token
```

> Node.js v12.2.0
> darwin 18.5.0
> ava: 1.4.1
> npm: 6.9.0

**Comment by novemberborn** [comment]
There's an exception in `node_modules/node-fetch/lib/index.js`. I wouldn't have expected that with Node.js 12 though.

I see you're using `esm`. Perhaps try disabling AVA's transpilation of the `import` syntax: https://github.com/avajs/ava/blob/master/docs/recipes/babel.md#preserve-es-module-syntax. That's all I can think of, really.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
