### ISSUE TITLE
Feature request: dependencies between tests / partially ordered (serial) tests

### ISSUE THREAD

**Issue by futpib** [avajs/ava#2129]
Between running all tests in parallel and running all tests serially there is a middle ground of enforcing a certain ordering of tests (which is currently not supported).

Imagine an endpoint, puppeteer or any other end-to-end test, which has to tests these scenarios:
1. Register a user
2. `N` tests for each free feature
3. Upgrade to a paid plan
4. `M` tests for each paid feature
...

These are not as pure as unit-tests should be, they have to share user credentials. I believe this is unavoidable in e2e tests, as making these truly independent without losing coverage effectively means generating `N * M * ...` independent tests, which will execute too slow if you imagine numbers of features (`N, M, ...`) keep growing over time.

You can't run them in parallel as tests 1 and 3 are prerequisite for tests 2 and 4 respectively.
You can run them serially and that would be correct but slow.

I propose ava provides a way to specify dependencies and runs tests in best possible order without breaking those dependencies:

```
           test 2.1              test 4.1               
         ╱    .     ╲          ╱    .     ╲             
 test 1 ──    .     ── test 3 ──    .     ── done       
         ╲    .     ╱          ╲    .     ╱             
           test 2.N              test 4.M             Time 
──────────────────────────────────────────────────────────▶
```

If there was another test with no dependecies, it could run in parallel with test 1, similar to how gulp tasks run, I hope the intention is obvious.

Potential syntax for specifying dependencies:

```js
const registrationTest = test('register a user', t => { ... });

const feature1Test = test('feature 1 works', registrationTest, t => { ... });

const feature2Test = test('feature 2 works', registrationTest, t => { ... });

const paidPlanTest = test('upgrade to a paid plan', [
	feature1Test,
	feature2Test,
], t => { ... });
```

**Comment by novemberborn** [comment]
You could build this on top of AVA. `test()` can be called asynchronously, as long as all tests are registered in one go. This means you could wrap `test()` with some other function that manages the dependencies. Then, wrap the test implementations so make sure you await previous tests before running.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by futpib** [comment]
If it was built on top of AVA, I imagine it messing up various AVA features:
* `beforeEach`/`afterEach` order will be like in a parallel run, when it should be in dependency order as well
* `test.only`/`ava --match` - with in-framework support, AVA could run selected test with their dependencies. An implementation on top of AVA can not control this
* failure in a dependency test (that is `await`'ed in every dependent test) will make every dependent tests fail. This is better modelled by introducing a separate state "skipped due to dependency failure" (or reusing existing "skipped")
* timeouts will apply to the whole dependency chain, not to a single test
I think you could make snapshots work properly with this approach, but this would be tricky too.

Solving these on top of AVA would require hacks or introducing new APIs in AVA. That's why I suggest it's supported by AVA.

**Comment by novemberborn** [comment]
I'd really like to see something like this built on top of AVA before considering how we may add such flow control to AVA itself. It's quite an advanced concept.



> * `beforeEach`/`afterEach` order will be like in a parallel run, when it should be in dependency order as well

Yes, but you could enforce that similarly to how you'd have to order the test themselves.



> * `test.only`/`ava --match` - with in-framework support, AVA could run selected test with their dependencies. An implementation on top of AVA can not control this

True, but that just raises the question: would those AVA features even be compatible if we'd implement this ourselves?

> * failure in a dependency test (that is `await`'ed in every dependent test) will make every dependent tests fail. This is better modelled by introducing a separate state "skipped due to dependency failure" (or reusing existing "skipped")

You could fail subsequent tests with `t.fail('dependency failed')` which would communicate this.

> * timeouts will apply to the whole dependency chain, not to a single test

Timeouts are based on the lack of any test completing, which seems appropriate here.

**Comment by futpib** [comment]
I implemented the most basic version of this: made `test` return a "Promise": https://github.com/futpib/ava-thenable.
