### ISSUE TITLE
Cannot read property 'after' of undefined

### ISSUE THREAD

**Issue by ttfreeman** [avajs/ava#2136]
I am running Google Cloud's Bookshelf tutorial ([https://cloud.google.com/nodejs/getting-started/tutorial-app](https://cloud.google.com/nodejs/getting-started/tutorial-app)) that has used AVA for testing. All the tests are running successfully except the last clean-up where test.always.after fails with error: "Cannot read property 'after' of undefined". Here is the code:

```
  //   clean up
  test.always.after.cb(t => {
    if (id) {
      getRequest(testConfig)
        .delete(`/api/books/${id}`)
        .expect(200)
        .end(t.end);
    } else {
      t.end();
    }
  });
```

**Comment by ttfreeman** [comment]
There was an error in the file. It's supposed to be test.after.always.cb... Could be because they had used a much older version of AVA. Regardless, closing this now...

**Comment by novemberborn** [comment]
Yes that tutorial seems to be using AVA 0.25 so it's quite outdated. Apparently they're converting their tests to Mocha so I guess the problem will go away eventually 😬https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues/254
