### ISSUE TITLE
Ava Vulnerability

### ISSUE THREAD

**Issue by nstanard** [avajs/ava#2137]
Vulnerability Report: 

path: ava > supertap > js-yaml 
https://npmjs.com/advisories/813

Supertap PR for bumping the js-yml version.
https://github.com/vadimdemedes/supertap/pull/2

**Comment by novemberborn** [comment]
AVA doesn't load YAML files and therefore is not vulnerable.

The patched version is selected by supertap's dependency range. If you don't have a package lock file you can delete `node_modules`, reinstall, and you'll get the patch. If you have a lock file then use `npm audit fix` to upgrade.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
