### ISSUE TITLE
Ava tests blocks run out of order before they are finished

### ISSUE THREAD

**Issue by StarpTech** [avajs/ava#2140]
Hello,
I run into an inconsistent behaviour during testing. It results in random failures.

```js
import test from 'ava';

const timeout = ms => new Promise(resolve => setTimeout(resolve, ms));

test('Should Test 1', async t => {
  console.log('+++++++++++++BEFORE FIRST+++++++++++', Date.now());

  await timeout(600);

  console.log('+++++++++++AFTER FIRST+++++++++++++', Date.now());
});

test('Should Test 2', async t => {
  console.log('++++++++++++START SECOND++++++++++++', Date.now());
});
```

Output:

```
+++++++++++++BEFORE FIRST+++++++++++ 1558867803667
++++++++++++START SECOND++++++++++++ 1558867803670
+++++++++++AFTER FIRST+++++++++++++ 1558867804270
```

```
lca: TAP version 13
lca: +++++++++++++BEFORE FIRST+++++++++++ 1558867912544
lca: # Should Test 1
lca: ok 1 - Test 1
lca: ++++++++++++START SECOND++++++++++++ 1558867912546
lca: +++++++++++AFTER FIRST+++++++++++++ 1558867913147
lca: # Should Test 2
lca: ok 2 - Should Test 2
lca: 1..2
lca: # tests 2
lca: # pass 2
lca: # fail 0
```

How is that possible that the second test is run before the first was done?

Ava: 1.4.1
Node.js: v11.14.0

**Comment by StarpTech** [comment]
Wow, I didn't know that even the tests blocks are executed concurrently.
https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#running-tests-serially

**Comment by sindresorhus** [comment]
Tests are run concurrently by default. Order is not guaranteed. This is in the docs.

Ideally, you should write atomic tests that don’t  depend on each other or order. If that’s not possible, there’s `test.serial()` or the `{serial: true}` config.

**Comment by StarpTech** [comment]
Hi @sindresorhus they didn't depend on each other but working with [nock](https://github.com/nock/nock) in your tests can lead to strange side effects because it can intercept only one at a time.
