### ISSUE TITLE
[Feature request] Simpler syntax for snapshot testing of commands that might throw or not

### ISSUE THREAD

**Issue by ehmicky** [avajs/ava#2145]
## Description

Many of my unit tests have the following structures:

```js
import myLibrary from '../index.js'

// Array of possible inputs
[
   {},
   { option: true },
   // and so on...
].forEach(options => {
  test(`should test this library | ${JSON.stringify(options)}`, t => {
    try {
      t.snapshot(myLibrary(options))
    } catch (error) {
      t.snapshot(error)
    }
  })
})
```

Basically I run a library function with a bunch of inputs, and snapshot the output. I wrote a library ([`test-each`](https://github.com/ehmicky/test-each)) around that concept (data-driven testing + snapshots).

The issue: I also snapshot exceptions that are thrown. Invalid inputs will throw an exception, but others won't, so my test code needs to handle both.

I wanted to suggest a feature request allowing to remove that duplicate `t.snapshot()` when writing tests like this. One possible way would be to allow `t.snapshot()` argument to be a function (like `t.throws()`). That function would be fired (with no arguments) and any exception thrown would be snapshot:

```js
// No try/catch block needed
t.snapshot(() => myLibrary(options))
```

It could also use a new method name.

Ideally this would work with async functions as well.

What do you think? Thanks!

**Comment by sindresorhus** [comment]
Unrelated to your request, but you probably want to be using test macros: https://github.com/avajs/ava/blob/bccd297f38c9f4cf6dbb16dffa7ee8753dbbd12f/docs/01-writing-tests.md#reusing-test-logic-through-macros

**Comment by ehmicky** [comment]
I am using one of my library ([`test-each`](https://github.com/ehmicky/test-each)) instead of macros. Mostly because I find it to have a simpler syntax. Also this separates the data-driven testing logic from the test runner. (I know that this makes it harder for static analysis like `eslint-plugin-ava` though).

With test macros:

```js
function macro(t, first, second) {
	t.is(typeof multiply(first, second), 'number');
}

macro.title = (title = '', first, second) => `should mix integers and floats | ${first} ${second}`

test(macro, 0.5, 2.5)
test(macro, 10, 2.5)
test(macro, 0.5, 5)
test(macro, 10, 5)

// Or:

[0.5, 10].forEach(first => {
  [10, 2.5].forEach(second => {
    test(macro, first, second)
  })
})
```

With `test-each`:

```js
testEach([0.5, 10], [2.5, 5], ({ title }, first, second) => {
  test(`should mix integers and floats | ${title}`, t => {
    t.is(typeof multiply(first, second), 'number')
  })
})
```

**Comment by novemberborn** [comment]
> The issue: I also snapshot exceptions that are thrown. Invalid inputs will throw an exception, but others won't, so my test code needs to handle both.

Do you know in advance whether an input will be invalid? I'd argue you should check for that explicitly using `t.throws()`. Then you'd end up with something like:

```js
if (invalidInput) {
  const err = t.throws(() => processInput(input))
  t.snapshot(err)
} else {
  t.snapshot(processInput(input))
}
```

You could wrap that up in a helper function, or indeed macro.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by ehmicky** [comment]
@novemberborn thanks for looking into this!

That would work. However that would require:
  a) creating an `invalidInput()` function. For projects with hundreds of tests, this would create quite a lot of code, including helpers.
  b) updating that code from time to time as the library changes.

Instead by simply snapshotting the result (including exceptions), no code is needed. I just need to:
  a) check the snapshots during the first run (ensuring there are no bugs).
  b) update them with `ava -u` when the library changes.

**Comment by novemberborn** [comment]
Fair enough. I don't think that's a use case for AVA to support directly. Writing a helper method is your best bet.

**Comment by ehmicky** [comment]
Makes sense. Thanks for looking into it!
