### ISSUE TITLE
Ava reports incorrect lines and source files with precompiled typescript

### ISSUE THREAD

**Issue by rianadon** [avajs/ava#2146]
I'm currently using Ava and Instanbul's nyc to run tests compiled to typescript. The tests are compiled with `tsc` and sourcemaps enabled, then I run Ava with the compiled JavaScript.

If I run without nyc (`ava build/tests`), Ava behaves perfectly. The output of a failing test looks like this:
```typescript
file › test

  /path/to/file.ts:38

   37:     const r = await t.context.axios.get('/url')
   38:     t.is(r.status, 201)                           
   39:     t.is(r.data, 'hi')
```
The sourcemap converts the filename to typescript and the line numbers and source files match the Typescript source code.

However, if I run with nyc (`nyc ava build/tests`), Ava prints JavaScript filenames, the JS source code, and incorrect line numbers:

```typescript
 file › test

  /path/to/file.js:4

   3:     return (mod && mod.__esModule) ? mod : { "default": mod };
   4: };                                                            
   5: Object.defineProperty(exports, "__esModule", { value: true });
```
In both cases, nyc uses the correct line numbers from the source map, so it seems the issue is in the handoff between nyc and Ava.

I have no configuration for Ava as I'm not using it to compile the TS files and [the guide](https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md) doesn't have any other instructions, but I've installed `source-map-support`. I've tried setting `"compileEnhancements": false` and `require: ["source-map-support/register"]`, but they make no difference.

My nyc config is:
```json
"nyc": {                                                                                                                                                                                     
  "extension": [                                                                                                                                                                             
    ".ts",                                                                                                                                                                                   
    ".tsx"                                                                                                                                                                                   
  ],                                                                                                                                                                                         
  "exclude": [                                                                                                                                                                               
    "**/*.d.ts",                                                                                                                                                                             
    "test"                                                                                                                                                                                   
  ],                                                                                                                                                                                         
  "reporter": [                                                                                                                                                                              
    "text",                                                                                                                                                                                  
    "html"                                                                                                                                                                                   
  ]                                                                                                                                                                                          
}
```

If it would help I can create a minimal reproduction, but I'd first like to check that I'm not missing any configuration options.

Thanks!

**Comment by sindresorhus** [comment]
Can you try without `nyc`? We've had reports in the past which turned out to be `nyc` problems, not AVA.

**Comment by rianadon** [comment]
It works without `nyc` (see the second and third paragraphs of my first comment). So the problem could definitely be entirely with `nyc`. However, since `nyc` read the source map correctly and then Ava running within `nyc` didn't, I figured the issue was with both of them.

If you think it would be more suitable, I could also create an issue on the `nyc` repo. Or do that and close the one here.

**Comment by rianadon** [comment]
Whoops I did more digging and realized this is a duplicate of #1604 (which is without using typescript but the same concept), which is related to https://github.com/istanbuljs/nyc/issues/619. Sorry for wasting your time :disappointed:.
