### ISSUE TITLE
What happened to "helpers" in 2.0.0

### ISSUE THREAD

**Issue by DuJiming** [avajs/ava#2153]
```
 ✖ No tests found in test/helpers/index.js, make sure to import "ava" at the top of your test file
```
I think some configurations have been added. By default, "helpers" are not excluded. Where is the configuration? Thank you.

**Comment by sindresorhus** [comment]
This is clearly documented in the release notes: https://github.com/avajs/ava/releases/tag/v2.0.0

Please try harder to find the answer yourself next time before opening an issue. Thanks.

**Comment by Lange** [comment]
In the issue author's defense, this tripped me up as well, because the docs here still reference the old behavior: https://github.com/avajs/ava/blob/master/docs/05-command-line.md

**Comment by novemberborn** [comment]
@Lange those are the pre-release docs. This is changing (and improving!) in v3 , out  now in beta.
