### ISSUE TITLE
ava 2.0.0 upgrade "Error: Cannot apply enhancement-only precompilation, possible bad usage"

### ISSUE THREAD

**Issue by edmorley** [avajs/ava#2156]
## Description

After upgrading from ava 1.4.1 to 2.0.0, our existing tests fail with:

> Error: Cannot apply enhancement-only precompilation, possible bad usage

I tried looking at the ava 2.0.0 release notes to see if there was a change we should have made to make our project compatible with it, however there's nothing listed, so this instead seems like a bug. If it's an intentional change, then it would be good to document it and make the error message clearer :-)

### Test Source

The error message doesn't say which test caused the issue. The directory containing our tests is here:
https://github.com/neutrinojs/webpack-chain/tree/master/test

### Error Message & Stack Trace

```
$ yarn test
yarn run v1.16.0
$ ava test
  ✖ Internal error
  Error: Cannot apply enhancement-only precompilation, possible bad usage: /home/travis/build/neutrinojs/webpack-chain/test
  Error: Cannot apply enhancement-only precompilation, possible bad usage: /home/travis/build/neutrinojs/webpack-chain/test
      at Object.precompileEnhancementsOnly.options.extensions.enhancementsOnly.length.filename [as precompileEnhancementsOnly] (/home/travis/build/neutrinojs/webpack-chain/node_modules/ava/lib/api.js:284:12)
      at precompilation.map.reduce (/home/travis/build/neutrinojs/webpack-chain/node_modules/ava/lib/api.js:190:21)
      at Array.reduce (<anonymous>)
      at Api.run (/home/travis/build/neutrinojs/webpack-chain/node_modules/ava/lib/api.js:184:34)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```
(from https://travis-ci.org/neutrinojs/webpack-chain/jobs/543377793#L254)

### Config

We don't have an `ava` key listed in `package.json`.

### Command-Line Arguments

```
  "scripts": {
    "test": "ava test",
    ...
  },
```

## Relevant Links

Example failing Travis run:
https://travis-ci.org/neutrinojs/webpack-chain/jobs/543377793#L254

Project source:
https://github.com/neutrinojs/webpack-chain

## Environment

Fails under all versions of Node.js that we use (8, 10, 12).

We're using ava 2.0.0 and yarn 1.15.2.

**Comment by novemberborn** [comment]
Remove the `test` argument to the `ava` invocation. With 2.0 you can now only provide paths to test files on the CLI, not directories or glob patterns. I've opened #2158 to ensure we throw a more descriptive error.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by Kikobeats** [comment]
This should be part of the release notes as a migration guide from 1.0.

Now that the CLI only accepts absolute file path, how we can convert `test` glob into something ava 2.0 like?

**Comment by novemberborn** [comment]
> This should be part of the release notes as a migration guide from 1.0.

It is mentioned:

> The CLI now only takes file paths, not glob patterns.

I agree a migration guide could still be useful. Is that something you may be interested in contributing?



> Now that the CLI only accepts absolute file path, how we can convert `test` glob into something ava 2.0 like?

For your use case, calling `ava` without arguments should suffice.
