### ISSUE TITLE
BeforeEach doesn't work if all tests are run with asyc/await

### ISSUE THREAD

**Issue by jannakha** [avajs/ava#2157]
test.beforeEach doesn't run before each test (and doesn't reset variables for each test) if tests are run with async. Example:

```
test.beforeEach(t => {
  // reset env variables
  // defaultEnv.PRIVATE_KEY = 'VALID KEY';
  process.env = {...process.env, ...defaultEnv};
});

test('getResult returns error if invalid JWT', async t => {
  process.env.PRIVATE_KEY = 'some wrong key';

  // more setup here and then do some tests here like 
  await getResult(mockRequest, mockResponse);

  // Give the query time to complete
  await new Promise(resolve => {
    setTimeout(resolve, 1500);
  });

  const responseStatus = mockResponse.status.firstCall.args[0];
  t.is(responseStatus, 500)
});

test('getResult returns 200 response if JWT is valid', async t => {
  await getResult(mockRequest, mockResponse);

  // Give the query time to complete
  await new Promise(resolve => {
    setTimeout(resolve, 1500);
  });

  const responseStatus = mockResponse.status.firstCall.args[0];
  t.is(responseStatus, 200)
});
```

basically, I have to manually call beforeEach() function to reset data as a quick fix.

- versions: Node 8.16, "ava": "^2.0.0",

**Comment by jannakha** [comment]
well, doh read docs and use test.beforeEach.cb (callback)

```
test.beforeEach.cb(t => {
	setTimeout(t.end);
});
```

**Comment by jannakha** [comment]
tried test.beforeEach.cb() but that didn't work either

**Comment by novemberborn** [comment]
AVA starts regular tests (`test('my test', t => { … })`) all at once. If a test is asynchronous this means the `beforeEach()` of the *next* test runs *before* the test completes. If you're sharing variables between tests, like you're doing here with `process.env`, you'll need to use `test.serial()`.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
