### ISSUE TITLE
Ensure files passed through CLI exist, and are files, before precompiling

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2158]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/avajs/ava/issues/2158)

See #2156, where AVA was called with a test directory as its CLI argument (`ava test`). Precompilation fails because the "file" cannot be read. We should catch this and throw a more appropriate error.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#2184 [Wip]: Ensure files passed through CLI exist, and are files](https://issuehunt.io/r/avajs/ava/pull/2184)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/ava/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by MarchWorks** [comment]
On which file should I add the test if necessary?
