### ISSUE TITLE
TypeError: Cannot read property 'emitStateChange' of undefined

### ISSUE THREAD

**Issue by JustinDFuller** [avajs/ava#2163]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/avajs/ava/issues/2163)

## Description

While running `ava` on a directory where node_modules does not have the proper permissions for the current user to write, ava gives the following error:

```
TypeError: Cannot read property 'emitStateChange' of undefined
    at Api.run (/usr/src/app/backend/node_modules/ava/lib/api.js:278:17)
    at Object.exports.run (/usr/src/app/backend/node_modules/ava/lib/cli.js:274:31)
    at Object.<anonymous> (/usr/src/app/backend/node_modules/ava/cli.js:10:23)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

After adding a console.log the ava code I found the actual error:

```
Error: ENOENT: no such file or directory, mkdir '/usr/src/app/backend/node_modules/.cache/ava'
    at Object.mkdirSync (fs.js:764:3)
    at AsyncFunction.module.exports.sync (/usr/src/app/backend/node_modules/make-dir/index.js:108:6)
    at Api._setupPrecompiler (/usr/src/app/backend/node_modules/ava/lib/api.js:299:13)
    at Api.run (/usr/src/app/backend/node_modules/ava/lib/api.js:114:38)
    at Object.exports.run (/usr/src/app/backend/node_modules/ava/lib/cli.js:274:31)
    at Object.<anonymous> (/usr/src/app/backend/node_modules/ava/cli.js:10:23)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/usr/src/app/backend/node_modules/.cache/ava'
}
```

After making a slight code change to api.js at line 251

```js
} catch (error) {
    // The code errored before RunStatus was created. I added this here to see what was expected.
    if (!runStatus) {
        runStatus = new RunStatus(files.length, null);
    }
    
    runStatus.emitStateChange({type: 'internal-error', err: serializeError('Internal error', false, error)});
}
```

I now get to the following error:

```
> ava

  ✖ Couldn't find any files to test
```

Once I fix the permissions I receive no errors.

What's happening:

In lib/api.js line 110 `api._setupPrecompiler` is throwing an error before `runStatus` is set. The error is because mkdir fails due to permissions issues. In the catch block on line 252, runStatus has not been set yet, so it cannot emit an error.  

### Test Source

```js
// Literally any test will reproduce. test/index.test.js

const test = require('ava')

test('foo', function (t) {
  t.true(true)
})
```

### Error Message & Stack Trace

See above.

### Config

Copy the relevant section from `package.json`:

No custom config. Running ava out of the box. No babel or anything.

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
> node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v12.4.0
linux 4.9.125-linuxkit
> ./node_modules/.bin/ava --version
2.1.0
> npm --version
6.9.0
```

Project structure:
```
> ls -la
drwxr-xr-x  465 root     root         20480 Jun 20 15:13 node_modules
-rw-r--r--    1 root     root        226376 Jun 20 11:58 package-lock.json
-rw-r--r--    1 root     root          1339 Jun 20 15:21 package.json
drwxr-xr-x    4 root     root          4096 Jun 20 11:54 src
drwxr-xr-x    6 root     root          4096 Jun 16 01:59 test
 
```
Test dir structure
```
> ls -la test
-rw-r--r--    1 root     root           182 Jun 16 01:59 index.test.js
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)
### Submitted pull Requests
- [#2183 Fix: running tests without cache directory permissions (fix #2163)](https://issuehunt.io/r/avajs/ava/pull/2183)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/ava/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by JustinDFuller** [comment]
As mentioned above, the issue is fixed by chowning node_modules to the correct user. This is not a problem, but I'd like to put in a PR to show a better error message to people who see this issue in the future. Since the ENOENT wasn't on a test file, but instead on a setup file, should a different error message be shown? 

"Couldn't access cache directory during setup. Disable caching or ensure your node_modules permissions are correct."

Something like that?

**Comment by novemberborn** [comment]
> In lib/api.js line 110 `api._setupPrecompiler` is throwing an error before `runStatus` is set. The error is because mkdir fails due to permissions issues. In the catch block on line 252, runStatus has not been set yet, so it cannot emit an error.

Oh nice find!

I guess what we should do is wrap these lines in their own `try`/`catch`:

https://github.com/avajs/ava/blob/dc917257e574987357670378f03d36700a57776e/lib/api.js#L110:L124

Then if there is an error we can set `files = []`, which is fair enough because we can't realistically find the files.

Trickier is that we need to store the error in, say, a `setupOrGlobError` variable. *After we emit the `run` event, but before we [bail out](https://github.com/avajs/ava/blob/dc917257e574987357670378f03d36700a57776e/lib/api.js#L154), we need to rethrow that error (if it exists, of course).

The control flow here is more difficult than it needs to be but this is the best we can do I think without rewriting more of the logic.

> As mentioned above, the issue is fixed by chowning node_modules to the correct user. This is not a problem, but I'd like to put in a PR to show a better error message to people who see this issue in the future.

I think if we make sure the error is reported then that may be sufficient?
