### ISSUE TITLE
Remove Node.js 11 from CI, package.json engines entry, docs

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2169]
Node.js 11 is end of life. We can stop testing it. The `package.json` `engines` entry should be updated to exclude it. If it's mentioned in any documentation we can remove that too.

**Comment by thewhitewolf17** [comment]
I excluded node.js 11 from package.json and went through docs, couldn't find mention of NodeJS 11 anywhere. 
adce1cab16ed8de2e60e8be2dd061e1d31541282

**Comment by novemberborn** [comment]
> Should I submit a PR?

Yes, that's the general idea 😄 

As it stands I've tackled this already in #2179 since speeding up the tests will help me in trying to get a release out today. Hopefully we have some other issues you're interested in?
