### ISSUE TITLE
In Node.js 12 or newer, add hasColors to the fake TTY methods

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2170]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/avajs/ava/issues/2170)

We're missing [`hasColors()`](https://nodejs.org/api/tty.html#tty_writestream_hascolors_count_env) in our fake TTY implementation: https://github.com/avajs/ava/blob/533ee4bc54cbcd1c2b6ab5c67f3ec8a699965269/lib/worker/fake-tty.js

It was introduced in Node.js 11, so we should check if the worker is running in Node.js 12 before adding it (Node.js 11 is end of life, see https://github.com/avajs/ava/issues/2169). We should be able to piggy-back off of the `colorDepth` value that's already available. I don't think we can make it work with arbitrary `env` variables though. We can deal with that as a follow-up.

Currently this is causing CI to fail with Node.js 12.5.0: https://travis-ci.org/avajs/ava/jobs/552425902

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/ava/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by okyantoro** [comment]
in `simulateTTY()` requires [`colorDepth`](https://github.com/avajs/ava/blob/533ee4bc54cbcd1c2b6ab5c67f3ec8a699965269/lib/worker/fake-tty.js#L35) option to define the `getColorDepth()` method. Should `hasColors()` be defined the same way as `getColorDepth()`? @novemberborn

**Comment by novemberborn** [comment]
@okyantoro it also requires `colorDepth`, yes, but `getColorDepth()` is available in Node.js 10 and `hasColors()` should only be made available in Node.js 12 and newer. Perhaps a `typeof process.stderr.hasColors()` is sufficient to see if it needs to be shimmed.
