### ISSUE TITLE
AVA should not glob for any file named `test.js` in the file hierarchy

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#2172]
AVA v2 changed to look for a `test.js` anywhere in the current project's hierarchy by default. That means it will try to run a test at `./foo/bar/templates/dist/unicorns/test.js`. Even though people are not likely to have a non-test file named `test.js`, it's still unexpected behavior.

I think for AVA v3, we should make the rule explicit and only look for a `test.js` at the project root (where package.json is).

**Comment by novemberborn** [comment]
I think we should still add `src/test.js` and `source/test.js`.
