### ISSUE TITLE
API reference

### ISSUE THREAD

**Issue by masaeedu** [avajs/ava#2174]
## Description
Hello. I was wondering if there's a comprehensive API reference for AVA available somewhere that documents the types of all the exports from `require("ava")` module? It seems this might have already been present in the README at some point and perhaps was moved, because there's various dead links in issues pointing to parts of the README that no longer exist. If not, would it be possible to add this to the README for easy reference?

Every time I have to do something non-trivial I have to spend some time flailing about trying to remember how the `cb` API etc. work.

**Comment by novemberborn** [comment]
Hi @masaeedu, do the links here help? https://github.com/avajs/ava#documentation

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by masaeedu** [comment]
Hi @novemberborn. Not quite; I'm looking for an API reference in the vein of the following:

- https://gcanti.github.io/fp-ts/modules/Array.ts.html
- https://sanctuary.js.org/#api
- https://github.com/cujojs/most/blob/master/docs/api.md#mostfrompromise

etc.

**Comment by novemberborn** [comment]
Ah I see. We could maybe generate that from our TypeScript definition file, once we have a documentation side. I haven't had time to catch up with #2051.
