### ISSUE TITLE
Vulnerabilities?

### ISSUE THREAD

**Issue by dmitriz** [avajs/ava#2188]
## Description
Bug: The currently used "lodash": "^4.17.11" is reported as vulnerable:
https://snyk.io/vuln/npm:lodash

### Command-Line Arguments

Running `npm audit fix` and `snyk test` uncovers multiple vulnerabilities.

## Relevant Links

Getting vulnerability warning by Github in my project https://github.com/dmitriz/cpsfy/network/alerts
due to the use of the older `lodash` by `ava`.

**Comment by novemberborn** [comment]
[No](https://github.com/avajs/ava/issues/2182).

**Comment by dmitriz** [comment]
@novemberborn That link refers to a non-direct dependency, while `lodash ^4.17.11` is a direct dependency explicitly mentioned in the current `package.json`, in the form it allows to keep the vulnerable versions installed. 

Any reason not to change it to the safer `^4.17.14` setting?

**Comment by novemberborn** [comment]
> Any reason not to change it to the safer `^4.17.14` setting?

The `^4.17.11` range already includes `4.17.14`. It'll most likely be made the minimum version when I bump dependencies for the next release. This isn't precluding npm from updating the dependency, and well this is a build-time test tool so it's not really an issue anyway.

**Comment by dmitriz** [comment]
The inclusion is only used for new installs if I understand it correctly,
and this may not cover some other cases.

E.g. https://github.com/avajs/ava/blob/master/package-lock.json#L486
explicitly refers to the older version and again, if I understand correctly,
your build is currently using the old version for testing,
that potentially cannot safeguard from breaking or leading to hard-to-reproduce errors 
for people using the newer version.

A newer release of `ava` would also force some additional skipping the cache and re-installs, so fewer people notice and complain. :)

**Comment by novemberborn** [comment]
> The inclusion is only used for new installs if I understand it correctly,
> and this may not cover some other cases.

That's your concern, not AVA's.



> E.g. https://github.com/avajs/ava/blob/master/package-lock.json#L486
> explicitly refers to the older version and again, if I understand correctly,
> your build is currently using the old version for testing,
> that potentially cannot safeguard from breaking or leading to hard-to-reproduce errors
> for people using the newer version.

The package lock is not published and does not affect your installs.



> A newer release of `ava` would also force some additional skipping the cache and re-installs, so fewer people notice and complain. :)

I suspect we may have to set up some issue templates and try and use that to educate people. Also [this tweet](https://twitter.com/dan_abramov/status/1149795048722067456).

I'm not going to frantically ship new releases to address perceived security issues that do not actually impact AVA.

**Comment by dmitriz** [comment]
I can't help to feel some irritation in your answer, and assure you, it was not my intent, and that I find these warnings as annoying as I do having to post such issues.

> The package lock is not published and does not affect your installs.

It is used for anyone forking the repo, so any PR will be tested against the old `lodash`.
When I run `npm i`, it does install the old `lodash@4.17.11`, not the newer.
So any new code, any PR is not tested with the same deps as used by 
the AVA end-users installing from `npm`.

I do hear you saying this change is unlikely to cause any problems and resonate with Dan's twitter message, and I agree, but the question is, is it really worth to spend our time thinking which one of these warnings is FUD and which isn't, when the fix is literally one character change? :) That would also save you from other people opening more issues of that kind btw.
(And I'd be happy to submit a PR if that is of any help.)
