### ISSUE TITLE
Add test coverage for reporter output when hooks fail

### ISSUE THREAD

**Issue by yovasx2** [avajs/ava#2194]
I tried to do that for tap formatter inside the regular folder, but all formatters require this folder so all specs were failing.

**report/regular/failing-hook.js**
```
import test from '../../../..';

test.before(_ => {
	throw new Error('error');
});

test('passing test', t => {
	t.pass();
});
```

**Comment by novemberborn** [comment]
Could you elaborate on what's missing here? Is this just for the TAP reporter?

**Comment by yovasx2** [comment]
every reporter is missing a test case like above, when the hook is failing (before, in this case)

**Comment by novemberborn** [comment]
Sure we can add some tests for that.
