### ISSUE TITLE
Does AVA accept donations?

### ISSUE THREAD

**Issue by tomholub** [avajs/ava#2207]
PayPal would be the easiest. Just checking

**Comment by novemberborn** [comment]
😍 We're set up somewhere, but I can't quite find a link in the README! @sindresorhus?

**Comment by sindresorhus** [comment]
https://opencollective.com/ava

**Comment by novemberborn** [comment]
Wouldn't hurt to add this to the README I suppose 😄

**Comment by dongjae93** [comment]
Added! Please check :)

**Comment by tomholub** [comment]
Thanks guys, I'll send some token of appreciation over when I have a chance.
