### ISSUE TITLE
Do we need to fake TTY in the worker processes?

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2215]
We fake the TTY in worker processes, forwarding best we can the settings with which AVA is run. This code is increasingly hard to maintain.

I'm not sure why we're even doing this in the first place. What are the consequences of launching the worker processes without any TTY? Does anybody rely on this?

Presumably we'd keep forwarding color support as we do now.

**Comment by sindresorhus** [comment]
I rely on this in a lot of tests. We fake TTY as the fact that AVA spawns multiple processes should just be an implementation detail.

**Comment by novemberborn** [comment]
Are you suggesting that if we had an execution mode where the tests didn't run in a child process, we could remove the faking?

**Comment by sindresorhus** [comment]
Yes, although I'm sure people rely on it when they need multi-process execution too, so it might be a good idea to keep it for the sake of a good developer experience.

I wonder if there's a way we could get Node.js to either have a way to fake TTY or expose more code so we don't have to duplicate as much.

**Comment by novemberborn** [comment]
> I wonder if there's a way we could get Node.js to either have a way to fake TTY or expose more code so we don't have to duplicate as much.

The constructors are exposed (https://github.com/nodejs/node/blob/master/lib/tty.js) so perhaps we could?

**Comment by novemberborn** [comment]
I'm adding the v3 milestone to hopefully explore whether we can make the faking opt-in instead.

**Comment by novemberborn** [comment]
Our tests pass without a fake TTY. I suggest we remove the faking, and then publish our implementation as a separate package which you can load in the worker processes.

**Comment by novemberborn** [comment]
TTY has been removed in #2337. I've opened https://github.com/avajs/ava/issues/2343 to deal with its replacement.
