### ISSUE TITLE
Consolidate mini and verbose reporters

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2217]
Currently we have two different reporter implementations. Code is duplicated across them which leads to various bugs. I once tried to consolidate them but [that work stalled](https://github.com/avajs/ava/pull/1776).

~~The idea is that we would have only one reporter. By default it provides minimal output. We show a spinner and the status of the last test, so you get a sense of activity, and once an entire test file completes do we print failures. In verbose mode, we'd print the results of all tests & hooks, including logs. Various counts for passing and failing tests are always shown at the end of the output.~~

~~If a TTY is not available, we wouldn't print a spinner and only write the appropriate output for a test file once it completes.~~

~~We'd use [`ink`](https://www.npmjs.com/package/ink) to construct the output.~~

**Comment by novemberborn** [comment]
@yovasx2 you've privately expressed interest in working on this. If you comment on this issue I can assign it to you within the GitHub interface.

**Comment by biofreak** [comment]
You could assign this task on me. But I have to warn you that this is my first time on github, so it will take some time to get familiar with.

**Comment by novemberborn** [comment]
@biofreak that's great, but @yovasx2 is working on this at the moment.

**Comment by yovasx2** [comment]
Sure

**Comment by pcdevil** [comment]
as of #2458 I expressed my interest to work with this and I'd take it!

**Comment by novemberborn** [comment]
@pcdevil did you manage to take a stab at this? I think @Michael55555 is interested in working on this as well.

**Comment by pcdevil** [comment]
Hello @novemberborn,

Sorry, I only did small improvements locally, started to outsource the identical part of [VerboseReporter.consumeStateChange()][1] into a new `BaseReporter` class.

Unfortunately I didn't have much time in the last two weeks as anticipated. I can hand it over that code to @Michael55555, no harm on my part if he wants to take it over!

[1]: https://github.com/avajs/ava/blob/master/lib/reporters/verbose.js#L112

**Comment by novemberborn** [comment]
Thanks for the update @pcdevil.

FWIW I don't think we need any base class. We can envision a single reporter, which in verbose mode… reports more!

@Michael55555 what do you think?

**Comment by Michael55555** [comment]
Moving the functionality from _minimal_ to _verbose_ would possibly be the best way to do it.
Once we did that, we can give the new reporter class a more descriptive name.

**Comment by novemberborn** [comment]
I'm not sure if modifying the current code is going to cut it.

**Comment by Michael55555** [comment]
Ok, I see. I think creating a base class would be great to avoid writing code twice. Some functions in the tap and the verbose reporter seem to be nearly the same.

**Comment by novemberborn** [comment]
I don't want us to expend any energy on the TAP reporter. Longer term we'll move it out of this repository. The duplication is fine for the time being.

**Comment by Michael55555** [comment]
Alright, I see. I just created a ``base-reporter.js``, which holds bot ``mini.js`` and ``verbose.js``.

**Comment by Michael55555** [comment]
@novemberborn I opened a pull request referencing this issue already, I'd be happy if you review the changes 😄. #2488

**Comment by novemberborn** [comment]
I've split off https://github.com/avajs/ava/issues/2500 & https://github.com/avajs/ava/issues/2501.
