### ISSUE TITLE
How to get Assertion Error in after hook?

### ISSUE THREAD

**Issue by smyth64** [avajs/ava#2219]
Hi,
I want to get the assertion error after each failed test in order to write it in my database.

How can I achieve that?

**Comment by novemberborn** [comment]
Could you expand on your use case? It might be better to use the TAP reporter and process the resulting file.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by smyth64** [comment]
@novemberborn 
I was just curious how I can pass the context to the tap output? It seems impossible =/ I want to give some payload information about the errors from the external micro service and some IDs that are generated in the test.

Is there any possibility?

**Comment by novemberborn** [comment]
You could log some of that information and it should show up in the TAP output but it won't be structured.

From the looks of it, you're trying to do something a bit beyond just testing your code. That's great but not AVA's core focus.

When we land https://github.com/avajs/ava/pull/1947 you'll have some access to the assertion failures so you could construct something on top of AVA.
