### ISSUE TITLE
Adding additional information to tap output

### ISSUE THREAD

**Issue by smyth64** [avajs/ava#2220]
In my tap output I get this:
```
# test › Make test
not ok 22 - test › Make test
  ---
    name: AssertionError
    assertion: assert
    operator: '!!'
    values:
      'Value is not truthy:': 'false'
    at: |-
      assert (test/services/test/test.js:47:7)
      t (test/services/test.js:40:14)
  ...
```

But what I want is additional information that I can parse later to a JSON.
I tried it with test.log() but it always prefixes an asterisk (*) so the default tap-parser ignores it =/

```
# test › Make test
not ok 22 - test › Make test
  * ---
  * lala: lolo
  * ...
  ---
    name: AssertionError
    assertion: assert
    operator: '!!'
    values:
      'Value is not truthy:': 'false'
    at: |-
      assert (test/services/test/test.js:47:7)
      t (test/services/test.js:40:14)
  ...
```

Is it impossible to add just some payload to the tap output? This is so inflexible...

**Comment by sindresorhus** [comment]
What kind of additional information?

**Comment by smyth64** [comment]
> What kind of additional information?

For example IDs or data that's generated while testing. I test an external service and I want to add the logs of the output to my tap output.

**Comment by novemberborn** [comment]
Please see my answer here: https://github.com/avajs/ava/issues/2219#issuecomment-523333284
