### ISSUE TITLE
Ava continues testing even if assertion fails

### ISSUE THREAD

**Issue by smyth64** [avajs/ava#2221]
## Description

I want to run 500 tests in parallel. Each test does a lot of operations and I want to abort the individual test if something fails. But it seems to be impossible.

I know there is the --fail-fast options but then all the remaining tests will be aborted aswell. I just want the individual test to abort because it's unnecessary to execute all other commands when an assertion fails.

### Test Source

```js
test("test", t => {
    console.log(123)
    t.assert(1 === 2)
    console.log(321)
})
```

Expected log:
123

Actual log:
123
321

I don't understand what's the purpose of keeping the test running after an assertion fails.

**Comment by novemberborn** [comment]
Please see this discussion: https://github.com/avajs/ava/issues/1485
