### ISSUE TITLE
Implement limit concurrency of tests

### ISSUE THREAD

**Issue by luotaoruby** [avajs/ava#2228]
## Description

I'm using AVA and selenium to do integration testing. with BrowserStack Automate I can test my web application on multiple platform and browsers, such as IE on Windows 10, etc.

Each testing I will create a new selenium webdriver client to connect remote selenium webdriver running on BrowserStack, and will destroy the client after each testing finished. AVA can run tests concurrently, it can speed up testing, but on my case, it's a problem. BrowserStack limited the concurrency of running selenium webdriver. So if I run my AVA test concurrently, will reached the limits, and much test will failed, caused timeouts.

So I am thinking about can I limit the concurrency of tests, not only limit the concurrency of test files.

I have forked this repo, and did some code changes for my case. Just limits the concurrency of tests, like limits concurrency of test files. It works for me.

So I am thinking about my be I can add an cli flag or options to limit the concurrency of tests. I think it might be useful for other people. If you agrees I can prepare to create pull request about this.

Thanks! AVA is awesome, I love it. 

<img width="1021" alt="CleanShot 2019-08-26 at 11 29 16@2x" src="https://user-images.githubusercontent.com/7478427/63663401-cb674080-c7f4-11e9-9867-86868b065483.png">

**Comment by novemberborn** [comment]
For your use case, I think it might be better to wrap the BrowserStack API so you can limit how many clients you run concurrently. https://www.npmjs.com/package/p-limit can help with that.

It sounds like the limit is on the BrowserStack side, so even if you limit the concurrency within one CI execution, if you have parallel CI runs you'll still run into trouble.

Ultimately I think limiting concurrency within the test file is rather niche. More likely you can't run any concurrent tests but that's what `test.serial()` is for.

> Thanks! AVA is awesome, I love it.

Thank you!

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by luotaoruby** [comment]
@novemberborn Thanks for reply!  

I agree your idea that I should wrap the BrowserStack API, but EVEN I wrap it, concurrency test still need to limit, otherwise most tests will waiting for the BrowserStack wrapper, and it will still timeout if there are much test.

**Comment by novemberborn** [comment]
AVA's timeout logic, if you enable it, is to limit how much time can pass between individual tests completing. It shouldn't matter how many tests you have pending.
