### ISSUE TITLE
Pronunciation file can not be played

### ISSUE THREAD

**Issue by MartijnCuppens** [avajs/ava#2229]
In the readme, the [link to pronunciation](https://github.com/avajs/ava/blob/master/media/pronunciation.m4a?raw=true) won't play the pronunciation because it violates content Security Policy directive.

```text
Refused to load media from 'https://raw.githubusercontent.com/avajs/ava/master/media/pronunciation.m4a' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.
Blocked script execution in 'https://raw.githubusercontent.com/avajs/ava/master/media/pronunciation.m4a' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

**Comment by novemberborn** [comment]
Thanks for noticing @MartijnCuppens!

Would be good to know whether this is a purposeful change on GitHub's part or something we need to deal with on our end.

**Comment by bok-jin** [comment]
I just checked the link and it is working, @novemberborn. I think that this issue can be closed.

**Comment by novemberborn** [comment]
Thanks @bok-jin!
