### ISSUE TITLE
--watch flag doesn't seem to work as intended

### ISSUE THREAD

**Issue by stringbeans** [avajs/ava#2233]
## Description

Running `ava --verbose --config ava.config.watch.js --watch` does not seem to work as intended. Specifically, it runs all tests in the `files` array whenever a change happens, as opposed to running **only** the tests that are applicable based on the source file changed.

For example, if I run:

`ava --verbose --config ava.config.watch.js --watch src/tests/unit/acl/agency/can-view.unit.ts`

I am expecting that the test `src/tests/unit/acl/agency/can-view.unit.ts` is executed **only if** a source file that is imported or related to the test file is changed. However, if I change a file in the source path that is completely unrelated to the test file it is still run.

### Config

My `ava.config.watch.js`:

```js
export default {
  "babel": false,
  "sources": [
    "src/**/*.ts"
  ],
  "require": [
    "ts-node/register/transpile-only",
    "dotenv/config",
    "bluebird-global"
  ],
  "compileEnhancements": false,
  "extensions": [
    "ts"
  ]
}
```

## Environment

Node.js v8.11.1
darwin 18.0.0
ava 2.3.0
npm 5.6.0

**Comment by stringbeans** [comment]
its possible that perhaps i have totally misunderstood how the `--watch` flag is intended to work so please let me know!

**Comment by novemberborn** [comment]
You're passing a specific test file to run. When AVA can't determine which specific test file a changed source was used in, it reruns all files. See this section on how to enable debug logging to show the events that AVA is detecting: https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#debugging

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by stringbeans** [comment]
thanks for the response @novemberborn ! ill experiment with the debugging option to better understand how it determines which tests to run...

how would i structure my config/CLI such that ava runs **only** the tests that are affected by the changes? here's what im thinking:

`ava --verbose --config ava.config.watch.js --watch`

My ava.config.watch.js:

```
export default {
  "babel": false,
  "files": [
    "src/**/*.unit.ts"
  ],
  "sources": [
    "src/**/*.ts"
  ],
  "require": [
    "ts-node/register/transpile-only",
    "dotenv/config",
    "bluebird-global"
  ],
  "compileEnhancements": false,
  "extensions": [
    "ts"
  ]
}
```

does that look right? and apologies but another question/comment thrown in... when I run watch like this, it first starts by running all the test specified in the `files` section. is there a way to start watch **without** running all the tests first?

**Comment by novemberborn** [comment]
> how would i structure my config/CLI such that ava runs **only** the tests that are affected by the changes?

Make sure `sources` only matches files that are loaded through test files, and inversely that your tests cover all your sources. You can use negation patterns if need be. I'd use the debugging option to figure out which files change often that aren't actually used in your program and then make sure they're not treated as a source.



> when I run watch like this, it first starts by running all the test specified in the `files` section. is there a way to start watch **without** running all the tests first?

No. We don't do any static analysis of the source code so we wouldn't know which test file depends on which source file until we've run them, so we run all tests when you start the watcher.
