### ISSUE TITLE
Test should be reported as failed if hook failed

### ISSUE THREAD

**Issue by nicholas-eden** [avajs/ava#2237]
## Description

The tap reporter swallows failures which occur within the hooks:
https://github.com/avajs/ava/blob/v2.3.0/lib/reporters/tap.js#L144

The failure is being recorded as a comment, which will be ignored by a tap parser.  This means that after parsing it the run will be considered a pass if there was a problem in the hooks that prevented a test from running.

In our use case tests need to setup accounts before executing.  When a PR is made and the tests run, we don't want the test to pass if it can't be executed, it should be marked as a failure for us to look into.

### Test Source

```js
test.serial.beforeEach('Auto failure in hook', () => {throw new Error('Simulated failure');});
```

### Error Message & Stack Trace

```
# Failed hook: Setup accounts for The test name
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
        "compileEnhancements": false,
        "extensions": [
            "ts"
        ],
        "require": [
            "ts-node/register"
        ]
    }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
$(npm bin)/ava --tap --timeout=3m -c 8 -t dist/test/*.js
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
local: darwin 18.6.0
Same issue in other linux based environments
ava --version
v2.3.0
npm --version
6.4.1
```

**Comment by novemberborn** [comment]
Yes, agreed. @yovasx2 what do you think?

**Comment by yovasx2** [comment]
@nicholas-eden agreed, we need to report the failure and  the missing tests as pending, however, the third-party package we are using for writing TAP is not providing a `failed hook` function, that's the reason we chose `comment`, and I think we cannot use `failedTest` cause this is a hook, maybe we can still use the comment and reported missing tests as pending or create a specialized function in the third-party package to report this in ava.

**Comment by nicholas-eden** [comment]
Looking at the TAP spec, there is no definition for failed hooks. Just 'ok' and 'not ok', I don't see a pending or any other status. When I tried reporting failed hooks as failed tests I realized that each hook was being reported, blowing up the test count. 

It seems like the best solution would be to allow the hooks to fail the test explicitly. I believe if a hook throws an error it still continues the test. Failing the test on an error in the hooks might be considered a breaking change. If the hook calls `t.fail()` it looks like it is ignored. Reporting the failure then and canceling the test seems like a good solution.

**Comment by novemberborn** [comment]
> I believe if a hook throws an error it still continues the test.

No. If a `before` hook fails, no tests should be run, and if a `beforeEach` hook fails, the test it's for shouldn't be run. I can't quite recall how we display that though. For the TAP purposes I'd be happy to print failures of the tests themselves. I don't think it much matters for the other reporters.

**Comment by yovasx2** [comment]
I don't like to mark them as failed, may be skipped because they are

**Comment by nicholas-eden** [comment]
I think it makes sense to display `not ok` for a test which had a fail hook, as long as it's only printed once.  In a more verbose output there's probably a better status than failed, but in a binary `ok`, `not ok` this scenario fits `not ok` best.

**Comment by yovasx2** [comment]
problem is making it compatible with other formatters, now they marked them as pending (not run), it's weird if we mark them as failed in tap and not run in others

**Comment by nicholas-eden** [comment]
Which other formatters are not marking the tests as failed?

The other two reporters both label failed hooks as failures as far as I can tell:
https://github.com/avajs/ava/blob/master/lib/reporters/mini.js#L152
https://github.com/avajs/ava/blob/master/lib/reporters/verbose.js#L110

**Comment by yovasx2** [comment]
the hook is marked as failed, but the tests are marked as pending https://github.com/avajs/ava/blob/master/lib/reporters/mini.js#L362

the thing is in TAP there is no hook syntax, so i can create a comment for this failure and then mark the tests as skipped

**Comment by novemberborn** [comment]
With the TAP reporter, I only care that it makes sense for consumers of the TAP output. It does not need to be consistent with what we do elsewhere.

I don't understand TAP well enough to adjudicate this, but it seems reasonable to me that tests fail when their hooks do. So unless you convince me otherwise I'll accept a PR that achieves that 😄

**Comment by grnch** [comment]
If anyone needs a quick & dirty workaround in the mean time, here's what we did in our CI infrastructure:

We changed the invocation of Ava from this:

`ava --tap > test-results.tap`

to this:

`ava --tap | sed 's/^# Failed hook:/not ok -/' > test-results.tap`

This allowed our CI infrastructure to actually notice when tests failed due to a hook failures, instead of erroneously thinking all tests passed and making the build green even though it had a ton of failures!
