### ISSUE TITLE
Check if the test is running in serial mode

### ISSUE THREAD

**Issue by szmarczak** [avajs/ava#2243]
Use case (`lolex` is a time-manipulation module):

```js
const hook = async (t, run) => {
	let clock;
	if (t.isSerial) {
		clock = lolex.install();
	}

	await run(t);

	if (t.isSerial) {
		clock.uninstall();
	}
};

test('description', hook, t => {
	...
});
```

**Comment by novemberborn** [comment]
That's interesting. Could we explore some things around this?

* Why not apply this hook only when you write your test with `test.serial`?
* Would you say we should expose this in `beforeEach` hooks as well?
* The `await run(t)` should be in a `try` / `finally`, I think we may have discussed elsewhere being able to add cleanup callbacks to `t`. Would that help?

**Comment by szmarczak** [comment]
> Why not apply this hook only when you write your test with test.serial?

That's what I'm currently doing: https://github.com/sindresorhus/got/pull/872

The thing is that you need separate hooks for serial and non-serial tests.

> Would you say we should expose this in beforeEach hooks as well?

:+1:

> The await run(t) should be in a try / finally, I think we may have discussed elsewhere being able to add cleanup callbacks to t. Would that help?

You're right. Let me propose another solution:

```js
const hook = async (t, run) => {
    if (t.isSerial) {
        t.context.clock = lolex.install();

        // Maybe this should be an `afterEach` hook?
        t.after(() => {
            clock.uninstall();
        });
    }
    ...
    await run(t, clock);
    ...
};

**Comment by novemberborn** [comment]
> > Why not apply this hook only when you write your test with test.serial?
> 
> That's what I'm currently doing: [sindresorhus/got#872](https://github.com/sindresorhus/got/pull/872)
> 
> The thing is that you need separate hooks for serial and non-serial tests.

To clarify, by "hook" here you mean a helper function, not a `.beforeEach()` hook?

I'm not sure it's any clearer if the helper function magically sets up lolex, but only for serial tests. Perhaps you could compose `withServer` and `withLolex`?

> ```js
>         t.after(() => {
>             clock.uninstall();
>         });
> ```

Yes I think something like this was proposed elsewhere. Maybe `t.teardown()` or something.

With `t.try()` (opt-in required) in 2.4 you could do:

```js
const hook = async (t, run) => {
	const clock = lolex.install()
	const attempt = await t.try(run, clock)
	clock.uninstall()
	attempt.commit()
})
```

Which removes the need for teardown hooks, at least for this use case.

---

That leaves us with whether it's useful for code to run whether it's running serially. I'm not super convinced that it would make your use case better — though it could be useful to ensure `withServerAndLolex` is called from inside a serial test.

**Comment by szmarczak** [comment]
> To clarify, by "hook" here you mean a helper function, not a .beforeEach() hook?

:+1: (sorry)

> I'm not sure it's any clearer if the helper function magically sets up lolex, but only for serial tests. Perhaps you could compose withServer and withLolex?

:+1: didn't know that, thanks.

> That leaves us with whether it's useful for code to run whether it's running serially. I'm not super convinced that it would make your use case better — though it could be useful to ensure withServerAndLolex is called from inside a serial test.

Exactly.

**Comment by novemberborn** [comment]
> > That leaves us with whether it's useful for code to run whether it's running serially. I'm not super convinced that it would make your use case better — though it could be useful to ensure withServerAndLolex is called from inside a serial test.
> 
> Exactly.

I'm just not sure this provides enough of a guard rail. *Maybe* if we see test helpers being shared via npm, but in that case perhaps the solution is in the way tests are declared, not exposing whether a test is run serially.

I'll leave this open to gather further feedback.

**Comment by szmarczak** [comment]
> perhaps the solution is in the way tests are declared, not exposing whether a test is run serially.

Why not?

**Comment by novemberborn** [comment]
I'm not sure if within a project there's enough of a need for helpers to ensure they're running serially.
