### ISSUE TITLE
array.forEach() behaves unpredictably 

### ISSUE THREAD

**Issue by ndekross** [avajs/ava#2244]
## Description

Thanks for the awesome tool that's really easy to use. I'm trying to use Ava with dynamically generated asynchronous tests and sometimes it behaves unpredictably. My current problem is that I don't understand why the code that works with simple `for / of` loop doesn't work with `Array.forEach()` function. It might be a feature, but I want to understand the behavior. 

### Test Source

```js
// This is the function that I'm testing. It's basically a wrapper 
// around the standard resolveMx()function from the
// Node's DNS module. The function makes DNS request 
// and checks if there are MX records for the given domain

function validateMx(domain, timeout = 500, maxAttempts = 2){
  return new Promise((resolve, reject) => {
    let done = false;
    function attempt(n){
      dns.resolveMx(domain, (failed, result) => {
        done = true;
        if (failed) reject(failed);
        else resolve(true);
      });
      setTimeout(() => {
        if (n > maxAttempts) reject(new Error("MX check timed out"));
        if (done) return;
        attempt(n + 1);
      }, timeout);
    }
    attempt(0);
  });
}

// function that reads emails from the list
function readEmailsFrom(list) {
  return new Promise((resolve, reject) => {
    let emails = [];
    fs.readFile(__dirname + `/${list}.txt`, 'utf-8', (err, file) => {
      if (err) reject(err);
      emails = file.split('\n');
      resolve(emails);
    });
  });
}

// This tests work as intended
test(`validateMx() – should return true`, async t => {
  // This reads separate txt file that contains some emails 
  // and puts these emails into an array
  const emails = await readEmailsFrom('valid-emails');
  t.plan(emails.length);
  for (let email of emails) {
    const [, domain] = email.split('@');
    const validation = await validateMx(domain);
    t.true(validation, domain);
  } 
});
// > ✔ validateMx() – should return true (468ms)

//This test is essentially the same as previous but using array.forEach
test(`validateMx() – should return true`, async t => {
  const emails = await readEmailsFrom('valid-emails');
  t.plan(emails.length);
  // ↓↓↓ right here
  emails.forEach(async email => {
    const [, domain] = email.split('@');
    const value = await validateMx(domain);
    t.true(value, domain);
  });
});
// It looks like that none of the tests are getting executed
//> ✖ validateMx() – should return true Planned for 8 assertions, but got 0.
```

### Error Message & Stack Trace

```
✖ validateMx() – should return true

  1 test failed

  validateMx() – should return true


  Planned for 8 assertions, but got 0.
npm ERR! Test failed.  See above for more details.
```

### Config

```json
{
  "ava": {
    "verbose": true
  }
  }
}
```

### Command-Line Arguments

```
nyc ava
```

## Environment

```
Node.js v12.10.0
darwin 19.0.0 (macOS Catalina)
ava 2.3.0
npm 6.10.3
```

**Comment by Gwenio** [comment]
> emails.forEach(async email => {

The issue is you are giving forEach an async function. It does not wait for the async functions to finish.

You would need something like: 

```javascript
// modified forEach test.
test(`validateMx() – should return true`, async t => {
  const emails = await readEmailsFrom('valid-emails');
  t.plan(emails.length);
  // ↓↓↓ right here
  await Promise.all(emails.map(async email => {
    const [, domain] = email.split('@');
    const value = await validateMx(domain);
    t.true(value, domain);
  }));
});
```

**Comment by ndekross** [comment]
Thanks for the neat explanation! 

So basically instead of using `forEach` I process the array values with my async function and then pass the whole array to Promise.all and wait until it resolves, right? It doesn't look as straightforward as I hoped it would be. Is there any advantage of the `for` loop way?

**Comment by Gwenio** [comment]
> Thanks for the neat explanation!
> 
> So basically instead of using `forEach` I process the array values with my async function and then pass the whole array to Promise.all and wait until it resolves, right? It doesn't look as straightforward as I hoped it would be. Is there any advantage of the `for` loop way?

For loops do not create new async operations that need to be awaited. Only async operation started inside the loop need to be awaited. However, if your test was not inside an async function then you would need to map to async functions to make await available inside the loop body.

If the Promise.all() is the last step in your test, you could return it instead of awaiting it, since AVA will await a returned promise.

**Comment by novemberborn** [comment]
I assume `validateMx()` makes network calls? You may not want to do too many of those concurrently either. If you want to run them serially, use:

```js
test(`validateMx() – should return true`, async t => {
  const emails = await readEmailsFrom('valid-emails');
  t.plan(emails.length);
  for (const email of emails) {
    const [, domain] = email.split('@');
    const value = await validateMx(domain);
    t.true(value, domain);
  }
});
```

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by ndekross** [comment]
> If the Promise.all() is the last step in your test, you could return it instead of awaiting it, since AVA will await a returned promise.

That's good to know. 

> I assume `validateMx()` makes network calls? You may not want to do too many of those concurrently either. If you want to run them serially, use:
> ```js
> test(`validateMx() – should return true`, async t => {
>   const emails = await readEmailsFrom('valid-emails');
>   t.plan(emails.length);
>   for (const email of emails) {
>     const [, domain] = email.split('@');
>     const value = await validateMx(domain);
>     t.true(value, domain);
>   }
> });
> ```

That's exactly what I did initially but then I decided to try the `forEach` way and it didn't work out so well. As I don't see much difference between the `for` loop and the Array `forEach` method I got interested why they behave differently. Hence my post. 

Anyway, if anyone is interested I rewrote the whole test generator function and it's easy generate all cases with just one function from a text file (as opposed to separately testing valid emails, invalid emails, etc).

The text file has the following structure: the test case is separated from the expected output the with the asterisk.

```
hello@world.invalid*The top level domain .INVALID doesn't exist
#.email@domain.com*Leading dot in address is not allowed
email.domain.com*Missing @ sign
tim.cook@apple.com*true
```

Here's the function itself.
```js
(async () => {
  const testCases = await fs.readFile(__dirname + `/test-cases.txt`, 'utf-8');
  testCases
    .split('\n')
    .filter(tc => tc[0] !== '#') //filters out commented test-cases 
    .map(tc => tc.split('*'))
    .forEach(([email, result]) => {
      test(`validateEmail('${email}') —> ${result}`, async t => {
        try {
          if (result === "true") result = true;
          return t.assert(await validateEmail(email) === result);
        }
        catch (error) {
          return t.assert(error.message === result);
        }
      });
    });
})();
```

**Comment by ndekross** [comment]
Actually it got me thinking. That would be awesome to have a simple DSL for writing test cases that could be parsed by AVA. One case is not usually enough to test something beyond one liners and writing lots test cases gets old pretty fast.

... or am I just ignorant and someone already did it?

**Comment by novemberborn** [comment]
AVA does have some tricks up its sleeve. I'd solve your problem like this:

```js
const validateCase = async (t, email, result) => {
	if (result === 'true') {
		t.true(await validateEmail(email))
	} else {
		await t.throwsAsync(validateEmail(email), { message: result })
	}
}
validateCase.title = (_, email, result) => `validateEmail('${email}') -> ${result}`

const testCases = fs.readFileSync(`${__dirname}/test-cases.txt', 'utf-8')
	.split('\n')
	.filter(tc => tc[0] !== '#') //filters out commented test-cases 
	.map(tc => tc.split('*'))

for (const case of testCases) {
  test(validateCase, ...case)
}
```

See https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#reusing-test-logic-through-macros.
