### ISSUE TITLE
`t.try()` assertion feedback

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2250]
Please leave your feedback on the `t.try()` assertion here.

**Comment by iamstarkov** [comment]
it will be nice to see some new recipes on how this feature can be used like property based testing with jsverify, testcheck-js.

**Comment by qlonik** [comment]
I've had a snippet how to use it with jsverify from a long time ago. I recently updated it for shipped `t.try()`. There are both variants for TS and JS. JS has one variant which is slightly nicer, but I cannot create types for it in TS.

https://gist.github.com/qlonik/9a297285284d71f7da47022f120ef4ad

**Comment by iamstarkov** [comment]
@qlonik thanks, do you mind publishing it to npm?

**Comment by mightyiam** [comment]
My feedback is that I couldn't find the docs for the `t.try` assertion :confused: :laughing: :boom: :man_shrugging: :roll_eyes:

**Comment by novemberborn** [comment]
@mightyiam we have an issue for that though 😉 https://github.com/avajs/ava/issues/2247

This is one of the reasons it's an experimental feature. The code was done, things like our ESLint plugin weren't, and the same with the documentation.

**Comment by iamstarkov** [comment]
I mean, it is a little bit hard to experiment with a feature you can't read about

**Comment by novemberborn** [comment]
This is now available without a flag in AVA 3.4.0!
