### ISSUE TITLE
trying to install ava for contributing to the 100% coverage

### ISSUE THREAD

**Issue by dhuang612** [avajs/ava#2252]
I forked the repo and then cloned my version to my computer. 
I then update it to get up to date with your version.
When I try to run npm install I get the following error: 
```
Error: EACCES: permission denied, open '/Users/danhuang/.npm/_cacache/index-v5/24/8a/b67c8c7ae732e85fdb0b589b0f4936e49e40b919175e011731b0021c0ece'
```
using node version 
10.16.3

I have read through the contribution guide and haven't seen any other instructions related to getting this project setup.
Can we get a guide on setting up the environment for contributing? 
I checked the readme and we only have one for getting the repo setup for testing purposes in other projects.

Thanks!

**Comment by sindresorhus** [comment]
That's a problem with npm, not AVA. You can get npm support here: https://npm.community

**Comment by dhuang612** [comment]
When I google the error it talks about having tried to installing a npm package with sudo. 
I am only having this npm error with this project. I can and have installed other npm packages since yesterday so I don't think that is the error
