### ISSUE TITLE
TryFn type makes ExecutionContext not covariant

### ISSUE THREAD

**Issue by vogre** [avajs/ava#2253]
## Description

When moving some utility initialization into a separate file / module, we sometimes use a base `BaseContext` interface which could be extended as needed by other tests. The issue can be worked around with by not defining functions using the `ExecutionContext` type, but sometimes would just be more verbose and in other cases less type-safe.

### Test Source

```typescript
import anyTest, { TestInterface, ExecutionContext } from 'ava';

interface BaseContext  { a: string; }
interface Context extends BaseContext { b: string; }

const test = anyTest as TestInterface<Context>;
function baseBefore(t: ExecutionContext<BaseContext>){ }
test.beforeEach(baseBefore);
```

### Error Message & Stack Trace

```
TS2345: Argument of type '(t: ExecutionContext<BaseContext>) => void' is not assignable to parameter of type 'OneOrMoreMacros<[], Context>'.
  Type '(t: ExecutionContext<BaseContext>) => void' is not assignable to type 'UntitledMacro<[], Context>'.
    Types of parameters 't' and 't' are incompatible.
      Type 'ExecutionContext<Context>' is not assignable to type 'ExecutionContext<BaseContext>'.
        Types of property 'try' are incompatible.
          Type 'TryFn<Context>' is not assignable to type 'TryFn<BaseContext>'.
            Types of parameters 'fn' and 'fn' are incompatible.
              Type 'EitherMacro<any, BaseContext>' is not assignable to type 'EitherMacro<any, Context>'.
                Type 'UntitledMacro<any, BaseContext>' is not assignable to type 'EitherMacro<any, Context>'.
                  Type 'UntitledMacro<any, BaseContext>' is not assignable to type 'UntitledMacro<any, Context>'.
                    Type 'BaseContext' is not assignable to type 'Context'.
```

### Config

Default

### Command-Line Arguments

```
tsc
```

## Environment

TypeScript 3.6.3, AVA 2.4.0

**Comment by novemberborn** [comment]
Yea something like that should work.

I think we're a little stuck here. Casting `test` is awkward. Typing macros is awkward. I'm not sure where to take this other than that sometimes, for TypeScript, it may be better to have explicit functions that created typed things rather than leaving everything to be inferred.

**Comment by qlonik** [comment]
I tried adding this bandaid solution: https://github.com/qlonik/ava/tree/bug-2253.

This "fix" is awkward and I'm not sure if there are going to be more issues because of this. But maybe you could try and see if it solves the issue for you?

**Comment by Gwenio** [comment]
> I tried adding this bandaid solution: https://github.com/qlonik/ava/tree/bug-2253.
> 
> This "fix" is awkward and I'm not sure if there are going to be more issues because of this. But maybe you could try and see if it solves the issue for you?
> 
> EDIT:
> It also means you need to type `baseBefore` as:
> 
> ```ts
> function baseBefore(t: ExecutionContext<BaseContext, Context>){}
> ```

@qlonik 

I think the place for a long term fix is the Implementation and Macro types. Here are some examples, though be aware I have not tried implementing the following changes. So they might not work out.

The idea behind them is to have them allow any `ExecutionContext<Base>` as long as `Context` extends `Base`.

```typescript
// current
export type Implementation<Context = unknown> = (t: ExecutionContext<Context>) => ImplementationResult;
export type CbImplementation<Context = unknown> = (t: CbExecutionContext<Context>) => ImplementationResult;
export type UntitledMacro<Args extends any[], Context = unknown> = (t: ExecutionContext<Context>, ...args: Args) => ImplementationResult;
// ... rest of macro types

// modified
export type Implementation<Base, Context extends Base = unknown> = (t: ExecutionContext<Base>) => ImplementationResult;
export type CbImplementation<Base, Context extends Base = unknown> = (t: CbExecutionContext<Base>) => ImplementationResult;
export type UntitledMacro<Args extends any[], Base, Context extends Base = unknown> = (t: ExecutionContext<Base>, ...args: Args) => ImplementationResult;
// ... rest of macro types
```

This would of then require a cascade of changes to  TestInterface and its friends.

```typescript
// modified TryFn
export interface TryFn<Context = unknown> {
	<Args extends any[], Base>(title: string, fn: EitherMacro<Args, Base, Context>, ...args: Args): Promise<TryResult>;

	<Args extends any[], Base>(title: string, fn: [EitherMacro<Args, Base, Context>, ...EitherMacro<Args, Base, Context>[]], ...args: Args): Promise<TryResult[]>;

	<Args extends any[], Base>(fn: EitherMacro<Args, Base, Context>, ...args: Args): Promise<TryResult>;

	<Args extends any[], Base>(fn: [EitherMacro<Args, Base, Context>, ...EitherMacro<Args, Base, Context>[]], ...args: Args): Promise<TryResult[]>;
}
// modified TestInterface
export interface TestInterface<Context = unknown> {
	<Base>(title: string, implementation: Implementation<Base, Context>): void;

	<T extends any[], Base>(title: string, macros: OneOrMoreMacros<T, Base, Context>, ...rest: T): void

	<T extends any[], Base>(macros: OneOrMoreMacros<T, Base, Context>, ...rest: T): void;

// ... rest of TestInterface is unchanged

}

// ... other interfaces that the changes apply to
```
