### ISSUE TITLE
still experiencing issue with this repo and a permission issue related to npm

### ISSUE THREAD

**Issue by dhuang612** [avajs/ava#2254]
Hi,

I opened an issue yesterday about trying to get this project installed on my local machine for contributing. 
The error I am getting is related to npm and when I researched into it, the responses were related to having installed an npm package via sudo which I haven't done. 
I am also not experiencing any issues with getting other npm packages installed for other projects so I don't think this is an issue on my end. 

Thanks

**Comment by sindresorhus** [comment]
Duplicate of #2252

**Comment by sindresorhus** [comment]
As I already commented, this is not the place to get npm install support.
