### ISSUE TITLE
Combining async helper functions and callback tests

### ISSUE THREAD

**Issue by szmarczak** [avajs/ava#2259]
```js
const wrapper = async run => {
	await run(Math.random());
};

t.cb('example', wrapper, (t, someData) => {
	t.cb();
});
```

gives:

> Do not return promises from tests declared via `test.cb(...)`, if you want to return a promise simply declare the test via `test(...)`

**Comment by novemberborn** [comment]
`wrapper` being an async function returns a promise. So either make it not an async function, or change `run` to return a promise as well.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by szmarczak** [comment]
> change run to return a promise as well.

I cannot as I'm testing callback style functions.

> make it (the wrapper) not an async function

That's nonsense. This violates the DRY rule. There's no point in having the same code written using `await promise` and `promise.then`.

This is my workaround:

```js
const wrapper = async (t, run) => {
	await run(t, Math.random());
};

const cb = callbackStyleFunction => {
    return (t, ...args) => new Promise((resolve, reject) => {
		let calledEnd = false;

        const tProxy = new Proxy(t, {
            get: (target, property) => {
				if (property === 'end') {
					return error => {
						if (calledEnd) {
							t.fail('`t.end()` called more than once');
							return;
						}

						calledEnd = true;

						if (error) {
							reject(error);
						} else {
							resolve();
						}
					};
				}

				return target[property];
			}
        });

        callbackStyleFunction(tProxy, ...args);
    });
};

test('example', wrapper, cb((t, someData) => {
	console.log('data:', someData);

	setTimeout(() => {
		t.pass();
		t.end();
	}, 1000);
}));
```

gives the desired result:

```
data: 0.8742159668795217
  ✔ example (1s)

  1 test passed
```

@sindresorhus What's your thoughts about this?

**Comment by novemberborn** [comment]
> I cannot as I'm testing callback style functions.

I sympathize, but `test.cb()` is really just meant for simple legacy callback style APIs. We even have an [ESLint rule to disallow it](https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/no-cb-test.md).

I'd do something like this:

```js
const wrapper = async (t, run) => {
	await new Promise(resolve => run(t, resolve, Math.random()));
};

t.cb('example', wrapper, (t, done, someData) => {
	done();
});
```

**Comment by szmarczak** [comment]
@novemberborn As of now your solution gives an error:

```
Error: Do not return promises from tests declared via `test.cb(...)`, if you want to return a promise simply declare the test via `test(...)`
```

**Comment by novemberborn** [comment]
@szmarczak sure, I guess I meant without the `.cb` bit:

```js
const wrapper = async (t, run) => {
	await new Promise(resolve => run(t, resolve, Math.random()));
};

test('example', wrapper, (t, done, someData) => {
	done();
});
```
