### ISSUE TITLE
Bug: require does not read environmentVariables properly

### ISSUE THREAD

**Issue by ffMathy** [avajs/ava#2266]
I tried looking for existing issues but couldn't find any that match my exact scenario.

I'm trying to use `ts-node` with Ava, and everything works fine at first glance.

However, if I then have a declarations (`.d.ts`) file:

```typescript
var ENV_TEST: boolean;
```

And I load my tests, TypeScript files referencing that variable will give the error:

> ReferenceError: ENV_DEV is not defined

I already set `TS_NODE_FILES` to `true`, and that didn't help.

Does anyone have a working sample somewhere using `ava` and `ts-node` that includes declaration (`.d.ts`) files?

**Comment by ffMathy** [comment]
It seems that the underlying issue is that `environmentVariables` in the config are actually ignored and invisible to the `require` of `ts-node/register`.

I made a small project to reproduce the issue: https://github.com/ffMathy/ava-repro

Note that if you run `npm test`, you get an error that a declared variable is unavailable. This is similar to running just `ts-node test.ts` - same error.

However, if you run `SET TS_NODE_FILES=true && ts-node test.ts` on Windows or `TS_NODE_FILES=true && ts-node test.ts` on Linux, the problem is gone.

In that sense, the problem should also be gone when setting `environmentVariables` in the config.

**Comment by novemberborn** [comment]
`environmentVariables` should be available under `process.env` within the worker processes.

Is there something magical in `ts-node` which exposes environment variables as actual global variables in the process?

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
