### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by tdotholla** [avajs/ava#2273]
[This package](https://www.jsdelivr.com/package/npm/ava) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by sindresorhus** [comment]
AVA has `index.js` file, which means it doesn't need a `main` field. This is in accordance with the package.json spec.
