### ISSUE TITLE
Take screenshots during automated browser tests.

### ISSUE THREAD

**Issue by shofel** [avajs/ava#2275]
Here is the answer to conversation on [spectrum](https://spectrum.chat/ava/general/taking-a-screenshot-when-automated-browser-test-fails~3a4f1efd-12f7-4d94-ab16-7d1e824ada14). Markdown is poorly rendered there, so I moved it here. I hope it's not as arrogant doing like that :)

#### TLDR
I write automated browser tests. And I want them to take screenshots for me. The best thing I could imagine is a screenshot after each test assertion.
It would be nice, though, to have a screenshot of the page at the end of every test.

I've done the later with two different ways:
1. by injecting title of the test to `t.context` by patching AVA code
2. by decorating `test` function with imitation of `beforeEach` and `afterEach` hooks

## Yeah, thanks!
I believe `t.try()` could help me here. But at the first sight it's unclear, how exactly.

What I need is just a bit of introspection on a test, when executing the hooks.
Two things are particularly interesting: 1. Title of the test; 2. Outcome of the test (fail/success).

### Mocha and Jest - NO
They have `afterEach` hooks, which are nullary functions. So that, no info available in a hook callback.

### Cucumber - YES
https://cucumber.io/docs/cucumber/api/#after
Callback function for `After` hook receives `scenario`.
> The scenario parameter is optional. If you use it, **you can inspect the status of the scenario.**
> For example, you can take a screenshot with WebDriver for failed scenarios and embed them in Cucumber’s report.

### Codeception - YES
https://stackoverflow.com/a/38568120/1991011 (`delete_successful`)
Make screenshots after all the tests, but then delete successful ones.

### 1. Get visual feedback for each step
- screenshot after each step
- name of file contains
  - name of test
  - name of step
  - outcome of step (success or fail)

### 2. Get visual feedback after the test
- ? do we really need it, when already having feedback for each step?

### 3. (BONUS) Then, when reviewing the results, I want to look at all the pictures of failed steps
Honestly, just guessing for now. Will observe behaviour of myself))
- do I really behave like this?
- place the pictures of failed steps in a separate folder

### Another reporter: NO

Reporting at the granularity of a single assertion looks interesting.  
- Can we use a reporter for that? Like a `screenshot reporter`.
- Can we run with more than one reporters at once?
- What about timing? When `runStatus.emitStateChange(...)` called, there is no time guaranteed to take a screenshot.

### Use `hooks`: MAYBE

We usually think of hooks like of `set up` and `tear down`, that is "prepare the environment" and "cleanup the changes".

In AVA we have `beforeEach` and `afterEach`, which share a reference to the common `context` - with each other and with the test they belong to. So then, the semantics of them is "some actions related to a particular test". Taking a screenshot when test fails perfectly fits here.

### Use `helpers`: NO?

@see https://github.com/avajs/ava/blob/master/docs/recipes/puppeteer.md

The args of a helper function are only `t` and `run`. That is no `title` presented.

### Decorate `test`: MAYBE

I run this code, and it works: screenshots are taken, tests are performed and reported.

- pro: no patching of AVA needed
- cons: feels dirty. If one is allowed doing this at all? I mean, wrapping `test` into a function.
- cons: adhoc implementation of `test.beforeEach` and `test.afterEach`

```js
/* util */
let first = xs => xs[0]

let prepareBrowser = context => {
  context.browser = await puppeteer.launch()
  context.page = await t.context.browser.pages().then(first)
}

let screenshot = async ({page, title}) =>
  page.screenshot({path: `${__dirname}/screenshots/${title}.png`})

/**
 * Decorate `test`,
 *
 * Set up: prepare the `browser` with a `page`.
 * Tear down: take a screenshot, and close the `page`.
 */
let test_ = (title, f) => {
  test(title, async t => {
    /* Imitate `beforeEach`: Set up the browser. */
    await prepareBrowser(t.context)

    try {
      await f(t)
    } finally {
      /* Imitate `afterEach`: Tear down the browser. */

      await screenshot({page: t.context.page, title})
      await t.context.page.close()
    }
  })
}
```

**Comment by novemberborn** [comment]
> Another reporter: NO

Whilst long-term I'd love to have more structured logging output you could build on top off, that's a long way off.

> Use `helpers`: NO?
> @see https://github.com/avajs/ava/blob/master/docs/recipes/puppeteer.md [](/avajs/ava/blob/HEAD@{2019-10-21T19:08:23Z}/docs/recipes/puppeteer.md)
> 
> The args of a helper function are only `t` and `run`. That is no `title` presented.

`t.title` holds the test's title.

> Decorate `test`: MAYBE

This isn't horrible, but it's better done as a helper.

---

> Cucumber - YES
> https://cucumber.io/docs/cucumber/api/#after
> Callback function for `After` hook receives `scenario`.
> 
> > The scenario parameter is optional. If you use it, **you can inspect the status of the scenario.**
> > For example, you can take a screenshot with WebDriver for failed scenarios and embed them in Cucumber’s report.

I believe his has been proposed at one point, though I can't immediately find that issue now.

I have limited bandwidth so I'm reluctant to add API surface. I'd really like this to be explored through `t.try()` first, in combination with a helper.

---

> Here is the answer to conversation on [spectrum](https://spectrum.chat/ava/general/taking-a-screenshot-when-automated-browser-test-fails~3a4f1efd-12f7-4d94-ab16-7d1e824ada14). Markdown is poorly rendered there, so I moved it here. I hope it's not as arrogant doing like that :)

Heh, yea, I'm always afraid to type too much there 😄 

That said, I'm closing this issue for housekeeping purposes, but let's keep the conversation going.
