### ISSUE TITLE
Default patterns for fixtures and helpers

### ISSUE THREAD

**Issue by sholladay** [avajs/ava#2282]
I'd like to discuss the default behavior of matching fixtures and helpers, which changed recently.

From the AVA 2.0 [release notes](https://github.com/avajs/ava/releases/tag/v2.0.0):

> Files inside `fixtures` directories are no longer ignored, and will now be treated as test files.

> AVA used to treat all files inside a helpers directory as test helpers. ... Instead you can now specify glob paterns to find these helpers

First of all, I want to say that I know a lot of hard work has gone into this over the years, in order to support different use cases and to optimize performance, etc. I really appreciate the struggle and everything that went into the decisions leading up to the changes in AVA 2.0.

That being said, I confess I much prefer AVA 1.0 in terms of how it automatically understands what to do with my test fixtures and helpers. I want to see if there is some way we can get back to a place where AVA treats them correctly out of the box, at least for simple/common cases.

Almost every app I've made that uses AVA has needed helpers and fixtures. Even small libraries that I want to test thoroughly often have multiple fixtures. I put them in `test/helpers` and `test/fixtures`, respectively. This is so common that I feel burdened by having to specify these paths in the `ava` config in package.json. Obviously, it's not a _huge_ deal, and there are workarounds like using a leading underscore in the filename, but it's an annoyance and it's something that I see as a regression from 1.0 to 2.0.

AVA 1.0 used very loose patterns, like `**/helpers/**`, and of course this was slow in big projects with many files. But AVA 2.0 seems to have just abandoned the defaults entirely, which seems like an over-correction.

I'd like to propose that the defaults should simply be `test/helpers/**` and `test/fixtures/**`. This would perform well while still being useful and fairly intuitive. It wouldn't cover every use case, some people will still need to override the defaults, but I believe that good defaults are very important.

**Comment by sindresorhus** [comment]
For `test/helpers`, I'm hoping that we can get rid of the concept of helpers eventually. It was only added as we needed to be able to only transpile test files without transpiling source files. This is no longer something we should aim for.

For `test/fixtures`, I like the convention and I've been inconvenienced by the change too, but I also appreciate to move for less magic, so I'm conflicted.

https://github.com/avajs/ava/issues/2155 will at least help the situation and support other use-cases too, as you would be able to use `_fixtures` without any config.

**Comment by novemberborn** [comment]
> For `test/helpers`, I'm hoping that we can get rid of the concept of helpers eventually. It was only added as we needed to be able to only transpile test files without transpiling source files. This is no longer something we should aim for.

Even without transpilation-by-default it's still a useful concept allowing you to compile test files differently from source files.

> For `test/fixtures`, I like the convention and I've been inconvenienced by the change too, but I also appreciate to move for less magic, so I'm conflicted.

Heh, me too. One problem is the naming conventions around these directories. `fixture`, `fixtures`… `__fixture(s)__`?

The other issue is how to undo a default exclusion.

#2155 is just about the safest approach.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by sholladay** [comment]
> The other issue is how to undo a default exclusion.

My preferred solution for this is that if the test helper patterns are specified in the user's config, then they should be used as-is, no merging with the default patterns. That way, overriding the defaults is simple.

In the case where a user does want to add to the defaults rather than replace them, AVA could support an `additionalHelpers` option.

This approach is inspired by hapi's [CORS settings](https://github.com/hapijs/hapi/blob/master/API.md#-routeoptionscors), where `headers` has a default value that is secure and spec compliant. If you specify `headers`, then the list is completely overridden. Finally, hapi adds in `additionalHeaders`, if any. The end result is very elegant, it's easy for the user to choose what to do and I find the semantics to be quite clear and easy to remember.

This same idea can be applied to any of AVA's options, but I think it especially makes sense for the list of file patterns, where good defaults are very useful but the user should still have flexibility to tweak them.

**Comment by novemberborn** [comment]
> My preferred solution for this is that if the test helper patterns are specified in the user's config, then they should be used as-is, no merging with the default patterns. That way, overriding the defaults is simple.

Ah yes, that is what we do now.

So then the question is what exclusion patterns we add to the default list? And, how do we specify these without running into performance issues?

**Comment by sholladay** [comment]
> The other issue is how to undo a default exclusion.

My preferred solution for that is, let's say an option such as `helpers` is used in the config, then the patterns in the config should be used as-is, no merging with the default patterns. That way, overriding the defaults is simple.

In the case where a user does want to add to the defaults rather than replace them, AVA could support an `additionalHelpers` option, which that user would use instead.

This approach is inspired by hapi's [CORS settings](https://github.com/hapijs/hapi/blob/master/API.md#-routeoptionscors), where `headers` has a secure and spec compliant default. If you provide `headers`, then it completely overrides the default headers list. Finally, the `additionalHeaders` are added in, if any. I love how flexible it is while still being simple and with no magic.

This approach could be applied to any of AVA's options, but I think it especially makes sense for lists of glob patterns where a default is desirable but may or may not be problematic in some edge cases.

**Comment by sholladay** [comment]
I think the performance problems can largely be traced back to how loose the old patterns were. For example, in AVA 1.0, the default patterns tried to support the use case of people who put tests next to their code. Patterns like `**/helpers/**/*` are inherently slow. It forces the system to crawl over huge build directories, media assets, and other nonsense.

My suggestion is to have the default pattern use a specific root. `test/helpers/**/*` or even `test/**/helpers/**/*` should be plenty fast. (The same principle applies to the other options as well.)

I think it would be perfectly reasonable for AVA 3.0 to say, "The default patterns support tests and helpers and fixtures, but only in the `test` directory, for performance reasons. If you keep tests next to your code, you'll need to use `files`, `helpers`, and `fixtures` options, as appropriate for your setup."

**Comment by novemberborn** [comment]
> My suggestion is to have the default pattern use a specific root. `test/helpers/**/*` or even `test/**/helpers/**/*` should be plenty fast. (The same principle applies to the other options as well.)

We currently look for a set of directory and file names, anywhere in your project: 
https://github.com/avajs/ava/blob/a69e63578b9cd2b0b74d656a666bbad260a88680/lib/globs.js#L45:L52

```js
	const defaultTestPatterns = [
		`**/__tests__/**/*.${extensionPattern}`,
		`**/*.spec.${extensionPattern}`,
		`**/*.test.${extensionPattern}`,
		`**/test-*.${extensionPattern}`,
		`**/test.${extensionPattern}`,
		`**/test/**/*.${extensionPattern}`,
		`**/tests/**/*.${extensionPattern}`
	];
```

What you're suggesting would require us to cut down on these patterns and become much more prescriptive. E.g. only support `test/**/*.${extensionPattern}`. Maybe allow for a `src/` prefix too.

We could do that, but I feel like there's many projects for which that's not a useful default.

Perhaps a different approach may be to define a set of directory names which are considered to be fixtures, e.g. `fixture`, `fixtures`, `__fixtures__`. Then we can filter out any test & helper files that are inside such a directory. Because we're not doing any extra globs there shouldn't be much of a performance hit.

**Comment by novemberborn** [comment]
This discussion is making me thing about the nature of helpers and precompilers. Since we're moving Babel support into a separate package, perhaps there is a way to make the helper stuff a responsibility of that package too. At least until such time as that package gains the ability to compile entire projects.

(Essentially, the `babel` configuration will be owned by a separate package and thus can evolve independently from AVA itself.)

**Comment by sholladay** [comment]
> We currently look for a set of directory and file names, anywhere in your project:

That makes the new default globs for helpers even more confusing. Be consistent about it. If you are OK with crawling every directory for tests, despite the performance concerns, then don't be overly restrictive about helpers just because of the same performance concerns. My helpers are not buried in some deeply nested place in a random directory within my project, they are in an easy to find place, both for a human and computationally speaking.

**Comment by novemberborn** [comment]
I've been thinking about this some more.

Our current separation of test `files`, `helpers` and `sources` is driven by our integrated Babel compilation, where the goal was to also compile the sources. We never got there, though.

Now that we're removing Babel (and providing it through a separate package) we should revisit this. The Babel provider can do extra globbing in order to find helper files to compile. And eventually it can deal with source compilation, too. This means we can remove the `helpers` configuration from AVA itself.

We do use the `sources` patterns so that the watcher knows *not* to restart when non-test/helper/source files are changed. This would be better achieved through a `ignoredByWatcher` configuration.

Finally then, the question of how to stop files, ordinarily selected as test files, from being treated as such. This could be done through negated glob patterns to start. Taking the default patterns:

```js
`**/__tests__/**/*.${extensionPattern}`,
`**/*.spec.${extensionPattern}`,
`**/*.test.${extensionPattern}`,
`**/test-*.${extensionPattern}`,
`**/test.${extensionPattern}`,
`**/test/**/*.${extensionPattern}`,
`**/tests/**/*.${extensionPattern}`
```

We could add:

```js
'!**/__tests__/**/__{helper|fixture}?(s)__/**/*',
'!**/test?(s)/**/{helper|fixture}?(s)/**/*',
```

If you specify `files` patterns you'd have to also add these exclusion patterns. We *could* manage them through a separate configuration as well, but I wonder if this is actually sufficient.

**Comment by sholladay** [comment]
I find negated patterns harder to read. But I like the idea of removing Babel from AVA's core and I like how that simplifies the configuration that is necessary. It would certainly be cool if I could tell AVA "these are my test files, ignore everything else". That would satisfy this issue for me, so long as the default made it easy to keep helpers and fixtures somewhere nearby the tests.

**Comment by novemberborn** [comment]
> It would certainly be cool if I could tell AVA "these are my test files, ignore everything else".

That'll definitely be the case, as long as you make your patterns specific enough 😉

**Comment by novemberborn** [comment]
https://github.com/avajs/ava/pull/2323 implements most of what we discussed here, aside from:

> We could add:
> 
> ```js
> '!**/__tests__/**/__{helper|fixture}?(s)__/**/*',
> '!**/test?(s)/**/{helper|fixture}?(s)/**/*',
> ```
