### ISSUE TITLE
Dynamic import fails with "Error: Not Supported"

### ISSUE THREAD

**Issue by florianb** [avajs/ava#2283]
## Description

In a Node lts/dubnium (12.13)-project using Fastify i widely adopt ES-Modules.

I use Ava for tests and (only during tests) i got the error message `Error: not supported`.

After some research it turned out to be an `import()`-statement in the fastify-service at the given route.

However https://github.com/avajs/babel-preset-stage-4 should already support `import()`.

~~> I was able to "fix" this for now by adding a `.babelrc`-file adding `@babel/plugin-syntax-dynamic-import` and `@babel/present-env`.~~ (False positive)

### Test Source

```js
// (Partial) test file
import {acceptance} from '../_helper'

acceptance.hook(test) // Things are loaded here
// ... - The test is irrelevant
```

```js
// (Partial) _helper.js
const newFastify = require('fastify')
const fastifyPlugin = require('fastify-plugin')
const App = require('../app')
// ...
export const acceptance = {
	hook: test => {
		test.beforeEach(async t => {
			const fastify = newFastify()
// ...
			fastify.register(fastifyPlugin(App))
// ...
```

```js
// (Partial) login-service (tested endpoint, loaded by the fastify-app)
module.exports = async fastify => {
	const Password = await import('../models/password.mjs')
// ...
```

### Error Message & Stack Trace

```
  ✔ first test
Error: Not supported
    at module.exports (<snip>/services/login.js:2:19)
    at Plugin.exec (<snip>/node_modules/avvio/plugin.js:89:17)
    at Boot.loadPlugin (<snip>/node_modules/avvio/plugin.js:175:10)
    at Task.release (<snip>/node_modules/fastq/queue.js:127:16)
    at worked (<snip>/node_modules/fastq/queue.js:169:10)
    at <snip>/node_modules/avvio/plugin.js:178:7
    at done (<snip>/node_modules/avvio/plugin.js:136:5)
    at check (<snip>/node_modules/avvio/plugin.js:147:7)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
  ✖ tests/features/sign-in.js exited with a non-zero exit code: 1

  1 test passed
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "verbose": true
  }
}
```

### Command-Line Arguments

```
ava
```

## Relevant Links

- This is similar to #1990 with the difference that the stage-4-support should include the dynamic import

## Environment

```
Node.js v12.13.0
linux 5.3.0-19-generic (Ubuntu 19.10)
ava: 2.4.0
npm: 6.12.0
```

# :gift_heart: 

As always - if there's anything i can do to fix it by creating an PR - please give me a hint!

**Comment by novemberborn** [comment]
AVA only compiles your test files, and `services/login.js` is not one of them. Have a look at https://github.com/avajs/ava/blob/master/docs/recipes/babel.md#compile-sources.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by florianb** [comment]
Wait

**Comment by novemberborn** [comment]
> I tried to install `@babel/plugin-syntax-dynamic-import` manually and added it to the ava-configuration:

That configuration is only used by AVA. You'll want to add a `babel.config.js` configuration instead. (Which AVA does extend by default, so at least you won't have to repeat it.)

**Comment by florianb** [comment]
Thank you for that hint @novemberborn!

Unfortunately this ends up in the first issue again (with one difference - the error is now thrown at login.js row 1 column 35; which is surely caused by the transpilation):

```
  ✔ first test
Error: Not supported
    at module.exports (<snip>/services/login.js:1:35)
    at Plugin.exec (<snip>/node_modules/avvio/plugin.js:89:17)
    at Boot.loadPlugin (<snip>/node_modules/avvio/plugin.js:175:10)
    at Task.release (<snip>/node_modules/fastq/queue.js:127:16)
    at worked (<snip>/node_modules/fastq/queue.js:169:10)
    at <snip>/node_modules/avvio/plugin.js:178:7
    at done (<snip>/node_modules/avvio/plugin.js:136:5)
    at check (<snip>/node_modules/avvio/plugin.js:147:7)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
  ✖ tests/features/sign-in.js exited with a non-zero exit code: 1

  1 test passed
```

```js
// babel.config.js
module.exports = api => {
	api.cache(true)

	return {
		plugins: [
			'@babel/plugin-syntax-dynamic-import'
		]
	}
}
```

**Comment by florianb** [comment]
This is ridiculous - even if Babel wouldn't provide a dynamic import, Node 12 provides it on its own.

Does it make sense to entirely disable Babel in Ava?

**Comment by novemberborn** [comment]
> This is ridiculous - even if Babel wouldn't provide a dynamic import, Node 12 provides it on its own.

Yea I don't really understand how all these things affect each other…

> Does it make sense to entirely disable Babel in Ava?

That's what I've been doing in my own projects, and then using `esm` at runtime. It's where AVA 3 is going, too (not including Babel by default, but letting you opt-in instead).

**Comment by florianb** [comment]
How do you do it? Just adding `babel: false` and `compileEnhancements: false`?

I guess AVA3 isn't testable yet?

**Comment by novemberborn** [comment]
> How do you do it? Just adding `babel: false` and `compileEnhancements: false`?

Yup.

> I guess AVA3 isn't testable yet?

No. Experimentally this is [available](https://github.com/avajs/ava/blob/master/docs/recipes/babel.md#experimental-feature-no-babel-out-of-the-box) in the `master` branch though.

**Comment by florianb** [comment]
Thanks again - i owe you a scotch!

**Comment by florianb** [comment]
Who ever comes here due to a similar error:

The error was caused by the missing `--experimental-modules`-flag.

Calling AVA like `NODE_OPTIONS='--experimental-modules'` npx ava` works on Node 12 & 13.
