### ISSUE TITLE
Clarification around ignore-by-default

### ISSUE THREAD

**Issue by creaux** [avajs/ava#2291]
I need to watch for subdirectory of node_modules as I have multiple interdependent packages.

Ava is using following https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#source-files-and-test-files to ignore all default places. 

I presume that it means even if I will add "node_modules/something" to "sources" key under configuration this will be ignored.

Is there a way how to override ignore-by-default patterns? Or any workaround?

**Comment by novemberborn** [comment]
This can't be overridden, sorry. Perhaps a symlink would work, in that AVA may detect the changes and rerun all tests. I'm not sure though.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
