### ISSUE TITLE
Feature Request: Configurable caller level for fail assertion message

### ISSUE THREAD

**Issue by clitetailor** [avajs/ava#2292]
## Description

For example the following code:

```js
function runTest(t, a, b) {
    t.is(a, b)
}

test('this assertion should fail', t => {
    runTest(t, 1, 1)
    runTest(t, 1, 2)
}
```

Would show the error message like this:

```
   3: function runTest(t, a, b) {
   4:   t.is(a, b)
   5: }
```

What i expect is that the assertion would show the error message where `runTest` is called:

```
    8:    runTest(t, 1, 1)
    9:    runTest(t, 1, 2)
   10: })
```

To do that i propose an API for increasing and decreasing the caller level in error message like this:

```js
function runTest(t, a, b) {
    t.level.increase(1)
    t.is(a, b)
    t.level.decrease(1)
}
```

Or

```js
function runTest(t, a, b) {
    t.level(2)
    t.is(a, b)
}
```
So that it would show the result as expected

**Comment by novemberborn** [comment]
The underlying problem is that we assume the assertion is called directly in the test implementation. If we could figure out this wasn't the case we could follow the stack trace and select a different call site. I'd prefer we improve *that* rather than add APIS like this. What do you think?

**Comment by clitetailor** [comment]
Oh, you right, the direct assertion is still needed to show the diff and the cause correctly. I'd like to add an option to extend the stack trace to include the original call site. It is very helpful to show where the test is called when the assertion fail.

**Comment by novemberborn** [comment]
We should explore what we want the error output to look like, when the assertion takes place outside of the test implementation.
