### ISSUE TITLE
Use `serialization` option for child process communication

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#2298]
`childProcess.fork` received a new option called `serialization`, which would let us use the V8 clone algorithm for passing messages instead of JSON. We could then pass types like `Buffer`.

It was added in Node.js 13.2.0, so we cannot use this until we target Node.js 14.

https://nodejs.org/en/blog/release/v13.2.0/
https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options

**Comment by novemberborn** [comment]
It's available in Node.js 12.16 now. There's a commit in #2478 which achieves this.

**Comment by novemberborn** [comment]
FWIW this requires https://github.com/nodejs/node/issues/34797 which I think may have been introduced in 16.4.2, but has not been backported to 14 or 12.

**Comment by novemberborn** [comment]
Done in https://github.com/avajs/ava/pull/3184.
