### ISSUE TITLE
Remove legacy t.throws() interface

### ISSUE THREAD

**Issue by szmarczak** [avajs/ava#2301]
I (and other people) often make this mistake:

```js
t.throws(() => {...}, TypeError, 'error message here');
```

while it should be:

```js
t.throws(() => {...}, {
	instanceOf: TypeError,
	message: 'error message here'
);
```

I propose something like this:

```js
t.throws(() => {...}, TypeError, 'error message here').describe('no error received');

// Actual solution
t.is(true, false, 'check failed');

// Expected solution
t.is(true, false).describe('check failed');
```

**Comment by novemberborn** [comment]
There's two separate concerns here. One is whether assertion messages are actually used, and if not, whether it be worthwhile freeing up that last argument by shifting to a more explicit API.

The other question is, if the last argument were to be available, whether we'd even want to use it with the `t.throws()` assertion.

Ultimately, requiring assertion messages to be provided explicitly would help us detect improper assertion usage. But it would be a breaking change. I'm not sure it's worth it.

I'd rather change `t.throws()` to require a matcher object.

**Comment by szmarczak** [comment]
> I'd rather change t.throws() to require a matcher object.

I agree. `assertion.describe()` would break too many things.

**Comment by sindresorhus** [comment]
> I'd rather change t.throws() to require a matcher object.

👍
