### ISSUE TITLE
Execute all files in single process concurrently

### ISSUE THREAD

**Issue by link89** [avajs/ava#2305]
`ava `only execute one file in one process. This is good for isolation, but I hope that `ava `can have an option to allow executing all files in single process, and believe that users will do concurrency control by themselves.

This is good for io intensive cases. In our case, we have 100+ test files with an average 5 tests per file. Our test is based on selenium and we have a browser pool that allows open 50 browsers at the same time.

If we use `ava -c 10` then we have to use `distributed lock` to ensure not more than 50 browsers are opened at the same time, or else case will failed, which is too complicated from my point of view.

If we use `ava -c 1` then we cannot make full use of our browser pool because we don't have many cases in a file.

An idea solution for this scenario is provide an option to allow execute all files at the same time in a process. Then we can simply use tools like `https://www.npmjs.com/package/throat` instead of `distributed lock` for concurrency control. And since it is an io intensive task, so single process is acceptable.

**Comment by sindresorhus** [comment]
See https://github.com/avajs/ava/issues/1332

**Comment by novemberborn** [comment]
(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
