### ISSUE TITLE
Set default timeout / ensure worker exits after unhandled rejections

### ISSUE THREAD

**Issue by Oloompa** [avajs/ava#2310]
I have tests which are executed in CI. Sometime it just hangs a lot of time cause test never end due to an uncaught promise error.

If i run the server in production it should crash ([but currently it do not](https://github.com/nodejs/node/issues/20392)).

We test in CI to prevent unexpected bug. Ava currently wait and consume CI time for unhandled async rejections.

It would save cost if ava could fail test instantly.

**Comment by novemberborn** [comment]
Yea, we really ought to set a default timeout, even if it's say 30 seconds. Will try and get that into the next major release.
