### ISSUE TITLE
Re-enable AVA in CITGM

### ISSUE THREAD

**Issue by BridgeAR** [avajs/ava#2312]
We run AVA test suite in [citgm](https://github.com/nodejs/citgm) and we got some reliable failures with Node.js v12.14.0. See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2137/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/ava_v2_4_0/ (available ~7 days).

It would be great if this could be investigated and fixed in a new release that we are able to unskip AVA again.

We also have AVA skipped in lots of environments such as AIX, Windows, PPC, 32 bit builds and Node.js v10.x (we check all supported Node.js release lines).

Please open a PR to citgm in case this got fixed to unskip AVA again (see e.g., https://github.com/nodejs/citgm/commit/f5d9a83b6457a4bafe18a31cf790b98349c9e673 how to unskip).

Ping @novemberborn

**Comment by novemberborn** [comment]
Looks like the syntax error for non-transpiled `import` has changed, and we're not looking for that. Should be easy enough to fix.

How do I find out what's upcoming in Node.js 12.14?

Our test suite is somewhat sensitive to timeouts (that's what you get when launching child processes that launch child processes that launch child processes), especially on Windows, so I'm not surprised you had to skip it in those environments.

**Comment by novemberborn** [comment]
Huh, I take it this runs the `v2.4.0` tag rather than `master`? Cause the tests pass in `master`. I'll open the PR to re-enable after the next release.

**Comment by novemberborn** [comment]
I've prepared the commit to reenable here: https://github.com/nodejs/citgm/compare/master...avajs:reenable-ava

Just waiting to submit until we officially ship v3.
