### ISSUE TITLE
[feature request] specific testing metadata

### ISSUE THREAD

**Issue by link89** [avajs/ava#2318]
As an automation QA,
I hope that ava can specific testing metadata, like what testcafe does: https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-testing-metadata
So that we can write it to report, and use it to filter cases to execute, etc

**Comment by novemberborn** [comment]
Yes that could be interesting.

How would you consume the test reports? The only structured format we have is TAP and even that's not particularly structured for AVA's capabilities.

**Comment by link89** [comment]
We write logs to` t.context` during cases execution, and write these logs and cases name to allure report in `afterEach`. 
We have use `testcafe` for a long time but now we decide to use `selenium`. So I really hope that `ava` can have those fancy features that `testcafe` have.

**Comment by novemberborn** [comment]
I don't want to add APIs to set metadata until we have a reporter which can then report that metadata. But I'd definitely like to have a structured reporter (not TAP) which can support all that.

**Comment by link89** [comment]
@novemberborn How about add metadata for cases filtering?

**Comment by novemberborn** [comment]
> How about add metadata for cases filtering?

@link89 could you elaborate?

**Comment by link89** [comment]
For example, I may set a field named "priority" in metadata whose value could be P0,P1,P2,P3.
Then I would hope that I can execute all P0 by providing some command line options, like `ava --meta-filter "priority=P0"`

**Comment by novemberborn** [comment]
I'm not sure that's a general enough use case for AVA.

There are some ways of doing this now, though not as elegant as you have in mind. You could prefix or postfix the test titles, and then use `--match "P0*"`.

You can also pass arguments to the worker processes:

```console
npx ava test.js -- --priority=p0
```

And then access that flag from `process.argv`. That way you could define a function like:

```
const p0 = (...args) => {
  if (executeP0) return test(...args)

  return test.skip(...args)
}

p0('my important test', t => t.pass())
```

(Just thinking out loud here.)

**Comment by link89** [comment]
Actually now we are working around this limitation by stringify an object (which contain name, case-id, priority, category, keyword, owner, components) and put it in title and then do whatever we need. But this makes output ugly during case execution.

In my option what `ava` need is to allow users to set more information (an object) to a case instead of just a title (a string). And then users will figure out how to use this by themselves, like put these data in report or make use of this to filter cases as your sample code.

**Comment by novemberborn** [comment]
I don't think this is actionable any time soon. Once we have an extensible structured logger we can explore this further.
