### ISSUE TITLE
Use assertion functions in our type definition

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2330]
We should update our TypeScript definition so that our assertions are typed as such, see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions.

That said, I haven't checked whether and how we can make this work for which assertions.

**Comment by novemberborn** [comment]
As per https://github.com/microsoft/TypeScript/issues/34596 I don't think this will work for us. But I don't really understand any of the discussion. Let's see what happens in future TypeScript versions.

**Comment by sindresorhus** [comment]
Maybe relevant: https://github.com/microsoft/TypeScript/issues/36067

**Comment by novemberborn** [comment]
Best I understand that issue, it'd still end up being useless for our use cases.
