### ISSUE TITLE
Typings error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'

### ISSUE THREAD

**Issue by pizzafox** [avajs/ava#2332]
## Description

When compiling with TypeScript there is a typings error which makes the TypeScript compiler exit with exit code 2.
The code still gets compiled but my build CI fails because of the exit code.
This happens on the latest AVA version if AVA is being compiled at all by TSC.

### Error Message & Stack Trace

```txt
node_modules/ava/index.d.ts:5:10 - error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'
5	[Symbol.observable](): ObservableLike;
```

### Command-Line Arguments

Run this to compile my example repo.

```sh
tsc index.ts
```

## Relevant Links

- Minimal repo is [here](https://github.com/pizzafox/ava-ts-error/tree/master), just clone, npm install, and run `tsc index.ts`

## Environment

TypeScript v3.7.4
Node.js v12.14.0
linux 4.4.0-18362-Microsoft
AVA v2.4.0
npm v6.13.4

**Comment by Silic0nS0ldier** [comment]
I've also experienced this issue. Having looked into closed tickets, this appears to have been an issue that was previously resolved.

A temporary work-around is to put this into a general "global types" file. With some tweaks, it can be placed directly in test files as well.
```ts
declare interface SymbolConstructor {
    readonly observable: symbol;
}
```

**Comment by novemberborn** [comment]
See the discussion in https://github.com/avajs/ava/issues/2212. A fix is in progress at https://github.com/avajs/ava/pull/2308.

**Comment by novemberborn** [comment]
Oh wait — reading more closely, is this something that started happening with TypeScript 3.7.4?

**Comment by pizzafox** [comment]
Issue is still present with TypeScript `v3.7.3` and `v3.7.2`.

**Comment by novemberborn** [comment]
I'd be happy to ship a 2.4.1 release if necessary, but I can't tell from the feedback here whether this is something that stopped working recently or has always been a problem. I haven't encountered it myself.

@znorman-harris[*](https://github.com/avajs/ava/issues/2151#issuecomment-570764340), do you have any insight here?

**Comment by pizzafox** [comment]
Perhaps this had something to do with the typings for Node `@types/node` and not the TypeScript compiler?

**Comment by novemberborn** [comment]
> Perhaps this had something to do with the typings for Node `@types/node` and not the TypeScript compiler?

Yes, maybe. Hopefully folks can work around that by pinning an older version.

**Comment by sramam** [comment]
I can verify that this happens with 
```
node @ v12.7.0
ava @ 2.4.0
@types/node @ 13.1.4
```

But does not at 
```
node @ v12.7.0
ava @ 2.4.0
@types/node @ 12.12.17
```

It seems to be a [@types/node@v13.0 update](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c47a34ead1637f6f34e7d630dc88ea3f6e5562cb#diff-a2f9a5377787f7084c7f52b20c0108cfL145)

I don't understand this change to make sense of what is going on, but it seems adding
`import Symbol_observable from 'symbol-observable';` to `avajs/index.d.ts` resolves the `tsc` error.

For my case it seems to work, not sure if that is however a proper fix.

**Comment by novemberborn** [comment]
OK so it may indeed be `@types/node`. That's not the best fix, but it looks like this can be worked around.

AVA 3 beta will be out soon (unofficially, I'm too tired to write the release notes) which does away with this symbol type altogether.

**Comment by znorman-harris** [comment]
@novemberborn this was something that came up recently for me. I remember seeing it a while back, but dismissed it when it didn't reappear. 

Considering there is a workaround I'm good and can wait until the next release!

**Comment by novemberborn** [comment]
`npm i -D -E ava@next` will give you the next release, but I haven't yet documented the breaking changes so use at your own peril 😉

**Comment by SephReed** [comment]
I'm getting this error as well.  Having a really hard time getting `tsconfig` `{ "exclude": [] }` syntax to ignore my test files.

**Comment by SephReed** [comment]
Got a fix for now:

tsconfig.json:

```
{
  "exclude": ["**/__tests/*", "**/testing/*"],
  "include": ["./src"],
  "compilerOptions": {
     // code omitted....
  }
}
```

**Comment by tjmosia** [comment]
The issue actually lies with Typescript here... The typescript file where global Symbol variable and SymbolConstructor is declared doesn't have observable as one of it's properties. It feels kinda crappy modifying that file...

**Comment by novemberborn** [comment]
@tjmosia this has been resolved with AVA 3.
