### ISSUE TITLE
Support ava.config.mjs files

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2346]
AVA recognizes `ava.config.mjs` files but refuses to load them. Let's fix this!

See the code here: https://github.com/avajs/ava/blob/7f99aef61f3aed2389ca9407115ad4c9aecada92/lib/load-config.js#L109

Of course `import()` is only available on Node.js 13. This should fail gracefully on Node.js 10 and 12.

`import()` is asynchronous. The `loadConfig()` method should still return synchronously when loading other files.

The documentation needs to be updated to explain when `.mjs` config files make sense and when users should use `.cjs` or `.js` files. Mostly this is to do with ESLint compatibility (since rules must currently be synchronous).

**Comment by arlac77** [comment]
Why not switching to async loadConfig() ?

**Comment by novemberborn** [comment]
This is to do with ESLint compatibility (since rules must currently be synchronous).
