### ISSUE TITLE
Globals are no longer available when loading ava.config.js

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2356]
This is a regression in the upcoming v3 release.

`ava.config.js` is given special treatment. Unfortunately I neglected to expose certain globals:

https://github.com/avajs/ava/blob/090884b5040a1d4b02a18939245f7c2305228e00/lib/load-config.js#L27

We should add:

* `process`
* `console`

And that's about all I can think of at this stage.

**Comment by jessecogollo** [comment]
Hi @novemberborn, I would be happy to work on this, could you be clarify what does it mean?
```
We should add: process console
```

**Comment by novemberborn** [comment]
Hi @jessecogollo,

The object passed to `script.runInNewContext()` provides the variables available in the file. So we need to add the `process: process` and `console: console` properties to that object. Using shorthand that just becomes `process` and `console`.
