### ISSUE TITLE
Question about endpoint testing doc

### ISSUE THREAD

**Issue by ftaiolivista** [avajs/ava#2366]
Doc about endpoint[ testing states](https://github.com/avajs/ava/blob/master/docs/recipes/endpoint-testing.md):

> If you start your server using a test.before() hook you should make sure to execute your tests serially

This is not clear to me why is better to have tests in serial in that case. Anyone can explain me?

**Comment by novemberborn** [comment]
Essentially, all tests would run at the same time, sending a lot of concurrent requests to your server. Depending on the state managed in the server this could lead to problems. When use execute tests serially it's easier to reason about.

I suppose we could clarify this in the recipe. Would you want to do a PR for that?

**Comment by stavalfi** [comment]
I maybe wrong but I believe that a test runner is not responsible for the user-test-logic.

**Comment by novemberborn** [comment]
> I maybe wrong but I believe that a test runner is not responsible for the user-test-logic.

Sure, but the behavior of the test runner imposes constraints on the logic that can be written. And we should make sure those are as clear as can be.
