### ISSUE TITLE
Watch mode doesn't seem to be debouncing

### ISSUE THREAD

**Issue by frangio** [avajs/ava#2375]
I'm running ava 3 over JavaScript test files in watch mode, while I edit TypeScript source files and compile in watch mode in the background with `tsc --watch`.

Sometimes TypeScript seems to trigger two "modify" events on the same JavaScript file, one immediately following the other (I've verified this using inotifywait), and that causes ava to rerun the tests twice. I would expect some debouncing to happen.

I can reproduce this using ava 3 with no configuration, a single simple `test.ts` file, and just running `ava --watch` while running `tsc --watch *.ts` at the same time.

The same thing doesn't happen in ava 2.

**Comment by novemberborn** [comment]
AVA is likely picking up the changes to the source file and the build output. If these happen to be far enough apart, the test is run twice.

See https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#debugging for how to check what the watcher is responding to.

You'll want to ignore your source files by setting the `ignoredByWatcher` configuration to something like `["src/**/*.ts"]`.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by frangio** [comment]
Ah I think that's what's happening. I was not able to reproduce the issue when ignoring the source files. Thank you!
