### ISSUE TITLE
"Enhancement compilation must be configured in AVA’s Babel options" error with TypeScript.

### ISSUE THREAD

**Issue by meyve** [avajs/ava#2376]
I'm trying to run some unit tests with TypeScript using `ts-node` package as described in official ava's TS [recipe](https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md).

Facing an error:
```
> node ./node_modules/ava/cli.js

  ✖ Enhancement compilation must be configured in AVA’s Babel options.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! some_package@0.0.1 test: `node ./node_modules/ava/cli.js`
npm ERR! Exit status 1
```

Node version: 13.6.0
Ava version: 3.0.0
TypeScript version: 3.7.5
OS: Linux Mint 19.1 (Tessa)
Running ava both ways leads to same result: 
`node ./node_modules/ava/cli.js` as locally installed
`ava` as globally installed.

Must note that with ava v2.4.0 everything works as expected.
Repository to reproduce: https://github.com/meyve/ava_test

**Comment by novemberborn** [comment]
Oh that setting is no longer needed. It should be removed from the documentation. I see it in two different places in that file, perhaps it's mentioned elsewhere too.

**Comment by iljoo** [comment]
Try this
```
$ yarn add -D @ava/babel
$ cat ava.config.js
export default {
  babel: {
    compileEnhancements: false
  },
  files: ['./specs/**/*.ts'],
  require: ['ts-node/register'],
  extensions: ['ts']
};
```

**Comment by jhechtf** [comment]
@iljoo in running your config I get a new error when attempting to run tests.

```
 × Cannot find module '@ava/babel'
```

**Comment by iljoo** [comment]
Did you install it?  `yarn add -D @ava/babel`

**Comment by jhechtf** [comment]
I did, curious why ava doesn't include it on its own though?

Is this mentioned on the install instructions? I didn't see it, and I don't
remember having this issue with earlier versions of ava.

**Comment by webees** [comment]
I had the same problem after upgrading to`v3.0`, but it was resolved after installing` @ava/babel`.

**Comment by novemberborn** [comment]
> Try this
> 
> ```
> $ yarn add -D @ava/babel
> $ cat ava.config.js
> export default {
>   babel: {
>     compileEnhancements: false
>   },
>   files: ['./specs/**/*.ts'],
>   require: ['ts-node/register'],
>   extensions: ['ts']
> };
> ```

To be clear, this is *not* needed with AVA 3. Babel is disabled by default, so if you want to use TypeScript with `ts-node` you only need to update the `require` and `extensions` configuration.

The documentation is wrong here, which is why this issue is still open. We'd appreciate a PR to update the TypeScript recipe.

---

[Per the release notes](https://github.com/avajs/ava/releases/tag/v3.0.0) if you want to use Babel you need to install `@ava/babel`. Having this as a separate package means it can grow on its own, and folks who don't need Babel won't have to install the extra dependencies.

**Comment by jhechtf** [comment]
I'm currently using ava in a typescript project without babel, which is why
the requirement for babel was so strange to me.

I'm also using ava 3 - should it not need the babel step? Do we just remove
the babel key? What configuration for ava v3 makes typescript work without
babel?

**Comment by novemberborn** [comment]
> I'm currently using ava in a typescript project without babel, which is why the requirement for babel was so strange to me. I'm also using ava 3 - should it not need the babel step? Do we just remove the babel key? What configuration for ava v3 makes typescript work without babel?

Again, the documentation is wrong. The `compileEnhancements: false` configuration needs to be removed. You do not need to configure `babel` if you're not using it.

**Comment by novemberborn** [comment]
@jhechtf that'd be amazing!

**Comment by meyve** [comment]
> Oh that setting is no longer needed. It should be removed from the documentation. I see it in two different places in that file, perhaps it's mentioned elsewhere too.

I removed `compileEnhancements` option entirely from `ava.config.js` and it works.

**Comment by matt-wiese** [comment]
> I've made clean install of ava@3.0.0, removed entirely `compileEnhancements` and it works now.
> 
> @novemberborn thanks for help!
> @jhechtf appreciate you took it!

Appreciate the work on this. However, I'm still getting this error with v3.14 via Atom on Win10.

**Comment by novemberborn** [comment]
> Appreciate the work on this. However, I'm still getting this error with v3.14 via Atom on Win10.

@matt-wiese happy to discuss in a separate [Discussion](https://github.com/avajs/ava/discussions). Without more context this looks like a v2 configuration incompatibility, but again let's discuss elsewhere.

**Comment by cancerberoSgx** [comment]
Just in case, if you are not using babel, removing `compileEnhancements` in the config will do the trick when upgrading to ava 3
