### ISSUE TITLE
Allow running ava from node 10.13

### ISSUE THREAD

**Issue by KnisterPeter** [avajs/ava#2378]
Hello,

we would love to migrate to ava 3, but we discovered that while ava is supporting node 10, its starting from 10.18 (https://github.com/avajs/ava/pull/2313).
Unfortunately we would need support from 10.13 which is the first 'Dubnium' release (LTS) for node 10.

We haven't found any documentation on why node 10.18 was chosen and would like to request if its possible do downgrad this to 10.13?

If it helps we will contribute a PR for this change.

**Comment by novemberborn** [comment]
It's very likely that AVA 3 works on Node.js 10.13; however it hasn't been tested. npm issues warnings but these are warnings only.

The minimal 12.14 restriction is more interesting since Node.js 12 may still receive additional features. We'll try and avoid relying on those features until the next major version.

Without checking, it's pretty likely that Node.js 10.13 has security vulnerabilities. Long term support means that new versions will be released that are unlikely to break your code. You should still update to those newer versions.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by KnisterPeter** [comment]
Hi @novemberborn,

thanks for you fast reply. We are building a tool internally for our company and we need to specify which version we will support to give teams straight guideline.
We could recommend our teams using our tool that they should keep up-to-date with node and use the latest possible version, but we cannot force the teams to do the updates.

Therefore we would welcome (if there are no roadblocks) to test ava against 10.13. Should we create a PR for this? 
The main issue for us is that in the `package.json` the `engines` are specified as `>= 10.13` which will result in yarn refusing to install ava even if its possible to run it with 10.13.

**Comment by novemberborn** [comment]
> Therefore we would welcome (if there are no roadblocks) to test ava against 10.13. Should we create a PR for this?

We don't actually test against `10.18.0`. We test against `10.18.0` *or newer*.

> The main issue for us is that in the `package.json` the `engines` are specified as `>= 10.13` which will result in yarn refusing to install ava even if its possible to run it with 10.13.

You can run yarn with `--ignore-engines`.

> We could recommend our teams using our tool that they should keep up-to-date with node and use the latest possible version, but we cannot force the teams to do the updates.

There have been security releases since 10.13; your teams really should be upgrading.

**Comment by novemberborn** [comment]
Alternatively I recommend you stick with AVA 2 and reassess in a few months.

**Comment by KnisterPeter** [comment]
> We don't actually test against `10.18.0`. We test against `10.18.0` _or newer_.
>
Okay, I've seen that in the github workflow its `^10.18.0` which means you will probably test against newer versions.
 
> You can run yarn with `--ignore-engines`.
>
I think its not an option for us to tell this a few hundred developers.
 
> There have been security releases since 10.13; your teams really should be upgrading.
>
Yes, I totally agree, but I still cannot enforce this.

I'll guess we have to stick with ava 2 then.
Thanks for the discussion.
