### ISSUE TITLE
Improve message when test.cb() is used with promises

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2386]
`test.cb()` is a legacy API. It can be used for testing callback APIs, but for anything more advanced we'd prefer you use `test()` with an async function.

We should update the error message here:

https://github.com/avajs/ava/blob/56338dcb77246b5eca3c01e24d1cb6d66da8f71f/lib/test.js#L597

It should say something like:

> Use `test.cb()` for legacy callback APIs. When using promises or async functions, use `test()`.

We should replace the "promises or async function" part with "observables" as appropriate.

**Comment by sindresorhus** [comment]
Is it really worth doing this if we plan to remove the API?

**Comment by novemberborn** [comment]
The actual removal may not happen for months.

**Comment by toddkcarlson** [comment]
From what I understand, this is simply changing the test text, is that correct? If so, I'd like to work on it.

**Comment by novemberborn** [comment]
@toddkcarlson great!

There was a PR yesterday that [came and went](https://github.com/avajs/ava/pull/23910), so it's all yours I think.

**Comment by govardhan27** [comment]
Hey is anyone still working on this?
I would like to pick up this task!

**Comment by toddkcarlson** [comment]
Yes! I'm working on it. I'll let you know if I need any help @govardhan27

**Comment by govardhan27** [comment]
Yeah sure @toddkcarlson

**Comment by Budhanatech** [comment]
Anyone still working on this ?

**Comment by toddkcarlson** [comment]
Yes @Budhanatech
