### ISSUE TITLE
Remove `test.cb()`

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2387]
`test.cb()` is a legacy API. It's probably time to remove it.

Ideally we can define [an experiment](https://github.com/avajs/ava/blob/56338dcb77246b5eca3c01e24d1cb6d66da8f71f/lib/load-config.js#L10), say "noCb" so users can opt in to not having `test.cb()` available.

When enabled, it should be removed from the chain:

https://github.com/avajs/ava/blob/56338dcb77246b5eca3c01e24d1cb6d66da8f71f/lib/create-chain.js#L77:L79

https://github.com/avajs/ava/blob/56338dcb77246b5eca3c01e24d1cb6d66da8f71f/lib/create-chain.js#L88:L92

Then by the time we're shipping the next breaking version we can remove it properly, from the TypeScript definition, the chain code and the implementation.

**Comment by sindresorhus** [comment]
Before it’s removed, it’s important that we have docs in place that show common `test.cb` use-cases with `test` instead. For example, promisify, events (using `p-event`), streams (using async iterator or `get-stream`, etc.

**Comment by ash0080** [comment]
Wish to include p-event similar internal,
events test is the shortcoming of AVA

**Comment by novemberborn** [comment]
@ash0080 we'd rather people use `p-event` directly at this stage than add more API surface to AVA.

**Comment by alastairs** [comment]
I'm writing tests for a [Pulumi](https://pulumi.com) application, and based on their own  appears those require the callback approach. Here's a (TypeScript) sample macro I've written using the callback API:

```typescript
const hasTag: CbMacro<[AzureResource, string[]], PulumiContext> = (t, resource: AzureResource, expectedTags: string[]) => {
  pulumi.all([resource.name, resource.urn, resource.tags])
    .apply(([name, urn, tags]) => {
      t.deepEqual(Object.getOwnPropertyNames(tags), expectedTags,
        `Some required tags were missing from resource ${name} (${urn})`);

      t.end();
    });
}
```

I'd like to move away from the callback model, but It's not immediately obvious to me how to promisify this: what are the resolve and reject scenarios? Annoyingly, while Pulumi's API is asynchronous, it is only Promise-like and doesn't actually return Promises anywhere; hence the `t.end();` is required inside the lambda function to indicate the test completion.

**Comment by novemberborn** [comment]
@alastairs looks like `const [name, urn tags] = await new Promise(resolve => pulumi.all([…]).apply(resolve))` to me.

**Comment by alastairs** [comment]
@novemberborn That worked a treat, thank you so much 🙏
