### ISSUE TITLE
Disallow `null` expectations for `throws` and `throwsAsync` assertions

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2410]
As a follow-up to https://github.com/avajs/ava/issues/2401, for the next major AVA release we'll remove support for `null` expectations in `throws` and `throwsAsync` assertions. If you want to specify a message without any other expectations you should set it to `undefined` instead.

This can partially land behind an [experimental flag](https://github.com/avajs/ava/blob/d0e21612390d50f084f7062b051164624ef391ff/lib/load-config.js#L10), to be unflagged when the next major is (pre-)released. The the TypeScript definition can only be updated at that point.

**Comment by JSimoni42** [comment]
Hey @novemberborn, I noticed that the previous PR for this one was closed out and put together a similar fix. I browsed https://github.com/avajs/ava/blob/master/.github/CONTRIBUTING.md and believe that this PR checks all the boxes, but any feedback would be appreciated.

**Comment by novemberborn** [comment]
Re-opening for the AVA 4 milestone, when we can remove the experimental flag and make this the default behavior.

**Comment by novemberborn** [comment]
Plus update the TypeScript definition.
