### ISSUE TITLE
Nyc + ava gives 0 on all coverage lines

### ISSUE THREAD

**Issue by catalin-luntraru** [avajs/ava#2417]
I followed the steps from https://github.com/avajs/ava/blob/master/docs/recipes/code-coverage.md

My ava config from `package.json` is 
```
"scripts": {
    "test": "ava",
    "coverage": "nyc ava"
},
"ava": {
    "files": [
      "src/test/**/*.spec.js"
    ],
    "require": [
      "./src/test/_setup-browser-env.js"
    ],
    "verbose": true
  }
```

When I run the coverage script I get this:

![image](https://user-images.githubusercontent.com/144854/76039608-a139cc80-5f55-11ea-8fb8-d38ca21b2e47.png)

I don't use babel, and imports are done with `import` not `require`.
I'm on the latest versions of node.js, ava, nyc

**Comment by novemberborn** [comment]
I sometimes have trouble getting good reports out of `nyc ava` as well. Sometimes it helps to delete the `coverage` and `.nyc_output` directories. Maybe even `node_modules/.cache`.

> I don't use babel, and imports are done with `import` not `require`.

So… you're using ESM with Node.js 13? There's a good chance that `nyc` cannot deal with that yet.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by catalin-luntraru** [comment]
For some people nyc and esm works https://github.com/istanbuljs/nyc/issues/905
I will open a ticket on nyc since it's more related to that than ava

**Comment by DemianD** [comment]
Instead of using nyc, you can also use https://github.com/bcoe/c8 which works with esm
