### ISSUE TITLE
“Couldn't find any files to test” – provide more information?

### ISSUE THREAD

**Issue by rauschma** [avajs/ava#2418]
Output:

```
% npm t exercises/installation_test.ts

> @ test /Users/rauschma/Projects/typescript/typescript-code
> ava "exercises/installation_test.ts"

  ✖ Couldn't find any files to test

npm ERR! Test failed.  See above for more details.
```

`package.json`:

```json
{
  "scripts": {
    "test": "ava"
  },
  "dependencies": {
    "ava": "^3.5.0",
    "ts-node": "^8.6.2",
    "typescript": "^3.8.3"
  },
  "ava": {
    "files": [
      "{exercises}/**/*{_test,_exrc}.ts"
    ],
    "extensions": [
      "ts"
    ],
    "require": [
      "ts-node/register"
    ],
    "failWithoutAssertions": false
  }
}
```

After a long time of trying to fix this, I found out what’s wrong:

* The entry in `ava.files` must be `"exercises/**/*{_test,_exrc}.ts"` (no curly braces!).
* I originally had two items inside the curly braces, but a single entry should be syntactically legal(?)

Suggestion:

* Would it be possible to provide more information along with the error message “Couldn't find any files to test”?
* For example: Argument `"exercises/installation_test.ts"` doesn’t match the glob `"{exercises}/**/*{_test,_exrc}.ts"`
* This would help a lot with debugging, where you can’t be sure if node-ts threw an exception, Node.js didn’t like something, something else went wrong inside the compilation pipeline, etc.

**Comment by novemberborn** [comment]
> * The entry in `ava.files` must be `"exercises/**/*{_test,_exrc}.ts"` (no curly braces!).
> * I originally had two items inside the curly braces, but a single entry should be syntactically legal(?)

Possibly, to the extend that there even is a standard for this syntax. Of the top of my head there's about 4 layers of dependencies that handle the globbing, this isn't immediately under our control.

> * Would it be possible to provide more information along with the error message “Couldn't find any files to test”?

> * Would it be possible to provide more information along with the error message “Couldn't find any files to test”?

Yes, we have an issue for that: https://github.com/avajs/ava/issues/2373

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by rauschma** [comment]
> Yes, we have an issue for that: #2373

Great!
