### ISSUE TITLE
Async assertion timeout is going bad

### ISSUE THREAD

**Issue by KSR-Yasuda** [avajs/ava#2430]
`t.notThrowsAsync()` assertion timeouts by the default timeout period.

* OS:      Ubuntu 16.04.6 LTS
* Node.js: v12.14.1
* `ava`:   v3.5.1

The code below timeouts by the default timeout or 10 seconds.

```javascript
const test          = require("ava");

test.only("Timeout: Tick", async (t) => {
    //t.timeout(75 * 1000);                   //(A) This does not work
    for (let i=1; i<=60; i++) {
        //t.timeout(75 * 1000);               //(B) This does not work either
        await t.notThrowsAsync(
            new Promise((resolve) =>
                setTimeout(() => {
                    //console.log(i);         //(C) With this, it does not get timeout (Even though both (A) and (B) disabled)
                    resolve();
                }, 1000)
            )
        );
    }
});
```

```
% time npx ava test/timeout.js -v T 5s

  
  ✖ Timed out while running tests

  1 tests were pending in test/timeout.js

  ◌ Timeout: Tick




real    0m10.509s
user    0m0.636s
sys     0m0.136s
```

`t.timeout()` setting in the test code (Line (A) or (B)),  
and command line `--timeout` / `-T` option looks not taking any effect in this case  
(although, `ava.timeout` setting in `package.json` does).

But, with the `console.log()` (Line (C)), it is not caught in the timeout error.

As the `console.log()` output (Line (C)) helps it,  
perhaps it might be a problem that it does not switch to `ava`'s timeout-managing context, or such.

Even if it is unluckily unavoidable,  
some more information about it would be wanted in the [Test timeouts][TestTimeouts] page.

[TestTimeouts]: https://github.com/avajs/ava/blob/master/docs/07-test-timeouts.md

**Comment by novemberborn** [comment]
See https://github.com/avajs/ava/issues/2384.

**Comment by KSR-Yasuda** [comment]
I got that the global timeout porposes to kill stuck test.

But then, isn't there any way to raise heartbeat or something to prevent timeout?
None of `t.log()`, `t.pass()` or other assertion does care about it
(If any assertion is called, test is anyhow running, isn't it?).

For example, in case of calling external command,
the only thing I can do is to set global timeout far longer enough?

```javascript
const test              = require("ava");

const path              = require("path");
const childProcess      = require("child_process");

//==============================================================================

test("External Proc", async (t) => {
    await t.notThrowsAsync(
        new Promise((resolve, reject) => {
            let proc        =
                childProcess.spawn(
                    path.resolve(__dirname, "timeout.sh")
                ,   [15]                                        //Takes 15 sec
                ,   {stdio:     "pipe"}
                )
                .on("error", reject)
                .on("exit",  resolve);

            proc.stdout.on("data", (data) => {
                data        = data.toString().replace(/[\s\n]*$/, "");

                //XXX:  Would like to raise a heartbeat here,
                //      when the process is saying something (means the command is working).
                //      Otherwise, this 15-sec-taking test is trapped in timeout.

                console.log(data);      //This works as a heartbeat (unknown why), but dirties stdout

                t.log(data);            //`t.log()`, `t.pass()` or other test assertion
                t.pass();               //has any effect on timeout
            });
        })
    );
});
```

```bash
#!/bin/bash

#timeout.sh [TIMEOUT_IN_SEC]

COUNT=$([[ $# -eq 0 ]] && echo 60 || echo "$1")

for i in $(seq 1 "${COUNT}"); do
    echo $i
    sleep 1
done
```

**Comment by novemberborn** [comment]
> But then, isn't there any way to raise heartbeat or something to prevent timeout?

Yes, that's what #2384 is about.



> in case of calling external command,
> the only thing I can do is to set global timeout far longer enough?

Yes.

**Comment by KSR-Yasuda** [comment]
Okay, I got it. Thank you.
I'll keep an eye on the issue and future updates.

**Comment by KSR-Yasuda** [comment]
Note for others:

Perhaps **`process.send({ava: {}})`** can be used as a heartbeat until the update comes.

As above, I found `console.log()` or other stdout/stderr output works so.
This was also that stdout/stderr's `data` events are converted as `ava`'s events to reset the global timer.

`process.send({ava: {}})` would be better:
it does not dirty any console output.
