### ISSUE TITLE
Add an option to output stdout into a file

### ISSUE THREAD

**Issue by adymorz** [avajs/ava#2431]
* I am trying to save the output of my test run (only stdout without stderr) to a file, using gulp-ava.
* Neither `AVA` nor `gulp-ava` has a parameter to do this yet. Redirecting the whole output of gulp-ava into a file also redirects output of gulp into it.
* [I implemented the parameter in gulp-ava already](https://github.com/avajs/gulp-ava/pull/32), but it might makes more sense to implement it in ava.

Would you like to have an option `outputfile`  in `AVA`?

**Comment by novemberborn** [comment]
No, sorry. AVA is designed to be used on the CLI, and you can redirect outputs in your terminal.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by adymorz** [comment]
Thanks for your reply. I just added a new comment to the [original pull request in gulp-ava](https://github.com/avajs/gulp-ava/pull/32) containig a new approach.
