### ISSUE TITLE
With `esm`: AVA 2 supports `type: module`, AVA 3 doesn't

### ISSUE THREAD

**Issue by fregante** [avajs/ava#2432]
I know that full ESM support is WIP (#2293) but I wanted to document this regression.

```
Error: ECMAScript Modules are not supported in this Node.js version.
```
This exact combination fails:

* Node 12.15 (12.16+ fails regardless)
* AVA 3.0+ (2.4- works)
* `ava.require`: esm
* `type: module` in the current package.json

I also tried dropping the internal [`supportsESM`](https://github.com/avajs/ava/blob/13d66519e7b69e810079673d6583dc7336a16ebe/lib/worker/subprocess.js#L9) function but it fails regardless.

A live demo can be seen on https://github.com/vadimdemedes/dom-chef/pull/56#commits-pushed-4fc9c23

<img width="672" alt="demo" src="https://user-images.githubusercontent.com/1402241/77789253-f9e71b80-7062-11ea-87a2-aa0cc4e23d08.png">

---

I also tried `ava --experimental-modules` (changing the [`require().default`](https://github.com/vadimdemedes/dom-chef/blob/a0beb3fe3477317282c90448fa4952ad6723e377/test.js#L14) to `import` and dropping `esm`) but for some reason it says it's still a `require`. I probably don't want to get into that since a dependency isn't `type: module` either

**Comment by novemberborn** [comment]
Yea sorry about that. The `.mjs` extension can now only be used with proper ES modules, not the `esm` package.

**Comment by fregante** [comment]
I don’t have mjs files, but `type: module`

But fair enough

**Comment by novemberborn** [comment]
Right. On mobile, need to check what is supported and what isn’t.

**Comment by novemberborn** [comment]
@fregante I see. I'm not sure we can override how Node.js interprets `type: module`. https://github.com/avajs/ava/issues/2345 proposes configuration for file extensions, so that would be the way to go, if we can somehow load these files as CJS.

**Comment by fregante** [comment]
There's nothing _extra_ to be supported: the module is a real ES Module and should be loaded as an ES Module just like Node can.

In this specific case it still wouldn't work due to non-`type:module` dependencies, but AVA 3 just fails even with an empty `./index.js`

This is what happens with:

- AVA 2.4
- Node 13.9
- Without ESM
- Only this line inside `test.js`
	```js
	import React from './index.js';
	```

```
❯ ava


  ✖ No tests found in test.js

  1 uncaught exception

  Uncaught exception in test.js

  ./test.js:14

   1: import React from './index.js';
   2:                                

  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ./index.js
  require() of ES modules is not supported.
  require() of ./index.js from ./test.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./package.json.
```

**Comment by fregante** [comment]
I think there's some deep issue with this combination:

- AVA 3
- `type:module`
- JSX in tests

The moment I add `@babel/preset-react` and rename it to `test.jsx` it starts throwing this _wrong_ error:

```js
  ./test.js:14

   1: import React from './index.js';
   2:                                

  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ./index.js
  require() of ES modules is not supported.
  require() of ./index.js from ./test.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./package.json.
```

I spent enough time on this today, I think this issue should be reopened (but it should mention JSX/babel)

**Comment by fregante** [comment]
[repro.zip](https://github.com/avajs/ava/files/4399774/repro.zip) contains:

### package.json


```json
{
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "ava"
  },
  "dependencies": {
    "@ava/babel": "^1.0.1",
    "@babel/preset-react": "^7.9.4",
    "ava": "^3.5.1"
  },
  "ava": {
    "babel": {
      "testOptions": {
        "plugins": [
          "@babel/plugin-syntax-jsx",
          "@babel/plugin-transform-react-jsx"
        ]
      },
      "extensions": [
        "js",
        "jsx"
      ]
    }
  }
}
```

### tests.jsx

```jsx
import same from './index.js'
import test from 'ava';

test('base', t => {
	t.throws(() => <br/>);
});
```

### index.js

```js
export default x => x;
```

### Error

```
❯ ava


  ✖ No tests found in test.jsx

  1 uncaught exception

  Uncaught exception in test.jsx

  test.jsx:1

   1: import same from './index.js'
   2: import test from 'ava';      

  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ./index.js
  require() of ES modules is not supported.
  require() of ./index.js from ./test.jsx is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./package.json.
```

**Comment by novemberborn** [comment]
@fregante I did not notice you were using `@ava/babel`. Per https://github.com/avajs/babel/issues/13 it cannot load ESM files. You can try running Babel outside of AVA and then using AVA's own ESM support.

**Comment by dimaqq** [comment]
[sorry if I don't understand the complexity here]
The issue is closed, yet the commentary seems to indicate that this circumstance is still unsupported:

> * AVA 3
> * `type:module`
> * JSX in tests

There's a comment that this (or something) needs to be solved in avajs/babel, so should this issue remain open waiting for that instead?

**Comment by novemberborn** [comment]
@dimaqq if you're using JSX with our Babel provider, then yes https://github.com/avajs/babel/issues/13 is the issue you're looking for.

In short, ESM only really works without on-the-fly compilers at this point. That's a general observation, nothing to do with AVA really.

**Comment by fregante** [comment]
> In short, ESM only really works without on-the-fly compilers at this point. 

I'm sure that in the easiest of setups (e.g. every file is a true ESM file + no external modules), some on-the-fly compilers will work, but:

- compilers likely mess with the imports, either changing them to `require` and breaking it, or viceversa
- bundlers are way more forgiving than Node’s ESM implementation, so they may be easier to set up (https://github.com/sindresorhus/refined-github/pull/3206)
