### ISSUE TITLE
Support assertion message in t.timeout()

### ISSUE THREAD

**Issue by shellscape** [avajs/ava#2443]
Please provide details about:

* What you're trying to do

I'd like to display a message to folks observing test runs on a particular timeout to indicate that they need to check some configuration locally. This particular scenario arises from bad user config that is detectable only at runtime (thanks AWS). 

* Why you can't use AVA for this

I've sifted through the docs and can't find a good way to do this. I haven't taken a look at the source for a hack as I've been burned by doing that in the past and upgrading major versions.

* And maybe how you think AVA could handle this

Spitballing here, but perhaps:

```js
test('verify email token', async (t) => {
  t.timeout(2000, 'Please check yo stuffs!');
  const result = await longRunningTask();
  t.assert(result);
});

// or if this is something you all would prefer to indicate for an entire suite

test.timeout(2000, 'Please check all the things');
```

**Comment by novemberborn** [comment]
AVA 3.6 gives you `t.passed` in `afterEach` hooks. Though that presupposes you can separate the tests likely to fail due to misconfiguration.

You could use [`t.try()`](https://github.com/avajs/ava/blob/master/docs/03-assertions.md#trytitle-implementation--macro--macro-args) instead:

```js
test('verify email token', async (t) => {
  const start = Date.now();
  const result = await t.try(tt => {
    tt.timeout(2000);
    const result = await longRunningTask();
    tt.assert(result);
  })
  if (!result.passed && Date.now() - start >= 2000) {
    attempt.discard();
    t.fail('Please check yo stuffs!');
  } else {
    attempt.commit();
  }
});
```

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by shellscape** [comment]
Disappointed that this was closed so quickly without any discussion. The trigger happy closing on Sindre's old projects is beginning to be a bit problematic.

While I appreciate the additional info, that solution is massively more complex than the proposed feature.

**Comment by novemberborn** [comment]
> Disappointed that this was closed so quickly without any discussion. The trigger happy closing on Sindre's old projects is beginning to be a bit problematic.

As I wrote before closing:

> (I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

And, well, I don't think this is an "old project of Sindre".

---

> While I appreciate the additional info, that solution is massively more complex than the proposed feature.

Sorry, my first reaction is to think about what lower level constructs can be used, before adding features.

That said, adding an assertion message to `t.timeout()` makes sense to me. I need to check how we could then show that in the reporters and then I can update this issue to reflect. What do you think?

**Comment by shellscape** [comment]
> I'm closing this issue for housekeeping purposes, but let's keep the conversation going

In all fairness, it's relatively universal that a closed issue is "resolved." That's the impression you're likely to get more often than not, and most users won't circle back after an issue is closed. (It's really not a good look) On some of the larger projects I help maintain, we use labels for housekeeping which makes filtering super easy.

> That said, adding an assertion message to t.timeout() makes sense to me. I need to check how we could then show that in the reporters and then I can update this issue to reflect. What do you think?

I think that's great and appreciate your willingness to look into it. If there's a way to proxy, wrap, or otherwise have `t.timeout` on our end, that would work for us as well. Given the length of time that Ava has been around and the lack of request for this until now, a re-usable hack would be great, and could even be added to the docs for `timeout`.

**Comment by novemberborn** [comment]
We can support an assertion message in `t.timeout()`.

This requires adding an argument here:

https://github.com/avajs/ava/blob/447d37153b5af9139c45cf5b0fd97ad92bea0c14/lib/test.js#L67

And then passing it along to here:

https://github.com/avajs/ava/blob/447d37153b5af9139c45cf5b0fd97ad92bea0c14/lib/test.js#L435

We should retain the default message. I think that should just show up correctly in the reporters.

We must also add it to the type definition:

https://github.com/avajs/ava/blob/447d37153b5af9139c45cf5b0fd97ad92bea0c14/index.d.ts#L344

Our ESLint plugin must also be updated:

https://github.com/avajs/eslint-plugin-ava/blob/bf2364459d240684b15b57f2542abc47f623c2d8/rules/assertion-arguments.js#L77

**Comment by shellscape** [comment]
Fantastic. I'm happy to help with that work if you'd like it

**Comment by novemberborn** [comment]
@shellscape yes, PRs welcome 😉

**Comment by shellscape** [comment]
Checking in, this is still on my radar.

**Comment by jonathansamines** [comment]
@novemberborn I'd like to work on this, if no one else is already doing so.

**Comment by novemberborn** [comment]
@jonathansamines yes that'd be great. I assume @shellscape hasn't found the time to pick this up yet.

**Comment by shellscape** [comment]
You have assumed correctly. :bow:

**Comment by novemberborn** [comment]
@shellscape no worries! Hope all is well.
