### ISSUE TITLE
Special characters & t.is

### ISSUE THREAD

**Issue by mesqueeb** [avajs/ava#2451]
I'm trying to check some strings with special characters, but I can't seem to:
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/3253920/79030590-bcdb6700-7bd4-11ea-87b4-11b35c85766a.png">

The result looks the same as the string I'm comparing to, but AVA still says it's different...

Please note these are only Latin-1 unicode characters. Aka the "most common" special characters. (for French, Spanish, some Scandinavian languages, etc...)

I'm not 100% sure how to debug something like this. 😅 

Here is my repo, reproducible when doing `npm run test` on master branch:
https://github.com/mesqueeb/case-anything

**Comment by sindresorhus** [comment]
Unicode characters can be different even if they look the same. That's why we have `String#normalize()`.

**Comment by mesqueeb** [comment]
@sindresorhus thanks. Using `String.normalize()` in my source code & in the tests code solved any of these issues had.
