### ISSUE TITLE
Have assertions return booleans

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2455]
Spurred by conversation in https://github.com/avajs/ava/issues/2449 and https://github.com/avajs/ava/issues/1485 we'd like for our assertions to return booleans. `true` when they pass, `false` when they fail. This does not apply to the `throws()` and `throwsAsync()` assertions.

Failing assertions will fail the test, but do not throw exceptions. This means your test does not stop executing. Usually that's fine, but there are conditions where you're about to do something that uses a lot of resources, and it's already unnecessary. Returning booleans will help with this.

The assertions are defined here:

https://github.com/avajs/ava/blob/18aeac64db2711d37853175b5e8dc1fd72c66d2a/lib/assert.js#L238

The type definition should be updated to reflect the new return type:

https://github.com/avajs/ava/blob/18aeac64db2711d37853175b5e8dc1fd72c66d2a/index.d.ts#L41

Some tests should be added to (or existing test updated in) https://github.com/avajs/ava/blob/master/test-tap/assert.js.

**Comment by aviralch** [comment]
Hello, 

can i work on this ?

**Comment by novemberborn** [comment]
@aviralch yea that'd be great, thanks!

**Comment by pmascheroni** [comment]
Hi, @novemberborn  I am also attempting an update to this issue and wondering if I could be assigned to it too?  Not sure if that is allowed, but I would like to work on this also.  

Thanks

**Comment by novemberborn** [comment]
@pmascheroni let's give @aviralch a chance first.

**Comment by aviralch** [comment]
@novemberborn, @pmascheroni this is my first issue, I will try to do this and keep you updated by the end of of week.

**Comment by BARICISSE** [comment]
Hi, if no one is currently working on this and it is still open, i would like to contribute.

**Comment by novemberborn** [comment]
@aviralch what do you think?

**Comment by aviralch** [comment]
Yup, sure go ahead. I am currently in middle of exams but if you need to get in touch lmk.

**Comment by novemberborn** [comment]
Thank you @aviralch, and good luck!

**Comment by RahulKannan12** [comment]
Hi, is it done ?, if not I can make a try ! Please let me know :+1:  I would like to contribute

**Comment by BARICISSE** [comment]
Hi @RahulKannan12, I am currently working on it.

**Comment by RahulKannan12** [comment]
Hi @BARICISSE , Okay great ! thanks for the information :+1:

**Comment by novemberborn** [comment]
@mzzlillieee yes go for it.

**Comment by jmarkham828** [comment]
@mzzlillieee @novemberborn  Hey yo! :) I have a draft PR for this issue that I believe is almost there. @novemberborn need a little guidance on how to update the test file -- this is my first issue. Would you mind if I pushed up what I had if @mzzlillieee is busy?

**Comment by mzzlillieee** [comment]
@jmarkham828 No I don't mind. Something came up, so I won't be able to work on this issue until next week.

**Comment by jmarkham828** [comment]
@mzzlillieee awesome! @novemberborn would you mind adding me to this issue so I can push?

**Comment by novemberborn** [comment]
> would you mind adding me to this issue so I can push?

@jmarkham828 sure, but you don't need to be assigned an issue to create a PR 😉

**Comment by rShar01** [comment]
Does this issue still a contributer?

**Comment by novemberborn** [comment]
@rShar01 this was picked up by @jmarkham828 quite recently, so maybe check in with them.

**Comment by jmarkham828** [comment]
Will work on this PR #2564 more this weekend -- took me a while to tie up some projects at work, but am free to work Saturday and Sunday! Like I said, @novemberborn,  I wasn't quite sure how to update the test file, what do you think?

**Comment by adiSuper94** [comment]
@novemberborn , I'd like to take a crack at this issue. If @jmarkham828  is no longer active.

**Comment by novemberborn** [comment]
@adiSuper94 both you and @Davidmh93 have expressed an interest. And we haven't yet heard back from @jmarkham828 but that's OK. I think if either of you could take their commits and add on top of them, based on my feedback in #2564 that'd be great. And then you could help each other as well if need be. Does that sound all right?

**Comment by Davidmh93** [comment]
I'm unable to pick this one up now sorry

**Comment by shailenpatel1** [comment]
Can I work on this?

**Comment by novemberborn** [comment]
@shailenpatel1 maybe you could pick up where https://github.com/avajs/ava/pull/2586 left off?

**Comment by novemberborn** [comment]
Merged in https://github.com/avajs/ava/pull/2696.
