### ISSUE TITLE
TypeScript errors not displayed when using a reporter

### ISSUE THREAD

**Issue by micaelmbagira** [avajs/ava#2457]
I have a TypeScript app and I am running the tests with the _tap-xunit_ reporter.
When there is a compilation error and using `--tap` the errors are not displayed

```
 $ nyc ava --tap | tap-xunit > testresults.xml
 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 lerna ERR! yarn run test:report stderr:
 error Command failed with exit code 1.
```

A more general question would be: is it possible to tap to multiple reporters? In this case, having the _verbose_ reporter on top of _xunit_ would solve it.

**Comment by novemberborn** [comment]
Our TAP reporter is barely functional unfortunately.

Do errors show in the `--tap` output itself? Would you happen to know how they should be formatted for `tap-xunit`?

**Comment by micaelmbagira** [comment]
@novemberborn Just did a simple repro case and the errors are displayed in the tap output. I will dig deeper if the problem comes from xunit or my CI/CD.
