### ISSUE TITLE
Ava --match glob does not match newlines

### ISSUE THREAD

**Issue by aureooms** [avajs/ava#2467]
Here is how to reproduce

```js
// test.js
import test from 'ava';
test('test\nhaha', t => t.pass());
```

Then

    ava test.js -m 'test*'

says `Couldn’t find any matching tests`.

Bug or feature? My current workaround is to `JSON.stringify` titles.

**Comment by novemberborn** [comment]
Yes I'd say it's a bug, but it originates in another package: https://github.com/sindresorhus/matcher/issues/24

**Comment by novemberborn** [comment]
@aureooms the `matcher` upgrade is now out in AVA 3.8.1.

**Comment by aureooms** [comment]
Thanks!
