### ISSUE TITLE
Process source maps in main process; allow disabling of processing

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2474]
Source maps get confusing real fast. I'd like to handle them more explicitly, removing the installation of [`source-map-support`](https://www.npmjs.com/package/source-map-support).

This means that any processing of stack traces should assume they have not been corrected for source maps. We should avoid unnecessarily processing stack traces in the worker processes. That means delaying source extraction:

https://github.com/avajs/ava/blob/1222ce9538e4890c20af695e558e3ee490f5a41b/lib/serialize-error.js#L76

Instead the main process should rewrite the stack trace. We should focus on the mini and verbose reporters (#2217 notwithstanding):

https://github.com/avajs/ava/blob/1222ce9538e4890c20af695e558e3ee490f5a41b/lib/reporters/beautify-stack.js#L68-L72

I'm really not too bothered about the stack traces that end up in the TAP output.

Line number selection attempts to find the original position of a test declaration. This does rely on a stack trace underneath. We should still convert using source maps, like we do now… though the current implementation probably breaks in certain conditions:

https://github.com/avajs/ava/blob/1222ce9538e4890c20af695e558e3ee490f5a41b/lib/worker/line-numbers.js#L74-L81

It should be possible to ask our `@ava/babel` and `@ava/typescript` providers to reverse-map a call site to the original source location.

We could do the same in the snapshot manager:

https://github.com/avajs/ava/blob/1222ce9538e4890c20af695e558e3ee490f5a41b/lib/snapshot-manager.js#L399-L405

That just leaves us with pre-compiled files that are *not* loaded through our providers, and files loaded with things like `ts-node/register`. Hopefully, those tools either already rewrite the stack traces for us, or `source-map-support/register` can be required by the user.

But, we do need an option to "assume stack traces are correct" which disables any source mapping. Otherwise we may and up mapping call sites twice.

My apologies for this issue being a bit of a brain dump. We can hash out the specifics together! The nice thing of this approach is that AVA won't change how your code runs (with automatic stack trace rewriting…), so your tests will better reflect what happens in live code.

**Comment by kaelzhang** [comment]
Any updates?

SourceMap problems never resolved in ava which drives people crazy

**Comment by novemberborn** [comment]
We'll switch to the Node.js built-in source map handling, see https://github.com/avajs/ava/issues/2763.
