### ISSUE TITLE
How to clear ava cache or any temporary files?

### ISSUE THREAD

**Issue by jcubic** [avajs/ava#2481]
I was working on my unit tests and I was running unit tests from Emacs ansi-term in watch mode using  inotifywait (so they was running in each file save) and something break because now each time I run the tests, every test is marked as pending and passing in same time (first is list all tests with pending status then list of all tests that are passing).

So I tough that this may be some kind of temporary files or cache that ava is creating that was not cleared. I've stashed all the changes I was working on got the same issues, same commit on Travis work fine.

**Comment by jcubic** [comment]
Just found this but it don't work: `./node_modules/.bin/ava reset-cache`.

**Comment by jcubic** [comment]
I'm running ava from nyc (too see conveage) but removing the both cache files don't work.

**Comment by jcubic** [comment]
I've commited trivial change and now my clean repo also fail, I'm running `nyc ava --verbose test.js` every tests is marked as pending and passing.

**Comment by jcubic** [comment]
Finally solved the issue using really long timeout: `nyc ava --timeout 10m --verbose test.js` 

Maybe there are just lot of tests and since they are all async it take time.

**Comment by novemberborn** [comment]
FWIW, AVA itself no longer writes temporary files. That only happens if you use `@ava/babel`.

**Comment by jcubic** [comment]
Yea it was not cache as I primary though it's just the my tests runs finish in 27 seconds (`user	0m27,328s` according to linux `time` command) and everything is async so it's probably real timeout but I'm not sure why it work fine without nyc but fail with nyc.

**Comment by novemberborn** [comment]
`nyc` adds overhead.
