### ISSUE TITLE
Create a documentation website

### ISSUE THREAD

**Issue by bok-jin** [avajs/ava#2493]
I noticed that there is a [repository containing the project documentation](https://github.com/avajs/ava-docs), but the English version is not there, some existing versions are out of date, some contain errors and the documentation reading experience is not welcoming at all.

I'm thinking of creating a GitHub page to centralize all the documentation, using tools like [Docusaurus](https://docusaurus.io) to manage it, for example.

I am willing to help with it, what do you think?
@novemberborn @sindresorhus @vadimdemedes

**Comment by novemberborn** [comment]
The English version is in this repository. Translations will fall behind, I think that's to be expected.

See https://github.com/avajs/ava/issues/1454#issuecomment-586707405 for the issue around having a website. We'd love the help!
