### ISSUE TITLE
Import from web root

### ISSUE THREAD

**Issue by mrozbarry** [avajs/ava#2496]
Please provide details about:

## What I'm trying to do

I'm building a web app that has no build steps and imports scripts using `type="module"`. All subsequent imports use `import foo from '/someFile.js'` - I specify the `/` because my web app is an SPA and all scripts are at the root. I'm also using CDNs where possible, like unpkg, which results in `import foo from 'https://unpkg.com/package?module=1'`, and node and esm don't do url imports.

## Why you can't use AVA for this

There is very poor support in most test frameworks for importing as if we're in a webserver. To get around this, I brought in [module-alias](https://www.npmjs.com/package/module-alias) and manually mapped all the relevant JS files to their local directories. I did something similar to remap the CDN urls, too.

## And maybe how you think AVA could handle this

I think `module-alias` is going to always be required for CDNs, there isn't really any way around that unless node supports it down the road.

But, I do think that ava could support an option, `importRoot: './path/relative/to/package.json/'` and maybe automatically remap imports that use a server root.

I think more test frameworks in general ~should~ **need to** support this. As more people migrate away from bundlers, and to `<script type="module" src="entry.js"></script>`, the more often there will be absolute paths used in import statements.

**Comment by novemberborn** [comment]
The goal of AVA is to be a Node.js test runner. We've found that trying to be clever with Node.js internals is not a viable strategy, _especially_ with the migration to ESM we'll be going through in the next couple of years.

I don't think we can do an "import root" feature in AVA itself. It might be possible to support this as a provider, along the lines of `@ava/babel` and `@ava/typescript`. But the benefits are low compared to requiring a third-party library that can take care of this, or perhaps even rewriting your import paths using Babel.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by mrozbarry** [comment]
I guess there are test frameworks that specifically run in the browser - maybe that's an option. I was hoping to run all my tests through ava (because let's face it, ava is pretty :sunglasses: ), but maybe this is a square peg/round hole situation. I am, however, surprised that testing in javascript is very geared towards node/web bundlers, but I guess that keeps the ecosystem node compatible.

**Comment by novemberborn** [comment]
> I am, however, surprised that testing in javascript is very geared towards node/web bundlers, but I guess that keeps the ecosystem node compatible.

There's at least two ecosystems in JavaScript 😉 Browser ecosystems tend to assume bundlers, a fully working ESM implementation, and as you found a different assumption around where the modules are coming from. In Node.js there's little use of bundlers, there's like 5 different ESM implementations, and of course a different runtime than for the browser.

That's not to say you can't test browser code in AVA, but the more things you use from a browser ecosystem, the harder it gets.

**Comment by mrozbarry** [comment]
I'd think that ava in the browser would _probably_ be a bad time - the main appeal of ava is how it divides up files to run tests quickly, and I'm not sure how that would work in the browser aside from spinning up a bunch of child windows. I don't think workers would be a good option because those are sandboxed and limited in which web apis they can access.
