### ISSUE TITLE
Support registering a custom assertion module

### ISSUE THREAD

**Issue by ColCh** [avajs/ava#25]
How to use it?  For example,  Chai is very nice. Or assert.js

**Comment by sindresorhus** [comment]
Yes you can. Updated the readme about it: https://github.com/sindresorhus/ava/commit/3deba5189186ce73ef6a7bc18c4044f713c63eed

It won't work with planned assertions though. For that, we'll need an AVA method that hooks those assertion so we can do the assert counting. Shouldn't be that hard, but not top priority.

**Comment by ColCh** [comment]
Thanks. Any tutorial on how to do that? Code sample will be cool.

**Comment by sindresorhus** [comment]
How to do what? With assert counting is not possible yet as outlined above. Without assert counting is documented in the readme as already mentioned.

**Comment by sindresorhus** [comment]
Please read the discussion in https://github.com/sindresorhus/ava/pull/49 before commenting.

**Comment by novemberborn** [comment]
I think we've become quite comfortable with AVA's built-in assertions since this issue was raised. We won't be adding tight integration for other assertion libraries any time soon, so I'm closing this issue.

**Comment by sindresorhus** [comment]
People can already use their favorite assertion module with AVA. It just won't work with planned assertions. That being said, I almost never use planned assertions anymore, now that we have async/await.
