### ISSUE TITLE
Hitting "The job exceeded the maximum log length..." on Travis CI

### ISSUE THREAD

**Issue by aureooms** [avajs/ava#2502]
I have a project were I run a lot of tests with AVA (> 30000 test calls).
I use travis-ci.org for CI. Current setup logs one line per test in the travis log.
The test suite logs approximately 27000 lines before being halted by Travis which says "The job exceeded the maximum log length, and has been terminated.". Is there a way to log less?

**Comment by novemberborn** [comment]
Ha, isn't that something!

You could redirect to a file, I suppose. But it'll be hard to find the failing tests. Then again with that many test calls I imagine that's a problem regardless.

Maybe output using `--tap` and pipe through something which highlights failing cases only?

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by aureooms** [comment]
> Maybe output using --tap and pipe through something which highlights failing cases only?
Yes I could try that. I wonder if it is worth adding an option for this kind of filtering directly in ava. Probably not.

**Comment by aureooms** [comment]
Currently using `--tap` and piping to [`tap-dot`](https://github.com/scottcorgan/tap-dot) works great.
