### ISSUE TITLE
Question: how to avoid snap conflicts

### ISSUE THREAD

**Issue by fisker** [avajs/ava#2504]
I'm using snap testing, problem is there are conflicts on every PR, since git can't merge `.snap` file. I tried to not store `.snap` file, but it won't work.

What's the best practice? Can we document it?

**Comment by novemberborn** [comment]
The `.snap` files contain the actual snapshot data, so you do need to commit them.

I merge or rebase the PR, locally, and update the conflicting snapshots by running that test file with `npx ava -u path/to/file`.

Perhaps you could do a PR to add this to https://github.com/avajs/ava/blob/master/docs/04-snapshot-testing.md?

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by fisker** [comment]
So, you are saying there is no way to store `.snap` as text now? And that means there has to be conflicts.

**Comment by novemberborn** [comment]
That's correct. But it's been that way for nearly three years now.

The way we preserve the data, so that we can do comparisons and render diffs, does not lend itself to a text based format.

**Comment by fisker** [comment]
Will we consider diff the `.md` file? Or behind a option, in that way we don't need store the `.snap`.

**Comment by novemberborn** [comment]
No, the Markdown file is just there for humans to look at.

**Comment by sindresorhus** [comment]
I think the proper fix here is for GitHub to make it possible to resolve merge conflicts concerning binary files in the GitHub UI. Maybe even https://github.com/sindresorhus/refined-github could do something about it. At least worth opening an issue there.

**Comment by fisker** [comment]
> No, the Markdown file is just there for humans to look at.

But different snap always  has  different `md` file, right?

**Comment by fisker** [comment]
@sindresorhus  I  don't understand how that can  resolve this  problem. It's not  text file, Either the  master snap nor the PR snap  is  right  , I thought  the  only way is re-generate it  by `ava`?

**Comment by novemberborn** [comment]
@fisker yea you'd have to pick either file (and make the same choice for the Markdown file), which probably isn't what you want.

**Comment by sindresorhus** [comment]
@fisker You're right. I was thinking you could just pick one, but that obviously won't work.
