### ISSUE TITLE
fast-glob call in test returns incorrect results in ava test

### ISSUE THREAD

**Issue by adam-lynch** [avajs/ava#2509]
This is a really weird one and I've lost hours trying to figure out what's going on. This is as far as I've narrowed it down but I'm not sure where the actual problem lies

### Environment

  * OS Version: macOS 10.15.2
  * Node.js Version: 12.16.1
  * npm version: 6.13.4
  * fast-glob version: 3.2.2
  * ava version: 3.8.2
  * Reproduce: https://github.com/adam-lynch/ava-fast-glob-issue

### Actual behavior
Only finds one file (`package.json`).

### Expected behavior
Finds two files (`package.json` and `yarn.lock`).

### Steps to reproduce

TL;DR: Follow steps in https://github.com/adam-lynch/ava-fast-glob-issue

_**In an Ava test**_, use fast-glob to match the following globs in a directory which contains `package.json` and `yarn.lock`:

- `*.txt`
- `package.json`
- `yarn.lock`

### Code sample

See:

1. https://github.com/adam-lynch/ava-fast-glob-issue/blob/master/test/index.js
2. https://github.com/adam-lynch/ava-fast-glob-issue/blob/master/index.js

### Other notes

- If not ran in Ava test, it all works.
- If `unique` is set to `false`, it all works.
- If `*.txt` is removed, it all works.
- There are common dependencies between ava and fast-glob but they all seem to be the exact same version.
- I tried to find any related ava/fast-glob reported issues but had no luck.
- fast-glob issue: https://github.com/mrmlnc/fast-glob/issues/272

**Comment by novemberborn** [comment]
Something came up and I haven’t yet had a chance to look at this.

**Comment by adam-lynch** [comment]
No prob @novemberborn. fast-glob have said it looks like a duplicate of https://github.com/mrmlnc/fast-glob/issues/268. It seems like running fast-glob via TypeScript makes it behave differently (🤷 ). I'll close this
