### ISSUE TITLE
expectations.is for the "throws" assertion doesn't make sense

### ISSUE THREAD

**Issue by gwn** [avajs/ava#2513]
AVA version 3.8.2
No configuration

Code below:
```
require('ava')('failed expectations', t =>
    t.throws(
        () => { throw new Error('asdf') },
        {is: new Error('asdf')},
    )
)
```

Causes the following warning:
```
  Returned promise rejected with unexpected exception:

  Error {
    message: 'asdf',
  }

  Expected to be strictly equal to:

  Error {
    message: 'asdf',
  }
```
And it makes sense.

The [documentation][exp-is] says the following about `expectations.is`:
> is: the thrown error must be strictly equal to expectation.is

[exp-is]: https://github.com/avajs/ava/blob/master/docs/03-assertions.md#throwsfn-expectation-message

The problem is that; there is also the requirement that the function throw an instance of the Error class. This doesn't play well with the "strict equality" requirement. Since strict equality for objects means that the compared objects has to be the exact same instance, how can anybody do anything at all with `expectations.is`? How can a test author obtain the exact same error instance that is thrown by the tested function before it is thrown?

Am I missing something? Please help.

Here is the relevant source code bit, for quick reference:
https://github.com/avajs/ava/blob/master/lib/assert.js#L144-L169

**Comment by sindresorhus** [comment]
You export the error constructor. This is quite a common pattern \*. If you don’t want to do that. Simply use a different property like `message`.

\* https://github.com/sindresorhus/p-event#peventtimeouterror

**Comment by novemberborn** [comment]
This is meant for circumstances where you can stub a function so it throws a specific error object.

**Comment by gwn** [comment]
Thank you.
