### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by SephReed** [avajs/ava#2514]
Every time I start a new project in Typescript and try to use Ava, it's an ordeal.

Something has changed since the last time I did it, so now I'm stuck having to figure it out again.

Please, please support Typescript.

I want this command to work:
`ava src/**/*.test.ts`

In the very least, it should give an error that gives direction.

**Comment by sindresorhus** [comment]
Have you followed the instructions in https://github.com/avajs/typescript ?

**Comment by SephReed** [comment]
Yeah.  I installed `tsc` instead of `typescript`.  I've put in a PR to make the docs more up front.

https://github.com/avajs/ava/pull/2515

**Comment by novemberborn** [comment]
> I want this command to work:
> `ava src/**/*.test.ts`
> 
> In the very least, it should give an error that gives direction.

Yes, and as we discussed a month ago, this is covered by #2373.

We won't ship TypeScript support out of the box. There's too many different ways people expect it to work. But AVA should guide you in the right direction, and `@ava/typescript` should support those ways.
