### ISSUE TITLE
React recipe: Enzyme usage is out of date

### ISSUE THREAD

**Issue by dschinkel** [avajs/ava#2522]
Your docs seem out of date for your enzyme integration.  People use the enzyme **adapter** now-days.

I'd be willing to update the docs but wanna throw this out here first.

**Comment by sindresorhus** [comment]
Help with bringing the recipe up to date would be much appreciated.

**Comment by novemberborn** [comment]
I think this is the [React recipe](https://github.com/avajs/ava/blob/master/docs/recipes/react.md)?

**Comment by Michael55555** [comment]
Can we close this issue, since we've merged #2573?
