### ISSUE TITLE
Importing image files into React Component causes Ava to Crash

### ISSUE THREAD

**Issue by dschinkel** [avajs/ava#2525]
**Tried to run tests after I added an image to my React Component:**
`import Logo from './logo.png'`

**then in my React Component:**
`<img src={Logo} alt="logo" />`

**Error during test run:**
```
Uncaught exception in test/some.spec.js

/src/client/logo.png:1
  �PNG

  SyntaxError: Invalid or unexpected token

  › SyntaxError: Invalid or unexpected token
  › newLoader (node_modules/pirates/lib/index.js:104:7)

  ✖ test/some.spec.js exited with a non-zero exit code: 1
  ─

  1 uncaught exception
```

**My tests we fine before this**

So it looks like somehow it's not able to transpile and for some reason trying to run index.js.  I just added the ability to load images in webpack and then that code to my react component and now Ava is not working.

**Comment by novemberborn** [comment]
You need to install some sort of `require` hook which knows how to deal with `.png` files. Currently Node.js assumes it's a JavaScript module.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by dschinkel** [comment]
I feel like this should be something everyone here has come across and fixed by now with Ava.  So how are you running tests when you have images in your React components like this?  It's not hitting webpack so what do you need to do to tell Ava to either ignore this or load the so-called require hook?  Anyone have an example doing this already?

**Comment by dschinkel** [comment]
**Here's the fix**

**ava.config.js**
**require: ['@babel/register', **'./test/compiler.js'**]**

**compiler.js**
/*
  Disable webpack-specific features for tests since
  tests do not use webpack in order to handle these
  if SUT is working with these types of files
*/
require.extensions['.css'] = function () {
  return null;
};
require.extensions['.png'] = function () {
  return null;
};
require.extensions['.jpg'] = function () {
  return null;
};

this is the same fix people used for mocha.  Would be nice it it were part of ava, where it could take care of this itself somehow.  I guess maybe that is something I could work on if I have time but right now I just don't.

**Comment by novemberborn** [comment]
> Would be nice it it were part of ava, where it could take care of this itself somehow.

AVA is a Node.js test runner. What you're doing here is trying to run your browser code outside of a browser and it's build process. That's going to require some workarounds, as you found out.
