### ISSUE TITLE
test.beforeEach not Working as Expected?

### ISSUE THREAD

**Issue by dschinkel** [avajs/ava#2526]
This is odd, pretty sure it's not my code.  

What's weird about this is **Calculator()** creates a new instance whenever it's called.  

So by moving the creation of the calculator per test in **beforeEach** I'd expect this third test to still pass. 

But for some reason, it looks like it's not creating a unique instance for my third test even though I specified to run the call in a beforeEach which should definitely have created a unique instance of Calculator for it

```js
test.beforeEach(t => {
  calculator = Calculator();
});

test('default evaluates to zero', t => {
  calculator.evaluate();
  t.is(calculator.getResult(), 0);
});

test('adds two positive numbers', t => {
  calculator.evaluate('0+1');
    t.is(calculator.getResult(), 1);
});

// this fails because it's retaining state from the previous test for some odd reason and so my assertion fails with a 16 instead of 15
test('handles multiple operations', t => {
  calculator.evaluate('0+1');
  calculator.evaluate('0+4');
  calculator.evaluate('10');

  t.is(calculator.getResult(), 15);
});
```

**If I put back what I had without the beforeEach and a const in each test, this is fine and passes:**

```js
test('handles multiple operations', t => {
  const calculator = Calculator();
  calculator.evaluate('0+1');
  calculator.evaluate('0+4');
  calculator.evaluate('10');

  t.is(calculator.getResult(), 15);
});

```

**Comment by novemberborn** [comment]
I wouldn't necessarily have expected that to fail, since the tests are synchronous, but what's probably happening is that a `beforeEach` hook is run for a new test and it overwrites the shared variable.

Use `test.serial()`, or better yet, assign unique calculators to `t.context`.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by dschinkel** [comment]
I think there was ultimately not a problem here.  I don't know what changed but after writing more code and refactoring, it's fine now.
