### ISSUE TITLE
Verify a snapshot's markdown report against its binary file

### ISSUE THREAD

**Issue by frangio** [avajs/ava#2528]
When doing snapshot testing, AVA generates a binary file and a markdown report. The markdown report is really useful because it can be inspected by a person during review, but AVA ignores it and really only compares test results against the binary file.

Since the binary file can't be inspected by a person during review, I would like AVA to inspect it and verify that it matches what is represented in the markdown report.

**Comment by sindresorhus** [comment]
We could maybe embed a hash of the binary in the Markdown file. AVA could then take the hash from the Markdown file and check.

**Comment by frangio** [comment]
A hash would prevent against accidents, but we could also imagine a malicious actor that intentionally submits a fake report. In that scenario they would be able to manually set the correct hash and bypass the check. I know this sounds somewhat far fetched, so I'm curious to hear what you think...

A way to fully protect from that would be to regenerate the markdown report from the binary file contents, and then compare that to the one on disk.

**Comment by novemberborn** [comment]
Who is your adversary in this scenario, @frangio? How likely is it that you don't notice a vulnerability introduced in code but hidden by manipulating the snapshot report?

We can't currently regenerate the Markdown file from the snapshot alone, though we should gain that ability. I haven't looked whether that's already tracked.

**Comment by novemberborn** [comment]
I should also say that the serialization and comparison algorithms used to create and verify snapshots are designed for accuracy, but could still be manipulated if you control the snapshot data.

**Comment by novemberborn** [comment]
Thinking about this more, I see two problems with verifying the Markdown report.

* Oddly configured Git repositories may rewrite line-endings.
* Changes in report generation may lead to verification failures, making them *breaking* changes.

Ultimately AVA is a tool to test your code, where we assume a decent level of trust in terms of who contributes the code. I don't think AVA should be the one defending against bad actors tricking you into accepting malicious code.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by frangio** [comment]
>How likely is it that you don't notice a vulnerability introduced in code but hidden by manipulating the snapshot report?

If the vulnerability is introduced in the project's own code then it would likely be discovered. If the vulnerability is indirectly introduced through a dependency it may be more likely missed, but it's more difficult to orchestrate.

In any case, I think the reasons for not implementing it make sense. Thank you for considering it!
