### ISSUE TITLE
ava, ~, and tsconfig-paths

### ISSUE THREAD

**Issue by jupl** [avajs/ava#2537]
I am following the instructions as noted here: https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md#using-module-path-mapping

With the following `tsconfig.json`:

```
{
	"baseUrl": ".",
	"paths": {
		"~/*": ["src/*"]
	}
}
```

When I have a file `/some/project/src/users/test.ts' like this:

```ts
import {something} from '~/common/util'
```

I get an error like this:

```
Error: Cannot find module '/some/project/src/users/~/common/util'
````

The path should resolve to `/some/project/src/common/util`.

If I change `~` to something else like `_` in `tsconfig.json` and `test.ts` it works just fine. Also I have no issue using `~` with `tsconfig-paths` in other test libraries like Mocha and Jest. In fact, this is the first time I've come across this issue with ava.

**Comment by novemberborn** [comment]
I take it you're using `ts-node/register` and `tsconfig-paths/register`? Are you combining this with `@ava/typescript`? (You shouldn't be.)

I can't really help with this I'm afraid, I don't use those tools. Improvements to the recipe are welcome though.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by jupl** [comment]
I'm not using `@ava/typescript`. And it's unfortunate you are closing the issue since others who potentially may have more experience and insight will less likely see this issue. This is a major deal breaker for me as I use `parcel`, which uses `~` for path resolution.

**Comment by jupl** [comment]
I think it makes no sense for this to be closed. You said you can't help, but if you keep this closed the visibility of this issue is limited as perhaps someone who may have insight into this will less likely see this.

**Comment by novemberborn** [comment]
> if you keep this closed the visibility of this issue is limited as perhaps someone who may have insight into this will less likely see this

Open or closed, it's been my experience in this project that it makes no difference either way. I'll see about getting access to GitHub's new Discussions feature which would be a better fit for resolving this.

**Comment by jupl** [comment]
Ok. Well I added some more details.

**Comment by CraigglesO** [comment]
I fought this for a few hours. I don't do it EXACTLY this way, but I found that ava + modules + paths was a nightmare. I switched to `vitest` and it immediately worked out of the box. I would recommend to anyone going the typescript test path to just use vitest.
