### ISSUE TITLE
console.log(JSON.stringify({...})) print a large json inside ava test only show part

### ISSUE THREAD

**Issue by zyfmix** [avajs/ava#2538]
Please provide details about:

node: v14.5.0
"ava": "^3.10.1"

* What you're trying to do
console.log(JSON.stringify({...})) print a large json

* What happened
print part in terminal

* What you expected to happen
print full continuity

![image](https://user-images.githubusercontent.com/12183914/87382858-9578a980-c5ca-11ea-94f7-282071402397.png)
![image](https://user-images.githubusercontent.com/12183914/87382900-afb28780-c5ca-11ea-8bcc-20f111b212ab.png)

**Comment by novemberborn** [comment]
I think this is the same underlying issue as https://github.com/avajs/ava/issues/1758. We can't get the data out quickly enough and then it gets corrupted, and yea the spinner also gets in the way.

Running with `--verbose` or `verbose: true` may work. I tend to use `console.error()` as well.

Sorry I know this isn't great.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by zyfmix** [comment]
> I think this is the same underlying issue as #1758. We can't get the data out quickly enough and then it gets corrupted, and yea the spinner also gets in the way.
> 
> Running with `--verbose` or `verbose: true` may work. I tend to use `console.error()` as well.
> 
> Sorry I know this isn't great.
> 
> (I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

Thank you for your reply,I'll try it!
