### ISSUE TITLE
animation spinner fills the console with new lines

### ISSUE THREAD

**Issue by dcsan** [avajs/ava#2541]
The little animation spinner is cute as the tests are running, however it seems to degrade and then put a newline on every iteration. My test run ends up filling pages of console

![image](https://user-images.githubusercontent.com/514002/87484731-cddcaf80-c5eb-11ea-8635-a84b43a82e89.png)

if the feature is broken, is there a way to at least disable it?

```
⠙ Actor › game loading
⠹ Actor › game loading
⠸ Actor › game loading
⠼ Actor › game loading
⠴ Actor › game loading
⠦ Actor › game loading
```

**Comment by novemberborn** [comment]
Yea that's not good.

It should be better with `--verbose` or `verbose: true` in the configuration.

**Comment by novemberborn** [comment]
I assume you have some `console.log()` output in the test / tested code?

**Comment by dcsan** [comment]
yes there are some logs there
`reply input: xx`

so perhaps that triggered the new lines to be happening...

![image](https://user-images.githubusercontent.com/514002/87580289-23689900-c68c-11ea-8d65-f172a29b1129.png)

**Comment by G-Rath** [comment]
I hit then when using ava for the first time when implementing a feature in [np]():

![image](https://user-images.githubusercontent.com/3151613/88848963-4757dd00-d23d-11ea-8cfd-cd7c257de1cc.png)

The above is a slice of a very long output filled with more of the same 😬 

While the loading spinner is indeed very pretty, having the ability to disable would be a great short-term solution.

**Comment by novemberborn** [comment]
Aha! While we try to clear the spinner (on stdout), before writing the output from the test (to stderr)… we don't wait for this to complete. I think I know how to fix this…

**Comment by novemberborn** [comment]
This should be fixed in `master` now. Normally I do releases at the end of the weekend, so it should be available soon.
