### ISSUE TITLE
Nested Describes

### ISSUE THREAD

**Issue by dschinkel** [avajs/ava#2546]
It doesn't appear Ava supports describes.  Unless I'm missing it in the docs, I miss my describes.

**Comment by novemberborn** [comment]
Nope, that's on purpose. We don't think BDD necessarily makes your tests any better. Sorry to disappoint 😄 

There's https://www.npmjs.com/package/ava-describe but I haven't checked how it's implemented.

I've started playing with ways of creating your own `test()` function on which you could install separate before / after hooks, which would allow for a BDD interface to be built properly. Keep an eye on #2435 for that.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by dschinkel** [comment]
And I'm sorry to annoy, but that's very short-sited.  Who's "we".  And who decides when BDD is useful or not?

Lets get to the point here.  A describe allows you to give a description of the feature under test.  Those who are only testing "per function" aren't testing "per behavior".  When I TDD, I go outside-in, and my tests describe behavior not implementation details so describes and test names go hand in hand when I'm reading groups of tests.

That third party ava-describe sucks.  This should be built-int Ava.  If you only want to allow one level of describes that's fine, because nested to me is an indicator that you need to break your features out into separate spec files anyway and the spec is doing too much but first level describes are important to have in any framework.

**Comment by dschinkel** [comment]
And I'm sorry to annoy, but that's very short-sighted to just come to such a conclusion. Who's "we". And who decides when BDD is useful or not?

Lets get to the point here. A describe allows you to give a description of the feature under test. Those who are only testing "per function" aren't testing "per behavior" because if you're only writing tests with implementation details in the test name, you're not getting "testing" to be frank, whoever you are.

When I TDD, I go outside-in, and my tests describe behavior not implementation details so describes and test names go hand in hand when I'm reading groups of tests.

That third party ava-describe sucks. This should be built-into Ava. If you only want to allow one level of describes that's fine, because nested to me is an indicator that you need to break your features out into separate spec files anyway and the spec is doing too much but first level describes are important to have in any framework.

Also have you considered that describes are useful both at the command-line and in IDEs like IntelliJ once they do create an Ava plugin? We'll want describes in there so we can clearly see features and expand tests under each feature.

This is enough for me to say forget Ava and go back to crappy slow Jest or even mocha (fast) was fine. Whether or not you care isn't the point, it's that to come to a conclusion that describes are not useful is bogus in any testing framework.

I see that the filename is output with -> but the problem with writing your tests per filename makes no sense to someone who is writing tests that are decoupled from implementation details.  My test names do not go 1:1 with filenames, that's a naive way to test or TDD code if you're doing TDD.  A lot of us don't want our tests coupled to filenames in fact, we want them coupled to behavior.

**Comment by novemberborn** [comment]
AVA's been around for a long time already. We, the maintainers, have never seen the need to include other interfaces, at least in the core `ava` project itself.

The work in #2435 will make it possible for a BDD interface to be build on top of the core project, and we'd be more than happy to host that in our GitHub organization and publish it under our npm namespace (e.g. `@ava/bdd`).

**Comment by dschinkel** [comment]
Alright maybe I'll contribute once it's possible.
