### ISSUE TITLE
Tell ava to ignore a file

### ISSUE THREAD

**Issue by kevholder** [avajs/ava#2562]
I have a `test/common.js` file that is used by my test files to setup common stuff, but ava outputs this error: `✖ No tests found in test/common.js, make sure to import "ava" at the top of your test file`. Is there a way to tell ava that this is expected so it stops outputing that error?

**Comment by sindresorhus** [comment]
There's an ignore option. See the config docs.

**Comment by kevholder** [comment]
Would be nice to auto ignore some files by convention, based on their file name, maybe `_common.js` ?

**Comment by novemberborn** [comment]
It already works like that.

**Comment by kevholder** [comment]
@novemberborn oh it does, thanks. guess that answers the question... maybe it should be documented somewhere if it isn't already.
