### ISSUE TITLE
t.passed is undefined in teardown context

### ISSUE THREAD

**Issue by tymfear** [avajs/ava#2572]
Please provide details about:

* What you're trying to do - save page screenshot in `t.teardown` callback when test has failed
* What happened - `t.passed` is `undefined`.
* What you expected to happen - `t.passed` to be defined. Since `t.teardown` might be used instead of `test.afterEach` hook it should have similar capabilities.

Code example:
```javascript
test('do some web testing', async t =>{
  t.teardown(async () => {
    if(!t.passed) {
       const imageName = `${t.title}.png`;
       t.log(`Saving screenshot "${imageName}" because test has failed`);
       await takeScreenshotAndSave(imageName);
    }
  })
})
```

**Comment by novemberborn** [comment]
Agreed. We can update `t.passed` once the test completes, and then it'll be accurate in a teardown.

We run the teardowns here:

https://github.com/avajs/ava/blob/983ce0cb714fe0b35b48834c0911ebd4cf8e71d6/lib/test.js#L728

A little later is the code that determines whether the test passed:

https://github.com/avajs/ava/blob/983ce0cb714fe0b35b48834c0911ebd4cf8e71d6/lib/test.js#L732-L733

We can move that up, and assign `this.testPassed = passed`. That should do the trick.

Teardown tests live here:

https://github.com/avajs/ava/blob/75cbc3b2a53d3b8530266b10bed71b838bc11fec/test-tap/test.js#L750

**Comment by tymfear** [comment]
@novemberborn, so I did the following change https://github.com/tymfear/ava/pull/1/files

Tested in manually - it works.

But I have no idea on how to create a test for that. Was thinking of something like
```javascript
test('t.passed is set in teardown for passing test', t => {
  return ava(a => {
    a.teardown(() => {
      t.is(result.passed, true) // <-------- Don't know how to reach the "passed" value as context is not passed to teardowns
    });
    a.pass();
  }).run().then(result => {
    t.is(result.passed, true);
    t.ok(teardown.calledOnce);
  });
});
```

Any idea on this?

**Comment by tymfear** [comment]
@novemberborn Ok, I found solution on how to create test for the change, but still what are your opinion of passing `t`-like object to teardowns?

**Comment by KarenEfereyan** [comment]
This seems like a pretty interesting issue. But it is already being handled. Kudos to you @tymfear
