### ISSUE TITLE
Sets are incorrectly compared for `t.deepEqual`

### ISSUE THREAD

**Issue by papb** [avajs/ava#2588]
Code:

```js
t.deepEqual(new Set([1, 2]), new Set([2, 1]))
```

Expected behavior: assertion should pass

Actual behavior: assertion fails:

```
Difference:

    Set {
  +   2,
      1,
  -   2,
    }
```

**Comment by novemberborn** [comment]
This is by design. Sets and Maps are compared not only by contents, but also by insertion order.

**Comment by novemberborn** [comment]
@tarochipz not with AVA's assertions. You'd have to write some logic, say compare the sizes and then iterate over one set and check that the other has all values.
