### ISSUE TITLE
Update TypeScript recipe for ESM support

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2593]
@FallingSnow [shared](https://github.com/avajs/ava/issues/2347#issuecomment-698499005) how to (experimentally) configure AVA and Node.js so that AVA can load TypeScript-based ESM files:

```json
"ava": {
    "extensions": {
      "ts": "module"
    },
    "nonSemVerExperiments": {
      "configurableModuleFormat": true
    },
    "nodeArguments": [
      "--loader=ts-node/esm",
      "--experimental-specifier-resolution=node"
    ],
    "files": [
      "test/**/*.spec.ts"
    ]
}
```

It'd be great to add this to our [TypeScript recipe](https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md).

**Comment by thasmo** [comment]
Trying to run TypeScript tests with ESM support, but failed to do so with the configuration above, adapted to my setup.
```
export default {
    nonSemVerExperiments: {
        nextGenConfig: true,
        configurableModuleFormat: true,
    },
    nodeArguments: [
        '--loader=ts-node/esm',
    ],
    extensions: {
        ts: 'module',
    },
    require: [
        'ts-node/register/transpile-only',
    ],
    files: [
        'packages/*/test/**/*.ts',
    ],
}
```

I'm running it with Node 14 and TypeScript 4, which results in this errors:
```
➜ npm test

> test
> ava

⚠ Experiments are enabled. These are unsupported and may change or be removed at any time.

(node:13990) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13996) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13997) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14010) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14004) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14025) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14018) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14031) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14038) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

  ✖ No tests found in packages/pack-cache/test/pack.ts
  ✖ No tests found in packages/pack-environment/test/pack.ts
  ✖ No tests found in packages/pack-watch/test/pack.ts
  ✖ No tests found in packages/pack-less/test/pack.ts
  ✖ No tests found in packages/core/test/packs/optimization.ts
  ✖ No tests found in packages/core/test/packmule.ts
  ✖ No tests found in packages/pack-log/test/pack.ts
  ✖ No tests found in packages/core/test/packs/base.ts
  ✖ No tests found in packages/core/test/packs/minification.ts

  ─

Uncaught exception in packages/pack-cache/test/pack.ts

Error: ERR_UNSUPPORTED_DIR_IMPORT /mnt/c/Users/thasmo/Projects/packmule.packmule/packages/pack-cache/src/ /mnt/c/Users/thasmo/Projects/packmule.packmule/packages/pack-cache/test/pack.ts

  › finalizeResolution (node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:370:17)
  › moduleResolve (node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:809:10)
  › Object.defaultResolve (node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:920:11)
  › node_modules/ts-node/src/esm.ts:55:38
  › Generator.next (<anonymous>)
  › node_modules/ts-node/dist/esm.js:8:71
  › __awaiter (node_modules/ts-node/dist/esm.js:4:12)
  › resolve (node_modules/ts-node/dist/esm.js:31:16)
```

**Comment by fregante** [comment]
I think the configuration above needs to be paired with a `tsconfig.json` containing:

```json
{
	"compilerOptions": {
		"target": "es2020",
		"module": "commonjs", // Without this, TS will still generate ESM and fail
		"esModuleInterop": true
	}
}
```

Still working on it though...

**Comment by fregante** [comment]
I can confirm that the first configuration works, as long as it's paired with:

```json5
// tsconfig.json
{
	"compilerOptions": {
		"module": "ESNext", // Or any ES version
		"esModuleInterop": true // Or else TypeScript will complain about CJS packages, even if Node can `import` them
	}
}
```

and 

```json5 
// package.json
{
	"type": "module" // Because the TS output is now ESM
}
```

**Comment by mikob** [comment]
This doesn't work with default exports for me. 

e.g.
```
import Visitor from "@swc/core/Visitor.js";
console.log('Visitor', Visitor);
```

prints:
`Visitor { default: [class Visitor] }`

@swc/core/Visitor looks like this:
```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
class Visitor { ... }
exports.default = Visitor;
```

**Comment by novemberborn** [comment]
@mikob that's a typical interoperability pattern to make CJS behave like ESM. However now that you're using actual ESM, it does not behave the way you expect. See https://nodejs.org/api/esm.html#esm_import_statements:

> When importing CommonJS modules, the module.exports object is provided as the default export. Named exports may be available, provided by static analysis as a convenience for better ecosystem compatibility.

You *might* be able to `import { default as Visitor } from …` but `default` is a special member so that probably won't work.

**Comment by mikob** [comment]
> You might be able to import { default as Visitor } from … but default is a special member so that probably won't work.

Tried that as well without success. In the end I reverted to using "esm" (https://github.com/standard-things/esm) in the "requires" property for ava.

**Comment by novemberborn** [comment]
That might paper over the cracks for now, yes. AVA 4 removes the special treatment for that package though.

**Comment by fregante** [comment]
Node 16.10 or later will break the ESM loader, not sure if this affects this recipe.

- https://github.com/TypeStrong/ts-node/issues/1007#issuecomment-917677011

**Comment by Akiyamka** [comment]
At this moment `ts-node/esm` can't handle some [edge-cases ](https://github.com/TypeStrong/ts-node/issues/1007#issuecomment-977820602).
More stable alternative is [esbuild-node-loader](https://www.npmjs.com/package/esbuild-node-loader).
Es-build work in transpile only mode, but work much faster.
```json
"ava": {
  "extensions": {
    "ts": "module"
  },
  "nodeArguments": [
    "--loader=esbuild-node-loader",
    "--experimental-specifier-resolution=node"
  ],
  "nonSemVerExperiments": {
    "configurableModuleFormat": true
  }
}
```

**Comment by Cobertos** [comment]
The above config is _much_ better.

The [default installation using `ts-node/esm`](https://github.com/avajs/ava/blob/main/docs/recipes/typescript.md#for-packages-with-type-module) was very slow. I had to increase the timeout for my tests.

My code makes heavy use of ES6 features like async/await syntax, Promises, Generators, AsyncGenerators etc. I narrowed down a couple problem tests and found that ES6 features that were working previously (in js before migrating to TypeScript) started working differently. Awaiting an object that wasn't a `Promise` was giving unexpected values. `for...of` loops over a custom Iterable would always received undefined, unless I manually called .next() myself.

After switching to the above (`esbuild-node-loader`) all my tests passed and it was much faster

**Comment by rrichardson** [comment]
I created a small PR to update the typescript recipe per the above  (I independently found the solution.. searching the issues here would have saved me some time :) ) 

https://github.com/avajs/ava/pull/2910

**Comment by mesqueeb** [comment]
I'm getting:
>   ✖ nonSemVerExperiments.configurableModuleFormat from undefined is not a supported experiment

**Comment by novemberborn** [comment]
@mesqueeb see https://github.com/avajs/ava/issues/2945.

**Comment by Grawl** [comment]
just started to work with AVA, and I want to replace Jest with it on my regular Webpack project (with Quasar Framework under the hood).

I have a lot of `.ts` files written with `import`/`export` and a few tests using some of them.

No one guide helped me with setup because I have Typescript files written in ESM. I tried a few configs from issues here and from guides of AVA and `@ava/typescript` but I do not want to compile tests before running, and I cannot add `"type": "module"` to my `package.json` because Webpack and other tools goes crazy with it.

Only one working solution it using esbuild like @Akiyamka offers. Here's my working config:

```js
module.exports = {
	'extensions': {
		'ts': 'module',
	},
	'nodeArguments': [
		'--loader=esbuild-node-loader',
		'--experimental-specifier-resolution=node',
	],
}
```

Also I have to `yarn add -D esbuild-node-loader` but it's fast and safe I think.

**Comment by fregante** [comment]
I'm getting `ERR_IMPORT_ASSERTION_TYPE_MISSING` when importing a JSON file in Node 16.16 but Node 16.14 works fine 😅 

Replacing `ts-node/esm` with `esbuild-node-loader` worked 🎉 

- https://github.com/refined-github/github-url-detection/pull/143

**Comment by plantain-00** [comment]
`esbuild-node-loader` is deprecated: https://github.com/antfu/esbuild-node-loader
I use `tsx`(https://github.com/esbuild-kit/tsx) instead and it works fine for me:

```ts
{
  "extensions": {
    "ts": "module"
  },
  "nodeArguments": [
    "--loader=tsx",
  ]
}
```

**Comment by fregante** [comment]
@novemberborn can you update the first post with @plantain-00’s? Thankfully now the amount of config is reduced (tested on Node 18)

**Comment by novemberborn** [comment]
> Or maybe this issue should be closed since [`main`/docs/recipes/typescript.md](https://github.com/avajs/ava/blob/main/docs/recipes/typescript.md?rgh-link-date=2023-02-03T07%3A04%3A33Z) seems to be up to date (although it uses `ts-node`)

That works for me, though you're suggesting it's not ideal?

**Comment by Sparticuz** [comment]
ts-node seems to be unmaintained, @plantain-00's solution should probably be what should be on https://github.com/avajs/ava/blob/main/docs/recipes/typescript.md

Maybe including a link to this page would be helpful to determine which loader the user would want to use https://github.com/privatenumber/ts-runtime-comparison

**Comment by MartynasZilinskas** [comment]
@Sparticuz for the performance reasons tsx looks like a good option. But has no support for `emitDecoratorMetadata`. I think `ts-node` has only drawback, that is performance.

I agree that we should have a link for other possible loaders, so you could choose for your specific case.

**Comment by novemberborn** [comment]
> This should probably be added to the documentation as the current boilerplate does not work at all

A PR would be welcome!

Personally I use https://github.com/avajs/typescript in my projects and compile TypeScript separately, which removes the dependency on various loaders and complications with the module systems.

**Comment by Sparticuz** [comment]
@novemberborn Does running ava on your compiled files affect coverage? I guess when I was compiling to cjs there were extra code paths that made it difficult to cover, but I'm not sure I've tried since switching to esm.

**Comment by novemberborn** [comment]
@Sparticuz https://github.com/bcoe/c8 does the trick.

**Comment by LangLangBart** [comment]
> `esbuild-node-loader` is deprecated: https://github.com/antfu/esbuild-node-loader I use `tsx`(https://github.com/esbuild-kit/tsx) instead and it works fine for me:
> 
> ```ts
> {
>   "extensions": {
>     "ts": "module"
>   },
>   "nodeArguments": [
>     "--loader=tsx",
>   ]
> }
> ```

The solution above worked for me up to [nodejs/node](https://github.com/nodejs/node) version **v19.9.0**. 

---

Starting with node **v20.0.0** (18/Apr/23) there are a lot of errors.

```sh
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"
```

The workaround was to tweak the **package.json** as follows and start **ava** with `npm run ava:run`.
- **Ref**: [TypeStrong/ts-node - #1997](https://github.com/TypeStrong/ts-node/issues/1997#issuecomment-1519023204), thanks to @wibed
```json
{
  "scripts": {
    "ava:run": "NODE_OPTIONS='--loader=tsx --no-warnings' ava"
  },
  "ava": {
    "extensions": {
      "ts": "module"
    }
  }
}
```

**Comment by punkpeye** [comment]
Note that in the above, setting `nodeArguments: ['--loader=tsx'],` does not work as a replacement for `NODE_OPTIONS`. You must start `ava` using `NODE_OPTIONS` just how @LangLangBart demonstrated.
