### ISSUE TITLE
Support for Vue 3

### ISSUE THREAD

**Issue by vinayakkulkarni** [avajs/ava#2595]
Please provide details about:

* What you're trying to do
- Enable Ava to work with Vue 3

* Why you can't use AVA for this
- Current way in the docs using [extension-hooks](https://github.com/avajs/ava/blob/master/docs/recipes/vue.md) breaks the Vue 3 tests

* And maybe how you think AVA could handle this
- Support for Vue 3 out-of-the-box without requiring extra extension hooks, maybe?

**Comment by novemberborn** [comment]
We'll happily take a PR to update the docs.

I don't quite know what's required, but we'd be happy to host a package that configures Vue correctly, too.

All that said this will need somebody to put in the work. I'd be happy to provide insight into how AVA works and how we can improve any integration.

For now though I'm going to close this issue. I don't think there's much use in keeping it open.
