### ISSUE TITLE
Unable to stub method with ava and sinon

### ISSUE THREAD

**Issue by sujeet-agrahari** [avajs/ava#2596]
I am trying to stub a method `doSendOtp` defined in `OtpService` but stubbing not working.

It works with mocha, but with ava I don't know why it isn't working.

I am doing it using `.serial` but it doesnt help either.

```
/* eslint-disable no-unused-expressions */
const test = require('ava');
const request = require('supertest');
const sinon = require('sinon');
const { expect } = require('chai');

const app = require('../src/app');
const OtpService = require('../src/components/auth/otp.service');

test.before(async (t) => {
  t.context.server = request(app);
  t.context.baseUrl = '/api/v1/auth';
});

test.after.always((t) => {
  delete require.cache[require.resolve('../src/app')]; // kills server
});

test.serial('Send OTP', async (t) => {
  const { server, baseUrl } = t.context;
  const sendOtpStub = sinon.stub(OtpService, 'doSendOtp');
  const response = await server.get(`${baseUrl}/send-otp?phone=8798787`)
    .expect(200);
  expect(sendOtpStub.calledOnce).to.be.true;
  expect(response).to.be.a('Object');
});
```

**Comment by novemberborn** [comment]
You haven't shared the actual test failure.

Without seeing your configuration, I'm going to guess that AVA thinks you didn't run assertions. This is because you're using `chai`.

Try [configuring AVA](https://github.com/avajs/ava/blob/master/docs/06-configuration.md) with `failWithoutAssertions` set to `false`.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by sujeet-agrahari** [comment]
@novemberborn This is error that I get.
```
 Send OTP

  tests\auth.test.js:25

   24:     .expect(200);
   25:   expect(sendOtpStub.calledOnce).to.be.true;
   26:   expect(response).to.be.a('Object');

  Rejected promise returned by test. Reason:

  AssertionError {
    actual: false,
    expected: true,
    message: 'expected false to be true',
    showDiff: true,
  }

  » tests/auth.test.js:25:39

  ─

  1 test failed
npm ERR! Test failed.  See above for more details.
```
Also, pelase confirm, is there built in assertion like `chai expect` in ava?

**Comment by novemberborn** [comment]
That'll be due to how your code works and whether you're stubbing it successfully. We can't help you with that here.

Yes AVA has [built-in assertions](https://github.com/avajs/ava/blob/master/docs/03-assertions.md).

**Comment by sujeet-agrahari** [comment]
> That'll be due to how your code works and whether you're stubbing it successfully. We can't help you with that here.
> 
> Yes AVA has [built-in assertions](https://github.com/avajs/ava/blob/master/docs/03-assertions.md).
Does it has the features as `chai` has? Can I replace `chai` with it?
How can I expect a value to be an object or an array.
I can do in `chai` like
```
expect(response).to.be.a('Object');
expect({a: 1}).to.have.own.property('a');
expect({a: 1}).to.have.property('b');
expect({a: 1}).to.not.have.own.property('b');
expect({a: 1}).to.own.include({a: 1});
expect({a: 1}).to.include({b: 2}).but.not.own.include({b: 2});
```

**Comment by novemberborn** [comment]
You'll have to rely more on JavaScript features, say `t.true(Array.isArray(thing))`. You can also do comparisons using `t.deepEqual()` and `t.like()`.

It's a different way of thinking about assertions compared to Chai.

**Comment by sujeet-agrahari** [comment]
@novemberborn All the issue is fixed now, I also removed `chai`, want my tests to be as quick as possible.
Here is my final test.
```
/* eslint-disable no-unused-expressions */
const test = require('ava');
const request = require('supertest');
const sinon = require('sinon');
require('dotenv').config();
// dependency to be stubbed
const OtpService = require('../src/components/auth/otp.service');
// stubs
const sendOtpStub = sinon.stub(OtpService, 'doSendOtp').resolves({});

const app = require('../src/app');

test.before(async (t) => {
  t.context.stubs = {
    sendOtpStub,
  };
  t.context.baseUrl = '/api/v1/auth';
  t.context.server = request(app);
});

test.after.always((t) => {
  delete require.cache[require.resolve('../src/app')]; // kills server
});

test.serial('Send OTP', async (t) => {
  const { server, baseUrl, stubs } = t.context;
  const res = await server.get(`${baseUrl}/send-otp?phone=8576863491`);
  t.is(res.status, 200);
  t.true(stubs.sendOtpStub.calledOnce);
  t.true(typeof res === 'object');
});
```
