### ISSUE TITLE
different output colors for report possible?

### ISSUE THREAD

**Issue by divramod** [avajs/ava#2597]
Hey, 

i really like ava. Thx for the awesome project!

Since i am using a light colorscheme and cannot really read the terminal output, i'd like to ask, if it is possible to change the output colors in the terminal?

![image](https://user-images.githubusercontent.com/1331662/95614405-ba17dc80-0a66-11eb-81ba-5799225c7b44.png)

**Comment by sindresorhus** [comment]
This is a problem for your terminal theme to fix. AVA is using standard named colors.

**Comment by novemberborn** [comment]
> i really like ava. Thx for the awesome project!

Thanks!

> This is a problem for your terminal theme to fix. AVA is using standard named colors.

Which is to say, terminal apps should be able to map the colors so they're appropriate for the theme. I haven't had to use this myself though, so I'm not sure how that works in practice. 

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
