### ISSUE TITLE
Implementing Mocks

### ISSUE THREAD

**Issue by marktyers** [avajs/ava#2599]
There are some situation where I need to be able to mock an interface to a nodejs Module, for example fs functions.

I can't find any documentation indicating how this is done in ava, is this functionality already available.

Perhaps is could be handled in a similar way to Jest where I could define a mock module in a mocks directory with the module name matching the module it is mocking?

Cheers guys.

**Comment by novemberborn** [comment]
There is no built-in mocking, sorry.

There's some great mocking libraries out there like https://github.com/testdouble/testdouble.js/ which I'd recommend you use.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by marktyers** [comment]
Cheers Mark
I was avoiding test double as it does not have a default export so can’t be imported as an ES6 module. If you know of any mocking library that supports this I would be very interested.

Cheers
Mark

**Comment by novemberborn** [comment]
Not really know — I try to avoid mocking, and I still compile everything down to CJS.

**Comment by marktyers** [comment]
No problem. last question (for now) can I run the tests in a single ava test suite?

**Comment by novemberborn** [comment]
There aren't suites as such, but you can pass the path to a single test file when you invoke AVA on the command line. Or a pattern that matches a subset of the files AVA would otherwise run by default.
