### ISSUE TITLE
Incredibly high CPU load during test running

### ISSUE THREAD

**Issue by bhallstein** [avajs/ava#2600]
Hi, I'm encountering some strange behaviour. I'm using an (I think) fairly standard ava + enzyme + babel setup.

I initially noticed my machine was running poorly — almost totally locked up — while ava tests were running. Investigating, I was astonished to find that CPU load was continuously _over 100_ during test running. The machine is so intensely locked up that Activity Monitor won't refresh any of its CPU or memory info until ava has finished running the tests. That 100 figure isn't a percentage, that's the actual CPU load figure, as a % it would be 10,000% CPU load. I thought I must be dreaming it, but it really is true.

My first thought was to try without concurrency (`-c 1`), and that results in CPU load around 1 (100%) as expected. Test running takes ~40s with `-c 1` and CPU load of about 1, compare with ~30s without `-c` and CPU load of about 100, system all but unusable.

Thinking about this, and 3 things seem possible explanations:

1. ava is getting the number of CPU cores available on the machine wrong, spawning too many threads/processes.
2. a 'thread bomb' situation, where lots of threads are spawned continuously.
3. inefficient inter-process communication is occurring. I wondered if poor multithreading support in one of the libraries, e.g. Enzyme, could have this effect? Or if there is a locking system for non-multithreaded shared libraries or some part of the test execution process that might be spin locking?

Or it could be something else. As I've never seen anything quite like this before, I'd really appreciate anyone's thoughts if they have further ideas.

Code: [link to repo](https://github.com/bhallstein/otter/tree/tdd-refactor)

- Tests are in [src/test](https://github.com/bhallstein/otter/tree/tdd-refactor/src/test)
- [package.json](https://github.com/bhallstein/otter/blob/tdd-refactor/package.json)
- `npm run t` is simply `ava src/test/*`

The machine is a MacBook Air, 1.3GHz, 2 real cores and SMT.

**Comment by bhallstein** [comment]
To try and get more info about what's going on, I just tried a few different levels of concurrency:

- without `-c`: 30s, CPU load ~= 100
- `-c 1`: 40s, CPU load ~= 1
- `-c 2`: 30s, CPU load ~= 50
- `-c 4`: 30s, CPU load ~= 100 (perhaps a little lower than with concurrency auto-set, it's a bit hard to tell)

This suggests first that ava might be spawning too many processes: equal to the number of logical rather than physical cores, although the workload does not spread well over SMT cores. However, even that seems unlikely to result in 100x load! Which I think also suggests that there is some kind of process scaling issue such as busy waiting during IPC or something? Does any of that seem likely?

ava is by far my favourite testing library and I'd love to carry on using & recommending it! For now I have disabled concurrency to make my machine usable again.

**Comment by novemberborn** [comment]
`@babel/register` might result in each worker process recompiling the code (because IIRC `@babel/register` compiles the first time a file is loaded in that process). That'll hit your CPU.

We use `node -pe 'os.cpus().length'` to determine concurrency. What is that on your node machine?

**Comment by bhallstein** [comment]
Thanks @novemberborn. `os.cpus().length` returns 4, which roughly gels with what's above. I wonder if using the physical number of cores would dramatically improve efficiency without losing much (any?) performance on machines with SMT. [Looks like that can be queried](https://gist.github.com/jakoboo/82be8c031bc09cf2e75dac9253645f2a) but it's not exactly pretty.

Thanks again I'll see if I can get some figures on `@babel/register`'s contribution to this.

**Comment by novemberborn** [comment]
> [Looks like that can be queried](https://gist.github.com/jakoboo/82be8c031bc09cf2e75dac9253645f2a) but it's not exactly pretty.

No, that looks pretty bad.

For I/O heavy tests, using all (hyper-threaded) cores can work well. But if the tests are extremely CPU heavy that might backfire. I suspect that's relatively rare though.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by XhmikosR** [comment]
I'm also hitting what I think is the same issue. Basically whatever value of concurrency bigger than 1 spawns too many processes making the system unresponsive...

I'm using a VM with 4 threads, but even if I use `-c=2` I'm getting tons of spawned processes.

**Comment by bhallstein** [comment]
That's very curious.

Re my original issue, I do often see CPU load of around 100; though I see this with a lot of node/npm related tasks, such as parcel builds, `npm install`, and so on, so I think it's unlikely it has much to do with ava.

**Comment by XhmikosR** [comment]
No, this is clearly due to ava. I only ran ava when I took the screenshot.
