### ISSUE TITLE
t.skipIf syntax

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#2602]
I've got a handful of tests I can't run in CI. Some I can only run in Windows, etc.

Proposed sytax:

```js
  test.skipIf(isCI).skipIf(!isWindows)('test title', t => {
  })
```

**Comment by novemberborn** [comment]
Hi @jamestalmage!

With https://github.com/avajs/ava/pull/2435 I started tinkering with a "forkable test interface". So you could do something like:

```js
const windowsOnly = test.make({ if: () => isWindows })
windowsOnly('test title', t => {})
```

Ultimately I think that's more versatile than adding lots of hooks to the regular test interface. What do you think?

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
