### ISSUE TITLE
`t.log` entries should start with `#`(without any spaces)

### ISSUE THREAD

**Issue by tymfear** [avajs/ava#2614]
Jenkins TAP reporter does not parse report correctly when `t.log` statements are present there.
E.g. tap report from ava
```
not ok 3 - test2.ts › Tomato block is not present 2
  * Log statement 1
  * Log statement 2
  * Log statement 3
  * Log statement 4
  * Log statement 5
  * Log statement 6
  ---
    name: AssertionError
    message: Tomato image still displayed
    assertion: 'true'
    values:
      'Value is not `true`:': 'false'
    at: |-
      e2e/spec/test2.ts:14:9
      initMacro (e2e/macros/initMacro.ts:55:3)
  ...
```

And the result of report is
<img width="1041" alt="Screenshot 2020-11-25 at 19 45 29" src="https://user-images.githubusercontent.com/6705391/100263965-d6100880-2f56-11eb-9f65-adfcd2195197.png">

So I created script the replaced `  *` with `#` and it parses it correctly
Script (just in case)
```bash
sed -i 's/  \*/  #/' report.tap
```
Report 
<img width="1299" alt="Screenshot 2020-11-25 at 19 49 02" src="https://user-images.githubusercontent.com/6705391/100264466-8bdb5700-2f57-11eb-8347-260bdfa8d3f5.png">
<img width="679" alt="Screenshot 2020-11-25 at 19 49 59" src="https://user-images.githubusercontent.com/6705391/100264483-8f6ede00-2f57-11eb-85f1-6db7982d0de2.png">

According to [specification](https://testanything.org/tap-version-13-specification.html) it should be diagnostic lines and start with `#`
```text
Diagnostics
Additional information may be put into the testing output on separate lines. 
Diagnostic lines should begin with a #, which the harness must ignore, at least as far as analyzing the test results.
```
```
Anything else
Any output that is not a version, a plan, a test line, a YAML block, 
a diagnostic or a bail out is incorrect. How a harness handles the incorrect line is undefined. 
Test::Harness silently ignores incorrect lines...
```

So, of course, there is a problem with Jenkins plugin, but that's another story. Ava should just stick to specification and stream diagnostic info lines starting with `#`.

**Comment by novemberborn** [comment]
Thanks @tymfear. PR welcome 😜

**Comment by tymfear** [comment]
@novemberborn could you give a hint where to search for it? I failed to find the place where log messages are preprocessed before printing. Would love to make a PR.

**Comment by novemberborn** [comment]
Good question… I think either of these three places?

https://github.com/avajs/ava/blob/09c5568d4268e6e4a382bbb3a956a52c44a5bf94/lib/reporters/tap.js#L103
https://github.com/avajs/ava/blob/09c5568d4268e6e4a382bbb3a956a52c44a5bf94/lib/reporters/tap.js#L115
https://github.com/avajs/ava/blob/09c5568d4268e6e4a382bbb3a956a52c44a5bf94/lib/reporters/tap.js#L126-L129

**Comment by tymfear** [comment]
@novemberborn looks like the problem is in `supertap` https://github.com/vadimdemedes/supertap/blob/master/index.js#L40

**Comment by tymfear** [comment]
@novemberborn any thoughts here?

**Comment by novemberborn** [comment]
@tymfear I didn't notice your edits, sorry.

We could fork it… but I don't really want to maintain it. It'd be the path of least resistance. How about you set that up and then we can transfer it into this org when done?

(We could inline it as well but that gets icky with licenses and whatnot.)

**Comment by tymfear** [comment]
@novemberborn I'll try it out!

**Comment by tymfear** [comment]
@novemberborn ping

**Comment by novemberborn** [comment]
@tymfear I typically don't have time for code reviews during the week, but try to get to them over the weekend.

**Comment by tymfear** [comment]
@novemberborn got it. Just pinged in case you missed it
