### ISSUE TITLE
typescript assertion functions

### ISSUE THREAD

**Issue by f5lee** [avajs/ava#2622]
Typescript since 3.7 has a way to declare that a function is an assertion function, which lets it make inferences about null/undefined values.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

Is this something ava should support? I can make a PR for it. (It would be conditional on typescript version)

**Comment by sindresorhus** [comment]
Relevant issue: https://github.com/avajs/ava/issues/2449

**Comment by novemberborn** [comment]
I don't believe this works with our assertions, being members of our `t` object.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
