### ISSUE TITLE
document that ava assertions don't throw

### ISSUE THREAD

**Issue by ghost** [avajs/ava#2624]
I didn't realize until recently that ava assertions don't stop the test when they fail.

I think this could be documented better, and I'm willing to do so if that's useful

**Comment by novemberborn** [comment]
I thought it was referenced, but I can't immediately spot it in the obvious places. This hints at it:

> If multiple assertion failures are encountered within a single test, AVA will only display the first one.

That might be the best spot to add a clarification?

**Comment by f5lee** [comment]
I'd scatter reinforcement of the idea at several places, since reference documents are often not read linearly, and "assert doesn't throw" is pretty unusual; in almost every other programming context, assert does throw.

I can make a PR in a day or so.

**Comment by novemberborn** [comment]
@f5lee fantastic, thank you.

**Comment by gavinpc-mindgrub** [comment]
For reference, see also https://github.com/avajs/ava/issues/1485

**Comment by novemberborn** [comment]
Fixed by https://github.com/avajs/ava/pull/3246.
