### ISSUE TITLE
Delay restart on watching

### ISSUE THREAD

**Issue by MrZyr0** [avajs/ava#2625]
## Please provide details about:

* **What you're trying to do :** I want to delay reloading ava when using `--watch`.
* **Why you can't use AVA for this:** I didn't see option, parameters are any infomation in the documentation & issue to do this.
* **And maybe how you think AVA could handle this:** Add a new parameter in `ava.config.js` like `watchingReloadingDelay` that accepts a human readable time like `500ms` to add a timeout on the reload action.

## Description of the problem
I use nodemon to restart my API every time I modify one of my files (except test files). Sometimes ava reloads at the same time as nodemon and all my tests that make a request to the API fail because of a terminated connection:
```js
Rejected promise returned by test. Reason:

  Error {
    address: '127.0.0.1',
    code: 'ECONNREFUSED',
    errno: -4078,
    port: 4000,
    syscall: 'connect',
    message: 'connect ECONNREFUSED 127.0.0.1:4000',
  }
```

**Comment by novemberborn** [comment]
> I use nodemon to restart my API every time I modify one of my files (except test files). Sometimes ava reloads at the same time as nodemon and all my tests that make a request to the API fail because of a terminated connection:

Delaying AVA is not the answer for this. It may still run too early.

Ideally AVA starts the API for you. I do this in test files, even launching child processes. So yes that's a new API process for each test file.

[Shared workers](https://github.com/avajs/ava/issues/2605) could provide a foundation for this as well.

However, for your current setup, the simplest approach might be a before hook:

```js
test.before(async () => {
  let connected = false
  while (!connected) {
    connected = await tryConnection()
  }
})
```

This stops tests from running until the connection can be established.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
