### ISSUE TITLE
t.like not handling arrays as expected

### ISSUE THREAD

**Issue by awlayton** [avajs/ava#2627]
I am trying to use the `t.like` assertion on deep objects with arrays of objects in them.

The following simplified example fails:
```ts
import test from 'ava';

test('deep t.like', (t) => {
  t.like({ a: [{ a: 1, b: 2 }] }, { a: [{ a: 1 }] });
});
```
```
> tsc -b

$ ava dist/ava.spec.js

  deep t.like

  Difference:

    {
      a: [
        {
          a: 1,
  -       b: 2,
        },
      ],
    }

  › src/ava.spec.ts:4:5

  ─

  1 test failed
error Command failed with exit code 1.
```

I expected the above assertion to pass. 
It seems that elements within arrays need to be deep equal rather than "like" for the assertion to pass.

AVA version:
```
$ ava --version
3.14.0
```

**Comment by ninevra** [comment]
(Not a maintainer, but)

This is behaving as documented: ["Any values in `selector` that are not **regular objects** should be deeply equal to the corresponding values in value."](https://github.com/avajs/ava/blob/master/docs/03-assertions.md#likevalue-selector-message) What a "regular object" is in javascript is admittedly not well defined, but arrays aren't it.

It would sometimes be useful for `t.like()` to recurse into arrays, but then there would be lots of design questions to answer: Should order matter? Should extra trailing elements in the sample matter? Should `Map`s and `Set`s also be recursed into? Adding such special-cases to `t.like()` would make it much less clear what any given assertion is actually checking.

One can achieve the expected behavior either by writing one's own selector function and then using `t.deepEqual()`, or by using an outside assertion library.

**Comment by awlayton** [comment]
I had interpreted it as anything that was JSON serializable. But I could see them meaning it more literally.

What do you mean about `t.deepEqual`? Is there some undocumented way to use it? It just takes 2 values to compare and an optional message.

**Comment by ninevra** [comment]
Internally, what `t.like(actual, selector)` is doing is constructing a subset of `actual` and then comparing it by deep equality to `selector`; i.e. there exists some function `select(actual, selector) -> sample` such that `t.like(actual, selector)` is equivalent to `t.deepEqual(select(actual, selector), selector)` A very simplified version might look like:
```javascript
function select(actual, selector) {
  if (isPlainObject(selector) {
    const selected = {};
    for (const [key, value] of Object.entries(selector) {
      selected[key] = select(actual[key], value);
    }
    return selected;
  } else {
     return actual;
  }
}

t.deepEqual(select(actual, selector), selector);
```
(The actual selector function used by AVA is in https://github.com/avajs/ava/blob/b71f396df7b9d74ef24262b6840df1593cad3798/lib/like-selector.js)

https://github.com/avajs/ava/blob/5d3b2006111a91253e0f7474ae278e41c1240820/lib/like-selector.js#L14


So if you want to recurse into arrays, you could write a selector function something like:
```javascript
function selectWithArrays(actual, selector) {
  if (isPlainObject(selector)) {
    // ...
  } else if (Array.isArray(selector) && Array.isArray(actual)) {
    const selected = [];
    for (const [index, value] of selector.entries {
      selected[index] = selectWithArrays(actual[index], value);
    }
    return selected;
  } else {
    return actual;
  }
}
```
and then use `t.deepEqual(selectWithArrays(actual, selector), selector);`

**Comment by novemberborn** [comment]
@ninevra is correct.

`like` uses `deepEqual` under the hood, which, like `snapshot` uses https://github.com/concordancejs/concordance to determine equality.

Ultimately a "partial equal" feature could be added there, allowing us to be smarter with say (primitive-value) sets and maps, but even then deciding how two arrays or complex-value sets are partially equal becomes difficult.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by awlayton** [comment]
I was expecting it to just treat an array the way it treats and object. That is, element `i` of the array (key `i` of it as an object) must be "like" element `i` of the corresponding selector array.

Not saying that is the only interpretation for arrays, but it is one way.

**Comment by novemberborn** [comment]
Yea, I appreciate that. I'm not quite sure how we'd build that *on top of* Concordance though, especially with nested arrays.

**Comment by awlayton** [comment]
I have no experience with concordance, but could you not simply transform any arrays to their "equivalent" object before doing the comparison with the selector?

**Comment by novemberborn** [comment]
You'd have to walk the object tree to find all those arrays. It's fine for simple cases but much harder for all cases.

**Comment by awlayton** [comment]
Not sure I see cases where it is hard, unless you are worried about it becoming slow for giant objects? You just need to recurse down the thing.

**Comment by novemberborn** [comment]
Recursing is the problem. For example it has to work for sets and maps (keys included).

**Comment by fungiboletus** [comment]
I'm migrating tests from Jest to Ava and we use [`.toMatchObject`](https://jestjs.io/docs/expect#tomatchobjectobject) that has an acceptable behaviour, it's like `like` in Ava, but it manages arrays. The order simply needs to be the same.

**Comment by Gozala** [comment]
I have run into the same problem, and also find handling of arrays surprising. I have identified problem to be caused by

https://github.com/avajs/ava/blob/f5caa8fb823e369517053181494374c64dfa58b2/lib/like-selector.js#L4

Which I was able to address locally with small changes
https://github.com/avajs/ava/pull/3023

**Comment by Greegko** [comment]
FYI, I [applied](https://github.com/Greegko/battleground/blob/master/packages/core/ava-fix-array-like-selector.js) @Gozala changes and patching the lib with it, so far it works for me without any issue.

**Comment by novemberborn** [comment]
@Greegko would you like to pick up https://github.com/avajs/ava/pull/3023 and turn it into a fresh PR?

**Comment by Greegko** [comment]
@novemberborn yeah I will try to create tests around it 👍
