### ISSUE TITLE
Make it easier to find failed tests in the default reporter

### ISSUE THREAD

**Issue by stavalfi** [avajs/ava#2641]
### Background

I'm migrating a Jest project to Ava and I find it hard to search the failed tests in Ava reporter.

With jest, you can search in the terminal "fail " (with a space at the end) and you will find all the failed tests files which failed. (it won't help you to find the actual tests which failed).

With Ava, I need to search for: "✖" symbol to find the actual tests which failed (but it won't help you to find the failed test files).

-----------

### Problem

In a project with 20+- tests it can be ok. but in my project I have 150+ tests and each one has a lot of logging (with `t.log`). so the test output is too long to find what I'm looking for.

----------

### Feature Request

At the end of the in the default reporter, list the following:

1. a list of all failed test files.
2. for each failed test-file, list all the failed tests titles.
3. 
---------

### Possible workaround

working ___locally___ with custom tap reporters is annoying because I need to pipe every command with them every time.

----

What to you think?

**Comment by novemberborn** [comment]
Sure. Would you mind adding this to https://github.com/avajs/ava/issues/2500?

**Comment by stavalfi** [comment]
Thanks @novemberborn.

from my understanding, this request won't be done in the next months. is there any workaround I can do to make it happen? different Ava reporter maybe?

It's unproductive to not knowing which tests are failing and which files are failing immediately.

thanks again for taking the time to answer me.

**Comment by novemberborn** [comment]
Nah, all we have is TAP and our default reporter, sorry.

**Comment by novemberborn** [comment]
@tymfear I think our energy is better spent elsewhere.

**Comment by tymfear** [comment]
...Just checked State of JS 2020 and I'm sad seeing people leave AVA or don't like it. I'm sure they just don't understand all the power of AVA and super used to Mocha/Jasmine/Jest (the same I see in my org with some people). But some people want good reporting, and what currently AVA provides is not that good and that makes people leave as well. And I really believe that improving reporting will make more people chose AVA, as otherwise it is hard to build good integration or E2E harness around it.

**Comment by stavalfi** [comment]
> ...Just checked State of JS 2020 and I'm sad seeing people leave AVA or don't like it. I'm sure they just don't understand all the power of AVA and super used to Mocha/Jasmine/Jest (the same I see in my org with some people). But some people want good reporting, and what currently AVA provides is not that good and that makes people leave as well. And I really believe that improving reporting will make more people chose AVA, as otherwise it is hard to build good integration or E2E harness around it.

 I agree, I can't suggest my Org to use Ava as well yet. Until there is a better reporting.

**Comment by tymfear** [comment]
I do use AVA in my organisation,  and advertise it,  and show all the benefits, but every time someone new sees AVA they are confused by macros and TAP reports, so that needs clarifications. But because of that I assume the same reactions across JS community

**Comment by novemberborn** [comment]
Would be great to have a [Discussion](https://github.com/avajs/ava/discussions) about this!

**Comment by tymfear** [comment]
I'm not sure what do you mean by `this`. But I'll create discussion about hooks.

**Comment by novemberborn** [comment]
About the points you're raising. Just suggesting we move it out of an issue thread and into the Discussion space 😄

**Comment by tymfear** [comment]
Done
