### ISSUE TITLE
Signed and unsigned zero values fail t.is comparison

### ISSUE THREAD

**Issue by maximilliangeorge** [avajs/ava#2643]
This is quite a simple issue to reproduce. I'm presuming this is a bug.

```
const test = require('ava')

test('Failing test', t => {
	t.is(-0, 0) // ??
})

test('Passing test', t => {
	t.true(-0 === 0)
})
```

Ava is invoked using `ava --watch`. Version 3.15.0.

**Comment by novemberborn** [comment]
This is by design, they're different values.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is.

**Comment by Basssiiie** [comment]
@novemberborn out of curiosity, may I ask why this design was chosen? Why would someone want to test for either negative or positive zero? Thank you for your time.

**Comment by novemberborn** [comment]
@Basssiiie IIRC, it's because we rely on `Object.is` (see above). And that differentiates. The values *are* technically different and we didn't want to make an exception if the language doesn't.
