### ISSUE TITLE
Question: Is it possible to use `.mjs` on Node.js 10?

### ISSUE THREAD

**Issue by fisker** [avajs/ava#2646]
I'm trying to covert test files to `.mjs`, but I still need run test on `Node.js` 10.
I can't find a way to run tests with `babel: true`.

**Comment by novemberborn** [comment]
`.mjs` is only really supported in Node.js 12 — I don't know how those extensions behave in 10.

Babel transpilation should work but you haven't shared your setup or errors so I can't really tell.

Let's continue this in a [Discussion](https://github.com/avajs/ava/discussions).

**Comment by fisker** [comment]
It seems I can't config `.mjs` file as `commonjs`, and https://github.com/avajs/ava/blob/32c5425353cc58422f0a196bb0c06a4095a33825/lib/worker/subprocess.js#L190 This line always try to use `import`. And https://github.com/avajs/babel/blob/5e7279b695760e8451a8c7ce664ad4eba5f1c421/index.js#L372 this line refuse to load it too.

I think the real problem is how to config `.mjs` file as a `commonjs` module.

If it helps, I can setup a reproduce repo.

**Comment by novemberborn** [comment]
Ah you're right, I remember now. We always treat `.mjs` as ESM. So no, you can't do this.

**Comment by fisker** [comment]
Too bad, I even try to modify some code, still can't make it work.

**Comment by fisker** [comment]
I feel this will be need when we target Node.js 12, people will switch tests to `.mjs` and to support old version of Node.js, we still want run with `babel`.

**Comment by fisker** [comment]
I also tryied rename `.mjs` to `.js` when old Node.js version detected, but one problem, snapshot won't match because filename changed.

**Comment by fisker** [comment]
Here is the change I want. https://github.com/fisker/eslint-plugin-unicorn/pull/227,  I guess have to wait untill we drop Node.js 10, what do you think @sindresorhus

**Comment by novemberborn** [comment]
Node.js 10 is end of life in April, so I don't think this will be an issue for much longer.

**Comment by sindresorhus** [comment]
@fisker Would be easiest to just wait a few months for us to be able to drop Node.js 10. Alternatively, you could drop Node.js 10 for the tests for now.
