### ISSUE TITLE
Share context across files or provide option to run folders in serial mode

### ISSUE THREAD

**Issue by jakobrosenberg** [avajs/ava#2650]
Not sure if this is a feature or documentation request.

**What you're trying to do**

Run production tests after development tests have run
- start server in `development mode`
- run all dev tests in parallel
- close server
- start server in `production mode`
- run production tests in parallel
- close server

**Why you can't use AVA for this**
AVA runs test files in parallel

**And maybe how you think AVA could handle this**
- an option to run folders in serial mode (but not their files)
- an option to share context across files (this could allow the developer to control the flow):
```javascript
let sub
test.before( async t => {
  // in this scenario my custom subscribe function would return
  // a promise which gets resolved when the server is ready
  sub = await t.context.subscribe('devServer')
})
...
test.after( async t => {
  // calling sub will unsubscribe. Once all tests have unsubscribed,
  //  my server will be started in production mode
  sub()
})
```

**Comment by novemberborn** [comment]
I think the better approach is to run AVA twice, but with different files. You can provide glob patterns on the CLI.

Let's discuss further in [Discussions](https://github.com/avajs/ava/discussions).
