### ISSUE TITLE
vue and typescript

### ISSUE THREAD

**Issue by Suyashtnt** [avajs/ava#2654]
Im trying to get vue with typescript support working in ava 2(I cant use ava 3 for config file reasons) and typescript does not seem to work.

log: 
```
➜ yarn test:unit             
yarn run v1.22.10
$ cross-env NODE_ENV=test TEST_TYPE=unit ava

⠇ nuxt-config › should merge users extend function with base

⠏ nuxt-config › should merge users extend function with base

  2 passedYou are running Vue in development mode.

  ✖ No tests found in test/unit/specs/basic.spec.js

  2 tests passed
  1 uncaught exception

  Uncaught exception in test/unit/specs/basic.spec.js

  /home/home/glowsquid-next/node_modules/require-extension-hooks/src/hook.js:117

  Error: Unknown file extension .ts

  oneTimeHook (node_modules/require-extension-hooks/src/hook.js:117:11)
  retrieveAndTranspileContent (node_modules/require-extension-hooks-vue/src/index.js:56:14)
  getScriptPart (node_modules/require-extension-hooks-vue/src/index.js:73:10)
  Array.module.exports (node_modules/require-extension-hooks-vue/src/index.js:214:22)
  transpile (node_modules/require-extension-hooks/src/hook.js:42:26)
  hook (node_modules/require-extension-hooks/src/hook.js:26:22)
  Object.<anonymous> (test/unit/specs/basic.spec.js:3:1)
  compile (node_modules/require-extension-hooks/src/hook.js:75:10)
  hook (node_modules/require-extension-hooks/src/hook.js:32:3)
```

repo is: https://github.com/glowsquid-launcher/glowsquid-next (im using a template which has unit tests built in but not working)

**Comment by novemberborn** [comment]
Sorry we can't help you with AVA 2 issues.

**Comment by rgeraldporter** [comment]
I had this issue as well in Ava 4. But was able to resolve it by making a minor adjustment to the default Vue example:

```
// Setup vue and js files to be processed by `require-extension-hooks-babel`
hooks(['vue', 'ts', 'js']).exclude(({filename}) => filename.match(/\/node_modules\//)).plugin('babel').push();
```

Note that `ts` was added to the hooks. You'll need this if you're using `lang="ts"` in your Vue component. The error is rather misleading, there is no file extension with `.ts` but the portion of the Vue file with TS is being turned into a `.ts` file under the hood.

**Comment by novemberborn** [comment]
@rgeraldporter is that something that can be added to the recipe?

**Comment by binhonglee** [comment]
I just wanted to add to @rgeraldporter's comment. I wrote about specifically using Ava with Vue 2 + TypeScript (through babel) [here](https://binhong.me/blog/2021-05-22-ava-with-vue-typescript-and-nyc/). Happy to help if there's any additional question. I'm trying to figure out how to make them work with vue 3 though.
