### ISSUE TITLE
Remove `id` support in `t.snapshot()`

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2669]
A presumably little known feature of the `t.snapshot()` assertion is that you can provide an ID for the snapshot. I doubt it's much used and it doesn't really fit with the mental model of of snapshots belonging to tests.

Let's remove it for AVA 4.

**Comment by ninevra** [comment]
I'd like to take a stab at implementing this, if that's alright? It'll simplify working on https://github.com/avajs/ava/discussions/2652.

**Comment by novemberborn** [comment]
Yea that'd be great @ninevra.

I'd like to raise an assertion failure when the option is passed, to aid people migrating from older AVA versions.

Note that we can make this change without requiring opt-in since we're now building towards AVA 4.
