### ISSUE TITLE
globalThis not defined

### ISSUE THREAD

**Issue by maikelmclauflin** [avajs/ava#2691]
Please provide details about:

* What you're trying to do
* What happened
* What you expected to happen

On node v11.15, I am trying to run basic tests after adding a package, but I got the subsequent error. I expected the tests to at least start to run but I was not even able to add a require to add the shim. I was able to update standard and get rid of the problem, as their [changelog](https://github.com/standard/standard/blob/master/CHANGELOG.md#new-features-1) has noted, but I have not been able to do so as easily with ava. I even tried adding ava/babel.
```
/Users/michaelmclaughlin/Documents/brave-intl/bat-ledger/node_modules/queue-microtask/index.js:5
  ? queueMicrotask.bind(globalThis)
                        ^
```
I am stuck on these versions and with a lot of these packages unfortunately. So I am hoping there is a workaround with ava.

Please share relevant sample code. Or better yet, provide a link to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
[code is open source](https://github.com/brave-intl/bat-ledger/tree/add-swagger) but i can try to make a minimal reproducible example

We'll also need your AVA configuration (in `package.json` or `ava.config.*` configuration files) and how you're invoking AVA. Share the installed AVA version (get it by running `npx ava --version`).
I tried adding require to add the [globalThis shim](https://github.com/es-shims/globalThis) first but to no avail

**Comment by novemberborn** [comment]
I don't see how this is related to AVA. We really try to not modify the environment.

Beyond that, Node.js 11 is not supported. I feel for you being stuck with those versions, but we're not in a position to help, sorry.
