### ISSUE TITLE
no-ignored-test-files hangs with ava@4.0.0-alpha.1

### ISSUE THREAD

**Issue by ninevra** [avajs/ava#2730]
With `ava@4.0.0-alpha.1` installed, running the `no-ignored-test-files` rule on any AVA test file causes `eslint` to hang indefinitely.

With `ava@3.x`, or with `"no-ignored-test-files": "off"`, everything's fine.

[Minimal reproducible example.](https://github.com/ninevra/ava-next-eslint-hangs-mre)

**Comment by novemberborn** [comment]
@ninevra this is now out as Alpha 2.
