### ISSUE TITLE
CLI sometime do nothing

### ISSUE THREAD

**Issue by fisker** [avajs/ava#2735]
Sometime I run `npx ava foo.js`, the CLI don't do anything, just pass

```console
>npx ava test/prefer-switch.mjs -u


>npx ava test/prefer-switch.mjs -u


>npx ava test/prefer-switch.mjs -u

/ Invalid #11
         1 | if (foo === 1) {}
         2 | else if (foo === 2) {}
         3 | else if (foo === 3) {}
         4 | else if (foo === 4) {}
         5 | else if (foo === 5) {}
         6 | else if (foo === 6) {}
         7 | else if (foo === 7) {}
         8 | else if (foo === 8) {}
         9 | else if (foo === 9) {}
        10 | else if (foo === 10) {}
        11 | else if (foo === 11) {}
        12 | else if (foo === 12) {}
        13 | else if (foo === 13) {}
        14 | else if (foo === 14) {}
        15 | else if (foo === 15) {}
        16 | else if (foo === 16) {}
        17 | else if (foo === 17) {}
        18 | else if (foo === 18) {}
        19 | else if (foo === 19) {}
        20 | else if (foo === 20) {}
        21 | else if (foo === 21) {}
        22 | else if (foo === 22) {}
        23 | else if (foo === 23) {}
  38 tests passed
```

Project: https://github.com/sindresorhus/eslint-plugin-unicorn

This happens a lot, I'm not sure how to reproduce, my system is windows 10. Node.js version seems doesn't mater.

**Comment by sindresorhus** [comment]
Are you sure it's a problem with AVA and not `npx`?

What AVA version?

**Comment by fisker** [comment]
Problem is I'm not sure what cause it... And sorry I didn't mention that it's not really doing nothing, it stuck for a while. Current version is `3.15.0`, but it happened before.

**Comment by fisker** [comment]
It also print timeout sometime


```console
>npx ava --verbose


  × Timed out while running tests


  × Timed out while running tests


  × Timed out while running tests


  × Exiting due to SIGINT (Pressed CTRL+C)

  ─
```

**Comment by fisker** [comment]
Another problem is it also ONLY run part of tests sometime, and I don't know what skipped. This really bothers me.

**Comment by novemberborn** [comment]
The multi-line output trips up the mini reporter a bit for me, to the point where I could see how the output may give the impression that nothing happened.

Timeouts and disappearance hint at the machine being stressed too much and IPC messages dropping. Reducing concurrency might help.

AVA 4 defaults to using worker threads, not child processes, which may also help.
