### ISSUE TITLE
Unnecessary error in extractSource due to not checking for null

### ISSUE THREAD

**Issue by erights** [avajs/ava#2744]
The line at
https://github.com/avajs/ava/blob/e9a69dca44dadb545d4698fb7df5587da2787f7d/lib/serialize-error.js#L31
should be changed to
```js
if (callsite && callSite.file === normalizedFile) {
```
since the previous line
```js
const callSite = stackUtils.parseLine(line);
```
may, and sometimes does, initialize `callSite` to `null`. Once this is fixed, if the catch at
https://github.com/avajs/ava/blob/e9a69dca44dadb545d4698fb7df5587da2787f7d/lib/serialize-error.js#L39
was there only because of this one error, then this do-nothing catch should be removed.

**Comment by novemberborn** [comment]
Thanks, that makes sense. I'll try and get this into the next release if nobody else beats me to it.

Looking at the commit history, the earlier logic checked for a falsy value so I assume the `catch` isn't needed with this guard.

**Comment by Fem-Fem** [comment]
Hi! Would it be possible for me to work on this?

**Comment by novemberborn** [comment]
@Fem-Fem that'd be great!

**Comment by Fem-Fem** [comment]
Thanks! I have a PR here: https://github.com/avajs/ava/pull/2750
