### ISSUE TITLE
Ava needs to upgrade read-pkg to 6.x due to npm-audit advisory

### ISSUE THREAD

**Issue by kylechadha** [avajs/ava#2749]
```
├─┬ ava@3.15.0
│ └─┬ read-pkg@5.2.0
│   └─┬ normalize-package-data@2.5.0
│     └── hosted-git-info@2.8.9 
```
Ava 3.15.0 is locked to `read-pkg` ^5.20, which contains the subdependency `hosted-git-info`. This library has an npm advisory (https://www.npmjs.com/advisories/1677) and needs to be upgraded >= 3.0.8.

This can be resolved by using `read-pkg` 6.x.

**Comment by novemberborn** [comment]
`read-pkg@6` is incompatible with AVA 3. You'll have to ask for a patch release [there](https://github.com/sindresorhus/read-pkg/tree/bfe8eb8232af1f1a32143387f909c5140a86e96d).

Looking at the advisory, AVA reads the `package.json` in the project being tested, and it's unlikely that would contain a URL that then leads to a denial of service in an AVA test run. If your policy allows you could ignore this advisory as it pertains to AVA.

I'll see if we can upgrade the dependency for AVA 4.

**Comment by kylechadha** [comment]
Got it, thanks @novemberborn, that makes sense. Will close this ticket.
