### ISSUE TITLE
SqliteError {} does not show message

### ISSUE THREAD

**Issue by andykais** [avajs/ava#2755]
Please provide details about:

* What you're trying to do: run a test and view stack traces when things go wrong
* What happened: I received an unexpected error, but the error message was not shown.
* What you expected to happen: I expected to see the error message, which happens when most errors are thrown.

repro:
install the npm package `better-sqlite3`
run `npx ava test.js` with zero ava configuration
```js
const test = require('ava')
const Sqlite3 = require('better-sqlite3')

test('sample', t => {
  const db = new Sqlite3('test.db')
  // this line will throw an exception
  db.prepare('invalid-syntax')

  t.pass()
})
```
this is the output:
```
 ✘ andrew  forager  npx ava test.js

  sample

  test.js:7

   6:   const db = new Sqlite3('test.db')
   7:   db.prepare('invalid-syntax')     
   8:                                    

  Error thrown in test:

  SqliteError {}

  › Database.prepare (node_modules/.pnpm/better-sqlite3@7.4.0/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
  › test.js:7:6

  ─

  1 test failed
```

contrast that with the following code sample:
```js
const test = require('ava')

class CustomError extends Error {}

test('sample', t => {
  throw new CustomError('test message')
  t.pass()
})
```
we correctly see the error message:
```
  Error thrown in test:

  Error (CustomError) {
    message: 'test message',
  }

  › test.js:6:9
```

this is odd because if I catch the SqliteError, I can call `error.message` and see that there is a string there. I am unsure why it is not being displayed by ava.

ava version: `3.15.0`

**Comment by andykais** [comment]
I think I found the reason: https://github.com/JoshuaWise/better-sqlite3/blob/03f382a3ba1977feeb57ff1349c628b846d8b8b3/lib/sqlite-error.js#L2 (`enumerable: false`)

Is there a chance we can always look for a `.message` even on errors that are not enumerable?

**Comment by novemberborn** [comment]
I agreed it'd be useful to print the message. I'm not immediately sure why it isn't being printed.

**Comment by andykais** [comment]
@novemberborn its not printing the message because it assigns makes the `message` property not enumerable for some reason https://github.com/JoshuaWise/better-sqlite3/blob/03f382a3ba1977feeb57ff1349c628b846d8b8b3/lib/sqlite-error.js#L13. A property that is not enumerable is one that you dont see doing something like `Object.keys(sqliteError)`

**Comment by novemberborn** [comment]
@andykais gotcha. This isn't readily fixable in AVA, I've added https://github.com/concordancejs/concordance/issues/77 on the dependency that formats the errors.
