### ISSUE TITLE
test runner applied a wired result

### ISSUE THREAD

**Issue by wfk007** [avajs/ava#2770]
Please provide details about:

* What you're trying to do：i'm trying to test a bool result
* What happened：the test runner shows me the result is `false`
* What you expected to happen：the result is `true` as it shows in `console.log`

Please share relevant sample code. Or better yet, provide a link to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

```ts
import test from 'ava';

const textRegex = /I18N((\['(\w+)'\])|(\["(\w+)"\])|(\.(\w+)))/g;

console.log("wired result:",textRegex.test('I18N["qwe312652"]'));

test('test regex single', (t) => {
    t.plan(3);
    t.true(textRegex.test('I18N["qwe312652"]'), 'double quotes');
    t.true(textRegex.test("I18N['qwe312652']"), 'apostrophe');
    t.true(textRegex.test('I18N.qwe312652'), 'dot ref');
});
```

We'll also need your AVA configuration (in `package.json` or `ava.config.*` configuration files) and how you're invoking AVA. Share the installed AVA version (get it by running `npx ava --version`).

in package.json，invoked with `npm run test`，ava version is `3.15.0`
```json
{
  "ava": {
        "extensions": [
            "ts"
        ],
        "require": [
            "ts-node/register"
        ]
    },
   "scripts": {
        "test": "ava"
    },
  "devDependencies": {
        "ava": "^3.15.0",
        "ts-node": "^10.0.0",
        "typescript": "^4.2.2",
    },
}
```

![image](https://user-images.githubusercontent.com/22289445/122337382-dc0c1c00-cf70-11eb-8a17-d9b049bd284c.png)

**Comment by sindresorhus** [comment]
A regex with the `g` flag is mutable and can return different result for each call.

https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results

**Comment by wfk007** [comment]
> A regex with the `g` flag is mutable and can return different result for each call.
> 
> https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results
> 
> You need to reset the `.lastIndex` property after each call or not reuse the regex.

thx very much！！！
