### ISSUE TITLE
Ava test output adds 's' to filenames

### ISSUE THREAD

**Issue by Basssiiie** [avajs/ava#2793]
(Minor issue)

Hello,

When I have, for example, two test files called `math.tests.ts` and `array.tests.ts`, AVA renames them to `maths.ts` and `arrays.ts` in the terminal output.

Image:
![image](https://user-images.githubusercontent.com/20048660/126879114-613603a1-ebf1-487a-8727-8b850c75e47d.png)

I'm guessing it tries to remove the word `test` along with the 2 dots, but fails to remove the `s` after `test` as well.

AVA version: `3.15.0`
Config in `package.json`:
```js
{
	"ava": {
		"extensions": [
			"ts"
		],
		"files": [
			"tests/**/*.tests.ts"
		],
		"require": [
			"./tests/_setup.js",
			"ts-node/register"
		],
		"verbose": true
	}
}
```
Thank you for your time and if you need any more info, please let me know.

**Comment by novemberborn** [comment]
I think I made some changes that are in `main`, but I'll have a look.

**Comment by novemberborn** [comment]
You're right it was removing `.test`. Correct behavior would have been to leave `.tests`. The supported filename pattern is `suite.test.js`.
