### ISSUE TITLE
Add a SECURITY.md file

### ISSUE THREAD

**Issue by JamieSlome** [avajs/ava#2831]
If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

**Comment by novemberborn** [comment]
You can contact me directly.

**Comment by novemberborn** [comment]
Done per https://github.com/avajs/ava/security/policy.
