### ISSUE TITLE
Source maps on Windows with Node.js 14.8.1 and ts-node/esm loader return sources that are not file URLs, which causes a crash in the snapshot manager

### ISSUE THREAD

**Issue by antonyfaris** [avajs/ava#2889]
I made [this minimal example](https://github.com/antonyfaris/sample-ava-ts).

You can see in [this gh workflow](https://github.com/antonyfaris/sample-ava-ts/runs/4119306273?check_suite_focus=true) how it only fails on windows. This error prevents tests from running.

It works fine with version 4.0.0-alpha.2

**Comment by novemberborn** [comment]
It's blowing up on this line: https://github.com/avajs/ava/blob/5cdeb9d44c709deb979a6e49e26e7e5e0ab1a3fa/lib/snapshot-manager.js#L401

>  TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file

So the source isn't a file URL. I'm confused though why this only happens on Windows. Looks like this is Node.js 14.8.1, have you tried with 16?

I also noticed you're using the experimental `ts-node/esm` loader. Perhaps that's not interfacing with the source map support correctly?

**Comment by novemberborn** [comment]
FWIW the format of the source paths is undefined, but so far I have only encountered file URL values. Which means either it can legitimately be a mix, or perhaps it's an issue in `ts-node/esm`.

**Comment by antonyfaris** [comment]
> So the source isn't a file URL. I'm confused though why this only happens on Windows. Looks like this is Node.js 14.8.1, have you tried with 16?

I added node 16 to the [gh workflow](https://github.com/antonyfaris/sample-ava-ts/runs/4141449750?check_suite_focus=true). It looks like it also throws the same error.

**Comment by jasikpark** [comment]
https://twitter.com/n_moore/status/1457731934050824205?s=20 & https://twitter.com/n_moore/status/1457733079389425667?s=20 might be helpful context if it's related.... 

@natemoo-re have any insight into this?

**Comment by natemoo-re** [comment]
Hmm, maybe you could check if `payload.sources[0]` starts with `file://` before trying `fileURLToPath`? Otherwise you can assume it's already a path?

**Comment by novemberborn** [comment]
@antonyfaris there's a fix in the `main` branch. Could you `npm install -D avajs/ava#main` and see if that works?

**Comment by antonyfaris** [comment]
@novemberborn [it seems to be working](https://github.com/antonyfaris/sample-ava-ts/runs/4279549454?check_suite_focus=true) :)

**Comment by novemberborn** [comment]
@antonyfaris hurray!

Are you OK using the GitHub install for now? I won't have time to put out another pre-release for a while.

**Comment by antonyfaris** [comment]
> Are you OK using the GitHub install for now? I won't have time to put out another pre-release for a while.

Thanks for asking, I will open a pr in our repo and I will let you know.
