### ISSUE TITLE
List watch mode failure & type of failure *after* the diff

### ISSUE THREAD

**Issue by lunelson** [avajs/ava#2900]
I'm using AVA to test Sass output, and when any test fails in watch mode the diff is usually so large that it is very hard to see the info about what actually failed or why. It would be helpful to RE-list the failures and type of failure after the diff, so I can see which output changed (if it was expected); otherwise I have to scroll up for hundreds of lines to figure out what happened in which file.

**Comment by novemberborn** [comment]
This isn't really specific to watch mode though, is it? You'd have the same problem with the regular reporter. #2500 should point the way to improvements.

**Comment by lunelson** [comment]
True point @novemberborn 🤔  I'll refer to that issue then 😄
