### ISSUE TITLE
Option to disable dependency tracking

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#2905]
Dependency tracking may be fraught in CommonJS and currently doesn't work anyway in ESM. See discussion in https://github.com/avajs/ava/discussions/2887 and #2388.

When dependency tracking breaks, watch mode becomes less useful. Let's add a `trackDependencies` configuration option, defaulting to `true`, which when set to `false` disables dependency tracking. We can add a guard here:

https://github.com/avajs/ava/blob/77623a5f32c139fa4ef7d316a4bbf7e172cc5acb/lib/worker/base.js#L159

Presumably the solution for #2388 will involve parsing syntax files which may be slow, so having an opt out will be useful regardless.

**Comment by Sarveshk76** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/78719645/144896571-b4bc30f0-2887-4088-9af6-9695347aa040.png">
Is it right?

**Comment by novemberborn** [comment]
This would be irrelevant if #3123 is completed.
