### ISSUE TITLE
`after` hooks trigger just after the test run, not all the test finished

### ISSUE THREAD

**Issue by HomyeeKing** [avajs/ava#2907]
Please provide details about:

* What you're trying to do: `trigger something after the last test finished`
* What happened: 'after hook triggered during the test running'
* What you expected to happen

Please share relevant sample code. Or better yet, provide a link to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

We'll also need your AVA configuration (in `package.json` or `ava.config.*` configuration files) and how you're invoking AVA. Share the installed AVA version (get it by running `npx ava --version`).

**Comment by novemberborn** [comment]
Please share relevant sample code.

Closing for housekeeping purposes but happy to reopen. This may also be good as a Q&A discussion in https://github.com/avajs/ava/discussions.
