### ISSUE TITLE
Similar test titles causing Ava to throw an unhandled exception

### ISSUE THREAD

**Issue by stonebraker** [avajs/ava#2912]
Please provide details about:

When writing two tests with only slight variances in their titles, an unhandled exception is thrown by AVA 4.0.0-rc.1.

Adding the following tests to a file will result in an unhandled exception being thrown by the second test.
```

test.serial('Directory Service: should throw an error when attempting to remove a directory that contains the current working directory', (t) => {
    t.true(true);
})

test.serial('Directory Service: should throw an error when attempting to remove the current working directory', (t) => {
    t.true(true);
})
```

I would expect both tests to pass. The actual result is the second test failing with an unhandled exception.

I tried to nail down what was happening using simpler titles, but wasn't able to. There seems to be something about these two rather long titles that Ava is getting hung up on. Perhaps somebody more familiar with Ava's code base can sort it out. My workaround in the meantime is to throw an extra character (I'm using a period) at the end of the title of the second test. Then both tests pass as expected. 

Package.json

```
{
  "name": "thing-cli",
  "version": "1.0.0",
  "license": "MIT",
  "main": "./build/bin/process-command.js",
  "bin": {
    "thing": "./build/bin/process-command.js"
  },
  "preferGlobal": true,
  "type": "module",
  "scripts": {
    "dev:build": "tsc --watch -p .",
    "dev:update": "nodemon -e js -w build --exec 'npm install . -g'",
    "dev": "run-p dev:*",
    "build": "tsc",
    "update": "npm uninstall -g thing && npm i -g .",
    "refresh": "rm -r build && npm run build && npm run update",
    "test": "NODE_ENV=test ava --serial",
    "test:watch": "NODE_ENV=test ava --serial --watch"
  },
  "ava": {
    "files": [
      "build/tests/**/*.test.js",
      "!build/tests/**/*.test.js.map",
      "!build/tests/helpers"
    ],
    "ignoredByWatcher": [
      "data/**/*"
    ],
    "nodeArguments": [
      "--enable-source-maps"
    ]
  },
  "dependencies": {
  },
  "devDependencies": {
    "@types/node": "^16.11.9",
    "ava": "^4.0.0-rc.1",
    "nodemon": "^2.0.14",
    "npm-run-all": "^4.1.5",
    "sinon": "^12.0.1",
    "typescript": "^4.5.2"
  },
  "engines": {
    "node": "^16.9.1"
  }
}

```

I'm invoking Ava using with: 

```
npx ava -w --serial **/*/thing.test.js
```

Version:
```
npx ava --version
```
Yields: 1.0.0

**Comment by stonebraker** [comment]
Closing. User error. I had a test with the same title further up in the same test file.

**Comment by novemberborn** [comment]
What was the error you saw? It should have provided a clue as to the problem.

**Comment by stonebraker** [comment]
The error message was perfect. It was appearing at the top of the output and I just wasn't scrolling up far enough in the terminal window to see it.

The message at the top:
```
Error: Duplicate test title: Directory Service: should throw an error when attempting to remove the current working directory
```

All I was seeing:
```
✖ build/tests/directory-service.test.js exited with a non-zero exit code: 1
```

If anything, it'd be nice if the message was at the bottom of the output, but I should've walked away and come back to it. I had been going too long which is why I was writing duplicate tests in the first place. :-) Thanks for your prompt response. This is my first time working with Ava and I'm really liking it.
