### ISSUE TITLE
No feedback from test timeout

### ISSUE THREAD

**Issue by moderatemisbehaviour** [avajs/ava#2916]
If you set a timeout for an individual test using `t.timeout` you get feedback as I'd expect.

> Error: Test timeout exceeded

But if you pass the timeout from the CLI it just prints a blank line and exits with code 1. You can reproduce by running `npx ava timeout.test.js --timeout 1s` on the following.

```js
import test from 'ava'

test.cb('Test timeout', t => {
  setTimeout(t.end, 2000)
  t.assert(true)
})
```

**Comment by mislav** [comment]
The timeout failure seems printed in `--verbose` mode but not in regular mode. For now, `-v` could be used as temporary workaround.

**Comment by novemberborn** [comment]
Due to this issues, AVA 4 has removed non-verbose mode and defaults to verbose. Which sort of "solves" the problem.
