### ISSUE TITLE
TypeError: test.cb is not a function

### ISSUE THREAD

**Issue by zhenglong0034** [avajs/ava#2929]
![image](https://user-images.githubusercontent.com/10396795/148032360-c81141c5-8f32-404c-b9bf-53b9d8dd5d38.png)

**Comment by zhenglong0034** [comment]
node: 16.13.1
npm 8.1.2
ava 4.0.0

**Comment by novemberborn** [comment]
It has been removed in AVA 4. Use async functions and [`util.promisify()`])https://nodejs.org/docs/latest/api/util.html#util_util_promisify_original) instead.

**Comment by benjamin-rood** [comment]
> It has been removed in AVA 4. Use async functions and [`util.promisify()`])https://nodejs.org/docs/latest/api/util.html#util_util_promisify_original) instead.

Sorry, what does that mean? What should one call instead of `test.cb`? Linking to the node.js.org docs doesn't tell me how to migrate my previously-working AVA code... Are there migration docs I could read? Thanks.

**Comment by novemberborn** [comment]
Use `test()` and promisify your callback-taking functions so you can await them.

**Comment by yamachu** [comment]
I was also having issues with this, so I used the following code to deal with it.

```ts
import { ExecutionContext, FailingFn, TestFn } from 'ava';

export const testCbCompat = <T>(
    test: TestFn<T> | FailingFn<T> /* if needs others, add them */,
    title: string,
    assertions: (t: ExecutionContext<T> & { end: () => void }) => void
) => {
    test(title, async (t) => {
        await new Promise((resolve) => {
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            (t as any).end = () => {
                resolve(undefined);
            };
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            assertions(t as any);
        });
    });
};
```

Then, replace

```ts
test.cb('hoge', (t) => {
  /* some assertion */
  t.end();
});
```

with

```ts
testCbCompat(test, 'hoge', (t) => {
  /* some assertion */
  t.end();
});
```

`s/test.cb(/testCbCompat(test, /g`

If you have trouble with timeout-related processing, you can do something like this.

```ts
testCbCompat(
    test.failing,
    'if process not finished in 500ms, it fail',
    (t) => {
        t.timeout(500);
        t.true(true);
        // t.end(); // not called, cb will not finished
    }
);
```

Since the code is ad-hoc, it might be a good idea to rewrite the tests so that they can keep up with changes in ava :sob:

**Comment by benjamin-rood** [comment]
@yamachu Thank you, that's very helpful!

> Since the code is ad-hoc, it might be a good idea to rewrite the tests so that they can keep up with changes in ava :sob:

Yes, for sure. I am just forking an abandoned repo and trying to bring it back to life, and the test coverage was written for AVA 2 and I don't previously have experience with AVA... good opportunity to learn, though!

**Comment by mister-jscad** [comment]
I just want to pipe in here... So, AVA decides to bump to a major version and leave functionality behind. Fine. But shouldn't there be some documentation on HOW to convert those CB test cases? How about a discussion about this as well?

**Comment by ericcornelissen** [comment]
If I'm understanding this thread correctly _"callback mode"_ is no longer a thing, correct? However, [some mentions of _"callback mode"_ remain in the documentation](https://github.com/avajs/ava/search?q=callback+mode).
