### ISSUE TITLE
Ava v4 not recognized by ESLint (with AirBnb-base)

### ISSUE THREAD

**Issue by DavidVujic** [avajs/ava#2935]
I upgraded Ava to v4 and ran into linting issues. I am developing a Node.js library. The config I use doesn't recognize `ava` when using require. See gifski generated animation below!

Not sure if it is an issue with Ava, or with AirBnb-base. But this was introduced when switching from Ava v3 to v4.

My current workaround is to have a custom rule in the "tests" folder, where I ignore the "missing imports" rule.

![ava-eslint-airbnb-base](https://user-images.githubusercontent.com/301286/148543483-c9e0c798-7f03-49f3-b120-4861eec34f53.gif)

package.json (this is an example code, that reproduces the error):
```json
{
  "name": "ava-eslint",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "ava"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ava": "^4.0.0",
    "eslint": "^8.6.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-ava": "^13.1.0",
    "eslint-plugin-import": "^2.25.4"
  },
  "ava": {
      "files": ["./test/**/*"]
  },
  "eslintConfig":{
      "parserOptions": {
          "ecmaVersion": "latest"
      },
      "env": {
          "node": true
      },
      "extends": [
          "airbnb-base"
      ]
  }
}

```

**Comment by sindresorhus** [comment]
The import plugin probably struggles with this:

https://github.com/avajs/ava/blob/9bc615e2c93b264b98bac009a897c09d59f72bc4/package.json#L12-L15

But that is a problem with the import plugin and not AVA.

**Comment by DavidVujic** [comment]
Thank you for clarifying!
