### ISSUE TITLE
Assertion parameter names are inconsistent between documentation and declaration ("value" vs. "actual")

### ISSUE THREAD

**Issue by DavidAnson** [avajs/ava#2938]
Documentation for the `is` assertion uses parameter names `value` and `expected`: https://github.com/avajs/ava/blob/6b63b1bc14a1aaa7d4ee4f2201f901624419c677/docs/03-assertions.md#L124

Declaration for the same assertion uses parameter names `actual` and `expected`: https://github.com/avajs/ava/blob/6b63b1bc14a1aaa7d4ee4f2201f901624419c677/types/assertions.d.ts#L190

This is inconsistent. I think actual/expected is more clear and more common, so suggest standardizing on that pairing.

**Comment by novemberborn** [comment]
Sounds good to me. Would you like to open a PR @DavidAnson?

**Comment by DavidAnson** [comment]
Please don't wait for me to send a PR, it's unlikely I'll have time for this soon.
