### ISSUE TITLE
can't handle timeout exception

### ISSUE THREAD

**Issue by alisa4y** [avajs/ava#2939]
hi I had code which throws error like this:

test("throws", async (t) => {
  const e = await t.throwsAsync(async () => {
    setTimeout(() => {
      throw new Error("error");
    }, 0);
    await timeout(10);
  });
});
function timeout(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

it just can't handle it

**Comment by sindresorhus** [comment]
Please spend some more time on the issue.

What happens? What did you expect?

**Comment by sindresorhus** [comment]
`.throwsAsync()` cannot catch an error thrown inside `setTimeout`. That's just how JavaScript works and has nothing to do with AVA.

**Comment by alisa4y** [comment]
> `.throwsAsync()` cannot catch an error thrown inside `setTimeout`. That's just how JavaScript works and has nothing to do with AVA.

yes that's true :)
but I expected some how ava could do it :D
