### ISSUE TITLE
Barebones ESM test module throws "TypeError [ERR_INVALID_URL]:   Invalid URL: ./package.json"

### ISSUE THREAD

**Issue by broofa** [avajs/ava#2943]
Trying to spin up a barebones ESM test...

```
$ mkdir /tmp/foo

$ cd /tmp/foo

$ npm init -y

$ npm i -D ava

$ cat > test.mjs <<- EOM
import {test} from 'ava';
test('runs', async () => {});
EOM

$ ava

  Uncaught exception in test.mjs

  TypeError [ERR_INVALID_URL]: Invalid URL: ./package.json

  ✖ test.mjs exited with a non-zero exit code: 1
  ─

  1 uncaught exception

$
```

Here's my environment ...

```
$ envinfo
npx: installed 1 in 0.937s

  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 67.50 MB / 16.00 GB
    Shell: 5.1.8 - /usr/local/bin/bash
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.1
    Safari: 15.1
```

**Comment by novemberborn** [comment]
Current Node.js doesn't let you import JSON. Use the file system or create a require().

**Comment by broofa** [comment]
@novemberborn Please consider reopening.  If you look at the (literally 2-line) test, you'll see I'm not doing anything with any `package.json`.  This is something internal to `ava` that's breaking.

**Comment by broofa** [comment]
FWIW, this appears to be something internal to Node's ESM loading...?  If I add a `console.log(error)` line to `ava`'s internal `serializeError()` method I get this stack trace for the error:

```
TypeError [ERR_INVALID_URL]: Invalid URL: ./package.json
    at onParseError (internal/url.js:279:9)
    at new URL (internal/url.js:355:5)
    at getPackageScopeConfig (internal/modules/esm/resolve.js:133:24)
    at packageResolve (internal/modules/esm/resolve.js:623:25)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:132:31)
    at async ModuleJob.run (internal/modules/esm/module_job.js:166:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24) {
  input: './package.json',
  code: 'ERR_INVALID_URL'
}
```

Which is a little weird, as there's no frame for anything related to either `ava` or my little test script.

**Comment by broofa** [comment]
Nevermind.  This inanity brought to you by having `import {test} from 'ava'` instead of `import test from 'ava'`.

![image](https://media.giphy.com/media/KBaxHrT7rkeW5ma77z/giphy.gif)

**Comment by lagden** [comment]
I had the same problem but had to dig in to find the real problem.  
I my case, when I updated the packages, one package was causing the error.  
So, I changed it:

`import FileType from 'file-type'` to `import {fileTypeFromBuffer} from 'file-type'`
