### ISSUE TITLE
Running a test with --node-arguments='--expose-gc' causes ERR_WORKER_INVALID_EXEC_ARGV

### ISSUE THREAD

**Issue by dmaevsky** [avajs/ava#2944]
`npx ava tests/perf.spec.js --node-arguments='--expose-gc' `

gives me
```
✖ Internal error
  Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid execArgv flags: --expose-gc
```

version `4.0.1`

**Comment by novemberborn** [comment]
AVA uses worker threads by default. Looks like this is not an argument that can be passed to worker threads. You can run with `--no-worker-threads` (IIRC) to use child processes and then this should work.

**Comment by codetheweb** [comment]
I ran into this too trying to use `--prof`. Might be worth adding something to the docs about.
