### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by vishnureddy17** [avajs/ava#2949]
I just got started using AVA, and I can't seem to find an API reference where I can get an overview of the entire API surface of AVA. Does something like this exist? If not, I think this is something to consider, as it will improve the usability of AVA. 

Apologies if this already exists!

**Comment by live627** [comment]
Did you [check the `docs` folder](https://github.com/avajs/ava/blob/main/docs/03-assertions.md#built-in-assertions)?

**Comment by novemberborn** [comment]
There's no API reference as such, the [type definitions](https://github.com/avajs/ava/tree/main/types) are probably closest but even those are spread across multiple files.

An actual website could be a way to go but we'd need contributors for that. Will close this for the time being.
