### ISSUE TITLE
[ERR_WORKER_UNSUPPORTED_OPERATION]: process.chdir() is not supported in workers

### ISSUE THREAD

**Issue by ctjlewis** [avajs/ava#2956]
It's not possible to change the process directory in an Ava test, and trying the hack suggested in #2591 throws the same error.

I intend to change directory and spawn processes in my test. Do I have to drop ava for these kinds of things?

**Comment by ctjlewis** [comment]
Working around by changing directory in the shell context, i.e.

```ts
await shell("cd ./my/dir && yarn test");
```

**Comment by sindresorhus** [comment]
https://github.com/nodejs/node/issues/41673

**Comment by sindresorhus** [comment]
You can use the `--no-worker-threads` flag.
