### ISSUE TITLE
Watch mode not respecting ignoredByWatcher

### ISSUE THREAD

**Issue by razor-x** [avajs/ava#2957]
When running a test that saves files to `tmp/some-dir/some-file` AVA will loop forever in watch mode even if `ignoredByWatcher` is set. Same behaviour in AVA v3 and v4.

Minimal reproducible example: https://github.com/rxbugs/ava-watch-ignore

```
Arch Linux

node version    
v16.13.2

AVA version
4.0.1 or 3.15.0
```

```json
{
  "ignoredByWatcher": ["tmp/**/*"]
}
```

```json
{
  "type": "module",
  "scripts": {
    "test:watch": "ava -w",
    "test": "ava"
  },
  "devDependencies": {
    "ava": "^4.0.1",
    "mkdirp": "^1.0.4"
  }
}
```

```js
import path from 'path'
import { promises as fsPromises } from 'fs'

import test from 'ava'
import mkdirp from 'mkdirp'

test.beforeEach(async (t) => {
  const root = 'tmp'
  await mkdirp(root)
  t.context.dst = await fsPromises.mkdtemp(path.join(root, 'foo-'))
})

test('bug', async (t) => {
  await fsPromises.writeFile(path.join(t.context.dst, 'foo'), 'bar')
  t.pass()
})
```

**Comment by novemberborn** [comment]
Your configuration isn't being picked up. AVA only support JavaScript configuration files, so you'd want something like `ava.config.js`:

```js
{
  "ignoredByWatcher": ["tmp/**/*"]
}
```

**Comment by razor-x** [comment]
> Your configuration isn't being picked up. AVA only support JavaScript configuration files, so you'd want something like `ava.config.js`:
> 
> ```js
> export default {
>   "ignoredByWatcher": ["tmp/**/*"]
> }
> ```


🤦🏻 Thank you. I feel I can't be the only one who missed this change. Can I suggest a waring like this? https://github.com/avajs/ava/pull/2962
