### ISSUE TITLE
Support `Actual extends Expected` in conjunction with `Expected extends Actual`

### ISSUE THREAD

**Issue by RebeccaStevens** [avajs/ava#2964]
### The Problem

The type `DeepEqualAssertion` requires that the `Expected` type extends the `Actual` type.
However, sometimes we want this relationship to be the other way around.

Consider the following example:

```ts
test("my test", (t) => {
  const expected = { foo: [1, 2, 3] } as const;
  const actual = functionToTest(1, 2, 3);

  t.deepEqual(actual, expected);
});
```

If the type of `actual` is inferred as `{ foo: number[] }` then this does not extend the type of `expected` which is `{ readonly foo: readonly number[] }`. Thus TypeScript reports an error.

### Suggested Fix

Add a overload to `DeepEqualAssertion` to handle this case:

```ts
export interface DeepEqualAssertion {
	/**
	 * Assert that `actual` is [deeply equal](https://github.com/concordancejs/concordance#comparison-details) to
	 * `expected`, returning a boolean indicating whether the assertion passed.
	 */
	<Actual, Expected extends Actual>(actual: Actual, expected: Expected, message?: string): actual is Expected;

	/**
	 * Assert that `actual` is [deeply equal](https://github.com/concordancejs/concordance#comparison-details) to
	 * `expected`, returning a boolean indicating whether the assertion passed.
	 */
	<Actual extends Expected, Expected>(actual: Actual, expected: Expected, message?: string): expected is Actual;

	/** Skip this assertion. */
	skip(actual: any, expected: any, message?: string): void;
}
```

**Comment by novemberborn** [comment]
I think this would be great. Would there be any compatibility issues with existing code?

**Comment by RebeccaStevens** [comment]
I don't believe this change would introduce any compatibility issues.

**Comment by novemberborn** [comment]
@RebeccaStevens do you want to submit a PR for this?

**Comment by RebeccaStevens** [comment]
@novemberborn #2969
