### ISSUE TITLE
Coverage with watch mode

### ISSUE THREAD

**Issue by eden-omb** [avajs/ava#2970]
I don't know much about how Ava is built, this might be just a missing recipe. By following [the coverage recipe](https://github.com/avajs/ava/blob/main/docs/recipes/code-coverage.md) I can generate test coverage reports. My best attempt at combining this with watch mode is to have an NPM script like so `c8 ava -w`, but then (reasonably) `c8` only triggers after I quit watch mode. I want a way to trigger `c8` on every watch mode run.

**Comment by novemberborn** [comment]
Node.js now has APIs to turn coverage collection off and on again. The challenge is knowing when to generate the reports. AVA currently has no hooks for that but shared workers could be extended in that direction.

**Comment by novemberborn** [comment]
FWIW https://github.com/avajs/ava/pull/3220 writes the coverage after each test run has ended — there's still no way to trigger `c8` afterwards though you could have a separate script monitor the output directory.
