### ISSUE TITLE
Support function in `message` expectation in `t.throws` / `t.throwsAsync`

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#2978]
The most common way to use `t.throws` is to match against the error message. However, sometimes part of the error message varies by Node.js versions or operating systems. Currently, you would use regex matching for this. But with regex, you have to be careful to escape special symbols.

I suggest adding support for a function as the `message`. This would make it easy to:
- Check is a message contains a certain string
- Check if the error message is one of multiple messages

Examples:

```js
await t.throwsAsync(async () => {
	throw new TypeError('🦄');
}, {
	message: message => ['🦄', '🐴'].includes(message)
});

await t.throwsAsync(async () => {
	throw new TypeError(`${process.platform} is not supported`);
}, {
	message: message => message.includes('is not supported')
});
```

**Comment by novemberborn** [comment]
Both sound good. We do validate the message expectation that is provided so this isn't a breaking change.

**Comment by il3ven** [comment]
I think we should not pollute the API when the above can be achieved by adding a simple line.

```js
const promise = Promise.reject(new TypeError('🦄'));

test('rejects', async t => {
	const error = await t.throwsAsync(promise);
	t.true(['🦄', '🐴'].includes(error.message));
});
```

**Comment by novemberborn** [comment]
@il3ven I get where you're coming from, and I would agree for additional non-standard error properties. However this is a nice extension of the already existing "expectations" API. I think it's worthwhile.
