### ISSUE TITLE
Document that AVA 4 cannot be run globally

### ISSUE THREAD

**Issue by binyamin** [avajs/ava#3026]
In commit a763592, the docs were modified to explain that AVA 4 cannot be run globally. In f09742f, this was removed ([diff](https://github.com/avajs/ava/commit/f09742f7baab7d44a48f1e3cee8f4b22deecf6f4#diff-a89aa74aa84d41f245185beac2e62ca024ba87d84740430e06aacf9b156cf5baL52-L53)). I assume the second change was a mistake. In any case, the user should know about this detail.

**Comment by novemberborn** [comment]
Sure, we could add a "Note: AVA 4 cannot be run globally." PR welcome.

**Comment by binyamin** [comment]
@novemberborn how about in [`/docs/08-common-pitfalls.md`](https://github.com/avajs/ava/blob/main/docs/08-common-pitfalls.md)?

**Comment by novemberborn** [comment]
@binyamin sure, sounds good.
