### ISSUE TITLE
CLI running tests filtered by line does not work anymore

### ISSUE THREAD

**Issue by sculpt0r** [avajs/ava#3049]
According to docs: https://github.com/avajs/ava/blob/main/docs/05-command-line.md#running-tests-at-specific-line-numbers it is possible to run a specific test by line number.

Please open the StackBlitz linked in the documentation. It should work fine. Then, change the AVA version to `4.3.0` in `package.json`. Instal with `npm i` and try to run the test again with `npm run test`. Now there is an error in the StackBlitz terminal:
![image](https://user-images.githubusercontent.com/6498567/172072112-25a7bc9c-3763-42f2-a729-00b9b9c1f945.png)

Also, in a different project with TS, when I tried to run a test with a line filter, I received only some generic information:
![image](https://user-images.githubusercontent.com/6498567/172072193-9141d6eb-e97c-40c9-bf06-209772d16410.png)

It would be good to provide some more output to the console - because right now I don't know the reasons why the file can't be parsed? Without the line filter - tests in the file work fine 🤔

**Comment by novemberborn** [comment]
The example works locally. Looking at the stack trace that is printed, it contains HTTPS URLs. AVA is not expecting that.

Probably `current` here is coming back as `undefined` which I would say is unexpected and due to the StackBlitz environment: https://github.com/avajs/ava/blob/3f17f8c7d6070c6414896a439dc93a6f3613a620/lib/worker/line-numbers.js#L105-L110

Are you running into this locally or really are you asking about your TypeScript project? If you modify this line it should contain more details: https://github.com/avajs/ava/blob/3f17f8c7d6070c6414896a439dc93a6f3613a620/lib/reporters/default.js#L222

**Comment by sculpt0r** [comment]
TBH I try to write a CodeLens for VSC extension that run test case from given line. For now, I tried this command with two TS projects I have, but maybe I should try with plain JS project 🤔 After unsuccessful runs I moved to the documentation sample - which works in `3.15.0` - but when I switched in a given sample to `4.3.0` it starts to fail. I'll try it as a local project - thanks :)

BTW, I've run this in debug mode and find out in event message: `"SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)"`. So it looks like my problems with TS 🤔

**Comment by sculpt0r** [comment]
The exception comes right from the code you highlighted. But only for the TS project. I just verified it on new clean JS project and filter with line numer works fine 👍 

I think I just open a new discussion, as you mentioned [here](https://github.com/avajs/ava/discussions/3036#discussioncomment-2886696).

Not sure - but this report could be closed or do you think that we need some outcome from it: like removing the stackblitz sample from the docs or just mention there that it works 'online' only for the version < `4`?

**Comment by novemberborn** [comment]
> The exception comes right from the code you highlighted. But only for the TS project. I just verified it on new clean JS project and filter with line numer works fine 👍 Thank you for the help :)

That does sound like a bug. That's locally / in CI right, not with StackBlitz? Do you have a reproduction you could share?



> Not sure - but this report could be closed or do you think that we need some outcome from it: like removing the stackblitz sample from the docs or just mention there that it works 'online' only for the version < `4`?

There's a PR for updating the examples so I've mentioned it there: https://github.com/avajs/ava/pull/3017#issuecomment-1148654771

**Comment by sculpt0r** [comment]
> That does sound like a bug. That's locally / in CI right, not with StackBlitz? Do you have a reproduction you could share?

That is right: it is locally. I try to prepare a sample project and if I won't be able - I try to send an invitation to the private repo - this one I can share :) Just give me some time 🙏

**Comment by sculpt0r** [comment]
So I have two sample projects:

- [ts.zip](https://github.com/avajs/ava/files/8858124/ts.zip)
This one I believe is the easiest version of TS + AVA. The results of running ava with filter:
```bash
![image](https://user-images.githubusercontent.com/6498567/172526960-b7d54825-97b8-45df-a11e-db89cff96d3c.png)
```

- [ts-no-tsnode.zip](https://github.com/avajs/ava/files/8858132/ts-no-tsnode.zip)
This one have no `ts-node` neither AVA config. And the same command produce different results:
![image](https://user-images.githubusercontent.com/6498567/172527278-a2acadd1-14a8-4997-a262-aa44a870a06a.png)


Also I send you an invitations to the organisation and the repository inside it. The repo is like a monorepo. Could you `npm i` in the main directory and then in the terminal go to the inner directory `src/backend` - then `npm i` again?

One of the test is placed in `/engine/src/backend/system/controller-selector.test.ts` - so when I runs it like:
```bash
npx ava --verbose /Users/sculpt0r/projects/engine/src/backend/system/controller-selector.test.ts:47
```
I receive:
![image](https://user-images.githubusercontent.com/6498567/172528747-f6ffeef4-80e8-4e8e-b64b-0c3fdff1dea4.png)

Please notice I changed the [ava/lib/worker/line-numbers.js](https://github.com/avajs/ava/blob/3f17f8c7d6070c6414896a439dc93a6f3613a620/lib/worker/line-numbers.js#L14-L18)
so it contains additionall `try...catch` and dummy `log`:
![image](https://user-images.githubusercontent.com/6498567/172528836-fa572b6d-858f-45ab-8c27-37be239dded7.png)

The exception detail indicates to: ``

**Comment by novemberborn** [comment]
I haven't had a chance yet to look into this.

**Comment by sculpt0r** [comment]
This feature works fine for JS project, but not for TS.

I'm able to run test file with AVA, but AVA is unable to find any test if the same file is filtered by line number.

**Comment by novemberborn** [comment]
@sculpt0r there's a bug in how the source map is applied for your `ts.zip` reproduction.

For the larger project you shared last month, the problem is that the parser chokes on the `implements` keyword. Ideally we identify a compatible parser or `acorn` replacement. We then need to figure out how to select that parser (either automatic, and added to the dependencies, or side-loading like `@ava/typescript`).

Even with `@ava/typescript` in pre-compiled mode we still attempt to parse the TypeScript. This is silly and we should parse the JS instead and then rely on the source maps.

I'll open some follow-up issues as well as a PR to fix the bug and report the parser error.

**Comment by novemberborn** [comment]
Bugfix: https://github.com/avajs/ava/pull/3061
Error reporting: https://github.com/avajs/ava/pull/3062
Follow-up issues: https://github.com/avajs/ava/issues/3064 & https://github.com/avajs/ava/issues/3065
