### ISSUE TITLE
ava's colored diff doesn't allow understanding diffs on plain text only logger interfaces like GitHub Actions

### ISSUE THREAD

**Issue by TimDaub** [avajs/ava#3052]
- as you can see from this piece of test code: https://github.com/neume-network/strategies/runs/6791138479?check_suite_focus=true#step:6:86 we're comparing two objects with each other using `t.is`
- And then below notice the diff https://github.com/neume-network/strategies/runs/6791138479?check_suite_focus=true#step:6:91
- Unfortunately, this specific error only seems to happen for us within the CI, so I can't reproduce it locally.
- But on GitHub Actions, as you can see for yourself, I can also not understand the diff as GitHub Actions don't log the colors in ava's original output
- Here's an example of that on my local machine. See how "hello" is marked in green

<img width="1240" alt="Screenshot 2022-06-08 at 16 01 23" src="https://user-images.githubusercontent.com/2758453/172636261-66450e3c-70d2-497f-8722-72677ccbd7f6.png">

To solve: Is this a general issue with ava, or do I maybe just have to select another diff reporter?

**Comment by TimDaub** [comment]
thanks for the tip for the work around. But yeah I think we're comparing strings. But in general, I'm also interested in solving this problem for good if it is indeed with ava and not my setup.

**Comment by TimDaub** [comment]
A work around that could get merged is IMO just printing both strings below each other for now. Then at least users have functionality in GH Actions until a fancy underline text algorithm is merged here.

**Comment by novemberborn** [comment]
@TimDaub I think it should print both lines, like you have locally. Any chance one of the values is an empty string?

**Comment by sindresorhus** [comment]
@novemberborn It really depends on what the terminal renderer in GitHub Actions supports. All terminals support bold, but only some support underline/strikethrough/italic. You kinda just need to test and see.

**Comment by novemberborn** [comment]
> It really depends on what the terminal renderer in GitHub Actions supports. All terminals support bold, but only some support underline/strikethrough/italic. You kinda just need to test and see.

@sindresorhus interesting. Sounds like that support is not detectable, so we'd need a way to identify CI's and refine based on our knowledge?

If you think that's a direction worth pursuing I can write it up in a ticket.

---



> it doesn't print `- ` from what I can tell

Indeed, that is pretty weird. Locally with empty strings or `undefined` it prints it just fine. It seems like we have two different problems here?

**Comment by sindresorhus** [comment]
GitHub Actions supports colors though, so not sure why it's not used. Maybe you need to upgrade Chalk for that.

**Comment by sindresorhus** [comment]
> so we'd need a way to identify CI's and refine based on our knowledge?

Any terminal and CI I know about that can display bold/underline, can also display colors.

**Comment by tmillr** [comment]
@TimDaub idk if it'd work but maybe try the `--color` cli option to Ava to force color output. I'm like 90% sure I read in the docs that GitHub actions supports color output in its logs via the standard/usual ANSI escape codes. Also I don't think GitHub Actions automatically allocates a tty or pseudo-tty for you either, and most utilities will automatically disable color/escape code output if they can't detect a tty device on stdout (although I'm not totally sure how Ava handles this). So perhaps forcing color output will help?
