### ISSUE TITLE
when using typescript, type errors aren't shown

### ISSUE THREAD

**Issue by odama626** [avajs/ava#3067]
When using typescript, when you have a type error, instead of getting the error from ts-node, you get the error "timed out while running tests"

```js
// ava.config.js
export default {
  files: ['packages/**/*.test.(j|t)s'],
  extensions: {
    js: true,
    ts: 'module',
  },
  nodeArguments: ['--loader=ts-node/esm'],
};
```

**Comment by novemberborn** [comment]
This is a problem with `ts-node`. AVA needs there to be an uncaught exception, but `ts-node` seems to fail silently. See also the discussion here: https://github.com/avajs/ava/discussions/3033#discussioncomment-2845448.
