### ISSUE TITLE
Eslint fails on node-no-missing-require and node/no-unpublished-require

### ISSUE THREAD

**Issue by NickColley** [avajs/ava#3088]
```javascript
const test = require("ava");

test("should be true", async (assert) => {
  assert.true(true);
});
```

With eslint node/recommended I get:

```
error  "ava" is not found (node/no-missing-require)
error  "ava" is not published (node/no-unpublished-require)
```

Is there something missing from my configuration or ava's published package.json?

**Comment by jonathansamines** [comment]
Hey @NickColley you'll probably need to adjust the [allowModules](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-missing-require.md#allowmodules) plugin setting to exclude ava. I had to do a similar thing for `eslint-plugin-import` (see https://github.com/mysticatea/eslint-plugin-node/issues/314). Most of eslint plugins do not play well yet with `exports maps` (which ava 4.x uses)

**Comment by Windvis** [comment]
I ran into the the `no-unpublished-require` rule as well and the docs explain it pretty good: https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-require.md#-rule-details

In my case it was triggered because `ava` is a devDependency but I didn't make use of `files` and the test files weren't added to `.npmignore` yet so they would have actually been published to npm.

**Comment by NickColley** [comment]
I wonder given my repository has "private" set to true so it can never be published if these rules could automatically relax?

**Comment by Windvis** [comment]
@NickColley I had the same thoughts and that's indeed a popular request in the eslint-plugin-node repo: https://github.com/mysticatea/eslint-plugin-node/issues/77 Sadly that projects is kind of unmaintained at the moment.

I did however create a [PR](https://github.com/eslint-community/eslint-plugin-n/pull/57) in the community fork but that still needs to be reviewed.

**Comment by NickColley** [comment]
Seems like this is already discussed then, thank you for your time.
