### ISSUE TITLE
Snapshots not working on Node.js 18.8.0

### ISSUE THREAD

**Issue by danez** [avajs/ava#3092]
Throws the following error:

```
  TypeError: Cannot destructure property 'payload' of 'sourceMap' as it is null.
```

This is happening because Node.js 18.8.0 changed the return value of `findSourceMap` from `undefined` to `null` if no source-map found (see [here](https://github.com/nodejs/node/pull/43875/files#r954804828)) and AVA is expecting `undefined` [here](https://github.com/avajs/ava/blob/main/lib/snapshot-manager.js#L393-L394).

Not sure if this was changed by mistake or on purpose in Node.js, so it might be reverted, but I wanted to raise this here in case other people run into this.

Might be anyway a good idea to change the if in ava to this?

```diff
-if (sourceMap === undefined) {
+if (sourceMap == undefined) {
```

https://github.com/nodejs/node/issues/44391

**Comment by novemberborn** [comment]
Thanks for reporting. See #3091.
