### ISSUE TITLE
Process completed with exit code 139 on Windows Server 2022

### ISSUE THREAD

**Issue by liby** [avajs/ava#3097]
With the `workerThads` option enabled, `Segmentation fault` is raised on Windows Server 2022.

Please provide details about:

* What you're trying to do 
	* Work on CI/CD	 
* What happened
	* Normal work
* What you expected to happen
  ```
	  D:\a\_temp\655f499a-168c-4478-b6d4-249d28b527fd.sh: line 2:  1158 Segmentation fault      yarn test
	  Error: Process completed with exit code 139.
	  ##[debug]Finishing: Build
  ```

Please share relevant sample code. Or better yet, provide a link to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
https://github.com/liby/hexo-util-rs/tree/feature/test-ci

We'll also need your AVA configuration (in `package.json` or `ava.config.*` configuration files) and how you're invoking AVA. Share the installed AVA version (get it by running `npx ava --version`).

- AVA configuration
	```
	  "ava": {
	    "require": [
	      "@swc-node/register"
	    ],
	    "extensions": [
	      "ts"
	    ],
	    "environmentVariables": {
	      "TS_NODE_PROJECT": "./tsconfig.json"
	    },
	    "workerThreads": true
	  },
	```

- how you're invoking AVA
	```
  "scripts": {
      "test": "ava",
    }
	...
	yarn test
	```
- `npx ava --version`: 4.3.3

**Comment by novemberborn** [comment]
Segfaults like this are most likely caused by Node.js, not AVA.
