### ISSUE TITLE
AVA Test fails due to timeout, however, exit code 0 is returned

### ISSUE THREAD

**Issue by simplenotezy** [avajs/ava#3098]
We sometimes experience that the Github actions to deploy our application fails the test suite, however, it marks it as completed. See:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/3786627/187437545-5927c25f-d28d-4fd6-96b5-ae8d79cadddd.png">

Should be (same test, just a few minutes earlier):

<img width="452" alt="image" src="https://user-images.githubusercontent.com/3786627/187437634-70a7fd38-4988-44f4-8e51-0d4618f9cebe.png">

We run the command:

```bash
ava --no-worker-threads -c 1 --verbose --timeout 1m --fail-fast
```

Using ava version: `^4.3.1`

**Comment by liby** [comment]
There is a [similar error](https://github.com/liby/hexo-util-rs/runs/8150130472?check_suite_focus=true), not sure if the issue is the same.

Configuration:
```
  "ava": {
    "require": [
      "@swc-node/register"
    ],
    "extensions": [
      "ts"
    ],
    "environmentVariables": {
      "TS_NODE_PROJECT": "./tsconfig.json"
    },
    "workerThreads": false
  },
```

**Comment by novemberborn** [comment]
Looks like the exit code is only `1` when there still were pending tests, which won't always be the case.

https://github.com/avajs/ava/blob/ea597d86137b6fe47ed56ccb29b1b1108bd6e9f9/lib/run-status.js#L129-L130
