### ISSUE TITLE
Do not strip repeat spaces from title

### ISSUE THREAD

**Issue by gajus** [avajs/ava#3114]
Please provide details about:

### What you're trying to do

I am trying to have two test cases with titles:

```
( test )
(   test   )
```

### What happened

Ava converts them both to `( test )` and complains about duplicate titles.

### What you expected to happen

I expected whitespaces to be kept as they are in my original title.

### Ava version

4.3.3

**Comment by novemberborn** [comment]
Hi @gajus. This came from #2774. AVA intends for test titles to be human readable; to help you understand what's being tested. Normalizing whitespace is the better decision for most use cases. You'll have to find a different way of representing the whitespace.
