### ISSUE TITLE
t.log() does not output anything if an async test fails due to time out

### ISSUE THREAD

**Issue by kevo1ution** [avajs/ava#3122]
First, thanks for maintaining such a great tool. So far it has addressed most of our javascript unit and integration test running needs.

**What you're trying to do**
I would like to see important test debug logs even if it times out.

**What happened**
Simple async test that will timeout because the promise resolves after 20 seconds. The test has a simple `t.log()` invocation.
```js
import test from 'ava';

test('example where logs are not provided by ava when test time out', async (t) => {
  t.log({ message: 'Very important debug statement, that developer would love to see in output after test run' });

  await new Promise((res) => {
    console.log('start promise that resolves after timeout...');
    setTimeout(res, 20000);
  });
});
```

Simple test output (note ava is run with timeout=1s configured):
```bash
 $ npx ava --timeout=1s --verbose

start promise that resolves after timeout...
  
  ✖ Timed out while running tests

  1 tests were pending in test/example.js

  ◌ example where logs are not provided by ava when test time out

  ─

  1 test remained pending after a timeout
```

**What you expected to happen**
I expected the output to contain the log: `Very important debug statement, that developer would love to see in output after test run`.
Being able to see this log will be very helpful in determining why the test timed out.

**Environment**
`package.json`
```json
{
  "name": "ava-logging-timeout-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ava": "^4.3.3"
  }
}
```
```bash
$ node -v 
v16.16.0
$ npx ava --version
4.3.3
```

**Comment by kevo1ution** [comment]
Just skimmed some of the code:

If we want to output logs even when the tests timeout, we have to call this `this.writeLogs(event);`. Right now, it seems only the `writeTestSummary` function does so: https://github.com/avajs/ava/blob/main/lib/reporters/default.js#L516

when handling tests that have timed out, I think we just need to either add `this.writeLogs` here:
https://github.com/avajs/ava/blob/main/lib/reporters/default.js#L366

or make the `writeTestSummary` function also supports tests that have timed out

**Comment by kevo1ution** [comment]
@novemberborn any thoughts on this?

**Comment by novemberborn** [comment]
I agree it would be useful to see these log messages. I'm not sure if they're ever sent up to the main process though. IIRC this data is only provided when the test fails or passes, neither of which is the case here. It would require more changes to make this work.

**Comment by kevo1ution** [comment]
After playing with the code, I think I see what you mean. We have to plumb the `test` object through somehow because it has a reference to the `logs`. Right now we don't emit any events to register the test logs until either it passes or fails.

So I think the right approach is we plumb that logs object through when the `Test` object gets instantiated by emitting a `stateChanged` event that the test started. I'll try to make a PR and take a stab at this
