### ISSUE TITLE
Basic example from readme doesn't work

### ISSUE THREAD

**Issue by vedmant** [avajs/ava#3157]
I followed basic example instruction from readme:

1. Added `"test": "ava"` to "scripts" in package.json
2. Run `yarn add ava --dev`
3. Created `test.js` in project root
4. Run `yarn test`

And have following error:
```
$ ava

  Uncaught exception in test.js

  /Users/my-project/test.js:1
  import test from 'ava'
  ^^^^^^

  SyntaxError: Cannot use import statement outside a module

  ✘ test.js exited with a non-zero exit code: 1
  ─

  1 uncaught exception
error Command failed with exit code 1.

```

**Comment by Zajozor** [comment]
do you have "type": "module" in your package.json ? 
If you have an empty project, maybe just adding it is enough.

It seems that the test code is has ESM style imports, but is treated as a CommonJS module to me.
Do you use a bundler of some sorts? If you're not familiar with the ESM vs CommonJS topic, I recommend [reading up](https://adamcoster.com/blog/commonjs-and-esm-importexport-compatibility-examples) on it, it's quite vital to understanding of the issue.

**Comment by vedmant** [comment]
@Zajozor In the example in readme there is no `"type": "module"` so I assume is supposed to work without it, so either readme should be updated or something should be fixed.

**Comment by novemberborn** [comment]
I've amended this in the main README, but it's hard to make this unambiguously clear without repeating it _everywhere_.

AVA is focused on being a test runner for Node.js, not bundler output. In 2023 that does require from users a familiarity with both module systems in use by Node.js.
