### ISSUE TITLE
feature request: set configuration from environment variables

### ISSUE THREAD

**Issue by gibson042** [avajs/ava#3160]
I have a need to invoke the same tests differently in the same CI setup; sometimes using the default reporter and sometimes using TAP. This precludes the possibility of using configuration files, and the particular setup involves automatic invocation in subdirectories in a way that makes varying arguments impractical.

But environment variables _are_ passed down fully, so it would be very convenient if the executable understood e.g. `AVA_TAP` as indicating that the `tap` setting should be on unless overridden by an argument. And fortunately, this is extremely convenient with the [yargs](https://www.npmjs.com/package/yargs) library already used by [cli.js](https://github.com/avajs/ava/blob/647d3e15305ae5fdfccf3009fdd1ef18a82af6a1/lib/cli.js)—basically as simple as [`.env('AVA')`](https://github.com/yargs/yargs/blob/HEAD/docs/api.md#envprefix) to support all arguments.

**Comment by novemberborn** [comment]
I'm reluctant to add configuration magic through environment variables. Configuration files (the JS ones) do have access to `process.env` though, could you use that to enable TAP conditionally?

**Comment by gibson042** [comment]
Nice idea. It works, but is a bit awkward because the subdirectories have package.json files with ava configuration so I need to explicitly specify `--config` and target a file that parses $projectDir/package.json to add overrides. But I understand (and in fact share) your apprehension around environment variables, and will understand if this case is not sufficiently compelling.
