### ISSUE TITLE
Pending timed-out tests are not reported at the end summary

### ISSUE THREAD

**Issue by emilis-ideait** [avajs/ava#3166]
I ran a number of tests. One of them timed out and was reported as pending:

![image](https://user-images.githubusercontent.com/78907189/216270518-4e691db6-afea-4abf-ba94-bab9385220c7.png)

At the end of the output I saw this:

![image](https://user-images.githubusercontent.com/78907189/216270883-77685795-daf0-4bb9-8d6d-33fc3e79d8fa.png)

I expected to see "16 tests passed, 1 test was pending" or similar at the end.

ava.config.js:
```javascript
export default {
    concurrency:                1,
    files: [
        'tests/scorm-tests/*.test.mjs',
    ],
    serial:                     true,
    verbose:                    true,
};
```

Ava version `4.2.0`.

**Comment by novemberborn** [comment]
There have been changes in AVA 5 relating to this I believe.
