### ISSUE TITLE
Default to verbose.

### ISSUE THREAD

**Issue by Raynos** [avajs/ava#3189]
without `--verbose` i get zero information about what test times out.

With verbose you tell me why the tests fail.

please just default to `--verbose` ... I wasted hours on this.

**Comment by novemberborn** [comment]
Non-verbose mode was removed in AVA 4 I think. The flag currently doesn't do anything other than being there for when a less verbose mode is reintroduced.

**Comment by Raynos** [comment]
The flag has impact in `ava 4.3.3`

It has a huge impact on whether you log timeouts or not log timeouts, `ava` without `--verbose` is unusable in `4.3.3`
