### ISSUE TITLE
registerCompletionHandler can't be used in CommonJS project

### ISSUE THREAD

**Issue by sosnovsky** [avajs/ava#3306]
Please provide details about:

* What you're trying to do
I tried to use `registerCompletionHandler` in CommonJS project (https://github.com/FlowCrypt/flowcrypt-browser)

* What happened
I wasn't able to import `registerCompletionHandler`, as it's not added to `main.d.cts`

* What you expected to happen
I expected `registerCompletionHandler` to be available for import

**Comment by novemberborn** [comment]
This is intentional. Mostly to avoid polluting the default export in CJS, which is shared with ESM. Also because usage ought to be rare enough that you can work around it in CJS using dynamic import.

**Comment by acro5piano** [comment]
> you can work around it in CJS using dynamic import

This works for me:

```ts
import('ava').then(({ registerCompletionHandler }) => {
  registerCompletionHandler(() => {
    process.exit(0)
  })
})
```
