### ISSUE TITLE
Add support for Node 22

### ISSUE THREAD

**Issue by ehmicky** [avajs/ava#3327]
* What you're trying to do

Use Ava with Node 22.

* Why you can't use AVA for this

If `--engine-strict` is used, `npm install` fails with:

```
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: ava@6.1.2
npm error notsup Not compatible with your version of node/npm: ava@6.1.2
npm error notsup Required: {"node":"^18.18 || ^20.8 || ^21"}
npm error notsup Actual:   {"npm":"10.6.0","node":"v22.0.0"}
```

If `--engine-strict` is not used, the following warning is printed, but `npm install` does not fail:

```js
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'ava@6.1.2',
npm warn EBADENGINE   required: { node: '^18.18 || ^20.8 || ^21' },
npm warn EBADENGINE   current: { node: 'v22.0.0', npm: '10.6.0' }
npm warn EBADENGINE }
```

* And maybe how you think AVA could handle this

Upgrade the following:

https://github.com/avajs/ava/blob/ec1a8d2336e55011aaea966c2273bb86e4dafa88/package.json#L39

However, there might be more work required due to the breaking changes that come with Node 22.

**Comment by arlac77** [comment]
Beside the warning I have no issues running ava on node 22.0.0 (OSX)

**Comment by lenovouser** [comment]
I just tested on a few repositories of ours and **ava** **`v6.1.2`** does work flawlessly with **node** **`v22.0.0`**

**Comment by lenovouser** [comment]
https://github.com/avajs/ava/pull/3328

**Comment by ehmicky** [comment]
Thanks @lenovouser and @novemberborn!

**Comment by ehmicky** [comment]
The same problem is now happening for Node 23.

```
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: ava@6.1.3
npm error notsup Not compatible with your version of node/npm: ava@6.1.3
npm error notsup Required: {"node":"^18.18 || ^20.8 || ^21 || ^22"}
npm error notsup Actual:   {"npm":"10.9.0","node":"v23.0.0"}
```

**Comment by novemberborn** [comment]
@ehmicky sorted.
