### ISSUE TITLE
[tap, @vercel/nft, xo, @ava/test, c8] Some internal modules are deprecated.

### ISSUE THREAD

**Issue by stein2nd** [avajs/ava#3331]
For verification, we temporarily modernised package.json by running 'ncu' and 'ncu -u' under the ‘ava’ installation folder.
![@avatypescript](https://github.com/avajs/ava/assets/531628/fa89a44b-5cde-4b02-b85e-8a358d91507d)

After running 'npm install', several internal modules still show a deprecated warning.

> npm warn deprecated read-package-json@7.0.1:
> This package is no longer supported. Please use @npmcli/package-json instead.
![Pasted Graphic 6](https://github.com/avajs/ava/assets/531628/e4d72286-ba4b-4f53-90df-a139d45cc81f)

> npm warn deprecated rimraf@3.0.2:
> Rimraf versions prior to v4 are no longer supported
![rimraf@3 0 2](https://github.com/avajs/ava/assets/531628/54410b79-b6fe-42de-84cd-e0d0f87fd66e)

> npm warn deprecated inflight@1.0.6:
> This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
![inflight@1 0 6](https://github.com/avajs/ava/assets/531628/d9e54beb-2c6b-4ba0-b1f5-30fec15880da)

> npm warn deprecated npmlog@5.0.1:
> This package is no longer supported.
![@mapboxnode-pre-gyp@1 0 11](https://github.com/avajs/ava/assets/531628/f2edca26-cff2-4dd2-880b-86d97768924c)

> npm warn deprecated are-we-there-yet@2.0.0:
> This package is no longer supported.
![npmlog@5 0 1](https://github.com/avajs/ava/assets/531628/1467008d-a22b-4540-93e7-bee6e7440db3)

> npm warn deprecated gauge@3.0.2:
> This package is no longer supported.
![Pasted Graphic 7](https://github.com/avajs/ava/assets/531628/b31633eb-5242-4ea2-bbec-8993d35a828f)

> npm warn deprecated glob@7.2.3:
> Glob versions prior to v9 are no longer supported
![Pasted Graphic 5](https://github.com/avajs/ava/assets/531628/bee0172e-3297-4554-a22b-bfaa95f6628a)

## System:
 - OS: macOS 14.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 107.72 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 22.2.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.22 - /usr/local/bin/yarn
 - npm: 10.8.0 - ~/.nodebrew/current/bin/npm
## npmPackages:
 - @ava/test: github:avajs/test => 0.0.0 
 - @ava/typescript: ^5.0.0 => 5.0.0 
 - @sindresorhus/tsconfig: ^5.0.0 => 5.0.0 
 - @types/node: ^20.12.12 => 20.12.12 
 - @vercel/nft: ^0.27.1 => 0.27.1 
 - acorn: ^8.11.3 => 8.11.3 
 - acorn-walk: ^8.3.2 => 8.3.2 
 - ansi-escapes: ^7.0.0 => 7.0.0 
 - ansi-styles: ^6.2.1 => 6.2.1 
 - arrgv: ^1.0.2 => 1.0.2 
 - arrify: ^3.0.0 => 3.0.0 
 - c8: ^9.1.0 => 9.1.0 
 - callsites: ^4.1.0 => 4.1.0 
 - cbor: ^9.0.2 => 9.0.2 
 - chalk: ^5.3.0 => 5.3.0 
 - chunkd: ^2.0.1 => 2.0.1 
 - ci-info: ^4.0.0 => 4.0.0 
 - ci-parallel-vars: ^1.0.1 => 1.0.1 
 - cli-truncate: ^4.0.0 => 4.0.0 
 - code-excerpt: ^4.0.0 => 4.0.0 
 - common-path-prefix: ^3.0.0 => 3.0.0 
 - concordance: ^5.0.4 => 5.0.4 
 - currently-unhandled: ^0.4.1 => 0.4.1 
 - debug: ^4.3.4 => 4.3.4 
 - emittery: ^1.0.3 => 1.0.3 
 - execa: ^9.1.0 => 9.1.0 
 - expect: ^29.7.0 => 29.7.0 
 - figures: ^6.1.0 => 6.1.0 
 - globby: ^14.0.1 => 14.0.1 
 - ignore-by-default: ^2.1.0 => 2.1.0 
 - indent-string: ^5.0.0 => 5.0.0 
 - is-plain-object: ^5.0.0 => 5.0.0 
 - is-promise: ^4.0.0 => 4.0.0 
 - matcher: ^5.0.0 => 5.0.0 
 - memoize: ^10.0.0 => 10.0.0 
 - ms: ^2.1.3 => 2.1.3 
 - p-map: ^7.0.2 => 7.0.2 
 - package-config: ^5.0.0 => 5.0.0 
 - picomatch: ^4.0.2 => 4.0.2 
 - plur: ^5.1.0 => 5.1.0 
 - pretty-ms: ^9.0.0 => 9.0.0 
 - resolve-cwd: ^3.0.0 => 3.0.0 
 - sinon: ^18.0.0 => 18.0.0 
 - stack-utils: ^2.0.6 => 2.0.6 
 - strip-ansi: ^7.1.0 => 7.1.0 
 - supertap: ^3.0.1 => 3.0.1 
 - tap: ^19.0.2 => 19.0.2 
 - temp-dir: ^3.0.0 => 3.0.0 
 - tempy: ^3.1.0 => 3.1.0 
 - tsd: ^0.31.0 => 0.31.0 
 - typescript: ~5.4.5 => 5.4.5 
 - write-file-atomic: ^5.0.1 => 5.0.1 
 - xo: ^0.58.0 => 0.58.0 
 - yargs: ^17.7.2 => 17.7.2 
 - zen-observable: ^0.10.0 => 0.10.0

**Comment by novemberborn** [comment]
These are transitive dependencies so not within our control.

We will from time to time update top-level dependencies. If that results in transitive dependencies being updated to non-deprecated versions, great.

**Comment by Ryuno-Ki** [comment]
FWIW Vercel updated https://github.com/vercel/nft/issues/389 which updates to a non-deprecated version of glob (ran into it today as well).
