### ISSUE TITLE
Use the programmatic API in the gulp & grunt plugins

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#345]
Posting here for visibility. Introduced in https://github.com/sindresorhus/ava/pull/279.

https://github.com/sindresorhus/grunt-ava
https://github.com/sindresorhus/gulp-ava

The API doesn't have any docs yet as it's private, but lots of tests to learn from here: https://github.com/sindresorhus/ava/blob/master/test/api.js

**Comment by novemberborn** [comment]
Closing this since there are PRs, but they're effectively blocked by #1043.
