### ISSUE TITLE
Standardize errors in API

### ISSUE THREAD

**Issue by vadimdemedes** [avajs/ava#365]
Currently, `errors` array of `API` instance contains exceptions, rejections and failed tests. As a consequence, items can be different from one another and we have to detect what's what in a loop.

We need to standardize the items in `errors` array, so that it's easily "forEachable" and all items have the same properties.

**Comment by jamestalmage** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by ariporad** [comment]
@sindresorhus, @jamestalmage, @vdemedes: How would you want this implemented? Should everything just get wrapped in an error? A promise? A custom object?

**Comment by vdemedes** [comment]
I haven't thought about that yet, but every item in `errors` should have the same set of properties, so that we can easily output the list of errors at once. So, whether it's a failed test or uncaught exception (which does not have a test assigned to it), the error object should have the same props.

**Comment by jamestalmage** [comment]
Also, `unhandledRejection`.

**Comment by jamestalmage** [comment]
Copying a my suggestion [here](https://github.com/sindresorhus/ava/pull/380#issuecomment-167447244):

> Instead of separate errors and tests arrays, should it just be tests? A test could have a status attached (passed / failed), and all assertions with their respective results. Might be better than just standardizing errors
>   -- @jamestalmage

and a valid counterpoint:    

> we also need to store rejections and exceptions, which are not attached to any test and don't have test title, etc. So storing rejections and exceptions in tests doesn't sound right.
> -- @vdemedes

**Comment by sotojuan** [comment]
What's the status of this?

**Comment by novemberborn** [comment]
@sotojuan it's up for the taking. Maybe we need to bikeshed the standardization details, though we could do that in a PR as well if you have a good idea on where to start.

**Comment by novemberborn** [comment]
While this might improve our code quality, it's not actually preventing any functionality. We've also not made progress on this refactor in over a year. I'm closing the issue, we can deal with it organically when the need arises.
