### ISSUE TITLE
power-assert graph missing from TAP output

### ISSUE THREAD

**Issue by alubbe** [avajs/ava#399]
Thanks for the awesome TAP support, although I suspect it is really all about nyan-cat.
I noticed that piping the output meant losing the awesomeness of power-assert - is that inherent to supporting TAP at all or is there someway we can have flying rainbow cats and nice asserts?

**Comment by jamestalmage** [comment]
Hmm. That should not be true. It's probably a bug from when we moved power-assert rendering to the main thread. I will look into it.

**Comment by alubbe** [comment]
To reproduce, I ran `ava --tap temp/test_temp/*.js | tnyan` on 0.9.1

**Comment by jamestalmage** [comment]
Seems specific to the `tap-nyan` reporter

I had better success with:

```
./cli.js --tap test/fixture/power-assert.js | tap-spec
./cli.js --tap test/fixture/power-assert.js | tap-mocha-reporter nyan
```

**Comment by alubbe** [comment]
Somewhat better, using tap-mocha-reporter I get
```
  t.ok(res.statusCode === 202)-----,
           |                   /\_/\ 
           200                ( ^ .^) 
 228 _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-__,------,
 1   _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-__|  /\_/\  
 0   _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_~|_( x .x)  
     _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_ ""  ""  

  1 passing (4s)
  1 failing

  1) :
     (unnamed error)
```
Now the cat output is part of the assert (not a biggie), but something ate the stack trace. Here is what it looks like with the default reporter:
```
  1 passed  1 failed

  1. foo › bar
    
  t.ok(res.statusCode === 202)
           |                  
           200                
  
  AssertionError: false == true
    at Decorator.concreteAssert (node_modules/empower-core/lib/decorator.js:95:20)
    at Object.decoratedAssert [as ok] (node_modules/empower-core/lib/decorate.js:48:30)
    at Test._callee$ (test/test.coffee:28:5)
    at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:121:21)
    at onFulfilled (node_modules/co-with-promise/index.js:66:19)
```

**Comment by novemberborn** [comment]
@jamestalmage what are our next steps on this?

**Comment by novemberborn** [comment]
The issue here is that our TAP output does not include the `power-assert` graph. I'm not sure if that's even possible within the TAP specification, and how that would interact with say `tap-nyan`. #723 suggests using the TAP v14 specification which may or may not be a prerequisite for resolving this.

See also #324.

**Comment by novemberborn** [comment]
We now do include the formatted values (based on `power-assert`) to the TAP output. It's a proprietary format and thus not very useful, but that's a separate concern.
