### ISSUE TITLE
Rewrite stack traces of AssertionErrors to hide power-assert calls

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#440]
If you do something like:

``` js
t.is(obj.foo().bar(), expected);
```

and `bar` is not a function, you get:

```
TypeError: _rec8._capt(...).bar is not a function
```

I'm not sure if this is something that can be fixed via source-map remapping, or if it can be fixed in `power-assert` somehow.

// @twada @novemberborn

**Comment by novemberborn** [comment]
I'm going to guess that [`source-map-support`](https://github.com/evanw/node-source-map-support) only rewrites the stack, not the error message.

Maybe `power-assert` could recognize the prefixes in type errors and rewrite them? Seems like a long shot though.

@twada?

**Comment by twada** [comment]
Hmm it's a hard problem...

One thing I can think of is that when AVA catches TypeError and its message matches some pattern `_recXX._capt(...)` then seek target line and column from original code.

**Comment by novemberborn** [comment]
@twada hmm you mean get those from the source-map adjusted stack trace? I guess showing the entire line would be better than showing the compiled code.

**Comment by twada** [comment]
@novemberborn Agreed. Showing the entire line would be better.

**Comment by novemberborn** [comment]
I don't believe this is an issue any longer.
