### ISSUE TITLE
Bench - Automate comparing workingtree against latest commit

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#500]
Follow-up to https://github.com/sindresorhus/ava/pull/496

> I think it would be useful with a quick script to automate gathering data from workingtree and the last commit and then run the tests. This would be the most common operation, so would be good to automate it, but we can do that later.

Something like:

``` console
$ node bench/compare-head
```

**Comment by novemberborn** [comment]
I'm sure this idea will come back to us if we're frequently doing bench runs. I'm pruning the list of open issues, and since the lack of this utility hasn't been a problem since the bench tests were introduced I'm closing this one (for now).
