### ISSUE TITLE
Bench - gather more data

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#505]
Using `time ava ...` has some advantages over our current benchmark utility.

Specifically, it allows you to see additional data beyond just how long it took to run (the most important being CPU time and % utilization).

It would be nice to figure out a way to extract that data as well.

It's probably doable just by parsing the last line of output. There may be a module on `npm` that does this for us already.

**Comment by novemberborn** [comment]
I'm sure this idea will come back to us if we're frequently doing bench runs. I'm pruning the list of open issues, and since the lack of this utility hasn't been a problem since the bench tests were introduced I'm closing this one (for now).
