### ISSUE TITLE
ESLint rules for your tests

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#522]
We've started this [ESLint plugin project](https://github.com/sindresorhus/eslint-plugin-ava) with AVA specific rules to make it easier to enforce certain style choices in your tests. We could use some feedback on the rule ideas and help implementing them.

Current rule ideas where we need help: https://github.com/sindresorhus/eslint-plugin-ava/labels/help%20wanted

-

##### Resources

- [Working with ESLint rules](http://eslint.org/docs/developer-guide/working-with-rules)
- [AST Explorer](http://astexplorer.net)

**Comment by smithamax** [comment]
At work we made a rule for mocha, no-only.

Pretty self explanatory, prevents you from committing `test.only(...)` by mistake.

**Comment by sindresorhus** [comment]
@smithamax Yup, that's already planned: https://github.com/sindresorhus/eslint-plugin-ava/issues/5 ;)

**Comment by sindresorhus** [comment]
Closing as the ESLint plugin is very mature now.

**Comment by jfmengels** [comment]
Finally!
