### ISSUE TITLE
Investigate instantiating new API and reporter in --watch

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#533]
#502 resets the API and logger/reporter between runs. Creating fresh instances may be preferable. This would require some sort of code sharing between `cli.js` and `watcher.js` though, since the former sets up the instances and has access to the required CLI flags.

One option would be to pass a callback to `watcher.start()` allowing the watcher to create new API and logger/reporter instances, but leaving the definition in `cli.js`.

**Comment by novemberborn** [comment]
@jamestalmage given your refactoring work what's your take on this?

**Comment by jamestalmage** [comment]
I actually was thinking we could move watcher support into the API itself. That was kind of the thinking behind the `test-run` event. Also, in my refactor branch `lib/ava-files` could probably incorporate some of the file-path processing in `watcher.js` (I'm thinking methods like `makeTestMatcher` and `buildChokidarPatterns`, etc).

I'm thinking of adapting the run method a little:

```js
// new testRun is returned immediately, it may not start receiving events until the current run finishes.

var testRun = api.run(files, {
  runOnlyExclusive: boolean,
  stopCurrentRun: boolean
});

testRun.on('test', ...)

testRun.result.then(function (result) {

});
```

**Comment by sindresorhus** [comment]
I like that idea. Ideally the CLI should just be a tiny wrapper around the API, with CLI only stuff.

**Comment by jamestalmage** [comment]
> Ideally the CLI should just be a tiny wrapper around the API, with CLI only stuff.

Agreed. Our CLI is pretty huge. A lot of it is options processing (parsing the command line and merging with `package.json`). Part of the idea behind #700 is to reduce the amount of options processing API consumers would need to do.

**Comment by novemberborn** [comment]
> I actually was thinking we could move watcher support into the API itself.

The watcher is fairly big though. I wonder if we could make the watcher instantiate its Api. We couldn't before due to how the loggers were coupled.

**Comment by jamestalmage** [comment]
I didn't mean "move all of `watcher.js` into `api.js`". Just expose a way to pass options `{watch: true}` to the API and receive `test-run` events as files change.

**Comment by novemberborn** [comment]
@jamestalmage that sound cool.

**Comment by novemberborn** [comment]
The lack of this refactor hasn't been an issue. Closing this, but I expect we'll do something like this eventually as needs dictate.
