### ISSUE TITLE
Allow other identifiers instead of `t`

### ISSUE THREAD

**Issue by Kl0tl** [avajs/ava#550]
```js
import test from 'ava';

test(assert => {
  const actual = true;
  const expected = false;

  assert.ok(actual === expected);
});
```

yields

```
 1 failed

  1. [anonymous]
  false == true
  AssertionError: false == true
    Test.fn (index.js:7:10)
```

instead of the expected

```
  1 failed

  1. [anonymous]
    
  assert.ok(actual === expected)
            |          |        
            true       false    
  
  AssertionError: false == true
    Test.fn (index.js:7:10)
```

It seems to be because of the patterns used to configure `power-assert` in [lib/enhance-assert.js](https://github.com/sindresorhus/ava/blob/master/lib/enhance-assert.js#L4-L22). Would it be possible to drop the `t.` to allow any identifier ?

**Comment by sotojuan** [comment]
Just by skimming the `power-assert` [docs](https://github.com/power-assert-js/empower#optionspatterns) I don't really see support for "multiple" patterns at once (like a `*` operator), but this is a question for @twada.

**Comment by twada** [comment]
@Kl0tl Sorry, this is a current limitation of CallExpression matching and intended to propose sensible default variable name for consistency. However it's nice to have some callee pattern matching notation like wildcard. Thanks @sotojuan.

**Comment by jamestalmage** [comment]
@Kl0tl - Can you explain why you need this? What prevents you from using `t`?

**Comment by sotojuan** [comment]
I think it was just an idea he had—but so far it doesn't seem like it's feasible.

**Comment by jamestalmage** [comment]
It's feasible, it just isn't really practical (at least not with a wildcard `*`). You almost certainly don't want any method called `same` wrapped with `power-assert` stuff.

We would have to do static analysis for `test()` calls, and then see what variable name was used as the first parameter, and then build new patterns from that. It's certainly doable, but it involves additional AST analysis - which pretty much guarantees a minimum amount of difficulty.

**Comment by Kl0tl** [comment]
Nothing prevents me from using `t` but enforcing this variable name seemed a bit artificial.

**Comment by jamestalmage** [comment]
Just use `t`.

Allowing `*` creates a namespace conflict with outside objects that might have methods with the same name.

We could do static analysis to detect test methods and match the first parameter, but that is going to be unreliable.

**Comment by jamestalmage** [comment]
Echoing what I said here: https://github.com/avajs/ava/issues/551#issuecomment-226838995

I say we just close this. This would require a lot of effort in `power-assert`, `ava-codemods`, and our linter.
