### ISSUE TITLE
Allow destructuring of assertions

### ISSUE THREAD

**Issue by Kl0tl** [avajs/ava#551]
Bound methods would allow to destructure assertions while waiting for something like https://github.com/zenparsing/es-function-bind/issues/5 to happen.

```js
import test from 'ava';

test(({ same }) => {
    same([1, 2], [1, 2]);
});
```

**Comment by sindresorhus** [comment]
Why would you use that? It's more verbose than `t.same()`.

**Comment by Kl0tl** [comment]
For a single assertion yes, but it would be a nicer when multiple assertions are used multiple times in the same test.

**Comment by Kl0tl** [comment]
And while this test is trivial I like how it makes immediately clear what assertions I'm using.

**Comment by sindresorhus** [comment]
We'll consider it, but this honestly feels like just using a new language feature for the sake of it, rather than actually being beneficial. It also IMHO makes tests look more noisy and inconsistent.

> And while this test is trivial I like how it makes immediately clear what assertions I'm using.

I don't see any benefit of knowing that up front.

**Comment by Kl0tl** [comment]
I may have been too used to it. Anyway, it means losing the `power-assert` output while https://github.com/sindresorhus/ava/issues/550 is pending.

**Comment by briandipalma** [comment]
`id-length` warnings in ESLint are triggered by `t` so it would be handy if we could use destructuring as a way to silence those.

**Comment by jamestalmage** [comment]
> id-length warnings in ESLint are triggered by t so it would be handy if we could use destructuring as a way to silence those.

Add `t` to  the `exceptions` property: http://eslint.org/docs/rules/id-length#exceptions

**Comment by jamestalmage** [comment]
I think this should just be closed. Allowing this would require significant effort for `power-assert`, our codemods, and linter. All to allow something of dubious value.

**Comment by briandipalma** [comment]
Any chance we could import the assertion functions from ava so there is no need for the `t` reference?

**Comment by jamestalmage** [comment]
> Any chance we could import the assertion functions from ava so there is no need for the t reference?

No, the `t` reference is specific to that particular test. We keep track of the assertion count, so you can use `t.plan`

**Comment by novemberborn** [comment]
Destructuring `t` for each test you write seems cumbersome.

From the `id-length` description:

> Very short identifier names like e, x, _t or very long ones like hashGeneratorResultOutputContainerObject can make code harder to read and potentially less maintainable.

I don't think that applies to AVA tests.

Closing this because the effort required isn't worthwhile.
