### ISSUE TITLE
Recipe for moving from Mocha

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#558]
Most people already use Mocha and will [need some guidance](https://twitter.com/VanCamp/status/699429484202622977) on how AVA is different and how to achieve the same thing with it. We should have a [recipe](https://github.com/sindresorhus/ava/tree/master/docs/recipes) for this.

Any Mocha converts interested in helping out with this?

**Comment by Lange** [comment]
Thanks so much for reaching out on Twitter and opening this issue! This type of outreach is great to see and feels very welcoming :grin:

@sindresorhus [asked me](https://twitter.com/sindresorhus/status/699554540740194304) to elaborate on my usage of Mocha:

I make heavy use of Mocha's `describe` keyword (and `context`, which is an alias for `describe`). I find it helps me organize large test files into more manageable logical chunks. ([Example](https://gist.github.com/Lange/c3e3311c94597b6e49dd)) I'm currently attempting to migrate [`nodecg/nodecg`](https://github.com/nodecg/nodecg)'s tests from Mocha to AVA, but I'm not sure how to do so in an organized manner. For instance, looking at AVA's 619-line [`test/api.js`](https://github.com/sindresorhus/ava/blob/master/test/api.js), and I'm unsure if having such a large file is a best practice or not. To me, a file of that length feels overwhelming and hard to maintain.

Does it make sense to split an API's tests up by method, one test file for each method? Or is the added overhead of having to maintain that many files more of a burden than maintain a single file of much greater length? If using a single file to test a large API, what is the best way to keep that file organized and easy to come back to?

Having described my issue, I think what I need more than an explicit Mocha recipe is a set of best organizational practices for AVA.

Thanks again for the outreach and for AVA!

**Comment by philmill** [comment]
I'm also coming from frameworks which use `describe` and `context` for organization. I'm wondering if something like [Tape's t.test|https://github.com/substack/tape#ttestname-opts-cb] would help although contexts aren't tests. 

I tried nesting a failing test within an empty test which just passes. 
```javascript
test('parent', (t) => {
  test('child', (tc) => {
    tc.fail();
  });
});
```

This certainly isn't a deal breaker as the features presented with AVA are compelling enough for me. Arguably if AVA forces me to write smaller test files which represent more narrowly focused context, that's probably a good thing.

**Comment by talexand** [comment]
@philmill: Does that still happen if you do something like

```js
test('parent', (t) => {
  test('child', (tc) => {
    tc.fail();
    t.end();
  });
});
```

**Comment by philmill** [comment]
Hey thanks for the suggestion @talexand, but the test still passes (results in infinite loop in call back mode). Also requiring calls to `end()` in callback mode isn't ideal. 

To be clear, I'm not really suggesting this as a solution to organization. It's just the first thing I tried after looking over the available API and searching for others who have tried similar contextual organization in AVA. I'm thinking this isn't how tests are intended to be structured and possibly not on the road map either (which is fine).

**Comment by sindresorhus** [comment]
> Nested Unit Tests: An Anti-Pattern - https://twitter.com/kentcdodds/status/735502601119137793

// @kentcdodds

**Comment by jamestalmage** [comment]
Nice! We should create an  "Avoid beforeEach" recipe and link to that video!
