### ISSUE TITLE
Remove defaults for private code

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#611]
AVA exposes two public interfaces: the CLI and the programmatic API. All other code is private. Currently a lot of the private code has defaults, e.g. `Runner` [can be instantiated without `options`](https://github.com/sindresorhus/ava/blob/eaca9f082fc36add3c905afad3eeca7f0f10cfcb/lib/runner.js#L39).

This tends to happen in tests and causes confusion where code has to be [extra defensive](https://github.com/sindresorhus/ava/blob/eaca9f082fc36add3c905afad3eeca7f0f10cfcb/lib/runner.js#L74) against scenarios that wouldn't occur if defaults were set at the public interface level.

Allowing defaults throughout the code makes it hard to reason about expected values. I'm proposing we  remove defaults from internal code and make our tests more explicit.

Thoughts?

**Comment by vdemedes** [comment]
I think we shouldn't do it, because those libraries/components should be stable on their own. They should not depend on other code passing these arguments correctly.

> Allowing defaults throughout the code makes it hard to reason about expected values.

We can improve our checking of value types, using functions like `Array.isArray()`, so that it's more clear what we're expecting.

**Comment by novemberborn** [comment]
> I think we shouldn't do it, because those libraries/components should be stable on their own

Sure, they'd just require valid options to be passed.

**Comment by novemberborn** [comment]
@avajs/core any thoughts on this?

**Comment by sindresorhus** [comment]
👍 Sounds good.

**Comment by novemberborn** [comment]
We'll just do this when we're touching code. No need to keep the issue open.
