### ISSUE TITLE
Growl / Notifications reporter

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#671]
One thing I still miss from karma is the Growl reporter. When doing TDD I liked to background the actual terminal window and just get the red/green notifications in the corner of my screen. I would only surface the terminal window when something unexpected happened (I wrote a test I expected to fail, and it didn't.  Or, I wrote code to make my latest failing test go green, and it didn't).

Some ideas on how I think messages should look:

**Passing Tests**

> :white_check_mark: 20 tests passed

Keep it simple, no need to list todo's/skipped

**Failing Tests**

> :x: 3 tests failed

Or, maybe show the title if there is only one failing test

> :x: failed test: "ensure it does stuff"

Or, maybe always the title of the first failing test.

> :x: "ensure it does stuff" and 2 other tests failed.

**Internal Errors**

> :warning: There was some problem.

This would be for "no tests received", etc.

---

Also, it might be interesting to make Notifications clickable (I think you can do that), and launch an app according to the `EDITOR` environment variable. We do something similar in XO.

**Comment by sindresorhus** [comment]
https://github.com/csabapalfi/tap-growl ?

**Comment by jamestalmage** [comment]
~~Does our tap output even work in watch mode?~~ Nope: #672

Regardless, I would prefer it be something we do internally. I still want notifications when using the mini reporter.

**Comment by novemberborn** [comment]
If we had a plugin architecture would this be something that could be provided in a separate module?

**Comment by jamestalmage** [comment]
> If we had a plugin architecture would this be something that could be provided in a separate module?

Probably, though I think it's a nice enough feature to just include. When I have good TDD flow, I only need to see the terminal window occasionally.

**Comment by JimmyBoh** [comment]
I agree with @jamestalmage, I'd usually just want the terminal in the background. Plugins would allow greater customization, but built-in notifications does have it's charm. `tap-notify`, `gulp-notify`, and others use [`node-notifier`](https://github.com/mikaelbr/node-notifier), which is a great cross platform implementation of notifications.

**Comment by coodoo** [comment]
Huge bump on this, any update?

**Comment by BarryThePenguin** [comment]
I've just spent some time building a reporter that logs to node-notifier on my [BarryThePenguin/ava/notifier](BarryThePenguin/ava/tree/notifier)

**Comment by coodoo** [comment]
@BarryThePenguin there's a typo in the link, here's [the correct one](https://github.com/BarryThePenguin/ava/tree/notifier) :)

**Comment by cbrwizard** [comment]
Would love this too.

**Comment by cbrwizard** [comment]
Why is this closed? Is this feature added?

**Comment by novemberborn** [comment]
I've been closing issues from the backlog, but not always with an explanation 😄 

I think this is something that can be provided in editor plugins, or otherwise by observing exit codes or through a TAP reporter. It's not something we want in AVA itself at this moment.
