### ISSUE TITLE
A way to submit tests that should fail. 

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#673]
It's really awesome when users report errors by submitting a failing test. I think it would be cool if AVA provided a way to merge those without killing the build.

I am thinking:

``` js
test.failing('this should work, but does not', t => { 
  ...
})
```

The difference from `.skip` would be:
1. It actually runs the test, it just expects the failure.
2. When it fails, it gets listed in red in the final output ("expected failure" or some such message), but the process still exits with 0. This keeps reminding you you've got a problem, but doesn't kill your CI process.
3. If the test passes, that is a failure (you've fixed the problem! hooray! remove the `.failing` flag).

**Comment by novemberborn** [comment]
Should this mandate an issue link? Bit chicken-and-egg but would save you digging through git blame etc.

**Comment by jamestalmage** [comment]
> Should this mandate an issue link?

That's a cool idea. Optional maybe? Not everyone uses AVA for open source projects with issue trackers (though really, that's the target audience for this feature). We could create an `eslint-plugin-ava` rule to make it mandatory.

**Comment by novemberborn** [comment]
Yea maybe not make it mandatory.

How's this?

```js
test.failing('this should work, but does not', t => { 
  ...
}).see('https://github.com/sindresorhus/ava/issues/673')
```

**Comment by jamestalmage** [comment]
:+1: `.see` should throw a helpful message (including the test title) if used without `.failing`.

Also, if we move ahead, we should raise issues on `eslint-plugin-ava` to enforce `use-see-with-failing` and `no-see-without-failing`.

**Comment by novemberborn** [comment]
> .see should throw a helpful message (including the test title) if used without .failing.

Or it's only implemented on the `.failing` return value. We'll see.

**Comment by sindresorhus** [comment]
I think this is a very cool idea, and would hopefully encourage more people to submit failing tests instead of issues. Not sure about `.see`, maybe `.issue` or `.reference`?

**Comment by BarryThePenguin** [comment]
I think this comes back into `todo` and `skip` functionality too. I canrethink and come back with some suggestions

**Comment by jamestalmage** [comment]
In my mind:

- `skip` - implementation that isn't run.
- `todo` - no implementation.
- `failing` - implementation that is run, but expected to fail.

**Comment by novemberborn** [comment]
@sindresorhus ,

> Not sure about .see, maybe .issue or .reference?

`.issue` is quite specific to the GitHub issue tracker, other trackers might use different terminology. Hence `.see` which is easier to type than `.reference` :smile:

**Comment by sindresorhus** [comment]
I'm good with `.see`.

**Comment by vdemedes** [comment]
I'm all for .failing() and .see()!

**Comment by cgcgbcbc** [comment]
Hi, I'm thinking about trying this issue, but it seems a little difficult. Seems that I should make the following changes?

0. add a new `failing` metadata
0. modify [`Runner._addTestResult` ](https://github.com/sindresorhus/ava/blob/master/lib/runner.js#L93): keep the metadata in props.
0. modify [`Runner._buildStats`](https://github.com/sindresorhus/ava/blob/master/lib/runner.js#L108) : add a new count for the expected failing, 
0. seems that in  [`index.js#test`](https://github.com/sindresorhus/ava/blob/master/index.js#L37) the prop is sent to somewhere for output? But I couldn't determine where to modify yet.

I'd be appreciate for any advice!

**Comment by cgcgbcbc** [comment]
For feature 2 seems that reporter must be modified? Is there any better solutions?

**Comment by jamestalmage** [comment]
You should not need to modify the Runner methods.

1. Add the `failing` metadata.
2. Modify the return value of `Test.run` so it flips the return value;
  a. If a synchronous success is returned, flip it to a synchronous failure.
  b. If a synchronous failure is returned, flip it to a synchronous success.
  c. If a Promise is returned, flip it's result.

For now, just modify successes to a an Error that says `Test was expected to fail, but succeeded, you should unmark the test as failing`.

Eventually, we want to modify the reporters so they still list `test.failing` tests in red/yellow (like a normal `test` that fails), but do not cause a non-zero exit code. We can do this in stages though.

**Comment by cgcgbcbc** [comment]
I wonder if just modifying [this](https://github.com/sindresorhus/ava/blob/master/lib/test.js#L189) will work ? But seems that some tests have failed...

**Comment by cgcgbcbc** [comment]
Hi @novemberborn I see this issue was closed in the merge request, but it seems feature 2 is still missing, i.e.

> When it fails, it gets listed in red in the final output ("expected failure" or some such message), but the process still exits with 0. This keeps reminding you you've got a problem, but doesn't kill your CI process.

Should another issue be opened for this?

**Comment by novemberborn** [comment]
@cgcgbcbc oh I missed that! I opened #836 for the `.see()` bit but forgot about the logger output.

To confirm, what we still need is to list the expected failing tests separately in the verbose and mini loggers?

**Comment by cgcgbcbc** [comment]
> what we still need is to list the expected failing tests separately in the verbose and mini loggers

Do you have some recommendation of how to display them?
