### ISSUE TITLE
Display test results in AnyBar

### ISSUE THREAD

**Issue by vadimdemedes** [avajs/ava#676]
Idea born out of #671.

Links:
- https://github.com/tonsky/AnyBar
- https://github.com/sindresorhus/anybar

**Comment by jamestalmage** [comment]
Interesting. 

The downside is that it is not cross platform. I often develop with Webstorm full screen (navbar not visible). Also, you can't send text (i.e. the failing test title, etc).

**Comment by cryptoquick** [comment]
Could it be made an option? It sounds hella cool!

**Comment by novemberborn** [comment]
How would we implement this? I wonder if we should have a plugin architecture with a documented internal API or something, then these things could be build by others.

**Comment by sindresorhus** [comment]
Sounds nice, but I think it's outside the scope of AVA core. Would be better as a recipe or something.

I just added an additional binary to [`anybar-cli`](https://github.com/sindresorhus/anybar-cli) that makes it so you can just do:

```console
$ anybar-exit ava
```

And have AnyBar turn green/red depending on the exit code.

Do you think that would be a good compromise? Also looking for feedback on how the binary works.

https://github.com/sindresorhus/anybar-cli/commit/747a9562d8e5c99701f6f92382444ea4f03a3f8f

**Comment by vdemedes** [comment]
I think solutions/suggestions from both @novemberborn and @sindresorhus are valid. Also, big +1 on plugin system, @novemberborn!

**Comment by sindresorhus** [comment]
I honestly think a plugin system is way too early and not something we should focus on at the moment. When we open up that floodgate there's no way back. I think IMHO it's rather something we should explore post-1.0.0.

**Comment by vdemedes** [comment]
Sure, I think it's the right thing to do, there's too much stuff on our hands at the moment. We need a "future" label for that kind of stuff.

**Comment by sindresorhus** [comment]
> We need a "future" label for that kind of stuff.

:+1: → https://github.com/sindresorhus/ava/labels/future
