### ISSUE TITLE
Show power-assert style errors in error summary

### ISSUE THREAD

**Issue by Qix-** [avajs/ava#689]
Trying to get `t.same()` to work.

The test line I have is

``` javascript
t.same(cc.rgb(), {color: {model: 'rgb', value: [0, 0, 0, 1]}});
```

Seems fairly straightforward.

Here is the output.

```
  ✖ models › rgb
  t.same(cc.rgb(), { color: { model: 'rgb', value: [0, 0, 0, 1] } })
            |
            Object{color:Object{model:"rgb",value:[0,0,0,1]}}


  1 test failed

  1. models › rgb
  AssertionError: {} === { color: { model: 'rgb', value: [ 0, 0, 0, 1 ] } }
    Test.fn (models.js:6:4)
    handleMessage (child_process.js:322:10)
    Pipe.channel.onread (child_process.js:349:11)


npm ERR! Test failed.  See above for more details.
```

Are these not the same objects?

```
{ color: { model: 'rgb', value: [0, 0, 0, 1] } }
```

and 

```
Object{color:Object{model:"rgb",value:[0,0,0,1]}}
```

?

As well, what's up with this?

```
AssertionError: {} === { color: { model: 'rgb', value: [ 0, 0, 0, 1 ] } }
```

What's going on here?

**Comment by Qix-** [comment]
Aha.

`t.same()` isn't checking non-enumerable properties (`color` on the object returned from `cc.rgb()` in the above example wasn't enumerable).

Is this desired?

**Comment by novemberborn** [comment]
> t.same() isn't checking non-enumerable properties (color on the object returned from cc.rgb() in the above example wasn't enumerable).
> 
> Is this desired?

Oh interesting! We use `only-shallow` under the hood which [uses `Object.keys()`](https://github.com/othiym23/only-shallow/blob/11e73050a8ed8e28fd6d6616b9af590db506c83b/index.js#L84).

I'm not sure what the correct behavior is. I imagine non-enumerable properties are often used for internal properties so requiring them to be present in the expected value would be problematic. That would preclude `t.same()` from comparing such properties.

Would be helpful if `power-assert` could list such properties, perhaps with an annotation. E.g.:

```
AssertionError: { color [non-enumerable]: { model: 'rgb', value: [ 0, 0, 0, 1 ] } } === { color: { model: 'rgb', value: [ 0, 0, 0, 1 ] } }
```

@twada?

**Comment by twada** [comment]
I think, the correct behavior of `t.same` is the same as `assert.deepEqual`

> Only enumerable "own" properties are considered. The deepEqual() implementation does not test object prototypes, attached symbols, or non-enumerable properties.

> "Deep" equality means that the enumerable "own" properties of child objects are evaluated also

[Assert Node.js v5.9.1 Manual & Documentation](https://nodejs.org/api/assert.html#assert_assert_deepequal_actual_expected_message)

**Comment by novemberborn** [comment]
@twada yes agreed. I wonder though if the error message could highlight non-enumerables so you stand a better chance of debugging your tests.

**Comment by twada** [comment]
The graph below is a power-assert output.
```
  ✖ models › rgb
  t.same(cc.rgb(), { color: { model: 'rgb', value: [0, 0, 0, 1] } })
            |
            Object{color:Object{model:"rgb",value:[0,0,0,1]}}
```

However, message below is not produced by power-assert (but maybe by `core-assert`) ?
```
1. models › rgb
  AssertionError: {} === { color: { model: 'rgb', value: [ 0, 0, 0, 1 ] } }
    Test.fn (models.js:6:4)
```
Therefore, it's nothing to do with power-assert currently.

It's nice to enhance default assertion message of base assertion library by power-assert, but also I think it's a bit overkill.

**Comment by novemberborn** [comment]
Oh I hadn't realized we had different output. Why wouldn't we repeat the initial output in the error summary? @jamestalmage?

**Comment by Qix-** [comment]
I'm fine with it failing due to non-enumerable properties though the lack of decent output explaining it caused me test-related blockage which I hate D:

Making those stand out would be great, if even it still fails (which is completey okay).

**Comment by novemberborn** [comment]
With #1341 we have much improved value formatting and consistent object comparisons.
