### ISSUE TITLE
Feature Request: Better error messaging for acorn parsing errors when testing React

### ISSUE THREAD

**Issue by dcousineau** [avajs/ava#693]
If JSX code is inlined into a test assertion (e.g. using enzyme's .contains, etc) acorn from the power-assert library fails hard (fails hard enough to kill the `--watch` watcher):

```javascript
test("some test", t => {
    //...
    const wrapper = shallow(<Lesson {...props} />);
    t.true(wrapper.contains(<div className="page-container is-kiosk-mode" />));
});
```

```
/Users/dcousineau/Projects/frontend/node_modules/acorn/dist/acorn.js:945
  throw err;
  ^

SyntaxError: Unexpected token (1:24)
    at Parser.pp.raise (/Users/dcousineau/Projects/frontend/node_modules/acorn/dist/acorn.js:943:13)
    at Parser.pp.unexpected (/Users/dcousineau/Projects/frontend/node_modules/acorn/dist/acorn.js:1503:8)
...
```

The solution to fix this error is a very simple:

```javascript
test("some test", t => {
    //...
    const wrapper = shallow(<Lesson {...props} />);
    const actual = wrapper.contains(<div className="page-container is-kiosk-mode" />);
    t.true(actual);
});
```

It would be nice if AVA could expect and catch this error, prevent it from hard exiting the process, and possibly display messaging like "Unparseable (possibly JSX) code found in your test assertion. Try assigning the code to a variable first then running the assert against the variable".

**Comment by twada** [comment]
@dcousineau Thank you for reporting. That's a power-assert's problem and [I'm trying to solve it](https://github.com/power-assert-js/babel-plugin-espower/pull/13). Sorry for inconvenience... I'll integrate it to AVA as soon as possible when the PR lands. So please stay tuned.

**Comment by novemberborn** [comment]
@dcousineau which version are you using? Could you try with `master`? If it still crashes perhaps you could share an example repo so I can fix the watcher crash? Thanks!

**Comment by babsonmatt** [comment]
Same issue here.  Using ava 0.14.0 and enzyme 2.3.0.
