### ISSUE TITLE
Fix slow serialization of `powerAssertContext`

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#703]
Given: 
```js
t.is(someObj.foo, 'bar');
```

The entirety of `someObj` is going to be serialized and sent across the wire. This is really problematic, since `someObj` can be arbitrarily large, and contain large loops.

In particular, test failures cause huge slowdowns if a Babel `NodePath` object is in the assertion.

I think the proper solution is to move powerAssert messaging back to the child processes, but that comes with a heavy dependency graph.

I know @twada is working hard on reducing that. Just let us know when it's ready so we can switch back.

**Comment by twada** [comment]
@jamestalmage Sorry for my late response :bow: 

I've started a new [power-assert-runtime](https://github.com/twada/power-assert-runtime) modules in a monorepo style.

First alpha version is already published and the first beta version will be released soon, maybe this weekend.
