### ISSUE TITLE
Ability to abort test run

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#710]
Would be useful to have a way to abort the current test run. CLI users can just Cmd+C, but from the API there's currently no way to cancel the test run.

I vaguely remember us talking about something like this being useful for watch mode.
(@novemberborn ?)

An easy solution would be to just have the runner kill the forked processes.
## 

From https://github.com/sindresorhus/atom-ava/pull/8#issuecomment-196472164.

**Comment by novemberborn** [comment]
> I vaguely remember us talking about something like this being useful for watch mode.

Yes, #518. Fair amount of discussion in that issue.

With #78 we'll no longer be running all test files at the same time, so aborting the test run could let current test files run to completion without starting new ones.

**Comment by jamestalmage** [comment]
I want to take this on. #713 is a refactor in preparation for this. I'd appreciate a quick review on that

**Comment by sindresorhus** [comment]
@jamestalmage Assigned.

*(Sidenote: We should use the "assignment" feature more)*

**Comment by jamestalmage** [comment]
I would have, but on mobile

**Comment by sindresorhus** [comment]
The mobile version is completely useless. It misses so many features I don't even bother to use it anymore. Better to use the desktop version on mobile and zoom in and out.

**Comment by novemberborn** [comment]
@jamestalmage from #518 I think we should:

* not start any serial tests that haven't yet been started
* disconnect the reporters from the current run
* as much as possible let the forks run to completion
* but maybe kill the processes to avoid blocking the (upcoming) process pool
