### ISSUE TITLE
Document how to use babel-polyfill to polyfill the test environment

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#727]
AVA does not load polyfills when running tests. This means features like `['foo', 'bar'].includes('foo')` are not available. We should update the [ES2015](https://github.com/sindresorhus/ava#es2015-support) docs to point this out, and add a recipe explaining how to use `babel-polyfill` with AVA.

There should be a caveat to the latter that users shouldn't load `babel-polyfill` unless they _also_ use it in their applications, since the polyfill will apply to both test _and_ source files.

See #263 for background.

**Comment by ahmednuaman** [comment]
Isn't it just about having this in the `package.json`:

```
"ava": {
  "require": [
    "babel-register",
    "babel-polyfill"
  ]
},
```

**Comment by florianb** [comment]
@novemberborn: following Sindre's call to the weapons - i'd like to take this issue if it is still relevant and nobody else is working on it!

**Comment by novemberborn** [comment]
@florianb that's awesome, go for it!

**Comment by florianb** [comment]
@novemberborn - it seems like this issue is invalid, since `Array.include()` is being [part of the standard from ES2016+](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-array.prototype.includes). Ava seems to support ES2017 out of the box, there is no ES2015-sepecific section in the docs anymore.

However, i might be wrong or i also could still add an ES2015-section to the docs. I'd appreciate any hint. 😄

**Comment by novemberborn** [comment]
> Ava seems to support ES2017 out of the box, there is no ES2015-sepecific section in the docs anymore.

ES2017 includes ES2015 😉 

https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md has further details beyond what is in the main README. The issue is that we can only transpile syntax, we don't modify built-ins. It's documented in https://github.com/avajs/babel-preset-stage-4, which is linked to, but we could spell it out better in at least the `babelrc` recipe.

This is why we should still document `babel-polyfill`.

**Comment by florianb** [comment]
Aye - i then will add a proposal for the babelrc. Thanks for clarification.

**Comment by florianb** [comment]
@novemberborn: Change drafted, i would appreciate any feedback and since this is my first contribution i guess there is room for improvement. Thank you very much in advance.
