### ISSUE TITLE
Show `expected` and `actual` if they exist on the AssertionError object.

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#764]
The following:

``` js
import assert from 'assert';
import test from 'test';

test(() => {
  assert.equal(3, 4, 'foo');
});
```

produces this output:

```
   1 failed

  1. [anonymous]
  foo
      Test.fn (test.js:4:9)
```

If you do not specify a message, you get a more helpful `3==4` in the message. If we get an AssertionError that was not enhanced by `power-assert`, we should be displaying (at a minimum) those two properties.

Mocha's output (for reference):

```
  0 passing (9ms)
  1 failing

  1)  foo:

      AssertionError: foo
      + expected - actual

      -3
      +4
```

**Comment by jamestalmage** [comment]
This would be really helpful for our eslint plugin tests, which rely on eslints [`RuleTester`](https://github.com/eslint/eslint/blob/master/lib/testers/rule-tester.js#L399-L413) utility. It throws plain old assertion errors.

**Comment by sindresorhus** [comment]
:+1: I got hit by the bad output of a `RuleTester` failure the other day too.

**Comment by danilosampaio** [comment]
@jamestalmage @sindresorhus  i'm a beginner at AVA, so if nobody has started yet i could do it.

**Comment by sindresorhus** [comment]
@danilosampaio Go ahead :)

Join [AVA chat](https://gitter.im/sindresorhus/ava) if you have any questions.

**Comment by novemberborn** [comment]
Let's continue this in #1277.
