### ISSUE TITLE
Remove timestamp from non-watch test runs

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#775]
```
  ✔ execa() (371ms)
  ✔ input can be a Stream (173ms)

  17 tests passed [15:51:49]
```

It's useful for `--watch`, but when running tests normally I don't see the value.

@novemberborn Thoughts?

**Comment by novemberborn** [comment]
You're right, it's pretty meaningless outside of `--watch`. I guess I hadn't considered that scenario.

**Comment by jamestalmage** [comment]
It does remind you how long it's been since you last ran the tests. Minimally useful, but not very harmful to leave it as is.

I'm indifferent on this really.

**Comment by sotojuan** [comment]
As far as I can tell `lib/reporters/mini.js` doesn't know if it's reporting on a watcher test—what would be a good way to pass down that data without coupling stuff too much?

**Comment by novemberborn** [comment]
Both the cli and the watcher call `logger.finish()`. We could pass a second argument indicating whether time output is desired.
