### ISSUE TITLE
t.throws not that helpful when the message assertion does not match

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#779]
```js
test(t => {
	t.throws(() => {
		throw new Error('foo');
	}, 'bar');
});
```

output:

```
   1 failed

  1. [anonymous]
  foo
      Test.fn (test.js:61:4)
```

It should show both the expected and actual message. (currently just shows the actual message `foo`).

**Comment by novemberborn** [comment]
We should implement `t.throws` ourselves, rather than wrapping `assert.throws`.

**Comment by novemberborn** [comment]
Closing in favor of #1047. See also #661.
