### ISSUE TITLE
Flag to show pending/hanging tests.

### ISSUE THREAD

**Issue by radiovisual** [avajs/ava#781]
I have a use case where I am testing functionality that sometimes causes the test run to hang. When a test causes the terminal to hang, I don't always know what test is hanging unless I go through the very tedious and manual process of using the `--verbose` flag and comparing my tests one-by-one with AVA's  output.

It would be awesome If I could pass some sort of flag/option (or the `--verbose` option is modified to be even more verbose), then I could see which tests are currently pending, which would narrow down my search to find the hanging test.

**Comment by sindresorhus** [comment]
Could you share such test? Just curious what makes it hang.

**Comment by radiovisual** [comment]
Sure. Right now I am troubleshooting a part of my application, and I am writing a test to ensure that an error is thrown, I have the following test, which sometimes causes the test run to hang in the terminal:

```js
test('should throw when local-config.js is not found', t => {
	const birdwatch = new Birdwatch({server: false, testData: false}).feed('testfeed');
	t.throws(birdwatch.start(), Error('local-config.js file not found.'));
});
```

It took me a little while to figure out which test was causing the test run to hang, which is why it would have been a big time-saver to have some sort of flag that could help narrow down the pending/hanging tests.

**Comment by sindresorhus** [comment]
You're using `t.throws` incorrectly? Is that intentional? What exactly made it hang?

**Comment by radiovisual** [comment]
Yes, in that example I am using `t.throws()` incorrectly, which does cause the test run to hang. However, I wasn't able to narrow down my problematic test until after I had gone through a pretty tedious test-by-test comparison to figure out which test was hanging.

Though, I am still working to find the exact bug/reason why the application is hanging in my tests.

**Comment by radiovisual** [comment]
**Update**: The only reason I can gather that makes that particular test to hang is the incorrect usage of `t.throws()`. When I use `t.throws()` correctly, the test run no longer hangs.

**Comment by jamestalmage** [comment]
Would #583 be enough to solve your problem?

**Comment by sindresorhus** [comment]
> The only reason I can gather that makes that particular test to hang is the incorrect usage of t.throws()

Too bad this happened now. If you'd used master (not that you should have), AVA would have warned you about it: https://github.com/sindresorhus/ava/commit/3201b1b4ff80ff75f0e1c288ca7da22f92c9b814

**Comment by radiovisual** [comment]
yeah, I recall seeing that a warning for improper use of `t.throws()` was merged into master not long ago, so as soon as I realized the problem, the first thought that came to mind was how that feature would have helped me. 😄

**Comment by radiovisual** [comment]
@jamestalmage , I do think that #583 would be enough to solve the problem, as long as a "hanging" test would be classified by AVA as a "pending" test. 👍

**Comment by jamestalmage** [comment]
Closing in favor of #583. (Hanging === Pending)
