### ISSUE TITLE
Idea: expectation generators.

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#784]
I'm using this construct in my code right now:

``` js
function *expectations(expected) {
  yield * expected;
};

test(t => {
  t.plan(3);
  const expected = expectations(['foo', 'bar', 'baz']);

  return someObservable()
    .forEach(val => t.is(val, expected.next().value)); // foo, then bar, then baz
});
```

This works pretty well, the only minor frustration is that I need to update two places if I want to add an expected value - and I need to count correctly (easy here - picture something more complex).

I wonder if we couldn't simplify this, to just:

``` js
test(t => {
  // expectation generator is just built in.
  const expected = t.expectations(['foo', 'bar', 'baz']);

  return someObservable()
    .forEach(val => t.is(val, expected.next().value)); // foo, then bar, then baz
});
```

We provide a generator for an expectation iterator. The added bonus is that we ensure the expectations are consumed completely upon completion of the test. No messing with `t.plan` - just list your expectations and be done!

UPDATE: I've been asked to provide a better, non-observable example. So... EventEmitters!

``` js
test.cb(t=> {
  const expectations = t.expectations(['foo', 'bar', 'baz']);

  var emitter = someEventEmitter();

  emitter.on('data', data => {
    t.is(data.value, expectations.next().value);
  });

  // I don't need t.plan, the number of arguments passed to `t.expectations` serves as a sort of plan
  emitter.on('end', t.end);
  emitter.on('error', t.end);
});
```

**Comment by sindresorhus** [comment]
I like the proposal and have had similar needs in the past. Let's keep this open for a while to gather feedback. We should be very careful about introducing new API's.

**Comment by sindresorhus** [comment]
@jamestalmage Can you also include an example not using Observables? Want to tweet about this issue, but most aren't familiar with Observables.

**Comment by jfmengels** [comment]
How would you test that the observable only has those values and then ends? (not that familiar using Observables, so correcti me if I'm saying something stupid).

```js
test(t => {
  // expectation generator is just built in.
  const expected = t.expectations('foo', 'bar', 'baz', 'NOOOOOOO');

  return someObservable()
    .forEach(val => t.is(val, expected.next().value)); // foo, then bar, then baz, and should not reach NOOOOOOO
});
```

**Comment by jamestalmage** [comment]
`observable.forEach` returns a promise for when the Observable has been consumed, so AVA will wait until it's consumed before finalizing the test. If you return an Observable directly, AVA will use `observable-to-promise` to accomplish the same thing. (`observable-to-promise` just uses `forEach` internally)

You can think of an Observable as an Array that arrives over time. It has lots of the same methods (forEach, map, etc). 

We would track the `expected` iterable, and make sure it was empty

**Comment by jfmengels** [comment]
> We would track the `expected` iterable, and make sure it was empty

That would be nice, but it sounds pretty hard or not user-friendly. Example:

```js
[1, 2, 3].forEach(function(i) {
  test(t => {
    const expectedIfOne = t.expectations('foo', 'bar');
    const expectedIfNotOne = t.expectations('foo', 'bar', 'baz');

    const expected = i === 1 ? expectedIfOne : expectedIfNotOne;
    return someObservable()
      .forEach(val => t.is(val, expected.next().value));
    });
});
```

I may be overthinking this, but it seems to me that in this case, if you would track the created expectations, without being able to tell whether the generator was started (is it possible? Maybe with some Babel plugin), you'd fail the test because one of the expectations was not emptied.

Would it not be simpler and friendlier if you had a method to compare a function to compare observable to an array? Or is that too narrow a use case?

Example: (maybe add an `async`/`return` somewhere?)

```js
test(t => {
  t.isObservableEqualToArrayFunction(someObservable(), ['foo', 'bar', 'baz']);
});
```

**Comment by jamestalmage** [comment]
> Would it not be simpler and friendlier if you had a method to compare a function to compare observable to an array? Or is that too narrow a use case?

I think it's too narrow. Using the proposed solution, you do not necessarily have to pass the output of the iterable directly into an assertion. Here's another potential usage:

```js
test.cb(t=> {
  const expectations = t.expectations(
    {flagA: true, flabB: true, value: 'foo'},
    {flagA: false, flabB: true, value: 'bar'},
    {flagA: true, flabB: false, value: 'baz'},
  );

  var emitter = someEventEmitter();

  emitter.on('data', data => {
    const expected = expectations.next().value;

    if (expected.flagA) {
       t.is(data.A, XXX);
    }
    
    if (expected.flagB) {
       t.is(data.B, XXX);
    }

    t.is(data.value, expected.value);
  });

  emitter.on('end', t.end);
  emitter.on('error', t.end);
});
```

In the above example, as you add expectations that may or may not trigger assertions, you can see how it gets more difficult to count up what your `plan` should be. By using ensuring `expectation` is exhausted, you don't have to. That's a real big part of the benefit to this.

For your example regarding generated tests, you could just do this:

```js
[1, 2, 3].forEach(function(i) {
  test(t => {
    const expectations = i === 1 ? ['foo', 'bar'] : ['foo', 'bar', 'baz'];
    const expected = t.expectations(...expectations);
    return someObservable(i)
      .forEach(val => t.is(val, expected.next().value));
    });
});
```

Or better yet, when we implement macros

```js
function macro(t, ...expectations) {
  const expected = t.expectations(...expectations);
  return someObservable()
      .forEach(val => t.is(val, expected.next().value));
}

test(macro, 1, 'foo', 'bar');
test(macro, 2, 'foo', 'bar', 'baz');
test(macro, 3, 'foo', 'bar', 'baz');
```

**Comment by jfmengels** [comment]
> you do not necessarily have to pass the output of the iterable directly into an assertion

Ok, makes sense. But to me, there's only limited gain either syntax or assertion wise, compared to for example something like this.

```js
test(t => {
  const expected = ['foo', 'bar', 'baz'];

  return someObservable()
    .forEach(val => t.is(val, expected.shift()));
});
```

Not fond of it myself, but it's shorter, potentially easier for users not used to generators (will admit I'm one of them), as you don't have to remember to call both `next` and `value` (less verbose and error-prone).
The only gain I see with `expectations` (and I would like to see more if you see others) is that it's possible to track on AVA's side whether the generator has ended at the end of the test.

I think that what I would like to see is an API that does not force the user to learn potentially new concepts (generators), and simplifies the verbosity of the test. Maybe something like `isObservableEqualToArrayFunction` solves 90% of the cases, and that'd be pretty fine IMO.

Note: Both methods pass but should fail if you have this in your observable
```
---foo---bar---baz---undefined--undefined--
```

(Sorry if I sound like a nagger/pessimist, not my purpose)

> For your example regarding generated tests, you could just do this

Yes, though that was a simple case. I assume it can get more complicated.

> Or better yet, when we implement macros

Now this is better :D and solves the use-case I proposed :+1:

**Comment by jfmengels** [comment]
```js
t.validateArrayLikeThing = function (actual, _expected, validator=(x, y => t.deepEquals(x, y))) {
  var expected = transform(_expected); // transform expected in whatever's convenient

  return promisify(actual)
    .forEach(val => validator(val, expected.shift()))
    .then(() => t.is(expected.length, 0, `There were less items in ${actual} than expected`));
}
```

In the case of @jamestalmage example with a complex validator:
```js
const validator = data => {
    const expected = expectations.next().value;

    if (expected.flagA) {
       t.is(data.A, XXX);
    }

    if (expected.flagB) {
       t.is(data.B, XXX);
    }

    t.is(data.value, expected.value);
};

t.validateArrayLikeThing(emitter, expectations, validator);
```

It's bigger than what was originally proposed (or what we're used to in AVA), but it seems more useful IMO, and more in the spirit of what is actually wanted.

**Comment by jamestalmage** [comment]
> The only gain I see with expectations (and I would like to see more if you see others) is that it's possible to track on AVA's side whether the generator has ended at the end of the test.

Well, in a sense, you are correct, that's the only gain. But I think that is a pretty big one:

```js
test.cb(t => {
  t.plan(3);
  var emitter = someEmitter();
  var fooExpectations = ['fooA', 'fooB'];
  
  emitter.on('foo', data => t.is(data, fooExpectations.shift());
  emitter.on('bar', data => t.is(data, 'bar');
  emitter.on('end', t.end);
});
```

The above example is problematic - I need to count up the number of listeners tied to each event, and how many times they will be triggered, and add them all up. Easy above, harder as the complexity of your test grows. Also, `plan` can't tell you the right events got called. What if the `bar` event just triggered three times, followed by `end`? The test still passes (but definitely not why I thought). To make my test foolproof, I need to modify how I end:

```js
emitter.on('end', () => {
  t.is(fooExpectations.length, 0);
  t.end();
});
```

That should work, right! Oops no, I need to update my assertion plan to `4`! 😏 

My point is that I am often trying to shoehorn `plan` to mean "All these expectations got met", and there are plenty of situations where that leads to verbose boilerplate, and plenty of ways to mess it up.

> I think that what I would like to see is an API that does not force the user to learn potentially new concepts (generators)

They wouldn't be exposed to generators. Just the `iterator` API, which is just the `next()` method. We would almost certainly use Array.shift to implement the iterator (I used generators as an example of what I have to do now).

> RE: `validateArrayLikeThing`

I don't see how `validateArrayLikeThing` knows when it's done and it's time to end the test. How does it know there is more data available to rerun the validator?

**Comment by jfmengels** [comment]
> I don't see how `validateArrayLikeThing` knows when it's done and it's time to end the test. How does it know there is more data available to validate against?

I thought about making `validateArrayLikeThing` return a Promise, so you could either return it and append a `.then()` or use `await` (`await validateArrayLikeThing(...); // then check stuff`).

> Well, in a sense, you are correct, that's the only gain. But I think that is a pretty big one

Okay, with your example, it's starting to make sense I think. Thanks for your patience on this :)

**Comment by jamestalmage** [comment]
> Note: Both methods pass but should fail if you have this in your observable
> `---foo---bar---baz---undefined--undefined--`

Yeah, our iterator should detect if they call `next()` and get back `{done: true}` (they never should - that's an error meaning they tried to call next to many times - so their plan is off). We could extend the iterator API to give them a `hasNext()` implementation like Java (I much prefer the Java iterator style).

**Comment by jamestalmage** [comment]
I just decided that using a spread argument is a bad idea. Instead `t.expectations` will take a single argument that is [iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) (doesn't have to be an array).

 I went through and updated all the discussions above so they use the array form

**Comment by jamestalmage** [comment]
I do think @jfmengels validator idea is pretty cool. I have some different ideas on how to do it though. I will open another issue.

**Comment by jfmengels** [comment]
> We could extend the iterator API to give them a hasNext() implementation like Java

I think something like this would do the trick:

```js
t.expectations = function *expectations(expected) {
  expected.forEach(function() {
    yield * expected;
  });
  throw new Error('Too many items');
};
```

**Comment by BarryThePenguin** [comment]
I know RxJS has tried to solve this a [couple](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/testing.md) of [times](https://github.com/ReactiveX/rxjs/blob/master/doc/writing-marble-tests.md)

I really like the idea of having enumerable expectations.

**Comment by jamestalmage** [comment]
See #795 for a more complex idea for building validators.

**Comment by novemberborn** [comment]
Like with spies, shouldn't this be something that can be provided through a third-party package?
