### ISSUE TITLE
[Blocked]: Use cache-require-paths

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#794]
We have discussed [`cache-require-paths`](https://www.npmjs.com/package/cache-require-paths) before and rejected it. At the time, the rejection reason was two fold: 
1. Caching that data for any length of time (i.e. between test runs) will cause problems if directory structures change in `node-modules` (because of `npm install`), so we really don't want to cache between test runs.
2. Trying to use a modified version that only applied to a single test run did not make any sense, because we launch all the child processes at the same time - and there's no good way to share require data at that point (tests do all their `require`-ing up front - so they all basically need the cached data at the beginning - before any one test has had the time to create it).

`2` is about to change with test batching. We could conceivably generate cached require paths for the first run, and pass that data along to subsequent runs.

There is a very real possibility this won't even produce that much of a speedup. I suspect much of the speedup advertised by `cache-require-paths` is for server processes that are not necessarily launched in quick succession. AVA child processes will be requiring the same modules over and over in quick succession, as each child process is likely to need mostly the same modules. Most operating systems cache the state recently accessed file-system resources, so AVA likely will not see as pronounced an improvement. Still, I think it's worth investigating.

Any work on this is blocked until batching has landed.

**Comment by novemberborn** [comment]
Batching, as it were, has landed. Still I imagine there are easier performance wins than this. Closing to clean up the issue backlog.
