### ISSUE TITLE
Validator callbacks

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#795]
Assumes we implement #784 (you should read that thread first).

---

Assuming we implement expectation iterators as described in #784, you could do something like this:

```js
function validator(iterator, fn) {
  return (...args) => fn(iterator.next().value, ...args)
}

test.cb(t => {
  var expectations = t.expectations([
    'start',
    {
      event: 'foo',
      message: 'foo1'
    },
    {
      event: 'bar',
      message: 'bar1'
    },
    { 
       event: 'foo',
       message: 'foo2'
    }
  ]);
  
  someEventEmitter()
    .on('start', validator(expectations, expected => t.is(expected, 'start')))
    .on('foo', validator(expectations, (expected, message) => {
      t.is(expected.event, 'foo');
      t.is(message, expected.message)
    })
   .on('bar', validator(expectations, (expected, message) => {
      t.is(expected.event, 'bar');
      t.is(message, expected.message)
    })
    .on('end', t.end);
});
```

This does some cool stuff.
 - It gets you an alternative form of assertion planning that's nicer in some ways than `t.plan` (see #784 for that discussion)
 - It provides planning that also takes into account which events should occur in which order.

Still, it's pretty freaking verbose.

-- 

We *could* improve it even more. A lot of the verbosity comes from specifying that `type` property, and checking it inside each event handler.

```js
// reusable validator definition
const definition = {
  start() {},
  foo: (t, expectation, message) => t.is(message, expectation),
  bar: (t, expectation, message) => t.is(message, expectation)
};

test.cb(t => {
  const validator = t.buildEventValidator(definition)
    .start()          // each line here adds an expectation
    .foo('foo1')     // the arguments here are expectations, which get passed to the definition funcs
    .bar('bar1')
    .foo('foo2')
    .build();        // when we are done setting up expectations, we build the validator

  someEmitter()
    .on('start', validator.start) // the built validator is just a hash of event handlers
    .on('foo', validator.foo)     // just pass it's properties to the emitter
    .on('bar', validator.bar)
    .on('end', t.end)
}
```

**Comment by jamestalmage** [comment]
This sells me on #784 even more.

While I'm not sure this is worthy of making a core part of AVA (emitter testing is a little niche). It would be pretty simple to implement as a separate module if #784 existed.

```js
import buildValidator from 'build-ava-validator';

const def = {...};

test.ct(t => {
  const validator = buildValidator(t, def)
    .start()
    .foo()
    // ...
});

**Comment by jamestalmage** [comment]
I considered making the `this` value `t`:

```js
const validatorDefinition = {
  foo(expected, message) {
    this.is(message, expected)
  }
}
```

But it might be nice to have helper methods on your definition

```
const definition = {
  foo(t, expected, data) {
    t.true(someSpecialConditionForFoo);
    _helper(t, data);
  },
  _helper(t, data) {
    // perform assertions shared across multiple event types. 
  }
}; 
```

**Comment by sindresorhus** [comment]
I like how it simplifies event testing, but I honestly very rarely test events. And wouldn't this be better solved with Observables?

**Comment by jamestalmage** [comment]
https://github.com/avajs/ava/issues/795#issuecomment-215252710

> While I'm not sure this is worthy of making a core part of AVA (emitter testing is a little niche). It would be pretty simple to implement as a separate module if #784 existed

**Comment by jamestalmage** [comment]
> And wouldn't this be better solved with Observables?

EventEmitters emit multiple named events. Observables only emit one. In a sense, EventEmitters are essentially a bag of Observables with a common completion. 

This could help you test the interleaving of events between two different Observables. Same idea as above, but pass the validator functions to two different Observables, instead of registering with two different event names on a single emitter.

> but I honestly very rarely test events

Would you if it were easier to do?

**Comment by sindresorhus** [comment]
> EventEmitters emit multiple named events. Observables only emit one. In a sense, EventEmitters are essentially a bag of Observables with a common completion.

I'm aware, but I was thinking just simply converting each event to an Observable and then have all the power of Observables for testing.

> Would you if it were easier to do?

Badly phrased. I meant I rarely have the need to, as I almost never use events.

**Comment by jamestalmage** [comment]
Yeah - I'm not sure how you test interleaved Observables though. I've seen the marble diagram type tests, but that seems convoluted to me for most scenarios (could be a lack of experience).

I really don't think there's any reason for this idea to end up in core. If we do it, it could totally be a separate module that just relies on #784.

> Badly phrased

I figured that's what you meant.

**Comment by novemberborn** [comment]
> I really don't think there's any reason for this idea to end up in core.

Going ahead and closing this then 😄
