### ISSUE TITLE
We should have some tests for our benchmark scripts

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#816]
https://github.com/sindresorhus/ava/pull/744#issuecomment-210477223

**Comment by Roshanjossey** [comment]
@jamestalmage: I know it's been some time since this issue was opened but I'd like to fix this.

I looked in to #744. I might need some help in understanding where tests should go.

Please gimme some information on how to take this forward

**Comment by novemberborn** [comment]
@Roshanjossey we'd like to have tests for https://github.com/avajs/ava/blob/master/bench/compare.js to start with. These could go inside a `test/bench` directory. Looking at the script it may need some refactoring though. Ideally the logic sits in another module that is passed a file path, which means you can test it against some fixtures. Right now it expects results to be in the `bench` directory which isn't ideal for unit testing (https://github.com/avajs/ava/blob/fa9abecad516b56391070c6324dc01110833da9f/bench/compare.js#L7).

**Comment by Roshanjossey** [comment]
@novemberborn, thanks for your reply. I'll start working on this and reach back to you if I need any more information from you.
