### ISSUE TITLE
test.afterEach() is not called on failing tests

### ISSUE THREAD

**Issue by jluchiji** [avajs/ava#819]
## Description
`test.afterEach` hook is not called on failed tests, which causes some failed tests to hang. For example:

```
const test = require('ava');
const mongodb = require('mongodb');

test.beforeEach(async t => {
  t.context.db = await mongodb.connect('mongodb://localhost:27017/test');
});

test(async t => {
  throw Error('foo');
});

test.afterEach(async t => {
  await t.context.db.close(true);
});

```

The above code would cause ava to hang indefinitely instead of reporting test failure.

## Environment

```
Node.js v4.4.2
darwin 15.5.0
```

**Comment by jfmengels** [comment]
That is by design, but you might want to look at https://github.com/sindresorhus/ava/pull/806 (or the issue linked there). It just landed in master (not on `npm` yet), it adds a `.always` attribute to `test` (`test.afterEach.always(...)`) that will get run even if the tests fail.

**Comment by jluchiji** [comment]
Thanks! Is there any ETA as to when this feature will make its way to `npm`?

**Comment by jluchiji** [comment]
BTW, to those who encounter the same issue, my current workaround is the following:

```

test.beforeEach(async t => {
  t.context.db = await mongodb.connect('mongodb://localhost:27017/test');
  t.context.timeout = setTimeout(() => t.context.db.close(true), 10000);
});

test.afterEach(async t => {
  clearTimeout(t.context.timeout);
  await t.context.db.close(true);
});

```
That is, assuming your tests take less than 10s to run.

**Comment by jluchiji** [comment]
Updating to the newest version and using the `always` modifier fixed this issue. Closing.
