### ISSUE TITLE
ANSI colour codes are leaking

### ISSUE THREAD

**Issue by gajus** [avajs/ava#823]
```sh
$ ava --version
0.14.0
```

## Description

`ava ./tests --watch ./**/*.js` command makes the type cursor invisible in iTerm2 (OSX).

![ud2pdtb7yh](https://cloud.githubusercontent.com/assets/973543/15161829/88fa15a8-16f7-11e6-87c1-46554063f564.gif)

**Comment by novemberborn** [comment]
I wonder if it's related to the Babel stack trace being spit out. Any chance you have a reproduction of this in a repo?

Watcher log output has changed a lot in `master`, could you try with `npm install sindresorhus/ava#master`?

**Comment by sindresorhus** [comment]
It might also be [`restore-cursor`](https://github.com/sindresorhus/restore-cursor) not being able to catch the error. (It's using the [`exit-hook`](https://github.com/sindresorhus/exit-hook) module for that).

**Comment by jamestalmage** [comment]
@gajus - Which Node version are you using? I've noticed problems with streams not flushing entirely before `process.exit` much more on Node 6 than previous versions (that behavior has never been guaranteed, but it's much more problematic now).

**Comment by gajus** [comment]
> I wonder if it's related to the Babel stack trace being spit out. Any chance you have a reproduction of this in a repo?

@novemberborn Sorry, that was a code in a private repository. I have not had a chance to test it using `#master`.

> 6.1.0

@jamestalmage v6.1.0.

**Comment by jamestalmage** [comment]
Try in Node 5 and see if you have the same problem.

> Sorry, that was a code in a private repository.

Creating an [MCVE](http://stackoverflow.com/help/mcve) without proprietary/closed source code is the best way for us to troubleshoot the issue.

**Comment by novemberborn** [comment]
Watch mode no longer crashes when Babel compilation fails, which means that the cursor can be restored when exiting watch mode.
