### ISSUE TITLE
Enhance .failing output with issue links

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#836]
#673 introduced `test.failing()` to describe tests that should fail. When writing those tests it's good practice to link to an issue tracking their eventual resolution.

Rather than adding a `.see()` helper as originally proposed we're now looking to support hyperlinks in code comments that precede the `test.failing()` declaration. These should be extracted using a Babel helper and output in the verbose and mini reporters.

See discussion: https://github.com/sindresorhus/eslint-plugin-ava/issues/110#issuecomment-219374863

**Comment by jamestalmage** [comment]
I will tackle the Babel transform. @cgcgbcbc is working on the logger output in #837.

**Comment by novemberborn** [comment]
Rather than extracting links, should we extract any immediately preceding comment?

**Comment by jamestalmage** [comment]
That could get verbose. Part of the idea is to make it clickable in iTerm. You can always click into the file and read comments directly

**Comment by novemberborn** [comment]
It'll still be clickable.

**Comment by jamestalmage** [comment]
My thought was to keep it succinct. For large projects, you may have a number of known issues that are long lived. I want provide just enough output to nag people into action, without flooding the console with stuff they will likely ignore.

**Comment by sindresorhus** [comment]
Yup, only the link.

**Comment by novemberborn** [comment]
Rather than adding more Babel transforms, we should solve this through linting, i.e. https://github.com/avajs/eslint-plugin-ava/issues/110.
