### ISSUE TITLE
Cut down on dependencies?

### ISSUE THREAD

**Issue by billyjanitsch** [avajs/ava#841]
## Description

AVA has grown to be really powerful -- certainly more powerful than Mocha (process isolation/concurrency, transpiling, etc.) -- but given that it brands itself as minimal and fast in comparison to Mocha's bloatedness, I was surprised by the following:

Clean installs of Mocha and AVA take up 1.2 MB and 17.6 MB, respectively*. On my machine, Mocha's install took 2.808s while AVA's took 50.627s (clearing npm cache before each). This is overwhelmingly due to dependencies, of which Mocha has 20 and AVA has 467 (recursively). In short, AVA is roughly 15x bigger, 18x slower to install, and has 23x more dependencies -- a surprisingly large difference.

As AVA approaches v1, it might be worth considering whether all of its dependencies are necessary, and whether there are leaner alternatives. Perhaps some of the larger ones that only cater to certain use cases could be pulled into optional plugins? (Although I suspect the core team would prefer to avoid additional config.)

Thanks for your work on AVA -- it's been exciting to follow its progress!

*Some of AVA/Mocha's dependencies can be deduped by npm@3, but, in my experience, there hasn't been much dependency overlap in typical projects, and in any case it's still adding a lot of work to npm's dependency solver.

## Environment

OSX 10.11.5
node 5.11.1
npm 3.9.0

**Comment by jamestalmage** [comment]
See #369

**Comment by billyjanitsch** [comment]
Yikes, sorry, I missed this while searching -- I was surprised that it hadn't been brought up. Thanks!

**Comment by gluons** [comment]
Agree. I try to play with **AVA**. After installing, I face the very large dependencies. It shocked me. 😱 
**Mocha** is currently lighter than **AVA**.

Hope **AVA** be lighter. Regards. 😃

**Comment by sindresorhus** [comment]
@gluons Most of it is Babel, which is unfortunately out of our control. Try https://github.com/yarnpkg/yarn instead of npm. It's a lot faster.

**Comment by gluons** [comment]
@sindresorhus Yeah! You're right. I currently use it. It's really awesome for me. 😄
