### ISSUE TITLE
Switch to disable color output to console

### ISSUE THREAD

**Issue by otakusid** [avajs/ava#843]
it would be good to have a switch that disable colors in console output f.e **--no-color**

it was useful when **ava** used under some CI systems f.e. **TeamCity** and color coding showed as plain text in test reports.

![pasted image at 2016_05_18 03_54 pm](https://cloud.githubusercontent.com/assets/2751715/15361598/d0cd7b6c-1d1a-11e6-9aba-b4e602f7aeb4.png)

**Comment by sindresorhus** [comment]
Yeah, it should already work, but trying it out now it doesn't. We'll look into it.

Also, please open up an issue on https://github.com/chalk/supports-color with the output of running `node -p 'process.env'` in TeamCity so we can try to disable colors automatically for you.

**Comment by otakusid** [comment]
done :)

https://github.com/chalk/supports-color/issues/37

**Comment by vdemedes** [comment]
Submitted a PR to fix this - https://github.com/chalk/supports-color/pull/39.

**Comment by vdemedes** [comment]
Oh damn, did not see the "good for beginner" badge... Sorry!

**Comment by sindresorhus** [comment]
@vdemedes No worries. The beginner badge is for fixing the `--no-color` flag in AVA.

**Comment by simonbuchan** [comment]
Obv. this should still be done, but is the OP using TeamCIty 9.1+? Colored output was supported with https://youtrack.jetbrains.com/issue/TW-23760

**Comment by ThomasBem** [comment]
As far as I can tell this issue has been made available again because of lack of activity in #1104. So I would like to see if I can finish up what @thinkimlazy started on.

**Comment by novemberborn** [comment]
@ThomasBem go for it!

**Comment by thinkimlazy** [comment]
@ThomasBem great! I think u need to check if main proccess has `color` flag disabled, then pass it to child test proccesses. And write tests. GL!

**Comment by ThomasBem** [comment]
I got it to work for the mini and verbose test reporters already. Gotten quiet familiar with those two from my recent issues / PR`s. Combined with the work you had already done that went really fast. Now I gotta figure out how to stop it from printing color in the tests themselves.

So gotta read some more code! :)

**Comment by aemxdp** [comment]
Still doesn't work correctly in `0.18.2`:
```javascript
import test from 'ava';

test('Test', (t) => {
    t.is(1, 2);
});
```

```
$ ava --verbose --no-color > test.log 2>&1
$ open test.log
```

```
  × Test  

  1 test failed [20:29:45]

  Test
  D:\Code\js\ava-sandbox\test.js:4

   3: test('Test', (t) => {
   4:     t.is(1, 2);      
   5: });                  

  Actual:

     [33m1[39m

  Expected:

     [33m2[39m
```

**Comment by novemberborn** [comment]
@aemxdp interesting. https://github.com/avajs/ava/pull/1334 should fix that.
