### ISSUE TITLE
Remove `t.doesNotThrow`

### ISSUE THREAD

**Issue by jfmengels** [avajs/ava#850]
I noticed that in `master`, `t.doesNotThrow` still exists even though it was deprecated (I didn't even know/remember it existed actually).
There is a link to `ava-codemods` (to be updated too, it points to @jamestalmage's repo), but there is no codemod for it.

I suggest removing it altogether, since it looks like it's been removed for a while now. Either that, or add a new codemod for it at the very least.

Willing to do the PR for the removal and the link fixing, and/or the codemod.

**Comment by sindresorhus** [comment]
I think we should leave the deprecation in for the next 0.15.0 release and then remove it afterwards. There's no rush.

**Comment by jfmengels** [comment]
The link was corrected in https://github.com/avajs/ava/pull/852.

I'm fine with leaving `doesNotThrow` in. Do we want to write a codemod for it?

PS: Shouldn't this rather be in the 0.16 milestone if we want to leave it in 0.15?

**Comment by sindresorhus** [comment]
> I'm fine with leaving doesNotThrow in. Do we want to write a codemod for it?

Nah. It's been warning for a while, so most users should have fixed it.

> PS: Shouldn't this rather be in the 0.16 milestone if we want to leave it in 0.15?

Fixed.

**Comment by platy11** [comment]
@sindresorhus I opened PR #1001

**Comment by justsml** [comment]
I wish AVA kept (or added) to the supported method aliases. 
Appears they were removed before I even knew the project existed. 😿 

> Ignore me if many people have already 'complained' about this (and if I just haven't found the `Original Issue` of record to understand what's going on. )

I see lots of `tape` compatible tests, all with varying standardization between them (`isError` vs. `error` etc.). They have varying levels of babel integration (not-working to no-stacktraces).
I avoid messing with it by running it though AVA ❤️ . (I fix it if I can, of course.)

I have a 'hack' injector/wrapper for AVA to map function aliases, but I feel silly every time I have to add & include it.

> Anyway, thanks @sindresorhus et al. for all the awesome projects.
