### ISSUE TITLE
Idea: A temp-dir helper

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#854]
From https://github.com/avajs/ava/issues/820#issuecomment-220806006

When doing tests that interact with the filesystem, it's often easiest to just write fixtures into a temp directory. `mock-fs` can cause odd problems, and you can't inspect the contents of a mock file system.

Using a temp dir doesn't make inspecting the fixture contents much easier. You have to figure out where the temp dir for that test was (usually just by adding a logging statement), then track it down on the filesystem (and it's usually at some weird and lengthy path).

I wonder if we couldn't offer a `temp-dir` alternative that hooked into AVA somehow, and gave you

```
./.ava-temp-dirs
  test-run-hash/       <-- unique id for each run, deleted if all tests pass.
     test-file-name/   <-- deleted in an `after` hook if all tests pass.
        test-name1/    <-- deleted in an `afterEach` hook if the test passed, left for inspection if the test fails.
        test-name2/   
```

What you are left with is a folder containing only fixture data and output from failing tests, and with a directory structure that makes it all easy to inspect.

I'm pretty sure this is too niche to live in core. But it might be worth exploring a "plugin" system someday that allowed this. We might want to give plugins the ability to do some/all of the following things:

- Add to the `--require` flag, so they can install their own hooks.
- Inspect test lifecycle events (pass/fail) in the child thread
- Inspect test lifecycle events in the main thread?
- Amend the babel config?

I certainly think we've got more important things to focus on now.

**Comment by vdemedes** [comment]
> Using a temp dir doesn't make inspecting the fixture contents much easier. You have to figure out where the temp dir for that test was (usually just by adding a logging statement), then track it down on the filesystem (and it's usually at some weird and lengthy path).

I disagree. I don't see how these 2 steps are complicated. There's no need to figure out the path, because `console.log` (as you said) displays it. And you don't need to track anything down as well, because you copy that path and `cd` into it, no matter how weird and lengthy it is.

WIth `.ava-temp-dirs`, the flow does not change actually. Let's assume AVA displays tmp path on test failure. Then you have to copy it and `cd`, just like before.

There's another downside with `.ava-temp-dirs`. When building a Docker image, it will get added to it, unless ignored in `.dockerignore`. Users might not be aware it exists and gets added, because Docker is silent about the files it copies.

**Comment by jamestalmage** [comment]
You wouldn't need to display the temp path. You would just cd into `./.ava-temp-dirs` after a failed test, and everything there would be from failed tests, named in a way that was intuitive to navigate.

I don't get the `.dockerignore` argument. Webstorm adds a `.idea` folder, NYC adds `.nyc_ouput` and maybe `.coverage`. If you're using source control, you're going to notice pretty quickly, because you likely won't have the files added to `.gitignore`.

**Comment by vdemedes** [comment]
> You wouldn't need to display the temp path. You would just cd into ./.ava-temp-dirs after a failed test

In that case, this process becomes one step shorter by not adding `console.log()`. I don't think it's worth building `.ava-temp-dirs` feature to skip this tiny step.

> I don't get the .dockerignore argument. you're going to notice pretty quickly, because you likely won't have the files added to .gitignore.

Talking specifically about Docker, not git:

> When building a Docker image, it will get added to it, unless ignored in .dockerignore. Users might not be aware it exists and gets added, because Docker is silent about the files it copies.

**Comment by vdemedes** [comment]
Fix for Docker argument is to put `.ava-temp-dirs` inside `node_modules/ava`, like `.ava-cache`.

**Comment by jamestalmage** [comment]
> Talking specifically about Docker, not git:

I know, I'm just pointing out that lots of stuff adds `.dotDirs` 

>  I don't think it's worth building .ava-temp-dirs feature to skip this tiny step.

Sure, I'm not convinced either.

> Fix for Docker argument is to put .ava-temp-dirs inside node_modules/ava, like .cache/ava.

That's fairly controversial: https://github.com/avajs/find-cache-dir/issues/1

**Comment by novemberborn** [comment]
@jamestalmage closing this since it's quite speculative.
