### ISSUE TITLE
Macros not working

### ISSUE THREAD

**Issue by tim-mcgee** [avajs/ava#857]
## Description

Macros are always passing

### Test Source

```js
import test from 'ava'

function macro(t, input, expected) {
    t.is(eval(input), expected);
}

test(macro, '2 + 2', 3);
test(macro, '2 * 3', 2);
```

### Error Message & Stack Trace

no error message

### Config

```json
{
  "ava": {
    "require": [
      "babel-register"
    ],
    "failFast": true
  }
}
```

### Command-Line Arguments

```
ava src/**/*.test.js
```

## Relevant Links

- https://github.com/tim-mcgee/ava-macro/

## Environment

- Mac OSX El Capitan (Version: 10.11.5 (15F34))
- darwin 15.5.0
- NPM v3.9.3
- Node.js v6.2.0
- AVA v0.14.0

**Comment by sindresorhus** [comment]
It's not released yet. The readme is for master (this is the case for most projects on GitHub). See https://github.com/avajs/ava/tree/v0.14.0 or https://www.npmjs.com/package/ava for docs for the latest version. We plan on doing a new release in a day or so.

**Comment by jamestalmage** [comment]
Macros are not yet published. Expect them in `0.15`!

If you want to use them now, install from master:

```shell
npm install --save-dev avajs/ava
```
