### ISSUE TITLE
Show line number of test declaration

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#867]
``` js
import test from 'ava';

function macro(t, input, expected) {
    t.is(eval(input), expected);
}

test(macro, '2 + 2', 4);
test(macro, '2 + 3', 5);
test(macro, '2 + 4', 7);
```

```
   2 passed
   1 failed


   1. [anonymous]

  t.is(eval(input), expected)
       |    |       |        
       6    "2 + 4" 7        

      Test.macro (foo.js:4:4)
```

Ideally, we would show the declaration stacktrace as well (i.e. `foo.js:9:1` in the above example).

**Comment by novemberborn** [comment]
I don't think this is macro specific. Rather, we should show the relative file path and line on which a test was declared, perhaps in grey below the test title. So in the following:

![screen shot 2017-08-28 at 16 07 58](https://user-images.githubusercontent.com/33538/29779674-2eaa6cf8-8c0b-11e7-9b50-41a36d8bdfb6.png)

`foo` would be followed by `test.js line 3`

**Comment by novemberborn** [comment]
The `test()` function could obtain a stack trace to figure out the line number. Of course the test could be declared in a separate file, so perhaps it should find the first call site from the test file itself. We need to see what the performance implications are of doing this.
