### ISSUE TITLE
Type definition tests

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#870]
It would be good to have a set of typescript fixtures that exercised the API.
The test would just be running the typescript compiler and ensuring it didn't complain about the syntax.

That seems to be how they do it for [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

@SamVerschueren @ivogabe - That sound like a good idea?

**Comment by SamVerschueren** [comment]
Yes, I was thinking the same yesterday "we should have tests for the type definitions". That would definitely be an improvement to somewhat validate them as the definitions getting more complex and more features are added.

**Comment by jamestalmage** [comment]
When we add new API features we can use `.failing` to mark them until a TypeScript contributor updates the definition...

Except we don't test with AVA 😭 .

**Comment by sindresorhus** [comment]
@jamestalmage We can use skipped tests.

**Comment by unional** [comment]
Chiming in. Just shape test is not enough:
https://github.com/typings/generator-typings#about-writing-tests-for-typings

**Comment by jamestalmage** [comment]
> Just shape test is not enough:

It would almost certainly be better than the nothing we have now though!

**Comment by unional** [comment]
> It would almost certainly be better than the nothing we have now though!

:smile: of course.

**Comment by unional** [comment]
Oh, by the way, if you lobby on this... :smile:
https://github.com/Microsoft/TypeScript/issues/7661

**Comment by ivogabe** [comment]
This seems to be related too: Microsoft/TypeScript#9281

**Comment by sindresorhus** [comment]
We also need this for a forthcoming Flow type definition: https://github.com/avajs/ava/pull/1007

**Comment by novemberborn** [comment]
We have… something, now. Closing since it's not clear to me whether there are any deficiencies in our current approach.
