### ISSUE TITLE
t.notRegex

### ISSUE THREAD

**Issue by silvenon** [avajs/ava#877]
Using `t.false(/regex/.test(str))` feels inconsistent.

**Comment by jamestalmage** [comment]
I agree. It's weird it's the only one we don't offer a negation for.

**Comment by vdemedes** [comment]
Good point, although `notRegex` reads like `not a regex` in my mind.

**Comment by jamestalmage** [comment]
Hmm. Yeah. That's not great, but I don't think it will confuse many people.

I think if we just enforce the string argument and provide a helpful error message, that will suffice. The few that are confused won't remain so long.

**Comment by silvenon** [comment]
Wow, that was fast 🎉

**Comment by sveisvei** [comment]
Not released yet thought, any release incoming soon?

**Comment by ai** [comment]
Wait for release too

**Comment by jfmengels** [comment]
Released in v0.16.0 https://github.com/avajs/ava/releases/tag/v0.16.0
