### ISSUE TITLE
The browser testing recipe should be more generic

### ISSUE THREAD

**Issue by lukechilds** [avajs/ava#882]
I don't mean in regards to the React example as mentioned here: https://github.com/avajs/ava/issues/773 but rather the way the environment is set up. Only `window`, `document` and `navigator` are exposed globally by the helper which means any other global variables available in a browser environment will only be accessible through `window`. This is fine for writing tests but lots of browser libs and their dependencies will expect everything to be global.

For example if one of the browser dependencies was doing something like: `if(domNode instanceof HTMLDivElement)` then `HTMLDivElement` would be undefined so you'd have to go in to the helper and add:

```js
global.HTMLDivElement = window.HTMLDivElement;
```

This could quickly get out of hand. I'm using a simple module ([lukechilds/node-browser-environment](https://github.com/lukechilds/node-browser-environment)) that by default adds everything in `window` to `global` so everything just works. If you want to limit to certain properties you can pass an array of required properties.

So the helper would just be:

```js
require('node-browser-environment')();
```

and you have everything on window available globally.

If you wanted to limit it to certain properties it'd be:

```js
require('node-browser-environment')(['window', 'document', 'navigator']);
```

Would you accept a PR to use this instead? Seems like it would be more frictionless.

**Comment by lukechilds** [comment]
Thanks for that example. That just sticks everything on to global though, I still think it would be beneficial to be able to provide an array of properties to be used. That way if your browser lib has no deps you can safely require what you need and be less likely to experience issues with node dev dependencies that may get confused by browser globals (like in that issue). Plus I'd rather not create a gazillion global variables if I don't have to. 😆 

There wouldn't be any extra stuff to install compared to the current recipe. Currently it's:

```shell
$ npm install --save-dev jsdom
```

`test/helpers/setup-browser-env.js`

```js
global.document = require('jsdom').jsdom('<body></body>');
global.window = document.defaultView;
global.navigator = window.navigator;
```

And I'm proposing to change it to:

```shell
$ npm install --save-dev node-browser-environment
```

`test/helpers/setup-browser-env.js`

```js
require('node-browser-environment')();
```

or if you know exactly what you need:
```js
require('node-browser-environment')(['window', 'document', 'navigator']);
```

If you'd rather I just added [this](https://github.com/lukechilds/node-browser-environment/blob/master/src/index.js) to the recipe I'm happy to do this but I thought this seemed like a good [Lego block](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328)

**Comment by lukechilds** [comment]
@vdemedes What do you want me to do with this?

**Comment by vdemedes** [comment]
Interesting point, I like it. I'm only wondering whether it would mess up with people's expectations that everything should be working out-of-the-box. That is sort of how AVA works, it assumes good defaults and lets developers customize them only when necessary. 

Let's hear what other people think ;) 

P.S. I'm going on vacation today, so I'll probably be completely offline until 20th July. Sorry for not being able to continue this discussion!

P.P.S. Thank you for such detailed posts, explanations and code examples, I wish more people explained their thoughts & arguments like that! 👍

**Comment by lukechilds** [comment]
No probs, I'll wait for more feedback before changing anything.

Have a great holiday!

**Comment by philmill** [comment]
@lukechilds I'm digging [`node-browser-environment`](https://github.com/lukechilds/node-browser-environment) which looks to be a convenient DSL for `jsdom` anyways. Just used it in a React project with ease.  👍  for using it in the example here. Nice job with the DSL btw.

**Comment by lukechilds** [comment]
@philmill Awesome, thanks!

At the risk of sounding like an idiot, what do you mean by DSL? Domain-specific language?

**Comment by philmill** [comment]
Yes, that's correct. I called `node-browser-environment` a DSL since it provides a specific language to use with `jsdom` (common DOM objects represented as string literals in an array). It's a loose use of DSL since it's not a language to be parsed into a GPL. Maybe API wrapper would be more applicable.

**Comment by novemberborn** [comment]
@vdemedes:

> I'm only wondering whether it would mess up with people's expectations that everything should be working out-of-the-box. That is sort of how AVA works, it assumes good defaults and lets developers customize them only when necessary.

At this stage AVA can test Node.js code, so it shouldn't be too surprising you need additional setup to mimic a browser environment.

@lukechilds are you still interested in adding your module to the browser testing recipe?

**Comment by lukechilds** [comment]
@novemberborn Yeah sure, I'm really busy atm but will try and find some time this weekend to write something up 👍

**Comment by lukechilds** [comment]
@novemberborn sorry, didn't get a chance at the weekend, just submitted https://github.com/avajs/ava/pull/1054
