### ISSUE TITLE
t.throws doesn't compare promises

### ISSUE THREAD

**Issue by tim-mcgee** [avajs/ava#885]
## Description

I don't know if it's a but but if not I think it should be a feature :)

A rejected Promise don't compare with the error message field if it's a string at t.throws().

### Test Source

```js
import test from 'ava'
import Promise from 'bluebird'

test('should pass', t => {
    t.throws(Promise.reject('error message'), 'error message')
})
```

I think it should compare the rejected value and the value given as the second argument with deepEqual.

#### Possible Workaround

```js
t.throws(Promise.reject('error message'), /error message/)
/**
 * But t.throws(Promise.reject({foo: 'bar'}), /.../)
 * would not work this way.
 */
```
or
```js
t.throws(Promise.reject('error message'), value => value === 'error message')
```
or
```js
Promise.reject('error message').then(() => {
  t.fail()
}).catch(errorMsg => {
  t.is(errorMsg, 'error message')
})
```

### Error Message & Stack Trace

Even if it's not an error then the error message isn't meaningful.

```
   1 failed

   1. should pass
   undefined undefined undefined
      From previous event:
        Test.fn (test.js:5:7)
```

### Config

```json
no config
```

### Command-Line Arguments

```
ava
```

## Relevant Links

- Reproduction: https://github.com/tim-mcgee/ava-promise-reject

## Environment

```
- Mac OSX El Capitan (Version: 10.11.5 (15F34))
- darwin 15.5.0
- NPM v3.9.3
- Node.js v6.2.0
- AVA v0.15.1
```

**Comment by jamestalmage** [comment]
You should always reject with Errors. Errors give you stack traces. AVA is intentionally opinionated about this.

If you insist on not rejecting with Errors, then your best option is the final workaround you mentioned. 

(But really, just reject with Errors).
