### ISSUE TITLE
Document reporter behavior when run in CI environment.

### ISSUE THREAD

**Issue by danielhusar** [avajs/ava#890]
Hey guys,

I have set verbose to false which works great on my machine:

```
> NODE_ENV=test ava app/**/*.test.{js,jsx}
97 passed
```

However same tests on CI have always verbose logging enabled:
<img width="481" alt="screen shot 2016-05-30 at 21 46 03" src="https://cloud.githubusercontent.com/assets/1857751/15663436/f396a59e-26af-11e6-94b4-8db07ed18a7b.png">

Is this indented ?
Tests run on codeship.

**Comment by BarryThePenguin** [comment]
I know it's intended, using `is-ci`, as shown in [cli.js L147-L149](https://github.com/avajs/ava/blob/ab3418fe62e1bcf2514b127ee340574027c507a3/cli.js#L147-L149)

#435 explains the history

**Comment by danielhusar** [comment]
👍 would be probably nice to add it to documentation

**Comment by jamestalmage** [comment]
Anyone want to do a documentation PR? It should just be adding a single short sentence. Just "the verbose reporter is always used in CI environments unless tap is specified"

**Comment by sindresorhus** [comment]
Documented in https://github.com/avajs/ava/pull/955.
