### ISSUE TITLE
Console messages aren't shown in VS Code console

### ISSUE THREAD

**Issue by kripod** [avajs/ava#892]
No output message gets shown if the `ava` command is ran as a Visual Studio Code task.

**Comment by jamestalmage** [comment]
Unfortunately, no one on the core team uses Visual Studio, and it's unlikely to ever be an officially supported platform.

Currently we support the following:

 - The default `terminal` on OSX
 - `iTerm2` on OSX
 - `cmd` on WIndows

**Comment by kripod** [comment]
I'm surprised about that, because IntelliSense in VS code provides great DX while writing tests:

![code](https://cloud.githubusercontent.com/assets/14854048/15712786/eff5d38c-2813-11e6-8000-4da9a3abc5b7.png)

**Comment by jamestalmage** [comment]
That's almost certainly a result of the hard work put in our TypeScript team, but it's unrelated to console output.

Have you tried `ava --verbose`?

**Comment by jamestalmage** [comment]
I checked out VisualStudio Code for OSX. I couldn't figure out what a "Visual Studio Code task" is.

**Comment by kripod** [comment]
Press `Cmd + Shift + P` and then input "Tasks: Configure Task Runner" into the box.

If the task runner was configured correctly, you can see a file appearing at `.vscode/tasks.json` with content similar to this:

```json
{
  // See http://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "0.1.0",
  "command": "npm",
  "isShellCommand": true,
  "showOutput": "always",
  "suppressTaskName": true,
  "tasks": [
    {
      "taskName": "build",
      "args": ["run", "build"],
      "isBuildCommand": true
    },
    {
      "taskName": "watch",
      "args": ["run", "watch"],
      "isWatching": true
    },
    {
      "taskName": "test",
      "args": ["run", "test"],
      "isTestCommand": true
    }
  ]
}
```

The existence of this file lets you quickly build and test projects by pressing `Cmd + Shift + B` or `Cmd + Shift + T`.

**Comment by kripod** [comment]
By the way, the `--verbose` flag does not seem to help...

**Comment by jamestalmage** [comment]
Still no luck. `Cmd + Shift + T` does nothing.

**Comment by kripod** [comment]
You can also run tests by pressing `Cmd + Shift + P` and then inputting "Tasks: Run Test Task" to the box.

**Comment by jamestalmage** [comment]
Verbose works great for me:

<img width="791" alt="screenshot 2016-06-01 11 20 34" src="https://cloud.githubusercontent.com/assets/4082216/15715055/0eed153a-27eb-11e6-8510-dd2f33a75a9b.png">


However, using the mini reporter, it's obvious the VS Code console does not support terminal control characters. 

<img width="787" alt="screenshot 2016-06-01 11 21 36" src="https://cloud.githubusercontent.com/assets/4082216/15715084/2fed7c20-27eb-11e6-80d3-f105f1a57d07.png">

I recommend sticking with verbose.

**Comment by kripod** [comment]
The `--verbose` flag still doesn't output anything for me on Windows.

![code](https://cloud.githubusercontent.com/assets/14854048/15715199/d6648cd8-281d-11e6-8eec-51145f2da618.png)

**Comment by jamestalmage** [comment]
I can't dedicate any more time to troubleshooting this, but if someone figures out why this is happening, we can discuss fixes

**Comment by kripod** [comment]
Thank you very much for your assistance! :smile:

**Comment by sindresorhus** [comment]
// @SamVerschueren

**Comment by SamVerschueren** [comment]
Will have a look when I find some time

**Comment by kripod** [comment]
It seems that new insider builds of VS Code have fixed this issue. Thanks for the assistance, especially for the tip about `--verbose`!
