### ISSUE TITLE
passed deepEqual not equal objects

### ISSUE THREAD

**Issue by GitScrum** [avajs/ava#899]
### Description
This test should not be passed

### Test Source

```js
t.deepEqual({a: {}, b: {}}, {b: {}, a: {}});
```

### Config

```json
{
  "ava": {
    "require": [
      "babel-register"
    ]
  }
}
```

## Environment

```
OS   --version ==> windows 10
node --version ==> 6.2.0 
ava  --version ==> 0.15.1
npm  --version ==> 3.6.0
```

**Comment by jfmengels** [comment]
These look equal to me. The order in which the keys are defined is not important, as in the JS spec there is no guaranty whatsoever about the key order.

**Comment by GitScrum** [comment]
@jfmengels if I take the keys then the order will not be equal
```js
t.deepEqual(Object.keys({a: {}, b: {}}), Object.keys({b: {}, a: {}})); 
```

**Comment by jfmengels** [comment]
> Because the order of iteration is implementation-dependent, iterating over an array may not visit elements in a consistent order

(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in, as https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys links to that one)

The order of the keys is not important in JS, as it is implementation specific and not guaranteed by the language. V8 for instance (which powers Node and Google Chrome) will return the keys in one order, while ther engines may return them in an order. In your example, the first arg will be `['a', 'b']`, while the second will be `['b', 'a']`, but that is the normal behavior. If you want to compare the list of keys, then you should sort them.

The important thing, is that two objects all have the same keys, and the same values associated with it. If you have that, then the objects are equal. This is the behavior that all assertion libraries have (afaik).

**Comment by GitScrum** [comment]
@jfmengels  Thanks, you right. :+1: 
>  If you want to compare the list of keys, then you should sort them.
