### ISSUE TITLE
Add an option to measure the run time of each test

### ISSUE THREAD

**Issue by kripod** [avajs/ava#904]
This feature could allow benchmarking to be done from the test suite.

**Comment by jamestalmage** [comment]
See: https://github.com/Hypercubed/chuhai

I would use caution when benchmarking with AVA however. There is a lot going on in the background, and spread across multiple processes. This is going to interfere with benchmark reliability.

**Comment by kripod** [comment]
Thanks for the tip, I saw that project and thought that it would add too much boilerplate to my test suite.
