### ISSUE TITLE
index.d.ts is old in 0.15.2 package

### ISSUE THREAD

**Issue by rhysd** [avajs/ava#908]
## Prerequisites

- `$ npm install ava`

## Description

In ava 0.15.2 package, [my previous PR](https://github.com/avajs/ava/commit/2e984380c4df2bfe5a0af2ec37a970f4001c9f53) seems not to be applied.

### Test Source

```typescript
import test from 'ava';

test.afterEach.always(() => {});
```

Then please execute `tsc test.ts --target es2015 --module commonjs`

### Error Message & Stack Trace

```
test.ts(3, 16): error TS2339: Property 'always' does not exist on type 'ContextualRunner'.
```

## Relevant Links

- This must be fixed if [my PR](https://github.com/avajs/ava/commit/2e984380c4df2bfe5a0af2ec37a970f4001c9f53) is applied.

## Environment

```
Node.js v5.6.0
darwin 15.3.0
ava 0.15.2
npm 3.6.0
```

**Comment by jamestalmage** [comment]
`0.15.2` was released from a feature branch based on the `0.15.1` tag, which didn't have your commit.

Your best bet is to install from master for now.

**Comment by rhysd** [comment]
@jamestalmage 

Thanks.  I understood and will use master branch.  Could you tell me when the PR is included in a package? 0.16?

**Comment by sindresorhus** [comment]
0.16.0. 0.15.2 was a quick fix to work around a deprecation in a dependency.

**Comment by rhysd** [comment]
@sindresorhus Thanks.

**Comment by andreasgrimm** [comment]
> Your best bet is to install from master for now

That's what I did until today I saw that the typings were gone and now my CI builds fail. Any hint on how to work around this in a quickly fashion?

**Comment by sindresorhus** [comment]
@andreasgrimm Never install master. It's a moving target. Specify a commit hash.

**Comment by andreasgrimm** [comment]
Any chance the above mentioned "error" get's fixed in a version that can be installed without any special means ?

**Comment by andreasgrimm** [comment]
With the `make-ts` available now, I guess it won't take too long, will it ;)
