### ISSUE TITLE
chokidar shouldn't be an optional dependency

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#913]
As per <https://github.com/babel/babel/pull/3307#issuecomment-213852070> chokidar should work on all platforms. If `fsevents` is the concern, it's already [an optional dependency of `chokidar`](https://github.com/paulmillr/chokidar/blob/15c642702060735f5157ee7a23fafb84b50b9a23/package.json#L43).

`chokidar` should be moved to the `dependencies` (it's currently [here](https://github.com/avajs/ava/blob/cddd2481386cecaf6622a9468dc8e1c5434a95bf/package.json#L178)).

The watcher could just require `chokidar` directly, instead of via its [`requireChokidar` function](https://github.com/avajs/ava/blob/cddd2481386cecaf6622a9468dc8e1c5434a95bf/lib/watcher.js#L11).

Tests also [need](https://github.com/avajs/ava/blob/cddd2481386cecaf6622a9468dc8e1c5434a95bf/test/watcher.js#L39:L54) [updating](https://github.com/avajs/ava/blob/cddd2481386cecaf6622a9468dc8e1c5434a95bf/test/cli.js#L17:L21).

**Comment by forresst** [comment]
I would do that. This will allow me to do anything other than translation.

**Comment by novemberborn** [comment]
@forresst great!
