### ISSUE TITLE
recipe needs update?

### ISSUE THREAD

**Issue by ORESoftware** [avajs/ava#915]
I saw this recipe:

https://github.com/avajs/ava/blob/47f08e09558e808ddfc017b7fe10405f1a8372c4/docs/recipes/babelrc.md

I thought AVA was not loading babel deps in every child process, for the sake of speed?

**Comment by novemberborn** [comment]
@ORESoftware which paragraph specifically are you referring to?

**Comment by ORESoftware** [comment]
Thanks I was referring to:

https://github.com/avajs/ava/blob/47f08e09558e808ddfc017b7fe10405f1a8372c4/docs/recipes/babelrc.md#transpiling-sources

"you will need to tell AVA to load babel-register in every forked process"

**Comment by jamestalmage** [comment]
You still need it to transpiled sources. Tests are transpiled in the main process. There are other issues tracking transpiling sources and helpers in the main process.

**Comment by ORESoftware** [comment]
RIght, I thought tests were transpiled in the main process, so you're saying that helper files/sources are the primary reason to use `require('babel-register')` ?

**Comment by jamestalmage** [comment]
Yes. Hence the `Transpiling Sources` header on that section you referenced. It also explains the performance trade-off, and links to the open issue that proposes we extend the precompilation behavior to the main process.

**Comment by jamestalmage** [comment]
Closed because I think the docs cover the current state well, and we have open issues to track improvements already

**Comment by ORESoftware** [comment]
why not just transpile/copy the entire "test" directory to "test-target"? Assuming all the test helpers etc were in test dir?

**Comment by jamestalmage** [comment]
Because we create a hash from the input and avoid retranspiling if it's unchanged.

Look in `node_modules/.cache/ava` - the filenames there are the hashes used for detecting cache hits / misses.
