### ISSUE TITLE
AVA randomly exists without finishing

### ISSUE THREAD

**Issue by jluchiji** [avajs/ava#921]
## Description
I develop a large project with hundreds of test files. When I run AVA on my late 2013 Mac Pro, there are no issues. However, when I run the tests on my MacBook Pro, sometimes AVA exits without finishing all the tests.

If I use `--concurrency` flag, then I frequently get `Test results not received` errors.

The exit code is 0 even if some of the tests run have failed. There are no error messages whatsoever. Everything looks as if AVA have finished running all the tests.

### Config

Copy the relevant section from `package.json`:

```json
{
"ava": {
    "files": [
      "ava/**/*.spec.js"
    ],
    "require": [
      "babel-register"
    ],
    "babel": "inherit"
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v4.4.2
darwin 15.6.0
ava 0.15.2
npm 3.8.7
```

**Comment by novemberborn** [comment]
@jluchiji is this still an issue? If you're still using AVA, would you be able to share the project? Or the test output? How can you tell it hasn't finished all the tests?

**Comment by jluchiji** [comment]
I am still using AVA, and this is no longer an issue as of 0.16.0. I am closing this issue.

I was able to tell that not all tests finished because the number of passed tests reported by AVA was sometimes a lot less than actual number of tests that I had, while AVA reported that all tests have passed. I am fairly sure it was not because of ignoring files or changing config, since re-running AVA with the same configuration produced different results, sometimes correct sometimes not.

For example, test output was `17 passed`, and AVA exited with code 0, while I actually had 100+ tests.
