### ISSUE TITLE
Date is pre-1970 (and therefore Date.now() returns 0)

### ISSUE THREAD

**Issue by tquetano-r7** [avajs/ava#930]
## Description

Pretty straightforward, basically all methods I can use to obtain the standard timestamp return 0, and it is because the date is set to be pre-UTC era. I've validated this is not in Node, and still exists when I remove jsdom from the equation, so I must believe it is ava-specific.

### Test Source

```js
// Avoid posting hundreds of lines of source code.
// Edit to just the relevant portions.

console.log(Date.now()); // 0
console.log((new Date()).getTime()); // 0
console.log((new Date()).valueOf()); // 0
console.log(new Date()); // Wed Dec 31, 1969 19:00:00 GMT-0500 (EST)
```

### Error Message & Stack Trace

```
COPY THE ERROR MESSAGE, INCLUDING STACK TRACE HERE
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "babel": "inherit",
    "failFast": true,
    "files": [...],
    "require": [
      "babel-register",
      "babel-polyfill",
      "./test/helpers/setup-browser-environment.js"
    ]
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
NODE_ENV=test ava --no-cache
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
ava --version
npm --version
```

Operating system: Ubuntu 14.04,
Node version: 4.4.2
NPM version: 3.9.6
AVA version: 0.15.2

**Comment by jamestalmage** [comment]
I just ran this:

```js
import test from 'ava';

test(() => {
	console.log(Date.now())
});
```

Got:

```
1466521648524
```

**Comment by tquetano-r7** [comment]
Damn, this is actually a result of sinon.test wrapping the async function call ...

```
test(async function() {
  const now = await Date.now();

  console.log(now);
});

// just fine

test(sinon.test(async function() {
  const now = await Date.now();

  console.log(now);
}));

// 0
```

I'll close because I think its now more likely a sinon issue
