### ISSUE TITLE
Add assertion count to summary

### ISSUE THREAD

**Issue by tony-kerz** [avajs/ava#933]
consider adding assertion count in addition to test count on summary report.

i was just thinking something simple as in [ruby minitest](https://github.com/seattlerb/minitest#running-your-tests). 

the number of assertions is just another datapoint, e.g. in theory, 10 tests/100 assertions > 10 tests/10 assertions. so i was just thinking a mention in the summary, something like: 
```
10 tests passed (100 assertions)
```

[original gitter reference](https://gitter.im/avajs/ava?at=576ac7b2c7594b5f0dd1be4d)

**Comment by sindresorhus** [comment]
Why? What do you gain from knowing the assertion count? Keep in mind that everything we add clutters the UI, so we don't add things lightly. We only really display the test count so the user would know if they had accidentally skipped/only a test, and for consistency with the output of some tests failing. Ideally I would have just showed `All tests passed`.

**Comment by tony-kerz** [comment]
like i said, it's just another data point.

it's possible to write tests like this:
```
test('scam test', () => {
})
```
which don't do anything meaningful, yet appear to illustrate testing.

it's also possible to have 100% code coverage without a single assertion.

of course, these shoddy testing techniques (let's hope more unintentional than intentional),
can be discovered with closer analysis of the test code, but having the ability to display
an additional "kpi" like assertion-count can provide a quick insight without a deep dive.

i understand your preference for cleanliness tho. 

perhaps consider adding the metric in verbose mode, or even with a distinct flag.

regards,
tony.

**Comment by vdemedes** [comment]
I don't think I'm on board with this addition as well, because it does not give any benefit or useful information to the user.

As for "shoddy testing techniques", not sure testing framework would help you discover those. How about this:

```js
for (let i = 0; i < 100; i++) {
  t.true(true);
}
```

would show that this test executed 100 assertions.

As for me, I usually look at the overall quality of the module, including taking a peek at its source code. I rarely (if not never) look at its code coverage or test results.

**Comment by kasperlewau** [comment]
The only time I would see any value in this would be to catch cases where the number of assertions exceed the number of tests (personal preference of mine, `max-assert` set to 1) - and eslint-plugin-ava takes care of that just fine 👌 

Gut feeling says your linter would do a better job than your reporter at catching shoddy testing techniques.

**Comment by tony-kerz** [comment]
@vdemedes agree. 

if someone was trying to game the system, it wouldn't help.

in the more likely good-faith case, it is an (easily collected?) metric that could be used as an anecdotal indicator of coverage, and i would use it as such.

i understand the dark side of metrics too (think lines-of-code), and resultant religious positions on the topic, so if the project owners feel it doesn't add value (or is otherwise evil), i understand.

**Comment by vdemedes** [comment]
> in the more likely good-faith case, it is an (easily collected?) metric that could be used as an anecdotal indicator of coverage, and i would use it as such.

We try to not add nice-to-have features, that don't help/solve the real pain. Sure, it may be easy to add, but that does not mean it should be done. Sometimes we just have to say no, unfortunately.

Feel free to propose your other ideas in new issues! ;)
