### ISSUE TITLE
Upgrade tap, ensure asynchronous tests return promises

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#935]
With `tap@5.8.0`, if a test returns a promise `tap` now ensures the next test isn't launched until that promise is settled (https://github.com/tapjs/node-tap/pull/249).

We should upgrade to `^5.8.0` and review our unit tests, ensuring that correct promises are returned for every asynchronous test (unless `t.end()` is used). This should help with race conditions in the tests and failures being attributed to the wrong test.

**Comment by sotojuan** [comment]
Taking care of this over the weekend.
