### ISSUE TITLE
Set stdout/stderr ttys to blocking

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#938]
From [npm v3.10.0 release notes](https://github.com/npm/npm/releases/tag/v3.10.0):

> As a part of this change we now explicitly set process.stdout and process.stderr to be blocking if they are ttys, using set-blocking. This is necessary to ensure that we can fully erase the progress bar before we start writing other things out to the console.

This seems relevant for AVA too.

**Comment by sindresorhus** [comment]
It was only an issue on Node.js 6 and now fixed in Node.js 6.2.1:

> tty: Default to blocking mode for stdio on OS X. A bug fix in libuv 1.9.0, introduced in Node.js v6.0.0, exposed problems with Node's use of non-blocking stdio, particularly on OS X which has a small output buffer. This change should fix CLI applications that have been having problems with output since Node.js v6.0.0 on OS X. The core team is continuing to address stdio concerns that exist across supported platforms and progress can be tracked at https://github.com/nodejs/node/issues/6980. (Jeremiah Senkpiel) #6895 - https://nodejs.org/en/blog/release/v6.2.1/
