### ISSUE TITLE
Confused about babel:inherit vs babelrc:true

### ISSUE THREAD

**Issue by callumlocke** [avajs/ava#943]
Maybe I'm being stupid, but I can't work out what the difference is between `"babel": "inherit"` and `"babel": {"babelrc": true}`. The docs [here](https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md) could maybe do a better job of spelling out the difference.

(Possibly related: no matter which approach I use, ava never seems to respect a `.babelrc` file in a subfolder; it only respects the `.babelrc` in the project root – is that intentional?)

**Comment by jamestalmage** [comment]
True is the [default behavior](https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#avas-default-transpiler-behavior) which includes `es2015` and `stage2`

`inherit` allows you to customize with whatever you want. 

PR welcome

**Comment by callumlocke** [comment]
> `inherit` allows you to customize with whatever you want.

Does that mean it adds to the default config, or replaces it?

**Comment by jamestalmage** [comment]
Replaces it.

**Comment by novemberborn** [comment]
With #1488 we'll be changing this behavior. Closing this issue, I doubt it'll lead to any edits to the recipe until those changes land.
