### ISSUE TITLE
Option to disable babel-plugin-transform-runtime?

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#947]
I am porting a Node.js v6 project to use AVA. I can already specify just the Babel plugins I need for my tests to run:

``` json
  "ava": {
    "babel": {
      "plugins": [
        "transform-async-to-generator",
        "transform-es2015-modules-commonjs"
      ]
    },
  }
```

However AVA will always add the `babel-plugin-transform-runtime` plugin. It's not really needed for my use case and actually causes a test to break:

I'm testing whether a module returns a promise, using `t.true(thingThatReturnsAPromise() instanceof Promise)`. The `babel-plugin-transform-runtime` plugin replaces `Promise` within the test with a `core-js` implementation, but the module returns a native promise. Hence `instanceof` fails.

It'd be useful if the `babel-plugin-transform-runtime` could be disabled. Perhaps like this:

``` json
"ava": {
  "babel": {
    "disable-transform-runtime": true
```

The above would leave AVA's Babel config in default mode, but disable the plugin.

To use it with `inherit` mode:

``` json
"ava": {
  "babel": {
    "inherit": true,
    "disable-transform-runtime": true
```

Or to use it with a custom config:

``` json
"ava": {
  "babel": {
    "disable-transform-runtime": true,
    "plugins": [
      "transform-async-to-generator",
      "transform-es2015-modules-commonjs"
    ]
```

Thoughts?

**Comment by niieani** [comment]
It would be good to also allow turning Babel off completely. It would solve the issue with resolving https://github.com/avajs/ava/issues/631.

**Comment by jrajav** [comment]
I'd like to add to this that even with `babel: "inherit"`, the fact that ava still includes some babel plugins (primarily transform-runtime) breaks many repos, including ours, in a very odd way, and has led us away from using ava for the time being. Not just this one case, ava should not impose *any* extra babel configuration or plugins at all on the source, however convenient it seems - even if it didn't break things, it couples things in a dirty way and goes against the notion of pure composability.

**Comment by sindresorhus** [comment]
@jrajav What breaks? Please open an issue about it.

**Comment by jrajav** [comment]
@sindresorhus I will try to reproduce it, but it might take time - I'd have to update our large repo with all its new configuration and tests to ava again. I'll definitely open one if I can.

**Comment by novemberborn** [comment]
`master` no longer applies the runtime transform.
