### ISSUE TITLE
Make 'concurrency' flag stable to limit RAM usage

### ISSUE THREAD

**Issue by hoschi** [avajs/ava#950]
At the moment the `concurrency` CLI flag is marked as experimental. AVA runs more than 230 tests and takes more than 12GB RAM without a limit for concurrency. I now limit it to 16 which has no impact on the time all tests need to complete, but AVA takes 2GB RAM instead.

Perhaps this could be also fixed through some other ongoing efforts I saw in the issue tracker.

**Comment by novemberborn** [comment]
It's experimental until we sort out remaining issues (notably `.only` behavior). You're free to use it though, and glad to hear it's helping with your use case.

**Comment by hoschi** [comment]
What is the problem/bug with `.only` and the flag?

**Comment by forresst** [comment]
@hoschi Check out this https://github.com/avajs/ava/issues/923
