### ISSUE TITLE
Custom Error Inheritance Breaks?

### ISSUE THREAD

**Issue by skorlir** [avajs/ava#952]
## Description

Custom errors extending from the Native Error in Node do not work correctly with `instanceof` and `t.throws`, in spite of the fact that in the Node REPL custom errors work correctly with `instanceof`.  I am compiling from TypeScript, but this makes no difference in the behavior (apart from occasional compiler warnings) from just writing in plain JS.

### Test Source

```js
// my custom error in app/support/errors.ts
export class RequiredError extends Error {
  constructor (requiredField: string, actualValue: any) {
    super(`${requiredField} was required but got ${value}`)
  }
}
// my test file in test/simple-test.ts
import test from 'ava'
import { RequiredError } from '../app/support/errors'

test(`Do errors inherit?`, t => {
  try {
    throw new RequiredError('myfield', undefined)
  } catch (e) {
    console.log(e instanceof RequiredError)
    console.log(e instanceof Error)
    t.true(e instanceof RequiredError)
  }
})
```

### Error Message & Stack Trace

![Error message](http://i.imgur.com/yhdYnpa.png)

(Sorry it's hard to copy that correctly from inside of tmux.)

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "failFast": true,
    "require": [
      "babel-register",
      "ava-jspm-loader"
    ],
    "tap": true
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```sh
# pretest
(tsc -p app ; :) && (tsc -p test ; :)
#test
ava | tap-difflet
#posttest
rm -f $(find app -name '*.js*') && rm -f $(find test -name '*.js*')
```

## Relevant Links

[Minimal reproduction](https://github.com/skorlir/ava-bug-custom-errors)

Note that to simplify the process the minimal reproduction is written in plain JS. The error's root cause seems to have nothing to do with most of my configuration - TypeScript and an ava plugin/hack - so I trimmed that all out.

## Environment

Node.js v6.2.0
linux 4.4.0-28-generic
Ubuntu 16.04 x64

ava --version
0.15.2

npm --version
3.8.9

**Comment by jamestalmage** [comment]
This seems like a Babel bug.

**Comment by skorlir** [comment]
Except if I compile the es6 and test whether `instanceof` works in the Node
REPL, it works fine.

Otherwise I would think it was something wrong in my Babel config, too.

**Comment by jamestalmage** [comment]
You are using ES6 modules which are not supported by Node yet, so there is transpilation happening somewhere.

If Nodes implementation of ES6 classes fails an instanceof check, then that's a Node bug. You would do well to transpile anyways until it is resolved.

Can you reproduce without the jspm loader?

**Comment by skorlir** [comment]
Yes, the minimal reproduction does not use the jspm loader. Please see [my example repo](https://github.com/skorlir/ava-bug-custom-errors).

**Comment by skorlir** [comment]
@jamestalmage hmm it looks like you must be right...

The output JS from `tsc` inherits correctly, and using the Node REPL I can test that `instanceof

**Comment by skorlir** [comment]
@jamestalmage You're right. The test only actually *passes* when the tsc target is es5 instead of es2015. This is a babel bug.
