### ISSUE TITLE
Promise & Iterator types not defined in index.d.ts

### ISSUE THREAD

**Issue by rbcasperson** [avajs/ava#953]
Upon transpiling my typescript tests written in ava, I get the following errors multiple times:
```
node_modules/ava/index.d.ts(5,40): error TS2304: Cannot find name 'Promise'.
node_modules/ava/index.d.ts(5,56): error TS2304: Cannot find name 'Iterator'.
```

This is because `Promise` and `Iterator` have not been declared in the file, and therefore cannot be referenced later.

If I add this to the top of my `node_modules/ava/index.d.ts`, all errors go away.
```
type Promise<T> = any
type Iterator<T> = any
```
It is a short term workaround, but these types need proper declarations.

I am running Ava at `0.15.2` and TypeScript at `1.8.10`

**Comment by jamestalmage** [comment]
I am surprised `Promise` and `Iterator` are not built in types. Perhaps you need to set the `target` in your compiler options? http://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by rbcasperson** [comment]
Ah yes, my target was set to `'es5'`, and the errors went away with target set to `'es6'`. I will need to set up multiple `tsconfig` files in order to send my source to `es5` and my tests to `es6`.

**Comment by ivogabe** [comment]
You can also set `lib` to `['es2015']` in TypeScript 2.0 to make those types available, without changing the target.
