### ISSUE TITLE
__DEV__ is not defined

### ISSUE THREAD

**Issue by shtefanntz** [avajs/ava#958]
Hi guys!
I asked this on SO, but probably it's not really visible :( http://stackoverflow.com/questions/38295522/react-native-unit-testing-with-ava
There is something missing with the setup for the first run because the Setup.js file is not taken into consideration.

I found out about AVA from this article, [https://shift.infinite.red/testing-the-bejeezus-out-of-react-native-apps-with-ava-330f51f8f6c3#.jy4ylsxj8](url) . After trying out step by step and failed, I cloned the author's repo and it still doesn't run the only test in the project.

Here are the details:
ava version: 0.15.2
npm version: 2.14.7

the rest is in the SO question already formatted :)

Thanks in advance!

**Comment by skellock** [comment]
Hi @shtefanntz ,

Article author here.

That's strange.  `__DEV__` should be available.  I wonder if, perhaps you've got an older version of Node installed?   

`npm` 2.14.7 looks a bit older.  Can you verify your `node` version too for me?

I see you're on Windows too.  Any problems running React Native in general?

**Comment by shtefanntz** [comment]
Hi Steve!

I updated npm to version 3.10.5 by running  
> npm i -g npm

and it still doesn't get past that line  in react-native.js. 
The version on node is 4.4.6.

I don't remember specific problems running RN in general. Most of the time, they are spawned from my lack of understanding of the whole architecture of ReactNative or mobile development. But it works in the end :)

I'm looking forward to any suggestions!

**Comment by skellock** [comment]
Thx for updating.  Node 6.3.x is out now, might want to try that.

The other thing, in your StackOverflow code, your `package.json` has a few issues with it:

![image](https://cloud.githubusercontent.com/assets/68273/16744761/9c17c89c-4780-11e6-9ade-f4bd42063917.png)

Give that a go.  If that doesn't work, let's hop over to https://github.com/skellock/bajeezus/issues and continue our conversation there.  

I don't believe this is an AVA issue.  <3

**Comment by shtefanntz** [comment]
Indeed it's not an AVA problem, nor a problem of its dependencies. 
Apparently, after installing the latest node version (i was using the lts one), deleting the node_modules folder and rerunning 

> npm i

the tests passed. I didn't change anything in package.json. 

Thanks a lot for your advice!
If you want, post the answer in SO and I'll mark it as resolved :)

**Comment by davidosorio** [comment]
I have the same problem but when I am running the test in CircleCI, in my local machine are working as expected. Any idea what is happening ?

I am using node version 7.4.0 and npm version 4.0.5

 Thanks.

![screen shot 2017-01-18 at 11 19 52](https://cloud.githubusercontent.com/assets/2844659/22062167/4e4acf70-dd70-11e6-89d1-ad57aa43eb77.png)

**Comment by skellock** [comment]
I don't have an experience with CircleCI.

Here's some really bad advice that might work:  If you have an AVA init script, throw a `global.__DEV__ = true` (or false if that's how you roll) in there and don't look back.  Never look back David.
