### ISSUE TITLE
typings: Consider using PromiseLike instead of Promise

### ISSUE THREAD

**Issue by unional** [avajs/ava#960]
Using the global `Promise` causes incompatibility error:
https://github.com/unional/ava/issues/1

Using `PromiseLike` should solve this problem.

**Comment by jamestalmage** [comment]
See https://github.com/Microsoft/TypeScript/issues/5911

It seems to suggest that `Promise` must be used for `async` functions. We definitely want to allow `async` functions, so not sure this is a good idea.

@SamVerschueren @ivogabe

**Comment by unional** [comment]
An alternative would be using `any-promise`. Since it includes its typings and does not have any dependencies, it should work too.
You can try it out with the changes I made

**Comment by unional** [comment]
`es6-promise` would also be possible (and likely a better option) once this is landed:
https://github.com/stefanpenner/es6-promise/pulls

**Comment by ivogabe** [comment]
`PromiseLike` would work, there's no need to add another dependency for it.

@jamestalmage That only applies when you annotate an async function with a return type. `Promise<T>` is assignable to `PromiseLike<T>`, so you can still use async functions after this change.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/avajs/ava/commit/1dd6d5b9127a6850d9a03c242e677ea359d67053.

**Comment by unional** [comment]
Great! Thanks. 

I'm working on `ava-fixture` in typescript that runs file-based tests (and baseline tests in the future). It would benefit from the updated typings. 

Are you planning to do a release soon?
