### ISSUE TITLE
Support NODE_ICU_DATA in forked processes

### ISSUE THREAD

**Issue by jgkim** [avajs/ava#962]
With the almost same reason with #531, we need to ensure `NODE_ICU_DATA` is absolute in `lib/fork.js`.
### Error Message & Stack Trace

```
#
# Fatal error in , line 0
# Failed to create ICU date format, are ICU data files missing?
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::internal::(anonymous namespace)::CreateICUDateFormat(v8::internal::Isolate*, icu_57::Locale const&, v8::internal::Handle<v8::internal::JSObject>)
 3: v8::internal::Runtime_CreateDateTimeFormat(int, v8::internal::Object**, v8::internal::Isolate*)
 4: 0x1e1d30b0961b
 5: 0x1e1d30ced87c
```

**Comment by jgkim** [comment]
It seems like this bug is also caused by #32.

**Comment by novemberborn** [comment]
@jgkim #32 changes the CWD to always be that of the nearest `package.json`. However if you were to run AVA from a different directory, with a relative `NODE_ICU_DATA` path, the path in the child processes will still be wrong.

In other words we still need to make the path absolute.
