### ISSUE TITLE
ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by LiTiang** [avajs/ava#963]
How can i use _AVA_ with _jQuery_ ? 
--------------------------------
In my case, 
i want to test a function which is in a file called **app.ts** (typescript file)
 
and i use `$.ajax` (_jQuery_ API) in that function,

so _AVA_ will want to ask me : what is the `$` meaning ?????

Note that, i want to keep unit test simple, clear, 

i use _jQuery_, but it is not meaning i also want to test _DOM_

NOW i just want to let _jQuery_ work in _AVA_

How can do that ?

**Comment by jamestalmage** [comment]
We don't have direct browser support yet.

There is a recipe for mocking the DOM [here](https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md). Some preliminary work on a browser solution via `karma` (https://github.com/avajs/ava/pull/942), and work on a full standalone browser test runner (https://github.com/avajs/ava/pull/887).

**Comment by LiTiang** [comment]
How to access `window` in test file ?
___________________________________

Hi, @jamestalmage , thanks reply

I read article for mocking the DOM which u present

but i have no idea how can i access `window` object in my _AVA_ test file ?

In _Node_, _jQuery_ need  `window` to initalize

like this `var $ = jQuery = require('jquery')(window); `

_AVA_ must know `$`, 
because it really execute that code, 
that meaning, i must declare `$` in test file, 
then run all test

**Comment by LiTiang** [comment]
ok, i solve it, 
i decide to use javascript instead of typescript,
it seems there is no need to use typescript in AVA now,
because i find the way to load typescript module directly in javascript

anyway, @jamestalmage  thanks again
