### ISSUE TITLE
Really esoteric node 0.10 strict mode pollution issue

### ISSUE THREAD

**Issue by forivall** [avajs/ava#964]
## Description

The version of v8 on node 0.10 suffers from a strict mode pollution bug, and I've ran into it while using ava. See the test source.

This doesn't happen if I directly require the file, either by requiring it at the top level of the request (which I don't want to do because I'm using mockery), or just from another source file like `'use strict'; require('./test/helpers/ava-bug')`. It also doesn't happen if I run ava with nyc.

I'm fine if this is closed, since it's really esoteric, and only affects 0.10.

### Test Source

https://gist.github.com/forivall/e78f320cc8b6452f7260c6d91d64568a

### Error Message & Stack Trace

```
» ava

   1 failed


   1. ava bug
   failed with "Illegal access to a strict mode caller function."
      Object.<anonymous> (helpers/ava-bug.js:5:9)
    extensions.(anonymous function) (/Users/jordanklassen/Code/ava-bug/node_modules/require-precompiled/index.js:16:3)
    Test.fn (ava-bug.test.js:5:3)
    handleMessage (child_process.js:322:10)
    Pipe.channel.onread (child_process.js:349:11)
```

## Environment

Node.js v0.10.43
darwin 15.5.0
ava 0.15.2
npm 3.10.5

**Comment by jamestalmage** [comment]
`0.10` exits LTS in two months. It would be imprudent for us to dedicate resources to tracking down why this is happening / how to fix it.

**Comment by forivall** [comment]
And yet, I have to deal with a vendor that still hasn't moved off of 0.10. I'm aware that 0.10 will leave support soon, which frustrates me that _vendor_ hasn't upgraded. No problem!

My workaround is to just do the require in a setTimeout to break the context:

`call-loose.js`
```
const Promise = require('bluebird');

module.exports = function (fn, arg) {
  return new Promise(function (resolve) {
    setTimeout(function () {
      resolve(fn(arg));
    }, 10);
  });
};
```

```
await callLoose(require, './helpers/ava-bug')
```
