### ISSUE TITLE
Failed to test Ajax with Sinon.js 

### ISSUE THREAD

**Issue by LiTiang** [avajs/ava#965]
#### Success to test Ajax example
* _Sinon_ + _jQuery_ + _Mocha_  :  http://codepen.io/anon/pen/Krkqyw?editors=1010

* _Sinon_ + _jQuery_ + _AVA_ : 
```javascript
test('test $.ajax', t => {
	var app = new App();
	var get = sinon.stub($, 'get');
	var fakeCallbackFunc = sinon.spy();

	get.yields(); 
 
    $.get('/users', {test: 'sinon_with_ava'}, fakeCallbackFunc);

	get.restore();

	t.deepEqual(fakeCallbackFunc.called, true, 
		"$.get callback havent been called"
	);
});
```

When i use `$.get` directly in test file, it work !!!!

but if `$.get` is in a file called : **app.ts**,
```typescript
// app.ts
export class Foo {
	justtest(callback:Function) {
		return $.ajax('/users', {test: 'sinon_with_ava'}, callback:Function);
	}
}
```

And i import it, call its function to execute `$.ajax`
then test will fail, and i have no idea why it is,
bug ? 

**NOTE**: i can import _typescript_ file directly in _javascript_ file by using 
package naming [**typescript-require**](https://www.npmjs.com/package/typescript-require)

**Comment by jamestalmage** [comment]
Please post a reproduction of the problem. You've posted code you tell us does work, but not an example of the code that does not. Specifically, what does your test look like that uses `app.ts`?

Also, please refer back to the [issue template](https://github.com/avajs/ava/blob/master/.github/issue_template.md), and provide anything relevant. Specifically your AVA config.

**Comment by LiTiang** [comment]
THX, i solve the prob, 

i still use **Typescript** + **jQuery** + **AVA** + **Sinon**
