### ISSUE TITLE
Test count in watch mode is incorrect

### ISSUE THREAD

**Issue by unional** [avajs/ava#973]
## Description

I'm running `ava` in watch mode and when I have a fail test and then fix it, the number of passed test is not correct:

![image](https://cloud.githubusercontent.com/assets/3254987/16971547/b33dc4cc-4dd9-11e6-87c6-34df01536c11.png)

If I stop the watch mode and run again, it runs correctly:
![image](https://cloud.githubusercontent.com/assets/3254987/16971566/c7e8fb30-4dd9-11e6-9715-94c976825a61.png)

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```sh
ava -w dist/**/*.spec.js
```

```
Node.js v4.4.7
darwin 14.5.0
ava 0.15.2
npm 3.10.5
```

**Comment by BarryThePenguin** [comment]
The [watch recipe](https://github.com/avajs/ava/blob/8edd9c2ed169909bf19a3f9229143d8fc87d5284/docs/recipes/watch-mode.md) goes into detail on watch mode.

In watch mode AVA only runs tests that have been modified. There is also an option to [manually rerun all tests](https://github.com/avajs/ava/blob/8edd9c2ed169909bf19a3f9229143d8fc87d5284/docs/recipes/watch-mode.md#manually-rerunning-all-tests)

**Comment by unional** [comment]
Thanks! Missed that sentence completely. 🌷
