### ISSUE TITLE
Show last run time in humanized format

### ISSUE THREAD

**Issue by tusharmath** [avajs/ava#976]
As of now (version 0.15.2) ava cli shows the last run time as follows —
`2 passed [14:00:46]`

Though useful, its not very clear unless someone keeps checking what the current time is and then match it with what's displayed. It would be great if it could say something like —
- `a few seconds ago`
- `a minute ago` 
- `5 minutes ago`

and so on.

**Comment by vdemedes** [comment]
I agree, something like `a minute ago` would be faster to understand when was the last run. Thanks for the suggestion, @tusharmath, let's see what other people think!

**Comment by novemberborn** [comment]
Wouldn't we have to continuously update the timestamp? (I assume this is to do with the watcher, right?)

**Comment by vdemedes** [comment]
@novemberborn Good point :)

**Comment by novemberborn** [comment]
I agree having a relative timestamp would be nice, but we'd have to keep it in sync which is a bit more work.

**Comment by tusharmath** [comment]
WE can simple put an interval for 5 seconds initially then then change it to minutes once the last run goes beyond 1 min and then 15 mins.

**Comment by vdemedes** [comment]
That would involve rewriting all the previous output, which is a nightmare.

**Comment by simonbuchan** [comment]
Is there any reason `ava --watch` leaves the previous errors up? This would be out of scope for this issue, but ideally it would re-write to show only the still failing tests, so if that was done then there is only one timestamp to worry about here.

**Comment by novemberborn** [comment]
@simonbuchan 

> Is there any reason ava --watch leaves the previous errors up? This would be out of scope for this issue, but ideally it would re-write to show only the still failing tests

The reporter buffer gets reset between test runs, so it can't clear earlier output. TBH I'm also not sure how terminals respond if you remove more lines than are currently displayed.

---

#939 implies a different approach to how we output logs, which could help with this feature request.

**Comment by novemberborn** [comment]
#939 is closed for now. Consequently I don't think we can make changes here anytime soon, so closing this as well.
