### ISSUE TITLE
Get export of regular tests from another file to work with async test.before()

### ISSUE THREAD

**Issue by DDChiang** [avajs/ava#977]
Something I've come across when trying to break my tests into different files (instead of having a long list of tests) is that the "test()" inside the exported file doesn't wait for the variables to resolve in the  "test.before()" from the first file.

What should I do to make sure that the tests will wait to run after the variables inside "test.before()" resolve, regardless of which file they're being called in?

**MainTest.js (Imports otherTests.js + tries to resolve the variables inside test.before()) :**

```
import {test} from 'ava';
import {otherTests} from './otherTests'; 
import {loadedDocument, loadedJson} from './asyncLoaders'; 

let document, json;

test.before(async t => {
    document = await loadedDocument(url); // async fetch stuff
    json = await loadedJson(jsonUrl); // async fetch stuff
});

// call tests from another file
otherTests(test, document, json);
```
**otherTests.js (File with tests to export):**

```
export function otherTests(test, document, json) {
   test('test document', t => {
       t.true(document.length > 0);   // results in "undefined"
   });

   test('test json', t => {
       t.true(json.length > 0);    // results in "undefined"
   })    
}
```

Could someone shed some light on what's happening and what's the correct way to "export" tests from another file for async situations?

**Solutions I've tried:** 
- running tests in serial (order)
```npm test -- --serial test/article/test-index.js```

- placing **test.before( );** to try to resolve variables again inside otherTests.js
```
export function otherTests(test, document, json) {
  let document, json;
 
  test.before(t=> {
      document = await document;
      json = await json;
  });

   test('test document', t => {
       t.true(document.length > 0);   // results in "undefined"
   });

   test('test json', t => {
       t.true(json.length > 0);    // results in "undefined"
   })    
}
```

**Comment by vdemedes** [comment]
Not sure I understand the goal of exporting tests and including them in another file. Couldn't you place your tests along with before hooks in `MainTest.js`?

**Comment by DDChiang** [comment]
The reason behind my goal of exporting tests and including them in another file is so I could start separating out the tests into different sections depending on what I'm testing("component behavior" vs "component rendering"). Right now, I'm stuck listing all the tests in one long file. I was hoping to be able to break them up into shorter sections.

**Comment by DDChiang** [comment]
@vdemedes Could you elaborate more on what you mean by **place your tests along with before hooks in MainTest.js**?

**Comment by vdemedes** [comment]
I meant place tests and hooks in the same file.

**Comment by DDChiang** [comment]
Ahh I see. But if you place the "before hook" into the same file as the test, then we can't use the values resolved asynchronously in the "before hook" for other tests inside other files. 

Perhaps I should have been more clear. I'm hoping to find a way to allow other test files(that will be exported) to use the resolved values returned from the same "before hook"

**Comment by novemberborn** [comment]
The before hook isn't executed until the tests start. In this example you're passing the undefined values:

```js
import {test} from 'ava';
import {otherTests} from './otherTests'; 
import {loadedDocument, loadedJson} from './asyncLoaders'; 

let document, json;

test.before(async t => {
    document = await loadedDocument(url); // async fetch stuff
    json = await loadedJson(jsonUrl); // async fetch stuff
});

// call tests from another file
otherTests(test, document, json);
```

You could do something like this:

```js
import {test} from 'ava';
import {otherTests} from './otherTests'; 
import {loadedDocument, loadedJson} from './asyncLoaders'; 

const documentPromise = loadedDocument(url);
const jsonPromise = loadedJson(jsonUrl);
let document, json;

test.before(async t => {
    [document, json] = await Promise.all([documentPromise, jsonPromise]);
});

otherTests(test, documentPromise, jsonPromise);
```

And in `otherTests()` repeat this bit:

```
let document, json;

test.before(async t => {
    [document, json] = await Promise.all([documentPromise, jsonPromise]);
});
```

Alternatively use `test.beforeEach()` and assign to `t.context`:

```js
import {test} from 'ava';
import {otherTests} from './otherTests'; 
import {loadedDocument, loadedJson} from './asyncLoaders'; 

let document, json;

test.before(async t => {
    document = await loadedDocument(url); // async fetch stuff
    json = await loadedJson(jsonUrl); // async fetch stuff
});

test.beforeEach(t => {
  Object.assign(t.context, { document, json });
});

otherTests(test);
```

Note that you don't necessarily need to pass `test` to `otherTests`. You can use `import test from 'ava'` in helper modules, they'll all get credited to the test file.

**Comment by DDChiang** [comment]
@vdemedes @novemberborn thanks for your input! I ended up using the solution with the "test.beforeEach" hook and Object.assign. Did exactly what I wanted it to do in assigning the resolved variables and allowing them to pass into the exported test. 

Thanks to you both for your help!
