### ISSUE TITLE
Plans to transpile the source to ES2015?

### ISSUE THREAD

**Issue by trixlerjs** [avajs/ava#978]
Plans to transpile the source to ES2015? Babel are already used as an dependency and also part of the core.

**Comment by sindresorhus** [comment]
Do you mean the source of AVA itself or the source of your tests?

**Comment by trixlerjs** [comment]
Ava itself. Es2015 standard now.

**Comment by sindresorhus** [comment]
No plans to do that. Creating a test runner is already hard and adding a layer of transpilation on top is not worth it. We'll adopt more ES2015 syntax when we can drop support for Node.js 0.10 and 0.12.
