### ISSUE TITLE
Ava ignores transform-object-rest-spread plugin

### ISSUE THREAD

**Issue by f0rmat1k** [avajs/ava#981]
## Description
Hello!
It's just not working, don't know why. Haven't any others babel settings.

### Test Source

```js
import test from 'ava';
import React from 'react';
import YBase from '../index.jsx';

test('Some', t => {
	t.pass();
});
```

### Error Message & Stack Trace

```
SyntaxError: index.jsx: Unexpected token (8:38)
>  8 | 		const {theme, className, type, url, ...rest} = this.props;
```

### Config

```json
{
"ava": {
    "require": "babel-register",
    "babel": {
      "presets": ["es2015", "react"],
      "plugins": [ "transform-object-rest-spread" ]
    }
  }
}
```

### Command-Line Arguments

```
ava test/test.js
```

## Environment
MacOS, nodejs 6.3.0, ava 0.15.2 installed locally.

**Comment by floatdrop** [comment]
@f0rmat1k `babel-register` will not pick up configuration from `ava.babel` in package.json. You should configure `babel-register` elsewhere. Read [Transpile sources](https://github.com/avajs/ava/blob/master/docs/recipes/babelrc.md#transpiling-sources) recipe for details.

**Comment by timwis** [comment]
I'm configuring in `.babelrc` and also experiencing this issue. My source compiles fine, but ava throws an error about not recognising `...foo()`.
