### ISSUE TITLE
t.throws() causes Node syntax error if first argument is function call with await arguments

### ISSUE THREAD

**Issue by nesukun** [avajs/ava#987]
## Description

I have a test that breaks after updating ava to version ~0.15.2 that works when using ava@0.14.0. This has been tested on node 6.3.1 and 4.2.4 amongst others. and seems related to a missing "use strict" after transpiling ES6 modules (wild guess there). I've looked at the commits between the two versions but haven't been able to identify what might cause the problem, but I haven't tested individual commits due to lack of time.
### Test Source, error message, and configuration

You can see the relevant files and error message here: https://gist.github.com/nesukun/f8cb2eef133548224d21bfd8a3ae5aa4

As a side note, using AVA's default babel config does not solve or alter the result. Hope you don't mind having everything in a gist, as I prepared that for the gitter channel before opening the issue.
## Environment

Tested mainly using the versions of node specified above under macOS 10.11.5 and inside the docker default node image

**Comment by vdemedes** [comment]
Let's see how test files look between different AVA versions:

1. switch to `0.14.0`
2. `rm -rf node_modules/.cache/ava`
3. `npm test -- test/server/core/crypto.js` (to test that specific file, that's causing trouble)
4. save the contents of `node_modules/.cache/ava/*.js` file in a gist
5. switch to latest AVA (`0.16.0`)
6. `rm -rf node_modules/.cache/ava`
7. `npm test -- test/server/core/crypto.js`
8. save the contents of `node_modules/.cache/ava/*.js` file in a gist
9. post the gists here

**Comment by nesukun** [comment]
Thanks for the response, here you have:
https://gist.github.com/nesukun/5798c1bf07848703ee57b2a459d41217/revisions?diff=split

**Comment by vdemedes** [comment]
Could you paste them without diff (as separate files/gists)?

**Comment by nesukun** [comment]
Sure

0.14.x https://gist.github.com/nesukun/5798c1bf07848703ee57b2a459d41217/cc0bd8906ed9e944ce3562cff384412fc8b1b2f7

0.16.x
https://gist.github.com/nesukun/5798c1bf07848703ee57b2a459d41217/b824ca833f581cceb0701511a15721a97823d4b0

**Comment by sotojuan** [comment]
@nesukun Sorry for the delay. Are you having the same issues in 0.16?

**Comment by nesukun** [comment]
Hi @sotojuan,
Yes, my lastest samples are using whichever where the lastest 0.14 and 0.16 versions when I made the comment. If you think it might have been resolved since then, or it could help you debug better, I could try again whith the current version.

**Comment by sotojuan** [comment]
Sorry, didn't see the 0.16.x! I'll investigate.

**Comment by novemberborn** [comment]
This is the [failing line](https://github.com/nesukun/mawpedia/blob/197e0bf0e5c170466f93128fa167fad76e2f2f4b/test/server/core/crypto.js#L21):

```js
t.throws(checkAgainst('4p455w0rd', await hash('4n0th3rp455w0rd')));
```

It's transpiled into:

```js
t.throws(_avaThrowsHelper(function () {
  return (0, _crypto.checkAgainst)('4p455w0rd', (yield (0, _crypto.hash)('4n0th3rp455w0rd')));
}, {
  line: 21,
  column: 11,
  source: 'checkAgainst(\'4p455w0rd\', await hash(\'4n0th3rp455w0rd\'))',
  filename: '/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.dkCnTDjWip/mawpedia/test/server/core/crypto.js'
}));
```

The function wrapper was introduced in #742. It breaks the `async`/`await` transpilation, since the `yield (0, _crypto.hash)('4n0th3rp455w0rd')` is no longer used in a generator function.

@nesukun the workaround would be to compute the hash outside the `t.throws()`:

```js
const targetHash = await hash('4n0th3rp455w0rd');
t.throws(checkAgainst('4p455w0rd', targetHash));
```

@jamestalmage this is a gnarly bug. I suppose the workaround would be to hoist any `await` statements out of the wrapper but that might be rather difficult.

**Comment by novemberborn** [comment]
@nesukun another potential workaround:

```js
const p = checkAgainst('4p455w0rd', await hash('4n0th3rp455w0rd'));
t.throws(p);
```

**Comment by nesukun** [comment]
Thanks for the investigation and response. I've stumbled with this issue in a few different proyects. Will surely follow your workaround recommendation until a more suitable solution is found. Have a great day!

**Comment by novemberborn** [comment]
I've tried to improve our throws helper but got stuck on another edge case. If anybody's interested in taking this on, the PR is at https://github.com/avajs/babel-plugin-ava-throws-helper/pull/6.

**Comment by novemberborn** [comment]
Fixed in https://github.com/avajs/ava/commit/d924045a8f2f6ecafb27ff86e10a4396a38a60d5.
