### ISSUE TITLE
devtool profiling fails with Uncaught Error

### ISSUE THREAD

**Issue by radiovisual** [avajs/ava#989]
## Description

When following the [profiling instructions in maintaining.md](https://github.com/avajs/ava/blob/master/maintaining.md#profiling):

```
$ devtool node_modules/ava/profile.js test.js
```

I get an Uncaught Error (see below). If it helps, I ran the profiler against the AVA tests in https://github.com/sindresorhus/generator-nm
### Error Message & Stack Trace

![image](https://cloud.githubusercontent.com/assets/5614571/17374559/1b5fa788-59a5-11e6-9639-499b2b5e8896.png)

Here is the text from the screenshot above:

<pre>
/usr/local/lib/node_modules/devtool/lib/require-hook.js:50 Uncaught Error: 
/Users/michael/forks/generator-nm/node_modules/ava/profile.js

/Users/michael/forks/generator-nm/node_modules/ava/lib/caching-precompiler.js

/Users/michael/forks/generator-nm/node_modules/ava/node_modules/convert-source-map/index.js
An error occurred while trying to read the map file at /Users/michael/forks/generator-nm/node_modules/ava/node_modules/convert-source-map/foo.js.map
Error: ENOENT: no such file or directory, open '/Users/michael/forks/generator-nm/node_modules/ava/node_modules/convert-source-map/foo.js.map'readFromFileMap @ /usr/local/lib/node_modules/devtool/node_modules/convert-source-map/index.js:32Converter @ /usr/local/lib/node_modules/devtool/node_modules/convert-source-map/index.js:39exports.fromMapFileComment @ /usr/local/lib/node_modules/devtool/node_modules/convert-source-map/index.js:112exports.fromMapFileSource @ /usr/local/lib/node_modules/devtool/node_modules/convert-source-map/index.js:131devtoolWrapModule @ /usr/local/lib/node_modules/devtool/lib/require-hook.js:75Module._compile @ module.js:509devtoolCompileModule @ /usr/local/lib/node_modules/devtool/lib/require-hook.js:32Module.load @ module.js:456tryModuleLoad @ module.js:415Module._load @ module.js:407Module.require @ module.js:466require @ internal/module.js:20(anonymous function) @ /Users/michael/forks/generator-nm/node_modules/ava/lib/caching-precompiler.js:4Module._compile @ module.js:541devtoolCompileModule @ /usr/local/lib/node_modules/devtool/lib/require-hook.js:32Module.load @ module.js:456tryModuleLoad @ module.js:415Module._load @ module.js:407Module.require @ module.js:466require @ internal/module.js:20(anonymous function) @ /Users/michael/forks/generator-nm/node_modules/ava/profile.js:15Module._compile @ module.js:541devtoolCompileModule @ /usr/local/lib/node_modules/devtool/lib/require-hook.js:32Module.load @ module.js:456tryModuleLoad @ module.js:415Module._load @ module.js:407Module.require @ module.js:466require @ internal/module.js:20(anonymous function) @ /usr/local/lib/node_modules/devtool/lib/preload.js:83emitOne @ events.js:96emit @ events.js:188
</pre>

## Environment

devtool@2.0.3
Node.js: `v4.4.4`
darwin: `14.5.0`
AVA: `0.15.2`
npm: `2.15.1`

(This issue is related to the archived issue #798)

**Comment by novemberborn** [comment]
Like #988, @avajs/core any ideas?

Is this something we should still include? Seems prone to breaking…

**Comment by sindresorhus** [comment]
@novemberborn It can be useful, especially until we do https://github.com/avajs/ava/pull/929. No idea why it's currently breaking though.

**Comment by sunny-g** [comment]
Possibly related to this? https://github.com/Jam3/devtool/issues/74

**Comment by novemberborn** [comment]
Could anybody confirm whether this is still an issue?
