### ISSUE TITLE
Weird timeout issue on Node v4

### ISSUE THREAD

**Issue by kripod** [avajs/ava#991]
According to the [Travis output](https://travis-ci.org/kripod/wsx/jobs/150280586) of my project, all of my ava tests pass, but on Node v4, it fails because of timeout, even though there are no more tests left to be performed. My Node v4 builds pass or fail at random due to this weird timeout behavior.

**Comment by sindresorhus** [comment]
It might just be that Node.js 4 is slower. Did you try increasing the timeout? To maybe 20s just to test.

**Comment by kripod** [comment]
I didn't try increasing the timeout, but it seems to me that 6 out of 6 tests have passed, just like in my v5 and v6 Travis builds.

**Comment by kripod** [comment]
Node v6 build output can be found [here](https://travis-ci.org/kripod/wsx/jobs/150280576). The amount of passed tests are the same.

**Comment by sindresorhus** [comment]
I would rather bet on some race issue in your test or code that causes `t.end()` not to be called in one of the tests. If `t.end()` is not called the test run will timeout.

**Comment by kripod** [comment]
I'm not sure that assertion planning will solve my issue. Especially because of the following quote from the readme:

> Note that, unlike `tap` and `tape`, AVA __does not__ automatically end a test when the planned assertion count is reached.

**Comment by sindresorhus** [comment]
@kripod It won't solve your issue, but it will help pinpoint where it is.

**Comment by kripod** [comment]
You were most probably right. After setting the test timeout to 30 seconds, my [Node v4 build](https://travis-ci.org/kripod/wsx/jobs/151231365) has passed, and it turns out that the `npm test` command ran for a total of 21.79s. One test could've taken too much time to be run on CI.

Thank you for helping me resolve this issue! :)
