### ISSUE TITLE
t.deepEqual says array deep equals keyed object

### ISSUE THREAD

**Issue by ngerritsen** [avajs/ava#992]
I had a bug in my application where an array got converted to an object with keys (by accident). In Javascript these are different things. This made our document store fail because it expected an array. My unit test did not detect this flaw.

It's about this assertion:

```
t.deepEqual(
  { 0: 'a', 1: 'b' },
  ['a', 'b']
);
```

I know that in some assertion libraries this fails (expect) and in some it does not (assert). I think it should fail.

Kind regards,

Niels

**Comment by sindresorhus** [comment]
Needs to be fixed in https://github.com/sotojuan/not-so-shallow.

// @sotojuan

**Comment by forresst** [comment]
This is fixed in version 0.1.4 not-so-shallow.

@sindresorhus Should we add additional tests for ava?

**Comment by sindresorhus** [comment]
@forresst Yes, useful in case we at some point change to another implementation.

**Comment by forresst** [comment]
I will do it

**Comment by forresst** [comment]
Done and number 1000 is for me !!!!! :tada: :smile_cat:

**Comment by ngerritsen** [comment]
@forresst But how does your test succeed now?

**Comment by forresst** [comment]
@ngerritsen `npm update` in your project
This will put the new version of not-so-shallow (0.1.4), used by AVA
