### ISSUE TITLE
Recipe for debugging AVA tests with WebStorm

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#998]
https://github.com/avajs/ava/pull/874 makes it possible. See  https://github.com/avajs/ava/pull/874#issuecomment-227298029 for how to use it.

-

Our current recipes: https://github.com/avajs/ava/tree/master/docs/recipes

**Comment by sindresorhus** [comment]
@develar Do you know anyone that could be interested in doing this?

**Comment by develar** [comment]
@prigara will do it next week.
